### ISSUE TITLE
Put all colour edit together

### ISSUE THREAD

**Issue by GrimPixel** [freeplane/freeplane#1004]
**Is your feature request related to a problem? Please describe.**
I found the background colour, then I saw the preview and want to change the font colour to make the text easy to recognise, then I close the window and find where I can edit text colour, then I need to readjust background colour. This doesn't feel convenient.

**Comment by dpolivaev** [comment]
Tell me a story. Record a video. Show me your pain. Otherwise, I can not understand why I should spend any effort in your ideas.

**Comment by GrimPixel** [comment]
Tell you what, I won't do that, switch to another product and won't recommend it and the problem's solved, as you tagged it wontfix.

**Comment by ldmpub** [comment]
Hi @GrimPixel,

Giving us here more details can lead to a solution and even an app improvement ; without any further information Freeplane community can not help you 😥.

**Comment by GrimPixel** [comment]
Ah, thanks. Let me install it back.

I would like to make its background colour darker, so I tried to find where it is. I thought there could be a dark mode, so I clicked on “View”, moved cursor to “View settings”. There was no dark mode. It was in “Format” -> “Map background” -> “Background color”. I changed the background colour to a dark one and saw the preview, found that the text colour needed to be changed. I found “Format” -> “Node core” -> “Node text color ...”, then it changed the text on the selected node only. I found “Text” under “Node color”, then I realised that I need to change the “Background” as well. The background of “Node color” doesn't fit the map background color. I tried to find “Map background” on the window and didn't find it, so needed to close this window, open that window, change it and repeat those steps, until I found a suitable combination of those three colours.

**Comment by ldmpub** [comment]
Ok I understand: you are complaining about too many **back and forth** to change color appearance of a freeplane map + node + text.

I agree with you that freeplane menus are sometime very strangely organized (for instance why "Search" is available under "Edit" menu??). What do you suggest to simplify your use case? Maybe adding a global colors panel containing all colors settings available for all freeplane objects in one place?

**Comment by dpolivaev** [comment]
I think you could use a template with dark mode either from the templates coming with the Freeplane or your own. Therefore you don't need to modify the colors often.

In addition to actions in the menu, you can use the formatting panel containing many formatting options.

<img width="389" alt="panel" src="https://user-images.githubusercontent.com/1558052/218335225-075ccc3d-0d10-49e8-aa84-f746566089ad.png">

**Comment by GrimPixel** [comment]
Thanks for your help. I get it. It requires some experience to find the solution: determine the background colour, then determine the text colour and node colour.
