### ISSUE TITLE
Wrong "what's new" version!

### ISSUE THREAD

**Issue by aadrian** [freeplane/freeplane#102]
When installing 1.6.x (e.g. with Chocolatey https://chocolatey.org/packages/FreePlane ), the first "welcome" screen is "What's new in Freeplane 1.5.x" :) .

This also seems the menu item in Help.

**Comment by dpolivaev** [comment]
You are right, nobody has developed a new welcome screen mind map for Freeplane 1.6.x.

Would you like to contribute it?

**Comment by aadrian** [comment]
> You are right, nobody has developed a new welcome screen 

Not the welcome screen is the problem but the "1.5.x" in the name, when the user downloads 1.6.x :) .

**Comment by dpolivaev** [comment]
Yes, we still have the old one because there is no newer one.

**Comment by aadrian** [comment]
> Yes, we still have the old one because there is no newer one.

Than just remove the number, and there will be no confusion :) .

**Comment by dpolivaev** [comment]
There is no confusion. I intentionally keep the number because new features of 1.6.x are not mentioned here.

**Comment by aadrian** [comment]
> There is no confusion. 

Not for you, since you created it :) .
