### ISSUE TITLE
Map Navigation: Command "Display note panel" prohibits proper map navigation

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#1020]
# Scenario
I want to display the note panel and be able to navigate the map at the same time.

# Problem
If you show the note panel with command "display note panel" Freeplane will move the cursor to the menu, instead of staying on the current node. So suddenly I am navigating the menu instead of the map :)

[Video](https://user-images.githubusercontent.com/10260832/221160571-f3d9c3ac-66f7-43c9-91d8-e44ea7e11cd7.mp4)

# Workaround
Manually selecting the node after using "display note panel"

# Version 
1.11.1-pre14

**Comment by dpolivaev** [comment]
Preview 1.11.1_16
