### ISSUE TITLE
Style "Selected node" not applied on nodes 

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#1021]
# Problem
Style "Selected node" has node shape set to ..
1. .. fork, but is not applied on map
2. .. parent, but is not applied on map

1.11.1-pre14

[Test Mindmap.zip](https://github.com/freeplane/freeplane/files/10842470/Test.Mindmap.zip)

[Video](https://user-images.githubusercontent.com/10260832/221170573-9c7b3310-b4d9-481f-a23b-65db98b48d99.mp4)

**Comment by dpolivaev** [comment]
In the attached example, style "selected node" does not override node shape. It is inherited from the default style.
Therefore it is not applied because only overridden properties of the selected node style are applied.
