### ISSUE TITLE
Map conditionals: Not fireing immediately when using scripts

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#1022]
This was working in earlier versions.... just saying :)

# Problem
The map conditionals are not being applied, when using scripts.

[Test Mindmap.zip](https://github.com/freeplane/freeplane/files/10842442/Test.Mindmap.zip)

[Video](https://user-images.githubusercontent.com/10260832/221174633-680ad61e-291b-47b2-be9c-97645ec34333.mp4)

# Workaround
Reloading map

**Comment by dpolivaev** [comment]
I fixed it. The fix can make the performance worse for some maps.

**Comment by dpolivaev** [comment]
Preview 1.11.1_16
