### ISSUE TITLE
Clean map: Summary node creates artifacts when filtering

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#1030]
# Problem

![See Video](https://user-images.githubusercontent.com/10260832/221513459-718e086c-a97d-4f78-ba53-1c0b72c5bf74.mp4)
[New Mindmap.zip](https://github.com/freeplane/freeplane/files/10837616/New.Mindmap.zip)

![image](https://user-images.githubusercontent.com/10260832/221513705-0ab4711b-8f09-40aa-8c36-9a1b2fdd3084.png)

**Comment by dpolivaev** [comment]
Preview 1.11.1_16
