### ISSUE TITLE
Add an env variable to easily override java

### ISSUE THREAD

**Issue by p-himik** [freeplane/freeplane#104]
Right now `freeplane.sh` checks a number of common environment variables that are used to specify the required JRE. It makes it rather hard to override JRE only for Freeplane. It would be great to have an additional top-priority variable like `FREEPLANE_JAVACMD`.

**Comment by eaglet3d** [comment]
I've set JAVA_HOME early in freeplane.sh to change the JRE.

If you don't like changing the script, you can launch the script with its
own environment by using parenthesis.

( export JAVA_HOME=/opt/java ; /opt/freeplane/freeplane.sh )

**Comment by p-himik** [comment]
Yes, these are all obvious solutions. The issue is that the distribution offers `.desktop` files that are integrated into the system. With the current approach, any way to change environment variables only for Freeplane either won't survive an update or will could cause other issues like duplicated menu entries.

**Comment by eaglet3d** [comment]
What if you set FREEPLANE_JAVA_HOME as per the instructions?

https://www.freeplane.org/wiki/index.php/Command-line_options_and_configuration

Kind regards,
Ralph

Ralph A. Navarro Jr.
*Navarro Computing LLC <https://navarrocomputing.com>*
Mobile: *+1(508)**287-0190*
AIM,YIM,Skype: eaglet3d

**Comment by p-himik** [comment]
I tried it, even though the wiki only mentions Windows and there's no usage of `FREEPLANE_JAVA_HOME` in the Freeplane source code. It didn't work.

**Comment by dpolivaev** [comment]
Hello, I like the suggestion. We shall add a check for  FREEPLANE_JAVA_HOME to freeplane.sh too.

**Comment by fnatter** [comment]
Done:
https://github.com/freeplane/freeplane/commit/ad8a38a108ec53bd41bd3b7e785d99c5eaecbec0
Wiki is updated:
https://www.freeplane.org/wiki/index.php/Command-line_options_and_configuration#Select_Java_installation_used_to_run_Freeplane

Cheers and Best Regards,
Felix
