### ISSUE TITLE
Summary nodes are always created from the top down to last selected.

### ISSUE THREAD

**Issue by DendrocoposMajor** [freeplane/freeplane#1044]
**Describe the bug**
Summary nodes are always created from the top down to last selected.
Meaning if nodes 2-4 out of 1-4 are selected and a summary node is added, 1 is always erroneously included.

**To Reproduce**
1. Create nodes 1-6
2. Select nodes 3-5
3. Add a summary node to selected nodes
4. See error.  Nodes 1 and 2 are included in summary node

**Expected behavior**
That only the selected nodes 3-5 are included in the summary node.

**Mind map files**
See attachments.

**Screenshots**
Screenshots added
**Desktop (please complete the following information):**
- - Edition	Windows 10 Enterprise
-- Version	21H2
-- Installed on	‎2021-‎10-‎25
-- OS build	19044.2604
-- Experience	Windows Feature Experience Pack 120.2212.4190.0

-- Freeplane: 1.11.1
-- Java 15.01
See also attached about dialogue for Freeplane and Java

**Additional context**
[Summary node error.zip](https://github.com/freeplane/freeplane/files/10920611/Summary.node.error.zip)
![Intention](https://user-images.githubusercontent.com/32731377/223713294-3dd54566-4674-40bd-b36d-306270349cce.jpg)
![Result](https://user-images.githubusercontent.com/32731377/223713301-fe54e251-d2d5-4876-9f6e-3e7aa905017b.jpg)

**Comment by dpolivaev** [comment]
Preview 1.11.1_17
