### ISSUE TITLE
Make the font size enterable

### ISSUE THREAD

**Issue by IArnaut2** [freeplane/freeplane#1045]
I want to change the size of the font in edit node dialog, but fonts are only limited to 8, 10, 12, 14, 18 and 24. Can you make it so that I can enter the custom font size?
![freeplane-font-size](https://user-images.githubusercontent.com/57326929/224145550-c3067527-f2bb-4b75-8e17-4e5fe47439d2.png)

**Comment by macmarrum** [comment]
I'm sure you know that you can put an arbitrary size for the whole node code, using the **Toolbar** or the **Tool panel**.

The HTML Editor is useful to set individual formatting for some text. Until your request is implemented, you can use a work-around for that. In the tab "HTML Code view", you can add CSS, like so:

![SimplyHTML-font_size_as_CSS-2023-03-10_16,45,54](https://user-images.githubusercontent.com/7197131/224361158-d9c238e0-0597-4610-93a6-8d2dfc8c55a3.png)

**Comment by dpolivaev** [comment]
Unfortunately, I could find no library which would generate HTML with CSS style attributes in the SPAN element. The way how it is implemented in Java makes no easy fix possible.
