### ISSUE TITLE
base64 encoded picture would suspend the node detail/note editor

### ISSUE THREAD

**Issue by living1069** [freeplane/freeplane#1046]
**Describe the bug**
When I insert a 136k base64-encoded picture, the whole application will be suspended.

**To Reproduce**
1. open a node detail editor
2. Click on 'HTML Code view'
3. Insert a img tag: `<img src=" data:image/png;base64,..." />`, where "..." is omitted because of github report limitation.

**Expected behavior**
The image could be displayed fluently.

**Desktop (please complete the following information):**
 - OS: windows
 - Version 10
 - Java Version: openjdk-17+35

**Comment by dpolivaev** [comment]
I am sorry I do not think I can fix it easily enough.
