### ISSUE TITLE
Tick handling for number input with leading zero should work different

### ISSUE THREAD

**Issue by joeUser555** [freeplane/freeplane#1047]
**Describe the bug**
You can enter numbers with leading zeors in freeplane by starting the input with a *'*.
The *'* ist stored in the xml.

**To Reproduce**
1. Create a new map
2. Enter *'0000* into the root node text field
3. Save the file
4. Open die file in a text editor
5. You can see the '*' in the xml file

**Expected behavior**
The *'* is only a marker for the GUI to perserve leading zeros in number input.
It must not be stored in the xml file.
The GUI must insert the *'* for editing if a text with leading zeros ist edited by the user.

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 22.04
 - Java Version 15

**Comment by dpolivaev** [comment]
By default, Freeplane tries to guess a type of content (text, number or date) to be used in comparisons.
If you want all nodes to be treated as text you can either start them with `'` or format them as `text`.
You can change it in your map styles and in your templates.

<img width="441" alt="coreTextFormat" src="https://user-images.githubusercontent.com/1558052/232061516-b2124bd6-16cb-49c8-a3a6-aaa223d48322.png">


Freeplane does not support local numbers and therefore it omits leading zeros.
If you have a need of using octal numbers, start a discussion and explain your reasons.

**Comment by macmarrum** [comment]
There's another way. I rarely use it, but it came up in a recent discussion, so I have it fresh in my memory: `Preferences…->Behaviour->Data formatting and parsing->Recognize input of numbers and date-time`. When turned off, any number entered in core text stays as text, including leading zeros, also when **Core text -> Format** is different than `Text`.

**Comment by joeUser555** [comment]
@macmarrum 
Thanx for this hint, it is a good work around or alternative.

**Comment by joeUser555** [comment]
@dpolivaev 
It seems to me you did not understand my point, did you ?
The problem is not the input interpretation of numbers and dates.
The problem is that the escape char '  is stored in the xml file thus confusing post processing xml transformation.
My point is to find a solution how to keep the escape semantic but getting rit of the escape char stored in the xml file.

**Comment by macmarrum** [comment]
@joeUser555

I like the solution provided by Dimitry. In my opinion, it will solve the issue presented at the beginning, i.e. how to enter a number with leading zeros `0000` in core text and have Freeplane retain it as is, also in .mm (xml). In particular, it will avoid the leading apostrophe `'`.

The way to do it is not to use the leading apostrophe `'` but instead to set **Core text -> Format** to `Text`.

I am guessing that what you also need is a way to convert your mindmap from leading-apostrophe to Format-Text. This can be done with the following script e.g. added to the root node and executed `Tools->Edit script…`

```groovy
node.find { it.text.startsWith("'") }.each {
    it.format = 'NO_FORMAT'
    it.text = it.text.drop(1)
}
```

**Comment by joeUser555** [comment]
@macmarrum 
Sorry, if I disagree.
The Problem in the beginning is the escape char ' is stored in the xml file.
To use the ' to inhibit input interpretation is a valid and feasible strategy.
It is used to trick out the intelligence of the GUI which is adequate.
But tricking the GUI must not effect the xml processes handling the saved file.
The XML file does not need to know the GUI was tricked to store a specific value.
If Freeplane needs a hint to correctly display a stored value it can write the necessary info to the XML file aside the stored value and keep the value in the XML file as the user would expect it.
The use of implementing filters to preprocess the XML is perhaps a working work around.
But the need of implementing filters is not intuitive to normal users.

**Conclusion**
The mentioined "solutions" are all good work arounds but no real solutions.

**Solution**
A real solution is only to prevent the escape char from being stored in the XML file.
In the current situation it is no problem that needs to be fixed urgently.
It can be implemented when other changes must be done on the XML file format.
So keep calm put it on the TODO list and do it if the time is ready for it.

May be when I find time to look at the source code, I will provide a patch.
