### ISSUE TITLE
Pressing ctrl+z shows incorrect layout icons

### ISSUE THREAD

**Issue by sifran-github** [freeplane/freeplane#1056]
**Describe the bug**
Pressing ctrl+z shows incorrect layout icons.

**Steps**
You should have a map with some nodes with specific layouts. Select a node, change its layout to auto, and then use ctrl+z.
See attached picture fore more info.

**Version**
 - Version freeplane_bin-1.11.1-pre12
![bug_layout_icons](https://user-images.githubusercontent.com/5730355/227739205-7d306a21-0a62-4c8e-95c5-03737987fcf6.png)

**Comment by dpolivaev** [comment]
Preview 1.11.1_22
