### ISSUE TITLE
Jump in & Jump out on folded nodes changes the map position

### ISSUE THREAD

**Issue by sifran-github** [freeplane/freeplane#1057]
**Describe the bug**
see title.

**To Reproduce**

1. choose a node which is folded.
2. jump in
3. jump out
4. the map has moved.

It only happen with folded nodes. Jumping in & out of other nodes works fine.

**Screenshots**
before:
![bug_1](https://user-images.githubusercontent.com/5730355/227740274-6649ae4e-7baa-4176-97fc-e7614eccbf03.png)
after jumping in and out:
![bug_2](https://user-images.githubusercontent.com/5730355/227740277-f714eff3-e4c0-4d86-8a16-ae1cd6263b60.png)

**Version**
freeplane-1.11.1-pre21

**map**
[bug_jumpin_position.zip](https://github.com/freeplane/freeplane/files/11070023/bug_jumpin_position.zip)

**Comment by sifran-github** [comment]
to quickly jump in & out, I use:
1. shift+esc
2. esc.

When you do this quickly on nodes that are folded vs nodes that are not folded, you can clearly see this bug.

**Comment by dpolivaev** [comment]
Preview 1.11.1_22

**Comment by sifran-github** [comment]
testd in Preview 1.11.1_22:
Actually this issue also exists when jumping in two levels of folded nodes.
even in the mindmap attached to this issue:

1. jump into the folded node
2. jump into the folded node that is inside
3. jump out
4. the map location has changed.

**Comment by sifran-github** [comment]
@dpolivaev  you addressed this bug as well in freeplane-1.11.1-pre23? looks like it behaves better.

**Comment by dpolivaev** [comment]
Preview 1.11.1_23
