### ISSUE TITLE
Jumping in & Out causes Freeplane to crash

### ISSUE THREAD

**Issue by sifran-github** [freeplane/freeplane#1059]
**Describe the bug**
Jumping in & Out causes Freeplane crash.
While trying to test bug https://github.com/freeplane/freeplane/issues/1057, i managed to crash Freeplane.

**To Reproduce, Screenshots**
1 - Select this node, jump in:
![image](https://user-images.githubusercontent.com/5730355/227741785-8af735ea-1f3c-4c3a-b484-c393212849d2.png)
2 - select this node, jump in:
![image](https://user-images.githubusercontent.com/5730355/227741801-efac137f-db6f-4ef9-9b01-13626bf66fbe.png)
3 - Jump out (esc). you can start to see an issue:
![image](https://user-images.githubusercontent.com/5730355/227741823-65f4fcfc-fefe-45d8-938c-8e3a1f874fbb.png)
4 - From the position of the last picture, Jump In (press shift+esc). You can see the node in the corner:
![image](https://user-images.githubusercontent.com/5730355/227741848-e2ce7801-63b3-4662-85f9-1d9bfe808112.png)
5 - Jump out (esc). Crash:
![image](https://user-images.githubusercontent.com/5730355/227741867-9df0cec2-5356-445b-8c44-ae7bf1b57878.png)

**Version**
freeplane-1.11.1-pre21

**Map**
The map is identical to the map from bug https://github.com/freeplane/freeplane/issues/1057 so go there to download it.

**Comment by dpolivaev** [comment]
Preview 1.11.1_22

**Comment by sifran-github** [comment]
This bug happen also in Preview 1.11.1_22.
Issue needs to be opened again, i think i that don't have permissions to reopen it.

**Comment by dpolivaev** [comment]
preview 1.11.1_23
