### ISSUE TITLE
Pressing unassigned shortcuts with F1-F12 keys always shows a dialog

### ISSUE THREAD

**Issue by p-himik** [freeplane/freeplane#106]
E.g. when I press `Ctrl+Shift+Alt+F12`, this dialog appears:
![image](https://user-images.githubusercontent.com/4410314/43757847-6c7da19c-9a44-11e8-8437-aff11a670f61.png)
It's very frustrating to see this dialog each time I press use that shortcut since the shortcut is global and is bound in another program that I use rather often.

I think this behavior should be either disabled completely (since non-F shortcuts do not cause the dialog to appear) or made optional.

**Comment by dpolivaev** [comment]
Improved in 1.7.1_02
