### ISSUE TITLE
Script-filter conditional styles cause large memory consumption

### ISSUE THREAD

**Issue by abc16361** [freeplane/freeplane#1060]
**Describe the bug**

One of my maps uses script filter conditional styles and runs smoothly on fp-1.11.1-pre14, but on versions from pre16 to pre22, editing like typing and adding nodes would cause large memory consumption (~40% cpu). If the script filter conditional styles are disable, large memory consumption would not happen. On fp-1.11.1-pre14, editing just triggers a brief increase of memory concuption up to 20% and quickly dropping back to zero.

**To Reproduce**
1. Typing node text, or
2. Adding a new node
3. check cpu consumption on Windows Task Manager

**Mind map files**
[ZtdM_1.zip](https://github.com/freeplane/freeplane/files/11072422/ZtdM_1.zip)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version fp-1.11.1-pre16~22
 - Java Version: zulu17.40.19-ca-jre17.0.6-win_x64.msi

**Comment by dpolivaev** [comment]
preview 1.11.1_23
