### ISSUE TITLE
Strange Map Position (When Opening + Using Esc)

### ISSUE THREAD

**Issue by sifran-github** [freeplane/freeplane#1061]
**Describe the bug**
The latest pre versions (tested on pre22+pre23 but not sure which version started it) introduced a strange issue with map positioning:
1. Some maps open up in a strange position, not centered.
2. Also when pressing esc, it jumps to root but moves the map to a strange position.

I might be related to https://github.com/freeplane/freeplane/issues/1057 but i'm not sure, thats why i opened a new issue.

**To Reproduce**

- just open the map...
- or... select a different node and just press esc to jump to root...

**Expected behavior**
The root should be in the center... it shouldn't jump to the side.

**Mind map files**
https://github.com/freeplane/freeplane/files/10677064/test_new_version_v2.zip

**Screenshots**
![image](https://user-images.githubusercontent.com/5730355/227799804-2c1b8971-dac0-47a6-9d0a-1e0b8518148f.png)

**Version**
freeplane-1.11.1-pre22 and freeplane-1.11.1-pre23 for sure.
maybe also previous pre versions.

**Comment by dpolivaev** [comment]
I fixed it. I am not going to create the new preview version right now because you might find other issues.

**Comment by dpolivaev** [comment]
Preview 1.11.1_24
