### ISSUE TITLE
Freeplane 1.10.6 stops won't accept keyboard input

### ISSUE THREAD

**Issue by designasaurus** [freeplane/freeplane#1069]
When I have more than one map open, the program will randomly stop accepting keyboard entry. I have to completely shutdown and restart the program to return functionality. Using LXDE with Compiz, if that matters.
Don't think it happens when only one map is open. Maps are small.  I believe this also affected the previous version of Freeplane.

**Describe the bug**
Freeplane will randomly stop accepting keyboard entry

**To Reproduce**
1. Open more than one map at a time
2. Wait. Not sure what the trigger is.

**Expected behavior**
program will randomly stop accepting keyboard entry

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.
Was typing "What you really need is for Inkscape to ou" , when it stopped taking input.

**Screenshots**

**Desktop (please complete the following information):**
 - Linux 5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)

**Additional context**
[kivy.zip](https://github.com/freeplane/freeplane/files/11115567/kivy.zip)

**Comment by dpolivaev** [comment]
I don't think it is a Freeplane specific issue.
Please check if the description and recommendations given in https://youtrack.jetbrains.com/issue/IDEA-78860/Keyboard-input-sometimes-is-blocked-when-IBus-is-active can explain and fix it for you.

**Comment by amariusz** [comment]
I have the same issue.
My OS (Linux Debian) has IBus 1.5.29.
It only happens in FreePlane. That said, PyCharm sometimes have similar issue, but changing focus to another window and back fixes it. Freeplane needs to be restarted.

**Comment by amariusz** [comment]
I've found more recent thread

https://youtrack.jetbrains.com/issue/JBR-6456/Sudden-keyboard-death-on-Linux-using-iBus

I'll try `ibus-daemon -rd` / `ibus restart` / `pkill ibus` next time it happens. Those seem to work for some people as a workaround.

**Comment by AlexandreBonneau** [comment]
I experience the same problem with Debian 12, and much more frequently since switching to 1.12.x (compared to 1.11.x).
Following @amariusz advice, I tried running `ibus restart`, and indeed that workaround fixes the keyboard input not being correctly understood by Freeplane.
Do note that when that happens, _only_ freeplane is affected in the whole desktop. The keys are correctly entered in Qt applications, Gtk applications, Firefox, Chrome, Blender, etc.
So it seems to me that since only Freeplane seems to be affected, maybe this ticket could be opened again and maybe we could try to find why this happens and fix it?

**Comment by amariusz** [comment]
I use `ibus-daemon -rd` every now and then. In my environment, three apps—Freeplane, Yed, and Pycharm—happen to experience this input issue. It occurs maybe once a week on average. As a workaround, a global hotkey running a bash script with this command works fine for me. It’s probably not directly related to Freeplane and is probably hard to investigate IMO.

**Comment by dpolivaev** [comment]
Try to use the latest Jetbrains java runtime together with the latest Freeplane preview 1.12.8_02.

You can download jetbrains java runtime at https://github.com/JetBrains/JetBrainsRuntime/releases, try JBR (vanilla) or JBRSDK for your platform, I think you do not need other packages.

**Comment by dpolivaev** [comment]
And please write here if it fixes the problem.
