### ISSUE TITLE
v11 cloud is offset

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#1072]
In v1.11.1-pre23, Cloud is offset, as compared to v1.10.7

![bug-v11-cloud-is-offset-v1 11 1-pre23](https://user-images.githubusercontent.com/7197131/229198524-9f4c5066-03ea-43fc-b3b0-c65cebf4fe29.png)

![bug-v11-cloud-is-offset-v1 10 7](https://user-images.githubusercontent.com/7197131/229198540-6e29d2ee-e68c-475e-98ee-5a3503357f1d.png)

[bug-v11-cloud-is-offset.mm.zip](https://github.com/freeplane/freeplane/files/11124778/bug-v11-cloud-is-offset.mm.zip)

**Comment by dpolivaev** [comment]
Preview 1.11.1_26
