### ISSUE TITLE
LAST_CHILD_BY_PARENT fails to mirror FIRST_CHILD_BY_PARENT

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#1076]
LAST_CHILD_BY_PARENT fails to mirror FIRST_CHILD_BY_PARENT https://github.com/freeplane/freeplane/discussions/1074#discussioncomment-5503682

**Node 3** and **node 4** should be at the same level as **root**.

![bug-v11-ChildNodesLayout-position-not-respected-LAST_CHILD_BY_PARENT-fails-to-mirror-FCBP](https://user-images.githubusercontent.com/7197131/229580249-84623c1b-8869-46cb-a8fc-f83bef201ff6.png)

[bug-v11-ChildNodesLayout-position-not-respected-LCBP.mm.zip](https://github.com/freeplane/freeplane/files/11140750/bug-v11-ChildNodesLayout-position-not-respected-LCBP.mm.zip)

**Comment by sifran-github** [comment]
I think this is a specific case of the bug that I posted and tried to generalize here: https://github.com/freeplane/freeplane/issues/1075
There are many issues with many layout combinations that are pushing nodes to odd positioning, including this one.

**Comment by dpolivaev** [comment]
Even if I know that you appreciate my work,
even if I know that you must have only best possible intentions,

I don't particularly appreciate reading words like "weird", "odd", and even "wrong" in any relation to my work and Freeplane behavior.

Please consider my feelings when you formulate your comments.

**Comment by dpolivaev** [comment]
One possible way to express your concerns could be

"I expect A but I see B"

**Comment by sifran-github** [comment]
?
I did not mean to offend or anything like it.

Yes i do appreciate your work! very much! and I told you many times.

Its just a bug description, nothing personal. I will try to describe it better but I'm still not sure why these words are problematic when describing a technical bug, which by definition is an unintended behavior of a software.

I'm writing it in a purely technical intention.

**Comment by dpolivaev** [comment]
Even if I know that you want to be respectful, I would highly appreciate it if you use a description like "I expect A but I see B" instead of any judgemental expressions.

**Comment by sifran-github** [comment]
OK

**Comment by sifran-github** [comment]
(deleted previous comments, left only this one)

I think this is a specific case of the bug that I posted and tried to generalize here: https://github.com/freeplane/freeplane/issues/1075

**Comment by dpolivaev** [comment]
Preview 1.11.1_29

**Comment by macmarrum** [comment]
Looks good :+1: 
Many thanks :bow:
