### ISSUE TITLE
Support transparent backgrounds for printing and exports

### ISSUE THREAD

**Issue by benzen3** [freeplane/freeplane#1077]
I keep trying to set Background Color's Transparency to 100% but it doesn't work. 

Steps:
1) Open a Map, right click on an empty space.
2) Click on Background color.
3) Click on either HSV or HSL.
4) Turn up Transparency to 100%. 
5) Save and export.

I've already disabled Preferences -> Appearance --> Colors -> White background for printing. 
What am I missing?

OS: Windows 10
Freeplane: v 1.10.6
Java: Not installed (java -version from cmd says command not found)

**Comment by dpolivaev** [comment]
I am afraid transparent backgrounds are currently not supported. I think I should introduce it for export.

**Comment by benzen3** [comment]
> I am afraid transparent backgrounds are currently not supported. I think I should introduce it for export.

Thanks for replying.  It would be great if you did, watermarking proprietary content would become much easier. 

For the benefit of posterity, there is a workaround which is seems to do alright for my purposes:

1) In Freeplane, export your mindmap as SVG

2) (Download and install Inkscape if you don't have it already)
--> Open SVG file in Inkscape. In the list of layers shown on the right, delete or turn off visibility for the last layer at the very bottom. 
--> If you want to watermark, go to top left File --> Import to import the watermark file of your choice. In the list of layers, drag down your newly imported image to the very bottom. 

3) Go to File -- > Export in Inkscape to export as a PDF (or other format of your choice)

**Comment by dpolivaev** [comment]
I reworked translucent backgrounds and do not print background if Preferences -> Appearance --> Colors -> White background for printing is set. (It is renamed to "transparent background...")

Preview 1.12.2_14
