### ISSUE TITLE
in 1.11.1-pre28: (Page Up) & (Page Down) keys to move to first and last sibling node DO NOT work

### ISSUE THREAD

**Issue by Bricklam** [freeplane/freeplane#1078]
in the newest version: when I navigate to 
Installing (Freeplane 1.11.1-pre28) on Java application: (zulu17.40.19-ca-jdk17.0.6-win_x64.msi): it works
but when I press (Page Up) or (Page Down) keys to move to the first or the last sibling node, it doesn't work
these keyboard shortcuts are essential part of Freeplane and they used to work through all previous Freeplane versions

**Comment by sifran-github** [comment]
I confirm as well, PageUp and PageDown do not change the selected node.

But a question arises: how should the program handle these keys on a horizontal layouts?
For example, you are here (node "LLL"), and you press Page Up or Page down. Where should the selection go?
![image](https://user-images.githubusercontent.com/5730355/230204208-9d0eedf9-d033-4528-ac20-099674bba0a3.png)

Should these keys behave by FUNCTION (select the first/last siblings which are now on the left and right sides of the selected node) or by DIRECTION (sticks to up and down)? (read the discussion below to understand more).

I have made a discussion about using the arrow keys here: https://github.com/freeplane/freeplane/discussions/989, but i support the idea that these keys should also be addressed.

**Comment by EdoFro** [comment]
@sifran-github,
I think this is currently a bug. 
"How should it work with the new layouts?" should be a new thread in the discussion forum. Until there is no new decision, it's a bug.
In my opinion, here is not the place to discuss it in order to not dirty the bug report.

jm2c

edo

**Comment by sifran-github** [comment]
@EdoFro OK. Created a discussion https://github.com/freeplane/freeplane/discussions/1081

**Comment by dpolivaev** [comment]
Preview 1.11.1_29
