### ISSUE TITLE
Frequent crashing

### ISSUE THREAD

**Issue by miloofcroton** [freeplane/freeplane#108]
Hi guys,

I'm a big time Freeplane user. My main map is 76MB. I'm using Ubuntu 18.04, Freeplane 1.6.13, and Java openjdk version 10.0.2. Let me know if you want any logs information or anything else from me.

I can reliably reproduce this freezing issue if I go too long without saving, it seems. If I keep saving, especially after opening new sections of the map, it will keep going. If I don't, I get freezing whenever I try to open a new node and start typing.

**Comment by dpolivaev** [comment]
This issue is known since months.
Check https://sourceforge.net/p/freeplane/bugs/2591/ for more info.

**Comment by miloofcroton** [comment]
Cheers. I installed Oracle Java 8, and the issue went away. :+1:
