### ISSUE TITLE
in (1.11.X): the screen doesn't move vertically along with nodes selected by the keyboard

### ISSUE THREAD

**Issue by Bricklam** [freeplane/freeplane#1080]
I found this bug / bad behaviour in version (1.10.X) and in (1.11.X), but it wasn't present in (1.9.X)
when I have a long list of sibling nodes, and starting selecting nodes from the top of the list downward, using/holding
the keyboard shortcut: (Shift+Arrow Down), this bug appears:
 when the selection reaches the bottom border of the screen, the screen doesn't move/scroll down automatically, to move along with the selected nodes (as it used to happen in previous versions).
 Instead, the screen is fixed and I have to scroll down manually to see where the selection has stopped.

I couldn't find any option to change this behaviour. So, I think it is a bug

Thanks

**Comment by dpolivaev** [comment]
Preview 1.11.1_29
