### ISSUE TITLE
LEFTTORIGHT_any_LEFT places new children on the right

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#1084]
![LEFTTORIGHT_any_LEFT-places-new-children-on-the-right](https://user-images.githubusercontent.com/7197131/230736568-a80eaa02-79ef-4881-9587-d9cb7b8d2890.png)

**Comment by macmarrum** [comment]
[LEFTTORIGHT_any_LEFT-places-new-children-on-the-right.mm.zip](https://github.com/freeplane/freeplane/files/11183913/LEFTTORIGHT_any_LEFT-places-new-children-on-the-right.mm.zip)

**Comment by dpolivaev** [comment]
I don't see any wrong behavior.
The nodes are placed at some distance to to the left of the right edge. It works as planned by me.
The reason is that the nodes are quite wide and moving child nodes to the left edge seems to be not efficient use of the space.

What do you expect?

**Comment by macmarrum** [comment]
Ah, yes. Of course. I can see the nodes are still to the left of their parent (the parent's right edge).

I was confused about the placement of new nodes, i.e. that they appear on the right of the existing nodes. I need to get used to the idea of left-to-right node's increments :smile: 

Not a bug. Closing.
