### ISSUE TITLE
in 1.11.1-pre29: cannot reduce the margin for nodes with (fork) shape 

### ISSUE THREAD

**Issue by Bricklam** [freeplane/freeplane#1088]
in 1.11.1-pre29: 
when the default node shape is (Fork), some (node shape) properties: (horizontal margin and vertical margin fields) cannot be edited, wether in the properties panel or in the style manager (their editing is disabled)
![Capture1](https://user-images.githubusercontent.com/129968602/230857766-aff33b99-21aa-4669-85cf-b625ee748ccb.PNG)

the problem is: I need to reduce the margins to (zero), because in (1.11.1-pre29):
the distance between sibling nodes get bigger than it should (when they are unfolded if every node has a single child),
here is an example: when the sibling nodes are folded (the vertical distance (margin) is very little:
![Capture2](https://user-images.githubusercontent.com/129968602/230858727-5c53eb4e-3dce-4820-9420-a903570177cb.PNG)

but the problem appears when the nodes are unfolded, the vertical distance/margin increases more than I want, and there is no way
to fix this:
![Capture3](https://user-images.githubusercontent.com/129968602/230859868-bd9de882-7999-4979-81e7-478ab8f5971e.PNG)

I prefer when I have a long list of sibling nodes, to be able to see as much nodes as possible within the screen view,
so, I don't want any wasted vertical margin/distance between nodes

another relevant point that might help reduce the distance between nodes:
I suggest (for fork nodes with single children) to make the single child on the same level of the parent node, instead of raising it up
when every level unfolded: (or it can be raised very slightly, since I can seee the point behind this raising children: to make it easier to see the borders between parent and child nodes,)
![Capture4](https://user-images.githubusercontent.com/129968602/230862798-c0c7398c-1983-4a1d-8336-3f4e0c208aaf.PNG)

thanks

**Comment by Bricklam** [comment]
this in an edited image, to clarify a little bit the idea of the suggested layout change with zero margins/paddings: between nodes (vertically/horizontally)
 to (remove all unnecessary spaces, cramming nodes above each others):
![Untitled555](https://user-images.githubusercontent.com/129968602/231674552-cf0e2d13-83d9-4041-b786-fae37a3c3efc.png)

**Comment by dpolivaev** [comment]
It is not a bug. If you have nodes with "fork" shapes with only one child node, it is slightly moved up so that you can easily see that the nodes are different. This shift is not applied for other shapes or if there is more than one child.

**Comment by Bricklam** [comment]
I understand why there single child is moved up. 
but the main problem is that the (horizontal margin and vertical margin options are disabled), in the first image above,
you can see that they cannot be edited (covered by gray background), but they are only activated if I changed the node shape
from (Fork) to another shape.
this is my point: why they are disabled in (Fork)?  since I want to reduce them to the least possible value
thanks

**Comment by dpolivaev** [comment]
They are already effectively zero for the shape "fork". They are only relevant if there is a shape like a bubble drawn around.
