### ISSUE TITLE
Splittable View Pane - See more than one map on the screen an one time

### ISSUE THREAD

**Issue by joeUser555** [freeplane/freeplane#1098]
**Current State**
Freeplane displays only one map at a time in the view pane.

**Wanted Behavior**
If you work with several map simultaneously 
you sometimes want to see two or more maps on the screen 
at the same time(without need to switch).

**Solution**
This could be achieved if the tab folder row would be splitable.
Notepadd++/nqq is an example for that what's my intention.

**Comment by macmarrum** [comment]
Once you have more than one tab, you can drag-and-drop a tab to the edge and it will split your view pane.
You can also have two views of the same mindmap: `View->New map view`

**Comment by joeUser555** [comment]
@macmarrum 
Thanx for the info.

**Comment by EdoFro** [comment]
this can be closed
