### ISSUE TITLE
in (1.11.1-pre29) the node width doesn't fit included text / bigger than the the text, leaving empty space in the node

### ISSUE THREAD

**Issue by Bricklam** [freeplane/freeplane#1107]
although the minimum node width is 0 (the default value), the node width increases than it should, wasting some space in the right (when adding long text that get wrapped through multiple lines, with or without line break character), this happens to all nodes regardles of their shapes (fork or bubble).
here is an example:
![bug](https://user-images.githubusercontent.com/129968602/233793818-d2ab2953-7188-46ec-a7f9-19cb75c26824.png)

I wonder why moving to (1.11.X) has brought multiple bugs, in (the Map View) part

Thanks

**Comment by dpolivaev** [comment]
Nothing has changed here.

For nodes with line breaks, Freeplane does not guarantee optimal width. The renderer uses javax.swing.plaf.basic.BasicHTML and HTML renderers, and they are not perfect at required width estimation.

**Comment by dpolivaev** [comment]
If you have content example which behaves differently on different freeplane versions please submit it here and I'll have a closer look.

**Comment by Bricklam** [comment]
Yes I understand. it is a not a big problem at all, it doesn't affect anything.
the reason I submited it as a bug report because: I don't remember seeing this behaviour in older versions, that is why I thought it might be a new bug. maybe I didn't notice it clearly back then. but now I can see it clearly, because sometimes the empty margin is clearly visible, like this example:

![node2](https://user-images.githubusercontent.com/129968602/233795124-f69803ec-93d3-4b6a-bfa6-8877b82d314a.png)

but anyway. it doesn't affect anything.
Thanks for your dedicated work and efforts to develop and maintain this great software
