### ISSUE TITLE
Trojan found in Freeplane-Setup-1.10.6u1.exe

### ISSUE THREAD

**Issue by Vax1969** [freeplane/freeplane#1113]
**Describe the bug**
Trojan "Trojan.Siggen20.37321" found in Freeplane-Setup-1.10.6u1.exe

**To Reproduce**
Analyse the exe file with https://www.virustotal.com

**Expected behavior**
No Trojan found in the original source file

**Screenshots**
<img width="1217" alt="Capture d’écran 2023-04-26 à 14 31 21" src="https://user-images.githubusercontent.com/60626425/234575829-0fb61075-fc62-465a-b643-eed1d785a161.png">

**Desktop (please complete the following information):**
 - OS: W10

**Additional context**
Profesionnal

**Comment by dpolivaev** [comment]
I think it might be a false positive. If only one checker finds something suspicious, it might be wrong itself.
