### ISSUE TITLE
suggestion :  command search : match filter checkboxes with order of items found

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1116]
I love command search.  I wish every app had this functionality.

But it seems a bit out of synch when the filter checkboxes are in one order (Menu items | Icons | Preferences  while the order of items found is in another order (Preferenced | Menu items | icons).

It is nothing major but it causes a mental disconnect for me.

![command search _  improve with order of filters , choices](https://user-images.githubusercontent.com/6380301/234982913-6ec6e703-7192-4ede-8c9a-22e73a12b148.jpg)

**Comment by blcham** [comment]
Agree, unless there is some serious rationale why it was done like that.

**Comment by dpolivaev** [comment]
preview 1.11.1_31
