### ISSUE TITLE
command search .  allows for multiple command search dialog windows

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1118]
issue :  FP allows multiple command search dialog windows to open.
- if this is as designed, sorry for submitting here.  If so, can it be transferred to feature requests?

to reproduce :
1. open command search dialog window 
2. click in the map 
3. ctrl+f1 : a new, additional command search dialog opens.
4. repeating steps 2-3 will open additional command search windows (see screenshot)

Expected behavior :
- I expect that only 1 command search dialog window should open per map.

Desktop :
 - OS: Windows 11  Home
 - Version: 22H2
 - Java Version: 17 0 7

screenshot : 
![multiple command search windows open](https://user-images.githubusercontent.com/6380301/235362281-e50fd5d0-d5af-4239-b0c0-becaafbf645e.jpg)

**Comment by dpolivaev** [comment]
Why is it an issue?

**Comment by kenfhill84083** [comment]
For me it is an issue because 
- screen real estate is so valuable for the map 
- especially since I cannot see any utility for it

Since you push me to further analyze this, I can now imagine someone wanting to apply multiple formatting, etc aspects without having to swap between search strings in a single dialog.  Multiple windows could help them experiment more easily.  And you can put the dialogs on another monitor if you have one.

I withdraw my bug report.  Can I delete it?  Thanks.

**Comment by dpolivaev** [comment]
Freeplane 1.11.2
