### ISSUE TITLE
missing key AutomaticLayout.level,2 | Conditional styles error

### ISSUE THREAD

**Issue by remghoost** [freeplane/freeplane#1119]
**Describe the bug**

When attempting to create a conditional style that checks for the Parent's Style Level then saving and reloading the file, it produces an error when opening that file. It seems to be a problem with how it's _saving_, as the condition works perfectly fine if the file stays open. It's only on saving and reloading that the error occurs.

At first I thought it was just with Level 2, but Level 3 produces the error as well (and I'm assuming that other levels would produce the error as well). The Root level seems to work fine.

Also, the condition changes upon reloading the file. 

It goes from
`Parent's Style 'Level 2'`
to
`Parent's Style '[AutomaticLayout.level,2]'`

Poking through the code, it seems like that reference is sound (though, I only know small amounts of Python and C# code, so I may be missing something).

Also, upon editing the `.mm` file to read:
`<style_equals_condition LOCALIZED_TEXT="Level 2"/>`
instead of:
`<style_equals_condition LOCALIZED_TEXT="AutomaticLayout.level,2"/>`

still produces the error. And checking the conditional styles shows that it reads:
`Parent's Style '[Level 2]'` instead of `Parent's Style 'Level 2'` as is created when the conditional style is made before saving and loading. Note the extra brackets.

-=-=-=-=-=-=-=-=-=-

**To Reproduce**
1. Create a conditional style for map that includes a condition that checks for the parent's style level.
2. Save and reload the file.

**Mind map files**
Here is the file I am working with that is producing the error.
[Game Story Flowchart.zip](https://github.com/freeplane/freeplane/files/11363983/Game.Story.Flowchart.zip)

My apologies, there are a few other conditions in there. I was attempting to reproduce the bug with different style levels.

**Screenshots**
<img width="368" alt="Screenshot 2023-04-30 233850" src="https://user-images.githubusercontent.com/34994940/235417892-ff5234ef-3cf4-452b-ae6a-dd7ddb8c46a7.png">

The screenshot below shows what is expected and what is created when reloading the file.
The top line shows what happens upon reloading the file.
The bottom line shows what a freshly created `Parent's Style 'Level 2'` looks like.
<img width="493" alt="Screenshot 2023-04-30 234057" src="https://user-images.githubusercontent.com/34994940/235417893-69768a44-78f2-41d8-a325-2e3e7ec52049.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.10.6 and 1.11.1
 - Java Version

**Additional Information**
This also seems to cause a crash if this error is left unchecked in a file for longer than about a half hour or so.

I'll poke around a bit more and see if I can figure out why it's doing this, but my programming knowledge is rather limited. I've just recently (in the past 6 months or so) started learning Python for machine learning purposes. Java is a bit foreign to me, though relatively similar to Python in syntax.

Also, I saw a comment from 2009 in one of the files.... Have you been working on this project for _14 years_...? That's incredible. **Mad props to you.** The world needs more people like you.

**Comment by dpolivaev** [comment]
Thank you for your words of appreciation and for the high quality of your bug report, I enjoyed reading it a lot.

**Comment by dpolivaev** [comment]
Fixed in Preview 1.11.1_32

**Comment by remghoost** [comment]
Thank you so much for the fix!
It works flawlessly.

Ah, the problem was in `StyleTranslatedObject.java`. I had that open in VSCode but I wasn't sure how it was causing an error.

I thinking it was in the `AutomaticLayoutController.java` on line 73, but I wasn't sure why or how...

https://github.com/freeplane/freeplane/blob/d1bc2857a5c23cbc30988b461a39a3372dd025ec/freeplane/src/main/java/org/freeplane/features/styles/AutomaticLayoutController.java#L71-L81

Anyways, I'm glad it was an easy fix.
Thanks again!
