### ISSUE TITLE
Conditional styles do not update recursively

### ISSUE THREAD

**Issue by remghoost** [freeplane/freeplane#1120]
I believe this is a bug, but it **could be my misunderstanding of how conditional styles for a map works.**

I will include a screenshot at the top to illustrate my goal and what I believe to be the bug.

I am attempting to keep Level 2 going indefinitely with this conditional list.
![Screenshot 2023-05-01 053958](https://user-images.githubusercontent.com/34994940/235452820-4f1ea7e5-0f42-4311-8a1f-f6eddfea70eb.png)

Yet with this condition list, I get this output.
The first bubble directly after a new Level 2 behaves correctly and is also assigned Level 2, but the bubble marked with the red arrow is incorrectly assigned. It appears as Level 4 when it should also be Level 2.
![Untitled-1](https://user-images.githubusercontent.com/34994940/235453890-fd961ece-d94e-4209-9d3e-75e90eba8f7c.png)

**I figured this might just be my misunderstanding, but when I manually switch the second Level 2 bubble to another level then back to Level 2, the bubble updates correctly.**

-=-=-=-=-=-=-=-

I believe this is caused by conditional styles not updating the `Format > Style` list correctly.

If you look at this screenshot, you can see that the conditional style I have applied _does not update in the Format menu_.
![Screenshot 2023-05-01 055810](https://user-images.githubusercontent.com/34994940/235454825-f983399c-0175-4ab1-9e91-807b0408e54a.png)

It also seems like these second Level 2 bubbles are reading as Level 3, despite being Level 2.
This also might be the cause of the problem.
![Screenshot 2023-05-01 061805](https://user-images.githubusercontent.com/34994940/235456985-cc12c9ef-9162-4d87-8daf-5e76a483b7bc.png)

I have attempted to change `Format > Style for new nodes` to `Default` and `Assign no style` with no success.
I have also tried to change `Format > Automatic level styles` to all options with no success.

-=-=-=-=-=-=-=-

I have included the map from the screenshots above.

**Mind map files**
[Root.zip](https://github.com/freeplane/freeplane/files/11365435/Root.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.11.1-pre32
 - Java Version

**Additional Information**
My apologies for submitting another issue so quickly after you fixed my prior issue.
This has sort of been driving me up the wall and I've been trying to remedy it since you fixed that last issue.
I can figure out a workaround so this isn't really high priority, but it would be nice if it were fixed.

Thank you!

-edit
As mentioned above, I have figured out this workaround to achieve the output I'm expecting, so no pressure on fixing anything.
![Screenshot 2023-05-01 064137](https://user-images.githubusercontent.com/34994940/235459909-690e2567-d3e4-44e2-9700-aa215a29c96d.png)

**Comment by dpolivaev** [comment]
Don't expect it to be so smart.
Conditional styles conditions should not depend on other conditional styles.

You can describe your actual use case if you want me to try to find a pragmatic solution.
