### ISSUE TITLE
Urgent recovery of a map file

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#1122]
**Describe the bug**
With FP 1.11.1_32 An important map is from today impossible to open, there is a never-ending run of FP without reaching the normal window, only the black screen and the circle running, this is happening with all of the .bak and autosave versions, but only for this map: any suggestion how to recover the data in the map.
At the beginning, you see a black screen with the blue circle running, but
After some minutes, the blue circle disappears but FP doesn't work: only a full black screen
And after some other minutes, I stopped the map (I tried many times)

Sorry, but I cannot share the map

Desired outcome: 
just open the normal FP frame (no black screen)

**Screenshots** --> just black screen with the blue circle running 

I add this log, if it can help
[log.0.txt](https://github.com/freeplane/freeplane/files/11376504/log.0.txt)
shots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22]11
 - Java Version: I use the FP-embedded java

**Additional context**

**Comment by Illegit** [comment]
Sorry, I think it incredible that after 10 minutes (and only after writing this post: after a full day of trouble) the map has been opened, please check only if it is possible to decrease the opening time in some ways. Thanks

**Comment by Illegit** [comment]
currently the map is moving very slowly each change of mouse position requires more than 4 minutes

**Comment by dpolivaev** [comment]
Can you reinstall the previous version (-pre31) and let me know if it works better?

https://sourceforge.net/projects/freeplane/files/freeplane%20preview/1.11.x/

**Comment by Illegit** [comment]
I tried with 31, 30, 28 28 same problem

**Comment by dpolivaev** [comment]
Try to deactivate option Preferences…->Plugins->Formulas->Disable formula evaluation cache and let me know if it helps

**Comment by Illegit** [comment]
ok, I'll do but each command to FP takes some minutes

**Comment by Illegit** [comment]
in that map I have plenty of formulas and clones

**Comment by dpolivaev** [comment]
Can you check how this map works with Freeplane 1.10.6?

**Comment by dpolivaev** [comment]
But because the options are saved in a different files make sure that option "Preferences…->Plugins->Formulas->Disable formula evaluation cache" has the same value in the both installations.

**Comment by dpolivaev** [comment]
And make a backup copy of your map before you test different Freeplane versions and different configuration options.

**Comment by Illegit** [comment]
yes i stop and try now

**Comment by Illegit** [comment]
just tried with 1.11.32: disabling formulas and cache the opening was immediate, why till 2 weeks ago I was working with 29 and it was normal with same map and now instead this delays?
Do you want I try with 10.6 in any case?

**Comment by dpolivaev** [comment]
Options "disable formula evaluation" and "disable formula evaluation cache" should never be activated unless you know exactly why you want to use them.

Can you please let me know how Freeplane behaves if they are both not set?

**Comment by Illegit** [comment]
It seems working well, I can open normally the map. I installed the 32 in 2 different pcs and both have the "disable formula evaluation cache" flagged , only this one. I have not flagged anything therefore probably they were flagged in the installer, I used the installer for windows with Java embedded.

**Comment by dpolivaev** [comment]
Hey, could you please answer?

**Comment by dpolivaev** [comment]
I have not changed anything in the installer.

**Comment by Illegit** [comment]
OK maybe it was an old setting I never was aware of

**Comment by Illegit** [comment]
Now I need to take care of this flag to be sure never again today was troubling.
I think you help me a lot. Many thanks
