### ISSUE TITLE
add-ons with network calls throw SecurityException when permissions are set to allow

### ISSUE THREAD

**Issue by barrymac** [freeplane/freeplane#1126]
**Describe the bug**
I have written an add on to call an API. I set the permit network operations in the preferences for scripts. When I 

**To Reproduce**
1. install this add on:  https://github.com/barrymac/freeplane_openai_addon
2. In freeplane preferences , check 'Permit Network operations'
3. Click on 'Tools>GPT AddOn>Gpt Ideas'
4. Logs will show: 

```
INFO: Calling GPT
ERROR: java.lang.SecurityException: Freeplane groovy scripts are restricted. The following Network operation is forbidden: Connect . You can change this in the program settings.
```

**Expected behavior**
the Permit Network operations preference allows the script to call openai API

**Mind map files**
Any simple map

**Desktop :**
 - OS: Ubuntu
 - Version 22
 - Java Version 1.8 , 11, 14 , 19

**Additional context**
the same groovy script that the add on uses runs OK when it's added as a script to the scripts plugin

**Comment by EdoFro** [comment]
Hi @barrymac,
I looked into the add on mind map and maybe there is the problem:

![image](https://user-images.githubusercontent.com/35700575/236491462-53024c1b-a856-46fb-9065-f677f7c31d5e.png)


mindmap files In the repository:
[Gpt-AddOn.mm#L409](https://github.com/EdoFro/freeplane_openai_addon/blob/b7ca31e91fdc45191212f65f7f127628059dafe2/Gpt-AddOn.mm#L409)
and [Gpt-AddOn-v0.2.addon.mm#L412](https://github.com/EdoFro/freeplane_openai_addon/blob/b7ca31e91fdc45191212f65f7f127628059dafe2/Gpt-AddOn-v0.2.addon.mm#L412)

hope it helps,
edo

**Comment by barrymac** [comment]
Thanks @EdoFro  i also suspected those permissions but it was the script with the permissions set to true that gave the error. However, i cleaned the Freeland build, cleaned the freeplane home directory and now don't seem to be able to reproduce the error. So perhaps it was a build cache problem of some kind. Before i close this issue though I'll need to do some more testing and try to reproduce it.
