### ISSUE TITLE
open only one command search dialog

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1127]
I use command search a lot.   Sometimes I search for a term like “width”  – for edge widths.

Then I will check in the map to do something there.   The I press ctrl+f1 to open the command search again.

But instead of a new CS dialog (the current behavior), I would like to return to the already-open CS dialog.   I have never used multiple CS dialogs (I thought it was a bug the first time it happened).

I know I can click back in the already-open CS dialog but that involves (1) moving my hand to the mouse, (2) moving the cursor to the already-open CS dialog, and (3) clicking in the dialog to get focus back on it.   (Maybe you can tell I try to avoid mousing whenever possible.)

It would be lots easier for me if I could just press ctrl+f1 to refocus on the already-open CS dialog.   

I often move the CS dialog to another monitor, so mouse travel distance is increased.   And sometimes my mouse gets snagged at a monitor edge while trying to move between monitors  – that causes another possible hurdle and delay.  (I don't know if that is a Windows glitch or my mouse deficiencies.)

I realize I could just Esc out of the dialog to the map then click ctrl+f1 to reopen the CS dialog  – but I have reenter the search parameter because that gets cleared out.

So an alternate to the above request might be to just have the CS dialog remember my search parameter like it remembers my search filters (eg, Preference , Menu item , icon.  If the parameter is highlighted, I - or other users - could just type over it.

I am an outlier in many things so I see this request as a checkbox option.

**Comment by dpolivaev** [comment]
Version 1.11.2

**Comment by kenfhill84083** [comment]
Thanks.  I've been using the updated command search a lot since this was completed.  The functionality is significantly better for me.

**Comment by kenfhill84083** [comment]
Seems to work fine on my laptop monitor .  BUT a bit of a glitch on a secondary monitor.  

1. When Freeplane is on a 2nd monitor
2. open command search (ctrl+f1)
3. go to full screen (f11)
4. click in map
5. open command search again

2nd instance of command search displays with no search terms.

monitor specs @ https://www.amazon.com/dp/B07Z8TC28F?psc=1&ref=ppx_yo2ov_dt_b_product_details 

![command search with FP on 2nd monitor in full screen mode](https://github.com/freeplane/freeplane/assets/6380301/9028105d-7469-4649-8fa6-0c0af04406c2)

**Comment by kenfhill84083** [comment]
update.

After the 2nd command search opens, you can click in the map and press ctrl+f1 and focus goes to the 2nd command search dialog - without opening a 3rd CS dialog.
