### ISSUE TITLE
check for updates dialog .  wrong current version

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1129]
The "check for updates" dialog shows the latest version as "1.1.2".  see image.  Cosmetic issue but could confuse people.

![check for update dialog](https://github.com/freeplane/freeplane/assets/6380301/ccba428a-fc55-4ad6-873a-f424d464382b)

**Comment by ldmpub** [comment]
I suspect that this error in the latest version number is the reason why the "Download button" is greyed / inactive.

**Comment by ldmpub** [comment]
![image](https://github.com/freeplane/freeplane/assets/1452146/552056ca-b146-46f0-ac7b-97fbb7529d6d)

**Comment by dpolivaev** [comment]
Thanks for letting me know, fixed
