### ISSUE TITLE
redraw of edge widths

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1134]
**Describe the bug**
When I change the edge width - using command search in this instance - the edge width does not redraw correctly.  It only partially redraws.  May be related to the structure in this part of the map?  I have a node with 4 child nodes and a summary node (see image).

**To Reproduce**
1. click on a node with siblings and a summary node
2. in command search , double-click on edge width 8
3. result: edge with changes but not completely
4. by moving the mouse or the map the redraw completes

**Expected behavior**
expected edge to fully draw

**Mind map files**
attached

**Screenshots**
attached

**additional file**
attached zipped video

**Desktop (please complete the following information):**
windows 11
FP 1 11 2
latest java

![edge width only partiall redrawn](https://github.com/freeplane/freeplane/assets/6380301/8151f18e-9f9f-4b9c-8c34-4c19dad1992c)

[edge width only partiall redrawn.zip](https://github.com/freeplane/freeplane/files/11447560/edge.width.only.partiall.redrawn.zip)

[Freeplane _ command search.zip](https://github.com/freeplane/freeplane/files/11447588/Freeplane._.command.search.zip)

**Comment by dpolivaev** [comment]
Freeplane 1.11.3_pre01
