### ISSUE TITLE
Zoom in to node feature

### ISSUE THREAD

**Issue by Alniceandeasy** [freeplane/freeplane#1135]
Hi, I love freeplane and very impressed with all its functionality.

The one feature it doesn't seem to have which I have in the program I used to use (mind genius) is the option to zoom into a node and then stop displaying the higher branches on the screen. (You could then zoom back up to the higher level if required). This keeps the visual clutter down when your working into many levels of child nodes. (Which is important to me a I have dyslexia). I couldn't see this feature in freeplane, but please let me know if I've missed it. Thanks.

**Comment by dpolivaev** [comment]
Navigate->Jump in (⇧+ESC)
Navigate->Jump out (CONTROL+ESC)
