### ISSUE TITLE
ability to synch/unsynch nodes' note

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1140]
**Is your feature request related to a problem? Please describe.**
Sometimes I am working on node Z but want to see the note for node A.  I would like to unsynch node A's note so I can see it while working on node Z.  Most of the time I would have the node and its note in synch.

I often use a version of this kind of functionality in the Bible software, theWord (I show how in the video mentioned below).

I realize I can either (1) copy node A's note text to node Z or (1) open a new map view.  But those options, though useful, are a bit more choreography (or so it seems to me).

**Additional context**
I have created a video to explain.  It is a private video on youtube.  https://youtu.be/6qjWXF7KCqA

**Comment by macmarrum** [comment]
How about using `Edit->Note->Edit note in dialog` on node A, then switching to node Z and continue working on it?

**Comment by kenfhill84083** [comment]
> How about using `Edit->Note->Edit note in dialog` on node A, then switching to node Z and continue working on it?

Thanks.  I hadn't thought about that.  Unfortunately, the note editor dialog opens in a place that is not very convenient and I have to manually move it each time I want it open.   Other than that, it would be better than the alternatives I mentioned.  Although playing around, I find making a new map view and positioning it off to the side in a narrow view that opening the note dialog comes up in more nearly the preferred location.  Still quite a bit of choreography.

There seem to be several workarounds in the current functionality.  It's just that after developing a workflow in my Bible software over the years, I think my proposal would be the cleanest way to accomplish what I want to do in FP.

**Comment by dpolivaev** [comment]
Hello Ken,

I can't watch your private video. You need to make it "unlisted".

Regards, Dimitry

**Comment by kenfhill84083** [comment]
> Hello Ken, I can't watch your private video. You need to make it "unlisted". Regards, Dimitry

Sorry about that.  I reset the status to unlisted.  Thanks for letting me know.

**Comment by dpolivaev** [comment]
I can implement it but I can not put the button to the note panel.

**Comment by kenfhill84083** [comment]
> I can implement it but I can not put the button to the note panel.

How is it implemented from a user perspective?  I can't figure it out.

**Comment by dpolivaev** [comment]
View->Notes->Note follows selection
Preview 1.11.3_01

**Comment by kenfhill84083** [comment]
> I can implement it but I can not put the button to the note panel.

You must be the most responsive software developer in history!  Thanks.
