### ISSUE TITLE
map view/screen doesn't always move to the selected node location

### ISSUE THREAD

**Issue by Bricklam** [freeplane/freeplane#1141]
when I have a big map with unfolded nodes:
 when editing any node of the map, then moving to another part (and selecting any node there),
then trying to undo changes done to  the first node by pressing (Ctrl+Z):
the expected behaviour is that the map view will return back to the last edited node location (the target of the undo operation), which should be selected after pressing (Ctrl+Z)
However, the screen/map view never moves back to the edited node location (to where the current selection is)
and stays fixed on the current part of the map.

I also noticed a similar behavior: when I have a long list of children node that require scrolling to see all its nodes
 (for example 30 nodes), and selecting the first child in the list:
if I want to select all the children from top down by (Shift+Page Down): I execpt the screen to move automatically to follow the selection, until reaching the last selected node (like it used to do in older versions),
 but it doesn't happen: the map view stays fixed on the top of the children list (where selection starts) instead of going to where selection ends

**Comment by dpolivaev** [comment]
I can not reproduce any of the reported issues. I need an example map and detailed instructions.

**Comment by dpolivaev** [comment]
I am making progress, however, I can not reproduce the first part with the undo

**Comment by dpolivaev** [comment]
I think I got it but I am not sure because you have not specified a concrete scenario with the undo

**Comment by Bricklam** [comment]
Sorry, for not providing more details. I thought the bug was easy to produce.
Now, I can see why you failed to produce it (because it requires specific editing) to appear:

First: here is some information:
Windows 10:
Java version: 17.0.6
Freeplane Version: [FreeplanePortable-1.11.2.paf.exe]

Now, to reproduce the bug: create a new node and add only 3 letters to its text and press Enter
(Note: more than 3 wouldn't produce the bug)
then go select another node (far away from the first node) and press (Ctrl+Z) to undo the editing of the first node.
and you can see the bug:  the map view didn't move back to the first node, although the selection has moved.
Here is a small video showing the process in details

https://github.com/freeplane/freeplane/assets/129968602/37049ce0-c1ff-442a-a1ac-7ed1928c3f40

**Comment by dpolivaev** [comment]
Freeplane 1.11.3_pre01

**Comment by Bricklam** [comment]
Thanks for trying to fix this issue,
 but Unfortunately the bug wasn't fully fixed in (1.11.3_pre01) and a new bug appeared (in the map view):

- the map view will follow the selection successfully for the first time only
  (when you select the first node and press (Shift+Page Down),
but when I repeat the process from the last node upward using (Shift+Page Up): it doesn't work again.
and here is a new bug appears: the option to scroll the map from the menu fails 
 (View > Scroll map > Center selected node at left) doesn't work

You can see all the details in this video:

https://github.com/freeplane/freeplane/assets/129968602/2c6b4f93-5846-4870-bc75-ee7678c68941

**Comment by Bricklam** [comment]
Sorry, forgot to attach this bug report, it might help
 (appears when I try to repeat the previous process) (selecting nodes by shift+page up/down)

=========================================================================
STDOUT: May 20, 2023 6:37:29 PM org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.11.3; freeplane_xml_version = freeplane 1.11.1
git revision = a0b190b6ea95c5dc126bc64e8a770e70bbe1a1f1 dpolivaev 2023-05-19T15:36:34Z
java_version = 17.0.6; os_name = Windows 10; os_version = 10.0
STDOUT: May 20, 2023 6:37:30 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date format M/d/yy
STDOUT: May 20, 2023 6:37:30 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date time format M/d/yy, h:mm a
STDOUT: Framework launched
STDOUT: May 20, 2023 6:37:35 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://3:1/org/freeplane/plugin/formula/defaults.properties
STDOUT: May 20, 2023 6:37:35 PM org.freeplane.core.util.LogUtils info
INFO: extending script's classpath by [E:\TEMP\FP_1.11.3-pre01_Launcher\FreeplanePortable\Data\Freeplane\1.11.x\compiledscripts, E:\TEMP\FP_1.11.3-pre01_Launcher\FreeplanePortable\Data\Freeplane\1.11.x\lib]
STDOUT: May 20, 2023 6:37:35 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://8:1/org/freeplane/plugin/script/defaults.properties
STDOUT: May 20, 2023 6:37:35 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: May 20, 2023 6:37:35 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: May 20, 2023 6:37:39 PM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
STDOUT: May 20, 2023 6:37:42 PM org.freeplane.core.util.LogUtils info
INFO: menu items to execute: []
STDERR: May 20, 2023 7:29:50 PM org.freeplane.core.util.LogUtils severe
SEVERE: Can not select next visible sibling in continious selection, endless loop
STDOUT: May 20, 2023 7:29:53 PM org.freeplane.core.util.LogUtils info
INFO: execute [rundll32, url.dll,FileProtocolHandler, file:/E:/TEMP/FP_1.11.3-pre01_Launcher/FreeplanePortable/Data/Freeplane/1.11.x/logs/]
