### ISSUE TITLE
Can't insert images as Relative Paths under Details Area

### ISSUE THREAD

**Issue by apaza610** [freeplane/freeplane#1142]
**Describe the bug**
Inserting an image by Insert/Image/AddImage under Details Area produces ALWAYS an absolute path, inserting inside Core Area works well tough...

**To Reproduce**
1. Go to 'Insert/Image/AddImage'
2. Click on 'open'
3. Hover over the image

**Expected behavior**
In older versions of freeplane the paths correctly looked like: ../../WebDevCamp2020/0media/explicado.png, it's no longer the case

**Screenshots**
![Problema1](https://github.com/freeplane/freeplane/assets/10149862/0363f3eb-e587-47a5-8f13-c85409498230)

**Desktop (please complete the following information):**
 - OS: [win10]
 - Java Version 17

**Additional context**

**Comment by dpolivaev** [comment]
Freeplane 1.11.3_pre01
