### ISSUE TITLE
Could you please update to the latest version?

### ISSUE THREAD

**Issue by hhlp** [freeplane/freeplane#1149]
The version of flatpak 1.10.3

6748f6ffd8bebb1b69c1ec4d911e9bc4a0954432 Dimitry Polivaev 2022-06-25T10:00:05Z

**Additional context**

version stable in freeplane website:

https://sourceforge.net/projects/freeplane/files/freeplane%20stable/

althought the flatpak version said the latest version is 1.10.6 and is 1.11.2

Regards.,

**Comment by dpolivaev** [comment]
I am sorry, flatpak distribution is not a part of this project. You need to raise the issue there.
