### ISSUE TITLE
FP 1.11.2 adds white background for transparent SVG images added to Freeplane map

### ISSUE THREAD

**Issue by Bricklam** [freeplane/freeplane#1153]
in Freplane (1.11.2) Portable, Windows 10:
when I copy SVG images (with no background color) to Freeplane canvas, it automatically adds a white background color to them
and I didn't find any way to reverse this action (from styles or any other settings)
here is an example:

- here is an example SVG file:
![Vector-based_example](https://github.com/freeplane/freeplane/assets/129968602/f887bf86-f9bf-41ea-b411-616d13a337a4)

- the SVG image displayed in the browser (Transparent / no background color):
![image1](https://github.com/freeplane/freeplane/assets/129968602/8cab4801-ec76-46bd-87de-d3dd8592dd4d)

- the SVG image displayed in Freeplane (White background added):
![image2](https://github.com/freeplane/freeplane/assets/129968602/e4c35ed4-8911-4b8e-aead-709983a32ed9)

since this doesn't happen to other images like (PNG), I think it may be a bug, associated only with SVG files
thanks

**Comment by dpolivaev** [comment]
Preview 1.11.5_02
