### ISSUE TITLE
option to disable windows special character using alt key

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1154]
**Is your feature request related to a problem? Please describe.**
I am addicted to using the alt key in combination with Home , End , PgUp, and PgDn - to control folding of a node.  (I cannot remember if these are predefined shortcuts or if I have added them.)  I always use the keypad for this because it is easy to do without looking at the keyboard.

The problem : the node I am on when I do this now has the ascii character.  Often I forget to look to see that a new character has replaced my desired content.

**REQUEST**
It would help me a lot if I could disable the windows functionality so I can continue to fold/unfold without having to ctrl-z back to the changed node's original content.  (Assuming I noticed the change.)

**Comment by EdoFro** [comment]
May this be a problem with the NumLock key that activates/inactivates the keypad?

**Comment by kenfhill84083** [comment]
I only use turn on numLock for bulk number entry.  I usually want the number pad for for navigation.  I'm just looking for a way to disable the alt key for special character entry.  I was hoping that could be done in Freeplane because (1) it is the only app I use where this is a problem and (2) the FP development team is so smart, accessible, and responsive.

It is not worth investing a lot of developer time.  I can try to be more attentive or assign new hotkeys (if that is available for these features).  Maybe I can turn off numlock and then superglue the numlock key.

**Comment by dpolivaev** [comment]
It is not a freeplane specific issue

**Comment by Dukuu-Wild** [comment]
> addicted to using the alt key in combination with Home , End , PgUp, and PgDn - to control folding of a node.

Same for me, after starting using the numpad for navigation - alt-codes became a problem. Ctrl+z each time - pissing out.
After i've read answers in this thread, i've reassigned alt+PgDn to ctrl+PgDn.
How to do that - it's easy (hope it'll help other people to keep using this software):

![E2cUBlu242](https://github.com/freeplane/freeplane/assets/20105241/40276de6-44e9-4205-966d-bf793ec68ab8)
