### ISSUE TITLE
incremental reveal (unfolding) of ancestors during filtering - (kind of flip side of unfolding levels of descendants)

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1161]
**Request**
I would like a way to incrementally reveal ancestors while filtering.

**Is your feature request related to a problem? Please describe.**
I use filtering a lot to temporarily unclutter my may to focus on the current node(s) I am working on as well as using a map in presentations.  Sometimes it is nice to see ancestors for context but if the filtered node is very far down toward the leaf nodes, the ancestor string can be long and distracting.

It would be useful (for me) to be able to unfold upstream of a filtered node similar to what I can with Navigate > Fold > unfold one level.  But instead of unfolding on the descendant side this would incrementally reveal level(s) on the ancestor side.

**Comment by kenfhill84083** [comment]
No one else seems interested in this.  It is probably not worth developer investment.

**Comment by macmarrum** [comment]
Hi @kenfhill84083 

Please try this script: [filterShowNextAncestorForSelected.groovy](https://raw.githubusercontent.com/macmarrum/freeplane-scripting/main/src/scripts/filterShowNextAncestorForSelected.groovy)

Feedback is welcome.

**Comment by kenfhill84083** [comment]
> Hi @kenfhill84083
> 
> Please try this script: [filterShowNextAncestorForSelected.groovy](https://raw.githubusercontent.com/macmarrum/freeplane-scripting/main/src/scripts/filterShowNextAncestorForSelected.groovy)
> 
> Feedback is welcome.

That's it.  Works perfectly.  Makes me wish I had the smarts to code like that.

**Comment by kenfhill84083** [comment]
> > Hi @kenfhill84083
> > Please try this script: [filterShowNextAncestorForSelected.groovy](https://raw.githubusercontent.com/macmarrum/freeplane-scripting/main/src/scripts/filterShowNextAncestorForSelected.groovy)
> > Feedback is welcome.

Thanks.
