### ISSUE TITLE
FP 1.11.3_02: error parsing message

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#1166]
**Describe the bug**
The map was impossible to 4read: parsing error

**To Reproduce**
Cannot include the map, but the log file

**Expected behavior**
Open the map and read the nodes

**Mind map files**
cannot at now

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] w11
 - Java Version: that in FP installer

**Additional context**
[log - 2023-05-22 parsing error in Tools file.txt](https://github.com/freeplane/freeplane/files/11536629/log.-.2023-05-22.parsing.error.in.Tools.file.txt)

**Comment by dpolivaev** [comment]
The log contains message "SEVERE: Can not process attribute CHILD_NODES_LAYOUT = 'AUTO_BYFIRSTCHILD'"

This layout name was only used in alpha previews. Currently it is replaced by "AUTO_FIRST", and to fix it you can use any text editor.

**Comment by Illegit** [comment]
OK thanks.
