### ISSUE TITLE
Documentation . userGuide.mm @ 10 node extensions > attributes - overlapping nodes makes reading very difficult

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1169]
**Describe the bug**
In the Helfp file - userGuide.mm @ 10 node extensions > attributes - overlapping nodes makes reading very difficult

**Expected behavior**
to be able to read the documentation and not have garbled text because of overlapping nodes

**Screenshots**
see attached image

**Additional context**
As someone who was part of the documentation team a few years ago, I know what a challenge it is.  The team is doing a great job but some things slip between the cracks.  I think that is especially so due to the sophisticated format of this help file - with nodes that have been moved, I suspect to mimic a printed document format.  

I have struggled with this format and have often wished for a more simple mindmap arrangement: **child nodes directly, horizontally to the leaf side of the parent**.  When I first saw this map I was very confused even trying to press the up arrow key in an effort to navigate to the parent (which appeared above the leaf node I was on).  I have wondered if the original layout was designed to meet 2 purposes: (1) to give high-quality information about FP and (2) to showcase layout flexibility.  I believe #1 should definitely have priority - especially if #2 (if it exists) makes the text hard to read.

I hope this is posted in the right place.  If not, could you please transfer it where it belongs.  Thanks.

Again, no disrespect is intended to the current or past documentation participants.  They are doing, and have done, a very difficult job very well.  Kudos.

![user guide overlapping](https://github.com/freeplane/freeplane/assets/6380301/815ce2a5-84ed-4b71-89f4-b6869f7bdbc2)

**Comment by dpolivaev** [comment]
I see no overlapping content on my computer.

**Comment by kenfhill84083** [comment]
hmmmm.  OK.  Thanks.  I will press the "close with comment" button.
