### ISSUE TITLE
in (1.11.3_pre02): deleting/cutting the first/last node in a list will cause selection to go to the wrong node, instead of the nearest sibling node

### ISSUE THREAD

**Issue by Bricklam** [freeplane/freeplane#1170]
**Describe the bug**
in the newest version (1.11.3_pre02): (Windows 10, Java 17)
when I have a list of child nodes, and when I delete/cut the last selected node in the list (or the first one),
I expect the nearest node to be selected automatically (the next node after/before the deleted one),
instead: the selection
jumps to another far node (in the middle of the list)

**To Reproduce**
- create a list of children node (minimum 5 or 6 to be able to see the bug clearlery)
- select the last one and delete it and see where the selection goes (you can do this for the first node and will see the same result)

**Expected behavior**
- the selection should go directly to the next node (the following node remained in the list after the deleted node),
this is the typical behaviour for all Freeplane versions (confirmed until 1.11.2_stable)
 
**Mind map files**
[Test22.zip](https://github.com/freeplane/freeplane/files/11546778/Test22.zip)

**Videos to explain the bug**

- this is the buggy behaviour (in 1.11.3_pr02):
https://github.com/freeplane/freeplane/assets/129968602/18fe42f0-0ea7-4710-a533-c3f47ae67841

- and this is the normal behaviour (in previous Freeplane versions):
https://github.com/freeplane/freeplane/assets/129968602/33ec72f6-3463-4667-8869-dc83d6a3b208

**Comment by Bricklam** [comment]
I just found out another issue with the selection, that is maybe related to this issue),
it can be produced in the same uploaded map:
if you select one of the children node and then moved to the root node (by pressing Left key), and then returned back
by (Right key), the selection will NOT return to the last selected child node, instead it will go to another node in the middle.

here is a video that show the case: (in 1.11.3_pre02)
https://github.com/freeplane/freeplane/assets/129968602/e166e38d-6ae9-47f0-b717-c020519a787f

- and in this video I show the normal/expected behaviour (that was in 1.11.2_stable version)
https://github.com/freeplane/freeplane/assets/129968602/32eeb1c5-c5bd-40b6-8ffa-4304d800df3a

Sorry if I'm overwhelming you with many bug reports. I just try to do my best to help improve Freeplane.
thanks

**Comment by dpolivaev** [comment]
Thank you for your bug reports, they were helpful. I think I could fix the issue.

**Comment by dpolivaev** [comment]
Preview 1.11.3_03

**Comment by Bricklam** [comment]
they all fixed. Well done
Thanks
