### ISSUE TITLE
Improve horizontal edge middle line position (regression to previous versions)

### ISSUE THREAD

**Issue by netforfreedom** [freeplane/freeplane#1171]
Open the mind map generated by v1.9.14 using Freeplane v1.11.2, but the previously arranged ones have changed. The overlapping branch lines (horizontal) will become thicker, and the branch lines of moving child nodes will become broken. Is there any way to restore operations like v1.9.14? Thank you for your attention. Please refer to the figure
1.This is the operation of v1.9.14
![1 9 14](https://github.com/freeplane/freeplane/assets/39705624/5dfa7d24-f95d-4dae-b47b-56affe3c3d00)

2.This is the operation of v1.11.2
![1 11 2](https://github.com/freeplane/freeplane/assets/39705624/080c3ee9-0f37-4b0c-9441-cebb48104c9c)

**Comment by dpolivaev** [comment]
the fix is available in https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
Preview 1.11.3_04

I liked the old way more after viewing your examples
