### ISSUE TITLE
How to make each level automatically align with it

### ISSUE THREAD

**Issue by netforfreedom** [freeplane/freeplane#1174]
version:v1.11.2 
The content of each sub node is different, resulting in different lengths of nodes. We hope to provide an explanation of its functionality,

Ability to automatically align nodes at each level. This makes the map more hierarchical and easier to understand at a glance.
Please refer to the picture, which shows the effect before it:
![1](https://github.com/freeplane/freeplane/assets/39705624/c0014c1c-049f-48b7-89a6-9cfbf6dcdec9)

------
This is for the subsequent effect
![2](https://github.com/freeplane/freeplane/assets/39705624/7698bb37-e725-40b4-b48b-9753a2638bd6)

**Comment by metbril** [comment]
This would be nice.

current workaround is to set min and max width for the parent node.

**Comment by euu2021** [comment]
I think it's possible to create a script that does that. It would be a calculation like this: depending on the width of the parent node, a certain horizontal shift is added to the child node, using `node.horizontalShift`.

The public API has no method to retrieve the width of the node, but [this thread](https://sourceforge.net/p/freeplane/discussion/758437/thread/f5517e8b/) explains how to retrieve the width using internal methods:
```
import org.freeplane.view.swing.map.NodeView
def nodeView = node.delegate.viewers.find() {it instanceof NodeView}
c.statusInfo = "width is ${nodeView?.mainView?.width}"
```

Tomorrow, I will try to create the script.
