### ISSUE TITLE
removing a node at the top of a sibling group takes focus away from where I am working

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1177]
**Describe the bug**
shown in attached video.  When removing a node at/near the top of a stack of sibling nodes, the focus shifts to a node closer to the middle of the sibling stack - away from where I am working.

**To Reproduce**
1. click a node at/near the top of a fairly tall stack of sibling nodes
2. remove the node

**Expected behavior**
I expect the focus to shift to the node immediately below the one I deleted.  As I recall, that is the behavior I remember as standard.  I should not have to disrupt what I am doing to regain focus.

**Desktop (please complete the following information):**
 - Windows 11
 - current Java Version 
 - FP ver  1.11.3

**Additional context**
in the bottom half of the sibling stack it works like I expect.

[deleting node produces drop - have to move to get back where I want.zip](https://github.com/freeplane/freeplane/files/11576287/deleting.node.produces.drop.-.have.to.move.to.get.back.where.I.want.zip)

**Comment by dpolivaev** [comment]
Preview 1.11.3_04
