### ISSUE TITLE
redraw issue with node details

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1179]
**Describe the bug**
When I hide a series of node details and then try to unhide them, I sometimes see a redraw issue - I can glimpse a small bit of the details but the full details do not display.

**To Reproduce**
map has 8 level 1 nodes, each with something in details (as does root) - see attached map
1. select all level 1 nodes
2. alt+f3  to hide the details
3. focus on root
4. select all nodes
5. alt+f3 to display details
6. BUG : can only see glimpse of nodes - until...
7. pan the map & details display correctly

**Expected behavior**
I expect the details to be clearly, fully visible without panning map

**Mind map files**
attached

**video**
attached

**Desktop (please complete the following information):**
 - Windows 11 Home
 - 22H2
 - Java Version : 15.0.10
 - FP : 1.11.3

**Additional context**
I have noticed other display problems that panning corrects but am not able to reproduce.

[screen redraw problem.zip](https://github.com/freeplane/freeplane/files/11582358/screen.redraw.problem.zip)
[redraw issue (map).zip](https://github.com/freeplane/freeplane/files/11582376/redraw.issue.map.zip)
![screen redraw issue with details](https://github.com/freeplane/freeplane/assets/6380301/b5d2e8aa-2809-4e18-b044-852e102de04a)

**Comment by dpolivaev** [comment]
I think it is already fixed.
Could you please try the latest available preview?

**Comment by kenfhill84083** [comment]
Yes.  It seems fixed.  Thanks.
