### ISSUE TITLE
JDK 11 support?

### ISSUE THREAD

**Issue by aadrian** [freeplane/freeplane#118]
Hi,

Any plans adding JDK 11 (Open JDK 11) support?

Thank you.

**Comment by ghost** [comment]
It works just fine with OpenJDK11 when you compile the program yourself.
The command is `gradle build`.

**Comment by fnatter** [comment]
hi aadrian,

freeplane 1.7.x should work fine with OpenJDK11. Is there something that does not work for you?
@mwuttke97: Why compile yourself? Which aspect does not work in the distribution?

Cheers and Best Regards,
Felix

**Comment by ghost** [comment]
@fnatter Indeed. I opened a seperate issue for this now: https://github.com/freeplane/freeplane/issues/122

**Comment by aadrian** [comment]
@mwuttke97 @fnatter I'm not sure it does: https://travis-ci.org/aadrian/freeplane/builds/479794254

**Comment by dpolivaev** [comment]
We use Java8 to compile it. It runs under Java 11.
We do not compile it using Java 11 as long as we want it to run under Java 8

**Comment by aadrian** [comment]
@dpolivaev 
> We do not compile it using Java 11 as long as we want it to run under Java 8

Sorry, but the one should not exclude the other.

**Comment by dpolivaev** [comment]
Absolutely. It is just not on the high priority task list

**Comment by dpolivaev** [comment]
Support means "runs under Java 11", not "compiles under Java 11". If you want to improve it, you are welcome to submit a pull request.

**Comment by aadrian** [comment]
@dpolivaev 

> Support means "runs under Java 11", not "compiles under Java 11"

Well, not really :) : "support" for OpenJDK 11 could also mean that it just works on a machine with only this version of Java for: development, compile, assemble, run, debug, install (and for the plug-ins too) :) .


> ... you are welcome to submit a pull request.

It would really cool if a simple PR would cut it :) . My experience so far upgrading quite a few applications to OpenJDK 11 is not so rosy :( .

**Comment by dpolivaev** [comment]
You got why it is not done yet

**Comment by dpolivaev** [comment]
Well, I took a look at Java build with Java 11. The build was reported to be successful on my own computer. Obviously, travis uses outdated gradle version which does not support Java 11 yet.

**Comment by aadrian** [comment]
> Obviously, travis uses outdated gradle version

@dpolivaev if the project would have a gradle wrapper, than Travis could use it, so it would not use that default outdated version you mention.

**Comment by dpolivaev** [comment]
I do not like gradle wrapper

**Comment by aadrian** [comment]
@dpolivaev 
> I do not like gradle wrapper

Just because it would be there, you would not have to use it, but Travis and other automated tests could use it: as long as you have the same version of Gradle as that of the wrapper, the results should be 100% the same :) .

**Comment by inglor** [comment]
You can add a simple task on an extra gradle build to be used only from Travis to support Gradle 5.0 and JDK 11. See [example]

[example]: https://stackoverflow.com/questions/42818269/is-gradlew-mandatory-for-travis-ci-to-work

**Comment by dpolivaev** [comment]
Lovely, I am doing it right now

**Comment by dpolivaev** [comment]
@inglor does not help with java 11 because gradle wrapper can not run, see https://travis-ci.org/freeplane/freeplane/jobs/480065543

**Comment by inglor** [comment]
@dpolivaev you might need to set the overwrite to true for the wrapper task
```
task wrapper(type: Wrapper, overwrite:true) {
    gradleVersion = '4.10'
}
```

**Comment by dpolivaev** [comment]
installed gradle can not execute task wrapper because it does not work under jdk 11
