### ISSUE TITLE
redraw issue when playing with Filter selected nodes + Jump in

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1187]
**Describe the bug**
too hard to describe.  See "to reproduce"

**To Reproduce**
Steps to reproduce the behavior  **(in attached map):**
1. observe node: "jump in" - should see the node core
2. select node: "filter selected nodes" 
3. turn on Filter selected nodes
4. select node: "asdf" with bubble node shape
5. Jump in
6. invoke Filter > no filter
7. Jump out
8. node cored for node : "jump in" has disappeard
9. clicking node redraws node core

**Expected behavior**
I expected all node cores to be visible

**Mind map files**
attached

**Screenshots**
attached x2

**video**
attached

**Desktop (please complete the following information):**
 - Windows 11 Home
 - Java Version : 17.0.7
 - FP  1.11.4

[screen redraw problem - filter selected noded - jump in.zip](https://github.com/freeplane/freeplane/files/11602609/screen.redraw.problem.-.filter.selected.noded.-.jump.in.zip)
![screen redraw issue - Filter selected nodes , Jump in (before)](https://github.com/freeplane/freeplane/assets/6380301/047fd931-7019-4950-b6bf-935a6d6981b3)
![screen redraw issue - Filter selected nodes , Jump in (after)](https://github.com/freeplane/freeplane/assets/6380301/fd84e9dd-b51b-4799-9ddf-ca1d425a6b72)
[filter-jump in demo video.zip](https://github.com/freeplane/freeplane/files/11602633/filter-jump.in.demo.video.zip)

**Comment by dpolivaev** [comment]
It looks like you have attached the video in the both zip files and no mind map.
Could you please reupload your testing mind map?

**Comment by kenfhill84083** [comment]
> It looks like you have attached the video in the both zip files and no mind map. Could you please reupload your testing mind map?

Sorry.  Try the attached. 

[filter-jump in demo video (mindmap).zip](https://github.com/freeplane/freeplane/files/11627731/filter-jump.in.demo.video.mindmap.zip)

**Comment by dpolivaev** [comment]
Preview 1.11.5_02
