### ISSUE TITLE
bug when working with Jump In and Filter Select Nodes

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1191]
**Describe the bug**
This is not clear or detailed so this may not be helpful.  I have been running into errors when using Jump In and Filter Selected Nodes in preparation of making a [video](https://www.youtube.com/watch?v=CJm-19pxQxo) about them.  Before recording I launched FP but at 8:35 the error shows up on the status bar.  I don't know if that can give any insight into this - I have not been able to find a reproducible recipe.

I did not know where else to report this with such flimsy information.  I'll keep playing around to see if I can spot a pattern.  

I'm sorry this cropped up in the video.

**Comment by dpolivaev** [comment]
Oh, I can actually reproduce it.

**Comment by kenfhill84083** [comment]
FP .  1.11.4

US Mountain time

I cannot give you the exact time.  As I recall, it was yesterday at about
5-6 pm.

**Comment by kenfhill84083** [comment]
>
> reproduce
>

great

**Comment by dpolivaev** [comment]
Preview 1.11.5_02
