### ISSUE TITLE
Freeplane crashes when I jump in then try to follow a link

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1193]
**Describe the bug / reproduce recipe**
In the mindmap attached, 
- at root node, I fold everything
- I jump in the node labeled "canine"
- go down the "asdf" branch to some links to nodes in the map
- click on a link 
- error

**when**
within last hour

**Expected behavior**
did not expect crash

**Mind map files**
[AnimalsSampleMap (MM).zip](https://github.com/freeplane/freeplane/files/11628481/AnimalsSampleMap.MM.zip)

**Desktop (please complete the following information):**
 - Windows 11 Home

**video**
[issues.zip](https://github.com/freeplane/freeplane/files/11628488/issues.zip)

**screenshots of error messages**
![jump in link issue](https://github.com/freeplane/freeplane/assets/6380301/214166ce-0303-409d-8ee4-3ffe9d894489)

**Comment by dpolivaev** [comment]
Preview 1.11.5_03
