### ISSUE TITLE
Default text for new nodes

### ISSUE THREAD

**Issue by ClaytonCurtis1947** [freeplane/freeplane#1195]
**Is your feature request related to a problem? Please describe.**
When I want to rapidly construct a network of nodes without taking the time to put text in each as it is added, it can be hard to tell where nodes actually are when the FreePlane defaults are used.  It would be valuable to be able to define default text; an very useful extension would be the ability to define style / level-specific text.

![1 - Multiple nodes inserted with current defaults](https://github.com/freeplane/freeplane/assets/34657219/98ca2fe2-10ea-4206-af55-ad1c72917970)
1 - Multiple nodes inserted with current defaults

![2 - Multiple nodes inserted with minimum approach to default text (global default)](https://github.com/freeplane/freeplane/assets/34657219/4b41db92-7bb6-4a03-8b50-a174e5696957)
2 - Multiple nodes inserted with minimum approach to default text (global default)

![3 - Multiple nodes inserted with approach to default text (level-specific default text](https://github.com/freeplane/freeplane/assets/34657219/f54e3603-cc21-4ce0-a183-b86c6d8cd8c0)
3 - Multiple nodes inserted with approach to default text (level-specific default text

**Comment by macmarrum** [comment]
Freeplane supports scripts aka macros, which can do what you described.

1 - Multiple nodes inserted with current defaults
```groovy
def numberOfNodesToInsert = 5

def n = node
(0..<numberOfNodesToInsert).each { n = n.createChild() }
c.select(n)
```

2 - Multiple nodes inserted with minimum approach to default text (global default)
```groovy
def numberOfNodesToInsert = 5
def defaultText = '*default*'

def n = node
(0..<numberOfNodesToInsert).each { n = n.createChild(defaultText) }
c.select(n)
```

3 - Multiple nodes inserted with approach to default text (level-specific default text
```groovy
def numberOfNodesToInsert = 5
def levelToDefaultText = [
  1: '*1*',
  2: '*2*',
  3: '*3*',
  4: '*4*',
  5: '*5*',
]
def countHidden = false

def n = node
(0..<numberOfNodesToInsert).each {
    n = n.createChild()
    n.text = levelToDefaultText[n.getNodeLevel(countHidden)]
}
c.select(n)
```

You can save each script to a file (e.g. `insertMultipleNodesWithCurrentDefaults.groovy`) and assign each a hot key or run them from Freeplane menu `Tools->Scripts` or right-click on a node -> `Scripts`

Note: to get to the `scripts` directory on the disk, you can use `Tools->Open user directory`

You can change the values assigned to `numberOfNodesToInsert`, `defaultText`, `levelToDefaultText` by editing the saved files before running them.

More information: https://docs.freeplane.org/scripting/Scripting.html

Regarding a default style for inserted nodes, you can use `Format->Style for new nodes`

**Comment by dpolivaev** [comment]
What do you think about copying any text you like into the clipboard and creating new nodes using the paste command CTRL+V

**Comment by ClaytonCurtis1947** [comment]
First of all, I realize that this is an edge case! 😊

Your suggestion will obviously work until / unless one uses the paste buffer for something else.

I really appreciate your response!

 

Clayton Curtis

**Comment by ClaytonCurtis1947** [comment]
Yikes!! 😊

Scripts are obviously powerful; I was just looking for something simple. 😊

(BTW, the number 5 wasn’t intended to be known a priori. I just depicted that number to have enough to illustrate the point.)

 

Thanks for the thoughtful response.

 

Clayton Curtis
