### ISSUE TITLE
spell check on Retina

### ISSUE THREAD

**Issue by yqzhang** [freeplane/freeplane#12]
Hi,
Sorry to bother you guys. I really enjoy this project and it's awesome.
I've got something you might find useful or not that I think the spell check doesn't work well with Retina on Mac. I firstly installed the latest stable version 1.2.23 which work perfectly with Retina, but when there is a spelling error the squiggly red line shows up a little bit (less than half second) and disappears forever. Then I also check 1.2.18 where spell check works smoothly while the only problem is that it doesn't support Retina.
Thank you very much!

**Comment by dpolivaev** [comment]
Please reopen this issue if needed
