### ISSUE TITLE
folding/unfolding by clicking on the folding circle doesn't work correctly in (1.11.5_pre04)

### ISSUE THREAD

**Issue by Bricklam** [freeplane/freeplane#1203]
**Describe the bug**
folding/unfoding any node by clicking by the mouse on the folding circle doesn't work
it doesn't change the folding status. you can see the image below

**To Reproduce**
just try to fold unfolded node, or unfold any folded node by the mouse by clicking on the folding circle

- the test map:
[TEST_55.zip](https://github.com/freeplane/freeplane/files/11644315/TEST_55.zip)

- here is a video to illustrate:
![Video_2023_06_03-2](https://github.com/freeplane/freeplane/assets/129968602/577649d2-f833-48c8-8d98-c2be0517224f)

**Comment by dpolivaev** [comment]
I can not see it here.
You don't need to double click. Do you?
Can you upload file auto.properties from Tools->Open user directory ?

**Comment by dpolivaev** [comment]
Now I see it.

**Comment by dpolivaev** [comment]
Preview 1.11.5_05
