### ISSUE TITLE
Too big unfolding symbol on freeplane-1.11.5_xx

### ISSUE THREAD

**Issue by abc16361** [freeplane/freeplane#1204]
**Describe the bug**
Not sure whether it is a bug or a new design, but just report here as a reminder.
The size of unfolding symbol (the symbol if a node is unfolded) on version 1.11.4 looks good to me, but on fp-1.11.5, it has been changed too big and it seems there is no way to adjust it.

**Screenshots**
<img width="619" alt="unfolding_symbol_size" src="https://github.com/freeplane/freeplane/assets/101362122/a4f0e4bb-f60f-4eb3-80c2-ac79f6daf100">

**Desktop (please complete the following information):**
 - OS: win 11 pro
 - Version : fp-1.11.5-pre05
 - Java Version: zulu17.42.19-ca-jdk17.0.7-win_x64.msi

**Comment by dpolivaev** [comment]
Then I should make it configurable. 
Could you please attach your mind map so that I know your node sizes?
As always I need a mind map, only a picture or video is not sufficient.

**Comment by abc16361** [comment]
Here are the maps. The foldingSymbol.mm is created from the standard-1.6 template and the screenshot was captured from it, and the new.mm is from a template I use daily and has the same big symbol. 
[sent.zip](https://github.com/freeplane/freeplane/files/11646492/sent.zip)
Thank you.

**Comment by abc16361** [comment]
Recently I got a 27 inches 4k monitor and the scale is set on 150%, and the nodes of 180 px width on my template look a bit small, so I need to create new templates because of it. If the size of the symbol can be configurable, that would be good!

**Comment by macmarrum** [comment]
The setting `Preferences…->Appearance->Size limits->Folding symbol width` does the trick for me.

**Comment by dpolivaev** [comment]
With this setting, you can increase the width but you can't reduce it.

**Comment by abc16361** [comment]
The size of the symbol could be different on a folded node and a hovered node.  The symbol would disappear on a folded node if the size is set to 1px, but there is a minimum limit on hovered nodes, 16px on fp-1.11.4 and 32px on fp-1.11.5.

**Comment by dpolivaev** [comment]
Preview 1.11.5_06

There is also new configuration option Preferences…->Appearance->Size limits->Folding switch width
