### ISSUE TITLE
Error While Parsing File - Cannot open my file

### ISSUE THREAD

**Issue by Damianus500** [freeplane/freeplane#1205]
I have problem opening a freeplane .mm file which I use as my epistemology class.

I upgraded to freeplane 1.11.4 recently. Don't know whether is the issue is with the latest version or is my file corrupted.

Any help much appreciated!

Damianus

---

**Describe the bug**
Error While Parsing File

---

**To Reproduce**
1. I execute the command from terminal:

> freeplane Epistemology_2023.mm

**Expected behavior**
I received this error message on terminal

Jun 05, 2023 10:43:37 AM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
Jun 05, 2023 10:43:38 AM org.freeplane.core.util.LogUtils warn
**WARNING: Error while parsing** file:/home/damianus/Dropbox/Apps/1writer/Epistemology_Notes/2023_PH313/2023_Lecture_Notes/Epistemology_salve.mm
**Closing tag does not match opening tag:** `node' != `richcontent', SystemID='file:.', Line=830
        at org.freeplane.n3.nanoxml.XMLUtil.errorWrongClosingTag(XMLUtil.java:295)
        at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:317)
        at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
        at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
        at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
        at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
        at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
        at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
        at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
        at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
        at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
....

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.
[Epistemology_2023.zip](https://github.com/freeplane/freeplane/files/11648173/Epistemology_2023.zip)

**Screenshots**

![image](https://github.com/freeplane/freeplane/assets/83386270/a7d7501b-0b74-4201-871d-b87a36a00a26)

**Desktop (please complete the following information):**

Jun 05, 2023 10:43:37 AM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
Jun 05, 2023 10:43:38 AM org.freeplane.core.util.LogUtils warn
WARNING: Error while parsing file:/home/damianus/Dropbox/Apps/1writer/Epistemology_Notes/2023_PH313/2023_Lecture_Notes/Epistemology_salve.mm
Closing tag does not match opening tag: `node' != `richcontent', SystemID='file:.', Line=830
        at org.freeplane.n3.nanoxml.XMLUtil.errorWrongClosingTag(XMLUtil.java:295)
        at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:317)
        at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
        at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
        at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
        at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
        at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
        at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
        at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
        at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
        at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
 OS: Pop!_OS 22.04 LTS x86_64
    //////7676767676*//////////////       Host: HP Laptop 15s-eq0xxx
   /////76767//7676767//////////////      Kernel: 6.2.6-76060206-generic
  /////767676///*76767///////////////     Uptime: 46 mins
 ///////767676///76767.///7676*///////    Packages: 3198 (dpkg), 73 (flatpak)
/////////767676//76767///767676////////   Shell: bash 5.1.16
//////////76767676767////76767/////////   Resolution: 1920x1080
///////////76767676//////7676//////////   DE: GNOME 42.5
////////////,7676,///////767///////////   WM: Mutter
/////////////*7676///////76////////////   WM Theme: Pop
///////////////7676////////////////////   Theme: Materia-dark-compact [GTK2/3]
 ///////////////7676///767////////////    Icons: gnome [GTK2/3]
  //////////////////////'////////////     Terminal: tmux
   //////.7676767676767676767,//////      CPU: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx (8) @ 2.300GHz
    /////767676767676767676767/////       GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
      ///////////////////////////         Memory: 6316MiB / 13883MiB      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64
    //////7676767676*//////////////       Host: HP Laptop 15s-eq0xxx
   /////76767//7676767//////////////      Kernel: 6.2.6-76060206-generic
  /////767676///*76767///////////////     Uptime: 56 mins
 ///////767676///76767.///7676*///////    Packages: 3198 (dpkg), 73 (flatpak)
/////////767676//76767///767676////////   Shell: bash 5.1.16
//////////76767676767////76767/////////   Resolution: 1920x1080
///////////76767676//////7676//////////   DE: GNOME 42.5
////////////,7676,///////767///////////   WM: Mutter
/////////////*7676///////76////////////   WM Theme: Pop
///////////////7676////////////////////   Theme: Materia-dark-compact [GTK2/3]
 ///////////////7676///767////////////    Icons: gnome [GTK2/3]
  //////////////////////'////////////     Terminal: tmux
   //////.7676767676767676767,//////      CPU: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx (8) @ 2.300GHz
    /////767676767676767676767/////       GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
      ///////////////////////////         Memory: 6832MiB / 13883MiB

 - Java Version
Jun 05, 2023 10:43:37 AM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
Jun 05, 2023 10:43:38 AM org.freeplane.core.util.LogUtils warn
WARNING: Error while parsing file:/home/damianus/Dropbox/Apps/1writer/Epistemology_Notes/2023_PH313/2023_Lecture_Notes/Epistemology_salve.mm
Closing tag does not match opening tag: `node' != `richcontent', SystemID='file:.', Line=830
        at org.freeplane.n3.nanoxml.XMLUtil.errorWrongClosingTag(XMLUtil.java:295)
        at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:317)
        at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
        at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
        at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
        at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
        at org.freeplane.n3.nanoxml.StdXMLParser.processElement(StdXMLParser.java:313)
        at org.freeplane.core.io.xml.XMLParser.processElement(XMLParser.java:45)
        at org.freeplane.n3.nanoxml.StdXMLParser.scanSomeTag(StdXMLParser.java:483)
        at org.freeplane.n3.nanoxml.StdXMLParser.processElementContent(StdXMLParser.java:357)
        at org.freeplane.core.io.xml.XMLParser.processElementContent(XMLParser.java:126)
 OS: Pop!_OS 22.04 LTS x86_64
    //////7676767676*//////////////       Host: HP Laptop 15s-eq0xxx
   /////76767//7676767//////////////      Kernel: 6.2.6-76060206-generic
  /////767676///*76767///////////////     Uptime: 46 mins
 ///////767676///76767.///7676*///////    Packages: 3198 (dpkg), 73 (flatpak)
/////////767676//76767///767676////////   Shell: bash 5.1.16
//////////76767676767////76767/////////   Resolution: 1920x1080
///////////76767676//////7676//////////   DE: GNOME 42.5
////////////,7676,///////767///////////   WM: Mutter
/////////////*7676///////76////////////   WM Theme: Pop
///////////////7676////////////////////   Theme: Materia-dark-compact [GTK2/3]
 ///////////////7676///767////////////    Icons: gnome [GTK2/3]
  //////////////////////'////////////     Terminal: tmux
   //////.7676767676767676767,//////      CPU: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx (8) @ 2.300GHz
    /////767676767676767676767/////       GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
      ///////////////////////////         Memory: 6316MiB / 13883MiB      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64
    //////7676767676*//////////////       Host: HP Laptop 15s-eq0xxx
   /////76767//7676767//////////////      Kernel: 6.2.6-76060206-generic
  /////767676///*76767///////////////     Uptime: 56 mins
 ///////767676///76767.///7676*///////    Packages: 3198 (dpkg), 73 (flatpak)
/////////767676//76767///767676////////   Shell: bash 5.1.16
//////////76767676767////76767/////////   Resolution: 1920x1080
///////////76767676//////7676//////////   DE: GNOME 42.5
////////////,7676,///////767///////////   WM: Mutter
/////////////*7676///////76////////////   WM Theme: Pop
///////////////7676////////////////////   Theme: Materia-dark-compact [GTK2/3]
 ///////////////7676///767////////////    Icons: gnome [GTK2/3]
  //////////////////////'////////////     Terminal: tmux
   //////.7676767676767676767,//////      CPU: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx (8) @ 2.300GHz
    /////767676767676767676767/////       GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
      ///////////////////////////         Memory: 6832MiB / 13883MiB⚝ Mon Jun 05  11:09 靜 ᗫ ⚝  ↬ java --version
openjdk 11.0.19 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1, mixed mode, sharing)

**Additional context**

**Comment by macmarrum** [comment]
Good news is that the file can be edited in a text editor (e.g. VSCode) and the invalid (from XML perspective) tags can be removed.

When I try to open your file in Freeplane, I get an error message which indicates the line number to look at:

- Closing tag does not match opening tag: node' != richcontent', SystemID='file:.', **Line=830**

When I open the file in a text editor and go to line 830, I can see `<font color="red">` has no closing tag, i.e. `</font>`, so I remove it, save the file and try to open it in Freeplane again. I get another error:

- Closing tag does not match opening tag: `node' != `richcontent', SystemID='file:.', **Line=3378**

In a text editor, in line 3378 I can see `<Greene`, which is most probably interpreted as an opening XML tag and missing a closing tag `</Greene>`, so I remove `<`, save the file and open it in Freeplane with success.

Here's your file after the modifications.
[Damianus500~Epistemology_2023~uncorrupted.mm.zip](https://github.com/freeplane/freeplane/files/11648493/Damianus500.Epistemology_2023.uncorrupted.mm.zip)

---

The issue needs further investigation though.
It would be great if you could attach a text file with the Note content that you originally pasted into the nodes
- `### Necessity & Contingency` (ID="ID_1112110957")
- `#### Gilson: The Modern Experiment` (ID="ID_1448519354")

so that the issue could be replicated

**Comment by macmarrum** [comment]
I managed to replicated the issue in v1.11.5-pre05:

- Change Note content type to Markdown
- Type `1 < 2`
- Save the file
- Try to open it again (causes the error `Closing tag does not match opening tag: `node' != `richcontent', SystemID='file:.', Line=`)

Here's my idea how to handle such situations:
- When closing a Markdown editor, Freeplane validates its content and prevents closing the window if invalid XML is found, and displays an error message

**Comment by dpolivaev** [comment]
Good catch, I am fixing it. It seems it never worked correctly.

**Comment by dpolivaev** [comment]
I could recover the most of the content.
[Epistemology_2023 recovered.mm.zip](https://github.com/freeplane/freeplane/files/11649937/Epistemology_2023.recovered.mm.zip)

It turned out that Freeplane can not handle unmatching < and > characters in the markdown content.
I am going to fix it ASAP, probably on the coming Thursday.

**Comment by dpolivaev** [comment]
Preview 1.11.5_06 contains the fix.
I think that the bug exists since version 1.11.3 which saved corrupted files in cases figured out by @macmarrum
