### ISSUE TITLE
tooltips for converting between child nodes and attributes read "for one node" should read "for selected node(s)"

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1208]
**Is your feature request related to a problem? Please describe.**
The tooltips for converting child nodes to attributes and converting attributes to child nodes - on both the menus and in command search - read in the singular "on one selected node".  But the action can also be invoked if more than one node is selected.

**request**
wording should reflect "node(s)" to include the possibility of multiple selected nodes.

![command search tooltips for converting between child nodes and attributes and vice versa](https://github.com/freeplane/freeplane/assets/6380301/7375270d-29a9-45fa-a202-8bd5b289253e)

**Comment by macmarrum** [comment]
I believe the **Convert...** actions come from an add-on, i.e. not part of Freeplane (core).

The way add-ons deliver their functionality is by adding scripts.
In general, a script in Freeplane can have the following execution modes:
- ON_SINGLE_NODE
- ON_SELECTED_NODE
- ON_SELECTED_NODE_RECURSIVELY

→ https://docs.freeplane.org/scripting/Scripting.html#execution-modes

A tooltip for a script-execution menu item is generated automatically. It consists of "Execute" + script name + mode of execution (defined in the script).

The tooltip "on one selected node" suggests that **Child nodes to attributes** is meant to be executed only once, no matter how many nodes are currently selected. Most probably the author of the script included code that goes over selected nodes and coverts them one by one.

**Comment by kenfhill84083** [comment]
Thanks.
