### ISSUE TITLE
Presentations to save Jump In

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#1210]
Currently a Presentations Slide can save a Filter. As a result, the true root is always visible, i.e. in each Slide.

It would be great for Presentations to also save **Jump In** (view root), in addition to Filter.

When stepping to a different Slide, Freeplane would switch to the saved view root (and avoid showing the true root).

This would bring all the benefits of Jump In to Presentations.

**Comment by dpolivaev** [comment]
Preview 1.11.5_06
