### ISSUE TITLE
Export to Java Applet: Mindmap doesn't load, may be Class ChildNodesAlignment missing? 

### ISSUE THREAD

**Issue by dartrax** [freeplane/freeplane#1214]
**Describe the bug**
When exporting a Mindmap to Java Applet (.html), the applet loads but the Mindmap isn't displayed.

**To Reproduce**
I uploaded an example here: https://www.dartrax.de/other/freeplane/mindmap.html
Use a browser that can execute java applets. The Mindmap doesn't load.

**Mind map files**
[JavaAppletExport.zip](https://github.com/freeplane/freeplane/files/11677097/JavaAppletExport.zip)

**Screenshots**
![image](https://github.com/freeplane/freeplane/assets/15105943/be5d9dd6-5838-461d-b08d-4edcb89fc0aa)

**Desktop (please complete the following information):**
 - Java Version Build 1.8.0_371-b11

**Additional context**
From [here ](https://github.com/leaningtech/cheerpj-appletrunner/issues/62) I leaned that the Class `ChildNodesAlignment` might be missing from `org/freeplane/api/ChildNodesAlignment`. The Cheerpj Appletrunner is a tool that allows using java applets in modern browsers. However, the bug described above was reproduced in both environments: Native execution in an old browser engine and execution by Cheerpj in Chrome.

What I want to achieve is to save a mindmap on a webserver and have a live preview without the need to deal with exported (possibly outdated) copys of any format, just the source .mm file. Another solution would be [this feature req](https://github.com/freeplane/freeplane/issues/1151).

**Comment by dpolivaev** [comment]
The applet is fixed in 1.11.5_pre06. Later I improved the toolbar, but this fix is not in the preview version yet.

**Comment by dartrax** [comment]
Thanks for your fast reaction, I'll test next week and let you know!

**Comment by dartrax** [comment]
Thank you, it works now! New link to test (Edge with Internet Explorer Mode):
https://www.dartrax.de/other/freeplane/map.html
