### ISSUE TITLE
\models is not rendered correctly in SVG and PDF

### ISSUE THREAD

**Issue by ghost** [freeplane/freeplane#122]
## Summery
The latex symbol `\models` is not rendered correctly when the mindmap is exported to SVG or PDF.

## Reproduction Steps

1. Copy this mm:
![screenshot-2019-01-08-23 39 08](https://user-images.githubusercontent.com/7082786/51142451-525e3e80-184c-11e9-8da8-6e44a055c914.png)
(The formula is `\[\pi \models \Phi \]`)
2. Export to either PDF or SVG
3. The result is this:
![screenshot-2019-01-08-23 38 41](https://user-images.githubusercontent.com/7082786/51142545-94878000-184c-11e9-8687-75470fb17932.png)
(PDF)
![screenshot-2019-01-14-23 25 47](https://user-images.githubusercontent.com/7082786/51145760-1b405b00-1855-11e9-8ad1-c8f4959571ea.png)
(SVG)

## System Info

Arch Linux with OpenJDK11

I use Arch Linux and freeplane isn't included in the official ArchLinux repo (but freemind is). There are scripts to build the package yourself on the Arch User Reposity ([binary](https://aur.archlinux.org/packages/freeplane/), [build from git source](https://aur.archlinux.org/packages/freeplane-git/)). Both versions have the same bug.

I've also tested this in a fresh installation of Debian GNU/Linux 9 in VirtualBox. I can reproduce this bug in Debian. I submitted this as an issue now, because it persits in both Arch Linux and Debian.

## Note, However...

When I clone & compile the code manually using gradle, and without installation, the formula is exported correctly. So I concluded that this may be a packaging issue.

So far I could only reproduce this bug using `\models`, other symbols (like `\bigcirc`, `\square`, `\frac`, etc.) work.

Last but not least, I would like to thank you for this great software :-)

**Comment by inglor** [comment]
@mwuttke97 Can you share the .mm file? I'm the AUR packager and trying to debug if it's my packaging or not.

**Comment by ghost** [comment]
[test.zip](https://github.com/freeplane/freeplane/files/2761788/test.zip)

**Comment by inglor** [comment]
I'm able to reproduce the issue. But I cannot see how you managed to export a .pdf correctly. I've tried with both AUR packages, compiling locally from gradle with and without an IDE and in all cases the export to .pdf is mangled as per your screenshots.

Could it be something to do with fonts installed locally?

**Comment by ghost** [comment]
This is very weird. I started the VM that I set up to test this issue and built freeplane there (using openJDK8 and gradle). I could reproduce this bug there, with PDF and SVG export.
I could also reproduce it locally (`gradle run`), however, only for SVG export. PDF export looks fine with `gradle run` on my local machine. Note that this way (local archlinux machine, openJDK11, `gradle run`, PDF export) was the only way how I could export this mm properly.

**Comment by inglor** [comment]
It seems like a classpath issue. Can you try to export with `gradle runDist` and see if you can export PDF correctly?

**Comment by ghost** [comment]
Yeah, you're right. I can reproduce the bug with `gradle runDist`.

**Comment by rainyl** [comment]
same problem...any solutions?,i found [it](https://sourceforge.net/p/freeplane/bugs/2625/) when i search about it, by the way ,windows version(1.17.0) also has the problem...

**Comment by fnatter** [comment]
hi rainyl,

can you try to change the options in Tools->Preferences->Environment->Export ?

Cheers and Best Regards,
Felix

**Comment by ghost** [comment]
Hi Felix,

I just tried a few options in the Preferences you mentioned. I have successfully managed to export a map like in the example, using the following options:

- "Use tabs in text output" unchecked
- "Convert texts to shapes" checked
- "Embed fonts in SVG" checked or unchecked (both options work)
- PDF export (But SVG export has the same issue)

**Comment by ghost** [comment]
I have now verified this issue on a virtual machine on my own computer, and on a remote compute (both running GNU/Linux distributions).

Here's the *.mm file:

https://gist.github.com/mwuttke97/16bc27305fd80442976e46a2c0ca84be

**Comment by ofossum** [comment]
I can also verify the behaviour mentioned in the first post in a SVG and PDF.

* Archlinux
* Freeplane 1.9.14 (now in the Arch "community" repos, AUR no longer needed)
* Java 11

**Comment by gamberoillecito** [comment]
@dpolivaev I'm having a similar issue but with most of the math symbols I'm using. "Convert texts to shapes" solves it but it is quite inconvenient since the created pdf is not searchable. Would it be possible to add an option to convert to shape only nodes containing latex?

- Freeplane 1.11.14
- Windows 11 pro
- Java version: 15.0.10

I'm adding a screenshot for reference. Please tell me if I should create a new issue since this one was referring only to some cases.

![immagine](https://github.com/freeplane/freeplane/assets/42670032/8b5c2b0a-298b-4bbb-9a1f-d3381e50969e)

**Comment by dpolivaev** [comment]
I usually do not work on issues related to PDF export because for the pdf and the svg export Freeplane uses apache https://xmlgraphics.apache.org/batik/ and it is not perfect.

**Comment by gamberoillecito** [comment]
Ok thank you, I will resort to converting text to shape and then perform OCR on the file with an external tool
