### ISSUE TITLE
Freeplane crashes when executing a script that add new child to a existing list of children, then delete it)

### ISSUE THREAD

**Issue by Bricklam** [freeplane/freeplane#1221]
in (1.11.5_pre05), Oracle Java (17)

**Describe the bug**
when I select a node that have children (any number of children nodes), and try to execute a script
that create a new child node (at the end of the children list) and then delete it (delete the last child in the list / the newly created one),
Freeplane crashes and I get these two messages:

```
"Error executing the script:
Cannot invoke "org.freeplane.features.map.NodeModel.isRoot()" because the return value of
"org.freeplane.features.map.NodeModel.getParentNode()" is null"

  and after that got this message:
"Internal error, program terminates."
```

I also got a long bug report, I pasted it in pastebin.com to avoid clutter, you can check it here:
[Bug Report in Pastebin.com](https://pastebin.com/sQTFiyzx)

**here is the script text:**
```
node.createChild("This is the Last child in a list")
lastChild = node.children[-1]
lastChild.delete()
```

**To Reproduce**
1- select any node that have children (it must have children, at least one child)
2- execute the script

**Comment by dpolivaev** [comment]
I can see the bug happening when I run the script and I can fix it.
However it produces another stack trace than the stack trace in PasteBin. 
I still can not reproduce the last one.

**Comment by Bricklam** [comment]
well. for me: it produces a similar one every time (not exactly similar report), but at least the top part is the same, here is another report: 
https://pastebin.com/LEHwjr1v

by the way: I use Oracle JDK17:
https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.exe

**Comment by dpolivaev** [comment]
Please upload some mind map where you experience this behavior, specify which node I can use to run the script, upload also your auto.properties. Given only the stack trace and the description I can not make it happen.

**Comment by Bricklam** [comment]
Sorry,
I investigated why this bug appears in some maps and not occuring in others:
I finally found that the bug is directly associated with this option (in the map style): (Style editor > Child nodes layout)

**How this option affects the bug**
if the map default style has the (Child nodes layout)  set as (Automatic), which is the default value: the bug will appear
but if the (Child nodes layout) of the map default style was changed to something else, for example (natural flow), the bug will not appear. and I mean changing it only in the (Edit Styles) window and not from the toolbar or the tools panel

I have uploaded two maps: (the first one that the bug occurs in, and the second one where the bug doesn't occur)
they are identical in everything, except onething: the (Child node layout) for the first one is (Automatic)(the default value) and for the second one is (Natural Flow)
you can see the only difference between the files by text editor in the line 12:
CHILD_NODES_LAYOUT="AUTO" 
CHILD_NODES_LAYOUT="AUTO_FLOW"

**here are the map files:**
[Two_Maps_with_different_layouts.zip](https://github.com/freeplane/freeplane/files/11710637/Two_Maps_with_different_layouts.zip)


**and here are two detailed videos explaining how to produce the bug**

1) in this video the bug occurs because the (Child node layout) in the default style is not changed, it is kept as (Automatic)(the default option)
https://github.com/freeplane/freeplane/assets/129968602/d8e57c16-0920-4607-9c9a-0ac47f5d2e0d



2) and in this video the bug cannot be produced because the (Child node layout) in the default style is set to other option than (Automatic)
https://github.com/freeplane/freeplane/assets/129968602/1ad804b1-b2e1-4e69-9b95-0cce0a9b18dc


Thanks

**Comment by dpolivaev** [comment]
Preview 1.11.5_06
