### ISSUE TITLE
Copied web content into Freeplane cannot be pasted correctly

### ISSUE THREAD

**Issue by Bricklam** [freeplane/freeplane#1225]
**Describe the bug**

I just discovered a new bug in (1.11.5_pre06) that wasn't existing in the previous version (1.11.5_pre05):

in (Google Chrome) browser: when I copy web content from the website:
[https://osintframework.com/](https://osintframework.com/)
  (which is an important website for OSINT research, and also has a similar structure to Freemind/Freeplane maps)

when I copy (list elements/nodes) from the website into the newest version (1.11.5_pre06): the pasted data gets corruped (it doesn't paste it correctly as rich text) as it used to do in the previous version (1.11.5_pre05)

**here is I copied the data (you can see the details in the posted videos):**

I select some elements (nodes) from the list in the web page, and copy them and then try to paste them into a Freeplane node (the regular paste) as child nodes

I have posted two videos to show the difference in pasting the same content into Freeplane (1.11.5_pre05) where there was no bug, and into the new version (1.11.5_pre06) where the bug exists:

**First video: in (1.11.5_pre05): no bug (the normal & expected behaviour)**
https://github.com/freeplane/freeplane/assets/129968602/38a7b192-77df-45fb-8a45-f91289d63bb6

**Second video: in (1.11.5_pre06): the bug appears (error in pasting content)**
https://github.com/freeplane/freeplane/assets/129968602/7c14d29c-aebe-4b3f-b5d0-54a7417a6313

**and I have also submitted two bug reports:**

- here is the first one is the (Automatic bug report) that appears in a (GUI) window)once the error occurs:
[https://pastebin.com/bJnp6QSV](https://pastebin.com/bJnp6QSV)

- and here the bug report stored in file: "log.0"
[https://pastebin.com/9ncmWaNu](https://pastebin.com/9ncmWaNu)

**Additional notice:**

- I noticed that the bug report complains about the HTML element "circle" included in the copied web text (rich text)
but this element didn't cause any problem in the previous version (1.11.5_pre05), here is the related line in the bug report:
```
[Fatal Error] :8:325: The element type "circle" must be terminated by the matching end-tag "</circle>".
Jun 11, 2023 2:09:40 AM org.freeplane.core.util.LogUtils severe
SEVERE: Can not create xhtml
org.xml.sax.SAXParseException; lineNumber: 8; columnNumber: 325; The element type "circle" must be
 terminated by the matching end-tag "</circle>".

```

-  Since this issue didn't exist in the previous version: (1.11.5_pre05). this indicates that this bug is
caused by new changes implemented in the newest version: (1.11.5_pre06).

- Fixing this bug should bring the same output (pasted result) as in (1.11.5_pre05) and earlier versions

Thanks

**Comment by dpolivaev** [comment]
Preview 1.11.5_07

**Comment by Bricklam** [comment]
Thanks for you work. I just tested (1.11.5_pre07) but unfortunately: it didn't work as expected
it produced a tottally different results. (the new fix removed all the HTML elemtns from the copied text), which is a bad behaviour
since these HTML tags are essential parts of the rich text and should stick with it even if Freeplane cannot display them.
I strongly need these HTML elements to stay intact (the same as the original text) because I use them in my scripts to parse and process the text

**for more clarification: here is an example:**
- in the version (1.11.5_pre05) where the paste was done correctly: 
if you selected & copied the first two nodes "Username, Email Address" from "https://osintframework.com/" page (in Chrome), and pasted them to Freeplane node, you will get a child node with the core text "Email AddressUsername",
if you checked its HTML code (HTML Code view), you can see all the attached HTML elements & tag are fully included, even the ones that are not intepreted/displayed by Freeplane SimplyHTML:
```
<html>
  <head>
    
  </head>
  <body>
    <font color="rgb(0, 0, 0)" face="Helvetica Neue, Helvetica"><g class="node" transform="translate(180,35.625)" align="start" style="letter-spacing: normal; text-indent: 0px; text-transform: none; word-spacing: 0px; white-space: normal; background-color: rgb(255, 255, 255)">
    </font><a target="_blank"><text x="-10" dy=".35em" text-anchor="end">
    Email Address</text></a></g><font color="rgb(0, 0, 0)" face="Helvetica Neue, Helvetica"><g class="node" transform="translate(180,11.875)" align="start" style="letter-spacing: normal; text-indent: 0px; text-transform: none; word-spacing: 0px; white-space: normal; background-color: rgb(255, 255, 255)"></font><circle r="6"></circle><a target="_blank"><text x="-10" dy=".35em" text-anchor="end">Username</text></a></g>
  </body>
</html>
```

* but the the problem with the fix in the new version (1.11.5_pre07): it removes all the HTML elements (keeping only "<a.." tag) 
```
<html>
  <head>
    
  </head>
  <body>
    <a target="_blank">Email AddressUsername</a>
  </body>
</html>
```


and I think that omitting or removing any HTML tag from the original text is a very bad behaviour, since it is essential part of the rich text (even if this text cannot be interpreted or displayed by Freeplane, it should maintain its full HTML code, 
because this text can be later exported out of Freeplane to another application which can display all its tags)

you can check (1.11.5_pre05): it used to do it perfectly without any problem

Thanks

**Comment by dpolivaev** [comment]
I have carefully analyzed your example and the way how Freeplane behaved before the latest changes.
Unfortunately, I come to the conclusion that it has been producing invalid xml (xhtml) content by interchanging the order of opening and closing tags.

In your example from the latest message if you concentrate on just <g>, <circle> and <font> elements you will find the following sequence of opening and closing tags:

````
<font><g></font></g><font><g></font><circle></circle></g>

````

I have seen tons of examples like that.

It happens because when very old html parser used by swing finds unknown tags it does not know if they will have closing tags. Originally in html not all tags had their closing counterparts. Therefore for me removing the tags which can not be interpreted by the swing seems to be a natural solution.

Alternatively, I could try to use a separate library (jtidy) for generating xhtml out of xml. However, I do not know xhtml produced by jtidy  would work with swing. And at the end of the day the main goal of allowing html content is rich text formatting, and unfortunately because of the transformation chain, Freeplane can not save original content coming from the clipboard - and it never happened.

For specific needs of scripting, I can suggest that you save your original content in attributes attached to nodes. But allowing to knowingly save invalid xml files which any xml processor would refuse to process seems to be not a good idea.

**Comment by Bricklam** [comment]
Thanks @dpolivaev for your work.
now I realize the depth of the problem: Freeplane cannot just continue saving bad XHTML text produced by the Swing html parser, and at the same time it would be a big setback for Freeplane to remove the HTML tags of the rich text (pasted from clipboard)
I also understand that Freeplane is not a web browser and it is not meant to preserve the original Html code, but to handle the rich text format to some extent However it would be a very good idea to keep the information of copied text (including the Html tags that are unknown) by the parser. why? I can say that it is essential for Freeplane as an (Information Manager application) to be able save and handle web content efficiently (because in today's age: the web content is the main source of information)

So, I think it is worthy to try and test a new ways for a better solution.
and your suggestion to use a separate library like "JTidy" looks very promising, in order to avoid the Swing old parser shortcoming. and it will improve Freeplane capabilities in handling Html code.

I tried to address your concern about "Jtidy" library working with Swing. and also chekced other alternatives that can provide a good solution to this problem. and found out that "JTidy" should work fine with Swing.
I also found other possible alternatives & solutions.
I had an interesting conversation with ChatGPT on this issue, where it provided many ideas:
 and I have uploaded the conversation as HTML file, you can check it here:
[JTidy & Swing Compatibility.zip](https://github.com/freeplane/freeplane/files/11728806/JTidy.Swing.Compatibility.zip)


I hope to find it useful and I would be happy to hear your response and I'm OK with any decision you make as a developer, nevertheless, I strongly vote for keeping Html tags & improving Freeplane HTML Parsing & saving capabilities
Thanks

**Comment by EdoFro** [comment]
I used once [JSoup](https://jsoup.org/) and it was developed to work with broken or bad HTML code.

From its webpage:

> ## **jsoup**: Java HTML Parser
> **jsoup** is a Java library for working with real-world HTML. It provides a very convenient API for fetching URLs and extracting and manipulating data, using the best of HTML5 DOM methods and CSS selectors.
> 
> 
> **jsoup** implements the [WHATWG HTML5](https://whatwg.org/html) specification, and parses HTML to the same DOM as modern browsers do.
> 
> -  scrape and [parse](https://jsoup.org/cookbook/input/parse-document-from-string) HTML from a URL, file, or string
> - [find](https://jsoup.org/cookbook/extracting-data/selector-syntax) and extract data, using DOM traversal or CSS selectors
> - [manipulate](https://jsoup.org/cookbook/modifying-data/set-html) the HTML elements, attributes, and text
> - [clean](https://jsoup.org/cookbook/cleaning-html/safelist-sanitizer) user-submitted content against a safelist, to prevent XSS attacks
> - [output](https://jsoup.org/apidocs/org/jsoup/nodes/Element.html#html()) tidy HTML
>
> **jsoup** is designed to deal with all varieties of HTML found in the wild; from pristine and validating, to invalid tag-soup; **jsoup** will create a sensible parse tree.

For example, in its webpage [jsoup](https://jsoup.org/) » [Cookbook](https://jsoup.org/cookbook/) » [Introduction](https://jsoup.org/cookbook/introduction/) » [Parsing and traversing a Document](https://jsoup.org/cookbook/introduction/parsing-a-document) it says:

> The parser will make every attempt to create a clean parse from the HTML you provide, regardless of whether the HTML is well-formed or not. It handles:
> 
> unclosed tags (e.g. `<p>Lorem <p>Ipsum` parses to `<p>Lorem</p> <p>Ipsum</p>`)
> implicit tags (e.g. a naked `<td>Table data</td>` is wrapped into a `<table><tr><td>...`)
> reliably creating the document structure (`html `containing a `head `and `body`, and only appropriate elements within the head)

It also let you define a **Safelist** of tags that are allowed in your HTML, so if it comes with unwanted links, cookies, etc., it can clean it.

jm2c

edo

**Comment by dpolivaev** [comment]
I don't think that most users would like to preserve tags not used for formatting, but I started a discussion https://github.com/freeplane/freeplane/discussions/1231 where you can bring your arguments.

**Comment by dpolivaev** [comment]
Preview 1.11.5_09
