### ISSUE TITLE
Note set by a script isn't reflected in note panel when Note Follows Selection is disabled

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#1227]
v1.11.5-pre06

### Actual
I have a script that gathers content from several nodes, processes it and writes the result in root's note.
I go to root, `View->Notes->Display note panel` and switch off `View->Notes->Note follows selection` so that Note Panel always displays root's note.
I move around the mind map, changing some of my nodes' content and run my script to update root's note.
Note panel's content stays the same.

### Expected
Note panel's content reflects the change in root's note

**Comment by dpolivaev** [comment]
Preview 1.11.5_14
