### ISSUE TITLE
Changing slide root after slide change during presentation doesn't work

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#1229]
v1.11.5-pre06

The new feature #1210 allows to save Jump In (view root) in addition to any existing presentations functionality.

### With the following set-up
Presentation 1
- Slide 1: View root = (true) root, i.e. jump out
- Slide 2: View root = node A, i.e. jump in
- Slide 3: View root = node B, i.e. jump in
- Slide 4: View root = (true) root, i.e. jump out

### Actual
Move from Slide 1 to Slide 2.
The entire mind map is visible.

### Expected
Jump in Node A, i.e. node A is view root, and other siblings and ancestors aren't visible

[test-FP1210-presentations-to-save-jump-in.xi.zip](https://github.com/freeplane/freeplane/files/11715386/test-FP1210-presentations-to-save-jump-in.xi.zip)

**Comment by dpolivaev** [comment]
I do not think that slide root should depend on the previous slide root.
If you deactivate the slide root, the map root becomes the slide root.
I would rather replace the toggle button by the usual button.

**Comment by macmarrum** [comment]
>I do not think that slide root should depend on the previous slide root.
If you deactivate the slide root, the map root becomes the slide root.

Looking at the XML, which part suggests that slide root is activated for slide NAME="X"?

```xml
<hook NAME="presentations">
  <presentation NAME="New presentation 1">
    <slide placedNodeId="ID_330179225" showsOnlySpecificNodes="true" showsDescendants="true" NAME="X">
      <NodesOnSlide>
        <NodeOnSlide nodeId="ID_294748816"/>
      </NodesOnSlide>
    </slide>
    <slide placedNodeId="ID_1694384354" rootNodeId="ID_1694384354" NAME="View Root A"/>
    <slide placedNodeId="ID_1572617237" rootNodeId="ID_1572617237" NAME="View Root B">
      <NodesOnSlide>
        <NodeOnSlide nodeId="ID_1572617237"/>
      </NodesOnSlide>
    </slide>
    <slide placedNodeId="ID_1152471647" showsOnlySpecificNodes="true" NAME="Z">
      <NodesOnSlide>
        <NodeOnSlide nodeId="ID_383458482"/>
      </NodesOnSlide>
    </slide>
  </presentation>
</hook>
```

The way I see it, the issue is linked to a transition between slides, not the definition of the slide.

In other words, can you modify the presentation so that transition between Slide 1 and Slide 2 results in the expected view?

**Comment by dpolivaev** [comment]
It is `rootNodeId="ID_1694384354"` and similar. If it is missed, currently the map root node is used as a slide root.
I can modify the logic. I am not sure how I like your suggestion to keep the slide root on the next slide if it is not explicitly specified.

**Comment by macmarrum** [comment]
> It is rootNodeId="ID_1694384354" and similar. If it is missed, currently the map root node is used as a slide root.

All clear. It makes sense.

> I am not sure how I like your suggestion to keep the slide root on the next slide if it is not explicitly specified.

It wasn't my intention to make such a suggestion.

What I expect is for Presentations to have the ability to transition from Slide 1 (jump out), to Slide 2 (jump in). The current functionality shows the entire mind map after this transition, whereas I expect to see Node A as the view/slide root.

I hope you can remove the label [not a bug] from the issue.

**Comment by dpolivaev** [comment]
For slides, you can not say "jump in" or "jump out" because each slide can have its own root. For example, if nodes A and B are siblings, two subsequent slides can have them as slide roots without the need of jumping out.

**Comment by macmarrum** [comment]
I use "jump in" and "jump out" only because it's how similar functionality is called in the core of Freeplane.

I am missing any acknowledgement from your side that you understand the issue I've described.
I am trying to understand what is missing in the description or how to change it so that my intended message reaches you.

I will try again.

What I expect is for Presentations to have the ability to transition from Slide 1 (no slide root set), to Slide 2 (slide root set). The current functionality shows the entire mind map after this transition, whereas I expect to see Node A as slide root and only its descendants visible, i.e. the following nodes to be hidden: root, X and its descendants, B and its descendants, Z.

### The entire mind map
![FP1229-2023-06-11_22,45,17](https://github.com/freeplane/freeplane/assets/7197131/29c7dd6e-ada1-42dc-8570-35d5c71b86bf)

### Slide 1
![FP1229-2023-06-11_22,45,43](https://github.com/freeplane/freeplane/assets/7197131/f78dd95d-b745-4443-bb84-8f4e6bb30203)

### Slide 2 transitioned from Slide 1
![FP1229-2023-06-11_22,45,58](https://github.com/freeplane/freeplane/assets/7197131/bc795b69-af9a-4c55-86f8-e934f6b8351a)

### Expected Slide 2 transitioned from Slide 1
![FP1229-2023-06-11_22,46,18](https://github.com/freeplane/freeplane/assets/7197131/aee7bd23-3402-42e1-a620-6309b18ecfe3)


Could you please confirm that you see the issue?

**Comment by dpolivaev** [comment]
I am sorry I have not checked your example before. Now I did and I confirm that the slide root is not chosen as expected if the slide is changed.

**Comment by dpolivaev** [comment]
Yes, I need to fix it

**Comment by dpolivaev** [comment]
Preview 1.11.5_08

**Comment by amariusz** [comment]
This is a nice feature. I've played with this functionality a bit and it seems to work fine on 1.11.5-pre13. 

However FreePlane asks to send bug reports with something like:

> > Exception in thread "AWT-EventQueue-0" 
> java.lang.ClassCastException: class javax.swing.plaf.basic.BasicHTML$Renderer cannot be cast to class org.freeplane.core.ui.components.html.ScaledHTML$Renderer (javax.swing.plaf.basic.BasicHTML$Renderer is in module java.desktop of loader 'bootstrap'; org.freeplane.core.ui.components.html.ScaledHTML$Renderer is in unnamed module of loader org.knopflerfish.framework.BundleClassLoader @54f9c7bd)

Complete bug report sent from the app.

**Comment by dpolivaev** [comment]
@amariusz I created a new issue https://github.com/freeplane/freeplane/issues/1251 and need more info from you
