### ISSUE TITLE
Add HiDPI Support & preferences

### ISSUE THREAD

**Issue by technosf** [freeplane/freeplane#1232]
I work on a **267 PPI** 2880 x 1920 13" display 

Initial run of _freeplane_ is microscopic. Setting Monitor Size to 39" helps some, choosing a '_flat_* theme helps more, but certain test is still minute and icon, menu bar are inconsistent.

Would it be possible to check for HiDPI displays on start, or have a HiDPI tab in Preferences so that there is a more straight forward way to consistently scale the UI?

**Comment by dpolivaev** [comment]
Freeplane has automatic HiDPI recognition where it is supported by Java namely by Windows and by MacOS.
Other OS users can configure their monitor size in the preferences, and the scaling is calculated accordingly.
The property is labeled "Monitor size (inches)"

**Comment by technosf** [comment]
Yes, as I wrote I have to set monitor size to **_3X_** its actual size to make _freeplane_ usable -  I use _Linux_. But the scaling of the UI assets is all over the place. Also I have to modify all the Font sizes to make them other than microscopic.

**Comment by dpolivaev** [comment]
The smaller monitor size you select, the bigger the fonts and UI looks. Using a larger monitor size you make the fonts smaller.

**Comment by technosf** [comment]
So there is no way to modify these in concert - On linux, you just have to juggle monitor size and fonts until it works?

**Comment by dpolivaev** [comment]
Attach screen shots of your preferences and how Freeplane looks. Actually there is usually enough ways to get it right.

**Comment by technosf** [comment]
![image](https://github.com/freeplane/freeplane/assets/535060/1b96c900-031e-4af9-991e-e6023e4bb682)

**Comment by dpolivaev** [comment]
Set monitor size to 13, menu font size to 10, toolbar icon height to 12 pt and restart

**Comment by technosf** [comment]
Thank you!
This looks great - Apologies on overthinking this, and I appreciate your help. And of course the great tool that freeplane is.
