### ISSUE TITLE
HTML styles disappear

### ISSUE THREAD

**Issue by dpolivaev** [freeplane/freeplane#1237]
Hi Dimitry, I tested the new version and found that the HTML styles I edit would automatically disappear, is this due to some changes made in the new version?
here is my node html:
![image](https://github.com/freeplane/freeplane/assets/50692082/7efde560-5b03-4028-bd72-47420b4435cf)
after I saving it, it changed to:
![image](https://github.com/freeplane/freeplane/assets/50692082/7ecfbe43-38cd-49b4-99c6-a85625a5e59d)

_Originally posted by @guoranjun2 in https://github.com/freeplane/freeplane/discussions/1231#discussioncomment-6183166_

**Comment by Bricklam** [comment]
I can confirm this bug started from version: (1.11.5_pre07) and (1.11.5_pre08),
but Not present in earlier versions: (1.11.5_pre06) and earlier

**Comment by dpolivaev** [comment]
Preview 1.11.5_10
