### ISSUE TITLE
Last character cut off when minimizing Markdown or HTML node

### ISSUE THREAD

**Issue by amariusz** [freeplane/freeplane#1242]
**Describe the bug**
When node core text format is set to Markdown and node contains multiple lines after minimizing node first line is show with last character cut off.

**To Reproduce**

1. Add new node with text: `foo<br>bar`
2. View->Control->Tool panel->Format->Core text->Format->Markdown
3. View->Minimize node (or press Alt-F3)
4. Minimized node text is "fo" not "foo"

The same result with e.g. `foo<p>bar</p>` or `foo<div>bar</div>`

I'm using Freeplane 1.11.4 on Linux. I've observed the same behaviour on Windows.

**Comment by macmarrum** [comment]
@amariusz I believe this is controlled by `Preferences…->Appearance->Size limits->Maximum shortened text 
width`. Could you set this value to a bigger number and try again?

**Comment by amariusz** [comment]
Hi. Thanks for quick reply. It was set to 100. Setting to 200 does not make a difference for "foo" string. Last character is still missing. Also last character is missing regardless if first line lenght is 3, 10 or 50 characters. 

But you're right that "maximum shortened text width" set to 3 could result in the same behaviour for this specific "foo" case .

**Comment by macmarrum** [comment]
Ah, yes, of course :blush: 
It's only the first line that is considered when minimizing a node.
Therefore it's important to count up to the first line break.

**Comment by amariusz** [comment]
@dpolivaev It seems you have already addressed this issue! :smile:  Is this correct?
Is it already available in some development build? Do you want me to test it and close the issue?

**Comment by dpolivaev** [comment]
Yes, thank you. Preview 1.11.5_12

**Comment by amariusz** [comment]
Wow! Thank you very much for implementing this change so quickly! :clap: 

I've tested it on Windows and it looks very good.

I've noticed two issues though:

- after minimizing node with single line (e.g. "foo"), text dissappears. This behaviour has changed compared to official build.
- node core text format is treated as `Markdown` even if it's set to `Text`. So after minimizing such node with text `foo<br>bar` it changes to `foo` although previous behaviour would be leave `foo<br>bar`.

(Updated formatting - backticks)

**Comment by dpolivaev** [comment]
Thank you, I'll check the minimizing of nodes with a single line.

I do not understand what you mean by the second point, could you please explain it, maybe with a screenshot?

**Comment by amariusz** [comment]
Regarding the second point.

a) Sorry, I've used the wrong quotes and that made my example confusing. 
b) It seems I've messed up something because I'm not able to reproduce it now :laughing:  It works as expected.

So please ignore it.

**Comment by dpolivaev** [comment]
Preview 1.11.5_13

**Comment by amariusz** [comment]
Works great! Thanks!
