### ISSUE TITLE
error opening command search

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1246]
**Describe the bug**
Whenever I open command search, the status bar notifies me of an error.

**To Reproduce**
1. open new map
2. invoke command search (I have remapped it to F1)
3. status bar reports error

**Expected behavior**
Expected no error.

**video**
[freeplane _ error opening command search (video).zip](https://github.com/freeplane/freeplane/files/11789339/freeplane._.error.opening.command.search.video.zip)

**Desktop (please complete the following information):**
 - OS: windows 11 Home
 - Version: 22H2  OS build: 22621.1848
 - Java Version:  17 0 7
 - Freeplane:  Freeplane-Setup-1.11.5-pre12.exe

**Comment by dpolivaev** [comment]
Preview 1.11.5_13

**Comment by kenfhill84083** [comment]
Verified working OK here.
