### ISSUE TITLE
After minimizing node with single line (e.g. "foo"), text dissappears.

### ISSUE THREAD

**Issue by dpolivaev** [freeplane/freeplane#1248]
Wow! Thank you very much for implementing this change so quickly! :clap: 

I've tested it on Windows and it looks very good.

I've noticed two issues though:

- after minimizing node with single line (e.g. "foo"), text dissappears. This behaviour has changed compared to official build.

_Originally posted by @amariusz in https://github.com/freeplane/freeplane/issues/1242#issuecomment-1597024689_

**Comment by dpolivaev** [comment]
Preview 1.11.5_13

**Comment by amariusz** [comment]
Minimizing works great now! Thank you.
