### ISSUE TITLE
Introduce a search option to ignore all kinds of white space: note cannot be searched after line wrapping

### ISSUE THREAD

**Issue by netforfreedom** [freeplane/freeplane#1260]
freeplane v1.11.4

- Under normal circumstances, this is the case:
![1](https://github.com/freeplane/freeplane/assets/39705624/6d73c17b-e2ac-4d7b-9ddb-d03489ec9dd6)

- I don't know how to solve this problem when I can't find any search results after changing lines?:
![12](https://github.com/freeplane/freeplane/assets/39705624/459108f8-61cf-4d6a-a889-90abaf4aac67)

**Comment by dpolivaev** [comment]
In western languages line breaks and spaces always separate words.
Do you need a search option to ignore all kinds of white space?

**Comment by dpolivaev** [comment]
Preview 1.12.7_03
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

The option is coupled with "ignore accents" filter option.
It is always active for the find and replace dialog, but not available for replacements in HTML content.
