### ISSUE TITLE
Are emojis / smileys supported (Linux)?

### ISSUE THREAD

**Issue by amariusz** [freeplane/freeplane#1264]
When I use FreePlane under Linux I'm not able to input any emojis (like 😂🤣👍💲⭐ etc) within node core text, details or notes. Some emojis seem to be skipped (e.g.❗), some are represented by  an empty square (e.g.💡). 

I've tried the same on Windows 10 (the same version 1.11.5-pre14, the same template, the same font - SansSerif). It seems most of the emojis work. They are black and white and rather oldish-looking but that's still very useful.

I'm wondering if there is a bug in FreePlane on Linux, something wrong with my system or if emoji support under Windows is kind of incidental?
Emojis are well supported by current operating systems and most of the apps. I suppose it's may not be the case with all Java applications?

Some additional notes:
- Copying content with emojis from text editor, to FreePlane and back to text editor preserves them.
- I'm aware of icons in FreePlane. I'm not asking about them.
- Other unicode characters like ¼ or "ó" work well.
- I'm able to see emojis after switching to Symbola font but this font is "hard to look at" for regular text.
- Emojis work in other GUI apps and terminals on my system. Although not in some Java apps (Yed for example).
- Maybe it was discussed already - if so, please let me know. Surprisingly I couldn't find  any pertinent thread.
- Sometimes invisible emojis seem to turn off antialiasing within the node.

BTW FP is great!!!

Thanks

**Comment by dpolivaev** [comment]
Emojis are represented by fonts, and unfortunately, some font types are not supported in Java and some others seeem to be not good enough. I don't think I can fix it.

**Comment by amariusz** [comment]
I understand. That's a bummer. I really hope things will change someday 'upstream' in the Java world and it will become possible.

Emoji symbols tend to be very useful in notes and prevalent in online content. I wouldn't diminish their significance in the long run. It's also much easier to input those now than in the past. I can imagine new users experimenting with Freeplane and hitting on this obstacle may get the impression it's outdated or broken and get discouraged. It takes some time on the other hand to discover all the "hidden" features and the full potential of Freeplane.

Any idea how to get Windows behavior (black and white emojis instead of squares) on Linux and why they differ? That would be probably the first time I encountered such differences between OSes in FreePlane.

One way to cope with it now, at least for content that moves between text editor and freeplane, is to substitute unicode emojis to github :emoji: format and vice versa with the script. 

Thanks again for the great tool!

**Comment by amariusz** [comment]
Update. 

> Any idea how to get Windows behavior (black and white emojis instead of squares) on Linux and why they differ? 

This behaviour is consistent between Linux and Windows with yEd graph editor. So it has probably nothing to do with FreePlane. I'll check on other distribution.

**Comment by amariusz** [comment]
Unfortunately the same results with Ubuntu 23.04. Emojis are not visible in FreePlane nor yEd. 
Also I've realized FreePlane requires Java 17 and installing newer version (18-21) is not helpful.

**Comment by amariusz** [comment]
@dpolivaev I've recently realized that other app I use sometimes - DocFetcher (https://docfetcher.sourceforge.io/en/download.html) is also built with Java and have no problems with emojis. It uses Sans / Monospace fonts. Could you consider checking how is this possible and if there's a hope for Freeplane in this regard?

BTW if emojis are not showing while previewing text files, this setting may help
`TextEncodingOverride = UTF-8`

**Comment by dpolivaev** [comment]
@amariusz could you please upload some screenshots from docfetcher using emojis so that I can see how you mean it?
Do you mean the black and white emojis?  Can you paste them here?

**Comment by amariusz** [comment]
Here's the sample screenshot. I'm able to enter emojis like 🔵🟢🟡🟠🔴 into search field and preview all kinds of emojis in text files that were indexed by docFetcher.

![240124_144456_docfetcher_emoji](https://github.com/freeplane/freeplane/assets/20703230/539f2164-049c-4ad7-8aa9-bcbaf74a3420)


(BTW searching by emoji does not work by default, but that's not the point. It's a matter of tokenization)

**Comment by dpolivaev** [comment]
Which OS do you have? Is it OS-specific? How do you enter colorful emojis in the input field?

**Comment by amariusz** [comment]
As far as I can tell all emojis are supported and have the same look as emojis in Chrome or Konsole terminal. I'm using Linux. There are many ways to enter emojis. The most generic one is copy and paste from the browser (e.g. https://beta.emojipedia.org/). In Freeplane I'm not able to obtain emojis regardless of the input method.

**Comment by dpolivaev** [comment]
Thanks, I'll have a look at what they do.

**Comment by amariusz** [comment]
This is what I see in Freeplane after copying the same text with emoji:

![240124_145828_freeplane](https://github.com/freeplane/freeplane/assets/20703230/931a85c4-de7b-4c5a-a053-7c5518741550)

Emojis are invisible, but there's a "hint" they are in the text - everything after emoji looks like antialiasing is disabled. I'm able to copy this text back to the editor and emojis are still there.

I'm using latest Debian Trixie.

**Comment by amariusz** [comment]
> Thanks, I'll have a look at what they do.

Thanks a lot!

**Comment by amariusz** [comment]
@dpolivaev did you have a chance to look into this? Is there a chance for emoji support in FreePlane similar to DocFetcher's?

**Comment by dpolivaev** [comment]
Thanks for remembering me. I do not know how to use docfetcher and I do not have any file with emojis.
Could you please upload some files containing many different emojis and explain how I can load them in docfetcher? I have no clue.

**Comment by dpolivaev** [comment]
I also do not know how I can input emoji characters into the docfetcher search field.

**Comment by dpolivaev** [comment]
Well, I was able to copy and paste the circle like emojis from your above post.

**Comment by dpolivaev** [comment]
Thanks for remembering me.

I have finally checked the source code. Docfetcher uses a Java library called SWT developed by Eclipse. It can use native implementations of UI elements. Freeplane is based on Java Swing and I do not know any easy way how they could be combined.

It explains why emojis work in Docfetcher and unfortunately does not help us to use them in Freeplane.

**Comment by amariusz** [comment]
> Docfetcher uses a Java library called SWT developed by Eclipse. It can use native implementations of UI elements. Freeplane is based on Java Swing

OK, that's too bad. Thanks for looking into it!

**Comment by amariusz** [comment]
> Emojis are invisible, but there's a "hint" they are in the text - everything after emoji looks like antialiasing is disabled. I'm able to copy this text back to the editor and emojis are still there.

I've realized that aliasing issues appear only in certain conditions. I'll post my observations here in case this could be fixed independently of emoji support.

Having following input:

    lines with emoji
        [🚩] Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has has been the industry's standard dummy text
            emoji at the beginning, multi line
        [🚩] Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has has been the industry's standard dummy text
            emoji at the beginning, multi line, minimized
        [🚩] Lorem Ipsum is simply dummy text of the
            emoji at the beginning, single line
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has has been the industry's standard dummy text  [🚩]
            emoji at the end, multi line
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has has been the industry's standard dummy text  [🚩]
            emoji at the end, multi line, minimized
        Lorem Ipsum is simply dummy text of the  [🚩]
            emoji at the end, single line


This is how Freeplane renders it:
![240830_084343_freeplane_aliasing_quirks](https://github.com/user-attachments/assets/cfb92fab-7d23-46ae-99ab-e81e5ca3fd40)

Note that aliasing issue is not present in edit mode, single line nodes and minimized nodes (even when they span multiple lines).

**Comment by amariusz** [comment]
For reference, I'm linking related discussion
https://github.com/freeplane/freeplane/discussions/2113
