### ISSUE TITLE
 Which freeplane version is working with which roan-presentation version without any errors?

### ISSUE THREAD

**Issue by michaelsjackson** [freeplane/freeplane#128]
I tried with lates freeplane, or current I should say, which is in my case 1.7.5, which I installed yesterday, and roan-presentation seems not to work here. I guess I should try with older freeplane versions then? Any tips which versions I should try? Of course removing the source of the problem would be better, but not sure if it is easy enough. Thanks in advance, and for all those great tools. I could not find any youtube videos on roan-presentation as well, I just wanted to see first how it looks and works in practice.

It says already requires freeplane 1.5, I thought it should work with later versions as well, but it seems not. Tried 1.5.21 which gives another error. So I should go back here as well it seems. Hmm.

My goal is now finding out any working combination for freeplane + roan-presentation. All I tried so far did not work, I mean working both together. If you know any working combination please comment, thanks in advance.

**Comment by michaelsjackson** [comment]
Found a working combination, freeplane 1.3.15 with roan-presentation 0.1.3, however in this freeplane version OPML import addon does not work, which is another showstopper. Plus how autozoom is implemented in this 0.1.3 is no fun to use, so best is disabling it.

**Comment by dpolivaev** [comment]
roan-presentation is not part of the freeplane project. I am not sure if it is still maintained. You can ask the last maintainer at https://github.com/vboerchers/roan-presentation

**Comment by michaelsjackson** [comment]
I see, we can consider roan-presentation as not existing.

**Comment by vboerchers** [comment]
> I see, we can consider roan-presentation as not existing.

The original author has abandoned the project but I have ported it to Freeplane 1.5.4 quite a while ago (see the link Dimitry has posted). Since I am not using roan-presentation I may or may not port it to a current Freeplane version.

Volker

**Comment by michaelsjackson** [comment]
Yes, it is not worth the effort. Zooming was not fun to use in the old version I tested. The only thing remaining is the auto-centering, but this we can have also without roan-presentation. The whole point should be the added zooming somehow.

**Comment by dpolivaev** [comment]
Consider freeplane presentations, they should be documented in the docu mind map.

**Comment by michaelsjackson** [comment]
I want something which works almost without any efforts, so the normal mindmap itself should be enough to start a presentation, it could be done with something like 'overlays' of single characters when holding a key, pressing that overlay key would fly to that entry. This would be my favourite style of using it, no extra effort, always having big picture view or sub-tree view, if you want this sometimes or the mindmap is too big otherwise, those overlays would do the rest of quick and direct navigation. Without having to setup anything beforehand each time. It should be quick and fun to use. Fun meaning mostly as direct as possible.

**Comment by dpolivaev** [comment]
What zooming logic would you need?
I have never used Roan Presentations.

**Comment by michaelsjackson** [comment]
Zooming logic could be always this:
-entire text width should fit onto screen
-if image available, entire image should fit onto screen, centered, as big as possible, even if text available its text could be ignored as the image should contain all relevant data anyway, or why did we add that picture? Fullscreen image.

From top to bottom:
-all mindmap
-subtree mindmap
-entries
(a)  only text
(b)  text with image

For navigating back, from bottom to top, commands could be:
-go one level up
-go two levels up
-go to overview which is top level

When in some level, holding a key would show all overlays, for visible elements, for easy and direct flying into that point.

This is what comes to my mind right now. Just as a general concept. Thanks for replying.

Plus the obvious candidates for navigating on same level:
-go to next on same level
-go to prev on same level
-both when reaching one end wrapping around, continuing from its other end
-auto-next on same level, would be possible when having wrapping feature, after each n seconds, e.g. n=5
-auto-prev on same level
-n could be read from the entry text itself,  :5: at the end of text for example using the tagging method of org-mode in emacs, so each entry could get its different value for auto navigation. Its upper level could auto-sum those values and display it, so you would know how many seconds are required for walking through this subtree with those tag values.
