### ISSUE TITLE
FP 11.5_15: parsing erro in a map

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#1282]
**Describe the bug**
parsing error cannot open the map

**Expected behavior**
how to solve the parsing error?

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]w11
 - Java Version FP javs

**Additional context**
[log - Copia (2).txt](https://github.com/freeplane/freeplane/files/11917708/log.-.Copia.2.txt)

**Comment by dpolivaev** [comment]
It looks like you have already been asking this question and I answered you in https://github.com/freeplane/freeplane/issues/1166. Nothing has changed since then.

**Comment by Illegit** [comment]
That part was already corrected, and there isn't any variable like that in the file, really i do not understand why sometimes happens that I get this parsing error, in the past I had even some data losses inside these files. So I become really worry to miss data.
Now in trying different solutions I have changed the file, that is still not working, it is not so critical so I restart from a copy fo 1 month ago that is working.... but in my mind it makes no sense (it must be the same)

**Comment by dpolivaev** [comment]
The attached log contained characteristic strings 

`````
SEVERE: Can not process attribute CHILD_NODES_LAYOUT = 'AUTO_BYFIRSTCHILD'
java.lang.IllegalArgumentException: No enum constant org.freeplane.api.ChildNodesLayout.AUTO_BYFIRSTCHILD
`````
If you like you can upload the map file so that I can check it.
To avoid data loss in the future I need to know which cases trigger Freeplane bugs.
You can also upload a log file showing the errors after the original file was edited.

**Comment by Illegit** [comment]
[Freeplane Instructions Evolutions parsing error.zip](https://github.com/freeplane/freeplane/files/11925651/Freeplane.Instructions.Evolutions.parsing.error.zip)
here the map
Thanks

**Comment by Illegit** [comment]
[log - Copia.zip](https://github.com/freeplane/freeplane/files/11925654/log.-.Copia.zip)
here the log file

**Comment by dpolivaev** [comment]
Preview 1.11.5_16
