### ISSUE TITLE
AddOns without "all images" throw SEVERE error in ManageAddOnsDialog

### ISSUE THREAD

**Issue by EdoFro** [freeplane/freeplane#1285]
## **Describe the bug**

When installing a new add-on or when opening the AddOns dialog, if any of the AddOns fails to have any of the images "needed" to be shown in its "page" in the dialog, then Freeplane logs a SEVERE error in the Log file.
This has allways been so, but now with the new "error sound" it is more noticeable.

The thing is that when installing a new add-on it beeps and it seems that the addon has a failure, but the only problem is that the developer didn't add images to it.

I think this should be logged as a "Warning" and not as a "Severe" error.

### AddOn dialog showing missing icons (images):
![image](https://github.com/freeplane/freeplane/assets/35700575/cd2028f5-9c00-4148-b383-b118a0bde424)

### Freeplane showing errors because of this:
![image](https://github.com/freeplane/freeplane/assets/35700575/01ea7a0a-3489-467b-b082-cea9d5df0904)

### Errors logged in Log.0 file:
```
STDERR: Jun 30, 2023 8:05:49 PM org.freeplane.core.util.LogUtils severe
SEVERE: can not load icon '/images/gptAddOn.svg'
STDERR: Jun 30, 2023 8:05:49 PM org.freeplane.core.util.LogUtils severe
SEVERE: can not load icon '/images/gptAddOn.png'
STDERR: Jun 30, 2023 8:05:49 PM org.freeplane.core.util.LogUtils severe
SEVERE: can not load icon '/images/gptAddOn.svg'
STDERR: Jun 30, 2023 8:05:49 PM org.freeplane.core.util.LogUtils severe
SEVERE: can not load icon '/images/gptAddOn.png'
```

## **To Reproduce**
1. if you have an addon instaled, that fails to have all the images
   1. open the AddOn manager. menu `Tools->Add-ons`
   2. open the different addons pages in the dialog
   3. it should beep multiple times

2. if you dont have any add on installed
   1. install an addon without images, for example one of the first versions from the chatgpt addon by barrymac
       - https://github.com/barrymac/freeplane_openai_addon/blob/main/Gpt-AddOn-v0.2.1.addon.mm
   2. try the steps in point 1.

## **Expected behavior**
It shouldn't beep or throw a severe error. It's desirable that an add-on has its own icon, but it shouldn't be a must.
A warning in log file should be enough.

Thanks in advance,

edo

**Comment by dpolivaev** [comment]
I can not reproduce the errors. 
When I install Gpt AddOn from https://github.com/barrymac/freeplane_openai_addon/releases/tag/v0.2.2 I do not see any errors when I open the dialog.
I don't know what is different.

**Comment by EdoFro** [comment]
ok. I’m going to create an addon with just one dummy script to see if the error arrises and then I will post it here with more information and instructions. 

Thanks 😉

**Comment by EdoFro** [comment]
Hi Dimitry,
Here I packed a dummy add-on. it has just only one script that displays an information dialog saying 'Hello world'

[dummy_addon-v0.1.addon.zip](https://github.com/freeplane/freeplane/files/11926694/dummy_addon-v0.1.addon.zip)


## Steps to reproduce the behavior:
1. Open the .addon.mm file into Freeplane
2. It recognizes that it's an add-on and displays
![image](https://github.com/freeplane/freeplane/assets/35700575/0281e35c-1219-4552-b7f2-f5336f014b10)

3. Click yes
4. Then it opens the Add-on manager dialog:
![image](https://github.com/freeplane/freeplane/assets/35700575/aed622e1-7bcf-45e4-a62f-84d46f4fdba8)

When this happens it throws the error. I don't even have to install the add-on. You can see in the dialog the "ICON" icon used when it doesn't find the desired resource.

5. It beeps and adds a severe error to the log and to the status bar
![added 1 error to status bar](https://github.com/freeplane/freeplane/assets/35700575/ea68391d-e98b-432a-a79b-7e26e731197b)

it adds these lines to the log file:
```
STDOUT: Jul 01, 2023 1:00:23 PM org.freeplane.core.util.LogUtils info
INFO: installing add-on from file:/C:/Users/efroh/OneDrive/Documentos/Mochila/Freeplane/dummy_addon/dummy_addon-v0.1.addon.mm
STDOUT: Jul 01, 2023 1:00:23 PM org.freeplane.core.util.LogUtils warn
WARNING: add-on has no property downloadUrl (hopefully that's not bad)
STDOUT: Jul 01, 2023 1:00:23 PM org.freeplane.core.util.LogUtils warn
WARNING: add-on has no property changelogUrl (hopefully that's not bad)
STDOUT: Jul 01, 2023 1:00:23 PM org.freeplane.core.util.LogUtils warn
WARNING: add-on has no property addonsMenu (hopefully that's not bad)
STDERR: Jul 01, 2023 1:00:23 PM org.freeplane.core.util.LogUtils severe
SEVERE: can not load icon '/images/dummyAddon.svg'
STDERR: Jul 01, 2023 1:00:23 PM org.freeplane.core.util.LogUtils severe
SEVERE: can not load icon '/images/dummyAddon.png'
```


Hope this helps

**Comment by EdoFro** [comment]
> I can not reproduce the errors. When I install Gpt AddOn from https://github.com/barrymac/freeplane_openai_addon/releases/tag/v0.2.2 I do not see any errors when I open the dialog. I don't know what is different.

Surely you had a version of that same addon that have had images. So it could find them in the images folder or in the cache.

**Comment by dpolivaev** [comment]
No, I do not see any errors installing your
<img width="1268" alt="no-error-1" src="https://github.com/freeplane/freeplane/assets/1558052/f112b5a0-6310-4b8c-8efd-c610caffaa4c">
<img width="1185" alt="no-error-2" src="https://github.com/freeplane/freeplane/assets/1558052/407d2176-1a27-4f2e-a303-3f04aca62e9c">
 dummy add-on.

**Comment by EdoFro** [comment]
did you look in the log file?

**Comment by dpolivaev** [comment]
Only after you have asked.

**Comment by dpolivaev** [comment]
Preview 1.11.5_16
