### ISSUE TITLE
Freeplane 1.10.3 on Fedora 38 does not recognise directories that are symlinks

### ISSUE THREAD

**Issue by dwlegg** [freeplane/freeplane#1286]
**Describe the bug**
Freeplane does not work with symlinks to directories on Linux.

**To Reproduce**
1. Start Freeplane.
2. Click on OpenFile icon.
3. Look for directory containing mind maps.
4. See that it is missing from the file browser thingy.

**Expected behavior**
Should show all directories, including those that are symlinks.

**Mind map files**
Not needed in this case.

**Screenshots**
I think words are ok this time.

**Desktop (please complete the following information):**
 - Fedora
 - 38
 - Java Version javapackages-filesystem-6.1.0-7.fc38.noarch
javapackages-tools-6.1.0-7.fc38.noarch
java-1.8.0-openjdk-headless-1.8.0.362.b09-2.fc38.x86_64
java-1.8.0-openjdk-1.8.0.362.b09-2.fc38.x86_64
java-11-openjdk-headless-11.0.19.0.7-1.fc38.x86_64
java-11-openjdk-11.0.19.0.7-1.fc38.x86_64
java-latest-openjdk-headless-20.0.1.0.9-8.rolling.fc38.x86_64
java-17-openjdk-headless-17.0.7.0.7-5.fc38.x86_64
java-17-openjdk-17.0.7.0.7-5.fc38.x86_64
java-latest-openjdk-20.0.1.0.9-8.rolling.fc38.x86_64
javascriptcoregtk4.1-2.40.3-1.fc38.x86_64

 - Freeplane 1.10.3 installed using flatpak on Fedora.

**Additional context**
I have my home directory on an SSD. The Documents directory is on my RAID array. My Mindmaps are in /home/me/Documents/MINDMAPS. The symlink /home/me/Documents points to /mnt/raid/blahblah/Documents, which contains the subdirectory MINDMAPS.

**Comment by macmarrum** [comment]
@dwlegg I can see symlinked directories on my Linux box (also in v1.10.3).
I know very little about Flatpak (I don't use it) but I suspect Flatpak configuration to be the culprit here.
Could you please check in Freeplane whether you can access your `/mnt/raid/blahblah/Documents/MINDMAPS` directory directly?

**Comment by dwlegg** [comment]
@macmarrum Yes, freeplane cannot even see /mnt, which is a normal directory, a mount-point:

# file /mnt
/mnt: directory
#

/mnt is not mentioned in /etc/fstab, but I don't see that that should matter, really. Thanks for looking at this.

I would happily install freeplane from RPMs, but flatpak was the first way that I found.

**Comment by dwlegg** [comment]
Have just found out how to install the latest freeplane, 1.11.4, from a .zip file.
This problem does not occur in this latest version.
Hooray.

I wonder if the version available from flatpak (1.10.3) is really rather old?

Feel free to close this 'issue'. Thanks.
