### ISSUE TITLE
Request: Add an option to NOT open a MindMap at all during start

### ISSUE THREAD

**Issue by Patronos** [freeplane/freeplane#1289]
Hi

I would like to ask for an option that tells FreePlane to not start a new MindMap when launched. Right now FreePlane loads up, starts and presents me with an empty new MindMap. This MindMap I usually close to load up another MindMap that I want to work with.

Therefore I would like to ask for a possibility to not show a new MindMap. Instead load FreePlane without a new MindMap so the user has exclusivly press <New MindMap> (made up) or <Load MindMap> without having to close a previously automatically opened one.

Thanks.

**Comment by macmarrum** [comment]
You probably have `Preferences…->Environment->Files->Skip template selection dialog` enabled. I would try disabling it. Then a simple `Esc` on Freeplane start will get you to where you want to be.

See also https://sourceforge.net/p/freeplane/discussion/758437/thread/b1bc65da4f/

**Comment by danieldownes** [comment]
It seems this is not an issue. A fresh install will prompt you to select a template.
Close issue?

**Comment by dpolivaev** [comment]
Now you can deactivate 

Preferences…->Environment->Files->Create new map on start if no maps are open
