### ISSUE TITLE
Small images cannot be resized

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1298]
I'm frequently getting trapped in a situation where I paste an image that has a very horizontal proportion (for example, a print screen of a line of text) and can't resize it. The arrow shows up, but the dragging doesn't work, so the image gets stuck with a very small size:

![image](https://github.com/freeplane/freeplane/assets/77707706/f05b8938-b433-4b55-bec1-78cc651585ad)

Even if I zoom in, the dragging still doesn't work:

![image](https://github.com/freeplane/freeplane/assets/77707706/25ae6704-43d0-47cf-8e1e-ccf419f63899)

Example map: 
[bug small image.zip](https://github.com/freeplane/freeplane/files/12009466/bug.small.image.zip)

**Comment by abc16361** [comment]
I made a double-click inside the node to make it edit in-inline and released it, then the image can be resized. Further, I attached the image on my map and it was also resizable by dragging. Your map is zoomed at 543%. If the zoom is changed, larger or smaller, the image can be dragged to resize.

**Comment by abc16361** [comment]
I tested on the original standard-1.6 new map, attached the image to a node(min width 0, max width 10cm), zoomed it at 600%, minimized the image size and saved it. The image can be dragged to resize when reopened.

**Comment by euu2021** [comment]
I tried everything with no success:

 
![javaw_wfiRD3B0fG](https://github.com/freeplane/freeplane/assets/77707706/037b201a-73d9-4e8a-a40d-cbf581089a5c)

**Comment by abc16361** [comment]
At first I thought maybe something wrong with the image, so I saved the image as another one to test with one of my scripts, and found out that it maybe is related with the image path.  The images resizable by dragging use absolute path, but the original node with the image not resizable is set on relative path. I set freeplane on absolute path, so it maybe is the reason that double-click on the node gives a response. You can try to see whether it is true. 
<img width="1039" alt="RelativePath_1" src="https://github.com/freeplane/freeplane/assets/101362122/cdfc19fc-4377-48a3-abd3-ceae63d5e481">
<img width="916" alt="RelativePath_2" src="https://github.com/freeplane/freeplane/assets/101362122/1ef8e781-2583-47c7-896c-0c436db7bf91">

**Comment by euu2021** [comment]
Using absolute path doesn't change anything for me. Still undragabble.

But, I found a workaround: right click in the image and use "reset zoom". Then, the dragging works normally.

**Comment by abc16361** [comment]
I just set freeplane on relative path, then reset it back to absolute, restart freeplane, suddenly the original image can be dragged to resize without firstly double-clicking on node. Something with the cache?

**Comment by dpolivaev** [comment]
Preview 1.11.8_07
