### ISSUE TITLE
update command search _ state checkmark on selected node change

### ISSUE THREAD

**Issue by kenfhill84083** [freeplane/freeplane#1307]
**Describe the bug**
In Command Search, the "state" indicators do not update as I expected they would while traversing.  After making a change (eg, sytle , always unfold node) -  CS does not update as you navigate thru nodes in the map.

**To Reproduce**
1. open attached map
2. select both nodes with bubble shape (2 & 4)
3. right-click one of the 2 bubble-shape nodes > right-click > check "always unfold node".
4. open CS >  type "unfold" > note the "Navigate->Fold->Always unfolded node (set/reset)" item is checked
5. click in map
6. navigate thru nodes
7. as you navigate, the state remains checked whether node is set to always unfold or not
8. on a non-bubble node, click inside CS (below the items listed)
9. the state changes
10. click on one of the bubble-shape nodes
11. the state is unchecked (even the always unfold node is set)
12. click inside CS (below the items listed)
13. this time the state does not show a check mark

**Expected behavior**
I expected that as I navigate thru the map the CS state indicators would update to show the current state of the nodes I traverse.

**Mind map files**
attached

**Screenshots**
attached

**video**
attached

**Desktop (please complete the following information):**
 - OS: Windows 11 home
 - Version 1.11.5   2023-07-16   T15:30:06Z
 - Java Version  17 0 7

**additional info**
Similar things happen when changing styles.  (see screenshot and video)

[command search does not update state (MM).zip](https://github.com/freeplane/freeplane/files/12081798/command.search.does.not.update.state.MM.zip)
[freeplane _ command search - state checkmark seems stuck (video).zip](https://github.com/freeplane/freeplane/files/12081799/freeplane._.command.search.-.state.checkmark.seems.stuck.video.zip)
![freeplane _ command search - doesn't update as I expect](https://github.com/freeplane/freeplane/assets/6380301/06a958ba-ba7a-47e0-b9d4-800bcbc7f256)

**Comment by dpolivaev** [comment]
Preview 1.11.5_18

**Comment by kenfhill84083** [comment]
> Preview 1.11.5_18

Thanks.
