### ISSUE TITLE
Map keeps opening in outline view

### ISSUE THREAD

**Issue by Lotus49b** [freeplane/freeplane#1310]
**Describe the bug**

**To Reproduce**
On opening the map it appears in outline view. I have to hit the hotkey twice to return to normal view.

Then I save the map (normal view), but when I reopen it's back in outline view.

**Expected behavior**
Stay in normal view as saved.

**Screenshots**
The opened file
![image](https://github.com/freeplane/freeplane/assets/11365744/f1914b51-c7fc-49b9-895c-35e670481597)

Saved again as normal view (didn't change)
![image](https://github.com/freeplane/freeplane/assets/11365744/3caa78d8-0c47-414c-bb43-43cc7bbc8f12)

**Desktop (please complete the following information):**
 - OS: Win10 Pro
 - Java Version 8

**Additional context**
If I edit the view manually in the raw file it will load properly, but revert back to outline view on next save.

**Comment by dpolivaev** [comment]
I am aware of the issue and I think it is fixed in the latest preview version. Can you please check it?
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

**Comment by Lotus49b** [comment]
Thanks Dimitry, that's working fine now.

Great work!
