### ISSUE TITLE
Possible interference with gnome's dark style setting

### ISSUE THREAD

**Issue by Chais** [freeplane/freeplane#1316]
**Disclaimer:**
I _think_ my issue was caused by Freeplane, but I'm not absolutely certain, as I haven't been able to reproduce it a second time. That may be due to the nature of the functionality, though. So if I'm barking up the wrong tree, please tell me and feel free to close this issue. Ideally point me to the right tree.

**Description:**
A few weeks ago I played around with Freeplane to see if it was something I wanted to use. I tried various colour schemes and landed on one of the dark ones. Maybe darcula or solarized dark, I don't remember and it shouldn't matter.

What matters is that after saving the setting a dialog popped up that offered to change the system settings to better work with the theme. As I said, if Freeplane definitely doesn't offer this, feel free to close this. For whatever reason I agreed and as a result my gnome desktop was somehow switched to the light style. I say "somehow" because the quick settings, appearance settings and dconf all still show the setting as dark style. Yet, every GTK application opens in the light style.

Changing any of these settings to light and back to dark does nothing. Resetting the appearance settings with `gnome-tweaks` or `dconf` does nothing.

**To Reproduce**
1. Switch gnome to dark style
2. Open Freeplane
3. Configure to use a dark theme
4. Agree to change system settings (might only be offered once)
5. Find gnome's settings ineffectual

**Expected behavior**
Freeplane should change the theme in a way that can easily be reverted and is well documented.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 1.11.4
 - Java Version: OpenJRE 17

**Comment by macmarrum** [comment]
Freeplane definitely doesn't offer this.

I know that KDE Plasma offers to change how GTK (GNOME) apps look like, so that it matches QT (KDE) apps. But to the best of my knowledge, GNOME Settings > Appearance is able to revert it.

If you are desperate, you can try running the following commands in a terminal (e.g. GNOME Console), then log out and back in to GNOME.

The first one creates a tar archive for backup purposes.
The second deletes the gtk rc files, i.e. settings responsible for how GTK apps look like (this is independent of GNOME settings, which are on top of GTK settings).

```bash
tar cvf gtk-rc-backup.tar.gz .gtkrc-2.0 .config/gtkrc .config/gtkrc-2.0 .config/gtk-3.0/ .config/gtk-4.0/
rm -vfr .gtkrc-2.0 .config/gtkrc .config/gtkrc-2.0 .config/gtk-3.0/ .config/gtk-4.0/
```

In you need to restore them
```bash
tar xvf gtk-rc-backup.tar.gz
```

**Comment by Chais** [comment]
Thank you. Sadly, deleting all the gtk configs didn't solve my issue. I wasn't able to reproduce the issue in a VM, either. Might try a few different mind mapping tools. Maybe I get lucky.  
Anyway, thanks again and sorry for the noise.

**Comment by dpolivaev** [comment]
@Chais Freeplane does not make any such changes by itself. But I can not say they could not be initiated by look and feels implemented by external libraries. Maybe by https://github.com/JFormDesigner/FlatLaf.
