### ISSUE TITLE
Markdown: No lines breaks appear before code block

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#1317]
When formatting a core text as markdown, linebreaks are missing before codeblocks.

https://github.com/freeplane/freeplane/assets/10260832/80a7cb8b-7e29-4696-8b04-6e9b48ab825e.mp4

[markdown.no line breakbefore codeblock.mm.zip](https://github.com/freeplane/freeplane/files/12193379/markdown.no.line.breakbefore.codeblock.mm.zip)

**Comment by dpolivaev** [comment]
If I enter your first example here, GitHub markdown also ignores the line breaks.
I don't think it is  a Freeplane specific issue. 

Let me add 5 line breaks after this line and before the code:




`````
CODE
`````
