### ISSUE TITLE
Usability / Make the current day more visible :)

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#1323]
# Problem
After a long use of freeplane I always found that an indicator for the current date was missing. Today I noticed.... there actually is one. I just can barley see it :)...lol.

I always had to reset the calender, just to see what the actual date was. Or I had to compare the system date with the caledar, which is tiresome, because the beginning of the week is handled differently. :)

![image](https://github.com/freeplane/freeplane/assets/10260832/31f81490-bc9e-4ba5-98a0-3b8cf46d0f21)

# Request
Please make the current date more visible :) How about like so.

![image](https://github.com/freeplane/freeplane/assets/10260832/77e8252d-ad14-4a50-82dc-1b57fdb35381)

**Comment by dpolivaev** [comment]
Preview 1.11.6_01
