### ISSUE TITLE
New highlighters: remove highlighter is not working after closing the inline editor

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1325]
steps:
- use a highlighter in the inline editor
- close the inline editor
- open the inline editor
- try to remove the highlighter. Doesn't work. Neither with the hotkey or navigating to:

![image](https://github.com/freeplane/freeplane/assets/77707706/8e03c690-70cc-4f81-920b-e6b0f0b2d2d1)

"Remove Formatting" works, though.

**Comment by dpolivaev** [comment]
Preview 1.11.6_01
