### ISSUE TITLE
Calendar not painting the current date in red. but the day before.

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#1329]
Hello

Excuse the bad quality of my comments in this video.

https://github.com/freeplane/freeplane/assets/10260832/2669f9b6-e9a1-488a-8783-04f2334e5fc9

# Scenario
On the 08 August I went back to my computer as usual. Freeplane is at least since the 7th. I am looking at the calendar and I am seeing the 7th shown painted in red.
![image](https://github.com/freeplane/freeplane/assets/10260832/4287ffbb-ceb5-4e98-8541-c3f97e271d38)

# Problem
It should show the 8th painted in red.

# Workaround
Restart freeplane. 
![image](https://github.com/freeplane/freeplane/assets/10260832/a3a79b68-5ec0-457a-bb3e-4d43ed5d61cd)

**Comment by dpolivaev** [comment]
Preview 1.11.6_01

**Comment by dpolivaev** [comment]
I hope that the fix works, but to be honest I have not tested it. Please share your experiences.
