### ISSUE TITLE
FP 1.11.5: Editing node details of FP 1.11.4 mindmap results in illegible details

### ISSUE THREAD

**Issue by Tom582** [freeplane/freeplane#1331]
**Describe the bug**
When editing the node details of a FP 1.11.4 mindmap with FP 1.11.5 the resulting details become illegible.

**To Reproduce**
1. Create a new mindmap with FP 1.11.4, add details to the root node and save the mindmap
2. Open the FP 1.11.4 mindmap with FP 1.11.5. The contents is correctly displayed.
3. Edit the details of the opened mindmap either inline or per CTRL-F3 with FP 1.11.5.
4. After completing the edits, the details become illegible.

**Expected behavior**
The edited details of the root node should be correctly displayed.

**Mind map files**
New_Mindmap_1-11-4.mm - Original FP 1.11.4 mindmap
New_Mindmap_1-11-5.mm - FP 1.11.4 mindmap edited with FP 1.11.5

**Screenshots**
New_Mindmap_1-11-4.png - Original correct display
New_Mindmap_1-11-5.png - Spoiled details

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 20.3
 - Java Version: openjdk 11.0.20+8-1ubuntu1~20.04

**Additional context**
Added mindmaps as zip archives.
Please let me know, if you need more information or if I can run additional tests.

![New_Mindmap_1-11-4](https://github.com/freeplane/freeplane/assets/45515358/5eb1ec8b-b166-41c3-84cc-81301cf71305)
![New_Mindmap_1-11-5](https://github.com/freeplane/freeplane/assets/45515358/5806997a-a534-4581-9175-21081bcb9075)
[New_Mindmap_1-11-4.mm.zip](https://github.com/freeplane/freeplane/files/12306787/New_Mindmap_1-11-4.mm.zip)
[New_Mindmap_1-11-5.mm.zip](https://github.com/freeplane/freeplane/files/12306788/New_Mindmap_1-11-5.mm.zip)

**Comment by dpolivaev** [comment]
Fixed
Preview 1.11.6_01 in https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

Unfortunately, the fix can not recover the maps saved with the previous version 1.11.5 automatically, but you can change the formatting using the editor.

**Comment by Tom582** [comment]
Hi Dimitry,

thanks for your quick reply and the fix. Fortunately, I noticed the issue right in the first 1.11.4 mindmap that I was editing with 1.11.5. :-)

Looking forward to 1.11.6.
Tom

**Comment by dpolivaev** [comment]
Please install and test the preview version at the above link.
I can create bugs and fix bugs, and I need your help in testing before the version can be released as stable.

**Comment by Tom582** [comment]
You're welcome.

In FP 1.11.6-pre01 the issue is gone.

Thanks
Tom
