### ISSUE TITLE
html code appearing instead of title-string when copying a URL from browser address window with ctr c, ctr v

### ISSUE THREAD

**Issue by dominiklenne** [freeplane/freeplane#1332]
**Describe the bug**
Normally, URLs copied from the MS Edge browser via ctr c ctr v appear as a blue, underlined title-string. This makes working with URLs nice and fluid. (Does not work with OPERA, but this BR is not about this fact.)
With some websites though, they appear as html-code. (see attached screenshots)

**Steps to reproduce the behavior:**
Copy URL from browser address bar via ctr L - ctr C.
Select a node in mind map, copy URL to it via ctr V.

**Result with some websites:**
HTML code appears as code like this:

```
 <html>
  <body>
    <a href="https://www.patreon.com/posts/early-access-to-87448882?utm_medium=post_notification_email&utm_campaign=patron_engagement&utm_source=post_link&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWRpc19rZXkiOiJpYTozNDFlYzRiNC01MzI3LTQyMjQtOWJjMy05NjcyNDRiZTlkM2UiLCJwb3N0X2lkIjo4NzQ0ODg4MiwicGF0cm9uX2lkIjoyMjc3MTcyNn0.-EitUM_LRGk7HqfcnfTLoRSmMl48pS5bW_63HiR267A">[Early access to this week's video | Patreon](https://www.patreon.com/posts/early-access-to-87448882?utm_medium=post_notification_email&utm_campaign=patron_engagement&utm_source=post_link&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWRpc19rZXkiOiJpYTozNDFlYzRiNC01MzI3LTQyMjQtOWJjMy05NjcyNDRiZTlkM2UiLCJwb3N0X2lkIjo4NzQ0ODg4MiwicGF0cm9uX2lkIjoyMjc3MTcyNn0.-EitUM_LRGk7HqfcnfTLoRSmMl48pS5bW_63HiR267A)</a>
  </body>
</html>
```

**Expected behavior**
The title string of  the web page appears blue and underlined as a clickable link.

**Workaround:**
Delete the part after the "?" in the URL before copying it into Freeplane. 

**Mind map files**
[testmap.zip](https://github.com/freeplane/freeplane/files/12312486/testmap.zip)

**Screenshots**
![image](https://github.com/freeplane/freeplane/assets/3583902/a6adcba6-6143-4053-a375-54fcd822e489)

**Desktop (please complete the following information):**
freeplane version 1.11.5
OS: W10

Browser: Edge

**Additional context**

**Comment by dpolivaev** [comment]
https://github.com/freeplane/freeplane/issues/1349

**Comment by dpolivaev** [comment]
Preview 1.11.6_04 has the fix
