### ISSUE TITLE
Pressing Cancel when exiting FP still closes some documents

### ISSUE THREAD

**Issue by sifran-github** [freeplane/freeplane#1333]
**Describe the bug**
I think that its an issue between a bug and a feature. I decided to write it as a bug.

This is the scenario:
1. You have multiple open documents, some of them are saved and some unsaved.
2. You exit Freeplane.
3. In the dialog box that is asking you if you want to save your unsaved documents, you click cancel.

The current result: All the saved documents are closed. Only some of the unsaved documents are still open.
The expected behavior: If you click Cancel at any time, no document will be closed. It will cancel the entire closing process.

**Additional context**
I think that the algorithm can be done in steps:

1. UNSAVED - deal with the unsaved docs. for each one, ask the user about it. save=save, cancel=stop the entire operation.
2. ALL - if we get here, after the user didn't cancel the operation (by clicking cancel), close every map and close FP.

**Comment by dpolivaev** [comment]
It has always been like that.

**Comment by sifran-github** [comment]
I understand. but It is just a bit annoying for me. i will explain:

First of all, It can happen when:
1. I accidently close Freeplane.
2. I close Freeplane but I didnt notice that there are some unsaved maps.

In both cases I want to click "cancel" and handle this manually.
So I click cancel, but then only part of the documents are left open...

and it is even more annoying because.... before, for example, If I had a set of 10 documents that were always open, and I usually closed and opened freeplane, they were already opened for me. Freeplane remembers the open documents which is nice.

but now.... when i clicked cancel... and only part of the documents are left open..... i have to manually set the environment again: open them again, sort them with the exact order that they were opened.... then making sure that everything is saved (otherwise it will happen again).... and only then I will close freeplane.

I prefer to avoid this by my suggested change.

**Comment by theelectricsoul** [comment]
INteresting. This is what I expect :)

**Yes**
Save the file :)

**No**
Close file without saving

**cancel**
Cancel whole operation and return to Freeplane

**Comment by dpolivaev** [comment]
Preview 1.11.8_01
