### ISSUE TITLE
Usability / Selecting the same filter again should reapply the filter

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#1339]
Hello

See [Video](https://github.com/freeplane/freeplane/assets/10260832/6d0f42b6-c718-4950-bf18-779dbd9b803f) for full details.

# Scenario
The user applied a filter and then kept editing the map. Now the user chooses to apply the same filter again, by selecting it from the drop down menu again. 

# Expected behaviour
The selected filter will be applied

# Actual behavior
Nothing happens

# Problem
If the filter has been applied before and is being shown in the filter field 
![image](https://github.com/freeplane/freeplane/assets/10260832/39d9b330-b32d-4c01-b3b2-dc2deceb7074)
reselecting the same filter won't trigger any filtering again.

# Workaround
Using this button.
![image](https://github.com/freeplane/freeplane/assets/10260832/cddf3bd9-5f04-4d91-9af4-a08c4f1a3992)

# Comment
This behaviour might not be intuitive. Wasn't for me at least :) It feels buggy if I cannot reselect a filter. I was wondering for around 5 minutes and kept clicking and clicking until the haze in my head cleared up. :)

**Comment by dpolivaev** [comment]
Preview 1.11.7_03
