### ISSUE TITLE
Hyperlink tag <a> generates error when using 2 URL parameters

### ISSUE THREAD

**Issue by apaza610** [freeplane/freeplane#1349]
**Describe the bug**
When writing an <a> tag using an href with 2 URL variables an error sound is generated

**To Reproduce**
Write the following <a> tag in freeplane
`<a href="http://localhost/apz/CursoBlender/Terrenos/?t=120&v=1">TheTutorial</a>`
See error

**Expected behavior**
Older version of freeplane (1.11.4) has no problems with these kind of hyperlinks.

**Screenshots**
![error](https://github.com/freeplane/freeplane/assets/10149862/e87de4ee-3107-4964-b6bf-3fa3924f352e)

**Desktop (please complete the following information):**
 - OS: Win10
 - Java Version 17

**Comment by dpolivaev** [comment]
Preview 1.11.6_04

thanks for reporting
