### ISSUE TITLE
Working with Google Drive

### ISSUE THREAD

**Issue by mozgermi** [freeplane/freeplane#1350]
-Moved mindmap file to Google Drive and created a shortcut on my Windows desktop so that I have a live backup.
-Anytime I edit and save the file, a Confirmation dialog pops up with the following message "Mind map file was changed by another program. Reload?" even though I am the only one using the program.
-Checking the "Don't ask me again." does not help because the dialog comes back again.

-Minor issue: There is a ? icon but it is not associated with any help.

Thanks
![javaw_8M7z5tBMq1](https://github.com/freeplane/freeplane/assets/91433/2de886dc-53d2-4891-95b5-e13d8ffd4488)

**Comment by dpolivaev** [comment]
I can not reproduce the problem:  if I click on `Don't ask me again` and then on `No` the dialog is not shown again.

**Comment by mozgermi** [comment]
Made a video to reproduce https://drive.google.com/file/d/1AWZARsPfa2nRD9dP4jaJ8SQzmH7TYVv8/view?usp=sharing
hope it helps.
Thanks

**Comment by dpolivaev** [comment]
Thanks for sending the video.
"Don't ask me again" in this dialog is applied only if you select "No".
If you select "Yes", the dialog is shown each time when external program changes the file time stamp because "Yes" means "Reload the map from the external drive now".

In the video you have not shown how the program acts if you select the check box and click on "No" afterwards. This is the only way how the dialog can be disabled.

**Comment by mozgermi** [comment]
The weird thing here is that it was not changed or even opened by another program. So why would it think that way? 

Thanks for the "No" heads-up :) BUT, I opened another instance of the same file (try to replicate "was changed or even opened by another program" The second instance gave me the same dialog which is OK. However, the first instance, since I clicked NO did not give me any warning at all. 

How does Freeplane check changes on multiple instances? Does it check the time stamp or is there a temp lock file I do not know. The issue also may be related to Google Drive.

Another problem just occurred. When I closed the second instance with some changes it asked me to save naturally, which I did and closed the second instance. The first one (even though there were some changes on the file) did not give me any warning whatsoever but asked me to save and when I saved it the changes made on the second instance were gone (probably because of NO)

I tried it on OneDrive. It behaved differently. This time no dialog box message on a single instance. But when I opened two instances of the same file and made changes to one, there was no warning that it was changed by another instance.

I hope this helps.

**Comment by dpolivaev** [comment]
Settings are loaded when you start Freeplane and saved when you end Freeplane.
If you edit Freeplane preferences having multiple instances open don't be surprised if the settings are not saved or loaded as you want.

**Comment by dpolivaev** [comment]
I have read that Google Drive indeed might change the time stamp. Blame them not Freeplane.

**Comment by mozgermi** [comment]
I am not blaming Freeplane or anybody. I am happy with Freeplane and thank you for creating. I'm merely trying to help make Freeplane better.

**Comment by dpolivaev** [comment]
Yes sure, I appreciate it.

**Comment by ArNicoS** [comment]
I had the same issue. Apparently the solution was easier than expected.  Somehow I thought it was necessary to press yes to implement the request to "not show again" the message.

Thank you for the explanation and your work!
