### ISSUE TITLE
Multiple icons on a same node

### ISSUE THREAD

**Issue by jcdouet** [freeplane/freeplane#1351]
Description : On my laptop Ubuntu, for any mindmap and any node, I want to put multiple icons at once on a node, but Freeplane does not seem to accept it. Typically, I want to write « eleven » using twice the icon « one ». Then icon « one » behaves like a toggle, that is, if I add another « one », the first icon disappear, and there is no icons left at all.

files « auto.properties » and « accelerator.properties » in the « tmp.zip » archive below…

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3
 - Version Jammy
 - Desktop : Gnome 42.9
 - Java Version :
       openjdk 11.0.20 2023-07-18
       OpenJDK Runtime Environment (build 11.0.20+8-post-Ubuntu-1ubuntu122.04)
       OpenJDK 64-Bit Server VM (build 11.0.20+8-post-Ubuntu-1ubuntu122.04, mixed mode, sharing)

[tmp.zip](https://github.com/freeplane/freeplane/files/12387830/tmp.zip)

**Comment by dpolivaev** [comment]
Preferences…->Behaviour->Remove icon if exists

**Comment by ajaberi1360** [comment]
hello
