### ISSUE TITLE
FP 1.11.6_04: paste on a selection doesn't work as before FP versions

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#1352]
**Describe the bug**
just discovered that pasting nodes to a selection of other nodes doesn't work in FP 1.11.6_04, it pastes only into the 1st node.

**To Reproduce**
1. select some nodes (more than one)
2. paste on them one or more nodes previously copied
3. it will paste only to the 1st of them

**Expected behavior**
Pasting on allof the selected nodes

**Mind map files**
none

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] W
 - Version [e.g. 22] 11
 - Java Version: FP installed

**Additional context**
none

**Comment by dpolivaev** [comment]
Version 1.11.6
