### ISSUE TITLE
Out of Memory Error on Export to PDF, PNG

### ISSUE THREAD

**Issue by hexatrope** [freeplane/freeplane#1356]
**Describe the bug**
I tried exporting my mind map, and got an out of memory error. This happened when going to both PDF and PNG. Note that I was a Freemind user from 2007 until just recently, and I did these exports in Freemind countless times, and on much larger mind maps. As a test, I tried doing this on a test map with just 2 nodes. This was after restarting the application. It did output to a PNG, but failed again on the PDF.

**To Reproduce**
1. Go to Export Map
2. Click on PDF or PNG
3. See error

**Expected behavior**
I expected to get a PDF or PNG as output. The PDF was 0 bytes, and the PNG never was created.

**Mind map files**
See attached

**Desktop (please complete the following information):**
 - Mac OS
 - Version: Ventura
 - Application Version: 1.11.5
 - Java Version: 15.0.8

[Bug Report Map.mm.zip](https://github.com/freeplane/freeplane/files/12403678/Bug.Report.Map.mm.zip)

**Comment by euu2021** [comment]
Maybe this helps: #127 or #351

**Comment by dpolivaev** [comment]
"Out of memory" can happen, and I do not consider it generally a bug.
