### ISSUE TITLE
Keep panning the mindmap to the left when a node is dragged to the right edge of the window

### ISSUE THREAD

**Issue by cdwijs** [freeplane/freeplane#1363]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of why you need it. Ex. When I want [...] I can not get it done because of [...]

My mindmap is too large to fit on my screen. I want to drag and drop a node onto another node that's currently not in view.  This is hard to do, as the mindmap doesn't move when I drag the node I want to move to the edge of the window. The mindmap actually does move slowly when I drag the node to close to the edge of the window, but it stops when the mouse gets closer to he edge of the screen.

My problem would be solved if the mindmap keeps moving when the node is dragged close to the edge of the window. See the below screenshot:
**Additional context**
![image](https://github.com/freeplane/freeplane/assets/8469638/a81164b8-38f3-42c3-9455-e8db0f7deab9)

My versions:
Freeplane 1.11.5
java 17.0.8
uname -a
Linux cedric 6.4.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Aug 2023 16:02:01 +0000 x86_64 GNU/Linux

**Comment by euu2021** [comment]
For faster drag and drop across long distances: I just found that, during the drag and drop operation, if you scroll the mouse wheel, WHILE moving the mouse, the screen scrolls, and that's faster than using the screen corners. Also horizontally if you use the Shift modifier.

**Comment by dpolivaev** [comment]
I increased the margins where auto-scroll is applied when a node is dragged and increased the auto-scroll speed, the closer to the window edge the higher.

Preview 1.11.7_03
