### ISSUE TITLE
 Error opening the linked file if the file name or file path is not in English

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1370]
Describe the bug:

Hello and thanks. When the name of the file we want to define a link to is non-English (such as Farsi or Arabic. For example, the file name is «علی » ), it causes Freeplane software to not open that file, it only opens the path of that file in Windows Explorer.

The above problem also happens when there is a non-English name in the corresponding file path.
For example, if the path of the file is: C:\New Folder\محمد\ .teach.docx
If all path words are English and the file name is English, the linked file will be opened.
These two bug do not happen in Freemind software.

OS: windows 11
Freeplane version: 1.11.6

![Untitled](https://github.com/freeplane/freeplane/assets/38586259/c8552822-6aa3-4a4e-92ec-652fb7b5f0b3)

**Comment by aaa1386** [comment]
This bug really exists in the software, so far no one has responded. I hope they will fix this in the next software updates.

**Comment by dpolivaev** [comment]
I am sorry. I do not know the characters you use. If you attach a mind map file having a name containing the mentioned characters I could try to debug it, but even in this case I do not know if it can be fixed.

**Comment by aaa1386** [comment]
Hello, thank you for your help.

The language in which I have written the name of the file or folder is Persian. If you install the Persian language in your Windows, you will notice the bug better

1- I prepared the items you requested in a zipped form.
2-The path of the links that I have defined inside the Freeplane file is different from the path you download the files into your system, re-introduce the links inside the Freeplane file to the files inside the copied zip folder.
3- Open the links inside the freeplane file and you will notice the bug. The linked file is not opened. Only the path is opened.

The problem seems to be a right-to-left or left-to-right interference.


I have zipped the files and folder that you need to link to reveal the error⬇️⬇️⬇️
[فایل های تصویری.zip](https://github.com/freeplane/freeplane/files/12588357/default.zip)

mind map file zipped⬇️⬇️⬇️
[آزمایشی.zip](https://github.com/freeplane/freeplane/files/12588419/default.zip)

**Comment by aaa1386** [comment]
I tried to give a clear explanation about the bug but got no response. This bug has made working with the software challenging for me
  This bug exists in linking for Persian and Arabic languages. I did not test other languages.
I hope the producers of Freeplan will fix this bug in the next update. I thank them for their efforts

**Comment by aaa1386** [comment]
Interestingly, the file I made with Freeplane software and the mentioned error is in it, when I open that file with Freemind software, there are no bugs and the linked files open well.

**Comment by dpolivaev** [comment]
I want you to know that Freeplane is my spare time project and I only have time for it on the weekends. 
During this time I work on the issues in an order I find the best in terms of effort and impact - ratio.
If you feel like your request is forgotten you might add a comment, but now I would appreciate it if you could just wait until I find some time for it.

**Comment by aaa1386** [comment]
Thank you for helping me. It's okay to work on this whenever you can.
I wait

**Comment by aaa1386** [comment]
🌺🌺

**Comment by ajaberi1360** [comment]
Hello, Mr. Dimitry Polivaev. Thank you for your efforts.
I did not understand the meaning of the link you posted. Does this mean that this problem will be solved in the next software update? Or that I have to do something special now to solve the problem. If so, is it possible for you to give a clear explanation?

**Comment by aaa1386** [comment]
@dpolivaev Hello
Hello
I downloaded the software that you updated.
All the problems I had raised on this page have been solved. Thank you
I have shown the only other bug in the video below. When we open the freeplane file from outside the software, it gives an error, but it opens from inside the software


https://github.com/freeplane/freeplane/assets/38586259/db6312b4-ed18-43fb-983a-937708c942f2

**Comment by aaa1386** [comment]
Files required for testing

[files.zip](https://github.com/freeplane/freeplane/files/12706215/files.zip)

**Comment by dpolivaev** [comment]
As far as I know, it is a bug in Java and I have no fix for it.

**Comment by aaa1386** [comment]
Thank

**Comment by aaa1386** [comment]
> As far as I know, it is a bug in Java and I have no fix for it.

I'm sorry - I have already sent you the necessary files to test this error that was raised in this topic - the problem is caused by files with names other than English or file path where there is at least one folder with a non-English name. will be
  I recently tested and found out that there is no problem when I drag the files into the software, but when I open the same file with double click, it has two modes. The first mode is when the software is not open, in this mode the file is opened. But an error message comes at the beginning, which can be edited by closing that message
The second case is when the software is open and we want to open it by clicking on the file. In this case, the same error message appears, but the file does not open.

These errors do not occur with Freemind software

**Comment by dpolivaev** [comment]
Sure it is a well-known Java problem.
Freemind might have used some work-around.

**Comment by aaa1386** [comment]
This was a big problem for me. Thank God, a solution was found.
If we adjust the region settings as shown below, the problem will be solved.
Be sure to activate the checkbox.

![image](https://github.com/freeplane/freeplane/assets/38586259/33f47ed0-039a-4217-87af-1abad01bdf91)
