### ISSUE TITLE
Keep non CSS attributes on span tag (shtml)

### ISSUE THREAD

**Issue by dpolivaev** [freeplane/freeplane#1372]
### Discussed in https://github.com/freeplane/freeplane/discussions/1371

<div type='discussions-op-text'>

<sup>Originally posted by **doctomlug** August 31, 2023</sup>
Sorry for being late to the html tag party.

My scripts use <span> tags for highlighting etc. and it is important for the script to be able to detect its "own" highlighting (e.g. to remove it selectively). So far I used the class attribute as an indicator, as the span tag was not removed and the attributes were left as is this worked well. 

Since the last update to 1.11.6 the class attribute gets removed and I am left with no (simple) way to detect the source of the span tag.

I tried a quick "workaround" by introducing bogus style information but this gets detected and removed as well. 

Is there a simple way to expand the html-handling to conserve the class attribute and its value? It has been ignored by the rendering engine so far and probably still is.
A more complicated solution might be to remove the unsupported tags but leave attributes of supported tags like span or p unchanged. 

Thanks</div>

**Comment by doctomlug** [comment]
[class example.zip](https://github.com/freeplane/freeplane/files/12488220/class.example.zip)
The example contains the highlighting generated by a script. It uses a style tag which is visible by looking at the save file as text file but hidden in the html-tab of the node editor. It contains the class and a style attribute. The example is generated with version 1.11.4

In 1.11.6 the span tag is displayed with style attribute in the html view but without the class attribute. 

Thanks for the support

**Comment by doctomlug** [comment]
Update:
I just opened the example in 1.11.6 (other machine) and examined the save file. The class attribute is still there but the html gets changed yielding my regex useless. 

I was unaware that the class is not shown in the html-editor in the old version as well (forgot?).

I think you can consider this issues solved and close it.

Is there some documentation on the behavior in terms of supported / removed html-tags and html-reformatting available somewhere (lib or similar)?

Thank you

**Comment by doctomlug** [comment]
I did some more tests. It is still an issue. As I did not get the included html-code formatted properly, please check out the attached message.
[message.zip](https://github.com/freeplane/freeplane/files/12495391/message.zip)

Thanks

**Comment by dpolivaev** [comment]
I know what happens and I am fixing it

**Comment by dpolivaev** [comment]
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
Preview 1.11.7_pre01

**Comment by doctomlug** [comment]
Great! Thank you so much for the quick fix. The scripts work again with the .7 version
