### ISSUE TITLE
Connector inclination defined on Connector Style to be applied when Style is assigned

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#1374]
I have written a script that compares the current mind map with its older version and marks changes using Styles with Connector → https://github.com/macmarrum/freeplane-scripting/blob/main/src/scripts/compareMindmap.groovy

In `Format->Manage Styles->Edit styles`, I define the connectors to have the desired inclination.

![diff-styles](https://github.com/freeplane/freeplane/assets/7197131/f6265f07-6049-4126-898a-093502efcc64)

But when I apply the style, the inclination is ignored.

![diff-styles-in-use](https://github.com/freeplane/freeplane/assets/7197131/7b5e99b7-9b88-414d-ae4d-c530892c22fb)

It would be great for Connector Style to apply its inclination when the style is assigned – either automatically via `assignsNodeDependantStylesToNewConnectors` or manually via the Connector dialog.
If no inclination is set in `Format->Manage Styles->Edit styles`, I propose that the original inclination of the Connector is kept unchanged.

[compare-mindmap-new~diff.mm.zip](https://github.com/freeplane/freeplane/files/12489626/compare-mindmap-new.diff.mm.zip)

**Comment by dpolivaev** [comment]
done
