### ISSUE TITLE
Mouse wheel doesn't work well during drag and drop operation

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1377]
First mentioned at https://github.com/freeplane/freeplane/issues/1363#issuecomment-1703927301

- start the drag and drop operation. I.e., click on a node, hold it, and move the mouse a little bit
- use the mouse wheel. Nothing happens.
- now, make dummy movements with the mouse while using the mouse wheel. All the mouse wheel actions work fine: up and down for vertical scroll; horizontal scroll with the Shift modifier; zoom in and out with the Control modifier.

This is relevant, because those mouse wheel actions can make the drag and drop operation more fluid.

**Comment by dpolivaev** [comment]
It seems to be not possible by OS design, see https://stackoverflow.com/questions/17726152/how-to-scroll-with-wheel-while-dragging-in-jtable-and-jscrollpane

**Comment by euu2021** [comment]
Interesting. Thanks.
