### ISSUE TITLE
Nodes start arbitrarily folded when saved as unfolded.

### ISSUE THREAD

**Issue by safield** [freeplane/freeplane#138]
Freeplane version 1.61.3
OS: Linux Mint 19.1

I unfold all the nodes in my mind map. Then I save.

When I subsequently open the mind map, the root node is unfolded, one tier 2 node is folded, the other tier 2 node is unfolded, and in that node the next tier is all folded.

Even if I change the fold configuration, then change some text (since it seems like fold structure is not considered a change), and then save, it will still open in the arbitrary folded state.

**Comment by dpolivaev** [comment]
Set Preferences -> Environment -> Save -> Save Folding -> Always
