### ISSUE TITLE
The layout of the content on the page may display disorderly during mouse clicks or movements

### ISSUE THREAD

**Issue by msglog** [freeplane/freeplane#1383]
**Describe the bug**
The layout of the content on the page may display disorderly during mouse clicks or movements

**Expected behavior**
The layout of the content on the page may display disorderly during mouse clicks or movements

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Organization:   N/A
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 25 Model 80 Stepping 0 AuthenticAMD ~3201 Mhz
BIOS Version:              LENOVO GKCN60WW, 23/3/7 星期二
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             zh-cn;Chinese (China)
Input Locale:              zh-cn;Chinese (China)
Time Zone:                 (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi
Total Physical Memory:     32,620 MB
Available Physical Memory: 5,817 MB
Virtual Memory: Max Size:  49,406 MB
Virtual Memory: Available: 7,220 MB
Virtual Memory: In Use:    42,186 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\OBJ
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5029718
                           [02]: KB5012170
                           [03]: KB5029351
                           [04]: KB5028756

 - Version ：1.11.6
 - Java Version ：javac --version 11.0.12

<img width="622" alt="_2023-09-06_13-04-21" src="https://github.com/freeplane/freeplane/assets/34530046/dedb3602-0730-4605-8f86-cf6e079c4773">

**Additional context**
<img width="992" alt="_2023-09-06_13-05-18" src="https://github.com/freeplane/freeplane/assets/34530046/d42c58f1-3738-46fe-a3ac-768c1d7492ab">

https://github.com/freeplane/freeplane/assets/34530046/c3a02d30-c817-4c5c-911d-3c8700e4b6ed

**Comment by dpolivaev** [comment]
See https://github.com/freeplane/freeplane/issues/1348

**Comment by msglog** [comment]
<img width="1260" alt="_2023-09-08_11-23-51" src="https://github.com/freeplane/freeplane/assets/34530046/5ab61c0c-be2c-4e64-baae-0841e831a057">


> See #1348

I use only one display


@dpolivaev
