### ISSUE TITLE
Timestamps in .properties files

### ISSUE THREAD

**Issue by ls-1N** [freeplane/freeplane#1385]
**Is your feature request related to a problem? Please describe.**
I have a minor issue. When I want to sync my Freeplane config between multiple devices I get a lot of noise from timestamps being at the head of `auto.properties`. Specifically, this means that in git this file will show up with a change, after each usage of Freeplane. Similarly, I am getting frequent sync conflicts on Nextcloud (what I use for Freeplane config and documents now), with the timestamp being the only change in the file:
![image](https://github.com/freeplane/freeplane/assets/9165395/9122115e-18ae-46a9-9559-4ba966b98b45)

**Additional context**
I am talking about the second line in `auto.properties`:
```
#Freeplane 1.10.3
#Wed Sep 06 11:19:37 CEST 2023
filter_toolbar_visible=false
show_menu_icons=true
...
```
Similar timestamps might be in other files - I didn't check. I don't see the added value of these timestamps but this is just my use case - maybe they are useful to or needed by others. 🙂

It seems this is a common issue with Java. [Here](https://stackoverflow.com/a/39043903/4335271) is a suggestion on StackExchange for a workaround. As mentioned on the link, sorting of the keys might also be needed for consistency of file contents.
If this change were approved, I could try to implement it myself.

**Comment by dpolivaev** [comment]
I implemented it using the workaround you suggested. However, I had to fix their code first.

**Comment by dpolivaev** [comment]
Preview 1.11.7_03
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

**Comment by ls-1N** [comment]
Wow, thanks @dpolivaev 🙏. That was super fast!
