### ISSUE TITLE
fail to download freeplane from sourceforge

### ISSUE THREAD

**Issue by huster-songtao** [freeplane/freeplane#1387]
https://sourceforge.net/projects/freeplane/files/latest/download

![微信截图_20230907153553](https://github.com/freeplane/freeplane/assets/94954133/6f16635d-51a5-4143-85b8-7ed31a8b894b)

**Comment by dpolivaev** [comment]
I do not understand which problem you are reporting.
And in any case, I think you should report it to source forge support because they own the servers.
