### ISSUE TITLE
Unfold on Drag&Drop not working anymore

### ISSUE THREAD

**Issue by bekoeppel** [freeplane/freeplane#1389]
**Describe the bug**
On older versions of Freeplane, I could drag a node, over another node and the unfold mark appeared. If I then moved my mouse over the unfold mark, the node would unfold.  With 1.11.6, this does not work anymore.

**To Reproduce**
1. Drag a node
2. Move mouse over a node that has children, and is folded
3. See folding mark appear of that node
4. Move mouse towards folding mark

**Actual behavior**
* Folding mark disappears as soon as I leave the node box
* Makes it impossible to unfold the node while dragging another node

**Expected behavior**
* Folding mark stays there
* On hovering folding mark, node unfolds

**Screenshots**
On 1.9.8:
![Screencast_turbot muasch ch_2023-09-07_12-40-31](https://github.com/freeplane/freeplane/assets/1185824/6583e50f-f080-46db-9232-5c0d4a12b057)

On 1.11.6:
![Screencast_turbot muasch ch_2023-09-07_12-41-06](https://github.com/freeplane/freeplane/assets/1185824/42b87312-4fc9-47ed-9106-3386e474e9ae)

**Desktop (please complete the following information):**
 - OS: Linux 5.15.0-78-generic
 - Freeplane Version: 1.11.6
 - Java Version: 17.0.8

**Comment by dpolivaev** [comment]
Preview 1.11.7_02
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

**Comment by bekoeppel** [comment]
Thank you! Confirmed it works now again :+1:

**Comment by bekoeppel** [comment]
Sorry I think this should be reopened; or let me know if you prefer me to raise a separate bug report.  I believe there is a regression now on 1.11.x aa2085b18:

When I drop a node quickly, I expect that the target node does _not_ unfold, i.e. the following behavior:
- behavior 1: drag a node onto a folded target node, keep mouse clicked, wait a little delay → target node unfolds, and allows to navigate into the subtree
- behavior 2: drag a node onto a folded target node, and release it immediately → node is placed as child of target, but target remains folded

Behavior 2 is broken now.

**To Reproduce**
Steps to reproduce the behavior:

1. Drag a node
2. Move mouse over a node that has children, and is folded
3. Immediately drop the node (i.e. release mouse)

Actual behavior
* Node is inserted as child of the target node
* (sometimes with a tiny delay) the target node is unfolded

Expected behavior

* Node is inserted as child of the target node
* Target node remains folded


**Screenshots**
![Screencast_turbot muasch ch_2023-09-11_19-26-41](https://github.com/freeplane/freeplane/assets/1185824/62f8e911-1a2e-4479-897b-74c37e9c9130)

**Comment by dpolivaev** [comment]
Thank you for the clear message, I fixed it.

**Comment by bekoeppel** [comment]
Wow that was fast! Thank you, works now :+1: 

And a big thanks for developing Freeplane! I use it every day extensively :-)
