### ISSUE TITLE
Destination node marking when linking one node to another node

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1393]
When we link to a node, a green arrow mark is placed on the source node, but no mark is placed on the destination node. It is requested to automatically place a token on the destination node. This sign can be a green ball or the word "LINKED" or something else
![1402_06_18_20_04_05_Map1_Freeplane_Mind_map_mode](https://github.com/freeplane/freeplane/assets/38586259/c754c9c9-da29-4766-a7d6-aa6555bef98f)
e.

**Comment by macmarrum** [comment]
You can use the following script to achieve this:
- [insertLocalLinkWithStyleForTarget.groovy](https://raw.githubusercontent.com/macmarrum/freeplane-scripting/main/src/scripts/insertLocalLinkWithStyleForTarget.groovy)

You can download the script and save it in your `<user-dir>/scripts` (can be easily opened via `Tools->Open user directory`).
You need to restart Freeplane for new scripts to be recognized.
In your mind map, add a style named `Local-Link Target` and add an icon of your choice to it.
You can now select 2 or more nodes and run the script on them.

You'll find the script in `Mac1->Insert`. To have it appear in `Tools->Scripts`, remove `="/menu_bar/Mac1/Insert"` from the first line.

You can change the script's setting in the script itself (open it with an editor line notepad++).

You can also have a look at a similar discussion:
- https://github.com/freeplane/freeplane/discussions/1255

**Comment by aaa1386** [comment]
Thanks for taking the time to reply.
The only thing that didn't work for me is that I don't know how to define an icon for a style that always has that style with it.

**Comment by macmarrum** [comment]
> The only thing that didn't work for me is that I don't know how to define an icon for a style [...]

Please have a look at https://docs.freeplane.org/user-documentation/styles.html

Once you create a style, you can add an icon to it just like you would to a regular node.

**Comment by aaa1386** [comment]
Thank you so much for your reply - absolutely correct
