### ISSUE TITLE
Link a node to more than one file or URL or another node

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1394]
Currently Freeplane software links a node to only one internet address or one file or another node. Sometimes it is necessary to link a node to more than one item. This feature is not available in the software

**Comment by macmarrum** [comment]
You can have many links per node by using Attributes:
1. `Edit->Node properties->Edit attribute in-line`
2. In the Attributes table, right-click the value cell to add a hyperlink or a node link
3. ...and to add a new attribute

![attributes-table-right-click](https://github.com/freeplane/freeplane/assets/7197131/6d25535d-dd90-4f99-8e02-41c66ba00783)

Please also have a look at `View->Node attributes`

**Comment by ajaberi1360** [comment]
> You can have many links per node by using Attributes:
> 
> 1. `Edit->Node properties->Edit attribute in-line`
> 2. In the Attributes table, right-click the value cell to add a hyperlink or a node link
> 3. ...and to add a new attribute
> 
> ![attributes-table-right-click](https://user-images.githubusercontent.com/7197131/266821835-6d25535d-dd90-4f99-8e02-41c66ba00783.png)
> 
> Please also have a look at `View->Node attributes`

Thank you for your great help

**Comment by aaa1386** [comment]
Thank you for your great help.
Problem solved with your explanation
