### ISSUE TITLE
No button to create a new mind map

### ISSUE THREAD

**Issue by magidc** [freeplane/freeplane#1400]
I am not so sure if this is a bug or the absence of a feature but as this is a obvious thing to have, I think some must be going wrong. Basically there is not a button to start a new map. You can open a previous one but not start from the scratch.
I faced this problem yesterday and ended up using the shortcut ctrl+n.

It may be my fault that I am not finding the option in spite of being there, in that case, it is not definitely intuitive enough for dumb users like me.
![2023-09-13_09-48](https://github.com/freeplane/freeplane/assets/4416693/0a58bac8-ce16-413d-a5e2-9d4bcecbccad)

By the way, the language of my system is Galician. As you see in the screenshot it is not fully supported yet, if you guide me how to do it, I will be happy to submit the translation.

**Comment by macmarrum** [comment]
I believe there is no button in the toolbar to create a new mind map. I know I can find such actions in the menu:
- `File->New map (Ctrl+N)`
- `File->New map from template…`
- `File->New protected (encrypted) map…`

For a translation how-to, please see https://docs.freeplane.org/contribute/Translation_How-To.html

**Comment by magidc** [comment]
I have not such File menu:
![2023-09-13_11-15](https://github.com/freeplane/freeplane/assets/4416693/cb6cb30b-3747-422c-9be0-9d296da6bf16)
 I am using PopOs (Ubuntu based). Am I missing something?

**Comment by macmarrum** [comment]
Menu bar can be toggled off.
You can toggle it back on using **Command Search**. The default hot key for it is `Ctrl+F1`. 
You can search among **Menu items** for `Menubar` and activate it using `Enter`.

You can have a look at the screenshots at https://docs.freeplane.org/user-documentation/hot-keys-and-beyond.html

**Comment by magidc** [comment]
Yes! It was indeed disabled. Now I can see the bar.
Thank you very much!
