### ISSUE TITLE
Edge color / Color changes when branch reaches top level

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#1402]
Thank you for freeplane :)

# Scenario
A branch needs to be moved. The movement of the branch is done by keyboard. Let's move a branch to the top of the hierarchy

## Settings used
![image](https://github.com/freeplane/freeplane/assets/10260832/7dde6505-06d7-4702-b6b7-d2e35cab1dbb)

# Expected behavior
The branch can be moved anywhere without changing in edge color.

# Actual behavior
The edge color changes as soon as the top level is reached. It seems to be treated like a new branch.

https://github.com/freeplane/freeplane/assets/10260832/b6b7a154-994d-401b-9368-bdd03a589f0a

# Problem
Colors do have a meaning, and they should not change after a branch was created.

**Comment by dpolivaev** [comment]
When node a is made a child of node b, its original edge color is lost because it keeps the same color as node b.
When it is moved back, it needs a new color.

If colors have meaning you can assign the colors to nodes or use styles.

**Comment by theelectricsoul** [comment]
ok this make sense...    a lot ...  lol
