### ISSUE TITLE
STDERR: missing key OptionPanel.horizontal_layout

### ISSUE THREAD

**Issue by olazzzzz** [freeplane/freeplane#1404]
**Describe the bug**
This error has always been flagged, what the consequences are I don't know, there is not, as far as I understand, any visible impacts on performance. 
The line in notepad describing it is "STDERR: missing key OptionPanel.horizontal_layout"
The program does not crash because of it. I would just like to understand what is causing it, so that it does not cause any problems in the future.

**To Reproduce**
Again, I cannot answer this, as the program flags the error in all mindmaps I am using.

**Expected behavior**
Nothing seems to differ because of this error.

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Screenshots**
A screenshot of the notepad file is attached:
![Freeplane error](https://github.com/freeplane/freeplane/assets/123204345/8e73d3b0-0c92-46b7-9a11-1b4f3481f929)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home x64
 - Version: 22H2
 - Java Version 8 Update 321 (build 1.8.0_321-b07=

**Additional context**

**Comment by dpolivaev** [comment]
The error message might come if you have some configuration files overriding the menu or preferences coming with Freeplane.

Open the freeplane user directory (Tools->Open user directory) and let me know which files you find there and in its subdirectories.

**Comment by olazzzzz** [comment]
Thank you for your answer.
I started digging in the freeplane user directory, experimenting with moving out addons and scripts to see if they would correct the error message.
Inside the "resources/xml" folder, I found a file "mindmapmodemenu.xml" (I don't remember if I created it earlier, or if it comes with Freeplane already). When I moved it out, the program opened without any error :)
Could you just confirm please that indeed this is not an important file the program needs to function? 
Thank you again!

**Comment by dpolivaev** [comment]
Yes, having a user-defined version of mindmapmodemenu.xml or preferences.xml was the most likely explanation for the reported error, because if action or property names change and translation files change your copies can easily become inconsistent with the updated Freeplane version.
