### ISSUE TITLE
An indication on the screen when the "jump in" option is active

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1406]
An indication on the screen when the "jump in" option is active
When the "jump in" mode is active, there is no indication that this mode is active. Because this state is out of the normal state, it would be great if there is a sign on the screen that clearly shows this state

**Comment by euu2021** [comment]
It would be nice to have this visual feedback inside the "new" root. Because, I find it difficult to identify the current Root after a jump in. For example:

![image](https://github.com/freeplane/freeplane/assets/77707706/86f6e0e9-1d32-4502-95c7-9abaeb8e96f7)

**Comment by macmarrum** [comment]
Until the feature request is addressed, you can consider using the scripts
- [jumpInWithStyle.groovy](https://raw.githubusercontent.com/macmarrum/freeplane-scripting/main/src/scripts/jumpInWithStyle.groovy)
- [jumpOutWithStyle.groovy](https://github.com/macmarrum/freeplane-scripting/raw/main/src/scripts/jumpOutWithStyle.groovy)

You can save each script in your `<user-dir>/scripts` (can be easily opened via `Tools->Open user directory`).
You need to restart Freeplane for new scripts to be recognized.
The scripts will appear in `Mac1->Jump`. If you remove `="/menu_bar/Mac1/Jump"` from the first line of each script, the scripts will appear in `Tools->Scripts`.

By default, the style name is **JumpIn**. You need to create it in your mind map(s).

The idea is to assign your usual jump-in/jump-out hot keys to the scripts, so that whenever you jump in, your View Root gets the JumpIn style, and when you jump out, the style is removed.

**Comment by aaa1386** [comment]
"The idea is to assign your usual jump-in/jump-out hot keys to the scripts, so that whenever you jump in, your View Root gets the JumpIn style, and when you jump out, the style is removed."

This idea is not enough because sometimes the first node or root is out of the user's view due to mental map navigation.
Especially the work becomes difficult when several mind map files are open. When moving from one mind map file to another, the user must check whether the first node is the root or a normal node. To recognize whether the state of jump is this or jump out and to understand whether the whole mental map is open or hidden in front of him?

**Comment by aaa1386** [comment]
Thanks, it's a little better
![image](https://github.com/freeplane/freeplane/assets/38586259/3841040c-f9e9-43cf-9024-545afbd9d0c4)
. But if it is navigated and the placed lamp leaves the screen, the state of jump in or jump out is not clear⬇️⬇️⬇️⬇️
![image](https://github.com/freeplane/freeplane/assets/38586259/97d24605-0d13-4ae0-bda9-c92275e52e0a)

**Comment by macmarrum** [comment]
Freeplane gives a lot of possibilities to style a node. In your example I recommend adding **Cloud** to you JumpIn style in your preferred color and shape. It will cover your entire mind map, so that you'll be able to tell if you've jumped in or not.

**Comment by aaa1386** [comment]
Thank you, it was a good help

**Comment by aaa1386** [comment]
The only problem with using this solution is that when we have defined a cloud for a node in the no-jump mode, when click "jump in" script , the Cloud defined "jumpin" style is not applied, Rather, the cloud is displayed unrelated to the "jumpin" style.

**Comment by macmarrum** [comment]
I have updated the scripts to change the mind map background color when you jump in and restore it to the original when you jump out. You can specify the color code in the script.

- [jumpInWithStyle.groovy](https://raw.githubusercontent.com/macmarrum/freeplane-scripting/main/src/scripts/jumpInWithStyle.groovy)
- [jumpOutWithStyle.groovy](https://github.com/macmarrum/freeplane-scripting/raw/main/src/scripts/jumpOutWithStyle.groovy)

`jumpInWithStyle.groovy` also adds **JumpIn** style to the mind map, if the style is missing.

**Comment by aaa1386** [comment]
Thank you, it was great🌸🌸

**Comment by dpolivaev** [comment]
A pin is displayed on the root nodes after jump-ins.

Preview 1.11.7_03

**Comment by euu2021** [comment]
Nice. Thanks.

**Comment by aaa1386** [comment]
> I have updated the scripts to change the mind map background color when you jump in and restore it to the original when you jump out. You can specify the color code in the script.
> 
> * [jumpInWithStyle.groovy](https://raw.githubusercontent.com/macmarrum/freeplane-scripting/main/src/scripts/jumpInWithStyle.groovy)
> * [jumpOutWithStyle.groovy](https://github.com/macmarrum/freeplane-scripting/raw/main/src/scripts/jumpOutWithStyle.groovy)
> 
> `jumpInWithStyle.groovy` also adds **JumpIn** style to the mind map, if the style is missing.


Everything works great in this script, the only problem I noticed recently is that when I open the mind map in a new view (via the "New map view" option), it changes the background in all new views. If I use the "jump in" option, the script does not work well, that is, when using "jump out", it does not return the background to the original state.

**Comment by macmarrum** [comment]
@ajaberi1360 

> Everything works great in this script, the only problem I noticed recently is that when I open the mind map in a new view (via the "New map view" option), it changes the background in all new views. 

Yes. This cannot be avoided. Freeplane allows to change the background per mind map, not per view.

> If I use the "jump in" option, the script does not work well, that is, when using "jump out", it does not return the background to the original state.

I cannot reproduce this situation. Please make sure you use the latest version of the script (re-download it and try again). If this is still an issue, could you please provide more information, maybe a video of this unexpected behavior?
