### ISSUE TITLE
marking on the node as long as the "Shift Next Child" option is active for a node,

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1408]
Imagine that a node named "Teaching" has ten sub-branches and we have activated the option "Shift Next Child" (navigate/fold/Shift Next Child). 
We opened three of these branches with "Shift Next Child" then navigated to another place in the mind map or even another file. We may forget that the "teaching" node has ten branches and imagine that it has only three branches.

This problem arises because there is no indication that the "Shift Next Child" mode is active on the node

**Comment by dpolivaev** [comment]
It is indicated when the mouse pointer is held over the node

<img width="131" alt="allChildrenVisible" src="https://github.com/freeplane/freeplane/assets/1558052/8f1ecb93-654a-4f91-b48b-29f98e504cff">
<img width="76" alt="someChildrenHidden" src="https://github.com/freeplane/freeplane/assets/1558052/acb83479-acc6-4e04-8182-f22850d95a8d">
