### ISSUE TITLE
Moving and deleting nodes related to Jump In terminates Freeplane

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1416]
For quite some time, a bug, related to Jump In, has been annoying me. It pops up very randomly, so I never managed to reproduce it. Today, I spent some time doing all kinds of maneuvers, until I identified it.
It looks like a random sequence of steps, but, for some reason, it sometimes happens for me (I use map views a lot):

- create node `a`
- create a child of `a` (node `b`)
- create child of `b` (node `c`)
- create new map view (map view 2)
- in map view 2, jump into node `b`
- in map view 1, move node `c` to be a sibling bellow node `b`
- in map view 1, move node `c` to be a sibling above node `b`
- in map view 1, delete node `b`

![RIeRPLoQCZ](https://github.com/freeplane/freeplane/assets/77707706/f6cafee4-02f9-4707-a0b5-92fda463d7e4)

Log:
[log bug.txt](https://github.com/freeplane/freeplane/files/12653433/log.bug.txt)

Freeplane 1.11.7-pre03

**Comment by dpolivaev** [comment]
Preview 1.11.8_01

**Comment by euu2021** [comment]
Thanks!
