### ISSUE TITLE
Add / Remove cloud on multiple nodes

### ISSUE THREAD

**Issue by sifran-github** [freeplane/freeplane#1422]
**Describe the bug**
if you select multiple nodes that some of them have clouds and some don't, and you press the toolbar on the button "add / remove cloud (default)", it is changing them individually: It will remove the cloud from Nodes that had cloud, and will add a cloud to nodes that didn't have it.

It is a different behavior from other buttons. For example, the the bold button will create a single effect for all selected nodes, no matter how many were selected. It will turn them to be consistent (either all bold, or all without bold).

**Expected behavior**
It is expected to work like other buttons. To choose either to add or remove the cloud, and apply this selection for all the selected nodes.

**Comment by dpolivaev** [comment]
Stable version 1.11.7
