### ISSUE TITLE
Syntax Highlighting for Markdown code blocks

### ISSUE THREAD

**Issue by bruno-brant** [freeplane/freeplane#1423]
**Is your feature request related to a problem? Please describe.**
As a developer, I use mind maps frequently when analyzing code. For that, I create code blocks in markdown, using the three-backticks syntax, and informing the language in the block. It would be really helpful if Freeplane was able to apply even some rudimentar syntax highlight to those blocks so that it would be easier to mentally parse the code when reading.

**Additional context**

The syntax for markdown code is:

\```language
Code goes here
\```

For instance, if I was writing haskell code I would:

\```haskell
module Main(main) where

main :: IO ()
main = do
  print "Freeplane rocks"

\```

Which, if correctly processed by the markdown parser, should look like this:

```haskell
module Main(main) where

main :: IO ()
main = do
  print "Freeplane rocks"

```

**Comment by euu2021** [comment]
related discussion: #1283

**Comment by dpolivaev** [comment]
Not supported by known markdown rendering libraries
