### ISSUE TITLE
Too big gap between parent nodes if their child nodes have slightly larger heights 

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1424]
In some cases, using the default style, the distance between the node and the branch is set incorrectly. But there is no such problem with the import style 

https://github.com/freeplane/freeplane/assets/38586259/d495f23e-8497-4282-9462-00bcc61c327e

**Comment by dpolivaev** [comment]
Please zip and attach the mind map file shown in the video. I always need the file you use to demonstrate the problem.

**Comment by aaa1386** [comment]
[bug.zip](https://github.com/freeplane/freeplane/files/12705876/bug.zip)

**Comment by dpolivaev** [comment]
Freeplane behaves as expected: when you add an icon to the leaf node, its height increases. Therefore extra distance is added between the parent nodes.

But if you add icons to the parent node either, the heights are same. Therefore no extra distance is added.

**Comment by dpolivaev** [comment]
I modified the layout to better handle such cases

**Comment by aaa1386** [comment]
Thank you
