### ISSUE TITLE
FP 1.11.7_03: hidden node command shortcut not active at the 1st start

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#1427]
**Describe the bug**
After running FP, when I need to change the status of a node to hidden node status (in the menu: view/hidden node):

- if during the 1st start, I do it with the menu command, it works nice
- but if at the 1st start, I do it with the shortcut (I use ctr+shift+S), nothing happens to the node--> at 1st start, it seems this shortcut is not active

And finally if I run the menu command it seems to be like a sort of activation because after this operation the shortcut works fine.
I think this is a bug: the shortcut must work always.

**Comment by dpolivaev** [comment]
Stable version 1.11.7
