### ISSUE TITLE
On Kubuntu can't open links that were added to nodes.

### ISSUE THREAD

**Issue by akwala** [freeplane/freeplane#1436]
**Describe the bug**
Clicking on a link that was added to node does not open the URI. The log shows the following for every such click:
```
WARNING: Opening URI is not supported by the OS
```
This is the case for links to local files/directories as well as those to web URLs.

Links in other applications open as expected, so the warning seems misleading.

**To Reproduce**
1. Add to a node a hyperlink to a local file or directory.
2. Click on the link just created.
3. Nothing happens besides the warning in the log.
4. Repeat steps 1–3 with a hyperlink to a web URL.

**Expected behavior**
Clicking on a link opens the link's URI.

**Desktop (please complete the following information):**
 - Freeplane 1.11.7
 - OS: Linux – Kubuntu 22.04.3
- KDE Plasma Version: 5.24.7
- KDE Frameworks Version: 5.98.0
- Qt Version: 5.15.3
- Kernel Version: 5.15.0-84-generic (64-bit)

 - Java Version: 17.0.8.1
![image](https://github.com/freeplane/freeplane/assets/1786/174e8bb9-d0c4-453b-a0d6-790a75db8f15)

**Comment by dpolivaev** [comment]
Upload your example mind map (zipped) and screenshots documenting every step.
I need to understand if the issue is OS-specific.

**Comment by dpolivaev** [comment]
Also upload freeplane log file.

**Comment by dpolivaev** [comment]
Sorry, I understand what happened.

**Comment by dpolivaev** [comment]
Preview 1.11.8_01

**Comment by akwala** [comment]
> Preview 1.11.8_01

Tested this. The links work as expected. Thanks!
