### ISSUE TITLE
export to pdf bug Freeplane 1.7.9

### ISSUE THREAD

**Issue by Gseguelg** [freeplane/freeplane#144]
Hello and congrats for the achievement of implementing this easy to use piece of software.

**The Issue:**
On version 1.7.9 (linux mint 19), I've found that exporting to pdf gets stuck for a very long time when at least a node with the "/" character is included as text (on any node). 

**Insights:**
At first i thought that the size of the map created was the cause, but exporting to **_jpg_** gives the expected result in a reasonable time.

I was able to recreate this issue using only root node, whose text was "_Nuevo/mapa mental_". Exporting to **_pdf_** gets stuck while _**jpg**_ is ready almost instantaneously. (standard-1.6.mm)

It takes so long on the freeze state, that overnight I found it outputs an error window. Unfortunately, I had to close it and did not keep the output. Meanwhile killing the process and changing "/" by similar characters does the job.

**It appears to be an issue only when exporting to pdf**, though, I haven't try other extensions besides jpg.

**Comment by Gseguelg** [comment]
Just found same problem on a map without "/". And wait for the following error:

> at 2019-09-21 01:39:23 CMT,  hash 476d3e294f1e5717c093d7d1f60dfd5e
> previous report : no reports sent before
> freeplane_version = 1.7.9; freeplane_xml_version = freeplane 1.7.0
> git revision = 2387c571bd85a40c679c06f3cc2a718afd92b690 Dimitry Polivaev 2019-06-10T17:19:31Z
> java_version = 11.0.4; os_name = Linux; os_version = 4.15.0-58-generic
> Exception in thread "AWT-EventQueue-0" 
> java.lang.OutOfMemoryError: Java heap space
> 	at java.base/sun.nio.fs.UnixPath.normalize(UnixPath.java:616)
> 	at java.base/sun.nio.fs.UnixPath.normalize(UnixPath.java:43)
> 	at java.base/java.io.FilePermission.init(FilePermission.java:345)
> 	at java.base/java.io.FilePermission.<init>(FilePermission.java:477)
> 	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:661)
> 	at org.freeplane.plugin.script.InternationalizedSecurityManager.checkRead(InternationalizedSecurityManager.java:156)
> 	at java.base/java.io.File.isDirectory(File.java:845)
> 	at org.apache.commons.io.filefilter.DirectoryFileFilter.accept(DirectoryFileFilter.java:70)
> 	at org.apache.commons.io.filefilter.AndFileFilter.accept(AndFileFilter.java:122)
> 	at org.apache.commons.io.filefilter.AndFileFilter.accept(AndFileFilter.java:122)
> 	at org.apache.commons.io.filefilter.OrFileFilter.accept(OrFileFilter.java:118)
> 	at java.base/java.io.File.listFiles(File.java:1303)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:357)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> 

Any ideas?

**Comment by dpolivaev** [comment]
Freeplane uses apache fop (https://xmlgraphics.apache.org/fop/) for generating PDF.
And it has two modes how text is exported: either each letter is converted to geometric path or the font is embedded. Second option is preferable in the most cases.

When PDF generation is run at the first time fop indices all fonts it can find in font directories on the computer in a so-called cache file. I do not know why. On my computers it takes only a few seconds, but on some computers this task takes very long time. DirectoryWalker.walk shown in your exeption trace seem to be part of the indexing process. As indexing goes it writes to the Freeplane log file which fonts it founds, so you can follow the process.

it would be interesting to look inside your log file, it could probably give some insides.

Also when you attach exception traces which are always interesting please attach them completely as you never know which parts are relevant for my investigations.

**Comment by Gseguelg** [comment]
Thanks for the answer. Apparently i'm not able to export anymore to pdf (issue appears only in freeplane).

`Log.0` file gives the following. Exporting the pdf happens from `STDERR`exception appears, everything before on startup.
> STDOUT: sept. 25, 2019 3:25:50 A. M. org.freeplane.core.util.LogUtils info
> INFORMACIÓN: freeplane_version = 1.7.9; freeplane_xml_version = freeplane 1.7.0
> git revision = 2387c571bd85a40c679c06f3cc2a718afd92b690 Dimitry Polivaev 2019-06-10T17:19:31Z
> java_version = 11.0.4; os_name = Linux; os_version = 4.15.0-58-generic
> STDOUT: sept. 25, 2019 3:25:53 A. M. org.freeplane.core.util.LogUtils info
> INFORMACIÓN: added parsing support for standard date format dd-MM-yy
> STDOUT: sept. 25, 2019 3:25:53 A. M. org.freeplane.core.util.LogUtils info
> INFORMACIÓN: added parsing support for standard date time format dd-MM-yy HH:mm
> STDOUT: sept. 25, 2019 3:25:53 A. M. org.freeplane.core.util.LogUtils info
> INFORMACIÓN: available locales not found
> STDOUT: sept. 25, 2019 3:25:53 A. M. org.freeplane.core.util.LogUtils info
> INFORMACIÓN: available locales not found
> STDOUT: sept. 25, 2019 3:25:56 A. M. org.freeplane.core.util.LogUtils info
> INFORMACIÓN: Loaded properties from bundle://6:1/org/freeplane/plugin/formula/defaults.properties
> STDOUT: sept. 25, 2019 3:25:56 A. M. org.freeplane.core.util.LogUtils info
> INFORMACIÓN: extending script's classpath by [/home/gseguelg/.config/freeplane/1.7.x/compiledscripts, /home/gseguelg/config/freeplane/1.7.x/lib]
> STDOUT: sept. 25, 2019 3:25:56 A. M. org.freeplane.core.util.LogUtils info
> INFORMACIÓN: Loaded properties from bundle://8:1/org/freeplane/plugin/script/defaults.properties
> STDOUT: sept. 25, 2019 3:25:57 A. M. org.freeplane.core.util.LogUtils info
> INFORMACIÓN: Loaded properties from bundle://8:1/org/freeplane/plugin/script/defaults.properties
> STDOUT: sept. 25, 2019 3:25:57 A. M. org.freeplane.core.util.LogUtils info
> INFORMACIÓN: looking for scripts with the following endings: [groovy, js]
> STDOUT: Framework launched
> STDOUT: sept. 25, 2019 3:25:58 A. M. org.freeplane.core.util.LogUtils info
> INFORMACIÓN: requesting mode: MindMap
> STDOUT: sept. 25, 2019 3:26:01 A. M. org.freeplane.core.util.LogUtils info
> INFORMACIÓN: menu items to execute: []
> STDERR: Exception in thread "AWT-EventQueue-0"
> STDERR: java.lang.OutOfMemoryError: Java heap space
> STDERR: at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:130)
> STDERR: at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
> STDERR: at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:280)
> STDERR: at java.base/java.io.FilePermission.init(FilePermission.java:344)
> STDERR: at java.base/java.io.FilePermission.<init>(FilePermission.java:477)
> STDERR: at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:661)
> STDERR: at org.freeplane.plugin.script.InternationalizedSecurityManager.checkRead(InternationalizedSecurityManager.java:156)
> STDERR: at java.base/java.io.File.isFile(File.java:878)
> STDERR: at org.apache.commons.io.filefilter.FileFileFilter.accept(FileFileFilter.java:59)
> STDERR: at org.apache.commons.io.filefilter.AndFileFilter.accept(AndFileFilter.java:122)
> STDERR: at org.apache.commons.io.filefilter.AndFileFilter.accept(AndFileFilter.java:122)
> STDERR: at org.apache.commons.io.filefilter.OrFileFilter.accept(OrFileFilter.java:118)
> STDERR: at java.base/java.io.File.listFiles(File.java:1303)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:357)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)
> STDERR: at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364)

**Comment by dpolivaev** [comment]
The problem comes from the library and can not be fixed within Ffreeplane.
You can try to activate option environment->export->convert text to shapes or use PDF printer.
