### ISSUE TITLE
Can't move nodes or delete nodes that are a child of a node that, in another map view, is folded

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1441]
There is a bug in FP 1.11.8-pre01. 

I have multiple map views opened with Jump in some of them. 
In one of those map views, with Jump in, I can create nodes, but when I try to move nodes or delete nodes, I get errors. Log:

[log.txt](https://github.com/freeplane/freeplane/files/12796274/log.txt)

I'll try to reproduce.

**Comment by euu2021** [comment]
Actually, it's not related to Jump In

**Comment by euu2021** [comment]
I got it.

- create node a as child of root
- create node b as child of a
- create node c as child of b
- new map view
- put the map views side by side
- fold b on the second map view
- try to delete c on the first map view. It gives an error

![javaw_ntehn2Bdv6](https://github.com/freeplane/freeplane/assets/77707706/6ea8d775-f68d-4e0a-9e51-59d23dd27c62)

Log:
[log.txt](https://github.com/freeplane/freeplane/files/12796492/log.txt)

**Comment by euu2021** [comment]
actually, the step `put the map views side by side` can be skipped. It's enough to have another map view with the node folded.

And, if the node is unfolded, the error stops happening, and node c can be deleted.

**Comment by dpolivaev** [comment]
I am sorry
Preview 1.11.8_02

**Comment by euu2021** [comment]
I've been using 1.11.8_02 for a couple of hours, and everything is working fine. Thanks!
