### ISSUE TITLE
FP 1.11.8: Changing "Automatic Level Styles" or "Automatic edge Color" raises error if Note Panel has never been shown in current session

### ISSUE THREAD

**Issue by EdoFro** [freeplane/freeplane#1442]
## **Describe the bug**
when changing the comboboxes in the toolpanel:
 - "Automatic Level Styles" 
 - "Automatic edge Color"

AND

- the note panel has been never shown in the current session

it raises an error.

## **To Reproduce**
1. open Freeplane
2. if the note panel is open, then you should close it and restart Freeplane
3. open a mindMap
4. change any of these two comboBoxes
5. error arises

## Log

<details> 
<summary> Log details </summary> 

<code>
STDOUT: Oct 04, 2023 8:24:09 PM org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.11.8; freeplane_xml_version = freeplane 1.11.5
git revision = 3fcac6cf6e0880645eb0891ed0b10de2783a85e9 dpolivaev 2023-10-04T09:02:01Z
java_version = 17.0.6; os_name = Windows 11; os_version = 10.0
STDOUT: Oct 04, 2023 8:24:10 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date format dd-MM-yy
STDOUT: Oct 04, 2023 8:24:10 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date time format dd-MM-yy HH:mm
STDOUT: Framework launched
STDOUT: Oct 04, 2023 8:24:13 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://3:1/org/freeplane/plugin/formula/defaults.properties
STDOUT: Oct 04, 2023 8:24:13 PM org.freeplane.core.util.LogUtils info
INFO: extending script's classpath by [C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\compiledscripts, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\groovyConsole\lib\groovyConsole.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\groovyNode\lib\groovyNode.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\mapDriveInator\lib\MapDriveInator.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\mapSavingOptions\lib\MapSavingOptions.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\markdownHelper\lib\MarkdownHelper.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\markdownHelper\lib\jsoup-1.10.2.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\markdownHelper\lib\markedj-1.0.16.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\menuOMatic\lib\Menu-o-Matic.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\pseudoFreeplaneAPI\lib\pseudoFreeplaneAPI.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\tabbedPanelMod\lib\TabbedPanelMod.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\tutorialOMatic\lib\Tutorial-o-Matic.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\tutorialOMatic\lib\markedj-1.0.16.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\tutorialOMatic\lib\jsoup-1.10.2.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\addons\unicodeProgressBar\lib\UnicodeProgressBar.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\lib, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\lib\jcommon-1.0.24.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\lib\jfreechart-1.5.3.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\lib\json-simple-1.1.1.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\lib\MDTool-1.2.4.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\lib\plantuml.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\lib\scriptlib.jar, C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x]
STDOUT: Oct 04, 2023 8:24:13 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://8:1/org/freeplane/plugin/script/defaults.properties
STDOUT: Oct 04, 2023 8:24:14 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: Oct 04, 2023 8:24:14 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: Oct 04, 2023 8:24:16 PM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
STDOUT: Oct 04, 2023 8:24:28 PM org.freeplane.core.util.LogUtils info
INFO: running init script C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\scripts\init\BookmarksMonitorIcons.groovy
STDOUT: Oct 04, 2023 8:24:28 PM org.freeplane.core.util.LogUtils info
INFO: running init script C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\scripts\init\TabbedPanelMod_init.groovy
STDOUT: Oct 04, 2023 8:24:28 PM org.freeplane.core.util.LogUtils info
INFO: running init script C:\Users\efroh\AppData\Roaming\Freeplane\1.11.x\scripts\init\Tabz_Menu-o-Matic_init.groovy
STDOUT: Oct 04, 2023 8:24:28 PM org.freeplane.core.util.LogUtils info
INFO: menu items to execute: []
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.NullPointerException: Cannot invoke "org.freeplane.features.note.mindmapmode.NotePanel.setComponentOrientation(java.awt.ComponentOrientation)" because the return value of "org.freeplane.features.note.mindmapmode.MNoteController.getNotePanel()" is null
STDERR: at org.freeplane.features.note.mindmapmode.NoteManager$2.mapChanged(NoteManager.java:89)
STDERR: at org.freeplane.features.map.MapController.fireMapChanged(MapController.java:646)
STDERR: at org.freeplane.features.styles.LogicalStyleController$11.run(LogicalStyleController.java:290)
STDERR: at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.NullPointerException: Cannot invoke "org.freeplane.features.note.mindmapmode.NotePanel.setComponentOrientation(java.awt.ComponentOrientation)" because the return value of "org.freeplane.features.note.mindmapmode.MNoteController.getNotePanel()" is null
STDERR: at org.freeplane.features.note.mindmapmode.NoteManager$2.mapChanged(NoteManager.java:89)
STDERR: at org.freeplane.features.map.MapController.fireMapChanged(MapController.java:646)
STDERR: at org.freeplane.features.styles.LogicalStyleController$11.run(LogicalStyleController.java:290)
STDERR: at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
STDERR: at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
STDERR: at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

</code>
</details>

**Comment by dpolivaev** [comment]
Preview 1.11.8_03

**Comment by EdoFro** [comment]
Tested OK

thanks!
