### ISSUE TITLE
Option to disable mouse driven node shifts

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1446]
Imagine you want to open or close a number of nodes by clicking the folding mark. In some cases, the mark node position may be activated unintentionally by moving the mouse, and this destroys mental focus.
  In addition, changing the position of nodes and branches is not useful for many people. Therefore, there is no need for node reposition mark

I suggest a checkbox in the view tab to enable or disable the mark node position which is oval. (Therefore, the position of the node mark is not activated by moving the mouse)

**Comment by euu2021** [comment]
Discussed at: https://sourceforge.net/p/freeplane/discussion/758437/thread/d230065b5c/

There, I proposed this workaround:

> If you go to Preferences…->Behaviour->Behaviour->Grid gap size and change it to something big, like 100 cm, you won't be able to move the nodes using the oval handles.

**Comment by aaa1386** [comment]
thank you
It solved the problem to some extent
But the problem still remains. Whenever, by mistake, instead of folding and clicking on the folding circle, the oval shape corresponding to the change of the node position is displayed, first, we must leave the oval once by moving the mouse and click the folding circle again.
As a result, showing the oval is annoying

**Comment by macmarrum** [comment]
@ajaberi1360 You can try using a bigger folding symbol width: `Preferences…->Appearance->Size limits->Folding symbol width`

**Comment by euu2021** [comment]
Also, changing the size of `Preferences…->Appearance->Size limits->Dragging` area width to the minimum (3 pixels), can be helpful while your request is not fulfilled.

**Comment by aaa1386** [comment]
Thank you for your comments-My problem was solved to a great extent by your comments
The easiest way to fold or unfold with the mouse is to left click inside the node once instead of clicking on the circle.
The only problem is that the first way works slowly, if it wasn't for this slowness, there would be no need for a circle sign
 
If the problem of its slowness is solved, it is very suitable and convenient for folding and unfolding

**Comment by sifran-github** [comment]
It took me sometime to understand what the author is talking about, and that "mark node position" is the oval movable handle next to nodes that moves the node, that is shown only when you hover over a node.

With that being said... it can be nice to have a checkbox to enable/disable it completely. I even think that it can be somewhere in the menus which is more accessible, and not in preferences.

I almost never move nodes and I will actually use this feature.
It didn't bother me too much, maybe because I use the keyboard a lot, but I will use it.

**Comment by dpolivaev** [comment]
Preview 1.11.8_04
Preferences…->Behaviour->Disable mouse-driven positional shifts of nodes
