### ISSUE TITLE
Please add build and run instructions

### ISSUE THREAD

**Issue by stokito** [freeplane/freeplane#145]
I would like to contribute with some small changes but I can't figure out how to build and run the freeplane locally.
Could you create a separate file `HACKING.md` which describes how to build the FreePlane?
For example, which JDK version do we need, what are gradle tasks, how to debug, Eclipse or IntelliJ code formatting settings, etc.

**Comment by dpolivaev** [comment]
I have added some hints and links to https://github.com/freeplane/freeplane/blob/1.7.x/README.md .
Please check if it is helpful enough.

**Comment by stokito** [comment]
thank you
