### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by steveatmaat** [freeplane/freeplane#1458]
**Describe the bug**
I don't know what the bug is, but some times I see an error message in the footer. When I look in the log file I see: java.lang.IndexOutOfBoundsException: Index: 4, Tab count: 4

**To Reproduce**
I can not reproduce the error. I have tried many times. It has something to do with changing tabs, or opening and closing the notes editor.

**Expected behavior**
I can't say, because it doesn't happen consistently

If there is anything I can do to help reproduce the error, or any way I can provide more information, please let me know. 

This has happened with 1.11.7 and 1.11.8.

I looked in the issues list and didn't see any bug report like this, so it could have to do with one of my maps, but I always have at least four maps open, and it doesn't seem to be related to any specific file.

I'm sorry I can't provide more information, but in case this is a real bug, I just wanted to get it on the radar.

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 - Java Version: whatever java version is installed by "with java" download.

log file:
STDOUT: Oct 06, 2023 2:11:28 PM org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.11.8; freeplane_xml_version = freeplane 1.11.5
git revision = 3fcac6cf6e0880645eb0891ed0b10de2783a85e9 dpolivaev 2023-10-04T09:02:01Z
java_version = 15.0.10; os_name = Windows 10; os_version = 10.0
STDOUT: Oct 06, 2023 2:11:29 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date format M/d/yy
STDOUT: Oct 06, 2023 2:11:29 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date time format M/d/yy, h:mm a
STDOUT: Framework launched
STDOUT: Oct 06, 2023 2:11:38 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://3:1/org/freeplane/plugin/formula/defaults.properties
STDOUT: Oct 06, 2023 2:11:39 PM org.freeplane.core.util.LogUtils info
INFO: extending script's classpath by [C:\Users\swcar\AppData\Roaming\Freeplane\1.11.x\compiledscripts, C:\Users\swcar\AppData\Roaming\Freeplane\1.11.x\addons\bookmarks\lib\bookmarks.jar, C:\Users\swcar\AppData\Roaming\Freeplane\1.11.x\addons\groovyConsole\lib\groovyConsole.jar, C:\Users\swcar\AppData\Roaming\Freeplane\1.11.x\addons\jumper\lib\jumper.jar, C:\Users\swcar\AppData\Roaming\Freeplane\1.11.x\addons\tutorialOMatic\lib\Tutorial-o-Matic.jar, C:\Users\swcar\AppData\Roaming\Freeplane\1.11.x\addons\tutorialOMatic\lib\markedj-1.0.16.jar, C:\Users\swcar\AppData\Roaming\Freeplane\1.11.x\addons\tutorialOMatic\lib\jsoup-1.10.2.jar, C:\Users\swcar\AppData\Roaming\Freeplane\1.11.x\scripts, C:\Users\swcar\AppData\Roaming\Freeplane\1.11.x\scripts\wikd.jar, C:\Users\swcar\AppData\Roaming\Freeplane\1.11.x\scripts\wikdshell.jar, C:\Users\swcar\AppData\Roaming\Freeplane\1.11.x\lib]
STDOUT: Oct 06, 2023 2:11:39 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://8:1/org/freeplane/plugin/script/defaults.properties
STDOUT: Oct 06, 2023 2:11:39 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: Oct 06, 2023 2:11:39 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: Oct 06, 2023 2:11:44 PM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
STDOUT: Oct 06, 2023 2:11:50 PM org.freeplane.core.util.LogUtils info
INFO: running init script C:\Users\swcar\AppData\Roaming\Freeplane\1.11.x\scripts\init\BookmarksMonitorIcons.groovy
STDOUT: Oct 06, 2023 2:11:51 PM org.freeplane.core.util.LogUtils info
INFO: menu items to execute: []
STDOUT: Oct 06, 2023 8:05:31 PM org.freeplane.core.util.LogUtils info
INFO: execute [rundll32, url.dll,FileProtocolHandler, file:///C://Fiction//ParkStreet//research]
STDOUT: Oct 07, 2023 2:01:19 PM org.freeplane.core.util.LogUtils info
INFO: opening 'C:\Cookbook\Marketing Materials\Maat Publishing\SteveCarter\AllCarsRunToParkStreet\PR\author talk\Author Talk Central.mm' for client
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.IndexOutOfBoundsException: Index: 4, Tab count: 4
STDERR: at java.desktop/javax.swing.JTabbedPane.checkIndex(Unknown Source)
STDERR: at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(Unknown Source)
STDERR: at net.infonode.tabbedpanel.theme.internal.laftheme.PaneUI.initTabLocations(PaneUI.java:1122)
STDERR: at net.infonode.tabbedpanel.theme.internal.laftheme.PaneUI.paintTabArea(PaneUI.java:700)
STDERR: at net.infonode.tabbedpanel.theme.LookAndFeelTheme$3$2.paint(LookAndFeelTheme.java:208)
STDERR: at net.infonode.gui.shaped.panel.ShapedPanel.paintComponent(ShapedPanel.java:205)
STDERR: at java.desktop/javax.swing.JComponent.paint(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
STDERR: at net.infonode.gui.shaped.panel.ShapedPanel.paintChildren(ShapedPanel.java:185)
STDERR: at java.desktop/javax.swing.JComponent.paint(Unknown Source)
STDERR: at net.infonode.tabbedpanel.TabbedPanel$ShadowPanel.paint(TabbedPanel.java:1604)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent.paint(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent.paint(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
STDERR: at net.infonode.gui.shaped.panel.ShapedPanel.paintChildren(ShapedPanel.java:185)
STDERR: at java.desktop/javax.swing.JComponent.paint(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent.paint(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
STDERR: at net.infonode.gui.shaped.panel.ShapedPanel.paintChildren(ShapedPanel.java:185)
STDERR: at java.desktop/javax.swing.JComponent.paint(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent.paint(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
STDERR: at java.desktop/javax.swing.JSplitPane.paintChildren(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent.paint(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
STDERR: at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(Unknown Source)
STDERR: at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
STDERR: at java.desktop/javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
STDERR: at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent._paintImmediately(Unknown Source)
STDERR: at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
STDERR: at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
STDERR: at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
STDERR: at java.base/java.security.AccessController.doPrivileged(Unknown Source)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
STDERR: at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
STDERR: at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
STDERR: at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
STDERR: at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
STDERR: at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
STDERR: at java.base/java.security.AccessController.doPrivileged(Unknown Source)
STDERR: at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
STDERR: at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
STDERR: at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by dpolivaev** [comment]
The error comes from a used library that is not maintained any longer. And it would take me too much effort to replace it. Therefore I am not going to fix the bug.
