### ISSUE TITLE
Add styles icon in toolbar.

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1459]
Changing styles is too much for most people.
  There are icons for some things that are rarely used, but there is no icon for styles.
To change the styles, he used the context menu, which is more difficult than the icon in the toolbar.

**Comment by euu2021** [comment]
There is a dropdown for styles in the toolbar:
![image](https://github.com/freeplane/freeplane/assets/77707706/91c82d75-abf4-4b10-b7a2-54b585edf6ed)

**Comment by EdoFro** [comment]
and you can add hotkey shortcuts to your most used styles.

look here: https://docs.freeplane.org/user-documentation/hot-keys-and-beyond.html?highlight=shortcuts#hot-keys-for-actions

**Comment by aaa1386** [comment]
I'm sorry, you are right, there is
I had not paid attention
