### ISSUE TITLE
FP terminates after moving node with drag and drop

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1463]
The situation was:
- many map views opened
- some of them with Jump in
- in one of the map views, without Jump In, I tried a very usual node move using drag and drop inside the same map view, and FP terminates

Log:
[log.txt](https://github.com/freeplane/freeplane/files/12849701/log.txt)

**Comment by euu2021** [comment]
As it's difficult to reproduce, I will close it as "can't repo", and add more information if the bug happens again.

**Comment by euu2021** [comment]
This sometimes happens to me, but I think I finally reproduced it. 

In this example map:
[box teste.zip](https://github.com/user-attachments/files/16918519/box.teste.zip)

Steps to reproduce:

- Select Root
- Unfold all nodes
- New view (creates view 2)
- In View 2, Select ddd
- Jump In
- Close View 2
- Select ccc
- Edit->Move and sort->Move node up

Result:
ccc disappears and error happens with this log:
[log.txt](https://github.com/user-attachments/files/16918520/log.txt)

![image](https://github.com/user-attachments/assets/9fe2f5ca-b3e5-4fee-8807-69b0dab75fce)

**Comment by dpolivaev** [comment]
Excellent

**Comment by dpolivaev** [comment]
Preview 1.12.6_03
