### ISSUE TITLE
Host releases in github instead of (or in addition to) sourceforge

### ISSUE THREAD

**Issue by kksharma1618** [freeplane/freeplane#1466]
**Is your feature request related to a problem? Please describe.**
Sourceforge download speed is too low. I get 50-60 KB/s whenever I download freeplane (app or updates) from there. Which makes updating a chore.
Since you are already hosting source on github (and it's an open source project), it would be nice if released binaries used github releases.

Thanks for the software. Absolutely love everything about it.

**Comment by dpolivaev** [comment]
On SourceForge you can choose a server location for downloads. Where are you downloading it from? Which servers have you tried?

**Comment by dpolivaev** [comment]
Check https://sourceforge.net/p/forge/documentation/Mirrors/

**Comment by kksharma1618** [comment]
I tried different mirrors and getting proper speeds in those. Closing the issue.
Thanks for the help :)
