### ISSUE TITLE
Enabling the "jump in" option on several branches at the same time and opening them in separate tabs.

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1474]
I create large mind maps in one file. I prefer not to have many files.
In order to focus on a branch and review and rewrite it, the Freeplane software provides two ways for this purpose, one way is to use the "Move branch to new map" option. This method does not serve my purpose because it creates many files. Suppose I have a mental map, if I separate 5 branches from it with the "Move branch to new map" option, it will create 5 new files for me and I I don't want many new files.

Another way is to focus the mind map on the desired node using the "jump in" option. This method is very good, it does not create new files, but the only drawback of this option is that I can only focus on one branch. I like to focus on several branches at the same time.
Also, I can't see the whole mind map anymore, which means I either have to see a jumped branch or exit this mode and see the whole map.

If possible, please include the following idea in the software. My suggestion is that when the "jump in" option is activated on a branch, the name of the first node of that branch should be displayed next to the tabs that show the names of the files opened in the Freeplane software.

  It is also possible to jump in several different branches at the same time. An icon should be placed in the tab of the node that has been jumped, and whenever that icon is clicked, it will be transferred to the general mind map tab.

**Comment by dpolivaev** [comment]
View->New map view

**Comment by aaa1386** [comment]
Thank you very much. Now I realized this option.

It would be great if we could change the title of the new tab when we create a new view of the map.

The better case is that when a node in the new map view is used to focus on a branch by the "jump in" option, its name should be the text tab of the first node.

**Comment by euu2021** [comment]
> It would be great if we could change the title of the new tab when we create a new view of the map.

It's your lucky day. This feature was released literally 3 days ago. Try the latest preview version. See: https://github.com/freeplane/freeplane/pull/1353

> The better case is that when a node in the new map view is used to focus on a branch by the "jump in" option, its name should be the text tab of the first node.

This sounds interesting.
