### ISSUE TITLE
Extensions Errors and Bug

### ISSUE THREAD

**Issue by mjjvc** [freeplane/freeplane#1477]
**Describe the bug**
Pack 'n Go

**To Reproduce**
Freeplane 1.11.7
Java 15.0.10
Pack 'n Go version 1.0

File - Pack 'n Go

Error: Error executing the Script: null

**Expected behavior**
Add-on to work.

**Mind map files**
It happened on a saved map and also on a new map
I have uploaded attached the map as zip

**Screenshots**

**Desktop (please complete the following information):**
Windows 10
Java 15.0.10

**Additional context**
[Domain 1. Manage Worksheets and Workbooks (10% - 15%).zip](https://github.com/freeplane/freeplane/files/12995738/Domain.1.Manage.Worksheets.and.Workbooks.10.-.15.zip)
![Pack 'n Go Error](https://github.com/freeplane/freeplane/assets/109234177/7fe013a4-e9d0-4744-86bf-b612562d04fd)

There was also a bug sent with another Add-On " Insert Inline Image".
When I open the Insert Inline Image Addon and click on the folder Icon to add, nothing happens and there is a beeping error sound.

Thanks in advance

**Comment by macmarrum** [comment]
Pack'n'Go isn't maintained anymore. You can try [Pack & Go-Go](https://github.com/macmarrum/freeplane-PackAndGoGo). In case of issues, please raise a ticket in https://github.com/macmarrum/freeplane-PackAndGoGo/issues
