### ISSUE TITLE
"Add node" action in toolbar

### ISSUE THREAD

**Issue by SoerenBusse** [freeplane/freeplane#148]
Hey there,

is there a way to add a "Add node" button to toolbar which mimics the behaviour of the insert key? When I first opened freeplane I had to search for the insert node button which is very hidden in the edit menu after I found the insert key.

Why? Especially when you're using a touch device you've to do 3 touches to add a new node which is from my point of view to much clicks for a a very fundamental function. In addition not every on screen keyboard on a touch device have an insert key directly accessible so you've to do multiple clicks here, too.

Or is there a simple way to remap the insert key to a different one, because not every hardware keyboard might have this key now days.

Thank you very much in advance

**Comment by gurkanctn** [comment]
Adding a node is possibly the most frequently used action during the creative phase. I want to fastly and intuitively create several nodes, here and there. 

Here's some ideas that I literally tried intutionally a few moments ago:

1. Right-click an existing node and drag to a direction to create a new node, linked to the existing one.

2. Just right click anywhere on the map (not on an existing node), and choose "add linked Node here" / "add floating Node here". Linked Node might wait for clicking to select the Source node to be linked with the New node.

**Comment by dpolivaev** [comment]
Yes, you need to learn how to use the tool properly.
And you need to learn how to use short cuts.
All short cuts are indicated in the menus.

**Comment by gurkanctn** [comment]
Dude, We're spending our time expressing ideas to improve the software here, not to criticize people who devote their time to improve it. Closing the issue with such a comment was not what I was expecting.

I know the menus, I know and use the (frequently used) shortcuts, and I've been using FreePlane for many years, "properly" or not. 

Right clicking to create a new node is not there, I swear. And I can't generate a new node towards a direction. Please let us know how you can click a mouse button with a keyboard shortcut. :) It seems you have not read what I have proposed at all.

If you want to improve the software, first of all, you have to take and respond to comments more properly. :)

**Comment by dpolivaev** [comment]
Hey,

if you want to help please submit your suggestion to https://sourceforge.net/p/freeplane/discussion/758437/ as a new post for community evaluation. 

Regards

**Comment by gurkanctn** [comment]
Sorry, I'm not willing to join yet another community (at sourceforge) to re-iterate an idea I've already written. (too much friction for an outsider to contribute a small idea)

Greetings.
