### ISSUE TITLE
Start the search operation by pressing the enter button.

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1498]
When I search for an item from the toolbar, by pressing the enter button, the first search result appears in the mind map. This is great.

But when I search for an item with the shortcut "Control + F" or through "Edit/Find/Find", the search does not start when the enter button is released, and the first search result does not appear, only the search box disappears.
To show the first search result, I have to click the "Find Next" icon after the search box disappears. It would be great if the software had the same functionality when we search from the toolbar.

**Comment by aaa1386** [comment]
Thank you for the change in the program.
Only when we use the mode "Control + F" or through "Edit/Find/Find" to search, there is a difference with the mode when we use the search box in the toolbar.

When the toolbar box is used, by pressing the enter button, the first search is revealed, if we press the enter button again, the second result is shown until we go to the editing mode, the enter button maintains its function and actually instead of "Find Next" shortcut works. This performance is very good and interesting. When we go to the editing mode (for example, we edit a node), the enter button performs its former function that we have set for it in the software.
All these things are good.
But when we use the modes "Control + F" or through "Edit/Find/Find" to search, by pressing the enter button, the search box disappears and the first search result is shown, but if we press the enter button a second time It goes to edit mode, not the one that shows the second search result, and this function is different from the function of the search box in the toolbar.

**Comment by dpolivaev** [comment]
Preview 1.11.8_07

**Comment by aaa1386** [comment]
I think I explained some parts badly.
It was very nice that the search box would disappear from the middle of the mind map by pressing the "enter" button.✅✅✅

After the changes , the search box does not disappear by pressing enter, and we have to press the escape key to make it disappear. This is not good in my opinion. It is a bit complicated. The search box also covers some nodes and results in the middle of the page.
I thought the following idea is possible: that when we type a word in the search box after pressing the "enter" button, the box will disappear and the first result will be shown, in addition to this, by pressing the enter button for the second time, the next result will be displayed. The search will be shown and the next results will be revealed by pressing the "Enter" button. Like searching in the toolbar, which shows the next searches every time you press enter.

Therefore, if this is not possible, return the program to its previous state, i.e., the state in which by pressing the first enter, both the search box disappears and the first result is shown. For the next results, we can use the "Find Next" shortcut button.
I'm sorry.

**Comment by aaa1386** [comment]
In other words, everything is fine except that the box is not hidden by pressing "enter"
