### ISSUE TITLE
If the search has no results, a message will be displayed.

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1499]
Sometimes we search for an item in the mental map, but that item does not exist in the mental map. It is suggested that a message be displayed stating that the item for our search was not found.

**Comment by KamalAhmad07** [comment]
hey @ajaberi1360 can you provide a screenshot what's are you searching and message is not being displayed.

**Comment by aaa1386** [comment]
Hello . I mean something similar to the One Note software that is shown in the image, when the search does not contain a result, a "No matches" message is displayed.

![image](https://github.com/freeplane/freeplane/assets/38586259/854ba897-f2cc-4ed4-91b0-011af5b0c504)

**Comment by dpolivaev** [comment]
Visual feedback added
Preview 1.11.9_05

**Comment by aaa1386** [comment]
thanks.
