### ISSUE TITLE
Two different policies in clouding a node

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1511]
When the background of the nodes is white, by clouding the node, all the nodes and the space outside the nodes become the color of that cloud. Such a function is not appropriate.
If the background of the nodes is non-white, by clouding the node, only the outer space of the nodes will become a cloud color, which is very suitable and good.

See the following video:

https://github.com/freeplane/freeplane/assets/38586259/875efc2b-82b9-4651-967e-b13ad196cf43

**Comment by dpolivaev** [comment]
Freeplane behaves as expected.
Generally, if you submit any bug report, I always need the mind map shown in the video.
Even if you believe the video is enough, it is usually not enough.

In this particular case it looks like transparen background color is set for the default style. It looks white on a white map background, but the nodes takes the color of their background.
You can define non transparent color for your default style.
It does not matter which color e.g. white it is.

**Comment by aaa1386** [comment]
[gggggg.zip](https://github.com/freeplane/freeplane/files/13239488/gggggg.zip)

**Comment by aaa1386** [comment]
Mind map sent

**Comment by dpolivaev** [comment]
Thanks, I checked it, my assumption was correct.

**Comment by aaa1386** [comment]
Thanks, I now understand how Freeplane works.
