### ISSUE TITLE
Ability to search in all opened mental maps.

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1529]
I have a lot of mental maps. Sometimes I open some of them that have a lot to do with each other. I want to search a branch or node. I don't know exactly in which mind map it is.

So I have to search for that item in each and every mind map. This is hard work.

I suggest to make it possible to search all open mind maps.
I think such an idea would be useful for many people.

**Comment by EdoFro** [comment]
![image](https://github.com/freeplane/freeplane/assets/35700575/d363106a-da84-45df-834c-717ea4e1c579)

**Comment by aaa1386** [comment]
Thank you.
"Find and Replace" solves an important part of my need, but not all of it.
Especially since there is a problem in right-to-left languages, which I will explain in the next comment.

I suggest that when we search for a word in the "Find and Replace" environment, the same word should be written in the search box in the toolbar, so that if we want to continue the search, we can follow it in the mental map. With this, a complete search will take place, half of it in the "Find and Replace" environment with good facilities such as "Date Medifield"... and its continuation in the mental map with the "Find Next" and "Find Previous" options.

**Comment by aaa1386** [comment]
bug : Right-to-Left Unicode
Error showing node path -

![image](https://github.com/freeplane/freeplane/assets/38586259/13698f3a-ced4-4f11-8958-4903b6d909ae)

**Comment by aaa1386** [comment]
[خطا - Right-to-Left Unicode bug.zip](https://github.com/freeplane/freeplane/files/13360373/-.Right-to-Left.Unicode.bug.zip)
