### ISSUE TITLE
Freeplane downloads is reported to contain virus'es using VirusTotal

### ISSUE THREAD

**Issue by jancoffee** [freeplane/freeplane#1532]
**Describe the bug**
Freeplane "freeplane_bin-1.11.8.zip","FreeplanePortable_1.11.8.paf.exe" downloads is reported to contain a virus using VirusTotal

**To Reproduce**
Downloading "freeplane_bin-1.11.8.zip" from https://sourceforge.net/projects/freeplane/files/ and uploading it to VirusTotal.
https://www.virustotal.com/gui/file/c76e0142f4493cce3ac64c7bc731576a3a19a40963b5cd9b471d0f9555ae2ece?nocache=1

Downloading "FreeplanePortable_1.11.8.paf.exe" from https://sourceforge.net/projects/freeplane/files/ and uploading it to VirusTotal.
https://www.virustotal.com/gui/file/fc43ba3aadd611a29a84c63e00dba0e9ef3e1d5f097634daa15d954598ea7612?nocache=1

**Expected behavior**
No virus reported in VirusTotal

**Comment by dpolivaev** [comment]
I think it is a false positive
