### ISSUE TITLE
DirectoryOpenException: Program Blocking

### ISSUE THREAD

**Issue by guoranjun2** [freeplane/freeplane#1535]
**Describe the bug**

I found that starting from version 1.11.7, opening folders through node links causes the program to block, while opening files works fine. 
see attachment.

**Mind map files**
[DirectoryOpenException.zip](https://github.com/freeplane/freeplane/files/13386869/DirectoryOpenException.zip)

**Desktop (please complete the following information):**
 - OS: win11 21H2
 - Version: 1.11.7
 - Java Version: java17

**Comment by dpolivaev** [comment]
I checked it on my Windows 10, it worked  fine.
Starting with 1.11.7 I use standard Java API to open files, https://docs.oracle.com/javase/8/docs/api/java/awt/Desktop.html
I do not know why it does not work on your machine.
