### ISSUE TITLE
issue with node text starting with a single quote

### ISSUE THREAD

**Issue by pohutukawa** [freeplane/freeplane#1555]
**Describe the bug**
When a single quote is used as a first character in node content, that first character (the quote/apostrophe) will not be displayed. Furthermore, when exporting a mind map with nodes starting with a single quote (e.g. to LaTeX Beamer), those nodes do not make it into the exported content. When exporting to other formats (e.g. Markdown), the node does not show up in the document hierarchy (the prefixed `###` characters for section headings as the other content has), but it shows up as text under the parent node's hierarchy level. In those cases the leading single quote 'lives on'.

This is particularly an issue for countries using a single quote (as opposed to a double quote) for quoted text, such as UK, NZ, AU, ...

**To Reproduce**
Steps to reproduce the behaviour:
1. Under any existing node, make a new node
2. Use something with a leading single quote as the node's content, e.g. `'test content' for demonstration`
3. See that the leading quote is missing in the UI, but the closing quote after `content` is shown
4. Export to LaTeX Beamer, and see the node missing
5. Export to Markdown, and see the node not being integrated into the hierarchy as the rest of the content

**Expected behaviour**
Any node content starting with a single quote needs to be a 'first class citizen' to be displayed in the UI and show up in any exports in the same way as other nodes do.

**Mind map files**
See attached `example.zip` containing the `.mm` file together with exported `.md` and `.tex` files.
[example.zip](https://github.com/freeplane/freeplane/files/13506117/example.zip)

**Screenshots**
![single_quote_issue](https://github.com/freeplane/freeplane/assets/422922/ed3a2948-ceba-41c6-8a90-d937834750eb)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Version: 23.10
 - Java Version: OpenJDK Runtime Environment Corretto-17.0.9.8.1 (build 17.0.9+8-LTS)

**Additional context**

**Comment by pohutukawa** [comment]
For some reason the file attachment didn't work on the initial one,here it is.
[example.zip](https://github.com/freeplane/freeplane/files/13506095/example.zip)

**Comment by dpolivaev** [comment]
The behavior you're experiencing with nodes starting with a single quote is related to how Freeplane recognizes and processes certain types of content. Specifically, Freeplane treats numbers or formulas differently when they are prefixed with a single quote. For instance, "001" is recognized as "1", but adding a single quote at the beginning ('001) prevents this conversion. Similarly, to stop a node from being treated as a formula, which typically starts with an '=', a single quote can be added before the '='.

This functionality is designed to give users more control over how their content is interpreted and displayed in Freeplane. However, it appears that this feature might also be affecting the display and export of nodes that unintentionally start with a single quote, especially in contexts where single quotes are commonly used, such as in certain languages or regional writing conventions​​.

In terms of a solution, it may be necessary to adjust the content of the nodes or employ a workaround, like using a different character or format for the start of the node text. However, this is an inherent aspect of how Freeplane processes certain characters and not a bug per se.

To disable the recognition of data such as numbers or dates in Freeplane, which is causing the issue with the single quote, you can use the following methods:

1. Turn Off Data Recognition Completely: This can be done in the Preferences under 'Behavior->Data formatting and parsing'. Disabling this option will stop Freeplane from automatically recognizing and formatting data like dates or numbers.

1. Change Node Format to Text: For individual nodes, you can change their format from the default to "Text". This adjustment can be made in the node's properties and will prevent data recognition for that specific node.

1. Start Typing with a Single Quote: If you begin typing a node's content with a single quote, Freeplane will automatically change the text format to "Text" for that node.

1. Change the Map Template to Text Format: You can set the format to "Text" in the standard map template ("standard.mm"). This will ensure that all new maps created using this template will have "Text" as the standard format, thereby avoiding automatic data recognition​​.

**Comment by dpolivaev** [comment]
https://chat.openai.com/share/1808eec4-3e0a-49f1-aeb5-688256cfc634

**Comment by pohutukawa** [comment]
@dpolivaev, thanks for the (AI generated) answer. So I get why it's a desired feature/functionality. And I may not want to turn it off all the way, but want to live with the solution # 2 explained above. How can I make a node a 'text node' and still be able to keep the leading quote in it? This is not explained. I've been looking, but can't find the answer looking through the Freeplane UI.

Maybe a human answer may be less flawed (though also less polished/convincing sounding).

Anyway, I'd appreciate an answer on how to make it work.

Cheers

**Comment by dpolivaev** [comment]
I don't see your point. The answer generated by the AI is excellent and complete, there is nothing more to say.

**Comment by pohutukawa** [comment]
I've not been able to find such a 'text property' under Edit → Node properties.
Neither under Edit → Node core or Format → Node core or Format → Style.

Furthermore answer # 3 for 'disable the recognition of data' explains just the normal behaviour (again), without telling me on how I can create a node with a leading single quote. Thus it's a non-answer.

**Comment by macmarrum** [comment]
![2024-05-02_09,40,26](https://github.com/freeplane/freeplane/assets/7197131/cbc94d37-61d9-41e1-93b4-930b5c50292c)
