### ISSUE TITLE
Inconsistent toolbar icon sizes

### ISSUE THREAD

**Issue by DavidInHawawii** [freeplane/freeplane#1580]
**Describe the bug**
Some icons on the toolbar display as a lot smaller than others.

**To Reproduce**
1. Start Freeplane v1.11.8.
2. Display toolbar if needed.
3. Note size differences between toolbar icons.

**Expected behavior**
Consistent toolbar icon sizes.

**Screenshots**
Added.
![Screenshot_2023-12-12_12-56-10](https://github.com/freeplane/freeplane/assets/83108243/73398b0e-0cda-4a0a-9382-2a8e4a056535)

**Desktop (please complete the following information):**
 - OS: Linux Debian Bookworm
 - XFCE
 - Java Version: 17.0.9

**Additional context**
Using a 14" 4K laptop display set to 192DPI.
Icon set in use is Yasis (Yet Another Scalable Icon Set).
Style theme is Adwaita-Dark.

**Comment by dpolivaev** [comment]
Preview 1.11.9_04
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
