### ISSUE TITLE
Freeplane 1.11.8 shortcut issue in 32-bit machines

### ISSUE THREAD

**Issue by metaad** [freeplane/freeplane#1581]
**Describe the bug**
Downloaded and installed Freeplane-1.11.8 - https://excellmedia.dl.sourceforge.net/project/freeplane/freeplane%20stable/Freeplane-Setup-1.11.8.exe
in Windows 32-bit machine. While launching the shortcut it requires Java Runtime Environment 11-17.999 (64-bit), but 64-bit java is not supported in 32-bit machine.

**To Reproduce**
1. Downloaded https://excellmedia.dl.sourceforge.net/project/freeplane/freeplane%20stable/Freeplane-Setup-1.11.8.exe
2. Installed the application - Freeplane 1.11.8 in Windows 32-bit machine
3. Launched the shortcut - Freeplane
4. Getting a prompt: "This application requires Java Runtime Environment 11-17.999(64-bit)

**Expected behavior**
Shortcut should launch as it does in 64-bit machine with Java 64-bit installed.
But as 64-bit Java is not supported in 32-bit machines, 32-bit Java should give the expected behavior.

**Screenshots**
![image](https://github.com/freeplane/freeplane/assets/106653425/53a480b2-08cc-4cd5-9982-293742a0c233)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise
 - OS Version:10.0.19045 N/A Build 19045
 - Java Version: Azul Zulu JRE 11.68.17 (11.0.21), 32-bit

**Additional context**
In windows 64-bit machine, Freeplane 1.11.8 works as expected with Java 11, 64-bit.

**Comment by dpolivaev** [comment]
Preview 1.11.9_04
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

**Comment by metaad** [comment]
@dpolivaev 
Thank you for your response.

Downloaded and installed Freeplane-1.11.9 -
https://master.dl.sourceforge.net/project/freeplane/freeplane%20preview/Freeplane-Setup-1.11.9-pre04.exe?viasf=1 using the above-mentioned link https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

- Installed the application - Freeplane 1.11.9 in both Windows 32-bit and Windows 64-bit machine where "**Azul Zulu JRE 11.68.17 (11.0.21), 32-bit**" is already present.
- Launched the shortcut - Freeplane
- Getting a prompt: "This application requires Java Runtime Environment 11-21.999" in both the machines
-  Attached snip for your reference.

![image](https://github.com/freeplane/freeplane/assets/106653425/ce11d148-bd35-4ab8-8c57-09de70577505)

**Comment by dpolivaev** [comment]
https://chat.openai.com/share/be4b2203-9454-4e3d-b93e-df8475fc31ab

**Comment by metaad** [comment]
@dpolivaev
Thank you for your response.

**In 64-bit machine:**
Freeplane 1.11.9 works as expected with J**ava 11/Java 17/Java 18, 64-bit.**
But getting the below prompt when **Java 8 - JDK or JRE.**
![image](https://github.com/freeplane/freeplane/assets/106653425/f6fd1f9d-c99d-4154-91c1-e33072059af9)

**In 32-bit machine:**

As suggested, tried adding the environment variable:
**Azul Zulu JRE 11 - With Environment variable**
Shortcut is not launching.
![image](https://github.com/freeplane/freeplane/assets/106653425/1728d684-eeca-44f3-b524-7bbbfbb7e4c0)

**Azul Zulu JRE 8 – With Environment variable**
![image](https://github.com/freeplane/freeplane/assets/106653425/ed0bd92d-7573-431b-9433-dad96f9911d4)

![image](https://github.com/freeplane/freeplane/assets/106653425/a5509bd3-06c7-4c7d-ac91-ccece6cfff86)

**JRE 8 with Env variable:**
![image](https://github.com/freeplane/freeplane/assets/106653425/21e1ae78-fac6-4a82-97fd-a96b204afc56)

![image](https://github.com/freeplane/freeplane/assets/106653425/9605638c-ec7c-4924-9db3-2d12846b2129)

Could you assist us to get the shortcut functionality in 32-bit machine?
Thank you.

**Comment by i-plasm** [comment]
@dpolivaev , I  can confirm @metaad 's  observation that in the previews ( I tried 1.11.9_01 and 1.11.9_10) the freplane.exe shortcut is not launching if FREEPLANE_JAVA_HOME is set to **Java 11.** But this time not even a popup error message appears, so the user has no feedback about what went wrong. However, setting FREEPLANE_JAVA_HOME  to **Java 17** fixes the problem. _Edit to add: my machine is Windows 10, 64-bit_

**Comment by dpolivaev** [comment]
Preview 1.11.9_13 supports Java versions 8 and 11 to 21 on Windows. However, it comes at costs of extra launcher written in Java that fixes the command line parameters and occupies about 100 mb ram extra.
