### ISSUE TITLE
fragmentized windows keep rendering along with cursor everytime when editing node. 

### ISSUE THREAD

**Issue by eremite-404** [freeplane/freeplane#1590]
**To Reproduce**
just open it and start showing this

**Expected behavior**
It seems to be java's JSE problem, cause it happens on Docear(which is also based on JSE)

**Mind map files**

**Screenshots**
![Uploading Snipaste_2023-12-17_17-16-14.png…]()

**Desktop (please complete the following information):**
 - OS: windows10
 - 1.11.8
 - Java 8 update391 (I have tried the former version but does not help )

**Additional context**

**Comment by dpolivaev** [comment]
The screenshot link is broken

**Comment by eremite-404** [comment]
https://github-production-user-asset-6210df.s3.amazonaws.com/52479912/291060805-ed90f9db-35f4-4936-b8fe-2eb00c01e339.png

the symptom in the screenshot is like: when the situation happens, the fragment windows show everytime the cursor hovers on the clickable buttons (for example: the node unfold&fold buttons and even the setting button on the top of the freeplane).

and also I found that the situation only happens when typing chinese characters or typing and inserting nodes quickly.
by the way change nodes' font to chinese style would make the freeplane error sound and window totally frozen and then crashed

and It's all function okay before, and still okay in my another laptop, so I guess It's specific on my computer. but I still wonder why this happens, It's a excellent mindmap software and it's sad not able to  continue using it.

**Comment by dpolivaev** [comment]
Same to me: I do not know when and why it happens on some computers. I am sorry I can not help because I do not own a computer where it happens.
