### ISSUE TITLE
Perhaps there is a vulnerability that needs to be addressed.

### ISSUE THREAD

**Issue by Kezry** [freeplane/freeplane#1593]
**Describe the bug**
My antivirus software alerted me to a security vulnerability and recommended using its provided method to patch the vulnerability to prevent potential issues. However, upon restarting the software, I encountered the following error.

**To Reproduce**
I'm not sure what happened exactly, but the antivirus software patched some vulnerabilities in the JDK. Perhaps using a newer version of the JDK might result in this issue. ->Freeplane-Setup-with-Java-1.11.8
By the way, I'm using 360 Antivirus.

**Expected behavior**
java_version = 15.0.10; os_name = Windows 11; os_version = 10.0
Exception in thread "AWT-EventQueue-0" 
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    groovy/lang/GroovyClassLoader.getPermissions(Ljava/security/CodeSource;)Ljava/security/PermissionCollection; @62: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'java/security/PermissionCollection'
  Current Frame:
    bci: @62
    flags: { }
    locals: { 'groovy/lang/GroovyClassLoader', 'java/security/CodeSource', 'java/lang/Object', 'java/security/ProtectionDomain', 'java/security/PermissionCollection', 'java/util/Enumeration' }
    stack: { 'java/lang/Object', 'java/security/Permission' }

**Comment by dpolivaev** [comment]
Some false positives happen always. As long as the majority of the AV finds nothing, the presence of a virus is quite unlikely.
