### ISSUE TITLE
Issue when running with Adoptopenjdk (Hotspot VM)

### ISSUE THREAD

**Issue by bzg** [freeplane/freeplane#161]
Hi, I am not the person observing the issue directly, I'm just reporting observations made by another user. This user is a central administration in France, using freeplane with no problem since a long time for many users.

This administration made the switch to AdoptOpenjdk (Hotspot VM) and suddenly freeplan is not working anymore.

Has anyone experienced the same issue?

What data would you need to get more information on this issue?

**Comment by Ciruman** [comment]
Hi @bzg, did you tried to start making use of the script or the executable? I had problems in Windows 10 with the executable(always asking for making use of the Oracle JDK) but no problem with the script.

**Comment by bzg** [comment]
Hi @Ciruman, thanks for your answer!  I will send your suggestion to the person that reported this issue to me, I hope it will solve his problem.

**Comment by bzg** [comment]
I did not have any feedback from the person, I'm closing this (old) issue.
