### ISSUE TITLE
special character - incorrect after leaving node

### ISSUE THREAD

**Issue by Bommi46** [freeplane/freeplane#1613]
I inserted a special character into a node (black triangle). As long as the cursor is inside the node, the triangle is displayed correctly. However, once I remove the cursor from the node, only a placeholder is visible instead of the triangle. I have attached a screenshot.
Windows 11
freeplane 1.11.9 with included java
![Screenshot special character](https://github.com/freeplane/freeplane/assets/120022537/baece2e7-4196-40db-9e04-f6efe95cd699)

![grafik](https://github.com/freeplane/freeplane/assets/120022537/c9e355d9-44b3-4cae-9350-924822e37cae)

**Comment by dpolivaev** [comment]
Freeplane does not support some characters, it is a known limitation
