### ISSUE TITLE
Question: how to add a summary node?

### ISSUE THREAD

**Issue by fwfsf** [freeplane/freeplane#1614]
How to add a summary node to e and f?

![question](https://github.com/freeplane/freeplane/assets/107751295/29e18e3a-254c-4373-abb6-4eba666a6cc2)

**Comment by dpolivaev** [comment]
Add it to b and d

**Comment by fwfsf** [comment]
Using b and d still fails.

![bd](https://github.com/freeplane/freeplane/assets/107751295/ade1161c-fd48-4947-900f-2d2c23bb22e4)

I want to implement the following structure:

![gg](https://github.com/freeplane/freeplane/assets/107751295/d4337c21-80bb-4c63-9054-a821a4ad283b)

Is there any way to implement it?

**Comment by dpolivaev** [comment]
I checked it and yes it is not supported: 

Node f is a first-level summary node.
A summary node containing f should be a second-level summary node.
But neither node b nor node e is a summary node.

Therefore, you can not have a summary node that summarizes b or e together with f.

**Comment by dpolivaev** [comment]
If e would be summary node of b, g could be summary node of e and f

<img width="354" alt="summarynodes" src="https://github.com/freeplane/freeplane/assets/1558052/45fddecc-e785-45c1-a255-a5b76e5e24e9">
