### ISSUE TITLE
FP 1.11.9 05: after installation it changed style of all nodes with link

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#1617]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Screenshots**
it changed the style of at least all of the nodes with links to the blue with underline, even if the node already with a user-style

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22] 11
 - Java Version: that of FP installation

**Additional context**
to revert I installed again the FP 1.11.9 04

**Comment by Illegit** [comment]
I see the comment was strangely written see above: I duplicate here again--> 
Describe the bug
it changed the style of at least all of the nodes with links to the blue with underline, even if the node already with a user-style

Desktop (please complete the following information):

OS: [e.g. iOS] Windows
Version [e.g. 22] 11
Java Version: that of FP installation

Additional context
to revert I installed again the FP 1.11.9 04

**Comment by dpolivaev** [comment]
Preview 1.11.9_06

**Comment by Illegit** [comment]
That's Ok Thanks.

Il mar 2 gen 2024, 19:37 Dimitry Polivaev ***@***.***> ha
scritto:
