### ISSUE TITLE
Freeplane 1.11.8 doesn't support Java 21 on Arch Linux.

### ISSUE THREAD

**Issue by rbarte** [freeplane/freeplane#1619]
**Describe the bug**
Freeplane 1.11.8 doesn't support Java 21 on Arch Linux.

**To Reproduce**
1. Open terminal.
2. Type freeplane and click enter.
3. See error:
`ERROR:   Found /usr/bin/java in $PATH.
ERROR:   It has version 21
ERROR:   Currently, freeplane requires java version 8 or from 11 to 17
ERROR:   
ERROR:   Select a supported java version
ERROR:   by setting FREEPLANE_JAVA_HOME to a valid java location
ERROR:   OR use an unsupported java version
ERROR:   by setting FREEPLANE_USE_UNSUPPORTED_JAVA_VERSION to 1`

**Expected behavior**
"Freeeplane 1.11.x requires Java between Java 11 and Java 21 on Windows and Mac, Java 8 and Java 21 on Linux." 
Source: https://docs.freeplane.org/getting-started/Command-line_options_and_configuration.html
So it shall run on Linux with Java 21.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: current 
 - Java Version: openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35)
OpenJDK 64-Bit Server VM (build 21+35, mixed mode, sharing)

**Additional context**
 Freeplane works fine again when I change the environment to use Java 11(openjdk 21 2023-09-19 OpenJDK Runtime Environment (build 21+35) OpenJDK 64-Bit Server VM (build 21+35, mixed mode, sharing).

**Comment by dpolivaev** [comment]
Already fixed for Freeplane 1.11.9, you can find the preview in https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
