### ISSUE TITLE
A predefined node style that can be switched by shortcuts

### ISSUE THREAD

**Issue by icesof** [freeplane/freeplane#1629]
**Is your feature request related to a problem? Please describe.**

Freemind has been a part of my life for many years. One of the most popular features of this software is the ability to switch node style with key shortcuts, which help users to easily understand the status of the nodes. A F5 key, for example, will change the text's color to red when I am working on something, and a F7 key will change the color to grey once I have completed it.

**Additional context**

**Comment by Olifair** [comment]
Seems to be very useful to me :-)

**Comment by i-plasm** [comment]
Hello @icesof . This could be useful: If you are on Windows, you can use the ` alt + < ` shortcut to insert a task progress icon and increase progress by 25% increases (25% -> 50% -> 75% -> 100% = DONE), and ` shift + alt + < ` to decrease progress analogously. If you are on another platform, check the shortcuts on the menu ` Insert > Icon > Progress Icon % ` or assign new ones with  ` Tools > Assign hot key ` . If you don't like that solution and still prefer switching font colors, you can do it via user styles this way:

1. Go to ` Format > Manage styles > Edit styles ` and create two user styles (` Manage style > new user style`), one style named 'task_in_progress' and the other 'task_completed'. Assign the font colors and any other desired formatting to each of those styles. When you are done, click "OK" to save the new styles.
1. Save these two scripts
    1. Script 1 (please save this as a file named taskCompleted.groovy):
	
	~~~ groovy
	import org.freeplane.plugin.script.proxy.ScriptUtils

	ScriptUtils.c().getSelected().getStyle().setName("task_completed")
	~~~
	
	1. Script 2 (please save this as a file named taskInProgress.groovy)
	
	~~~ groovy
	import org.freeplane.plugin.script.proxy.ScriptUtils

	ScriptUtils.c().getSelected().getStyle().setName("task_in_progress")
	~~~
1. Install the scripts. 
1. Restart Freeplane
1. Now you can assign your desired shortcuts to the scripts via ` Tools > Assign hot key ` (the scripts are located in the menu ` Tools > Scripts > Task In Progress/Task Completed`. Now you can use those shortcuts to change the node style.
1. NOTE: Make sure you have script execution enabled. Go to `Tools > Preferences > Plugins `, and in the 'Scripting'  section set `Script execution enabled` to "Yes"

Best regards

**Comment by EdoFro** [comment]
I think I am missing something here, because in Freeplane you can assign hot keys to styles directly. 

just:
1. go to menu `Format-> Styles`
2. hold Ctrl key and click on the style you want

No need for extra scripts.

**Comment by icesof** [comment]
hi @i-plasm ,

I'm really thrilled to have received it. And, I'm very thankful to all of your suggestions for continuing to let us play in the world of freeplane. 

BR,
Peter

**Comment by icesof** [comment]
hi @EdoFro ,

That's a good quick-start guide.

BR,
Peter
