### ISSUE TITLE
temporary .mm~ files not deleted upon closing

### ISSUE THREAD

**Issue by Olifair** [freeplane/freeplane#1630]
**Describe the bug**
When I close FreePlane, then the temporary .mm~ files are not deleted automatically, so when I re-start FreePlane, it will complain the the files are already edited and will open them only in read-only mode. And it does this for every file in a separate window (which is totally normal). But as I have usually about 20 maps open in different tabs, this needs a lot of clicking before FreePlane is actually started. I then need to re-close, remove manually the .mm~ files and restart FreePlane. I have tried for some of the maps to change then and save them, but this does not change the temporary files problem. I think this has started since I have installed the latest version that I'm running, 1.11.8 (I'm running windows 10, 64 bits, FreePlane runs on Java 15.0.1. 

I would be grateful if anybody has any ideas of how to correct this problem 

And a happy new year to everybody in the group, but especially Dimitry and all the people actually programming FreePlane
Cheers
Oliver

**Comment by dpolivaev** [comment]
Yes, I can confirm the bug. Thanks for reporting. To be fixed soon.

**Comment by Olifair** [comment]
Thanks, 
I unchecked the "Experimental file locking" option as suggested by @EdoFro , and this seems to have resolved this problem. 
I have answered more questions in the discussion thread [here](https://github.com/freeplane/freeplane/discussions/1645#discussioncomment-8165999)

**Comment by dpolivaev** [comment]
Bug fix available in preview 1.11.9_13
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
