### ISSUE TITLE
modify creation date

### ISSUE THREAD

**Issue by Olifair** [freeplane/freeplane#1631]
Is there any way to change the creation date of a node ?
I would like to use on map of gathering recent informations that I get and then regularly using a date filter to check of old informations and delete them. I will then, depending on icons, delete infos that are older than X days, weeks or months. 
But to do this properly, the creation date of a node needs to reflect some date intrinsic to the information. Sometimes (actually regularly, as I'm always late in my emails) I will put informations into the mindmap which predate the creation date. So, for these nodes, I would like to edit the creation date. I haven't found an option to do this yet. 
If anybody has any thoughts on this, or a script, I would be gratefull :-)

Happy 2**10+1000
Cheers

Oliver

**Comment by euu2021** [comment]
It's possible to use scripts to change the creation date. For example, this change the creation date for the present moment:

`node.setCreatedAt(new Date())`

**Comment by Olifair** [comment]
Thanks @euu2021 . I have never programmed scipts for FreePlane, how would I go about it ?
I tried a one line script within an existing node (using Tools/Edit script : 
node.setCreatedAt(new Date(0)).format('dd/MM/yy')"10/12/23"
based on the FreePlane Groovy tutorial : https://docs.freeplane.org/scripting/api-groovy-tutorial.html
and on : https://docs.groovy-lang.org/latest/html/groovy-jdk/java/util/Date.html

but I just get an error : Result:Cannot invoke method format() on null object
while still the creation date is changed to "01/01/1970".

any ideas ?

**Comment by nnako** [comment]
Hi @Olifair ,

if you want to try an alternative to internal Groovy scripting, you could also try external Python scripting for this. Using the [`freeplane-python-io`](https://github.com/nnako/freeplane-python-io) library. Please just follow the simple instructions on the main project page to setup the the tool. And then write a Python file e.g. "`test.py`" like this:

```python
import freeplane
import datetime

# open mindmap containing nodes to be modified
mm = freeplane.Mindmap(r"Absolute\Path\To\Your\Mindmap.mm")

# localize your node e.g. by searching for its content or directly stating a node id
node = mm.find_nodes(core="put the node's text here")[0]    # the CORE TEXT must exist
#node = mm.find_nodes(id="ID_12345678")[0]                  # the NODE ID must exist

# create a timestamp to be set
timevalue = datetime.datetime.fromisoformat("2023-12-10"    # put your date value here
timestamp = str(int(timevalue.timestamp() * 1000))

# modify node's "created" attribute accordingly
freeplane.update_date_attribute_in_node(node._node, date=timestamp, key="CREATED")

# save mindmap
mm.save(r"Absolute\Path\To\Your\Mindmap.mm")    # might be the same as the one read from
```

Ready for a try?

**Comment by euu2021** [comment]
> Thanks @euu2021 . I have never programmed scipts for FreePlane, how would I go about it ? I tried a one line script within an existing node (using Tools/Edit script : node.setCreatedAt(new Date(0)).format('dd/MM/yy')"10/12/23" based on the FreePlane Groovy tutorial : https://docs.freeplane.org/scripting/api-groovy-tutorial.html and on : https://docs.groovy-lang.org/latest/html/groovy-jdk/java/util/Date.html
> 
> but I just get an error : Result:Cannot invoke method format() on null object while still the creation date is changed to "01/01/1970".
> 
> any ideas ?

another approach is to use postpones, instead of setting exact dates. I don't know if I understood correctly your usecase, but it seems that it would be useful to you simply pushing the creation date to the future, instead of picking an exact date.

So, you could have 3 scripts: one that postpones 1 day; the second postpones 1 week; and the third postpones 1 month.

For example, this script postpones the creation date for 1 week:

```
import java.time.ZoneId
import java.time.LocalDate
import java.time.Instant

nodeOriginalDate = node.createdAt
LocalDate nodeOriginalLocalDate = Instant.ofEpochMilli(nodeOriginalDate.getTime()).atZone(ZoneId.systemDefault()).toLocalDate()

LocalDate newDate = nodeOriginalLocalDate.plusWeeks(1)
Date date = Date.from(newDate.atStartOfDay(ZoneId.systemDefault()).toInstant())

node.setCreatedAt(date)
```

Do you need to pick exact dates? Do you need to deal with hours, or just dates?

**Comment by Olifair** [comment]
@euu2021  actually I would need exact dates; I would be quite content to have a one line script that I can copy/paste into the script part of a node, put in the correct date and then delete it again. 
Something as : 
`node.setCreatedAt(new Date(0)).format('dd/MM/yy')"10/12/23"
`
which unfortunately does not work, I guess the time format in the string is wrong.

**Comment by Olifair** [comment]
@nnako thanks for the idea; for the moment a one line Groovy script would do the trick and seems a "lighter" solution than installing the python packages.

**Comment by Olifair** [comment]
@euu2021  I have managed to create a date variable with : 
```
pattern = "yyyy-MM-dd"
input = "2023-12-13"
date = Date.parse(pattern,input)
```
but when I try to apply this to the setCreatedAt
`node.setCreatedAt(date)`

I get "Result:null" and no change in the created date. 
Any ideas ?

**Comment by Olifair** [comment]
@euu2021  I did it !

`node.setCreatedAt(Date.parse("yyyy-MM-dd","2023-09-24"))`

is working

Thanks again for putting me onto this
