### ISSUE TITLE
API is being generated in German

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1632]
My FP is set to English, but when I use `Help-Freeplane API…`, I get this:

![image](https://github.com/freeplane/freeplane/assets/77707706/00ca4438-7d5f-4093-acf2-920edf4bb233)

freeplane_bin-1.11.9-pre09

**Comment by dpolivaev** [comment]
Preview 1.11.9_10
I use Java 17 for javadoc generation now.
Java 21 has a bug (regression) https://bugs.openjdk.org/browse/JDK-8222793
