### ISSUE TITLE
Feature Request: Automatic Template Change for Existing Maps

### ISSUE THREAD

**Issue by alexalxs** [freeplane/freeplane#1637]
Hello Freeplane Team,

I am a frequent user of Freeplane for organizing my thoughts and managing knowledge. I greatly appreciate the flexibility and functionality your software offers. However, I've encountered a situation where I believe an additional feature could be immensely beneficial.

Currently, when I wish to apply a new template to an existing map, I have to manually copy and paste styles and elements from the template to my map. This process can be time-consuming, especially for complex maps or when trying to maintain a consistent style across multiple maps.

I would like to propose a feature for automatically applying a new template to an existing map. This feature would allow users to easily update the visual style and layout of their maps without the need to manually adjust each element. Ideally, this function would let us choose a new template and automatically apply its styles, colors, fonts, and node formats to the current map.

I believe this feature would significantly enhance the user experience, particularly for those who use Freeplane for complex projects or who need to frequently update their map's appearance.

Thank you for considering this suggestion. I am looking forward to any improvements that make Freeplane even more user-friendly and efficient.

**Comment by euu2021** [comment]
I'm not sure if I understood, but this may be helpful: `Format->Manage Styles->Copy map styles from…`

**Comment by alexalxs** [comment]
Thanks this work.
