### ISSUE TITLE
Note changes are totally lost on interaction with Tool Panel

### ISSUE THREAD

**Issue by i-plasm** [freeplane/freeplane#1638]
**Describe the bug**
When typing a new HTML note or editing an existing one inside the embedded Note Panel, the changes disappear on interaction with the Tool panel.

**To Reproduce**
1. Go to the *Note Panel*
2. Type anything
3. Interact with the *Tool Panel* in either of these ways:
    1. Resize the *Tool panel* by dragging the tool panel border (i.e manipulate the JSplitPane divider). (see gif video below)
    2. Hide the *Tool panel* by clicking on the arrow-like handle located on the JSplitPane divider (see gif video below)

**Expected behavior**
The note in the *Note panel* should not be deleted/altered unintendedly. This bug is particularly troublesome since the loss is permanent: the note can not be restored by *undo/redo* actions.

**Interesting observations**
1. The bug does NOT happen when editing Markdown notes, i.e using the embedded Markdown editor (following otherwise the same steps above)
2. The bug does NOT happen when manipulating the divider of the JSplitPane that contains the MapView and the Note Panel.

**Mind map files**
I reproduced this bug on both new and existing maps

**Screenshots**
![bug-note-disappears](https://github.com/freeplane/freeplane/assets/144830522/c05e8051-fced-407c-ab2b-f2d452393d44)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.11.7
 - Java Version: 15.0.10

**Comment by dpolivaev** [comment]
Preview 1.11.9_10
