### ISSUE TITLE
htmlToPlain: tags such as <p> should produce a new line

### ISSUE THREAD

**Issue by Opexy** [freeplane/freeplane#164]
https://github.com/freeplane/freeplane/blob/2ad1157eb8f54295595400f2ebd8b80704d895ab/freeplane/src/main/java/org/freeplane/core/util/HtmlUtils.java#L118-L120
I.e., Line 118,
`Pattern.compile("(?ims)<p[^>]*>\\s+"),`
will not produce a new line unless the tag <p> is followed by some space character.

Request to change line 118-120's \\s+ to \\s*
I.e., Line 118,
`Pattern.compile("(?ims)<p[^>]*>\\s*"),`
so each tag is replaced by \n properly in the process.

Thanks.

**Comment by dpolivaev** [comment]
Implemented in Freeplane 1.8.6, thanks
