### ISSUE TITLE
macOS: Display/Hide Note panel shortcut key displays the panel only

### ISSUE THREAD

**Issue by himatech** [freeplane/freeplane#1641]
In macOS, according to the shortcut keys mentioned in the menu, to display the Note panel I should press `command+>`.

1. It's actually `command+.`, I don't know why it's showing `command+>`
2. My keyboard layout is French Canada,so the `command+>` is not like the US keyboard layout. Anyway, it's always the same button `command+.`
3. When I press the shortcut key to display the note panel, it displays it and the cursor focus changes to this panel. When I press it again, I expect the panel to hide; it doesn't and the cursor focus changes to the map.

**Screenshots**
![image](https://github.com/freeplane/freeplane/assets/6548896/77729c45-b6d0-4501-b5a3-ebaf3d878d59)

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1 (23C71)
 - Version Freeplane 1.11.8
 - Java Version: 15.0.8

**Comment by dpolivaev** [comment]
There are the both shortcuts:
Edit->Note->Switch Note/Map Focus (⌘+.)
View->Notes->Display note panel (⌘+>)

**Comment by dpolivaev** [comment]
If you need to press the shift or option key to enter a character, you can do it even if the shortcut does not indicate it.

**Comment by himatech** [comment]
Thanks! What about point 3?

**Comment by dpolivaev** [comment]
Use Display note panel (⌘+>)

**Comment by himatech** [comment]
The keyboard shortcut doesn't hide the panel. It only shows it.

**Comment by dpolivaev** [comment]
I mentioned 2 shortcuts. Therefore your statement "The keyboard shortcut doesn't hide the panel. It only shows it." is ambiguous. Please try the both shortcuts and report your observations for each of them separatetly.

**Comment by himatech** [comment]
The two shortcuts don't work. Sure, I'll report my observations separately sometime this week. Thanks!

**Comment by i-plasm** [comment]
I checked in my old mac and I have issues with shortcuts as well, for instance (⌘+>)  does not work at all for me. I recall having troubles with shortcuts involving certain modifiers when I used a mac in the past . However, my suggestion for @himatech  is to assign a different shortcut, one that does not involve modifier keys other than ⌘ , for instance you could assign command + lesser (⌘ + <) , which in my experience successfully hides/displays the notes panel in my mac. To assign a shortcut go to ` Tools > Assign hot key ` .

**Comment by himatech** [comment]
@i-plasm Amazing idea, thank you! I just assigned different keys to this option and all good now 😄. FYI, I imitated the shortcut keys of Mindmanager because I was used to it for years.
