### ISSUE TITLE
​'ZWSP' character in the API

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1642]
Some of the methods, when copied directly from the API, show a ​'ZWSP' character, which is invisible everywhere but on an IDE. For example, this method:

![image](https://github.com/freeplane/freeplane/assets/77707706/9264aa9a-81aa-4033-92ca-7107e8d81214)

This creates confusion in the user (see https://github.com/freeplane/freeplane/discussions/1542#discussioncomment-7622212), and may cause difficulties for ChatGPT to read the API. 

I'm trying to give the API to ChatGPT in HTML format, and it cannot read it. I don't know what is the reason, but it could be that 'ZWSP' character problem. The message is:

![image](https://github.com/freeplane/freeplane/assets/77707706/a920732d-da00-4d49-b729-d37d6276eb73)

Is it possible to avoid the ​'ZWSP' character being created in the Javadoc?

**Comment by euu2021** [comment]
Even if the ChatGPT problem is not related to the ​'ZWSP' character, I think the user confusion problem is an issue to have in mind.

**Comment by dpolivaev** [comment]
I do not influence how Javadoc is generated; they change with new java versions.
