### ISSUE TITLE
I want a website for collections of templates where you could freely download templates and share your good templates

### ISSUE THREAD

**Issue by Stephenzero** [freeplane/freeplane#1648]
I want a website for collections of templates,  where you could freely download templates and share your good templates

just like emmmm, when you use MS office 365,  alright.

MS will provide you lots of templates, right?

so, if we could share some templates on a website and others could download it that could be much better.

**Comment by dpolivaev** [comment]
You can use Freeplane discussion forums at GitHub and post all your mind maps and templates zipped using https://github.com/freeplane/freeplane/discussions/new?category=shared-mind-maps
