### ISSUE TITLE
Links to Release notes and Changelog?

### ISSUE THREAD

**Issue by LeeteqXV** [freeplane/freeplane#165]
Hi, I am looking for information that is normally found in Release Notes and/or Changelog(s), where can I find that? I have looked in both Sourceforge, here at Github and on the Freeplane.org wiki, but cannot spot any such docs.

I want to find out what is the main feature differences between version 1.6 and 1.8, since the former is the latest available in Ubuntu APT, and the latter is the one used in Snap installs.

I have seen the FreeplaneTutorial.mm that comes with v. 1.8, but it strangely stops at the changes in 1.7, does not say anything about new features in 1.8..?

**Comment by dpolivaev** [comment]
Check https://github.com/freeplane/freeplane/blob/1.8.x/freeplane/doc/history_en.txt . Probably it should be moved and renamed.

**Comment by reagle** [comment]
That doesn't look like it is updated.

**Comment by dpolivaev** [comment]
Obviously it is https://github.com/freeplane/freeplane/blob/1.10.x/freeplane/doc/history_en.txt now

**Comment by reagle** [comment]
Sorry.
