### ISSUE TITLE
New Freeplane.app (1.11.9) on MacOS Intel crashes at startup

### ISSUE THREAD

**Issue by pietvo** [freeplane/freeplane#1653]
**Describe the bug**
The newest version of Freeplane (1.11.9) on MacOS Ventura 13.6.3 on my Intel MacBook Pro does not start. 
**To Reproduce**
1. Download the DMG https://netcologne.dl.sourceforge.net/project/freeplane/freeplane%20stable/Freeplane-1.11.9-intel.dmg
2. Open the DMG
3. Copy Freeplane.app to /Applications
4. Doubleclick on the copied app /Applications/Freeplane.app
5. The app doesn't start
6. The error message is 
Error: Could not find or load main class org.freeplane.launcher.JavaLauncher
Caused by: java.lang.ClassNotFoundException: org.freeplane.launcher.JavaLauncher

**Expected behavior**
The app should start.

**Desktop (please complete the following information):**
 - MacOS Ventura 
 - Version 13.6.3
 - Java Version openjdk 15.0.8 2022-07-19 (embedded in the app)

**Additional context**

**Comment by dpolivaev** [comment]
Many thanks for letting me know, I am releasing an urgent fix release right now

**Comment by dpolivaev** [comment]
The fix is available as version 1.11.10
