### ISSUE TITLE
Cannot open second mindmap

### ISSUE THREAD

**Issue by gs-dk** [freeplane/freeplane#1656]
After opening a mindmap, I cannot open another one. When I want to open a second map, by clicking menu > file > open mindmap or by pressing ctrl+O, the file dialogue comes up, I choose a file and then does nothing. 
If I open a mindmap and create a new one, the new one appears in a new tab. If I then open another map, it jumps back to the first tab, not opening the map.

I used the Windows installer including JAVA. This behaviour has been seen after installing "Freeplane-Setup-with-Java-1.11.8.exe" and "Freeplane-Setup-with-Java-1.11.10.exe". 
I use Windows 10 pro, btw.

**Comment by gs-dk** [comment]
Reinstalling after uninstalling whilst choosing to delete resources and user data did not help as well. I only can start a second instance of Freeplane and work with that.

**Comment by dpolivaev** [comment]
I can not set the problem on my Windows 10  pro computer.

- Please try to open some files again, and after you see that it fails 
- execute Tools->Open user directory
- and attach zipped file auto.properties and zipped directory "logs" that you find in the opened explorer window to this bug report.

**Comment by gs-dk** [comment]
>     * and attach zipped file auto.properties and zipped directory "logs" that you find in the opened explorer window to this bug report.

[log.0.zip](https://github.com/freeplane/freeplane/files/14037468/log.0.zip)

Id did as you asked. There is barely anything in it, unfortunately. I've tried to open a file and to drag and drop it. The file is only mentioned once in the log.

**Comment by gs-dk** [comment]
After several days, continuously working with mindmaps, it works again. As of today. I've changed nothing. I apologize for the inconvenience, book this under "curiosity" and close this issue.
