### ISSUE TITLE
menu bar problems with versions 1.11.9 and 1.11.10

### ISSUE THREAD

**Issue by Olifair** [freeplane/freeplane#1657]
When freeplane is loading,  first the menu bar on top is properly organised (Freeplane loading1.jpg), but then instead of 2 rows, it ends up with 4 rows (Freeplane loading 3.jpg), all alogned to the left, and lots of free space to the right; This happened with then 1.11.9 and also now with the new 1.11.10 versions (both versions including JAVA), on a windows 11 computer.  I had to take pictures with my phone in burst mode to be able to show what is happening, also in between (Freeplane loading 2.jpg)

Any ideas of how to rearrange the menu bars ? 

![Freeplane loading 1](https://github.com/freeplane/freeplane/assets/6613705/51140a26-920a-41ba-8bce-2a709a2e0932)
![Freeplane loading 2](https://github.com/freeplane/freeplane/assets/6613705/1034b9d5-c1b5-4b0d-9162-6e8a92cfb38e)
![Freeplane loading 3](https://github.com/freeplane/freeplane/assets/6613705/0d221376-b9e3-4c97-9879-04b729056cc4)

**Comment by dpolivaev** [comment]
I guess that it happens because filter toolbar has got new buttons and they do not fit your screen any longer.
Try to decrease size of the toolbar icons in Preferences…->Appearance->Look and feel->Toolbar icon height

**Comment by Olifair** [comment]
thanks Dimitry for your fast reply, taking the icon height down from 16 to 15 did the trick :-)
