### ISSUE TITLE
Doesn't support latex footer mark  syntax X_{i}  

### ISSUE THREAD

**Issue by eromoe** [freeplane/freeplane#166]
Correct one :
![image](https://user-images.githubusercontent.com/3938751/86890683-447f3600-c130-11ea-8ea2-6c2d628422b3.png)

Freeplane doesn't render correctly: 
![image](https://user-images.githubusercontent.com/3938751/86890616-287b9480-c130-11ea-88fc-5c60a594940e.png)

**Comment by fnatter** [comment]
hi eromoe,

Freeplane puts you in text mode by default. Please wrap your formulas in $...$ or $$...$$, then it works.

Cheers and Best Regards,
Felix
