### ISSUE TITLE
Chinese input problem in macOS

### ISSUE THREAD

**Issue by ucSec** [freeplane/freeplane#167]
Hi!
I found there is a problem when I input Chinese characters in node.
For Chinese input, we need a kind of software call "InputMethod", I both tried the Apple's official inputmethod and SogouInputMethod, the results are the same.

When I tried to input the first character, the InputWindow appear but it's on the left bottom, after I  inputted the second character, the things became wired, the InputMethod still working but a copy of my first character was in front of it.

![](https://img.vim-cn.com/d2/22cdcd2e4611f8a7d3d674fa8f09d7fa1e7428.png)
![](https://img.vim-cn.com/03/7c036d7849dd77c4ed1f385be0e7c0a3bcc58a.png)

- system: macOS 10.15.5
- Freeplane version: 1.8.6
- Java version: 12.0.2
- That's what happened while I was running freeplane in the terminal: [here](https://paste.ubuntu.com/p/X3zYmDR2W2/).

**Comment by yangqiang** [comment]
You can press F2 to enter edit mode, then everything will be OK.
https://github.com/freeplane/freeplane/issues/136

**Comment by ucSec** [comment]
> You can press F2 to enter edit mode, then everything will be OK.

Thanks!
Now I can use it normally.

**Comment by iczrac** [comment]
any improvement now？

**Comment by yangqiang** [comment]
> any improvement now？

Upgrade to the latest sogou input method. https://pinyin.sogou.com/mac/

**Comment by uqix** [comment]
This config works for me:
Behavior - In-line node editor - Display **inline editor** for all **new** nodes: check

**Comment by yangqiang** [comment]
> This config works for me: Behavior - In-line node editor - Display **inline editor** for all **new** nodes: check

Cool! It works.
