### ISSUE TITLE
Script console - unwanted printouts

### ISSUE THREAD

**Issue by eegerly** [freeplane/freeplane#168]
Hi, 

When running node script in script editor, the console is flood with "Setting icons for node".

Possible root cause: System.out.println() call at
freeplane/freeplane/src/main/java/org/freeplane/features/icon/hierarchicalicons/AccumulatedIcons.java # line 64

Please, remove this line from the code. 

Thank you!

**Comment by dpolivaev** [comment]
Done, thanks
