### ISSUE TITLE
error button and sound without errors in log

### ISSUE THREAD

**Issue by Olifair** [freeplane/freeplane#1686]
I'm getting quite regularly an error sound (sort of Bing with an echo), and then on the botton of the Freeplane window, on the left side (right to the created dates of the actual node), I get a button with an exclamation mark in a triangle and "X errors" shown. 
When I click on this button, the file explorer opens in the "logs" directory. 
BUT : the "log.0" file is empty, shows the date from today, but a time older than the error signal
the log.1 file also shows today's date, but the time when I first opened Freeplane on that day. 
Below is what I find in the log.1 file (knowing that the error bing happened at 13:53, 

When the error-bing happens I'm usually not doing something species, so either the error bing and the button are spurious, or there is an actual error, but it is not written into the error log. 
Anybody any ideas ? 

Thanks
Oliver

STDOUT: Feb 09, 2024 9:30:27 AM org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.11.10; freeplane_xml_version = freeplane 1.11.5
git revision = 4f3abb16eb364b5e520b02ec6cb8dde52417e666 dpolivaev 2024-01-22T17:02:25Z
java_version = 15.0.10; os_name = Windows 11; os_version = 10.0
STDOUT: Feb 09, 2024 9:30:28 AM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date format yyyy-MM-dd
STDOUT: Feb 09, 2024 9:30:28 AM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date time format yyyy-MM-dd, hh:mm:ss
STDOUT: Installing shutdown hook.
STDOUT: Framework launched
STDOUT: Feb 09, 2024 9:30:30 AM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://4:1/org/freeplane/plugin/formula/defaults.properties
STDOUT: Feb 09, 2024 9:30:30 AM org.freeplane.core.util.LogUtils info
INFO: extending script's classpath by [C:\Users\obrendel\AppData\Roaming\Freeplane\1.11.x\compiledscripts, C:\Users\obrendel\AppData\Roaming\Freeplane\1.11.x\addons\freeplane-zotero\lib\freeplane-zotero.jar, C:\Users\obrendel\AppData\Roaming\Freeplane\1.11.x\lib]
STDOUT: Feb 09, 2024 9:30:30 AM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://9:1/org/freeplane/plugin/script/defaults.properties
STDOUT: Feb 09, 2024 9:30:30 AM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: Feb 09, 2024 9:30:30 AM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: Feb 09, 2024 9:30:32 AM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
STDOUT: Feb 09, 2024 9:30:39 AM org.freeplane.core.util.LogUtils info
INFO: menu items to execute: []
STDOUT: Shutdown hook invoked, stopping OSGi Framework.

**Comment by Olifair** [comment]
actually I get regular errors in the error file and these always start with : 
_STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.IndexOutOfBoundsException: Index: 12, Tab count: 12_
or
_STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.IndexOutOfBoundsException: Index: 11, Tab count: 11_

these are then followed by a long list of either 
_STDERR: at net.infonode.[...]_
or
_STDERR: at java.desktop[...]_

The errors occur randomly with anything I do, it can be just moving the FreePlane window, clicking on any menu, button, node etc ... 

Anyboy any ideas ?

**Comment by amariusz** [comment]
I've got the same kind of issues on 1.10.15. 

> STDERR: Exception in thread "AWT-EventQueue-0"
> STDERR: java.lang.IndexOutOfBoundsException: Index: 7, Tab count: 7

**Comment by amariusz** [comment]
And BTW, I can see speaker icon on FreePlane icon on task bar permanently after this issue. It looks like FreePlane is constatnly playing some audio / using sound device. This is little confusing.

**Comment by Olifair** [comment]
I don't quite see what you mean with speaker icon, but I don't think I observe this in windows 11. Perhaps you can add a screenshot to your post ?

**Comment by amariusz** [comment]
> Perhaps you can add a screenshot to your post ?

Maybe it's only on Linux. 
On the screenshot Firefox is currently playing a sound, and FreePlane is just pretening to ;)

![240220_143818_](https://github.com/freeplane/freeplane/assets/20703230/af355ada-493d-48aa-828f-9a66c8c0b04c)

Speaker icon appears with FreePlane sound notification about the error.

**Comment by Olifair** [comment]
I caught another one : 
STDERR: Exception in thread "AWT-EventQueue-0"
STDERR: java.lang.IndexOutOfBoundsException: Index: 7, Tab count: 7

and this time I wasn't even working in the FreePlane window, but in a different window. So it seems to be some internal process. 
And also, FreePlane was not showing the Tab7, but the Tab 10 ....

**Comment by i-plasm** [comment]
I get that same error every now and then: `STDERR: Exception in thread "AWT-EventQueue-0" ... STDERR: java.lang.IndexOutOfBoundsException: Index: 7, Tab count: 7)`. I suspect it may have to do with usage of scripts that interact with the Freeplane UI, but I'm not sure and I don't know how to reproduce it. To turn the sound off: `Preferences…->Environment->Plays sound on errors`.

**Comment by dpolivaev** [comment]
The error comes from the library used to arrange multiple mind maps. Unfortunately, it is not supported any longer, and all I could do would be try to replace it with another similar library.

**Comment by i-plasm** [comment]
> Unfortunately, it is not supported any longer, and all I could do would be try to replace it with another similar library.

@dpolivaev in my experience the error, when it has occurred, has never caused any issues in Freeplane or in scripts. Like I said, in my environment it occurs only now and then. I never saw that error on freeplane v1.8.8 or v1.9.12... but definitely on v.1.11.x. My workaround is just to disable the sound : ` Preferences…->Environment->Plays sound on errors.`.

**Comment by dpolivaev** [comment]
In preview 1.11.11_04 I disabled error reports if they come from this code location.

**Comment by Olifair** [comment]
Great, thanks. But I'm a bit confused : if there is code in FreePlane which is not working, and creating an error, then this must surely mean that something is then also not functioning, which is perhaps not visible uptfront but might cumulate in the background ?

**Comment by dpolivaev** [comment]
For me, it looks like there is a bug in the library used for arranging mind map views. I can not fix it easily enough. And I do not think it is likely to have cumulative effects or cause data loss.

**Comment by i-plasm** [comment]
Dear @dpolivaev  , I found that the same bug has been reported before over the infonode sourceforge https://sourceforge.net/p/infonode/bugs/32/. The bug is located in the `ComponentCache` class and ebourg apparently fixed it in this commit: https://github.com/ebourg/infonode/commit/e14d433c1c2d467913bf5f069904fbb292be0e04 . I share Olifair concerns that silencing error reporting from the infonode library could lead us to ignore any potentially serious bug. Having error logging is valuable for us who make and use scripts that interact with the Freeplane GUI in a non-trivial way. I hope this will fix it!

**Comment by dpolivaev** [comment]
@i-plasm I applied the fix you found in preview 1.11.11_05 and reactivated bug reporting completely

**Comment by i-plasm** [comment]
> I applied the fix you found in preview 1.11.11_05 and reactivated bug reporting completely

Great! Many thanks
