### ISSUE TITLE
Navigate > Goto Node does not function by non standard node IDs

### ISSUE THREAD

**Issue by medienmeister** [freeplane/freeplane#1704]
**Describe the bug**
Navigate > Goto Node does not function in Apple version (presumably on imported files)

**To Reproduce**
1. (Copy the ID of a node; after that select a random different node)
2. Invoke Navigate > Goto Node an paste the just copied ID
3. (after clicking OK): Nothing happens

**Expected behavior**
I expected the targeted Node to be selected

**Mind map files**
I cannot provide a file. But: Navigating nodes works in new files or on nodes, that I create in Freeplane.
My map was imported from another mind managing software (the deseased iThoughts) and I discovered that the format of the IDs is different for imported maps and nodes in them:
Example ID of an imported node: 9DED47CC-28C6-412E-B312-FDA67753C549
Example of an ID, freshly created in Freeplane: ID_1714596347

Freeplane does not seem to recognize those malformed IDs. Maybe it could and reset or repair such IDs?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 14.2.1]
 - Freeplane Version [1.11.11]
 - Java Version: bundled with the Freeplane binary (21.0.1)

**Additional context**

**Comment by euu2021** [comment]
Edo mentioned here that if the id is deleted in the file, it is recreated in the next map open: https://github.com/freeplane/freeplane/issues/939#issuecomment-1387686150

I did a small test here, and it seems to work. So, the idea is to use a regex to delete the ids. But, I'm not sure how safe it is.

**Comment by dpolivaev** [comment]
It is not safe because it would destroy all connectors AKA local links.

**Comment by euu2021** [comment]
Ok, I maybe there is a solution:

If you append "ID_" to the ID 9DED47CC-28C6-412E-B312-FDA67753C549, the GoTo Node works.
So, the idea is to use a regex to append "ID_" to those imported IDs.

**Comment by dpolivaev** [comment]
If you wait until the weekend I can check why ID_ is important and if I can relax it.

**Comment by euu2021** [comment]
> If you wait until the weekend I can check why ID_ is important and if I can relax it.

If there is no ID_, then the text is considered an "at(" path. https://github.com/freeplane/freeplane/blob/11d334b993fda70f847d2824b8c60b199edfe4d6/freeplane/src/main/java/org/freeplane/features/map/GotoNodeAction.java#L64-L67

**Comment by dpolivaev** [comment]
Do you think it makes sense? The logic could be changed because it is an action, not an API part.
I could check if the string is used as ID and then use it as ID.

**Comment by euu2021** [comment]
> I could check if the string is used as ID and then use it as ID.

I think this would solve the problem, and I don't see negative side effects.

**Comment by euu2021** [comment]
For future reference:

It's possible to change the node ID by using:

```
package org.freeplane.features.map;

import org.freeplane.features.mode.Controller;

final Controller controller = Controller.getCurrentController();
final IMapSelection selection = controller.getSelection();
final NodeModel node = selection.getSelected();

node.id = "new ID"
```

And this approach automatically set the new ID to the connectors, so they are kept.

**Comment by dpolivaev** [comment]
preview 1.11.11_03

**Comment by medienmeister** [comment]
Thank you for the time and the effort. Looking forward to try the preview.

A remark and a reminder from a user's perspective (with little programming knowledge):
If I copy a selected branch and paste it (making a copy), the copied nodes seem to get proper "Freeplane-IDs". So: select all, copy, delete and paste again – seems to give me "good" IDs and a somewhat clean map (of course it would brake existing links – but it might be helpful when importing a map from another app).

Again: thank you for the time and the effort. Freeplane is growing on me every day – and maybe even an end user can help making it even more stable.

**Comment by euu2021** [comment]
> Thank you for the time and the effort. Looking forward to try the preview.
> 
> A remark and a reminder from a user's perspective (with little programming knowledge): If I copy a selected branch and paste it (making a copy), the copied nodes seem to get proper "Freeplane-IDs". So: select all, copy, delete and paste again – seems to give me "good" IDs and a somewhat clean map (of course it would brake existing links – but it might be helpful when importing a map from another app).
> 
> Again: thank you for the time and the effort. Freeplane is growing on me every day – and maybe even an end user can help making it even more stable.

If possible, please create a thread telling if there are any relevant features of iThoughts that are missing on Freeplane. Some features can be recreated in Freeplane using scripts and add-ons. I think that it will be useful, because, now that iThoughts was discontinued, many users will come to Freeplane, as an alternative.

**Comment by dpolivaev** [comment]
> Thank you for the time and the effort. Looking forward to try the preview.

Available since yesterday in https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

**Comment by euu2021** [comment]
For future reference:
By chance, I found a macmarrum's script that regenerates node IDs: https://github.com/macmarrum/freeplane-scripting/blob/main/src/scripts/regenerateNodeIDs.groovy
