### ISSUE TITLE
clone node problem

### ISSUE THREAD

**Issue by cobblepot1** [freeplane/freeplane#1738]
**Describe the bug**
I cannot create a clone node

**To Reproduce**

1. select node
2. copy node
3. click Edit / Paste Clone
4. nothing is pasted

**Expected behavior**

Expect clone node to be pasted

**Desktop (please complete the following information):**

Win 10, x64, Java
Freeplane 1.11.11
Java 8 v 401

**Comment by dpolivaev** [comment]
Please upload a zipped mind map file and describe which node you want to clone and where you are trying to paste it.

**Comment by jfrome1** [comment]
On testing, I was able to clone nodes. The problem was that it was not clear to me that I need to select a node other than the source node before pasting it. Am I right that can I not paste the clone as a child of the source node? But I can paste a 2nd clone as a child of the 1st clone node? If yes, is there a reason that the user cannot pasted the clone as the child of the source node?

**Comment by cobblepot1** [comment]
On testing, I was able to clone nodes. The problem was that it was not clear to me that I need to select a node other than the source node before pasting it. Am I right that can I not paste the clone as a child of the source node? But I can paste a 2nd clone as a child of the 1st clone node? If yes, is there a reason that the user cannot pasted the clone as the child of the source node?

**Comment by macmarrum** [comment]
@cobblepot1 

The thing about clones is that they can represent a single node or a whole branch.

You probably already know the difference between `Ctrl+C` vs `Ctrl+Shift+C`:

* `Edit->Copy->Copy node (branch) (Ctrl+C)`
* `Edit->Copy->Copy node (single) (Ctrl+Shift+C)`

When a clone is pasted (`Ctrl+D`), its "scope" is based on what was copied. In case of a branch, it makes little sense to place the clone as a child of itself. It would create and endless loop. In case of a single node, the clone can be a child of itself.

Even if Freeplane disallows pasting a clone within its own branch, you can paste a single-node clone into a different branch and then move it (e.g. to become a child of itself).

**Comment by dpolivaev** [comment]
@macmarrum thanks for the explanation and for letting me know it does not work for single nodes.
I have removed this limitation for single nodes now.

**Comment by dpolivaev** [comment]
@cobblepot1 You can not past the whole cloned subtree under the same node because it would mean endless recursion (the node would be a descendant of itself), but when you copy nodes without their subtrees there is no reason for the limitation.
