### ISSUE TITLE
Flickering nodes on hover

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1744]
Since some days ago, I'm getting a flickering on node hover:

![javaw_zUXHgnrFen](https://github.com/freeplane/freeplane/assets/77707706/9210d975-8f6b-4f44-b645-4d3655988664)

When quickly hovering over many nodes, it gets really annoying.

There is some relation to zoom level. In the example above, the zoom level is at 96%.

Example map and autoproperties: 
[Testjumps.zip](https://github.com/freeplane/freeplane/files/14667426/Testjumps.zip)

**Comment by dpolivaev** [comment]
It looks like selection suddenly changes to node bbb when you are hovering over node ccc. I do not see it at least on my mac.

**Comment by euu2021** [comment]
I don't know if it helps, but I noticed that the problem only happens when the zoom level is below 100%. There is a very consistent correlation with the zoom level.

**Comment by dpolivaev** [comment]
I can't reproduce the issue on Windows either.

**Comment by euu2021** [comment]
This problem disappeared some time ago. I don't see it anymore.
