### ISSUE TITLE
Freeplane v1.11.11 upgradw - java error

### ISSUE THREAD

**Issue by OpaYoda40** [freeplane/freeplane#1758]
**Describe the bug**
prompted by update tip when using v 1.1.10 to download update to v 1.11.11.  Using v 1.11.10 works fine with dayily backups.  But when trying to opem latest back up & previous backups now all fail to load without errors with either v 1.11.10 or v 1.11.11 of the Freeplane-intel ap on MacIOS.  
  --=  errror log (consistent with either version) 
STDOUT: Mar 26, 2024 5:02:31 PM org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.11.11; freeplane_xml_version = freeplane 1.11.5
git revision = 0423d9e8cc362354ff5d7da3eaba272f8746e314 dpolivaev 2024-03-01T14:40:43Z
java_version = 15.0.8; os_name = Mac OS X; os_version = 10.15.7
STDOUT: Mar 26, 2024 5:02:32 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date format M/d/yy
STDOUT: Mar 26, 2024 5:02:32 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date time format M/d/yy, h:mm a
STDOUT: Installing shutdown hook.
STDOUT: Framework launched
STDOUT: Mar 26, 2024 5:02:36 PM org.freeplane.core.util.LogUtils info
INFO: extending script's classpath by [/Users/jrp/.freeplane/1.11.x/compiledscripts, /Users/jrp/.freeplane/1.11.x/lib]
STDOUT: Mar 26, 2024 5:02:36 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://2:1/org/freeplane/plugin/script/defaults.properties
STDOUT: Mar 26, 2024 5:02:36 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: Mar 26, 2024 5:02:36 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
STDOUT: Mar 26, 2024 5:02:36 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://8:1/org/freeplane/plugin/formula/defaults.properties
STDERR: Mar 26, 2024 5:02:36 PM org.freeplane.core.util.LogUtils severe
SEVERE: can not load icon '/images/formula.png'
STDOUT: Mar 26, 2024 5:02:38 PM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
STDOUT: Mar 26, 2024 5:03:05 PM org.freeplane.core.util.LogUtils info
INFO: menu items to execute: []

**Desktop (please complete the following information):**
 - OS: MacOS CATALINA v10.15.7  on MacBook Pro (13-inch, Mid 2012
 - Java Version  8 update 401 (current for Macbook)

**Additional context**
  --- this is a recurring problem with updates;  JAVA issues need to be tracked down & fixed every time

**Comment by HaaiHenkie** [comment]
Hello Opa Yoda,

In my language opa means grandpa. Are you in any way related to baby Yoda Grogu?

I am not sure what you mean by daily backups. Do you mean the automatic backups from which you can recover unsaved changes? I do not see any errors in the logging you provided.

In the last days I also experienced problems upgrading to v1.11.11 and downgrading back tot v1.11.10. Maybe my experiences can be of use to you. After upgrading I experienced a problem with running an addon, see #1743. When downgrading to v1.11.10 I experienced a problem with starting up Freeplane, see #1711. In both issues I have added a solution that does not require to delete the complete content of your Freeplane user directory.

**Comment by OpaYoda40** [comment]
Henk, vielen Dank für ihre Antwort. 

  --- When catching your comment, I was in process of preparing for Apple Time Machine to recover back to v1.11.10 myself.  

  --- Due to previous experience going back more than a decade, I was waiting to update FreePlane versions for when I thought I could afford to delay working out the update issues pretty much expected.  
 BUT this time I didn't make enough time to do the upgrade in one of my alternate lab systems ( MS; other Nix family OS, et al) [usually in VM environments] }.

  --- I normally refrain from Apple Time Machine & FreePlane b\automatic backups.  They interrupt too much with good work flow and waste resources like time, storage, and bandwidth.  I chose long ago to simply to backups on demand, usually when finished with a subtask or edit.  Also as back up before attempting recovery (from duplicate copies of previous back up).  LESSON LEARENED from "Hard Knox University" -- (more expensive tuition than "School of Hard Knox".)  

 ---  The "**Opa Yoda**" moniker refers to my acting as a Yoda Grand Master for Meine Enkel,  Urenkel, & other ypung folk as my **Padawan** to gain wisdom & sills needed in adult life.

**Comment by dpolivaev** [comment]
The error message indicates that some of your add-ons uses internal Freeplane resources that have been removed.
You can find all older Freeplane releases at https://sourceforge.net/projects/freeplane/files/freeplane%20stable/archive/, so there is no need to use the time machine.
