### ISSUE TITLE
UTF-8 scripts encoding problem

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1764]
Consider a script with this content: `node.text = "📌"`

When I open `Tools->Edit script…` , create new script with this content, and apply to an empty node, the result is, as expected:
![image](https://github.com/freeplane/freeplane/assets/77707706/5c2691c7-b989-4ecc-934f-440e252511f9)

When I save a groovy file, encoded in UTF-8, and apply it using `Tools->Scripts->Test UTF`, the result is:
![image](https://github.com/freeplane/freeplane/assets/77707706/92b37a88-335e-40b1-aff9-72e4ea43fe1b)

The groovy file used in the example:

[testUTF.zip](https://github.com/freeplane/freeplane/files/14796480/testUTF.zip)

Maybe, related to: https://github.com/freeplane/freeplane/issues/98

**Comment by dpolivaev** [comment]
I am going to enforce reading files using UTF-8 encoding following Java decision to change their default to UTF-8 on all systems. Because can be a breaking change for some users, I am going to introduce it only in Freeplane 1.12.x. And I am not going to have it configurable.

For the moment you can enforce using UTF-8 by adding -Dfile.encoding=UTF-8 to freeplane.bat, freeplane.l4j.ini and freeplaneConsole.l4j.ini or by using Java 18 or later for running Freeplane.

What do you think?

**Comment by euu2021** [comment]
> I am going to enforce reading files using UTF-8 encoding following Java decision to change their default to UTF-8 on all systems. Because can be a breaking change for some users, I am going to introduce it only in Freeplane 1.12.x. And I am not going to have it configurable.
> 
> For the moment you can enforce using UTF-8 by adding -Dfile.encoding=UTF-8 to freeplane.bat, freeplane.l4j.ini and freeplaneConsole.l4j.ini or by using Java 18 or later for running Freeplane.
> 
> What do you think?

It makes sense.

**Comment by euu2021** [comment]
> I am going to enforce reading files using UTF-8 encoding following Java decision to change their default to UTF-8 on all systems. Because can be a breaking change for some users, I am going to introduce it only in Freeplane 1.12.x. And I am not going to have it configurable.

Did this happen, already? I'm still getting the same problem, on Freeplane-Setup-1.12.8-pre01

**Comment by euu2021** [comment]
It's working, now.

**Comment by gamepad-coder** [comment]
+1 working now

- I was on `1.12.something` and emojis were not working.
- Updated to `1.12.11` and now emojis and unicode render perfectly!

I've wanted emoji support in FreeMind for like a decade, this is amazing.

Thanks **so much** for all the work on this project ✨
