### ISSUE TITLE
Inherited style for first child node in Freeplane 1.11.11

### ISSUE THREAD

**Issue by jockster74** [freeplane/freeplane#1774]
**Change to how styles are inherited?**
In Freeplane 1.11.11, when I apply a style to a node, that style is inherited by the first child node under it, recursively.

**To Reproduce**
1. Create a new empty mindmap.
2. Insert a child node under the central node. It receives the same style as its parent.
3. Insert a sibling node (to the node created in the previous step), it does not inherit the style of the parent.
4. Insert a child node to the node created in step 2. It inherits the style of the parent node.

See the animated GIF
![2024-04-07_freeplane_inherited_styles](https://github.com/freeplane/freeplane/assets/5231687/304317e6-7c09-4857-948b-6e70f664a9d3)

**Expected behavior**
The expected behavior as seen in previous versions of Freeplane is that the parent's style is not inherited by child nodes.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 23H2
 - Java Version: 15.0.10

**Comment by euu2021** [comment]
This:

Format->Preserve format for new child nodes

Format->Preserve format for new sibling nodes

**Comment by jockster74** [comment]
Thank you! Learnt something new. Closing this ticket.
