### ISSUE TITLE
Prezi-like presentation

### ISSUE THREAD

**Issue by AtomicNess123** [freeplane/freeplane#178]
I know RoAn Presentation seems to be obsolete in current FreePlane versions. Is there any addon/option to visualize slides in FreePlane in Prezi-style (navigating and zooming in and out of the focus)? That'd be great. Thanks.

**Comment by dpolivaev** [comment]
Freeplane has its own presentation support available in the tool panel. Check it out.

**Comment by AtomicNess123** [comment]
Thanks. This is what I see in the tool panel: Where exactly is this presentation support? Thanks!
![image](https://user-images.githubusercontent.com/47029233/103376327-07936b00-4ae5-11eb-9c66-02094e586a35.png)

**Comment by dpolivaev** [comment]
![Selection_018](https://user-images.githubusercontent.com/1558052/103377729-7e7a3500-4ae0-11eb-935b-4c426208acee.png)
Here

**Comment by AtomicNess123** [comment]
Thank you. I have Freeplane 1.8.10, and I can't understand how to find that in the menu. Is the Tool panel the tool section in the menu? [5 minutes later]: I found it! Will test this now. :)

**Comment by AtomicNess123** [comment]
I actually now went about trying this, but it's not very intuitive how to make slides. Is there any tutorial? Thanks so much for your time.

**Comment by dpolivaev** [comment]
You could ask your questions in our community forum at https://sourceforge.net/p/freeplane/discussion/758437/ It has been helpful in many cases.
