### ISSUE TITLE
1.12.1_02 regression: tags cannot be deleted

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1786]
Deleting the text of the tag makes it be replaced by an empty tag:
![tags](https://github.com/freeplane/freeplane/assets/77707706/42724e31-e2dc-4e20-81cb-7f1e56a078ad)

**Comment by dpolivaev** [comment]
Yes, to delete the tag you can use delete or backspace button not modifying the text in the text field

**Comment by euu2021** [comment]
I see. Thanks
