### ISSUE TITLE
How to narrow down the visible nodes with a predefined 'filter set'

### ISSUE THREAD

**Issue by dpolivaev** [freeplane/freeplane#1800]
### Discussed in https://github.com/freeplane/freeplane/discussions/1799

<div type='discussions-op-text'>

<sup>Originally posted by **theelectricsoul** April 24, 2024</sup>
Hello

# Scenario

1. I have a bunch of nodes with different styles. 
2. I filter the nodes that have the style 'task' only. 
3. I activate the function 'Applied to filtered nodes', because I want to further narrow down the nodes by adding more filter criteria.
![image](https://github.com/freeplane/freeplane/assets/10260832/8a94a27e-0aae-4529-8e20-cf8333a30b55)
4. I pick a pre-definded filter to hopefully narrow down the results.
![image](https://github.com/freeplane/freeplane/assets/10260832/b20ca312-2b6b-4e2f-b9ca-d9384c1ed1c0)

# Result
Picking a predefined filter ignores the currently filtered nodes. Freeplane simply applies the pre-defined filter to all nodes on the map.

# Question
Is there a way to use pre-defined filters to further narrow down the filter?

*I know that I could simply create a pre-defined filter that combines all my needed filter criteria, however I do not want to create a filter for every needed filter combination that I might use.*</div>

**Comment by theelectricsoul** [comment]
@dpolivaev 
I got it. Please see the video

https://github.com/freeplane/freeplane/assets/10260832/806a1f73-4236-4155-bdaa-ae8189f5361d

**Comment by theelectricsoul** [comment]
@dpolivaev 
Here is the map
[New Mindmap.zip](https://github.com/freeplane/freeplane/files/15095850/New.Mindmap.zip)

**Comment by theelectricsoul** [comment]
This can be closed....   sry
