### ISSUE TITLE
Tags: drag and drop of tags directly in the node

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1804]
> Now it supports copy, cut and, and paste, drag and drop

This is nice to make bulk operations and distribute tags. Now, it would be even faster if I could do the drag and drop of tags directly in the node, without having to open the tag editor of each node:

![image](https://github.com/freeplane/freeplane/assets/77707706/372db8fa-d77d-4112-a64e-b15076ef2515)

This operation of copying or moving tags between close nodes is relevant in daily like.

_Originally posted by @euu2021 in https://github.com/freeplane/freeplane/discussions/1652#discussioncomment-9245393_

**Comment by euu2021** [comment]
For future reference, in case the feature is not possible to be implemented: dropping in the node with the Ctrl modifier activated creates new nodes with the text of the tag. So, it may be possible to come up with a clever script that has a listener that transforms those new nodes in tags of the target node.

**Comment by euu2021** [comment]
An alternative, that may be easier to implement: a button "Insert selected tags in selected node", inside the Tag Editor.

**Comment by dpolivaev** [comment]
You already can drag and drop tags between different opened tag editors. And you can click on "alt" to copy.

**Comment by dpolivaev** [comment]
You can also copy and paste between tag editors.

**Comment by euu2021** [comment]
I see. The operation that I have in mind is to distribute some tags over some nodes. 

For example, starting with this situation, I want to copy tags 111, 333 and 555 to nodes ccc, ddd and fff:

![image](https://github.com/freeplane/freeplane/assets/77707706/2b998970-b4cf-4036-95e0-fc361279f12d)

It seems that the most convenient way would be to open the tag editor in node bbb, select the tags, select the target nodes, and "insert tags in selected nodes":

![image](https://github.com/freeplane/freeplane/assets/77707706/668e55c5-8595-4120-9798-7823fc9884f9)

**Comment by dpolivaev** [comment]
I could implement it.
Could you explain how you want to use it?

**Comment by euu2021** [comment]
> Could you explain how you want to use it?

A common situation when using tags is: 
- I have a list of 50 itens (nodes) in front of me. The itens can be, for example, tasks
- I want to do some tagging of the itens. For example, setting the tags "Urgent" and "This week" to urgent tasks
- I select an item that already has those 2 tags, and open the tag editor
- select the 2 tags
- select some nodes
- add the tags to the selected nodes

So, it's useful for bulk tagging operations.

**Comment by macmarrum** [comment]
I'd go a step further: it would be great to not only add tags but also to remove them to/from a selection of nodes.

In other words, it would be useful for me if Edit Tags affected all the nodes which were selected when Edit Tags was invoked.

This brings to my mind the topics of duplication/uniqueness and partiality/scope.

1. Uniqueness (duplication)
  - It would be useful for me if Freeplane could limit Node's Tags to a unique set
  - Example 1
    - Given Node A with Tags [x, y, z]
    - When (another) Tag x is added
    - Then the set of Tags in Node A remains unchanged, i.e. [x, y, z]
2. Scope (partiality)
  - It would be useful for me if Edit Tags could provide indication
    - about Tags present only in a subset of selected Nodes (partially present)
    - about Tags present in all selected Nodes (fully present)
    - about Tags absent in all selected Nodes (not present yet, i.e. additions to be OK-ed)
  - Example 2
    - Given Node A with Tags [x, y, z] and Node B with Tags [x, y]
    - When Edit Tags is invoked on both Nodes
    - Then Tags x, y are indicated as fully applied and Tag z as partially applied
  - It would be useful for me to change the scope in Edit Tags from full to none and from partial to full or to none
  - Example 3
    - Given Edit Tags invoked on Nodes A with Tags [x, y, z] and B with Tags [x, y], and in Edit Tags, Tags x, y indicated as fully applied and Tag z as partially applied
    - When the indicator for Tag z is changed from partial to all and Edit Tags is OK-ed
    - Then both Nodes A and B have Tags [x, y, z]

**Comment by dpolivaev** [comment]
I currently work on a Tag Category Editor. It allows creation of user specific tags organized in categories and save them in a file in the user configuration directory. When defined they can be used for creating menus for adding tags to nodes.

<img width="271" alt="tagCategories" src="https://github.com/freeplane/freeplane/assets/1558052/64788206-ac12-4ed8-b1c5-6bf6002d6c6a">

<img width="271" alt="tags" src="https://github.com/freeplane/freeplane/assets/1558052/41f11074-6c6b-4a62-b70c-9bffd9e5039e">

**Comment by euu2021** [comment]
Now, there is a `Insert into selected nodes`, which fulfills the request, so I think it can be closed.
