### ISSUE TITLE
Node and Connector Filter

### ISSUE THREAD

**Issue by dpolivaev** [freeplane/freeplane#1806]
When I think about filtering related to Connectors, I come up with 3 main cases:
1. Node Filter
2. Connector Filter
3. Node and Connector Filter

The following examples present the cases:

![2024-04-27_18,57,18](https://github.com/freeplane/freeplane/assets/7197131/e3104db3-c556-43cf-9fc1-cc961915ea3b)

![2024-04-27_18,58,51](https://github.com/freeplane/freeplane/assets/7197131/aa0add2f-3cff-4653-9dc9-9dc8cab358cb)

![2024-04-27_19,00,49](https://github.com/freeplane/freeplane/assets/7197131/c1d86616-f392-4f4d-a5ac-d466796b7107)

![2024-04-27_19,02,24](https://github.com/freeplane/freeplane/assets/7197131/6ffd3047-2ba3-4b81-81f5-01dd87e8180d)

Freeplane 1.11.x supports case 1 – Node Filter (based on Connector properties).
Freeplane 1.12.1-alpha-3 additionally supports case 2 – Connector Filter (based on Node or Connector properties).

I think it would be great for Freeplane to also support case 3.

_Originally posted by @macmarrum in https://github.com/freeplane/freeplane/discussions/1801#discussioncomment-9246779_

**Comment by dpolivaev** [comment]
Implemented in preview 1.12.1_04

<img width="814" alt="filterModes" src="https://github.com/freeplane/freeplane/assets/1558052/d7e4ae32-4084-4d27-80bb-c56c6f3d0b6c">

**Comment by macmarrum** [comment]
Marvelous :1st_place_medal:
