### ISSUE TITLE
can not create map inside transaction

### ISSUE THREAD

**Issue by farvardin** [freeplane/freeplane#181]
Sometimes when I'm using freeplane (both stable and preview version), it happens I can no longer load a new map: I get a "java.lang.illegalStateException: can not create map inside transaction".

![image](https://user-images.githubusercontent.com/477243/103169997-fcb8ac00-4840-11eb-8f8d-e72fb6361fbd.png)

So I have to close freeplane and restart it again.

java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

(I got this too with java-8-openjdk)

**Comment by farvardin** [comment]
It looks like it's crashing at random, but I wonder if it's not happening first when loading a template from the template folder.

**Comment by dpolivaev** [comment]
This message can come if undo handler of the currently opened map is in a corrupt state.
It would be helpful if you could understand which operations you did with this map before.

Undo handler is internally attached to the map. What happens if you save and reload the map when you see this behavioud, can you create / open other maps afterwards?

**Comment by farvardin** [comment]
I don't remember. I can't make it crash any longer at the moment. The problem is also when it reaches this unstable state, I often can't save maps correctly (I'll need to open a new issue for this problem), for example I think if I have 2 open documents, when I want to save one, the * remains on my current document, and it looks like it's the other document which is saved. I'll post more if I encounted this again (it happened 4 or 5 times)

**Comment by dpolivaev** [comment]
Hopefully fixed

**Comment by dpolivaev** [comment]
The bug occurred if some script changed the current map.
Does it match your observations?
