### ISSUE TITLE
create api key does not update freeplane

### ISSUE THREAD

**Issue by tigadad** [freeplane/freeplane#1811]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Screenshots**

**Desktop (please complete the following information):**
 - Java Version

**Additional context**

**Comment by tigadad** [comment]
The OpenAI API installation says to "copy" the newly generated key then go to Freeplane Add-ons and paste the key.

There is nowhere to paste the key.

**Comment by tigadad** [comment]
I am om on Lubuntu 22.04.4 LTS using Freeplane 1-11-13.

**Comment by dpolivaev** [comment]
You can ask your question in the discussion forum if you still need a solution
