### ISSUE TITLE
location of arrow links randomly change in mm file

### ISSUE THREAD

**Issue by nnako** [freeplane/freeplane#1822]
**bug description**
On each save, the XML elements of type `arrowlink` below a specific `node` element within a mindmap file (type `mm`) seem to randomly change their order. Even when there was no change made within the node itself, and no change to the arrowlinks of that node. When trying to evaluate the mm file programmatically, there appear to be loads of changes even though there would not be a single "real" change in content.

**reproduction**
1. open any mindmap and add some arrow links between one and multiple other nodes
2. save that mindmap e.g. with a name "test1.mm"
3. fold and unfold the parent of that node containing the arrow links (just to create some non-content change)
4. save the mindmap with a different name "test2.mm"
5. now get yourself a simple text editor (with left- and right-side view) and open both mindmaps "test1.mm" and "test2.mm"
6. compare the two mindmaps

**expected behavior**
When no change was made to the mindmap, I would expect the mindmap to be saved always showing the identical XML structure within the mm file. Is there a certain concept which is followed when adding the arrowlinks to the XML? Why is its sequence not constant?

**Mind map files**
A mindmap could look like this:

![respective_mindmap](https://github.com/freeplane/freeplane/assets/5845602/6a8cb92e-64cb-4228-8da2-10ba8b833a84)

**screenshot**
An example will look like this (see where the different arrowlink elements moved):

![excerpt_from_mm_file](https://github.com/freeplane/freeplane/assets/5845602/40ea11ed-ac08-40de-ba8d-fe5cd0fea179)

**desktop**
 - OS: `Windows`
 - OS Version: `10`
 - Java Version: `15.0.10`

**Comment by dpolivaev** [comment]
I think it is fixed
