### ISSUE TITLE
Tags: `Remove from selected nodes`

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1826]
FP now has the option `Insert into selected nodes`, which seems to work perfectly.

For the same reason that `Insert into selected nodes` is useful (see https://github.com/freeplane/freeplane/issues/1804#issuecomment-2080966821), also `Remove from selected nodes` would also be useful. In other words, I would like to quickly remove a certain tag from several nodes.

Thanks,

**Comment by euu2021** [comment]
Bumping this up, because it's essential when mass editing tags. Today, I was in a situation where I needed it.

**Comment by dpolivaev** [comment]
Preview 1.12.2_09

**Comment by euu2021** [comment]
Thanks!

I see that the feature is available at the Tag Category Manager, but I would like to use is also in the Edit Node Tags window, please.
