### ISSUE TITLE
Tag layout improvements

### ISSUE THREAD

**Issue by dpolivaev** [freeplane/freeplane#1830]
Greetings - Now on this morning’s Preview 10. Thank you Dimitry!! These new capabilities are absolutely terrific and I’m already making great use of them. With a large map/database of over 11,000 nodes, the ability to sort and filter in a Listview makes the collection manageable, and these colorful Tags are the easiest way to group distant but related nodes together with visual clarity. 

I never want to ask for too much, but you did mention that enhancement requests are best illustrated with a use case, so here’s mine. 

Quite a few of my notes and links relate to Economics. I’ll capture an article, then use CKEditor and an AutoHotkey script to transform it into the cleanest HTML, and generate a branch node to import title and link into the main Freeplane map, where it looks something like this:

![SampleNodeWithTags](https://github.com/freeplane/freeplane/assets/68667676/4109314e-b734-4d30-b093-a7948204ae55)

As you can see, the map is all in gray; I’ve set most everything on the PC to look this way, using Windows’ Contrast Themes, to combat eye strain. And nodes are horizontal; I’m using the layout that simulates Outline View.

To fit this node view, a few enhancements to request, mainly cosmetic.

- The display of tags along the left column best fits tightly wrapped and deeply indented nodes. Any chance for those of us using more horizontal layouts to be able to display our tags as sausage links beneath the node text? It’d make for major space saving.  Hope it’s not too late to ask. 
- With the objective of fighting eye strain, I’d really appreciate the ability to control text and edge colors for these tags. Even if Freeplane generates text and edge colors from the background color,  could we perhaps store those colors in the map with their corresponding tagcolor so they could be tweaked with a script?  Long hours in front of the screen over many years have me favoring muted, low-contrast colors. And I’d have chosen black over white text and edges for the tags shown above. 
- A small UI quirk when changing colors, most likely to be noticed in left-aligned maps like mine. The Edit Tags window aligns with the node’s left edge, and if that happens to be off the screen, it’ll be forced into view, so that both have a minimum X coordinate of roughly 15. However, if we want to change a tag’s colors, the color picker control aligns with the *right* edge of the Edit Tags window. So, for me, the color picker always starts out partly off the screen. I’d request a similar X-minimum for it. 

BTW I also use AutoHotkey to generate a rather crude Listview of my own, to navigate the map and to generate views from it. No XML library, just parsing the mindmap as a long string, which takes about ten seconds to read in and split out. Double clicking runs the NodeURI, of course. 

![TagsListview](https://github.com/freeplane/freeplane/assets/68667676/f2b219d4-2dac-4577-90db-eaac952388f3)

Four Attribute fields are shown as columns, inspiring the question:

- With this round of improvements to Freeplane’s own Search & Replace Listview, any possibility of adding the map’s Attribute fields to it?

Thanks always!!

Jerome

_Originally posted by @JJSlote in https://github.com/freeplane/freeplane/discussions/1652#discussioncomment-9424141_

**Comment by dpolivaev** [comment]
Preview 1.12.1_11
View->View settings->Show Tags->Beside Nodes / Under Nodes / Never

**Comment by dpolivaev** [comment]
If you have any other issue, please submit it separately.
I am not able to see more than one issue in one thread.

**Comment by JJSlote** [comment]
Thanks, works beautifully. 
(Yes, related issue up in moments.) 
Rgds - JJS
