### ISSUE TITLE
& char in a pasted HTML link gets HTML encoded in the node's URL link

### ISSUE THREAD

**Issue by walmar** [freeplane/freeplane#1832]
**Describe the bug**
When copying a HTML link like [Freeplane: Revision history - Wikipedia](https://en.wikipedia.org/w/index.php?title=Freeplane&action=history) with a web browser such as Mozilla Firefox 125.0.3 and pasting it into a Freeplane mindmap, the ``&`` character in the node's URL hyperlink will automatically become [HTML encoded](https://en.wikipedia.org/wiki/Character_encodings_in_HTML#HTML_character_references) to ``&amp;``.

When following the unexpected encoded hyperlink with a web browser such as Mozilla Firefox 125.0.3, the [separated query parameter](https://en.wikipedia.org/wiki/Query_string#Structure) is not recognized.

**To Reproduce**
<details><summary>Follow the steps described above.</summary>

1. Select the full text of [Freeplane: Revision history - Wikipedia](https://en.wikipedia.org/w/index.php?title=Freeplane&action=history) and press Ctrl + C keys.
2. Select the mindmap and press Ctrl + V keys.

</details>

**Expected behavior**
The & character in a node's URL hyperlink is not automatically HTML encoded, similar to how HTML links are processed in other programs such as Apache OpenOffice 4.1.15 Writer.

**Mind map files**
x

**Screenshots**
x

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Freeplane Version: 1.11.13
 - Java Version: Eclipse Temurin JRE with Hotspot 11.0.23+9 (x86)

**Additional context**
x

**Comment by dpolivaev** [comment]
Can you please specify how exactly you copy the link and how exactly you paste it? There are many different ways to do it. I need  a very precise description of your steps.

**Comment by walmar** [comment]
I have added more information to the reproduce section of the issue. Let me know if there's anything else you'd like to know.

**Comment by dpolivaev** [comment]
I think it is fixed in the preview versions.
