### ISSUE TITLE
Exception on Search and Replace - 1.12.1-pre10 any map

### ISSUE THREAD

**Issue by JJSlote** [freeplane/freeplane#1833]
Greetings - Now getting the error whistle clicking to Search and Replace. S&R doesn't happen, but I can continue editing and saving the map; it did work as expected on initial tests. The content or size of the map doesn't matter; I get the same error on a generic new map, attached with the log. 

Windows 11
1.12.1-pre10
Java version: 15.0.10

Rgds - Jerome

[log.zip](https://github.com/freeplane/freeplane/files/15320740/log.zip)

**Comment by JJSlote** [comment]
This was resolved by removing the User Folder 1.12x before a fresh install. Will know for next time.

**Comment by dpolivaev** [comment]
Even if removing the folder helps, reporting the bug is still important.

**Comment by JJSlote** [comment]
I also removed the addons from 1.11x before reinstalling 1.12.1.
