### ISSUE TITLE
Tag font size on Edit Tags dialog tied to size in Map

### ISSUE THREAD

**Issue by JJSlote** [freeplane/freeplane#1836]
Hi - we're using _Edit Styles_ to get the Tags in preferred relation to the default node text size. But that size is also picked up on the Edit Tags dialog, where it's too small to read. We can zoom the map; we can't zoom the dialog:

![Size6TagsWithDialog](https://github.com/freeplane/freeplane/assets/68667676/db99181c-5757-4ec7-afe4-892ce87e24e7)

We need a considerably larger tag size to display readable tags in the dialog:

![Size10TagsWithDialog](https://github.com/freeplane/freeplane/assets/68667676/cd76e947-c207-4cd1-b630-e633180c1325)

Tag display size in the Filter system is better; it's independent of the size used within the Map:

![Size6TagsWithFilter](https://github.com/freeplane/freeplane/assets/68667676/9fcec53e-1a6c-46b7-aa44-9e528281f0bc)

So I'd request that approach also in Edit Tags.

Thanks for considering!!
Jerome

**Comment by dpolivaev** [comment]
Preview 1.12.1_12
