### ISSUE TITLE
Tags: (Regression) autocomplete not working

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1837]
Autocomplete for tags stopped working in freeplane-1.12.1-pre10

- freeplane-1.12.1-pre09: works fine
- freeplane-1.12.1-pre10: not working
- freeplane-1.12.1-pre11: not working

It rarely pops up, but 99% of the time it doesn't work
![javaw_aGnHIz5Uaq](https://github.com/freeplane/freeplane/assets/77707706/48d1a12d-4e73-485c-ab2e-e5388ce5ddb7)

**Comment by dpolivaev** [comment]
On my machine it works after I press the arrow down key. I intentionally do not show it automatically because if I do, selected value in the list overwrites the text you type.

**Comment by euu2021** [comment]
>  On my machine it works after I press the arrow down key. I intentionally do not show it automatically because if I do, selected value in the list overwrites the text you type.

Oh, now I see. I think that 99% of the people will never find the autocomplete 😅

For me, showing the autocomplete results straight away works way better. I've been using like this in anki for years. 

The reason: when I start typing a tag, I'm usually not sure if it already exists, so I need quick feedback from the autocomplete. Having to press down every time is a pain. If I want to enter an original tag, ignoring the autocomplete, I can simply keep writing, and, if needed, click outside the autocomplete and it disappears, allowing me to accept the original tag:


![javaw_jKcV1MzzaZ](https://github.com/freeplane/freeplane/assets/77707706/67c1b47b-59dd-4d5f-a5e8-f1651b7712aa)

**Comment by dpolivaev** [comment]
Preview 1.12.1_12

**Comment by euu2021** [comment]
I like it. Thanks
