### ISSUE TITLE
Tags: Tags below node make the node unnecessarily too wide

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1838]
Tags below node make the node unnecessarily too wide:

![javaw_70DhqWFher](https://github.com/freeplane/freeplane/assets/77707706/035f33f8-06c1-48a5-b5f3-7e9b13b6078a)

freeplane-1.12.1-pre10

**Comment by dpolivaev** [comment]
Attach your mind map.
Also check what happens on zoom 100%. If it works there, I have already fixed it.

**Comment by euu2021** [comment]
There is something weird going on with the zoom:
![javaw_pqtaSInjZI](https://github.com/freeplane/freeplane/assets/77707706/bec114c7-132c-4b9b-922e-aedcbea5dfba)

[tags bug zoom.zip](https://github.com/freeplane/freeplane/files/15370274/tags.bug.zoom.zip)

**Comment by euu2021** [comment]
> There is something weird going on with the zoom

The weird thing that I'm referring is: as the zoom changes, the width of the node changes

**Comment by dpolivaev** [comment]
Preview 1.12.1_12

**Comment by euu2021** [comment]
I see that the zoom problem was solved, but the node is still too wide.

Notice that the width is fine when the nodes are besides:

![image](https://github.com/freeplane/freeplane/assets/77707706/2a5a16f9-cace-401b-a6a4-bdd83bfe7206)

But it gets super wide when nodes are below. Even with only two tags:

![image](https://github.com/freeplane/freeplane/assets/77707706/17873562-607f-47c1-a910-64bc283b054f)

**Comment by dpolivaev** [comment]
Got it, fixed in source code

**Comment by dpolivaev** [comment]
Please check if the bug is still present
Preview 1.12.2_01 alpha

**Comment by euu2021** [comment]
It's working fine. Thanks
