### ISSUE TITLE
Tags: `Manage tag categories for map` and the categorization of the `Insert` menu when using ad-hoc categories

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1839]
My point got lost in the discussions about categorizations, so I will create this issue. As I said:

[...] I think that I will use Node categories, because I don't see, for my situation, the advantage of Map categories. But, I would like to use the `Manage tag categories for map` and the categorization of the `Insert` menu.

_Originally posted by @euu2021 in https://github.com/freeplane/freeplane/discussions/1652#discussioncomment-9405951_

**Comment by euu2021** [comment]
It's also related to what macmarrum said about renaming categories (https://github.com/freeplane/freeplane/discussions/1652#discussioncomment-9481467). With the `Manage tag categories`, it's possible to easily rearrange the categories using drag and drop.

**Comment by dpolivaev** [comment]
Well, having separate data structure specifically for categories has its advantages.
I do not know how I could combine the both approaches.

**Comment by euu2021** [comment]
> Well, having separate data structure specifically for categories has its advantages. I do not know how I could combine the both approaches.

I see. But, here, I'm not talking about combining the approaches. I just want to use `Manage tag categories` (or anything that is similar to that) with the ad-hoc categories.

**Comment by dpolivaev** [comment]
Well, instead of inserting a managed tag the same structure could be used for inserting the ad-hoc tag like `food--berry--blueberry'.

**Comment by euu2021** [comment]
> Well, instead of inserting a managed tag the same structure could be used for inserting the ad-hoc tag like `food--berry--blueberry'.


Sorry, I'm not sure if I understand what you mean.

I will make a recap:

- What I want: 

Currently, there is a feature called `Edit->Node properties->Manage tag categories for map`.
This feature is good, but it is only available for the "Managed categories", and not to the "Ad-hoc categories".
In other words, the user who chooses to use "Managed categories" has access to the excellent `Manage tag categories for map`, but the`Ad-hoc categories` use doesn't have that.
I will use `Ad-hoc categories` and I would like to have access to a feature like "Manage tag categories".

- Why I need it:

**_Reason 1_**: the "Manage tag categories" makes it easy to rearrange categories.
![javaw_oPThOHbQ04](https://github.com/freeplane/freeplane/assets/77707706/55fd15e4-0fa3-4e46-98dc-478df1f8eded)

**_Reason 2_**: I like how, in "Manage tag categories", it's easy to navigate through existing categories, and choose tags to include in the selected nodes. 
I will usually insert the tag directly from the autocomplete, but in some situations it's good to pick using the "Manage tag categories".

**Comment by dpolivaev** [comment]
If tag categories are distributed in ad-hoc categorized tags, in order to do what you suggest we would need extremely complicated logic as follows:

1. The categories should be aggregated from the nodes distributed across the whole map
2. All operations on the tree should be captured
3. They should be applied to each node individually.

This complexity is a result of a need to synchronize categories across the whole map that are saved independently.
It requires non trivial data structure mapping that just do not fit in my head.

If you understand how it should work, please give me a full specification.

**Comment by euu2021** [comment]
Yes, I think that this is the logic.

> If you understand how it should work, please give me a full specification.

Maybe I'm oversimplifying, but isn't it just a search and replace operation that is triggered by each change in the tree?

For example, when the user makes this change in the tree:

![javaw_oPThOHbQ04](https://github.com/freeplane/freeplane/assets/77707706/e3befb78-1ae3-4f89-a289-5920c5a933db)


FP searches for each node that uses `food--vegetable--tomato` and replace it with `food--fruit--tomato`.

Is it technically difficult to have this kind of change listener in the `Manage tag categories` window?

**Comment by aaa1386** [comment]
Hello
Can you explain how you colored some of the words?
Sorry that the question is not related to the topic of this page.
![image](https://github.com/freeplane/freeplane/assets/38586259/b294c01c-aa3d-4c08-a9d3-b1a8a6103d95)

**Comment by aaa1386** [comment]
![image](https://github.com/freeplane/freeplane/assets/38586259/1db298b8-f306-4179-a002-5d0b9921907a)

I really like grouping tags.
But I can't create a category according to this image.
Can you explain how you did this?

My category:
![image](https://github.com/freeplane/freeplane/assets/38586259/b84ec047-555c-4d7b-ba51-99c879d959e7)

I don't know how to work with "Ad-hoc categories" option.

**Comment by euu2021** [comment]
> Can you explain how you colored some of the words?

Put the words between backticks (this symbol: `)

See: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

> But I can't create a category according to this image.

Your categories seem to be working similar to mine. What difference are you talking about?

**Comment by aaa1386** [comment]
> > Can you explain how you colored some of the words?
> 
> Put the words between backticks (this symbol: `)
Thank.

**Comment by aaa1386** [comment]
I don't know how to work with `Ad-hoc categories` option.

**Comment by dpolivaev** [comment]
Preview 1.12.2_01 alpha
