### ISSUE TITLE
Tags: Retain the color when renaming a tag 

### ISSUE THREAD

**Issue by JJSlote** [freeplane/freeplane#1841]
Hi - At present, to rename a tag in the tag editor is to generate a new color for it. I'd request a toggle to enable the user to retain the tag's existing color.

We'd then be able to maintain maps with our own tag color palettes, share them with the community, and copy branches as needed out into our production maps, where we'd replace the hexcode names with meaningful ones. Via the usual Freeplane magic, colors first, then names. 🪄 

![HexcolorTagset](https://github.com/freeplane/freeplane/assets/68667676/b09b4517-e3d7-4fc3-99ab-53f003c8c4c2)

Thanks for considering!!
Jerome

1.12.1-pre12

**Comment by aaa1386** [comment]
Excuse me, can you explain how you created Group1?

**Comment by JJSlote** [comment]
> Excuse me, can you explain how you created Group1?

Certainly. I made some tags with common color names such as Green, Gold, Orange. Gave them preferred shades in the Tag Editor. Trial and error in the HSL tab to find the lowest value for Lightness that would yield black edges and lettering. After saving, used a text editor on the map file to replace the common color names with their corresponding _tagcolor_ values. 

For a possible future AutoHotkey script, I'd find appealing color palettes on the web, and copy them out to the clipboard. The script would parse the clipboard to identify the six-character hex values. It'd then fix each color with several different values for lightness (by concatenating "44","88","CC" for example to each hex value), check for colors already on the Palette map, and generate new Group nodes on the same pattern. 

Rgds - Jerome

**Comment by dpolivaev** [comment]
I  decided to keep the color when tags are renamed in tag category editor, but not in the tag editor, because if you change a tag in the tag editor it is changed only for one node and it is likely to have another meaning than the previous tag.
