### ISSUE TITLE
Error in node text layout for non fork nodes

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1842]
Freeplane software has bugs with right-to-left languages. I tested two languages, Persian and Arabic, and these bugs exist. I describe a bug on this page.

Introduction: There are many people who use right-to-left languages. For example, there are other languages such as Arabic and Persian.
There are many users of these languages. The number of countries with Arabic language and Farsi (Persian) language is shown in the two links below.

https://en.wikipedia.org/wiki/Arab_world

22 countries speak Arabic.

https://en.wikipedia.org/wiki/Persian_language

Freeplane software is compatible with right-to-left languages, but there are still some bugs.
I will explain some of them .
I hope the creators of Freeplane software pay more attention to these problems and fix them if they can be fixed.

  Add Arabic keyboard to Windows. Useful for troubleshooting.

First, I give explanations about two languages, Persian and Arabic, which are useful for solving bugs.

The way of typing words and letters in English, Arabic and Farsi is similar. Each time you press a key on the keyboard, a letter is typed, and when you press  space key, the words are separated, so when we type several letters, the word is created by pressing the space button.

I will describe one of the bugs. And I suggest a solution.

First, watch the video below. When zooming, the number of lines of a node increases and the text gets confused.
 Especially when the laptop is connected to another monitor, when disconnecting or connecting monitor ، the Freeplane software, sometimes it can't fully synchronize with the new resolution and mode, so even without zooming, many nodes lose their original mode. And the number of rows of nodes increases.

https://github.com/freeplane/freeplane/assets/38586259/6ad416c7-918c-4927-99a0-9a221ebbfd2d

**Comment by aaa1386** [comment]
The cause of this bug is the width of the node line. When the width of the node line is increased, this increase in the thickness of the node line comes to the inside of the node, not to the outside of the node. This causes the space inside the node to decrease and causes bug in  right-to-left languages.

Freeplane software developer has used this policy so that the nodes are perfectly aligned.

Suggested solution: Increase the thickness of the node line towards the outside of the node. The alignment of the nodes is not a problem. Because usually someone changes the thickness of the node line very little, for example 0.1 mm. This increase practically does not affect the level of the nodes.

See the following video: According to the proposed solution, in the worst case, if someone thickens the node line by one millimeter, the level of the node will change by a small amount, i.e. one millimeter.
I have shown what happens in the proposed plan at the end of the video.

If someone wants:    "Min node width" or "Max node width" options for the default style, the alignment can be completely created.


https://github.com/freeplane/freeplane/assets/38586259/6a459e3d-ff14-4edb-9b60-6f63de6f397b

Maybe the Freeplan software developer will use a method that preserves the advantages of the alignment of the nodes and solves the problem of text confusion in right-to-left languages, just as there is no text confusion in English.
If such a thing is possible, it is the best solution to this problem.

**Comment by aaa1386** [comment]
[bug (2).zip](https://github.com/freeplane/freeplane/files/15395415/bug.2.zip)

**Comment by aaa1386** [comment]
I have compared some nodes with correct and unordered representation. 

Sometimes a half of a word is shown in one line and the other half in another line. If you don't know Arabic, you can compare it with the correct way of displaying it in the picture.
Some nodes have created an extra line.
I will explain the other bug in the next comment.
![image](https://github.com/freeplane/freeplane/assets/38586259/7783833d-cc26-472e-af69-3e452f7e0c98)

**Comment by aaa1386** [comment]
The quality of text display is also weak and bad. You can see the good and bad mode in the image below.

Zoom in for a better view.

![image](https://github.com/freeplane/freeplane/assets/38586259/486bb2b2-48f4-426a-952b-f244a76268d8)

**Comment by aaa1386** [comment]
![image](https://github.com/freeplane/freeplane/assets/38586259/e8e9390a-7302-467f-9540-29cc966fb03a)

**Comment by dpolivaev** [comment]
Preview 1.12.2_01 alpha
