### ISSUE TITLE
Markdown/ Links with brackets not regognized correctly

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#1847]
# Reproduce
Take this link `https://doi.org/10.1016/S2542-5196(21)00251-5` and put in in markdown code like so.  
  
`[My link](https://doi.org/10.1016/S2542-5196(21)00251-5)`

# Expected
[My link](https://doi.org/10.1016/S2542-5196(21)00251-5)

# Actual result
![image](https://github.com/freeplane/freeplane/assets/10260832/d4b922df-6de9-498a-9abc-66cb9e7914f2)

Freeplane is love :) ❤

**Comment by dpolivaev** [comment]
Currently you can encode it as `[My link](https://doi.org/10.1016/S2542-5196%2821%2900251-5)`
