### ISSUE TITLE
Unfold node when children folding is toggled

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1849]
With `Navigate -> Fold -> (Un) Fold children` option, you can fold or unfold the first level of a branch.
It is very important to see the first level of each branch. As you can see in the video, using this option, nodes 1, 2, 3, 4, 5, 6, 7, 8, 9 can be viewed side by side. You can focus on which of the branches 1, 2, 3, 4, 5, 6, 7, 8, 9 to open.   It is very interesting that this option remembers the user's settings on open and closed nodes. Like the settings related to "bbbb" or "cccc" nodes 

  The only drawback is that this option does not work if the "aaaa" node is fully folded. But you can use the `unfold one level` option, but there is a flaw, that is, it messes up the user's settings in the "bbbb" and "cccc" nodes. 

Suggestion: Make the `Navigate -> Fold -> (Un) Fold children` option work even when the node is fully folded. 
  This makes us always able to fold or unfold the first level of each node in any situation. without manipulating user settings.

**Comment by aaa1386** [comment]
https://github.com/freeplane/freeplane/assets/38586259/09d02328-a776-4d3e-bab0-023c08626672

**Comment by aaa1386** [comment]
`Navigate -> Fold -> (Un) Fold children` option does not work.  [

https://github.com/freeplane/freeplane/assets/38586259/43182dfb-261f-45cc-80bd-e457008130db

](url)

**Comment by aaa1386** [comment]
https://github.com/freeplane/freeplane/assets/38586259/4188f550-40e2-4e86-a693-78e985df2a46

Messing up user settings in "bbbb" nodes
  and "cccc"

**Comment by macmarrum** [comment]
Here's a script that should cover what you need:
```groovy
def isNodeFolded = node.isFolded()
def isAnyChildFolded = node.children.any { it.isFolded() }
if (isNodeFolded) node.folded = false
node.children.each { it.folded = isNodeFolded || isAnyChildFolded ? false : true }
```
Please let me know if it works as expected.

**Comment by aaa1386** [comment]
> Here's a script that should cover what you need:
Thank you.
This option is very useful for me. It works fine now, if I find any problem I will report it.

**Comment by aaa1386** [comment]
> Here's a script that should cover what you need:
> 
> ```groovy
> def isNodeFolded = node.isFolded()
> def isAnyChildFolded = node.children.any { it.isFolded() }
> if (isNodeFolded) node.folded = false
> node.children.each { it.folded = isNodeFolded || isAnyChildFolded ? false : true }
> ```
> 
> Please let me know if it works as expected.

https://github.com/freeplane/freeplane/assets/38586259/bc083096-6391-4794-9e33-58bccd33afe4

It works fine, but if we open a map in a new view, the script does not work independently in both views.
If the script assumes two views of the map as two separate and independent maps, its performance is more accurate.
I don't know if it is possible to modify the script or not? In any case, it meets my needs to a large extent.
Thank.

**Comment by aaa1386** [comment]
I noticed that in the Freeplane software, when two views of the map are created, the `Navigate -> Fold -> (Un) Fold children` option 
It does not work in those two views independently. Watch the video below:

In "Map1 ":       Node "3" should not be folded because before we click `Navigate -> Fold -> (Un) Fold children` , node 3 was unfolded.
https://github.com/freeplane/freeplane/assets/38586259/278b9475-2705-4848-a752-85b6af22c164

**Comment by aaa1386** [comment]
> Here's a script that should cover what you need:
> 
> ```groovy
> def isNodeFolded = node.isFolded()
> def isAnyChildFolded = node.children.any { it.isFolded() }
> if (isNodeFolded) node.folded = false
> node.children.each { it.folded = isNodeFolded || isAnyChildFolded ? false : true }
> ```
> 
> Please let me know if it works as expected.

@macmarrum   Hello .Thanks for making the script.
Suppose node 1111 is selected.
If the node 1111 is folded, by running the script, the branch 1111 will be expanded first, and by running the script again, the first level of the node 1111 will be revealed (that is, the nodes 1111 and 2222 will be revealed)

I like to do the opposite.
  That is, the first time the script is run, it will only fold the first level. (only nodes 1111 and 2222 are visible) The second time we run the script, the branch 1111 will expand without messing up the settings related to node 3333.


My main goal is to open the first level of a branch and minimally manipulate the nodes settings of that branch.
![image](https://github.com/freeplane/freeplane/assets/38586259/71edb480-7e54-46c4-88d1-92a100fbd153)

**Comment by macmarrum** [comment]
Sorry. I don't follow.
Maybe you could record a video of how you use the script?

**Comment by aaa1386** [comment]
My goal is to always be able to easily see the first level in any situation so that all the nodes of the first level are folded.
The software does not have an option for this. I have to combine two options :   `Navigate -> Fold -> (Un)Fold children` and    `Navigate -> Fold -> Show first level`  .

When the selected node is expanded, use the option `Navigate -> Fold -> Fold children` to display only the first level of the node.
 
If the selected node is folded, I use the option `Navigate -> Fold -> Show first level`  and display the first level.

  This option has a drawback. Open and closed settings will mess up the nodes in the subdirectory. It means that it folds all the nodes of that branch. 

Therefore, the software does not have the `Show First Level` option for navigation. 
When the selected node is folded, executing it will open the first level.  
When the selected node is expanded more than one level, using that option will reveal only the first level. Without messing up the fold or unfold settings of nodes on level 2, 3 and more.

**Comment by aaa1386** [comment]
> Sorry. I don't follow. Maybe you could record a video of how you use the script?



@macmarrum   Watch the following two videos:
Wrong performance - expands the node first - I have to run the script twice to reach my goal which is to display the first level of the selected node.





https://github.com/freeplane/freeplane/assets/38586259/d3ab190d-4c17-43ab-acc1-e2d453728f6f






https://github.com/freeplane/freeplane/assets/38586259/0c9eba3b-d2c6-4e43-8d8e-c7426e49b04e

**Comment by aaa1386** [comment]
I uploaded a better video of the script running

**Comment by macmarrum** [comment]
I think this is what you what:
* if the selected node is folded
  * unfold it and fold all its children
* otherwise
  * if any child is unfolded
    * fold all node's children
  * otherwise
    * unfold all node's children

Is that correct?

**Comment by aaa1386** [comment]
If I understand correctly - I think that is correct. thank you

**Comment by macmarrum** [comment]
```groovy
if (node.isFolded()) {
    node.folded = false
    node.children.each { it.folded = true }
} else {
    if (node.children.any { !it.isFolded() })
        node.children.each { it.folded = true }
    else
        node.children.each { it.folded = false }
}
```

**Comment by aaa1386** [comment]
>

https://github.com/freeplane/freeplane/assets/38586259/f304fd24-0764-441d-8f65-61d282259542

When the selected node has multiple branches, one of which has no children, the script will not work. That is, it does not unfold.

**Comment by macmarrum** [comment]
Please try this one
```groovy
def foldableChildren = node.children.findAll { it.isVisible() && !it.isLeaf() }
if (node.isFolded()) {
    node.folded = false
    foldableChildren.each { it.folded = true }
} else {
    if (foldableChildren.any { !it.isFolded() })
        foldableChildren.each { it.folded = true }
    else
        foldableChildren.each { it.folded = false }
}
```

**Comment by aaa1386** [comment]
Thank you very much - it works great.

**Comment by aaa1386** [comment]
@macmarrum   .   Excuse me, can you write another script according to this description?
I apologize, I would like to have both scripts. Both the previous script and the script according to the description below.
Both are good and great for me.

>
> * if the selected node is folded
>   
>   * unfold it and fold all its children
> * otherwise
>   
>   * if any child is unfolded
>     
>     * fold all node's children
>   * otherwise
>     
>     * fold the selected node
>

**Comment by macmarrum** [comment]
@ajaberi1360 I'm glad the script is helpful.

Maybe you could try to change my last script yourself? Only one line needs to be changed, so it could be a good start for diving into the world of scripting :smile:

If you get stuck, let me know.

**Comment by aaa1386** [comment]
def foldableChildren = node.children.findAll { it.isVisible() && !it.isLeaf() }
if (node.isFolded()) {
    node.folded = false
    foldableChildren.each { it.folded = true }
} else {
    if (foldableChildren.any { !it.isFolded() })
        foldableChildren.each { it.folded = true }
    else
{
    node.folded = true
    foldableChildren.each { it.folded = false }
}
}

**Comment by aaa1386** [comment]
It's strange - no matter how hard it was, I finally modified that script.
I congratulated myself and you.😄😄😄

**Comment by dpolivaev** [comment]
Preview 1.12.1_01 alpha

**Comment by aaa1386** [comment]
A good thing has happened in the software update, but I like this script more, it has a small difference with the option `Navigate -> Fold -> (Un) Fold children`.
![image](https://github.com/freeplane/freeplane/assets/38586259/b81295a4-7f60-4df6-916d-8805f1b01d3d)

**Comment by dpolivaev** [comment]
Preview 1.12.2_05

**Comment by aaa1386** [comment]
very good. Thanks.
