### ISSUE TITLE
Cannot use CSS to specify the width/height of image to be set to auto in node's HTML

### ISSUE THREAD

**Issue by cjwomack** [freeplane/freeplane#1852]
**Describe the bug**
I'm trying add an image inside html of a node but only specify only the height or the width of the image with the other dimension rescaling automatically.

**To Reproduce**
1. Right click Edit on a node
2. Edit node core in dialog
3. Select right tab on bottom named HTML Code view
4. Add an image nestled between <body> tags with deprecated `<img src="test.png" height="200" style="width: auto">`  OR `<img src="test.png" style="height=200; width: auto">`
5. Select left tab on bottom named Layout view - this shows the image rescaled properly (It also shows it rescaled without style defined but I believe that isn't the right behavior)
6. Click on OK on bottom of dialog

**Expected behavior**
I expect to see a resized image with the width scaled to the same width to height proportion in original image

Also when redoing steps 1-3 again - the style="width: auto" has disappeared from the img tag.

Looks like simply html can render the html but Freeplane uses something else to render it in main mindmap.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.11.14
 - Java Version Java version: 15.0.10

**Additional context**
Seems similar to https://github.com/freeplane/freeplane/issues/1710 only I'm not using Markdown
Yes, I know one can insert an image via the menu. I also know I can specify both coordinates... but this is annoying.

**Comment by dpolivaev** [comment]
Unfortunately, html renderer implemented by Swing offers no way to fix it.
