### ISSUE TITLE
Java Warning on opening  last opened map opens as blank window 

### ISSUE THREAD

**Issue by badger62** [freeplane/freeplane#1853]
Upon opening Freeplane from the terminal, it opens with a blank window  with the name of the last opened mind map in the title of the window .  
At the end of the message in the terminal is the following warning:
`WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.freeplane.plugin.script.ScriptingRegistration (bundle://9)
WARNING: Please consider reporting this to the maintainers of org.freeplane.plugin.script.ScriptingRegistration
WARNING: System::setSecurityManager will be removed in a future release
May 28, 2024 9:10:33 AM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
Shutdown hook invoked, stopping OSGi Framework`

Expected behaviour:
Window with Freeplane running in it should start as normal , opening to the most recently open map.

Other context:
Occasionally Freeplane will start OK and the `Shutdown hook invoked, stopping OSGi Framework` will not be printed on the terminal.

Ubuntu 22.04 ,  
Freeplane 1.11.13 , 
Java version: 17.0.10

**Comment by dpolivaev** [comment]
I do not understand what exactly you mean by "blank window", please attach a screenshot.
The warning is OK, Security Manager was deprecated without any replacement and Freeplane continues using it.

The issue might be related to setting Preferences…->Environment->Single program instance->Open files in a running instance. Try to deactivate it and write here if it helps.
