### ISSUE TITLE
Outdated version suggested for download on 'sourceforge.net'.

### ISSUE THREAD

**Issue by glissner-futura** [freeplane/freeplane#1854]
**Problem description**:
The 'Download latest version'-button on 'https://sourceforge.net/projects/freeplane/files/' does lead to an outdated version of the software (...13) instead of the latest version (...14) (s.a. attached screenshot).

![FreeMindWrongDownloadVersion](https://github.com/freeplane/freeplane/assets/104490925/e73ed5fa-3cc9-4d72-8fde-4eab5b635866)

**Steps to reproduce the behavior**:
1. Open: https://sourceforge.net/projects/freeplane/files/
2. Click on 'Download latest version'
3. Outdated version is suggested.

**Expected behavior**
Current version should be suggested for download.

**Comment by gamepad-coder** [comment]
This is confusing as a user only halfway paying attention lol.

<br>

Using `Freeplane 1.11.13`:
- Clicking **New version '1.11.14' available** <br>takes you to SourceForge

![image](https://github.com/freeplane/freeplane/assets/65138515/edaefa88-f177-4850-903c-779a79b0cd03)

<br>

- Then clicking **Download Latest Version** leads the user to download the version they're already on.

![image](https://github.com/freeplane/freeplane/assets/65138515/7297cc17-127b-473f-baa1-c41d35735a7c)


<br>

Taking the user right back here <br>after the reinstall:

![image](https://github.com/freeplane/freeplane/assets/65138515/edaefa88-f177-4850-903c-779a79b0cd03)

**Comment by gamepad-coder** [comment]
@dpolivaev 
[It looks like you added the commit](https://github.com/freeplane/freeplane/commit/9f7e8ed5c5f1d6a40abb6aa7bd761feebe600094) that bumped freeplane to version `1.11.14`?

Is there automation that's supposed to update the latest version on Sourceforge, or does it need to be manually updated by someone?

**Comment by dpolivaev** [comment]
Thanks for letting me know, fixed. I have not automated it yet and probably forgot to set version 1.11.14 as the new default.

**Comment by glissner-futura** [comment]
Thank you for fixing it!
