### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by mdvga** [freeplane/freeplane#1855]
![Parsing Error](https://github.com/freeplane/freeplane/assets/171441092/1db3cd12-562e-466b-b846-4022dd67a2c5)
Error while parsing file:C:\Users\mdvga\OneDrive\! 1 Faith Walk\! Discipleship\! ZeroBC

**Comment by mdvga** [comment]
Spent time creating and even printing this MM and now it won't open???

**Comment by dpolivaev** [comment]
Spent time reading your report found not enough information. If you want me to investigate the issue please attach the mind map file and the log files.
