### ISSUE TITLE
Scroll unfolded node tree to visible after any unfold action

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1856]
In the good Freeplane software, there is an option `scroll map after unfolding node`.

But even though the map auto-scroll option is very useful and functional, this option only works after unfolding a node.

 Automatic scrolling of the map is a very practical option for the mode where the user selects the node, but it is not yet available in the software.

Please add the `scroll map after selecting a node` option to the FP.
Thanks to the creators of FP.

**Comment by aaa1386** [comment]
This option is very intelligently designed, but unfortunately it is not available for the mode where the node is selected.
If this option is created in the software, the user will scroll the least. This is very important.

**Comment by aaa1386** [comment]
The `scroll map after unfolding node` option has a flaw.
It works only when we click on the folding mark. When we unfold the node in other ways, the option does not work, for example, unfolding using the `Unfold All` option and other things.

**Comment by aaa1386** [comment]
I suggest: It should have three modes for the scroll map.

1- `Scroll map after unfolding node by clicking on the folding mark. `

2-`Scroll map after unfolding the node (Any method). `

3-`Scroll map after selecting node`.

**Comment by aaa1386** [comment]
> `scroll map after unfolding node`.


The auto-scroll map option is very nice, but I'll explain the limitations it has in more detail.
1- The `scroll map after unfolding node` option scrolls the map in the following cases, and in some cases it does not do this.
Items that scroll:
- After running the `Navigate -> Fold -> Unfold` option.
- After clicking on folding mark and unfold node.
-When the node is unfolded by the right or left buttons.

Scrolling is not done:
-If the node is unfolded by the `Unfold all` option.
- If the node is unfolded by `Unfold one level` option.
- Unfolding the node by double clicking on it.
- Unfolding by the option `Navigate -> Fold -> Unfold children`

Don't you think this is confusing?
You always have to think about how to scroll the map automatically? This means that your mind is always engaged with this question when you work with maps?
In addition, the map is not automatically scrolled for you in all cases. Pay attention to the following article.

2- Sometimes all nodes are expanded. Suppose we want to select a branch whose nodes are not visible on the screen. Can the  `scroll map after unfolding node` option scroll the map for you?
Therefore, for users who like the map to be scrolled automatically, the `scroll map after unfolding node` option is not enough.

**Comment by euu2021** [comment]
> Please add the scroll map after selecting a node option to the FP.

Try:
View->View settings->Center selected node automatically
Preferences…->Behaviour->Selection method->Center selected node automatically

Also, see #1258

**Comment by aaa1386** [comment]
[euu2021](https://github.com/euu2021) Thank you for your comment.
If you enable the `View->View settings->Center selected node automatically` option، the map moves whenever you select a new node.

It is an option that is used for special cases. By activating it the map is always moving. The movement of the map makes it difficult to concentrate.

Therefore, the least movement should be given to the map so as not to disturb the user's intellectual concentration.

One of the great advantages of the `scroll map after unfolding node` option is that the map is moved the least, avoiding extra movements. This makes it possible to always enable `scroll map after unfolding node`. This option always puts the map in the best state, without giving the map extra moves.

**Comment by aaa1386** [comment]
In addition, placing the selected node in the center of the screen does not mean the best case. Sometimes the best situation is that the node is in the corners. This is done by the `scroll map after unfolding node` option

**Comment by aaa1386** [comment]
Look at this link.
https://github.com/ajaberi1360/123456789/issues/1
 I was writing the idea and I accidentally saw the "scroll map after unfolding node" option.
I realized that the function of the idea is exactly implemented in FP, but it has a flaw.
It does not work for the mode where the node is selected. It is only for the unfolding mode, that is unfolding from some methods, not all of them.

**Comment by aaa1386** [comment]
@dpolivaev
Excuse me - will this idea that was raised on this page be added in FP?
We often set the selected node and children on my screen by manually scrolling. This is hard. If the idea is implemented in the software, manual scrolls are not needed many times.

**Comment by aaa1386** [comment]
The "makes sense" tag. Does it mean that it is implemented in the software?

**Comment by aaa1386** [comment]
> I suggest: It should have three modes for the scroll map.
> 
> 1- `Scroll map after unfolding node by clicking on the folding mark. `
> 
> 2-`Scroll map after unfolding the node (Any method). `
> 
> 3-`Scroll map after selecting node`.

[macmarrum](https://github.com/macmarrum)
Excuse me, is it possible to write a script for the idea?

**Comment by macmarrum** [comment]
> Excuse me, is it possible to write a script for the idea?

@ajaberi1360 The scripting API is limited when it come to working with map views, so I think it isn't possible.

**Comment by aaa1386** [comment]
@macmarrum

Hi - You probably didn't understand what I meant, so I'll give a clearer explanation.
First, we enable the `Preferences -> Behavior -> scroll map after unfolding node` option.

Suppose the operation that this option performs is `BBB`.
We know that BBB is done just by clicking on the folding mark and unfolding the node.

What I want is the following script:
If any node is selected by the user, perform `BBB` operation.

Is this script not possible?

**Comment by macmarrum** [comment]
@ajaberi1360 

Thanks for the explanation. So when a node is selected, you want the map to scroll in the same fashion as for `Preferences…->Behaviour->Scroll map after unfolding a node`.

I think it isn't possible, using the scripting API, to react on a node being selected.

**Comment by aaa1386** [comment]
Thank you for your reply.

**Comment by dpolivaev** [comment]
Preview 1.12.2_05

**Comment by aaa1386** [comment]
[dpolivaev](https://github.com/dpolivaev)     Thanks for this good update.
But there is a bug: sometimes it doesn't work properly.
If the node selection method is in the following two modes:
`Preferences -> Behaviour -> Selection method -> Delayed or Direct`

That is, when we use the mouse to select the node, it does not work.

**Comment by aaa1386** [comment]
Another bug that exists is that:
It does not work when the `Auto-expand` option is enabled.

**Comment by dpolivaev** [comment]
Preview 1.12.2_06.

**Comment by aaa1386** [comment]
> Preview 1.12.2_06.

If the node selection setting is: `Preferences -> Behavior -> Selection method -> By click`
If the `Auto-expand` option is enabled, the bug still exists.

When we select a node by clicking.
