### ISSUE TITLE
Conditional formating filters dissapear if not used

### ISSUE THREAD

**Issue by juliomap** [freeplane/freeplane#186]
I am trying to add conditional formating rules.
Format => Manage styles => Manage conditional styles for MAP
The expected (I suppose) procedure is to first add a filter, **then select it before accepting the new filter addition**, and then add a rule that uses the recently added filter.
But as I hadn't read the instructions, I was trying to first add 10 filters, and later add rules to use each of them.
The filters get lost.
So if you add a filter, and don't select it **inmediately** before pressing OK, to close the "filter composer", it doesn't get added actually.
Anyway, the Idea of separating filter creation from contitional styling rule creation **is not very straightforward**. (I mean, at least for me, it is not easy to understand).

**Comment by dpolivaev** [comment]
Fixed for Freeplane 1.9

**Comment by dpolivaev** [comment]
Fix available in preview 1.9.0_02

**Comment by juliomap** [comment]
Excellent.
Thanks!
😀
