### ISSUE TITLE
si je rajoute des icones et que 2 identiques se suivent, cela ne fonctionne pas exemple A10 marche, A11 ne marche pas, le deuxieme icone 1 efface le précédent. comment inserer A11 en icone ?

### ISSUE THREAD

**Issue by JM49070** [freeplane/freeplane#1860]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Screenshots**

**Desktop (please complete the following information):**
 - Java Version

**Additional context**

**Comment by euu2021** [comment]
Try:
`Preferences…->Behaviour->Remove icon if exists`
or
`Insert->Icons->Remove icons->Remove icon if exists`

**Comment by JM49070** [comment]
OK merci
