### ISSUE TITLE
Option "Preferences…->Behaviour->Link to emails from text"

### ISSUE THREAD

**Issue by hi2u** [freeplane/freeplane#1861]
### Currently:

* When I have a parent node selected (but not editing its text)
* ...if I paste some text that Freeplane detects as linkable (a URL or email address)
* ...it will create the child node with the link field populated (and you get the little clickable icon to the left of the node)
* ...it works for various types of "linkable" text, e.g:

1. `https://example.com/`
2. `email@example.com` and `maybeemail@notld` ... creates a `mailto:` link

![2023-08-16_084432 - mindmap - tasks - todo - TTT_ - Freeplane - Mind map mode D__1_Documents_Flowcha](https://github.com/freeplane/freeplane/assets/9689599/07749ebd-3d30-40ac-ae92-2a37926a9dba)

### Question / feature request:

* Can I disable this link-detection for email addresses?
* I'd still like it keep the feature for http/https links though.
* I haven't been able to find the settings for this feature under `Tools > Preferences`, but might have missed it.

**Comment by dpolivaev** [comment]
Preview 1.12.2_14
