### ISSUE TITLE
unchanged map asks for saving

### ISSUE THREAD

**Issue by Olifair** [freeplane/freeplane#1868]
**Describe the bug**
Freeplane is opened with several maps opening. When closing again, some maps will ask for saving them, even if they have not been edited (or even the tab has been clicked on). With some testing I found that this is related to text in the note field of the central node, this is an old bug that has been corrected a long time ago, but has come up again in one of the more recent versions. The text in the note field needs to have rich formatting (something in bold or italics) for this problem to happen

**To Reproduce**
* Open Freeplane
* open several maps
* create a new map with some nodes
* write some text into the note field of the central node, some of this text should be formatted (**bold** or _italics_)
* save the map
* go to some other map and change something, save
* close freeplane
* reopen freeplane -> the new map will reopen (but should not show first)
* do **not** change the new map or even go to it
* do some changes in a different map
* close Freeplane
* Freeplane will ask to save the the map where you did some changes, but also for the new map, even though nothing has been changed in the new map 

**Expected behavior**
upon closing Freeplane will ask to save the maps that have been changed (or depending on your preferences, even if nodes have been opened or closed), but not for this new map (as nothing has been changed. 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.11.14
 - Java Version 16.0.10

**Comment by dpolivaev** [comment]
I can't see it. It might be related to the content of your maps or to your auto.properties. Please attach all maps you use in your test and your auto.properties.

**Comment by Olifair** [comment]
I have put my example map which includes a note in the main node, and my auto.properties into a zip file (we are not allowed to join .mm in the github); I have just reduced the "last opened" list to only one map
Hope this helps
[auto_and_testmap.zip](https://github.com/user-attachments/files/15864567/auto_and_testmap.zip)

**Comment by dpolivaev** [comment]
Preview 1.12.2_03 alpha

**Comment by Olifair** [comment]
Great, thanks @dpolivaev . What was the problem ? The bug is still classed as "not reproducible", if you did some changes in the 1.12.2:03, should it not be "solved"  ?

**Comment by dpolivaev** [comment]
I added .trim() before checking if the note content was changed

**Comment by Olifair** [comment]
Ah, OK, I'm curious to test. Any idea when 1.12 will be available as a non-alpha version ?
