### ISSUE TITLE
Please add an option to change the font of the tags.

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1869]
Adding tags to nodes is very useful.
Please add an option to chang the font tags to FP.
![image](https://github.com/freeplane/freeplane/assets/38586259/9df74fc6-e798-4fb1-9d41-5ea82eafad35)

![image](https://github.com/freeplane/freeplane/assets/38586259/9f45c6bf-b57c-4f1a-8b01-5d43cb962b2a)

**Comment by dpolivaev** [comment]
The font can be set in new style "Tags" available in the style editor

**Comment by aaa1386** [comment]
> The font can be set in new style "Tags" available in the style editor

very good.
