### ISSUE TITLE
Tags: error when trying to open tag tree in Insert, inside Edit Tag

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1871]
In this example map:

[EXAMPLE bug tag cat.zip](https://github.com/user-attachments/files/15858088/EXAMPLE.bug.tag.cat.zip)

Open Edit Tag, and try to use the Insert->Tag in the toolbar:

![image](https://github.com/freeplane/freeplane/assets/77707706/71d2b1e6-2d19-4e6c-9569-36ebaae79789)

An Error fires, with this log:

[log.txt](https://github.com/user-attachments/files/15858105/log.txt)

Preview 1.12.2-01 alpha

**Comment by dpolivaev** [comment]
1.12.2_02
