### ISSUE TITLE
Clone-tree membership is lost on save for single clones that are also part of a clone tree

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#1875]
When a mind map is saved, clones that are both single and are part of a clone tree are converted to single-only, i.e. the clone-tree membership is lost.

Steps to reproduce are outlined in the attached mind map.
When the mind map is opened, you can see the clones of node `A` are indicated as single (aka content) clones.
Run `script1` to delete and recreate the clones and observe the clone-tree status of the clones.
Close the mind map and reopen it, to see the clone-tree membership being lost.

[test-clone-serialization.v.x.mm.zip](https://github.com/user-attachments/files/15892875/test-clone-serialization.v.x.mm.zip)

I've observed this behavior in v1.11.14 and v1.12.1, and can see it also in v1.5.10

**Comment by dpolivaev** [comment]
It is interesting and I am going to have a closer look at it. I see the problem that after clones are created, the formula results of the cloned nodes containing references to the clones are not removed from the cache, and it is a bug. 

But no script should ever modify the node id because it breaks everything. Therefore script1 is illegal.

**Comment by macmarrum** [comment]
I want to make sure my report is understood as I intended it. Please note the issue that I'm reporting is not about formula cache. The issue is that once the mind map is serialized to XML, some clone-related information is lost.

> no script should ever modify the node id because it breaks everything. Therefore script1 is illegal.

In `script1`, I have commented out the lines that set ID, to show that the result is still the same:
1. After I run `script1`, `ID_5`'s child is both: a single clone and a clone-tree root. To prove it, I can add a child to it and it appears in `ID_4`'s child and in `ID_6`'s grandchild.
2. Once I close the mind map and open it again, `ID_5`'s child looses its status of a clone-tree root and is considered a single clone only. This means that adding a child to it will no longer add a child to `ID_4`'s child and `ID_6`'s grandchild.

[test-clone-serialization-2.v.x.mm.zip](https://github.com/user-attachments/files/15905142/test-clone-serialization-2.v.x.mm.zip)

**Comment by dpolivaev** [comment]
Preview 1.12.2_05

**Comment by macmarrum** [comment]
Thank you so much :rocket:

**Comment by macmarrum** [comment]
## Clone-tree membership is lost on save for **second (and 3rd, 4th, etc)** single clones that are also part of a clone tree

I've extended the test case to show that a second (and 3rd, 4th, etc) no-tree clone is still affected.

Tested on freeplane-1.12.2-alpha-pre06

[test-clone-serialization-3.xii.mm.zip](https://github.com/user-attachments/files/16028129/test-clone-serialization-3.xii.mm.zip)

1. Open the mind map
2. Run `scrip1`
3. Observe children of **ID_4**, especially the second child – it has the status of a "tree clone" and of a "single clone"; you can insert a new child node and see that it's replicated in the branch under **ID_6**
4. Save the mind map
5. Open it again
6. Observe children of **ID_4**, especially the second child – it has lost the status of a "tree clone", i.e. it's now only a "single clone"; you can insert a new child node and see that it **isn't replicated** in the branch under **ID_6**

**Comment by dpolivaev** [comment]
User Test Driven Development lol

**Comment by dpolivaev** [comment]
Preview 1.12.2_07

**Comment by macmarrum** [comment]
Awesome :rocket: 
Many thanks :smile:
