### ISSUE TITLE
Please mention the changes in different updates.

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1878]
Please mention the changes in different updates.
 For example, in updates 1.12.2, 1.12.3, 1.12.4, users do not know what happened.

**Comment by macmarrum** [comment]
I know that changes for stable releases are mentioned in https://www.freeplane.org/changelog

For alpha and pre-releases, changes are mentioned in discussions and issues.

1.12.x is still in alpha/pre-release phase.

Do you find it difficult to follow discussions and/or issues for 1.12.x to learn about changes?

**Comment by aaa1386** [comment]
> Do you find it difficult to follow discussions and/or issues for 1.12.x to learn about changes?

Yes, some changes are hard to find.
Many times, I tried to understand what exactly is happening, but I don't understand.

**Comment by dpolivaev** [comment]
The most important changes are reflected in "history.txt". available in the preview directory. If it is not changed, probably only bug fixes.
