### ISSUE TITLE
 I have enabled `scroll map after unfolding node`, but sometimes it doesn't work.

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1879]
For example:
1- First, enable the `scroll map after unfolding node` option.
2- Fold or unfold the node by `Navigate -> Fold -> (Un)fold children`.      
  or :  `Unfold All`  , etc.

**Comment by aaa1386** [comment]
#1856

**Comment by aaa1386** [comment]
The `scroll map after unfolding node` option only works when the folding mark is clicked.
The bug that exists is that: There are other methods for unfolding the nodes, by using those methods the `scroll map after unfolding node` option does not work.

**Comment by dpolivaev** [comment]
Preview 1.12.2_05
