### ISSUE TITLE
Tags: tag is duplicated, when renamed

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1884]
In this map ([EXAMPLE tag bug dup.zip](https://github.com/user-attachments/files/15944723/EXAMPLE.tag.bug.dup.zip) ), rename xxx::111 to xxx::111b, and, besides the new xxx::111b, a new tag 111b will be created under Uncategorized Tags:

![image](https://github.com/freeplane/freeplane/assets/77707706/27044d21-e409-42be-8d83-1bc852b13ddc)

freeplane_bin-1.12.2-alpha-pre05

**Comment by dpolivaev** [comment]
Preview 1.12.2_06. Changed more code than usual.
