### ISSUE TITLE
getHorizontalShift() returns vertical shift

### ISSUE THREAD

**Issue by eegerly** [freeplane/freeplane#189]
Hi, 

NodeProxy.getHorizontalShift() returns vertical shift. 

Possible root cause is wrong call at 
freeplane_api\src\main\java\org\freeplane\api\NodeRO.java # 446
in 
getHorizontalShiftInScreenPixels().

Please fix the code. 
Thank you!

**Comment by dpolivaev** [comment]
Thanks, fixed
