### ISSUE TITLE
Slow refresh rate when dragging a map with the left mouse button 

### ISSUE THREAD

**Issue by krislabs** [freeplane/freeplane#1893]
**Describe the bug**
At first run even a small mindmap is choppy when moved via dragging with the left mouse button. It fixes itself when for example the _Preferences_ window is opened & closed.

**To Reproduce**
1. Open a mindmap.
2. Try dragging it around with the left mouse button - movement / render refreshing is choppy.
3. Open & close _Preferences_ window - problem is gone.

**Expected behavior**
Smooth dragging / moving of a mindmap.

**Mind map files**
It happens for a text-only map with over 150 nodes. A map with around 10 nodes doesn't have that problem.

**Screenshots**

**Desktop**
 - OS: Windows
 - Version: 11
 - Java Version: 15.0.10
 - Display: 4K 100% scaling

**Additional context**
- Freeplane Version: 1.11.14

**Comment by macmarrum** [comment]
I noticed that when I disable `Preferences…->Appearance->Antialias->Antialias`, the scrolling and/or dragging of the map is less choppy.

**Comment by krislabs** [comment]
> I noticed that when I disable `Preferences…->Appearance->Antialias->Antialias`, the scrolling and/or dragging of the map is less choppy.

In my case disabling antialiasing helped a bit but it's still choppy.

**Comment by dpolivaev** [comment]
It is a bit hard to observe. I have quite old Windows laptop. and I do not see any significant difference  before and after opening the preferences window

**Comment by Timberjaw** [comment]
I'm seeing a similar choppiness on Linux.
* OS: EndeavourOS (6.9.7-arch1-1), KDE Plasma 6.1.1, Wayland
* Java Version: 21 (also in Java 17)
* Freeplane Version: 1.11.14
* Display: 1440p, 100% scaling, 60hz or 144hz

Some observations:
* Opening and closing preferences alone does not have an impact for me.
* Disabling antialiasing helps quite a bit, but causes artifacting/holes inside node corners.
* Choppiness _seems_ strongly correlated with the pixel dimensions of the repainted area. Zooming in to fill the viewport with a single node = choppy. Zooming out to make the entire tree a postage stamp = smooth.

**Comment by theelectricsoul** [comment]
@krislabs you got an example map? Because I have huge maps and they scroll just fine.

**Comment by krislabs** [comment]
The solution to the problem was adding:
`-Dsun.java2d.d3d=false`
to the end of:
`C:\Program Files\Freeplane\freeplane.l4j.ini`
and restarting Freeplane.

Antialiasing is enabled for all together with SVGs.

Source:
[If you're having performance issues when scrolling/selecting nodes](https://sourceforge.net/p/freeplane/discussion/758437/thread/e39711bd6f/)

**Comment by krislabs** [comment]
> @krislabs you got an example map? Because I have huge maps and they scroll just fine.

This issue was visible on basic maps containing from several dozen to over 100 nodes with just text.

**Comment by dpolivaev** [comment]
@krislabs Thanks, I included the hint into https://docs.freeplane.org/user-documentation/Troubleshooting.html#performance-issues-when-scrollingselecting-nodes
