### ISSUE TITLE
FP 1.12.2_06: Tag category manager topic 1 - it freezes the map

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#1895]
**Describe the bug**
Compared with previous solutions now the tag category manager editor (TCME) changes some actions, and  I think these topic sare bugs.
 when you open the TCME you cannot select other  nodes and cannot navigate the map with the TCME open, therefore it becomes a real burden in my operativity: I was using this as the main tags tool because I create modify substitute tags on the fly, cannot afford a 2 steps or more activity in managing a subgroup of tags

**To Reproduce**
just open the TCME in FP 1.12.2_06 and compare it with the same tool in FP 1.12.2_04 or 03 (I do not remember well which one), but 1.12.2_05 got same problem as the release 06

**Expected behavior**
WIth TCME open to be free to jump on different nodes in different maps and apply the tags (as in FP 1.12.2 early solutions

**Mind map files**
NA

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] W
 - Version [e.g. 22] 10 and 11
 - Java Version -> FP version

**Additional context**
NA

**Comment by dpolivaev** [comment]
Actually, it is not a bug: currently Freeplane expects you to finish editing of categories before you can modify the map in a different way. If you want to modify the mind map and the categories concurrently please elaborate your use case.

This issue actually relates to aggregating the category changes until you press the OK. If you want to have a different approach, use our discussion forum to develop the idea together with other community members.

**Comment by Illegit** [comment]
So I think that the problem is: the OK button doesn't save anything at the moment, and in FP 1.12.2_04 instead it was working in the way I described that was really operative and efficient, because I need to work with the editor that is open.

Please try to restore the FP 1.12.2_04 situation

**Comment by Illegit** [comment]
[Bugs & Problems.zip](https://github.com/user-attachments/files/16032796/Bugs.Problems.zip)

**Comment by Illegit** [comment]
Hi, as suggested I moved this bug topic to the forum: https://github.com/freeplane/freeplane/discussions/1901

**Comment by Illegit** [comment]
In my case this function is preventing me from using tags because I cannot see an alternative (the previous behavior was so smooth) 
eg: for example I need to add other 2 new suppliers and I have some nodes in different maps: I select all of them map by map and apply the tags I need. Now I have to go for each node, open the editor apply the tag close the editor select the node and so on...it  makes the job impossible!

**Comment by Illegit** [comment]
Imagine being in the middle of a meeting with the need to update 10 nodes... never again: I miss the meeting contents.

My previous solution was using many icons combined with attributes with a specific name "@", but in the case of attributes  when I installed the FP 1.12.2 from the FP 1.11 in some important and big maps (in the range of 10-15 MB with 25-35 knodes) I lost all of them and there were many hundreds...

**Comment by dpolivaev** [comment]
I can remove the insert tag menu entries from the tag category editor and make them available on the Freeplane main menu. How good would it fulfill your needs?

**Comment by dpolivaev** [comment]
> My previous solution was using many icons combined with attributes with a specific name "@", but in the case of attributes when I installed the FP 1.12.2 from the FP 1.11 in some important and big maps (in the range of 10-15 MB with 25-35 knodes) I lost all of them and there were many hundreds...

Can you explain what you mean by "lost"?

**Comment by dpolivaev** [comment]
Are you actually aware that Freeplane 1.12 is an early alpha version and that using it in production is not entirely risk free?

**Comment by Illegit** [comment]
> Are you actually aware that Freeplane 1.12 is an early alpha version and that using it in production is not entirely risk free?

Of course and  I do not to blame FP for it (it is my risk-taking resp). In those days you were developing the tags  therefore I moved drastically to them.

> 

> My previous solution was using many icons combined with attributes with a specific name "@", but in the case of attributes when I installed the FP 1.12.2 from the FP 1.11 in some important and big maps (in the range of 10-15 MB with 25-35 knodes) I lost all of them and there were many hundreds...
> 
> Can you explain what you mean by "lost"?

Simply said: after the installation of FP 1.12. these attributes disappeared from those maps (I wasn't able to focus them even opening the .mm file with notepad++) , but I understood that only after a day and those maps were all changed,... I cannot share because they are sensitive, but basically, the tags are the improvement.
If you give me some days maybe I try to rebuild the situation, but I'm not sure to succeed. Is it necessary?

**Comment by dpolivaev** [comment]
>  If you give me some days maybe I try to rebuild the situation, but I'm not sure to succeed. Is it necessary?

If you report that Freeplane 1.12 lost some data from Frreeplane 1.11, it would be good to see how I can prevent it from happening.

**Comment by Illegit** [comment]
I do not know how to show you it now, if there will be a next time I try to trace it but now is too late.
It happened that sometimes the maps were truncated and not working, but in last relaeses I got only this topic of missing attributes (there were about 600). I have old maps with all of them, the problem is to re-list them to each single node.... in the current map. And at now if tags are working smoothly i do not need them any longer.  I'll trace and send you if it happens again.
In the current maps with FP 1.12.2 rarely I create some and they are present (no losses). 

Going back with my memory: I do not remember well if this event happened when I installed FP 1.12.2_01 or maybe the release before the last of FP 1.11, and in fact you sent a release after the FP 1.12.2 _01 that I didn't install because of this event.
Cannot be more precise nad helpful at now.

**Comment by Illegit** [comment]
> I can remove the insert tag menu entries from the tag category editor and make them available on the Freeplane main menu. How good would it fulfill your needs?

The opitmal situation for the TCME was that fo relaese FP 1.12.2_04: doing everything with the editor open.
Maybe it will be better to have the insert out of editor, but if I 've well understood in any case I have to perform 2 different operations 1) creating the tags in the TCME and save, 2) go for inserting them: before it was contextual in 1 only operation (much better).

Please some other notes with the TCME FP 1.12.2_06: 
1) today I tried again the file I attached earlier and it was possible to drag above and below some tags (strange: yesterday full day was impossible)
2) still no way to save a new created tag in TCME if you do not insert it in a node (this is unacceptable because you need ot create tags in advance)

**Comment by Illegit** [comment]
> I can remove the insert tag menu entries from the tag category editor and make them available on the Freeplane main menu. How good would it fulfill your needs?

as above I do not like it, but it will be better than now, let's try to use it and I feedback.

**Comment by dpolivaev** [comment]
> today I tried again the file I attached earlier and it was possible to drag above and below some tags (strange: yesterday full day was impossible)

Now you see how important it is to document all cases where Freeplane behaves in a wrong way so that I can reproduce and fix it. You see that just knowing that sometimes something goes wrong is not sufficient.

**Comment by dpolivaev** [comment]
> still no way to save a new created tag in TCME if you do not insert it in a node (this is unacceptable because you need ot create tags in advance)

Same story: I need DETAILED DESCRIPTIONS of ALL your STEPS so that I can REPRODUCE the issue with your map. Otherwise I can not do anything.

**Comment by Illegit** [comment]
Sure, I think this tag editor topic is strategic, ( eg.: this is for sure one big miss in the MS Office suite). 
Understanding how to work with it in maps for a user like me is something I need to try physically because I need to identify my operational micro-steps to be effective. And because before it was not available I adopted different strategies. In the end, it is a matter of following a learning curve... Even providing feedback is not so simple sometimes.

**Comment by dpolivaev** [comment]
I have no use cases personally. You do not need to adapt to how Freeplane behaves if you can make your use cases clear.

**Comment by Illegit** [comment]
Yes. In some steps it will be like you write.

**Comment by dpolivaev** [comment]
Preview 1.12.2_07
