### ISSUE TITLE
FP 1.12.2_06: Tag category manager topic 1 - drag&drop inside doesn't work

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#1896]
**Describe the bug**
In the tag category manager editor TCME before this  FP release was possible to drag and drop tags in order to re-order the tag list, below I listed 3 cases, 1) & 3) happened 100% of the times, 2) happened 90%

**To Reproduce**
the best thing to show will be using a video, how the behavior of mouse gets troubles, but I do not have the tool for it, so I try to describe:
case1): at the sub level of tag d&d doesn't work
![Screenshot 2024-06-28 100551](https://github.com/freeplane/freeplane/assets/62674157/e1780537-3d7e-47e5-b2c2-2c1337b92cfe)
case2): quite always  it is not possible to d&d tag from an upper level to a lower level in most of the times that tag disappears or worse even some other even disappear if they are already in lower level and  below the future position of the dragged tag.
![Screenshot 2024-06-28 101043](https://github.com/freeplane/freeplane/assets/62674157/da519275-d6ef-4768-80cd-ac18d7115cb3)
case3): most of the times I'm not able to delete created tag -> remove command, or delete or cancel they do not work

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] W
 - Version [e.g. 22] 10 and 11
 - Java Version FP 1.12.2_06

**Additional context**
NA

**Expected behavior**
using drag&drop to move tag in side the TCME in order to reorder tags structures.
**Mind map files**
NA
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] W
 - Version [e.g. 22] 10 and 11
 - Java Version FP 1.12.2_06

**Additional context**
NA

**Comment by dpolivaev** [comment]
Please attach the mind map containing the tags mentioned in your screenshots. I am not AI and I can't reconstruct them from the image !!!!!

**Comment by dpolivaev** [comment]
I tried how reordering works and it works on my machine.
Having YOUR mind  map file is necessary for any analysis.

**Comment by Illegit** [comment]
I attach the map but because the ok doesn't save changes it will be slightly different. this map is just a test map, all of the problems I described happened in a big and sensitive map I use for managing some projects that I cannot share.
[Bugs & Problems.zip](https://github.com/user-attachments/files/16032784/Bugs.Problems.zip)

**Comment by dpolivaev** [comment]
Can you please explain exactly what you want, what you do, what you observe and that you expect?
When I open the attached, map I can not observe any malfunction. And I can not know how exactly you trigger it and what exactly you expect.

**Comment by Illegit** [comment]
Correct i tried the same map today and it was working, but yesterday for a full day and after closing and re-runnign the pc 2-3 times still I got the same problem... today instead smoothly. 
![Screenshot 2024-06-29 152324](https://github.com/freeplane/freeplane/assets/62674157/829ba6f4-f7d0-4c8a-89ae-4d2761fcaf53)



Only thing I can figure out is that even if I use 8G dedicated to FP in 1 pc and 2G on another PC, I may have some disruptions because of the pc memory engagement by FP? Normally I use 1 big external screen or 2, and this is consuming memory... and masp may have many formulas even to be calculated.

About the TCME saving please go to the other bug alert.

**Comment by dpolivaev** [comment]
1. Does drag and drop not work or the saving after you press the OK?
2. If you have node tag editors open  when you open TCME and save node tags, it can revert changes you do in the TCME because each editor has its own copy of the tag category data. Can it be the cause of your troubles? 
3. If you do not see any errors in the log file, I do not think you have any out of memory issues.

**Comment by Illegit** [comment]
> Does drag and drop not work or the saving after you press the OK?

saving with OK: in main level  it works in some sub-levels not (see image)
![Screenshot 2024-06-29 153839](https://github.com/freeplane/freeplane/assets/62674157/396fbd2e-83bd-4b31-a660-7d3d558e1be6)

drag&drop: now it works...


> If you have node tag editors open when you open TCME and save node tags, it can revert changes you do in the TCME because each editor has its own copy of the tag category data. Can it be the cause of your troubles?

Not, I do not use normally node tag editors, I use them only for removing tags from the node. They were all closed when I use TCME.


> If you do not see any errors in the log file, I do not think you have any out of memory issues.

Understood: the first time I will observe a strange behavior related to a possible memory problem I will check it and eventually, I'll send you my log file.

**Comment by Illegit** [comment]
[log - Copia.zip](https://github.com/user-attachments/files/16040335/log.-.Copia.zip)
here just in case.

**Comment by dpolivaev** [comment]
> saving with OK: in main level it works in some sub-levels not (see image)

Can you explain what exactly you do ? (e.g. I drag node "preferred" inside of Tags->Prototype and drop it on node "Tags->free") and it does not move and stays at the original place

**Comment by dpolivaev** [comment]
Yeah, your log file shows internal errors. But I do not know what you do to trigger them.

**Comment by dpolivaev** [comment]
I can know only as much as you can tell me.

**Comment by Illegit** [comment]
Some examples:
----
![Screenshot 2024-06-29 162425](https://github.com/freeplane/freeplane/assets/62674157/410c1a20-5696-44f5-8fcd-db5fd86d632c)
1) delete the free tag in the main level: using remove from the menu or delete key, in both cases result is OK after saving
![Screenshot 2024-06-29 162701](https://github.com/freeplane/freeplane/assets/62674157/23160288-4ccc-4bed-bd23-d9e46ee5b6d5)
----
2) try to move each single tag named free along the same level and the tag named ghost
![Screenshot 2024-06-29 163012](https://github.com/freeplane/freeplane/assets/62674157/cd350f2d-7dfa-404f-b5ea-cdb200da4076) 
1 free is possible,  the other and ghost not possible to be moved
---
3) there is even some sort of instability: see this case of moving the tag named tu
![Screenshot 2024-06-29 163638](https://github.com/freeplane/freeplane/assets/62674157/835c7273-aafd-4e91-9a74-f499feb76b43)
but after saving it was in the correct place 
![Screenshot 2024-06-29 164139](https://github.com/freeplane/freeplane/assets/62674157/b7fba764-cf75-4091-963e-ef2443322f8d)
---
4) create the tag named regular in a sub-level and tried to move down in the same sub-level: not possible
![Screenshot 2024-06-29 164359](https://github.com/freeplane/freeplane/assets/62674157/e9d5146a-d7ab-48b0-94fd-552508dfb8f7)
but after saving the surprise not drag  but 2 copies of regular in the new position
![Screenshot 2024-06-29 164702](https://github.com/freeplane/freeplane/assets/62674157/71660c09-0bb0-4454-be36-90056212b74e)
---
5) now I try to delete these 2 copies with delete key and ok, but no result
![Screenshot 2024-06-29 165054](https://github.com/freeplane/freeplane/assets/62674157/eec24344-a678-4ac8-b5f2-8031bc861c67)
---
6) now I move regular (the original) up one level: success, and after I move t again in the previous position and one of the copies of regular in the level will disappear.
![Screenshot 2024-06-29 165350](https://github.com/freeplane/freeplane/assets/62674157/0e8df6e5-f37e-4956-8108-19c731e80d47)
see with reference to note 2) that even ghost tag generated copies
![image](https://github.com/freeplane/freeplane/assets/62674157/2a4ee4a5-516c-4dc2-acdc-5284d60f604b)
---
7a) creating a new tag named why-not
![Screenshot 2024-06-29 170019](https://github.com/freeplane/freeplane/assets/62674157/719fb0b7-0f24-4c2e-9016-a4c4157b20f6)
pushing ok button, but
![Screenshot 2024-06-29 170247](https://github.com/freeplane/freeplane/assets/62674157/b785fb84-f166-4399-9b6c-60680ebdb92d)
 creating with editor menu
7b) same result if I do with the menu add sibling and so on.
---

Dimitry these are some examples working but mostly not always working.

**Comment by Illegit** [comment]
I tested FP 1.12.2_07: as the first impact every problem here listed has been solved. Many thanks.
