### ISSUE TITLE
FP 1.12.2_06: tag editor in node doesn't let copy tags correctly

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#1898]
**Describe the bug**
When copy a tag from a node tag editor (nTE) to another node nTE 
it is not any longer possible to cpy the tag as it is but only it creates a new tag
![Screenshot 2024-06-28 105854](https://github.com/freeplane/freeplane/assets/62674157/b6c38e82-1a27-442a-ba1e-a9079644805b)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] W
 - Version [e.g. 22] 10 and 11
 - Java Version FP 1.12.2_06

**Comment by dpolivaev** [comment]
I think you use it in a wrong way: you copy the tag and paste it inside a text field having a cursor.
Try to paste the tag not opening the text editing field directly in the tag table.

**Comment by Illegit** [comment]
[Bugs & Problems.zip](https://github.com/user-attachments/files/16032831/Bugs.Problems.zip)
I tried different methods but all with the same result (in the image above)
1) open the from editor and the to editor and drag the tag from to
2) open the from editor and the to editor and copy from and paste to
3) open only the from editor and drag to the to node
4) open only the from editor and copy to the to node

> I think you use it in a wrong way: you copy the tag and paste it inside a text field having a cursor.
Try to paste the tag not opening the text editing field directly in the tag table.
I do not understand to what case you are suggesting.


When I open the from nodeTagEditor with dragging or copying in anycase the from nodes generates a child node Tagname#ffaa00ff, if instead I open even the to nodeTagEditor it creates that Tagname#ffaa00ff as a new tag, and there are only two  points where you can paste that in a blank row or in the separator cell...
I need more explanation. Thanks
[Bugs & Problems.zip](https://github.com/user-attachments/files/16032976/Bugs.Problems.zip)

**Comment by Illegit** [comment]
> 'I think you use it in a wrong way: you copy the tag and paste it inside a text field having a cursor.
Try to paste the tag not opening the text editing field directly in the tag table.`

I have not understood it, what do you intend?

**Comment by Illegit** [comment]
Now I'm using FP 1.12.2_07, but I have not clear how to do it.

**Comment by dpolivaev** [comment]
Select any tag and click control+C
Select any other tag or empty cell and click control+V

**Comment by Illegit** [comment]
editor to editor: 
![Screenshot 2024-06-30 171359](https://github.com/freeplane/freeplane/assets/62674157/62a9bc59-a48f-4ffc-ad20-03716e119b14)


editor to node:
![Screenshot 2024-06-30 171718](https://github.com/freeplane/freeplane/assets/62674157/c1e6943d-5c5c-4b8a-8139-0ff327387285)


whtat I'd like is to hav  the same tag

Really I do not understand how to have the same tag.

**Comment by dpolivaev** [comment]
Preview 1.12.2_08
