### ISSUE TITLE
Multi layers overlap

### ISSUE THREAD

**Issue by Lawrence-of-AnKing** [freeplane/freeplane#1903]
One day I open the Freeplane, multi layers over in my screen, every time I move mouse on the bottom, it happend.

![](https://cdn.jsdelivr.net/gh/Lawrence-of-AnKing/imgBank@main/imgMD/2024/06/30/20240630-160927.png)

Windwos11, 1.11.14

**Comment by dpolivaev** [comment]
https://github.com/freeplane/freeplane/issues/1348
https://github.com/freeplane/freeplane/issues/536
https://github.com/freeplane/freeplane/issues/230
https://github.com/freeplane/freeplane/discussions/1755
