### ISSUE TITLE
Save folding state independently for each clone

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#1904]
freeplane-1.12.2-alpha-pre07

1. Make sure `Preferences…->Environment->Save->Save folding` is set to `Always` or `If map is changed`
2. Open the attached mind map and run `script1`
3. Observe that `ID_4` is **unfolded** and its clone in the branch of `ID_6` is **folded**
4. Save, close and reopen the mind map
5. Observe that both `ID_4` and its clone in the branch of `ID_6` are **folded**

#### Expected
Each clone retains its folding state set in step 3, i.e. `ID_4` is **unfolded** and its clone in the branch of `ID_6` is **folded**

[test-clone-serialization-4.xii.mm.zip](https://github.com/user-attachments/files/16045084/test-clone-serialization-4.xii.mm.zip)

**Comment by dpolivaev** [comment]
Preview 1.12.2_08

**Comment by macmarrum** [comment]
Awesome!
Thank you
