### ISSUE TITLE
Tags: confirmation dialog problems

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1907]
When the X is clicked in the Edit Node Tags window, after some change were made in the tags, I see two problems in the conformation dialog that pops up:

![image](https://github.com/freeplane/freeplane/assets/77707706/8d60b731-b1e1-43c4-8d21-df0709455e3f)

The buttons are not in English;

And, pressing Esc here is like pressing No. I would expect that it would be the same as pressing Cancel.

freeplane_bin-1.12.2-alpha-pre07

**Comment by dpolivaev** [comment]
I fixed the escape behavior. The language is lower priority for me.

**Comment by dpolivaev** [comment]
Preview 1.12.2_08
