### ISSUE TITLE
[Question] [Documentation request] Installing dictionaries when using AppImage

### ISSUE THREAD

**Issue by tonicebrian** [freeplane/freeplane#191]
Following https://www.freeplane.org/wiki/index.php/Spell_checker it says to download dictionaries and put them under resources/ortho but those folders don't exists when using an AppImage.

Could you update documentation to add instructions to add those dictionaries when using the AppImage?

**Comment by dpolivaev** [comment]
Could you try to show Freeplane.app package contents in the finder and copy the dictionaries into Freeplane.app/Contents/app/resources/ortho ? Please post how it works.

**Comment by tonicebrian** [comment]
In Ubuntu 20.04 finder only shows the Freeplane icon.

**Comment by dpolivaev** [comment]
I thought you had macos.
Actually, I do not know what you mean by AppImage and where you get the distribution.
Anyway you need to find where freeplane is actually installed and find the resource directory which is part of its installation.

**Comment by tonicebrian** [comment]
I'm sorry, I really was convinced that I was working with an AppImage but I have everything installed through a deb. I followed instructions and now it is working. Thanks.
