### ISSUE TITLE
Node text or attribute value "6D" is changed to "6"

### ISSUE THREAD

**Issue by frdrc2023** [freeplane/freeplane#1913]
**Describe the bug**
I noticed an issue when importing attributes with csv, but it seems to touch other parts of freeplane:
For any value of the type xD or xF, x being a number, freeplane transforms it into the plain number (numeric value).

**To Reproduce**
1. Create a new node
2. Type in 6F as text for the node (screenshot 1)
3. Freeplane shortens the text to 6 automatically (screenshot 2)

Same when I enter attribute name or value by "hand", or thought a script. The attribute value '6F' is transformed in numeric value '6'. It seems to happen with letters D and F (I havent tested it for others) and any int number.

**Expected behavior**
Is it a bug? Is there a way around it? Other text values like 6B don't show the same behavior.

**Mind map files**
[Nouvelle carte.zip](https://github.com/user-attachments/files/16105775/Nouvelle.carte.zip)

**Screenshots**
![Change text](https://github.com/freeplane/freeplane/assets/152307944/6b79bffc-9602-4c74-bdc4-98bb8dff9265)
![Result](https://github.com/freeplane/freeplane/assets/152307944/63ea7823-4b0f-467c-a867-b44759c57769)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version Freeplane 1.11.14
 - Java Version 8 (update 371) (build 1.8.0-b11)

**Comment by theelectricsoul** [comment]
@frdrc2023 
`'6F` should do the trick. But I do not know what is happening in the first please.

**Comment by frdrc2023** [comment]
It does, but freeplane shows the ', and in addition importing csv databases with field values 6C and 6B means... well, to change the database (still possible I guess, but not really satisfying)...

**Comment by dpolivaev** [comment]
See https://docs.freeplane.org/user-documentation/Data_recognition_and_data_formats.html

**Comment by frdrc2023** [comment]
> See https://docs.freeplane.org/user-documentation/Data_recognition_and_data_formats.html

Thank you Dimitry, it solved my issue:
I did turned off data recognition, which solved both issues with node text and import from csv to attribute values with a readLine() method.

I still hardly understand why a 6D is recognized as a number, but not 6C... it says in the before last paragraph:
"If for instance a number is followed by a word it's not considered a number." There might be something strange in the "/formats.xml" file, or a purpose for those parsing I don't understand yet ...
There might be some clues in the http://download.oracle.com/javase/6/docs/api/java/util/Formatter.html mentioned in the "/formats.xml" file, but the document seems out of my league for the moment. I'd appreciate if anyone had an explanation I can understand, I'd feel a bit smarter tomorrow morning?

Anyway, thanks again Dimitry for the straight to the point solution.

**Comment by euu2021** [comment]
> I'd appreciate if anyone had an explanation I can understand

The D and F are Java conventions for double and float data types. This is the google search you need, if you want to understand more:
![image](https://github.com/freeplane/freeplane/assets/77707706/6e108d8b-2bd2-430f-bedf-86e4aa9627fd)

**Comment by frdrc2023** [comment]
Thanks euu2021. It does make sence now :)
