### ISSUE TITLE
Tags: error uncategorized tags duplicate categorized tags

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1915]
In the example map, move the uncategorized xxx tag into the 111 tag:

![image](https://github.com/freeplane/freeplane/assets/77707706/1c99672c-f31f-4085-846f-8c740e0cc7fb)

Press OK, and FP freezes without error log.

[EXAMPLE bug tag cat 3.zip](https://github.com/user-attachments/files/16117746/EXAMPLE.bug.tag.cat.3.zip)

freeplane-1.12.2-alpha-pre08

**Comment by dpolivaev** [comment]
If a tag xxx appears in the categorized tags it must never appear as uncategorized tag. How have you created the situation depicted on the screenshot? If I open the map you attached I do not see xxx under the uncategorized tags.

**Comment by euu2021** [comment]
> If a tag xxx appears in the categorized tags it must never appear as uncategorized tag. How have you created the situation depicted on the screenshot? If I open the map you attached I do not see xxx under the uncategorized tags.

Steps:

- create a new map
- open Edit Tags
- create tag xxx
- create tag xxx::111
- click ok
- open Tag Category Manager. Tag xxx will be both under categorized and uncategorized:

![image](https://github.com/freeplane/freeplane/assets/77707706/c4f5ba5d-bcab-41df-a4f0-a48b04b7a21a)

**Comment by dpolivaev** [comment]
Preview 1.12.2_09
