### ISSUE TITLE
Tags: error when renaming tag that is both categorized and uncategorized

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1917]
first reported at https://github.com/freeplane/freeplane/issues/1905#issuecomment-2212068804

---

Steps:
- create a new map
- open Edit Tags
- create tag xxx
- create tag xxx::111
- click ok
- open Tag Category Manager
- rename the categorized xxx to xxx2:
![image](https://github.com/freeplane/freeplane/assets/77707706/1813a098-a21a-4bc4-948f-0a012f0311ac)
- click ok
- open Tag Category Manager
- rename the uncategorized xxx to xxx3
- click ok. Error happens

freeplane-1.12.2-alpha-pre08

**Comment by dpolivaev** [comment]
Duplicate of #1915

**Comment by dpolivaev** [comment]
Preview 1.12.2_09
