### ISSUE TITLE
FP 1.12.2_08: Message "locking of the map XXX failed. Acton Save as aborted

### ISSUE THREAD

**Issue by dpolivaev** [freeplane/freeplane#1918]
### Discussed in https://github.com/freeplane/freeplane/discussions/1916

<div type='discussions-op-text'>

<sup>Originally posted by **Illegit** July  7, 2024</sup>
The following message appears when I close FP (with that map still open):
![image](https://github.com/freeplane/freeplane/assets/62674157/b2a12102-7ece-4783-a03f-0f278b063086)
What I have to do to avoid this message?
Please note that the same map file in another FP installation doesn't create any message.</div>

**Comment by dpolivaev** [comment]
@Illegit I added logging, to the new preview 1.12.2_09. Please test it and upload the logs when you see the message again.

**Comment by Illegit** [comment]
Hi Dimitry, it has been solved with FP 1.12.2_09. Thank you. If the case I'll send you the log file .

**Comment by Illegit** [comment]
Hi, this error appeared again but with slightly different behaviour in FP 1.12.2_10:
1) there was an existing file XXX.mm in FP maps already opened (in the 1st pc)
2) I copied the update file named XXX.mm from a second PC and I copied in the first PC
3) FP in 1st pc asked to reload it: I confirmed
4) I changed something in the open map always with the name XXX.mm in the 1st pc, and I saved: here the message occurred

Below the log file
[log - Copia (2).txt](https://github.com/user-attachments/files/16322305/log.-.Copia.2.txt)

Please note that, after a 2nd save of the same file the message disappears, and if I close FP and reopen the XXX.mm map at the 1st save this message appears, from the 2nd save the message doesn't appear.

**Comment by Illegit** [comment]
Here the name of the file is "Tools Evolution"
