### ISSUE TITLE
Freeplane menu fonts are increased each time `File > Export > PDF` is used

### ISSUE THREAD

**Issue by ldmpub** [freeplane/freeplane#1920]
**Describe the bug**
Freeplane menu fonts are increased each time `File > Export > PDF` is used.

**To Reproduce**
1. Open a map in Freeplane
2. `File > Export Map` then choose PDF as exported file format
3. Wait ... Go back to Freeplane => you will see the changes: in Freeplane menu fonts are supersized 🧙‍♂️

Note: no error.

**Screenshots**

Menus with normal fonts size at Freeplane startup:
![Freeplane 1 - Menus with Normal Fonts size](https://github.com/freeplane/freeplane/assets/1452146/351e3bda-34bc-45c7-a8d8-8c8ce588327a)

Freeplane Menus with increased fonts size after only 3 PDF Exports of the same map:
![Freeplane 2 - Menus with Increased Fonts size afer 3 exports](https://github.com/freeplane/freeplane/assets/1452146/1b15c28f-dc74-4d94-8d00-3851d318811e)

**Mind map file**
On request.

**Desktop**
 - OS: Windows 10
 - Freeplane Version: **Freeplane 1.11.11**
 - Java Version: 21

![image](https://github.com/freeplane/freeplane/assets/1452146/43b6dcc6-0f36-4071-b230-6d4c07ccd5c2)

**Comment by dpolivaev** [comment]
I checked it with some random map on my Windows 10 with Java 21 and I can not see it here.
If you l like you can upload your map and your auto.properties so that I can try it with your map and your settings, otherwise I can only close the issue.

**Comment by ldmpub** [comment]
Perfect, I will try to reproduce on other PC and with other maps and will let you know here.

**Comment by ldmpub** [comment]
Hi @dpolivaev,

I've found the source of the issue
=> On 1 Windows 10 PC, **the display scale is customized (factor set to 120)**, causing the strange behavior of increasing Freeplane main menus font size are each time `File > Export > PDF` is used.

Here is the setting involved from the Windows control panel (sorry it's in french, in english it should be something like "_custom display scale factor_".
![Mise à l'échelle](https://github.com/user-attachments/assets/edbb40a8-c975-4497-ba84-4f375e36de27)

>  [!NOTE]
> **Freeplane install updated** from 1.11.11 **to `1.11.14`**, and the 🐛bug is still there => it looks like it's an old one 😋.

**Comment by dpolivaev** [comment]
Please check preview 1.12.2_11 alpha

**Comment by ldmpub** [comment]
@dpolivaev, I confirm => **you have fixed the bug** in the indicated preview version 👏.

**I close this issue** _(I regularly update Freeplane through Chocolatey)_

Many thanks for your work, you're a magician 🧙‍♂️ :
-  ✔You pay attention to fix all bugs, even minor ones like the one reported in this issue..
-  ✔I never have seen so quick and efficient answers from any, even senior, dev 🥳.

Thanks, thanks again, thank you.
