### ISSUE TITLE
Allow to uncategorize tags

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1922]
It's possible to move an uncategorized tag as a categorized tag:

Drop it into the Parent Tags Icon:
![image](https://github.com/user-attachments/assets/1841b4c4-5ba4-41ca-aa9d-5cb1afe65295)

And it becomes a top level category:
![image](https://github.com/user-attachments/assets/c576cd25-156d-4e3c-8ce3-2d1bbf800c6c)

I see that it can be useful in some situations, but it's relevant to be able to do the opposite movement, i.e., turning that tag into an uncategorized tag.

freeplane-1.12.2-pre09

**Comment by dpolivaev** [comment]
What should happen with node bbb::111 if you drag and drop node bbb into node Uncategorized Tags?
For me it looks like both node bbb and node 111 should become children of uncategorized tags, and all nodes bbb::111 should be replaced by 111. How do you see it?

And it is not quite easy to implement, but everything related to tag category management has quite complicated algorithms and data structures. Quite a challenge.

**Comment by dpolivaev** [comment]
Well, actually I could allow moving only leaf nodes into uncategorized tags, it would make it easier

**Comment by euu2021** [comment]
> Well, actually I could allow moving only leaf nodes into uncategorized tags, it would make it easier

Yes, I think this is enough. I don't see why someone would want to move a whole branch into Uncategorized Tags.

**Comment by dpolivaev** [comment]
Preview 1.12.2_11 alpha
Complete solution

**Comment by euu2021** [comment]
Thanks

**Comment by regis586** [comment]
Hi..
Hum... 
The application (V1.12.4) crashed while I was "dragging and dropping" the tags as categories and sub-categories...

**Comment by i-plasm** [comment]
> The application (V1.12.4) crashed while I was "dragging and dropping" the tags as categories and sub-categories...

@regis586  can you share exactly which steps you performed that would reproduce the issue leading to the crash? That would be helpful. I also had it crash yesterday when dragging and dropping some items (I had to use the Task Manager to kill the freeplane process), but unfortunately don't know the exact sequence of steps. Thanks.

**Comment by regis586** [comment]
> > The application (V1.12.4) crashed while I was "dragging and dropping" the tags as categories and sub-categories... > > @regis586 can you share exactly which steps you performed that would reproduce the issue leading to the crash? That would be helpful. I also had it crash yesterday when dragging and dropping some items (I had to use the Task Manager to kill the freeplane process), but unfortunately don't know the exact sequence of steps. Thanks.

Hi,
A good drawing is worth a thousand words... 
The bug happened again during the"*.bug-3.png". ![20240822-FreePlane-Tags-Bug-3](https://github.com/user-attachments/assets/1acb4c12-b0bf-46d7-bafd-053ed0e10536) ![20240822-FreePlane-Tags-Bug-2](https://github.com/user-attachments/assets/651fe429-d095-4ec6-8257-16362d283799) ![20240822-FreePlane-Tags-Bug-1](https://github.com/user-attachments/assets/e29278bc-43ee-41bf-bc83-65376379c8b2)

Just to clarify...I also killed the task (each time it crashed), but my Freeplane map remained displayed (?) on the screen... I had to close my session each time...

**Comment by regis586** [comment]
> > > The application (V1.12.4) crashed while I was "dragging and dropping" the tags as categories and sub-categories... > > @regis586 can you share exactly which steps you performed that would reproduce the issue leading to the crash? That would be helpful. I also had it crash yesterday when dragging and dropping some items (I had to use the Task Manager to kill the freeplane process), but unfortunately don't know the exact sequence of steps. Thanks.
> 
> Hi, A good drawing is worth a thousand words... The bug happened again during the"*.bug-3.png". ![20240822-FreePlane-Tags-Bug-3](https://private-user-images.githubusercontent.com/67907497/360367161-1acb4c12-b0bf-46d7-bafd-053ed0e10536.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTg3NDEsIm5iZiI6MTcyNDMxODQ0MSwicGF0aCI6Ii82NzkwNzQ5Ny8zNjAzNjcxNjEtMWFjYjRjMTItYjBiZi00NmQ3LWJhZmQtMDUzZWQwZTEwNTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA5MjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZWIxZWQ2ZTBmOTg0YWQ2MWU2Mjg0NTg2NGQyOWEwMzBmOTY1OTZjMjdkY2YxYjMyZjkwYzRjMmEwZTgzMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QYtvcINAvNxjH0r1yytQszLvAlIjca8BvM2FAIcgSN8) ![20240822-FreePlane-Tags-Bug-2](https://private-user-images.githubusercontent.com/67907497/360367168-651fe429-d095-4ec6-8257-16362d283799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTg3NDEsIm5iZiI6MTcyNDMxODQ0MSwicGF0aCI6Ii82NzkwNzQ5Ny8zNjAzNjcxNjgtNjUxZmU0MjktZDA5NS00ZWM2LTgyNTctMTYzNjJkMjgzNzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA5MjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYTYwNTdiOTgyYzc2MmU4YjJlMDdiMjFlYzQ0MjMyYWI4ZTFlODM4MWU1NmUzZWE5ZGIwZmM5YTM4NmE2NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pGTYWwlIr14pQN9HO_NHd2Q-G3ZPlKWuZ3q1nt0UauA) ![20240822-FreePlane-Tags-Bug-1](https://private-user-images.githubusercontent.com/67907497/360367175-e29278bc-43ee-41bf-bc83-65376379c8b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTg3NDEsIm5iZiI6MTcyNDMxODQ0MSwicGF0aCI6Ii82NzkwNzQ5Ny8zNjAzNjcxNzUtZTI5Mjc4YmMtNDNlZS00MWJmLWJjODMtNjUzNzYzNzljOGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA5MjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNTBlMjVjYjM3YjIxNTU1MmYzMTZiOGQyY2JmYjlhYTQzN2U3ZDI2NmEyYTY4MDY5MzdiODU2YTA2ODc0MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xI6ML6Yblngff8urpVIHEXdc5-LpY9XNAyCULZOH-Ks)
> 
> Just to clarify...I also killed the task (each time it crashed), but my Freeplane map remained displayed (?) on the screen... I had to close my session each time...

I did it again, but this time I "validated" after each entry (drag and drop)... and I made sure to save my map each time. And no more crashes!
![20240822-FreePlane-Tags-Bug-5](https://github.com/user-attachments/assets/964d2fe4-8174-4f33-81ec-9719e61f0d04)
![20240822-FreePlane-Tags-Bug-4](https://github.com/user-attachments/assets/e053543f-2b08-4d36-90d3-e685c020507e)

**Comment by dpolivaev** [comment]
Can you please upload the map and describe the steps leading to the bug?

**Comment by dpolivaev** [comment]
@regis586 Can you please upload the map and describe the steps leading to the bug?

**Comment by dpolivaev** [comment]
@regis586  I could reproduce the bug based on your screenshots. Actually, Freeplane was not "crashed" but "frozen".
