### ISSUE TITLE
FP 1.12.2_09: missing short cut in menu of category tags editor

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#1924]
**Describe the bug**
the tag category editor is missing some shortcuts:
![Screenshot 2024-07-15 215644](https://github.com/user-attachments/assets/d0e8b205-8c4d-4837-bd05-d36c80040bbb)
1) insert into selected nodes (previously it was ctrl+I)
2) remove from selected nodes

or please explain how to create these shortcuts.
Thankyou

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  W11
 - Version [e.g. 22]  FP 1.12.2_09
 - Java Version above

**Comment by dpolivaev** [comment]
Preview 1.12.2_10
