### ISSUE TITLE
Option to synchronize selection across all visible views

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1930]
I propose a very practical and excellent idea, I hope you will pay attention to it.

First, you should familiarize yourself with the terms that I defined myself. Well, pay attention, I explain the idea according to these terms.
🟢 Terms:
-Imagine a person named Ali, he has two brothers named Hamid and Muhammad. He has three uncles. He also has three children. Look at the image below. When I say in my explanation, the column of fathers and uncles, or the column of Ali and brothers, or the column of children, you can see these columns respectively on the map.

![image](https://github.com/user-attachments/assets/e36fa6c1-352c-4f9b-b4bf-6ba3f965ef48)

2-Three orange arrows show the color of the columns or levels. Pay attention that level 3 is lower than level 1. Because it is farther from the root.
3-  Look at the image below: By implementing the idea, you will have twin panels, which I call the main and auxiliary or secondary panels. The main panel is exactly like the FP maps, and the secondary or auxiliary panel is different and has a different function.

Even now, two views of the map can be seen side by side, but there is no connection between these two views, like two bricks side by side that have no connection with each other, they are just placed next to each other.
By implementing this idea, many connections are established between two views of the map.

![image](https://github.com/user-attachments/assets/eeb67996-becc-422d-b11f-b1c9826c02a9)

🟢🟢 Why this idea came up:
I wrote some questions in FP. All questions were in one column or level. The answer to all those questions had many branches and nodes.
 When I checked the answer nodes, I couldn't see any questions that were all level 1. I was thinking that I wish it was possible to see those questions in a separate  and I could easily select that particular question whenever I wanted. . Similar to bookmarks in a PDF file, you can always view the entire level of bookmarks in the side panel.

another point:
One of the meanings of the mind map is to be able to obtain information about the structure and framework of a number of items and their relationship with each other in one moment.
I give an example:
Look at the image below:
![image](https://github.com/user-attachments/assets/3bea13fd-4cf6-4aca-8927-42c40d57ca26)

Imagine the "colors" node.
 In the map, three things are important for concentration: simultaneously seeing the nodes of brothers, the nodes of fathers and uncles, and the nodes of children.
I drew a line around these things.

I will explain more later, but if the "Ali" node is selected:
 The uncles or brothers or both of them are displayed in the auxiliary panel depending on the modes set by the user.

Next point:

Suppose we have a node named "A".
The problem is that if the map has many nodes and branches, or if all the brothers of "A" are unfolded, or if node "A" has many children (for example, 30 children), in these cases, the brothers of node "A" are not seen. 

Another problem is that the uncles of the selected node are not seen on the screen at the same time in many cases. Even the father of that node is not obvious in many cases if the `Scroll map after selecting a node` setting is active.

 This idea can have many side benefits in addition to solving the above problem. To get to know the idea briefly, imagine the bookmarks panel of a PDF display software and the navigation panel of Windows Explorer and Microsoft Word. Imagine how helpful these tools can be and create a lot of mental focus for the user.
We are looking to create a panel that can do very interesting things.

🟢🟢  Some benefits of this idea:
• Ability to see father, uncles and brothers at the same time.
• More mental focus on the map - like the help panels in some of the mentioned software.
• Ease of copying and pasting nodes in the map with minimal folding or unfolding of nodes.
• If the distance between the brothers is large, copying and pasting is difficult, but with this idea it is very easy to do.

• Very easy navigation on the map.

• New navigation mode in the auxiliary panel among layers and columns using the four buttons for the direction of the view.

• Improve the efficiency of the `Scroll map after selecting a node`  option. This option takes the selected node to the beginning of the screen. (In this case, the father and uncle of that node are not displayed, but the father of that node can be viewed using the auxiliary panel.

• When you select a node in the auxiliary panel, it causes an automatic scrolling to occur in the main panel. It means that you have selected the desired node and set the map so that the most nodes can be seen.

• Prevents many opening and closing. You don't have to worry about how many nodes of the map are open or closed. The side panel helps you.

🟢🟢 How to create two panels?

FP has a feature that you can display two maps on the screen at the same time or display one map in such a way that half of the screen shows that map and the other half of the screen shows the same map.

 The way to do it is to mount the idea on one of these two panels. Whenever we implement the option of twin panels, our idea will be implemented, but the basis of the work is to display two maps at the same time in FP. In fact, it is two real views of the map that have an effect on each other. And each has its own characteristics.

🟢🟢Rules of twin panels:

1- Four different modes of displaying nodes in the auxiliary panel: 1- Show only brothers 2- Show father and uncles 3- Show brothers and father and uncles 4- Lock on the selection column.
 You can tell FP to lock on that column in the auxiliary panel by dragging a node from the selected column or layer to the mode 4 icon.

• Relationship between two panels:

•  Whenever we click on a node in the main panel, for example, if we have activated the  mode 2, the father and uncle of that node will be displayed in the auxiliary panel. 

•Whenever another node is selected in the main panel, the necessary changes to display fathers, uncles, etc. are updated in the auxiliary panel.

•   If one of the uncles is clicked in the auxiliary panel, his children will be displayed in the main panel.
•  etc.

• Sometimes the nodes are very long, so the user has a setting that allows him to choose two modes: display 5 words from each node or fully display the nodes (if the number of nodes is small, the full display will be automatic)

 The auxiliary panel does not always show more than one level or at most two levels (when the display mode of brothers, uncles and father is active).
 By selecting a node from the sub-map, all its children will appear in the main panel. The map should appear in the main panel in such a way that the most nodes are displayed (i.e. automatic scrolling).
 If mode 1 is selected, i.e. "only brothers" display mode, in the auxiliary panel, in addition to the display of brothers, the father of the node selected in the main panel will be shown in a separate color at the top of all brothers.

• Higher or lower levels are shown in the auxiliary panel with the right and left arrow keys. In this case, the highest node of the displayed level must be defined by FP to display its children in the main panel.
This is a new navigation mode in auxiliary panel. If you imagine it well, this navigation with right and left and up and down arrow keys is very useful.

**Comment by aaa1386** [comment]
Microsoft Word software, PDF file viewers, Windows Explorer, etc. have created a panel for more focus.
If the idea expressed in FP is implemented, we will benefit from the advantages of the mentioned software, but many more benefits will be created in FP.

**Comment by aaa1386** [comment]
A point to better understand the necessity of this idea.
Suppose you have made a PDF with ten bookmarks in one level.
PDF viewer software has an interesting function that is very logical.
They have a panel that is always visible to the user for bookmarks and a main panel for displaying the selected bookmark text.
It doesn't matter how much the contents of a bookmark are organized and charted or not? The important thing is that you have ten bookmarks that you always have to scroll through so it should always be visible to you.
Although an FP map is made up of many nodes, this logic exists in FP maps, between nodes and branches.
 Sometimes a level or column like those ten bookmarks that we said should always be visible to the user. This level or column of nodes has children and branches. Consider all these children and branches as the text of that bookmark. In the idea that was expressed, the auxiliary panel works like the bookmarks panel in the software that shows the PDF file. Of course, this idea is much more flexible and attractive than other software.

The existence of this idea makes the user unconsciously encouraged and forced to create a clearer logical connection between the nodes.

Even if sometimes there is no clear logical connection between the auxiliary panel and the main panel, the least effect of this auxiliary panel is in easy navigation between maps and moving nodes between maps.

In my opinion, the existence of this idea makes the FP map have a very beautiful and attractive logic.

**Comment by aaa1386** [comment]
another point :
By implementing this idea, nothing is lost from the environment that shows the map, FP works exactly as before in the main map. This idea just adds an auxiliary panel to the map, which is very useful.

**Comment by aaa1386** [comment]
Another point:
One of the important applications is to solve the problem of long distance between nodes, which exists in many cases.
We know that many nodes have a logical connection and dependence on each other, that's why we should always observe them simultaneously. But the long distance between these nodes makes us unable to observe them at the same time.
 I have shown the presence of a large distance in the image below.
This idea solves this problem to a large extent. Especially since the auxiliary panel shows the items that usually have the most and closest logical connection to each other. Like brothers, uncles, or the user's favorite column.
 Although folding the nodes is a solution to view the nodes at the same time, but in many cases it is not the best solution because you have to move from your node and branch to the root and get closer to be able to close the nodes. Sometimes you don't want to lose the extent of the map while you also need to see some nodes together.

![image](https://github.com/user-attachments/assets/28bdd55a-5cce-4abf-885c-bd076d72554e)

**Comment by aaa1386** [comment]
If it is possible to create an auto-hide feature for the auxiliary panel, it will be great.

**Comment by euu2021** [comment]
I suggest that you open a discussion. The topic is too complex for a feature request ticket.

For example, I understand the "problem of long distance between nodes", but I don't understand this situation:

> Why this idea came up:
I wrote some questions in FP. All questions were in one column or level. The answer to all those questions had many branches and nodes.
When I checked the answer nodes, I couldn't see any questions that were all level 1. I was thinking that I wish it was possible to see those questions in a separate and I could easily select that particular question whenever I wanted. . Similar to bookmarks in a PDF file, you can always view the entire level of bookmarks in the side panel.

**Comment by dpolivaev** [comment]
I want to try something here.

**Comment by dpolivaev** [comment]
preview 1.12.2_11 alpha
View->New map view
fold/unfold all nodes on the second view and arrange views
activate View->View settings->Synchronize selection

**Comment by aaa1386** [comment]
> preview 1.12.2_11 

Thank you for your attention to this idea.
But the "Synchronize selection" option implements a small amount of the expressed idea.
In addition, it has many problems, especially sometimes in different folding or unfolding modes, it does not work in the view that is activated and it works in the opposite view that is not active.



https://github.com/user-attachments/assets/ee0b8a58-6f17-4588-907d-513cacb717a1


https://github.com/user-attachments/assets/73376977-f83f-4c80-b953-2935e1c0a018


https://github.com/user-attachments/assets/c9bdb4e0-81e5-43c9-ba04-328f3050495e

There are many such errors.
Currently, despite these errors in folding or unfolding in the active view, this option cannot be used.

**Comment by aaa1386** [comment]
@dpolivaev        Please visit page 1925. I reported an error.

**Comment by dpolivaev** [comment]
In all recent video examples I see no errors. Could you please explain what you think is wrong?

**Comment by dpolivaev** [comment]
Generally, Freeplane does not make any difference between full panel and auxiliary panel, it only makes difference between currently selected panel and other visible panels where the selection is adjusted.

**Comment by aaa1386** [comment]
> In all recent video examples I see no errors. Could you please explain what you think is wrong?

Watch the second video:
I have activated the right panel. When I select node "1". That node is not selected in the left panel.

Watch the third video:
I have activated the left panel. When I select node "1". And I fold it, this node does not fold in the left panel which is active, but it folds in the right panel which is not active.

Watch the first video:
I have activated the right panel. When I press the right or left view direction buttons, the map moves in the left panel.

**Comment by aaa1386** [comment]
The right and left panels should work independently of each other, for example, when the right panel is active, all folding and unfolding modes should be done only on this panel. The other panel should only automatically select the nodes or branches that match the nodes of the right panel, and not do anything else.

**Comment by aaa1386** [comment]
> In all recent video examples I see no errors. Could you please explain what you think is wrong?

If I have activated the right panel, I select the first node in the right panel and fold it, that node will be folded in the same panel, so it works correctly. I select the next group in the right panel and fold it, that node is not folded in the right window, but it is folded in the left window, this means an error. If I select the next node from the side panel and fold it, the same node will be folded again in the right panel.
It means that it works intermittently.

**Comment by dpolivaev** [comment]
I am confused, but I see no errors.
