### ISSUE TITLE
Add an import export to json format with text and relationships only

### ISSUE THREAD

**Issue by Upcycle-Electronics** [freeplane/freeplane#1931]
**Is your feature request related to a problem? Please describe.**
I would like an easier way to import and export a mind map to use with open source offline AI where the only feature that is imported and exported is the data within each cloud and its relationship in the map.

**Additional context**
I'm no dev and barely functional in this space. The tools to process and generate json already exist within Oobabooga Textgen Webui (open source AI model loader and text inference server that works with open source offline AI). I've been writing a book for fun and building out a science fiction universe mostly using a LLM to bounce ideas off of casually in long conversations. In an ideal world, I would be able to give the model my mind map in json format, and a long previous conversation. Then I could prompt the model to further expand the json with the new details laid out in the conversation, or describe any discrepancies. It would also help the model understand the story context much better if the story was described in structured text, but would help me to see the story structure in a mapped visual form. This would be quite helpful in the human practical sense of accelerated task management and organization. It would also help with diagnosing what and how the model being used understands context, concepts, and relationships enabling further corrections and contextualization of information by someone with less experience and technical skill.

Regardless, thanks to everyone that is involved with this project. You've made my disabled life a little better with a tool I find useful.

**Comment by macmarrum** [comment]
You can try my libraries for JSON import/export:

1. Save [Export.groovy](https://raw.githubusercontent.com/macmarrum/freeplane-scripting/main/src/lib/io/github/macmarrum/freeplane/Export.groovy) and [Import.groovy](https://raw.githubusercontent.com/macmarrum/freeplane-scripting/main/src/lib/io/github/macmarrum/freeplane/Import.groovy) to `<user-dir>/lib`
2. Save [exportToJsonClpbSkip1.groovy](https://raw.githubusercontent.com/macmarrum/freeplane-scripting/main/src/scripts/exportToJsonClpbSkip1.groovy) and [importFromJsonClpb.groovy](https://raw.githubusercontent.com/macmarrum/freeplane-scripting/main/src/scripts/importFromJsonClpb.groovy) to `<user-dir>/scripts` – you can adjust the menu location by changing `ON_SINGLE_NODE="/menu_bar/Mac1/Export"`
3. Restart Freeplane

**Note**: *You can find your `<user-dir>` in Freeplane `Tools -> Open user directory`*

The scripts will use Clipboard to transfer your JSON (will copy to Clipboard on export and paste from Clipboard on import).

You can adjust which properties of a node are to be exported; see `settings` in [exportToJsonClpbSkip1.groovy](https://raw.githubusercontent.com/macmarrum/freeplane-scripting/main/src/scripts/exportToJsonClpbSkip1.groovy)

**Comment by Upcycle-Electronics** [comment]
Thanks @macmarrum for the reply and scripts. 

Perhaps I do not understand what you mean by, "you can adjust the menu location by changing ON_SINGLE_NODE="/menu_bar/Mac1/Export"" and this means something more than I think, or perhaps something about my setup is not correct. I am using the flatpak version of Freeplane and copied both the libraries and scripts into the respective user directories as instructed. When I try to export using the Mac1 menu after restarting Freeplane, I only get a "null' result in the output. The logs are not reporting an error. When I launch Freeplane from the terminal using the flatpak run command there are a couple of warnings that are perhaps related, but I'm not sure what I am looking at here:

<details>
<summary>~$ flatpak run org.freeplane.App</summary>

```
WARNING: package sun.swing.shell not in java.desktop
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.freeplane.launcher.Launcher (file:/app/Freeplane/freeplanelauncher.jar)
WARNING: Please consider reporting this to the maintainers of org.freeplane.launcher.Launcher
WARNING: System::setSecurityManager will be removed in a future release
Knopflerfish OSGi framework launcher, version <unknown>
Copyright 2003-2020 Knopflerfish. All Rights Reserved.
See http://www.knopflerfish.org for more information.

Created Framework: org.knopflerfish.framework, version=8.0.11.
Background mode.
Jul 28, 2024 4:59:15 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://1:1/freeplane.properties
Jul 28, 2024 4:59:15 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://1:2/org/freeplane/main/application/
Jul 28, 2024 4:59:15 PM org.freeplane.core.util.LogUtils info
INFO: Listening for application instances on socket 42489
Installed: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.bugreport (id#2)
Installed: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.formula (id#3)
Installed: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.jsyntaxpane (id#4)
Installed: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.latex (id#5)
Installed: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.markdown (id#6)
Installed: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.openmaps (id#7)
Installed: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.script (id#8)
Installed: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.svg (id#9)
Started: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.bugreport (id#2)
Started: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.formula (id#3)
Started: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.jsyntaxpane (id#4)
Started: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.latex (id#5)
Started: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.markdown (id#6)
Started: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.openmaps (id#7)
Started: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.script (id#8)
Started: reference:file:/app/Freeplane/plugins/org.freeplane.plugin.svg (id#9)
Jul 28, 2024 4:59:15 PM org.freeplane.core.util.LogUtils info
INFO: language resources for en found
Jul 28, 2024 4:59:15 PM org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.11.6; freeplane_xml_version = freeplane 1.11.5
git revision = f7f4bfc921430d8cc1b8f6d824405b7e80bdc437 dpolivaev 2023-08-22T18:01:36Z
java_version = 17.0.7; os_name = Linux; os_version = 6.9.8-200.fc40.x86_64
Jul 28, 2024 4:59:15 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date format M/d/yy
Jul 28, 2024 4:59:15 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date time format M/d/yy, h:mm a
Framework launched
Jul 28, 2024 4:59:16 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://3:1/org/freeplane/plugin/formula/defaults.properties
Jul 28, 2024 4:59:16 PM org.freeplane.core.util.LogUtils info
INFO: extending script's classpath by [/home/$USER/.var/app/org.freeplane.App/config/freeplane/1.11.x/compiledscripts, /home/$USER/.var/app/org.freeplane.App/config/freeplane/1.11.x/lib]
Jul 28, 2024 4:59:16 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://8:1/org/freeplane/plugin/script/defaults.properties
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.freeplane.plugin.script.ScriptingRegistration (bundle://8)
WARNING: Please consider reporting this to the maintainers of org.freeplane.plugin.script.ScriptingRegistration
WARNING: System::setSecurityManager will be removed in a future release
Jul 28, 2024 4:59:16 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
Jul 28, 2024 4:59:16 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [groovy]
Jul 28, 2024 4:59:16 PM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
Jul 28, 2024 4:59:18 PM org.freeplane.core.util.LogUtils info
INFO: menu items to execute: []
```
</details>

**Comment by macmarrum** [comment]
> Perhaps I do not understand what you mean by, "you can adjust the menu location by changing ON_SINGLE_NODE="/menu_bar/Mac1/Export"" and this means something more than I think

You can ignore this. It's only about where the script appears in the menu.

> I am using the flatpak version of Freeplane 

I have no experience with Flatpak. If all else fails, you can download [freeplane_bin-1.11.14.zip](https://sourceforge.net/projects/freeplane/files/freeplane%20stable/freeplane_bin-1.11.14.zip/download), unpack it and run `./freeplane.sh` – provided you have `java` available in your `PATH`

> The logs are not reporting an error.

No errors in logs indicates to me correct execution.

> I only get a "null' result in the output

Maybe there was nothing to export. Did your node have any children? The export script skips the selected node (`Skip1`).

> When I launch Freeplane from the terminal using the flatpak run command there are a couple of warnings that are perhaps related, but I'm not sure what I am looking at here

The warnings are unrelated.

---

You can try to copy the following to the clipboard and run `Mac1->Import->Import From Json Clpb`

```json
{
    "Pangram": {
        "@link": "https://en.wikipedia.org/wiki/Pangram",
        "@style": "AutomaticLayout.level.root",
        "English": {
            "@backgroundColor": "#ccccccff",
            "@textColor": "#000066ff",
            "The quick brown fox jumps over the lazy dog": null
        },
        "French": {
            "Portez ce vieux whisky au juge blond qui fume": {
                "@details": "Take this old whisky to the blond judge who is smoking",
                "@note": "uses each basic consonant once, though not any letters with diacritics."
            }
        },
        "German": {
            "Victor jagt zwölf Boxkämpfer quer über den großen Sylter Deich": {
                "@details": "Victor chases twelve boxers across the Great Levee of Sylt",
                "@note": "contains all letters, including the umlauted vowels (ä, ö, ü) and ß. The letter y is limited to loanwords and proper names like Sylt"
            }
        },
        "Italian": {
            "Pranzo d'acqua fa volti sghembi": {
                "@details": "A lunch of water makes twisted faces",
                "@note": "has 26 letters and includes all 21 letters found in native Italian words. It does not include the five letters which are not found in any Italian words, except for some loanwords: j, k, w, y, and x.: Cantami o Diva del pelide Achille l'ira funesta. (Sing to me, O Diva of the hairy Achilles, the raging wrath.) has 39 characters without considering any apostrophe and space; it's used in Microsoft Windows operating system if the language is set to Italian (Italiano)"
            }
        },
        "Spanish": {
            "Benjamín pidió una bebida de kiwi y fresa. Noé, sin vergüenza, la más exquisita champaña del menú": {
                "@details": "Benjamin ordered a kiwi and strawberry drink. Noah, without shame, the most exquisite champagne on the menu",
                "@note": "uses all diacritics and the foreign letters k and w.: El veloz murciélago hindú comía feliz cardillo y kiwi. La cigüeña tocaba el saxofón detrás del palenque de paja. (The quick Indian bat was happily eating cardillo and kiwi. The stork was playing the saxophone behind the straw palenque.) contains 2 sentences and 92 letters; it's used in Microsoft Windows operating system if the language is set to Spanish (Español)."
            }
        }
    }
}
```

**Comment by Upcycle-Electronics** [comment]
Thanks so much. I had a dumb moment I guess. I had assumed export defaulted to the entire presently loaded map. After you mentioned "The export script skips the selected node (Skip1)." My mistake was obvious. This works now. Thanks again.
