### ISSUE TITLE
Image and clarity of the mind map through three image sizes Icon - Thumbnail - normal

### ISSUE THREAD

**Issue by toschroe** [freeplane/freeplane#1933]
**Is your feature request related to a problem? Please describe.**

**Additional context**

My image handling so far only works with images at the end of a branch. First there is a node with the text "Image" as a warning, then a thumbnail-sized image and then one in normal size.
With this I want to achieve:
- that the clarity of the mind map is not disturbed by large images
- that images are shown in exactly the size/smallness that seems to me to be a good compromise

---
![image](https://github.com/user-attachments/assets/0c6ec8ec-60ac-4942-9874-fcf6670c924b)

The idea is now that an image can be shown in three variants. The first is an icon, the second a thumbnail and the third the image in normal size.

Advantages
- This means that image nodes can be recognized by their icon,
- can be anywhere in the tree
- and do not take up much space.
Actions such as a mouse hover would show the thumbnail and another action would show the image in normal size.

Handling
There is still potential for coming up with ideas for:
- a suitable icon for this special image display (perhaps similar to the note icon)
- the actions for switching between the three image displays. A hover for thumbnail and a wait or shift hover for normal size, for example.
- an idea of ​​how the desired permanent status of the image can be set (perhaps by clicking?)

**Comment by euu2021** [comment]
Interesting! I don't like to leave the images big, because they take up too much space, so I need to resize every time I want to see the image better. Having an automatic enlargement on mouse hover, or a tooltip that shows the enlarged image, would be nice.

**Comment by i-plasm** [comment]
I just published the "[ImgInspector](https://github.com/freeplane/freeplane/discussions/1948)" script, which can help solve some of the problems of having big images on your mindmaps. It allows the user to set the zoom as small as wanted, because it displays a convenient full-size preview popup when hovering over the image. Like what @euu2021 mentioned.



![demo_ImgInspector](https://github.com/user-attachments/assets/48e02fd9-0eb1-4cf3-b96b-0917332e38c4)

**Comment by toschroe** [comment]
@i-plasm Yes, that's what I wanted, thank you, great work!

**Comment by toschroe** [comment]
The case is solved and can be closed.
