### ISSUE TITLE
Mindmap with Latex - Export to PDF corrupt formulas

### ISSUE THREAD

**Issue by afriesinger** [freeplane/freeplane#1937]
### Discussed in https://github.com/freeplane/freeplane/discussions/1912

<div type='discussions-op-text'>

<sup>Originally posted by **afriesinger** July  3, 2024</sup>
I created a mind map with a lot of formulas. Written in Latex. in Freeplane everything is nicely shown. 
When i export the mind map to pdf. All the symbols are replaced by random signs and letters. Even normal Latex text like the word "fluid" in the example, isn't exported correctly. 
For me it looks like that the latex font isn't applied correctly during export. 
![grafik](https://github.com/freeplane/freeplane/assets/76171462/1ae4e65f-d6cb-4914-a72d-d2c2030c5e6d)
</div>

**Comment by edbeee** [comment]
I'm facing the similar issue.
Pdf screenshot:
![image](https://github.com/user-attachments/assets/d955c351-3443-4c93-a0ba-0295875c4432)

freeplane screenshot:
![image](https://github.com/user-attachments/assets/01b55f85-7542-494f-b4f5-b40ba5cef34d)


when exported to png:
![image](https://github.com/user-attachments/assets/b2359e76-ff71-4bed-841f-3c6d4ff52b0b)




@dpolivaev could you please have a look on this?
thank you a lot🥰

**Comment by dpolivaev** [comment]
@edbeee please upload your mind map, I generally always need mind maps to reproduce reported issues and test bug fixes.

**Comment by dpolivaev** [comment]
I tried it and can't reproduce. Which OS and which PDF viewer do you use?

**Comment by edbeee** [comment]
@dpolivaev sorry I wasted your time by not attaching the files. I'm attaching the mind map in Zip and the pdf.

I use windows 10 pro as OS. And I use adobe acrobat and sometimes MS Edge browser to open the pdfs.


I hope there will be a solution.
Thank you @dpolivaev for you great efforts to maintain this amazing app. I'm really fascinated by the features.

[New Mindmap.zip](https://github.com/user-attachments/files/17174411/New.Mindmap.zip)
[pdf version.pdf](https://github.com/user-attachments/files/17174412/pdf.version.pdf)

**Comment by dpolivaev** [comment]
Thank you, I can see the problem now and confirm that my fix works.

**Comment by afriesinger** [comment]
HI @dpolivaev , 
could you explain the fix. Will it be in the next release or is there some "trick" 
I am also on WIN 10 pro, 
Java 1.8.0_401
Freeplane 1.12.6

**Comment by dpolivaev** [comment]
Just wait, the next preview should get the fix.

**Comment by dpolivaev** [comment]
Preview 1.12.7_01
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

**Comment by afriesinger** [comment]
@dpolivaev 
Tested it today with the preview version. 
But for me it still doesn't work. 

Attached the small test file. 
System: Windows 
Java 1.8.0_401
Freeplane 1.12.7

Pdf generation by the File -> Export Menue. 
[Latex test.zip](https://github.com/user-attachments/files/17269585/Latex.test.zip)

any Idea whats the issue?

**Comment by dpolivaev** [comment]
Preview 1.12.7_02

**Comment by afriesinger** [comment]
Thanks. Now it works
