### ISSUE TITLE
Disable "direct" and "delayed" node selection while the mouse is moving.

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1938]
This idea makes a big difference in the two node selection modes "direct" and "delayed".
Check out the video below as the nodes are selected like crazy when the mouse is moving.

https://github.com/user-attachments/assets/0356ce5d-e2c2-4db5-84d2-733247baed17

**Comment by aaa1386** [comment]
This idea avoids too much unwanted selection and cluttering the user's focus.
Because of this lack, I sometimes make mistakes in choosing nodes.

**Comment by aaa1386** [comment]
The correct state is when the mouse stops:
1- In "Direct" mode: FP will select that node immediately.
2- In "delay" mode: after the set period of time, FP selects that node.

**Comment by dpolivaev** [comment]
You can use delayed selection with longer delay. It is configurable.

**Comment by dpolivaev** [comment]
You don't need to mention my name here.

**Comment by dpolivaev** [comment]
I do not understand your last message at all.

**Comment by aaa1386** [comment]
There is more problem in "Auto Extend" mode. It is not important for other places.
If the user chooses the "direct" mode, can FP automatically create some delay in the node selection in the "auto extend" mode?

**Comment by aaa1386** [comment]
Is it clear now?

**Comment by dpolivaev** [comment]
No, I do not understand how you mean " can FP create some delay". Do you need the delay? If yes, what for? Does FP delays anything?

**Comment by aaa1386** [comment]
I like the direct mode, but I can't choose it for two reasons, because if I enable the "auto expand" mode, I have no control over the selection of nodes.
The second reason is that I use the "auto map scrolling" mode, which means that the map scrolls automatically by selecting each node. In this case, with the movement of the mouse, the nodes are selected like crazy, and the map is always in movement and scrolling mode. This makes me lose my concentration completely.
I just found out that I have no choice but to select the "delayed" mode by setting a longer time to delay node selection.

**Comment by aaa1386** [comment]
I will end the discussion. The "delayed" mode also works very well with the setting of 200.
