### ISSUE TITLE
Bigging some icons that are too small.

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1939]
Do you have a way to adjust these icons? It is very small.
My monitor has a high resolution, but even with a laptop with a resolution of 1080, these icons are small.

  I've checked all the settings and can't find a way to make these icons bigger.
There is no shortcut for these icons.
So it is very difficult to use them.

![image](https://github.com/user-attachments/assets/8a48e164-2aac-4644-9767-d98c3512d3a6)

**Comment by dpolivaev** [comment]
preview 1.12.2_13

**Comment by aaa1386** [comment]
Thank you very much.
