### ISSUE TITLE
Some bugs in auto scrolling when a node is selected.

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1944]
FP has a function for each node: when some value of the node is visible on the screen and some value is not visible, when we select that node, it automatically scrolls to display the node in full.
But when the node is larger than the width of the display, when we select that node, it does not perform well. Look at the two images below, the word "AAA" is the beginning of the text inside the node. When scrolling happens, the beginning of the node should be displayed, but FP does not.
Before selecting the node.

![image](https://github.com/user-attachments/assets/3faa22b2-e275-404e-828c-c4ff0edcc4b7)

After selecting the node.
![image](https://github.com/user-attachments/assets/b3b2a6b0-a03b-45c0-964c-af56f0980b97)

**Comment by aaa1386** [comment]
The second bug:
Look at two pictures :

First picture: the node is minimized.

![image](https://github.com/user-attachments/assets/8a22d168-5974-47bf-b47f-e7e5a1d0c5c0)


The second photo is when the node is removed from the minimize mode.
See auto scrolling is not done.
![image](https://github.com/user-attachments/assets/e25098d8-6743-469a-b0e1-898b22f95617)

**Comment by dpolivaev** [comment]
Make you nodes smaller. I do not think that handling nodes of the size larger than screen should be supported.

**Comment by aaa1386** [comment]
> The second bug: Look at two pictures :.....

  This problem exists even if the nodes are small.
Is it not possible to do something about the second case?

Some of the cases I report are just to make FP better and more complete.

**Comment by dpolivaev** [comment]
Then I do not understand your report at all

**Comment by aaa1386** [comment]
Sometimes the user faces a problem, but there are sub-solutions to solve the problem in another way.
I say that some cases that I insist and do a lot of follow-up to solve a problem is because the software becomes more complete and flawless. I could ignore that problem and not spend time on it at all. But because I like FP, I want to help it.


I raised two problems on this page, you answered the first problem that there is no need for FP to support large nodes.
But you did not answer about the second case.
I would like to ask you to tell me more clearly where an idea or opinion is not possible so that I do not waste time on it.
Thanks.

**Comment by dpolivaev** [comment]
I do not know what looks like a bug for you.
If you want you can try to be more clear.

**Comment by aaa1386** [comment]
Maybe it can't be called a bug, it's better to say a feature request.
Explanation about the first two images: Yes, the user should try not to make the nodes too big. But if FP can scroll a large node in such a way that the beginning of the node is visible, it is very good. Yes, the last parts of the node cannot be revealed because the node is too big and FP has tried to display the beginning of the node.
 FP is currently trying to scroll that big node, but it moves the map in such a way that some of the beginning and end of the node are not displayed, that is, FP tries to match the middle point of the node with the middle point of the screen. . It is better if FP assigns the top part of the screen to the beginning of the node.

Of course, I understand the difficulty of software development and I don't expect everything I say to be created in FP.


But the last two pictures:
We shrink a large node with the "minimize node" option. We select that node.
 If necessary, FP automatically scrolls the map so that the node is completely on the screen and the user can see the node completely. So far so good.

 Now suppose we want to remove that node from the minimized state and view all the text of the node. When we do this, the map does not scroll automatically and some of the node is displayed outside the screen as shown in the last picture.
It is very good that when the node exits the "minimize node" mode, the map is automatically scrolled so that the node is fully visible on the screen.

**Comment by aaa1386** [comment]
Of course, if these are not implemented in FP, there is no problem, we will scroll manually.

**Comment by aaa1386** [comment]
I do not know English well. Wherever you feel the need for more explanation, tell me so that I can be clearer.
