### ISSUE TITLE
Immediately apply filter to new nodes on unselected views

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#1946]
If I apply a filter to a map view, and then make changes to it, the filter is not reapplied automatically. For example, starting with this map:
![image](https://github.com/user-attachments/assets/3924a01d-542c-428d-8a1d-589a80ea5e63)

if I filter for only "aaa" nodes, this is the result:
![image](https://github.com/user-attachments/assets/8b3a46aa-f2b3-448b-a867-338c894ea81b)

But then I add a new "bbb" node, it is not filtered:
![image](https://github.com/user-attachments/assets/731fc6ce-3907-4367-bcd9-9b53ca38f0c6)

I see that this is useful in some situations. But, there is a situation where it's useful to have the filter automatically reapplied. For example:

Using the new "Navigate->Synchronize selection" feature, I want to keep a left view with only the nodes of style "structure", and the right view with all nodes. This way, I can use the left view as an overview, or an index, for quick navigation. So, in the left view, I use a filter. This is the result:
![image](https://github.com/user-attachments/assets/d954ed3b-13b0-4931-a416-ceb69d973e1c)

The problem is that, when I add, in the right view, a new node that is not of style "structure", it also appears in the left view, which defeats the purpose of keeping the left view as an overview:
![image](https://github.com/user-attachments/assets/941b3aa2-4b01-40e9-be33-41702d6c63be)

So, I would like to have the option to make the filter "persistent", in order to make it avoid showing new nodes that are out of the scope of the filter.

Thanks,

**Comment by euu2021** [comment]
Looking at the change in the title of the ticket, I think that I need to clarify more my usecase above.

I also add the new nodes as child of nodes that already have other child showing in the filter. For example, adding, on the right view, the node aaaa (I would like that the aaaa node wouldn't show up on the left view):

![image](https://github.com/user-attachments/assets/b542769e-f9a8-4acf-bc2e-7205363361f7)


And I would like that, if I add a new node that is inside the scope of the filter, I want it to actually show up on the left view. For example, here, on the right view, I add the node bbb, with style "structure":

![image](https://github.com/user-attachments/assets/437fd762-0bb3-4d44-8d8c-36f95cde65d7)

This works in the current behavior, and I wish that the new behavior also works like this.

**Comment by euu2021** [comment]
One more clarification:

It's not only about the new nodes, but also about modifying old nodes. For example, If I change the style of a node from "structure" to something else, like "default", I want it to be removed from the left view:
![image](https://github.com/user-attachments/assets/6909c7d8-3854-4b01-bf3b-9bd7f4c4ae49)

And, also, vice versa. I.e., if I have a node of "default" style, and then set it to "structure" style, I want it to show up in the left view.

So, maybe this could be the title of the request: `Immediately apply filter to new or modified nodes on unselected views`

**Comment by dpolivaev** [comment]
I think that applying a filter across the whole map usually has high costs. On the other side, filter conditions of node X can depend on any value of any other node in the map, even if in the most cases they depend only on a value of the changed node. So I do not know if I should always reevaluate all nodes - I think it would make Freeplane very slow - or only the modified nodes. The last would be feasible.

**Comment by euu2021** [comment]
> I think that applying a filter across the whole map usually has high costs. On the other side, filter conditions of node X can depend on any value of any other node in the map, even if in the most cases they depend only on a value of the changed node. So I do not know if I should always reevaluate all nodes - I think it would make Freeplane very slow - or only the modified nodes. The last would be feasible.

I see. For my current use case, reevaluate only modified nodes is enough.

**Comment by dpolivaev** [comment]
Could you please create a discussion about it? I want to be sure everyone agrees before I implement it.

**Comment by euu2021** [comment]
related discussion: https://github.com/freeplane/freeplane/discussions/1950

**Comment by dpolivaev** [comment]
Preview 1.12.02_15

**Comment by euu2021** [comment]
Nice! Thanks
