### ISSUE TITLE
Selection/navigation over clones is very slow on first visit

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#1947]
Selection/navigation over clones is very slow the first time they are visited

1. Open the mind map [EPIC-0001~obfuscated.zip](https://github.com/user-attachments/files/16482638/EPIC-0001.obfuscated.zip)
2. Go to node ID_157379599
3. Use `Up` (arrow key) to go up several nodes

The slowness seems to be associated with the commit `fix formula result refresh for nodes accessing clones`, i.e. when I remove the commit, the slowness goes away.

Freeplane version 1.12.2-pre14

**Comment by dpolivaev** [comment]
Preview 1.12.02_15

**Comment by macmarrum** [comment]
Great!
Thank you
