### ISSUE TITLE
Improving displaying bidirectional paths in search and replace dialog

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#1951]

**Comment by aaa1386** [comment]
See the messy path of the node in the image:
![image](https://github.com/user-attachments/assets/0d7de2af-77b1-41e7-b3d3-e912c857a062)

Currently, this problem is not the first priority.
The only way that corrects the path of the nodes:
1- All the nodes should be in the same language, for example, all of them should be Arabic or all of them should be English.
2- If there are Arabic nodes and English nodes on the map, the beginning of all nodes should be set from right to left or vice versa. I don't think anything can be done in this field, because if all the nodes turn right to left or vice versa, other problems may arise.

**Comment by aaa1386** [comment]
🟢🟢🟢 🟢🟢🟢 



[RTL solution.zip](https://github.com/user-attachments/files/16534328/RTL.solution.zip)



🟢🟢🟢

**Comment by dpolivaev** [comment]
Thank you very much for the efforts you put in this issue. I am going to check your findings on the weekend.

**Comment by aaa1386** [comment]
The third problem:
Whenever there is a non-English word in the path of an FP file, it causes the title to be messed up in the FP software. Also, the environment of "Most Recent Maps" is messed up.
To solve this problem, the beginning of all the words in the file path that are not in English should be put the u200e character . This will solve the problem completely.
But the user cannot do this for all files. Can't FP automatically adjust the path of the files when it receives them from the "windows explorer" to display them in its own environment?
I am not a programmer. It may not be possible.

That is, wherever FP found a non-English word in the path, it should place the u200e character at the beginning of it.
Of course, it is clear that FP cannot change "Folder Explorer", but it is meant to consider those characters in its own environment.

**Comment by aaa1386** [comment]
> The second problem:
> 
> ![image](https://private-user-images.githubusercontent.com/38586259/354938342-2d7927eb-196c-42ab-8e67-3d2890186c44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjc0ODEsIm5iZiI6MTcyMzAyNzE4MSwicGF0aCI6Ii8zODU4NjI1OS8zNTQ5MzgzNDItMmQ3OTI3ZWItMTk2Yy00MmFiLThlNjctM2QyODkwMTg2YzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDEwMzk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNDdkNTQ0YmFiNjNlMTMzNjc3ZmNhYmJhZDc5YWJlZWViM2QyYTUyODJhMzE4MzA2ZjlkMGZjZTY4NDI5MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.huH0SnSsGmaVp6hJCrp7rxqJZ3KYqFWjsiaaHz-RLeE)

I did some more research. I noticed that FP works well in many places. And I made a mistake. Look at this picture. It means that if we type each of these two words first, it will have the same display, but it is not wrong because if the user has typed the Arabic word, it will actually start reading from the right side, and if the user has typed English first, it should be read from the left side. I did some more research. I noticed that FP works well in many places. And I made a mistake. Look at this picture. It means that if we type each of these two words first, it will have the same display, but it is not wrong because if the user has typed the Arabic word, it will actually start reading from the right side, and if the user has typed English first, it should be read from the left side. Read and the first word on the left is English.

I gave explanations to solve what I thought was an error and drew many diagrams.
Of course, I did a lot of research, sometimes FP has mistakes that I have to explain at another time.
Now I know that some of these diagrams are useless. If it is implemented, it may cause many problems. Maybe.

Maybe these diagrams show the importance of characters.
For example, 
The confusion of the path of the FP file in the title at the top of the screen and the confusion in the "Most recent maps" environment in the above comment can probably be solved by using characters, because when I manually change name the folders that are in the path of the FP file,((if If it is not English language )), I put the «u200e» character at the beginning of the folder name.

I also checked another solution for these two problems, only the character U+202E at the beginning of the path is enough.



f course, all these solutions are temporary. Maybe there are solutions to fix the basic problems.

**Comment by aaa1386** [comment]
🌟🌟🌟🌟
Here I propose an idea. I think it is a very good idea.
I don't know programming, but I know that FP can create two types of nodes. Normal nodes that are simpler and complex nodes using HTML codes.

I know that using HTML codes, you can make various and beautiful nodes.
Now there is an HTML editing environment for all nodes. But each node must be edited. This is very difficult. Of course, you can design and edit the headings. But every node must be opened and edited in this environment.

A very interesting idea is to have a default text field in the style editing section where you can write a simple sentence or write HTML codes. Suppose we create a heading with HTML codes, which is blue color  and its direction is from right to left. Then we save that style with the name of «heading 1». Now imagine we can easily create nodes based on this custom style. Suppose you have made 100 nodes with this style, you decide to make its font bigger or its color green, you can easily create the desired settings by changing that style and apply it to all those hundred nodes.
 Of course, I don't know, maybe the nodes made based on HTML make the FP file more size. But the user can control. and use these built-in styles for smaller maps.
For large maps, use a combination of HTML-based styles and normal styles.


It seems that this idea can be a big evolution in styles.

**Comment by aaa1386** [comment]
I deleted the comments and tables that I had prepared. Because now I understand that FP is almost good at combining two different languages ​​and in some cases I was wrong.
And I thought the reader might be confused.

**Comment by aaa1386** [comment]
I am reporting a bug in this comment.


I am sending a FP file.
In branch 1, first I type two English words, then two Arabic words.
Branch 2: First two Arabic words, then two English words.
There are bugs in two cases when using the right and left arrow keys, when we move from the beginning of the text to the end and vice versa among the letters of these four words.
 Place the cursor at the beginning of the text, then move with the right or left arrow keys, again place the cursor at the end of the text, then move with the right or left arrow keys, and you will notice the errors.

You can compare the correct cursor movement in Microsoft Word. 

[aaaa.zip](https://github.com/user-attachments/files/16553661/aaaa.zip)

**Comment by dpolivaev** [comment]
I looked at your examples and findings.
I think that there is a significant difference between Microsoft Word and Freeplane: 
Microsoft Word knows which language you use. Freeplane doesn't. And it uses very complex logic to understand which language is used in a sentence, and in case when you mix latin and arabic letters, it can be confused.

Your assumption that if the sentence contains arabic letters and start with a latin letter it should be handled as arabic language completely does not seem to be resonable.

However, for single nodes I added a formatting setting where you can choose if the node uses left-to-right or right-to-left language. And I can use this knowledge for displaying paths in search and display dialogs.

I do not have an idea what else I could do.

**Comment by dpolivaev** [comment]
Preview 1.12.02_15 not perfect but better than before
I am afraid I do not know how to make it better than in this preview

**Comment by aaa1386** [comment]
> Preview 1.12.02_15 not perfect but better than before I am afraid I do not know how to make it better than in this preview

Yes, thank you - I understand how you feel.

**Comment by dpolivaev** [comment]
@ajaberi1360  Please check the latest preview 1.12.02_16, I have tried a new fix.

**Comment by aaa1386** [comment]
There are still some problems which I will explain very clearly in due course. Please check the latest preview 1.12.02_16, I have tried a new fix.


thank you very much It got better than before. Now "Replace Search" is usable for me.

thank you very much It got better than before. Now "Replace Search" is usable for me.
 There are still some small bugs that I will explain very clearly at the appropriate time.
