### ISSUE TITLE
Option to paste HTML as plain text node hierarchy

### ISSUE THREAD

**Issue by rnavarro2** [freeplane/freeplane#1954]
**Describe the bug**
Pasting a node's detail that has bulleted items into a new node as hierarchy (plain text or html), the resulting new nodes do not retain the hierarchical nature of the bullets.

**To Reproduce**
1. Create a node
2. Using the Node Details Editor create a multiple hierarchy of bulleted text.
3. Copy all of the text in the node details (CTRL-A, CTRL-C)
4. Click OK in the Node Details Editor to save and exit the editor.
5. Select a node with no children.
6. From the Menu: Edit->Paste as..., select "Paste text as node hierarchy"
7. Multiple child nodes are created from the parent just one level from the selected parent node.

**Expected behavior**
The pasted nodes should resemble the hierarchy of the bulleted text they came from.

**Mind map files**
[Node Details Text Hierarchy Paste Problem.zip](https://github.com/user-attachments/files/16549964/Node.Details.Text.Hierarchy.Paste.Problem.zip)

**Screenshots**
![image](https://github.com/user-attachments/assets/92be438f-1a26-45c6-aacb-4adcb9eb3a9f)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Enterprise
 - Freeplane Version 1.11.14
 - Java Version 11.0.23

**Additional context**
I also tried the normal pasting of the clipboard into a selected node, and Paste As... HTML as node hierarchy.  Same flat children nodes were posted.

**Comment by dpolivaev** [comment]
"Paste As... HTML as node hierarchy" works on all my machines (Windows 10 and MacOS).
If you choose to paste it as plain text, it currently ignores HTML structure and parses only plain text. Maybe I should change it. But as now it should work if you paste HTML and convert it to plain text in the next step.

What happens on your computer when you use this paste option? Can you send me your resulting mind map?

**Comment by dpolivaev** [comment]
Preview 1.12.7_03
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
