### ISSUE TITLE
Add-on guide

### ISSUE THREAD

**Issue by OmarMohamedAero** [freeplane/freeplane#1973]
Hello all,

I'm having a problem with Freeplane. I need to create an addon for Freeplane, and I was wondering if there are any resources where I can read documentation or tutorials to see how it works. 

I would appreciate it if you could guide me to any resources that could help me add some features to the app.

Please, if you can, provide me with a resource for that.

**Comment by euu2021** [comment]
Start here: https://docs.freeplane.org/scripting/Start_Here.html

About Add-ons, specifically, see here: https://docs.freeplane.org/scripting/Add-ons_(Develop).html
