### ISSUE TITLE
Error: Tag disappears from node unexpectedly after interacting with the categories manager

### ISSUE THREAD

**Issue by i-plasm** [freeplane/freeplane#1975]
**Describe the bug**
Tag disappears from node unexpectedly after interacting with the categories manager. I'll describe 2 variations of this bug.

**To Reproduce**

## Variation 1

Steps to reproduce the behavior (see video at the end):
1. Create a new mind map
1. Add these two tags to the root node (by right clicking the node and choosing `Edit -> Edit tags`:
   - `cat::tag1`
   - `cat::tag2`
1. Click OK
1. Open the categories manager (`Edit -> Node properties -> Manage tag categories for map`)
1. Fully expand the tags tree
1. Reorder the sibling tags by dragging `tag2` to the place above `tag1` (so they remain siblings, but now `tag2` appears first)
1. Click OK
1. =>>> ERROR: `tag2` unexpectedly disappears from the node, but no error/exception whatsoever is logged.

## Variation 2

Steps to reproduce the behavior (see video at the end):
1. Create a new mind map
1. Add these two tags to the root node (by right clicking the node and choosing `Edit -> Edit tags`:
   - `cat::tag1`
   - `cat::subcat::tag2`
1. Click OK
1. Open the categories manager (`Edit -> Node properties -> Manage tag categories for map`)
1. Fully expand the tags tree
1. Move `tag2` by dragging it to the towards the right of `tag1` (so that it becomes the child of `tag1`)
1. Move back `tag2` to its original place by dragging it to `subcat` (so that it becomes again the child of `subtag`)
1. Click OK
1. =>>> ERROR: `tag2` unexpectedly disappears from the node, but no error/exception whatsoever is logged.

**Expected behavior**
`tag2` should not have been deleted without the consent of the user. Also, if any inevitable problem occurred internally, exceptions should have been logged or displayed to alert the user. 

**Screenshots**

Variation 1 video:

![tag_error1_var1-](https://github.com/user-attachments/assets/b16f3a1a-e4e5-407e-9982-6f961b923b25)

Variation 2 video:

![tag_error1_var2](https://github.com/user-attachments/assets/531c4eff-877d-478c-8263-7bf7c2f170b9)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Freeplane 1.12.2-pre17
 - Java Version: 17.0.5

**Comment by dpolivaev** [comment]
Thanks for reporting. Users wanted that tags can changed and deleted when they are modified in the tag category manager. The logic is quite complicated and  it looks like you found a bug here. I'll check it. Thanks.

**Comment by dpolivaev** [comment]
I fixed it in preview 1.12.3_02 and removed release 1.12.2 from stable.

**Comment by i-plasm** [comment]
Thank you Dimitri. I can imagine the logic of this feature must be quite intricate. Sometimes in the past I've found strange behaviours in the Categories manager, but I was never sure which steps I did caused them! Hard to replicate. I will keep testing. Best regards.

**Comment by dpolivaev** [comment]
@i-plasm Hello, I just want to let you know that I have released 1.12.3 (stable) today because I fixed even more bugs compared to preview 1.12.3_02, and wanted to go live with it.
