### ISSUE TITLE
1.12.2 Windows installer sets wrong DisplayVersion number in registry

### ISSUE THREAD

**Issue by robert-reiser** [freeplane/freeplane#1976]
**Describe the bug**
After installing the most recent Windows version 1.12.2 (with JAVA included), I used winget to update other software on my system. winget showed the installed freeplane version as version "1.2.2" (instead of "1.12.2) and therefore as outdated.

**To Reproduce**
1. Install the latest freeplane version 1.12.2 (with Java) on Windows 11
2. Check the following registry entry:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{D3941722-C4DD-4509-88C4-0E87F675A859}_is1\DisplayVersion
3. DisplayVersion will show "1.2.2" instead of the correct version "1.12.2".
4. Manually changing DisplayVersion to "1.12.2" stops winget from trying to update with an outdated version.

**Expected behavior**
See above, step 3

**Desktop (please complete the following information):**
 - Windows 11
 - Java Version

**Comment by dpolivaev** [comment]
Fixed in 1.12.3

**Comment by dpolivaev** [comment]
Thank you for letting me know.
