### ISSUE TITLE
Tag renders incompletely

### ISSUE THREAD

**Issue by i-plasm** [freeplane/freeplane#1977]
**Describe the bug**
Tag renders incomplete graphics when mindmap zoom is 100%, and tags are set to appear under nodes. When zoom is different (e.g 90% or 110%), the graphics render fine. Note: tag font size seems to be irrelevant

**Screenshots**

![100-](https://github.com/user-attachments/assets/922de744-e202-4ee2-addf-fdd8713220cc)
![90](https://github.com/user-attachments/assets/b1458d4f-c144-4c57-9aeb-a5a3ffb4d490)
![110](https://github.com/user-attachments/assets/83730771-7026-40b9-b04f-4d3adffff2a4)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Freeplane 1.12.3-pre02
 - Java Version: 17.0.5

**Comment by dpolivaev** [comment]
Fixed in 1.12.4 released as stable
