### ISSUE TITLE
Error: Categorized tag color is lost after saving-closing-reopening the mindmap

### ISSUE THREAD

**Issue by i-plasm** [freeplane/freeplane#1978]
**Describe the bug**
Categorized tag color is lost after saving-closing-reopening the mindmap. Note that the same steps, if performed on a "Uncategorized" tag did not lead to the error.

**To Reproduce**
1. Create a new mind map
1. Add the tag `cat::tag1` to the root node (by right clicking the node and choosing `Edit -> Edit tags`)
1. Click OK
1. Open the categories manager (Edit -> Node properties -> Manage tag categories for map)
1. Locate `cat::tag1` and change its color from its original yellow to e.g black
1. Click OK
1. Save mindmap
1. Close mindmap
1. Open mindmap
1. =>>> ERROR: `tag1` color is not black, but has reverted to the original yellow. Color changes were lost.

**Expected behavior**
Categorized tag color changes should have been saved.

**Desktop (please complete the following information):**
- OS: Windows 10
- Freeplane 1.12.3-pre02
- Java Version: 17.0.5

**Comment by dpolivaev** [comment]
Fixed in 1.12.4 released as stable (data integrity issue, urgent fix release)

**Comment by i-plasm** [comment]
Thank you Dimitry, I will try version 1.12.4 and test some more. Will report if I notice important bugs.
