### ISSUE TITLE
1.12.4 scripting API is in German

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#1979]
When I open `Help->Freeplane API…` or https://docs.freeplane.org/api/ the language of the page is German.

Expected: English.

**Comment by dpolivaev** [comment]
Fix released as 1.12.4u1

**Comment by macmarrum** [comment]
Thanks.
I've triggered https://github.com/freeplane/docs/actions/runs/10494596081 to update https://docs.freeplane.org/api/
Looks good.
