### ISSUE TITLE
Error: Interacting with the tag categories manager causes the loss of categorized tag color changes

### ISSUE THREAD

**Issue by i-plasm** [freeplane/freeplane#1983]
Hello Dimitry. I have been testing on v.1.12.4, and the old tag bugs are fixed - thanks! I did find a few more bugs, and today I'll share this one, and hopefully in the upcoming days I will share the rest of them.

**Describe the bug**
Interacting with the tag categories manager causes the loss of categorized tag color changes. Note: the bug does not happen with uncategorized tags. Also, it may not happen if the steps are not followed strictly as indicated.

**To Reproduce**
1. Create a new mind map
1. Add this tag to the root node (by right clicking the node and choosing `Edit -> Edit tags`):
   - `cat::tag1`
1. Click OK (Note: this step and the next one seem redundant, but are necessary) 
1. Once again, right click the root node and choose `Edit -> Edit tags`
1. Change the color to e.g Black
1. Click OK
1. Open the categories manager (`Edit -> Node properties -> Manage tag categories for map`)
1. Fully expand the tags tree and don't do anything (notice that the color of `tag1` is not black but showing as original yellow)
1. Click OK.
1. =>>> ERROR: The color of `tag1` is reverted to original yellow.

**Expected behavior**
The color change performed in the node tag editor should have been synchronized with/published to the categories manager.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Freeplane v.1.12.4
 - Java 17.0.5

**Comment by dpolivaev** [comment]
Preview 1.12.5_01
