### ISSUE TITLE
Merging categorized tags causes node tag editor to perpetually ask if changes must be saved

### ISSUE THREAD

**Issue by i-plasm** [freeplane/freeplane#1989]
**Describe the bug**
Merging categorized tags causes node tag editor to perpetually ask if changes must be saved. After performing the steps, it seems the tagged node enters some sort of perpetual "pending changes to be saved" state that is not even alleviated by saving the map and reopening it.

**To Reproduce**
1. Create a new mind map
1. Add these two tags to the root node (by right clicking the node and choosing `Edit -> Edit tags`):
   - `cat::tag1`
   - `cat::tag2`
1. Click OK
1. Open the categories manager (`Edit -> Node properties -> Manage tag categories for map`)
1. Fully expand the tags tree
1. Merge both tags into one by changing the name of `tag1` to `tag2`
1. Click OK
1. Save the mindmap
1. Close the mindmap
1. Reopen the mindmap
1. On the root node, right click and choose `Edit -> Edit tags`
1. Don't do anything, but simply click "X" to exit the dialog
1. =>>> ERROR: A message appears saying "You have changed the node. Do you want to save changes?" despite not having performed any type of changes. Even if you click "YES", and save the mindmap, the next time you right click and choose `Edit -> Edit tags` and press "X", the same message will appear again and again. 
1. NOTE: this bug also occurs if merging occurs via drag and drop, let's say there are two tags `aaa::tag1` and `bbb::tag1`, and the first `tag1` is drag and dropped to `bbb`. The exact same issue occurs.

**Expected behavior**
After saving the tag changes by clicking OK, and then saving and reopening the mindmap, the mindmap should not perpetually remember and ask about saving old tag changes.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Freeplane v.1.12.4
 - Java 17.0.5

**Comment by dpolivaev** [comment]
Preview 1.12.5_02
