### ISSUE TITLE
Incomplete display of text in svg format 

### ISSUE THREAD

**Issue by souxls** [freeplane/freeplane#199]
Some text is not displayed when exporting svg format。
Version: 1.8.11 1.9.1 (only used)
OS: windows 10
Attach: freeplane source and svg file
![test](https://user-images.githubusercontent.com/7885342/118799145-fbac1800-b8d0-11eb-9ec2-3d7a291895c4.png)
[test.zip](https://github.com/freeplane/freeplane/files/6507942/test.zip)

**Comment by ofossum** [comment]
I was kind of able to verify this, but it seems to depend on which program is used to view the `.svg`.

* Archlinux
* Java 11
* Freeplane 1.9.14

* source mindmap looks fine in Freeplane
* `test.svg`-file has the clipped text as shown in the initial screenshot above
* your source `test.svg` in Inkscape seems also to have clipped text

However, if i export the source mindmap `test.mm` from Freeplane, my exported `.svg` looks fine (see on the _right side_ in the attached screenshot):


![test_comparison](https://user-images.githubusercontent.com/99810909/160214874-103e8bef-da0e-4413-8be8-ca7c558eebd4.png)
_left_ yours, _right_ mine exported `.svg`


* Does the issue still exist in the newest version Freeplane?
* Might be an issue with the used font!? Maybe try another one, to see if it fits better.

**Comment by souxls** [comment]
> I was kind of able to verify this, but it seems to depend on which program is used to view the `.svg`.
> 
>     * Archlinux
> 
>     * Java 11
> 
>     * Freeplane 1.9.14
> 
>     * source mindmap looks fine in Freeplane
> 
>     * `test.svg`-file has the clipped text as shown in the initial screenshot above
> 
>     * your source `test.svg` in Inkscape seems also to have clipped text
> 
> 
> However, if i export the source mindmap `test.mm` from Freeplane, my exported `.svg` looks fine (see on the _right side_ in the attached screenshot):
> 
> ![test_comparison](https://user-images.githubusercontent.com/99810909/160214874-103e8bef-da0e-4413-8be8-ca7c558eebd4.png) _left_ yours, _right_ mine exported `.svg`
> 
>     * Does the issue still exist in the newest version Freeplane?
> 
>     * Might be an issue with the used font!? Maybe try another one, to see if it fits better.

Solved. It's a font problem. After changing fonts, it works. Thanks a lot.
