### ISSUE TITLE
Freeplane (V1.12.4) was frozen after reordering tags

### ISSUE THREAD

**Issue by dpolivaev** [freeplane/freeplane#1990]
> > The application (V1.12.4) crashed while I was "dragging and dropping" the tags as categories and sub-categories... > > @regis586 can you share exactly which steps you performed that would reproduce the issue leading to the crash? That would be helpful. I also had it crash yesterday when dragging and dropping some items (I had to use the Task Manager to kill the freeplane process), but unfortunately don't know the exact sequence of steps. Thanks.

Hi,
A good drawing is worth a thousand words... 

![20240822-FreePlane-Tags-Bug-1](https://github.com/user-attachments/assets/e29278bc-43ee-41bf-bc83-65376379c8b2)

 ![20240822-FreePlane-Tags-Bug-2](https://github.com/user-attachments/assets/651fe429-d095-4ec6-8257-16362d283799)

![20240822-FreePlane-Tags-Bug-3](https://github.com/user-attachments/assets/1acb4c12-b0bf-46d7-bafd-053ed0e10536)

Just to clarify...I also killed the task (each time it crashed), but my Freeplane map remained displayed (?) on the screen... I had to close my session each time...

_Originally posted by @regis586 in https://github.com/freeplane/freeplane/issues/1922#issuecomment-2304186090_

**Comment by dpolivaev** [comment]
Preview 1.12.5_01

**Comment by regis586** [comment]
Tags  work fine,  now with 1.12.5..
Thanks 😊..
