### ISSUE TITLE
Window copy and overlap when using Microsoft input method

### ISSUE THREAD

**Issue by lizzary** [freeplane/freeplane#1991]
![3d1adceb96766c9a441d979f8febd0a](https://github.com/user-attachments/assets/4f6344ad-bc07-44c7-8144-bd98f7b3adce)
my version:Freeplane-Setup-1.12.4u1
op:win10
when I try to use the Microsoft input method to type something, there are many page copy and overlap at the trajectory of my mouse movement

**Comment by dpolivaev** [comment]
Check https://docs.freeplane.org/user-documentation/Troubleshooting.html#graphics-issues-with-the-ui and write back if it could help

**Comment by lizzary** [comment]
the issue solved, thanks
