### ISSUE TITLE
Unknown Unicode character displayed in search results

### ISSUE THREAD

**Issue by jockster74** [freeplane/freeplane#1997]
Unknown Unicode character in search result path
I noticed the following bug after installing Freeplane 1.12.4. In the **Search replace** dialog I select a result and there is a square character showing up before every segment of the path to that result, as shown at the bottom of the dialog. I believe it is the WHITE SQUARE' (U+25A1) character.

**To Reproduce**
1. Open **Search replace** dialog,
2. In the **Find** field, type a few characters of a string you know exists in the map.
3. Select the search result.
4. Check the path at the bottom of the dialog.

**Screenshots**
Please see the screenshot.

![freeplane_search_issue](https://github.com/user-attachments/assets/8eecd8c5-ed19-4a22-ab99-53a3c51209b3)

**Desktop (please complete the following information):**
Freeplane 1.12.4
Java version: 15.0.10
Windows 11 Enterprise, version 23H2

**Comment by dpolivaev** [comment]
Preview 1.12.5_04
