### ISSUE TITLE
FP 1.12.5_04: do not delete tags for deleted and pasted categories

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#2001]
**Describe the bug**
As I installed the 1.12.5_04 and I opened my files I discovered that I had lost all of the tags already present.
Sadly I do not remember if before perceiving it I cancelled the previous tags from the Tag Category Editor and recreated a new structure by copying it from another file. (that is a normal procedure I performed with previous releases w/o troubles)
**To Reproduce**
Currently, I'm not able to reproduce it.

**Expected behavior**
Is it possible to create protection in order not to accidentally cancel all of the tags if you cancel the tag categories, or at least place a message informing what to do next if keeping the existing tags in the nodes or not?

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] w11
 - Java Version included in FP 1.2.15_04

**Additional context**
Not sure if this is a bug or a feature request. Thanks

**Comment by dpolivaev** [comment]
Preview 1.12.5_05
I would appreciate it if you could test the new preview version soon so that I can release it if it does fine.

**Comment by Illegit** [comment]
Hi Dimitry I tried fastly these 4 cases: my consideration is that I need all of these cases working keeping the created tags even if I delete the categories from the TCE, and basically I need to copy the tags from the TCE of one map to the TCE of another map, without destroying the tags already present in that map.
Please have a look at the trials.

TCE= Tag Category Editor
Case 1: 

1. I created tags with TCE of map,
2. I saved the map
3. after I copied tags from the TCE of another map (but  I didn't paste)
4. I cancel the existing categories in the  TCE of the map
Result: tags were deleted out of the map
after: I tried to paste the tags of the other map, but it was not possible <--- this is necessary to be possible
finally: I closed the map currently without tags and without categories of tags

Case 2: 

1. I reopened the previous map,
2.  I copied the tags from the TCE of another map
3. I closed that TCE
4. I opened the TCE of the destination map
5. I pasted the tags &categories on this TCE: ---> not possible

After this I understood I have lost irreversibly the tags on that map (luckily it was a trial map)
I confirm that it is not any longer possible to copy tags from a TCE of map1 and paste them in the TCE of map2 --> very problematic

Case 3:

1. open the TCE of a tag source map
2. open destination map, (note that this destination map hs in its TCE some tags in common with the source map)
3. added tags to some nodes (working)
4. open the destination map TCE
5. canceled some of them in the TCE and saved the destination map TCE 
Result: the tags disappeared from the nodes --> not what I expect, I need the tags remain on the node

Case 4:

1. open destination map (map without any tag)
2. opened source map TCE
3. went to destination map and crated some tags on the map nodes using the TCE of the source maps
4. closed the tce
5. saved the destination maps
6.Result: tags are still present in uncategorized list of the TCE of the destination map

**Comment by Illegit** [comment]
I do not know how to reopen this issue

**Comment by dpolivaev** [comment]
I am sorry, i can't understand your abstract descriptions. Please upload all source and destinations maps and describe exactly what you do, what you expect and what you observe.

For example, I don't understand how you use tag category manager to create node tags. And there are many other things I do not get from your descriptions.

Tag management is so complicated that only exact and detailed descriptions including all maps and screenshots can help me.

**Comment by Illegit** [comment]
Here the 2 maps I used for those 4 cases: 
[Source&Destination Maps.zip](https://github.com/user-attachments/files/16822423/Source.Destination.Maps.zip)

Source Map: is the map with the reference list of Tags/Categories  (its TCE has been simplified just for these trials, normally is much bigger: at now of about 200 tags and growing)
ProvaTag01: is a destination map

Let me summarize the 2 most important topics:
1) Normally I prefer to have only one TCE clearly managed (in the source map) and I work with many projects in many maps but I need to have all of the tags of those maps + the reference tags copied and pasted from the Source Map TCE into the Destination Map TCE.
This operation was possible in previous releases, but not possible in this one.

2) Deleting some tags in the destination maps TCE (and in fact in any map) imply the deletion of those tags from the nodes that got them. This is not correct. I prefer to maintain those tags and delete them only with the TE (tag editor). Or at least to receive a message proposing if I want o to delete them out of their nodes or I prefer to go with the node TE.

Thanks

**Comment by Illegit** [comment]
Last comments are referred to the FP 1.12.5_05 release

**Comment by dpolivaev** [comment]
Can you please explain what you use the tags for and which tags and categories you usually have?

I can't look at the attached maps until tomorrow because it is too late now.

**Comment by Illegit** [comment]
Ok, let's say that you look at the 2 maps in the zip file. 

Comment for point 1. : 
They are very simple maps: one, the Source Map, has a basic TCE with all of the tags and categories  I want to have in all my maps. The second map is a Destination Map like many. 
In the Destination Map, I need to have some specific categories + all of the categories of the Source Map. Therefore when I create a new Destination Map I need to copy the categories of the Source Map and paste them in this new Destination Map.
Normally I have a Map template, but with the constant use of the Tags, I need to add categories to the Source Map, therefore the template needs to be integrated periodically, in between I need to copy categories and tags from the source to the destinations.

Comment for point 2.:  I think it is enough clear..., if you need more info please send me your questions.

I want to thank you for this tags tool: I'm managing some project resources and with the tags is faster to identify misses and problems... sparing time and reducing the risk of losing money. Very useful.

PS: if necessary, I do not know how to show you a cinematic: eventually may you suggest some apps for PC  for creating video and eventually even tracing the keys...

**Comment by Illegit** [comment]
I tried :
point 1 (copy/paste tags categories from/to different TCE) with FP 1.12.5_04, it is working perfectly, but it is not working at all in FP 1.12.5_05.
point 2 (deleting tag categories w/o deleting tags) is not working in both the releases.

Probably it is necessary to open another bug issue for point 1?

**Comment by dpolivaev** [comment]
point 1: I know you are non dev, but if you looked in the logs yourself you would see the exception trace that identifies the malfunction. I have already fixed it on my computer.

point 2: deleting tag categories without deleting tags is not possible by design because it would be inconsistent. But you can move any category tags into uncategorized tags, and it is probably what you actually need.

**Comment by dpolivaev** [comment]
Preview 1.12.5_06
Break it till we make it

**Comment by Illegit** [comment]
Done.
Release working: thanks
Errors recovered.

About point 2: I follow your recommendations. It is working. There is a risk of unintended cancellation of tags: if you imagine a tag tree with many levels, so I suggest giving the user the possibility to decide if to activate a warning message when deleting categories.

Thank you.

**Comment by dpolivaev** [comment]
> There is a risk of unintended cancellation of tags: if you imagine a tag tree with many levels, so I suggest giving the user the possibility to decide if to activate a warning message when deleting categories.

If you rename tags, move tags or categories to another categories, or delete tags or tag  categories in the tag category manager, when you click on OK all changes are applied to tags existing in the mind map. It is a consistent behavior. So I don't understand when Freeplane should display warnings and how to phrase them.

**Comment by Illegit** [comment]
Ok, maybe it is necessary to highlight it in the tag instructions in the Freeplane help.
