### ISSUE TITLE
Filter tool bar: date selector doesn't close after month selection was changed

### ISSUE THREAD

**Issue by guiljo** [freeplane/freeplane#2003]
**Describe the bug**
When you try to select a date in the search field, the calendar opens to select a date, but selecting a date doesn't change it in the search bar. The calendar can't be closed either

**To Reproduce**
1. Look at the search panel
2. In the 'contains' drop-down menu, select '<='
3. In the search bar, select the calendar '📅' icon
4. Select another month
5. Click on the date you want to choose

**Expected behavior**
The chosen date appears in the search bar, the date selector closes itself.
NB: it kind of works if you don't select another month, though you still have to click outside of it to close it. But as soon as you change the month, it doesn't work anymore.
It even remains on top of other apps...

**Mind map files**
[Papach 5 inter-avancé.zip](https://github.com/user-attachments/files/16799504/Papach.5.inter-avance.zip)

**Screenshots**
[bug Freeplane](https://github.com/user-attachments/assets/176cc2bb-42e1-4548-9dca-46e3ee0b4716)
![bug Freeplane 2](https://github.com/user-attachments/assets/95e9da2d-fc97-4310-8d0f-799448dedaa2)

**Desktop (please complete the following information):**
 - OS: Windows 11 Famille FR 23H2 22631.4037
 - Freeeplane 1.12.4
 - Java 1.8.0_361-b09

**Comment by dpolivaev** [comment]
Preview 1.12.5_05
