### ISSUE TITLE
Pinch-to-Zoom Support for Freeplane on macOS

### ISSUE THREAD

**Issue by himatech** [freeplane/freeplane#2011]
**Is your feature request related to a problem? Please describe.**
When I want to zoom in and out of my mind maps in Freeplane on macOS, I cannot get it done efficiently because the current Control+scroll method is buggy and unreliable. As a macOS user, I'm accustomed to using pinch-to-zoom gestures on my trackpad for seamless zooming in various applications. The lack of this feature in Freeplane hinders my productivity and creates a disjointed user experience when switching between applications.

**Description of the solution I'd like**
I would like Freeplane to implement pinch-to-zoom functionality for macOS users. This feature would allow users to zoom in and out of mind maps using the standard two-finger pinch and spread gestures on their trackpad. The zoom level should smoothly adjust in real-time as the user performs the gesture, similar to how it works in other macOS applications like Preview or Safari.

**Alternatives I've considered**
While the current Control+scroll method is available, it's not working correctly and feels unintuitive for macOS users. An alternative could be to implement Command+scroll for zooming, which aligns better with macOS conventions. However, pinch-to-zoom would still be the most natural and efficient solution for trackpad users.

**Additional context**
- This feature would greatly improve the user experience for macOS users, bringing Freeplane more in line with native macOS applications and user expectations.
- Pinch-to-zoom is a standard gesture in macOS, and its implementation would make Freeplane feel more integrated with the operating system.
- If full pinch-to-zoom implementation is challenging, consider at least fixing the current Control+scroll method to ensure it works reliably for all users.

**Comment by guangd2000** [comment]
i'd second @himatech! For mac users, it is a widely used feature. Having it built in Freeplane would give Freeplane the premium feel that encourages more user adoption.

**Comment by dpolivaev** [comment]
If you could convince Java library makers to support this feature in Java Swing applications, I could integrate it.

**Comment by dpolivaev** [comment]
https://stackoverflow.com/questions/68802576/pinch-zoom-with-swing-and-openjdk
https://bugs.openjdk.org/browse/JDK-8226225
