### ISSUE TITLE
TAGS as part of ChangedElement for NodeChangeListener

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#2014]
`org.freeplane.api.NodeChangeListener` can be used to react on changes to TEXT, DETAILS, NOTE, ICON, ATTRIBUTE, FORMULA_RESULT or UNKNOWN.

It would be great to have TAG as a separate `ChangedElement` item, so that tag changes can be detected in scripts and reacted to easily.

**Comment by dpolivaev** [comment]
How should it react to changes in tag categories? This change does not affect single nodes alone, but the changes including renaming and deletion of tags are applied to all nodes in the map.

**Comment by macmarrum** [comment]
I think that a change of a tag category is similar to a find-and-replace operation for node's text/details/note, it just affects a different property of a node, namely `tags`.
In my opinion, if a tag category changes then each tag consisting of this category changes, therefore each node that has the tag assigned changes. In other words, if a change in category affects 10 nodes, then all 10 nodes are effectively changed.

---

Given the following nodes

- A	['location::fridge', 'food::vegetable::tomato']
- B	['location::table', 'food::fruit::orange']
- C	['location::pantry', 'food::vegetable']

When Tag Category `food::vegetable` is changed to `food::fruit`

Then `NodeChanged` event with `changedElement == TAGS` is emitted for nodes A and C

---

Given a mind map with a Tag Category `day::Wednesday` not assigned to any node

When the Tag Category `day::Wednesday` is changed to `weekday::Wednesday`

Then no `NodeChanged` event is emitted

---

I also think that it would be better if a change of a tag's color didn't trigger `ChangedElement.TAGS`, but instead triggered `ChangedElement.UNKNOWN`, like it is for `core` when its formatting properties (e.g. bold, font) are changed.

**Comment by dpolivaev** [comment]
Unfortunately, I do not iterate over nodes, I implemented a more efficient algorithm. I don't even know which nodes are affected. I update only node views, and they are just a subset of all nodes.

**Comment by macmarrum** [comment]
I think that's fine. Tag Categories are a special case, so the currently emitted UNKNOWN is reasonable.

How about direct tag changes (not category changes)? Can TAGS be emitted for such events, so that they can be distinguished from others?

**Comment by dpolivaev** [comment]
Actually, tag category changes are map events, not node events, therefore I think they are not reflected by node change listener. But for usual tag assignment changes I can implement your suggestion.

**Comment by macmarrum** [comment]
> Actually, tag category changes are map events, not node events, therefore I think they are not reflected by node change listener.

Indeed, I don't see any `NodeChanged` events emitted on Tag Category changes.

> But for usual tag assignment changes I can implement your suggestion.

That's great! Thanks.
