### ISSUE TITLE
Tags -except the first one- cannot be inserted via typing in the Node Tag Editor

### ISSUE THREAD

**Issue by i-plasm** [freeplane/freeplane#2015]
**Describe the bug**
Tags -except the first one- cannot be inserted via typing (and the wrong one is inserted instead) in the Node Tag Editor

**To Reproduce**
1. Create a new mind map
1. Open the categories manager (`Edit -> Node properties -> Manage tag categories for map`)
1. Add these three uncategorized tags
   - `aaa`
   - `jjj`
   - `zzz`
1. Click OK
1. On the root node, right click and choose `Edit -> Edit tags`
1. Type `jjj` or `zzz` and then press `Enter`
1. ERROR: `aaa` was chosen/inserted instead. Extra info: I noticed this pattern. I noticed that the first tag (first according to ascending alphabetic ordering) is always chosen. E.g if instead of `aaa`, `jjj` and `zzz` we had used `mmm`, `qqq` and `yyy`, then the chosen tag would have been `mmm` and the others are impossible to choose. 

**Expected behavior**
The tag the user typed should have been chosen instead of `aaa`

**Screenshots**
![issue](https://github.com/user-attachments/assets/af8a920f-3f96-4e3a-959e-a9ec51c5a37f)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.12.5-pre04
 - Java 17.0.5

**Comment by dpolivaev** [comment]
preview 1.12.6_01
