### ISSUE TITLE
conditional style "tag contains" fails to load on map open

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#2016]
Freeplane v1.12.6-pre (4fbb82a4)

1. Create a map conditional style `tag contains "orange"`.
  ![2024-09-01_20,08,44](https://github.com/user-attachments/assets/88c2b896-f869-4c0d-a31c-ce76debd2277)
2. Save and close the mind map
3. Open the mind map, open `Format->Manage Styles->Manage conditional styles for map` – the condition says `Always` (and is applied to all nodes). Expected: `Tag contains "orange"`

From .mm after it is saved:
```xml
    <conditional_styles>
        <conditional_style ACTIVE="true" LOCALIZED_STYLE_REF="styles.important" LAST="false">
            <tag_contains_condition VALUE="orange"/>
        </conditional_style>
    </conditional_styles>
```

[tags-contains-test.mm.zip](https://github.com/user-attachments/files/16830074/tags-contains-test.mm.zip)

**Comment by dpolivaev** [comment]
preview 1.12.6_01
