### ISSUE TITLE
Export to png inverts colors

### ISSUE THREAD

**Issue by ebussf** [freeplane/freeplane#2018]
**Describe the bug**
When I export the file to png format the background color comes out black

**To Reproduce**
1. Go to 'File'
2. Click on 'Export map'
3. Scroll down to 'png'

**Expected behavior**
png image should be normal colors

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Screenshots**
![Azer Abdelmalek](https://github.com/user-attachments/assets/339f01ca-b7f4-4bd7-b39b-11698b6a1b44)

**Desktop (please complete the following information):**
 - Java Version

**Additional context**

**Comment by euu2021** [comment]
Try disabling: Preferences…->Appearance->Default colors->Transparent background for printing

**Comment by ebussf** [comment]
It worked. Thank you very much.
