### ISSUE TITLE
Increased distance between children (branches) when grandchildren are multi-line

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#2019]
### Single level -- distance between children is as expected

![2024-09-05_08,46,01](https://github.com/user-attachments/assets/c70965a4-9986-47d5-8d03-acffc22f6a8d)

### Two levels with single-line grandchildren -- distance between children (branches) is as expected
![2024-09-05_08,55,23](https://github.com/user-attachments/assets/a13b9e4e-5231-4867-b0b9-bf42ea6c1096)

### Two levels -- distance between children (branches) is different depending on grandchildren being single or multi-line

![2024-09-05_08,33,36](https://github.com/user-attachments/assets/08165439-c463-4104-8d83-598dba09e39f)

![2024-09-05_08,38,24](https://github.com/user-attachments/assets/60e91a62-5933-4cf0-a701-80aef12a7346)

![2024-09-05_08,39,02](https://github.com/user-attachments/assets/49dfaf34-91bd-4ae7-8135-2352c0d7f539)

![2024-09-05_08,39,33](https://github.com/user-attachments/assets/c55c6b8c-d130-4bef-a04b-db474b6b263e)

### Expected: distance between children (branches) is retained (not increased) when grandchildren are multi-line

Freeplane 1.12.6-pre

[test-distance-between-branches.mm.zip](https://github.com/user-attachments/files/16885282/test-distance-between-branches.mm.zip)

**Comment by dpolivaev** [comment]
It is intentional

**Comment by dpolivaev** [comment]
I know why I implemented it as you describe: even if a node has only one child, the child itself could have multiple children, and I do not want to check it down the tree. Therefore the gap is increased if the width of the children exceeds the width of the node even if there is only one child.

**Comment by macmarrum** [comment]
I think it's equally undesirable to use an increased child gap between branches when they are multi-child.

In [test-distance-between-branches.mm.zip](https://github.com/user-attachments/files/16885282/test-distance-between-branches.mm.zip), I use the following script filter to use a different child gap for nodes with more than one child (you can enable it in map conditional styles)
```groovy
def hasMoreThanOneChild(n) {
 def ch = n.children
 return ch.size() > 1 || ch.any { hasMoreThanOneChild(it) }
}
node.children.any { hasMoreThanOneChild(it) }
```
In any other situation, I'd like to see the same gap between nodes and branches.

What is your option about adding some kind of an option to Freeplane to configure it? Something like 

- [ ] Use an increased distance around "fat" branches

or 

`7 px` Extra distance around "fat" branches

where `7 px` is editable

By "fat" I mean the situation when (as you put it) *the width of the children exceeds the width of the node even if there is only one child*.

**Comment by dpolivaev** [comment]
I closed the issue as "not a bug", and I think it is a correct judgement.

If you want to convince me to change the existing logic, you need to show that the majority of Freeplane users supports your claim.

Unfortunately, I do not use Freeplane often enough myself to agree or disagree with your arguments.

And I am generally against adding new options that the majority of the users is not likely to discover.

Regards.

**Comment by macmarrum** [comment]
Thank you for your opinion.

I'd like to learn a bit more about why you think the majority of users wanted an extra gap around fat branches in the first place. Was there a discussion, a request or something like that before?

This will help me prepare for a further discussion.

**Comment by dpolivaev** [comment]
https://github.com/freeplane/freeplane/discussions/672

And please do not discuss it with me here. We have this status quo since  about 2 years, and if you want to change it, you can start a general discussion with other community members.

**Comment by macmarrum** [comment]
Thank you for pointing me to #672. I remember it now.

Having re-read the thread, I can tell you that I'm not interested in reigniting the discussion. I think the implemented solution is good enough for the majority of users.

Now that I can locate the commit related to the change, in my fork I will modify the code to fit my needs.

Thank you for your patience in getting to this point with me. I appreciate it.
