### ISSUE TITLE
Tags: editing in bulk on multiple node selection

### ISSUE THREAD

**Issue by Dmytro-Shulha** [freeplane/freeplane#2020]
## Test steps:

Select several nodes;
Right Click -> Edit ->Edit tags (Alt+F8)
Add/Remove some tags;
Click OK.

## Expected result:

Tags are added/removed for all selected nodes.

## Actual result:
Tags are added/removed only for the first clicked node in a selection.

**Comment by euu2021** [comment]
The Edit Tags menu is for one individual node. It doesn't refer to a group of nodes.

You need to use those two options, in order to make bulk operations:

![image](https://github.com/user-attachments/assets/f3a85cd0-40e8-4010-90c1-ce3cd6d42cc4)

Drag and drop into the map also works.

**Comment by dpolivaev** [comment]
I mean it is implemented as euu described

**Comment by Dmytro-Shulha** [comment]
Yes, indeed - that works as I wanted it to.
Thank you :)
