### ISSUE TITLE
JPG export does not work

### ISSUE THREAD

**Issue by scm1599** [freeplane/freeplane#2022]
**Describe the bug**
JPG export does not work.

**To Reproduce**
1. Go to 'File'
2. Click on 'Export Map'
3. Select 'Compressed image (JPEG) (.jpg)'
4. Save
5. See error: "Export failed", JPG File is generated with 0 Bytes

**Expected behavior**
A JPG file is written.

**Mind map files**
Tested with "freeplaneFunctions.mm", found in install files

**Screenshots**
![Unbenannt](https://github.com/user-attachments/assets/0f737838-5a33-4525-a11f-87afd05ee41a)

**Desktop (please complete the following information):**
 - Edition:	Windows 10 Pro Version	22H2
Operating system build 190.454.780
 - Java Version
Java 8 Update 421 (64-bit)

**Additional context**
Portable version used:
FreeplanePortable-1.12.5.paf.exe

**Comment by dpolivaev** [comment]
Could you please attach your log files?

**Comment by dpolivaev** [comment]
OK, I can see the problem here.

**Comment by scm1599** [comment]
Thanks

**Comment by dpolivaev** [comment]
Preview 1.12.6_03

**Comment by scm1599** [comment]
Preview 1.12.6_03 tested. JPG export now working. Thanks
