### ISSUE TITLE
FP 1.12.6_03: not possible to create new tags in the tag category editor TCE

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#2030]
**Describe the bug**
In trying to create a new tag in the TCE, the row remained empty, with the cursor blocked, and when trying to close it it happened in some cases to delete even more  existing tags
**To Reproduce**

![Screenshot 2024-09-11 202534](https://github.com/user-attachments/assets/d762aad4-acb4-4c82-9aea-e3a7dbff02b0)

**Expected behavior**
normal tag creation as in 1.12.6_01 that is working
**Mind map files**
Here the log file
[log - Copia (5).zip](https://github.com/user-attachments/files/16968489/log.-.Copia.5.zip)

note same operation was performed in another PC, with worse results (but I do not have the log file)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] W
 - Version [e.g. 22] 11
 - Java Version FP1.12.6_03

**Additional context**

**Comment by dpolivaev** [comment]
Preview 1.12.6_04
