### ISSUE TITLE
Correct color is not assigned after merging tags

### ISSUE THREAD

**Issue by i-plasm** [freeplane/freeplane#2033]
**Describe the bug**
Correct color is not assigned after merging tags

**To Reproduce**
1. Create a new mind map
1. Add these two tags to the root node (by right clicking the node and choosing `Edit -> Edit tags`):
   - `aaa::bbb`
   - `ccc::bbb`
1. Click OK
1. Open the categories manager (`Edit -> Node properties -> Manage tag categories for map`)
1. Fully expand the tags tree and notice that `ccc::bbb` color is purple
1. Merge both tags into one by changing the name of `aaa` to `ccc`
1. Click OK.
1. Right click on the root node and choose `Edit -> Edit tags`
1. Don't do anything, and just Click 'X'
1. =>>> ERROR: A message appears saying "You have changed the node. Do you want to save changes?", which indicates the tag entered some sort of "pending color change confirmation" state. If the user says 'NO' the and saves the mindmap, then reopens it, the purple color will not be preserved but will revert to green. Even if the user had manually assigned a tag color, it would have been lost.

**Expected behavior**
The correct color should have been assigned and applied to the merged tag in the Categories Manager itself.

**Desktop (please complete the following information):**
 - Freeplane v1.12.6-pre04

**Comment by dpolivaev** [comment]
Preview 1.12.6_05

**Comment by i-plasm** [comment]
Hello Dimitry, I'm testing with Preview 1.12.6_05 and it is behaving much better. Historical bugs are OK. Thanks! That said, I found a couple of extra bugs of hopefully a less serious nature but I'll post them another day. Additionally, the bug of this issue seems to not be fully fixed (I'll explain below). However, maybe it would be good to not postpone the new stable release any longer so that the crucial bug fixes are available to users IMHO. Regarding the bug of this issue, I now notice this:
1. The issue  in step 10, i.e the "You have changed the node. Do you want to save changes?" message, still occurs. So there's still an abnormal "pending confirmation" state going on.
1. The colors that end up being assigned (in the categories manager) after the merge are that of the "discarded"  tag `aaa::bbb`. I think the intention of the user -in case they have assigned custom colors- would be to keep the colors of the "preserved" tag `ccc::bbb` (why would they want to keep instead the colors of the discarded tag?). Of course this seems non-important if the user does not mind colors. But for the user employing color-coding, they would lose their color data. See:
- Before merging
![image](https://github.com/user-attachments/assets/b37d8dd3-9b59-4ef4-ae12-fea8240a2db0)
- After merging (notice the original colors of the "preserved" tag have been lost, and instead the colors of the "discarded" tag `aaa::bbb` have been adopted)
![image](https://github.com/user-attachments/assets/01c87d73-cc3b-4cae-b6ae-e9ed22f763cc)

**Comment by dpolivaev** [comment]
Preview 1.12.6_06
Thank you for testing!
I am waiting for your findings.
