### ISSUE TITLE
Categorized Root Node Tag color cannot be changed by Node Tag Editor

### ISSUE THREAD

**Issue by i-plasm** [freeplane/freeplane#2040]
**Describe the bug**
Categorized  Tag color cannot be changed by Node Tag Editor if it was previously changed in the Categories Manager and the map was saved-closed-reopened

**To Reproduce**
1. Create a new mind map
1. Add this tag to the root node (by right clicking the node and choosing `Edit -> Edit tags`):
   - `cat::tag1`
1. Click OK
1. Open the categories manager (`Edit -> Node properties -> Manage tag categories for map`)
1. Change `tag1` color to black
1. Click OK
1. Save the mindmap
1. Close the mindmap
1. Reopen the mindmap
1. On the root node, right click and choose `Edit -> Edit tags`
1. Change the color of `cat::tag1` to red
1. Click OK
1. Save mindmap
1. Close the mindmap
1. Reopen the mindmap
1. =>>> ERROR: Notice color is reverted to black. Red color has now fully been lost
1. NOTE: issue does not happen with uncategorized tags

**Expected behavior**
The color should not have been reverted

**Desktop (please complete the following information):**
- freeplane-1.12.6-pre06

**Comment by dpolivaev** [comment]
Preview 1.12.6_07
