### ISSUE TITLE
Stylename is null on pasted nodes

### ISSUE THREAD

**Issue by acebone** [freeplane/freeplane#2049]
**Describe the bug**
When text is pasted into FP, new nodes are not assigned a style name. 

They look like "default"-styled nodes, but when scripting you realise that their stylename is null.

**To Reproduce**
create a script with the following code:

```
// @ExecutionModes({ON_SELECTED_NODE})
c.statusInfo = node.style.name.toString()
```

You can put your script in `<user directory>/scripts`, then restart FP

Paste text from another application into FP so that FP creates one or more nodes from the pasted text.

select any one of the new nodes, run the script.

statusbar will say null.

**Expected behavior**
Nodes that are created by copy/paste operations should be assigned a style when they're created.

It would make most sense to assign style default.

when running the above code c.statusInfo should say "default", not "null"

Note that the style-box in the GUI will act as if the nodes were of style "default". Hence you can't see this bug in the GUI, but it has consequences when you're scripting - a work-around is to use:

```
if (!node.style.name) {
    node.style.name = 'default'
}
```

 - OS: Ubuntu 23.10
 - Freeplane: 1.12.6 
 - openjdk 17.0.11 2024-04-16
OpenJDK Runtime Environment (build 17.0.11+9-Ubuntu-123.10.1)
OpenJDK 64-Bit Server VM (build 17.0.11+9-Ubuntu-123.10.1, mixed mode, sharing)

**Comment by macmarrum** [comment]
`node.style.name` is `null` on purpose, to indicate there is no style explicitly assigned to the node. If there are no conditional styles either, Freeplane falls back to using "Default".

Please see also https://docs.freeplane.org/user-documentation/styles.html

**Comment by macmarrum** [comment]
`node.style.allActiveStyles` will give you all active styles, assigned explicitly or via other means like conditional-style rules or automatic-style rules → https://docs.freeplane.org/api/org/freeplane/api/NodeStyleRO.html#getAllActiveStyles()

**Comment by acebone** [comment]
Ok.

I enumerated a nodes style and got this: 

```
[
    "STYLE_NAME_MUST_NOT_BE_NULL",
    "allActiveStyles",
    "backgroundColor",
    "backgroundColorCode",
    "backgroundColorSet",
    "border",
    etc ....
]

```

Which led me to believe that a null-style had to be a bug.


i can't see what the idea in a non-assigned style that looks like default is, but it's a minor thing.

Thanks for the answer!
