### ISSUE TITLE
Add to find dialog an option to search in subtree

### ISSUE THREAD

**Issue by Tormen** [freeplane/freeplane#2054]
**Describe the bug**
I hope I did not miss something.
In Freeplane no possibility seems present to limit the scope of your search (both with CTRL+F and CTRL+G).

In Freemind a search (CTRL+F) was searching from currently selected Node "downwards" (towards children of this node).
But NOT around ("upwards" in direction of trunk).

Not sure if this is a bug or a feature in Freeplane. It seems like a bug; especially as, please see "additional context".

**To Reproduce**
1. Open tree
2. Go to some start-node (other than the trunk
3. Search for something that is present in the CHILDREN of the currently selected NODE 
    AND for instance in a Child of a sibling of the parent of the currently selected node.
4. Search will find both, no way to limit the search scope (that I could see)

**Expected behavior**
Search with CTRL+F (or CTRL+G) should be limited to only current node and all it's children and childrens children, etc.

**Mind map files**
I can provide if necessary.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version - sorry, I have to check (it's on my other PC)
 - Java Version

**Additional context**
Searching is essential. chosing the scope by selecting a "start"/"reference" node seems to be very intuitive.
And super useful to first search a "topic node" and then search WITHIN the topic node for keywords that you might have for SEVERAL topic nodes...

**Comment by dpolivaev** [comment]
Please explain your use case

**Comment by euu2021** [comment]
Possible workarounds:

- Jump in into the "start"/"reference" node. This will limit the scope.
- or use https://github.com/lilive/Freeplane-Jumper. Could be coupled with [UtilityPanels](https://github.com/euu2021/Freeplane_UtilityPanels/tree/main?tab=readme-ov-file#quick-search-panel), but it's still not working 100%.

**Comment by aaa1386** [comment]
I had decided to request a feature at the right time
Search in the selected node and sub-nodes(children and childrens children, etc).
Different search modes can be set, but this option is not available.
If I understand correctly, Tormen requested the same feature.

**Comment by dpolivaev** [comment]
Preview 1.12.7_03
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
