### ISSUE TITLE
text lines in "details" are weirdly breaking automatically.

### ISSUE THREAD

**Issue by edbeee** [freeplane/freeplane#2055]
**Describe the bug**
When I'm typing in bangla language the lines are automatically breaking when I set the content type "For details" to "Standard" or "text". But when I set that in "latex" it doesn't break. 

**To Reproduce**
1. Just typing the long text
2. See error

**Expected behavior**
the whole text in the "details" section setting it as "standard" or "text", should show like a paragraph if I don't put any line break intentionally. The expected behaviour can only be seen when I set the text to latex (shown in the file and screenshot), which is not usual.

**Mind map files**
Mind map .mm file:
[text breaking.zip](https://github.com/user-attachments/files/17174498/text.breaking.zip)
Exported pdf:
[text breaking.pdf](https://github.com/user-attachments/files/17174500/text.breaking.pdf)
exported image in png:
![text breaking](https://github.com/user-attachments/assets/837800dc-0ed9-407d-a0fd-3773cd6f0d3c)
Checked with different Fonts (SansSerif, Nirmala UI, and Kalpurush): 
[kalpurush.zip](https://github.com/user-attachments/files/17174532/kalpurush.zip)

**Screenshots**
Node 2:
![image](https://github.com/user-attachments/assets/09e2805a-b05a-49a5-b12f-1c1fb105934c)
you can see the that no. 2 node is set to "standard" in "for details" box. And the whole text is broken in the middle even though I didn't put any line break.

Node 3:
![image](https://github.com/user-attachments/assets/aac34c2e-3c97-4480-ba09-ebf406856e98)
As you can see Node 3 contains the same texts as written in node 2. But I set "for details" to "LaTex", which is why the whole text is showing the expected behavior. The line didn't break this time.

The same issue happened in Node 4 and 5. Even though both of the nodes contain the same text in details, they shows different behavior.
Node 4:
![image](https://github.com/user-attachments/assets/ff49349c-e3b6-4c04-b5e2-730bce01928f)
Node 5:
![image](https://github.com/user-attachments/assets/d698f4aa-ac6d-4f68-a4fe-a97d1cb68a09)

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Version [windows 10, professional, 22H2]
- Java Version 8 (also that comes with freeplane software)

**Additional context**
The fact is I put same texts in different node (I showed in the screenshot) but the behaviour is different. 
In addition, those broken nodes "details" are also creating issue while exported to pdf (attached).

**Comment by dpolivaev** [comment]
Details are internally handled as html with latex being the only exception. I do not have a fix.
