### ISSUE TITLE
Exported Latex file's error while compiling because of extra "}" sign.

### ISSUE THREAD

**Issue by edbeee** [freeplane/freeplane#2061]
**Describe the bug**
Mindmap's exported latex file always containing extra or less "}" sign which is why there is an error while compiling.
I tried to compile on both overleaf and Texstudio, I got the same behavior.
I think the the problem is producing from the "details" section. Nodes which don't contain any texts in "details" there are no problems.
**To Reproduce**
1. Go to 'File'
2. Click on 'Export map'
3. Scroll down to 'latex book or document' as the file extension
4. try to compile on any compiler, see the error.

**Expected behavior**
the exported latex file should have compiled effortlessly having no error on the structural signs.

**Mind map files**
[world war.zip](https://github.com/user-attachments/files/17189171/world.war.zip)

**Screenshots**
![image](https://github.com/user-attachments/assets/fb01d6b3-d9c8-4148-acab-0c5044363b07)
As you can see in above screenshot, there are too many "}" signs, which are causing the error. 

![image](https://github.com/user-attachments/assets/0a59954f-3bc3-4360-a18e-d185c053278b)
As you can see I have also tried to compile in book format, and found the same error.
This zip file contains the exported tex files (book and doc format) : 
[latex testing.zip](https://github.com/user-attachments/files/17189245/latex.testing.zip)

![image](https://github.com/user-attachments/assets/e91f8d6f-d46f-4ebc-a655-9280326e0a84)
as you can see in above SS the pdf is also containing extra "]" sign.

**Desktop (please complete the following information):**
OS: [Windows 10]
Version [windows 10, professional, 22H2]
Java Version 8 (also that comes with freeplane software)

**Additional context**

**Comment by edbeee** [comment]
For easier understanding I made the mindmap shorter. Note: the texts in the nodes are just random.


![image](https://github.com/user-attachments/assets/62bb9470-5ba8-44a8-88b1-9bc8fd57304b)
the above SS is the short version for the easier understanding. You can see the red highlighted lines and below in the log view the cause error is shown.

![image](https://github.com/user-attachments/assets/bb5a8e31-e7bd-40bd-a617-18d897ef2208)
above is the mindmap view. nodes which have the "details" texts are causing the problem mainly.

[world war short version.zip](https://github.com/user-attachments/files/17190295/world.war.short.version.zip) Mindmap

[latex testing short version.zip](https://github.com/user-attachments/files/17190300/latex.testing.short.version.zip) Latex file and pdf.

**Comment by dpolivaev** [comment]
Preview 1.12.7_02
