### ISSUE TITLE
Shortcut key for reducing small progress indicator is wierd.

### ISSUE THREAD

**Issue by Horseechen** [freeplane/freeplane#2065]
Version 1.12.6 for windows.
When using the small progress indicator icon of freeplane, a problem occured. Which is, when the progress needs to be reduced, the default shortcut key given by the software is Alt+Shift+less than sign, but the less than sign itself needs to be entered by the Shift key, so this shortcut key cannot actually be entered. 
Which means there isn't any shortcut key to reduce progress when using small progress icon, it's wierd. 
I think it's a design issue, and while it seems a bit unusual to reduce the progress, I do come across this use case very often. Can you change the shortcut key combination in next version?

**Comment by Horseechen** [comment]
OK, I now get to know how to set my own shortcut keys.
I've changed the shortcut key to Alt+Shift+Period for adding progress while Alt+Shift+Comma for reducing.
Maybe it's a good way for me to get used to it.
But I'm not sure if my settings would lead to conflicts for other shortcuts.
I still insist on changing the default shortcut to make it more rational.

**Comment by dpolivaev** [comment]
There are too many different keyboard layouts to perfectly support all. The change might disappoint users used to the old short cut. So I am going to keep it as it is. Pragmatism over perfection.
