### ISSUE TITLE
Filter Conditions dropdown disappears when mouse is moved

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#2068]
If I open the dropdown using the arrow, it works fine:

![javaw_S4Z8ZTp4xQ](https://github.com/user-attachments/assets/b4c3e6aa-3b39-414d-88d4-d718e0fded39)

But, if I open clicking on the white are, there is no mouse hover listener:

![javaw_6GvmUXhd33](https://github.com/user-attachments/assets/79e4ba5a-f206-4d74-b4a2-89f69fa216e4)

freeplane 1.12.7-pre01

**Comment by dpolivaev** [comment]
I do not get what you try to do.
The tooltip with the mouse listener appears not when you click but when you just move your mouse over the field with the condition.

**Comment by dpolivaev** [comment]
I have not implemented the tooltip  with the listener for the list elements. Do you need it? What for? I could add it, but I am not sure if it would be not too much because at the moment clicking on the list element selects the condition.

**Comment by euu2021** [comment]
I did not explain correctly. I'm not talking about the tooltip. What I mean is that, if I open the dropdown by clicking on the white area, the items of the list don't have the listener that avoid the list closing when the mouse is hovering over the list items. 

Notice, in the second image, that, when I try to move the mouse over the list, the list closes down immediately. I'm not clicking on any list item, there.

The problem doesn't happen if I open the list by clicking on the arrow (first gif).

**Comment by dpolivaev** [comment]
I can not see the problem here. Please attach your log file and auto.properties.

**Comment by dpolivaev** [comment]
OK, now I see how I can get it.

**Comment by dpolivaev** [comment]
Preview 1.12.7_02
