### ISSUE TITLE
org.freedesktop.Platform branch 22.08 is end-of-life

### ISSUE THREAD

**Issue by imoves61** [freeplane/freeplane#2074]
**Describe the bug**

Info: runtime org.freedesktop.Platform branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   org.freeplane.App

**To Reproduce**

Flatpak update

**Expected behavior**

Please update to 24.08

**Mind map files**

-

**Screenshots**

-

**Desktop (please complete the following information):**
 - OS:  Fedora
 - Version 40
 - Java Version

**Additional context**

-

**Comment by dpolivaev** [comment]
I do not think we have it somewhere in our project codebase. Are you sure you ask the right project? I do not even know what is org.freedesktop.Platform at all.

**Comment by imoves61** [comment]
Unfortunately I don't know much about it, but I thought the Freeplane app (on Flathub) was maintained by them. And it looks like the dependency on org.freedesktop.Platform Runtime is on 22.08, and there is now version 24.08.2?

**Comment by dpolivaev** [comment]
I have no relation to Flathub and their maintainers.

**Comment by imoves61** [comment]
Ok, sorry
