### ISSUE TITLE
Support more date and number formats in formulas

### ISSUE THREAD

**Issue by Coffee-Search** [freeplane/freeplane#2088]
The format function in formula scripting not presenting expected results for date object and format string. 

**To Reproduce**
1. Create node and add attribute "test_date" with value "2024-10-23"
2. Add the following formula to node `=format(node["test_date"].date, "yyyy")` this should present the text **2024** 
3. Copy and paste node a number of times and change the format string ...
**yyyy-MM** expect: **2024-10**
**yyyy-MMM** expect: **2024-Oct**
**MMM** expect: **Oct**  ERROR got: **2024-10-23**
**yyyy-EEE** expect: **2024-Wed**
**EEE** expect: **Wed** ERROR got: **2024-10-23**
**yyyy-dd** expect: **2024-23**
**dd** expect: **23** ERROR got: **2024-10-23**
Anecdotally, I have not tested all permutations but the format string seems to require a year  parameter (yyyy or yy) to present expected results. So 'dd/MMM', 'MMM/dd', 'dd/MM', 'MM/dd', etc. all produce unexpected results but 'MMM/yy/dd' will present **Oct/24/23**

**Screenshots**
![Screenshot from 2024-10-28 09-23-40](https://github.com/user-attachments/assets/d5c6f028-1612-41f8-909f-b960c058cf6a)

 - OS: Ubuntu 24.04.1 LTS, Java Version: openjdk version "1.8.0_422", OpenJDK Runtime Environment (build 1.8.0_422-8u422-b05-1~24.04-b05), OpenJDK 64-Bit Server VM (build 25.422-b05, mixed mode)
 - OS: Windows 11, Java 1.8.0_421-b09
 - Freeplane Version 1.12.6

[date_formatting_tests.zip](https://github.com/user-attachments/files/17540604/date_formatting_tests.zip)

**Comment by dpolivaev** [comment]
Preview 1.12.7_04
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
