### ISSUE TITLE
Apple could not verify “Freeplane” is free of malware that may harm your Mac or compromise your privacy.

### ISSUE THREAD

**Issue by simonLeary42** [freeplane/freeplane#2089]
I downloaded `Freeplane-1.12.6-apple.dmg` and `Freeplane-1.12.7-pre03-apple.dmg` from Sourceforge (and installed via homebrew) and my computer really does not want to open them. I can go into settings and create a temporary (1 hour) exception for this program, and then confirm with my sudo password that I really want to open the application, but at this point I don't want to.

**Comment by simonLeary42** [comment]
found this: https://sourceforge.net/p/freeplane/discussion/758437/thread/1d0afce2/

**Comment by dpolivaev** [comment]
The applications (Freeplane.app) were actually signed, but not the dmg files. Now I signed them too and reuploaded them. Can you please try to download Freeplane-1.12.6-apple.dmg and Freeplane-1.12.7-pre03-apple.dmg again and to check if they are fixed?

**Comment by dpolivaev** [comment]
Also applied to preview 1.12.7_04

**Comment by simonLeary42** [comment]
Same issue. Opening the DMG file and dragging/dropping Freeplane into `Applications` didn't throw any errors, but I still get the same warning trying to open Freeplane after doing so.

<img width="288" alt="image" src="https://github.com/user-attachments/assets/b6cf7b89-7031-4666-8a1c-a30ed959e9f9">

**Comment by dpolivaev** [comment]
I see, please try preview 1.12.7_05
Thank you for letting me know.

**Comment by simonLeary42** [comment]
fixed!

**Comment by bopm** [comment]
1.12.7_05 is ok, but 1.12.7_06 is facing same issue again

**Comment by dpolivaev** [comment]
Thanks, I fixed the signatures and reuploaded the file
