### ISSUE TITLE
Compatibility Issue with Open JDK 8 Red Hat in Latest Freeplane Versions

### ISSUE THREAD

**Issue by NivedithaVeerapuraSiddappa** [freeplane/freeplane#2093]
I am reaching out regarding a compatibility issue encountered with recent versions of Freeplane, which currently require Open JDK 11 or higher as a dependency. Unfortunately, this update has impacted users who rely on Open JDK 8 (particularly the Red Hat variant) due to dependencies with other applications.

Given the broad use of Open JDK 8 in our environment, we would like to check if there is any possibility of making the latest Freeplane versions compatible with Open JDK 8. 
Alternatively, are there any plans within the Freeplane roadmap to address this dependency requirement, or might there be a workaround available?

Your input on this matter would be greatly appreciated, as well as any guidance on potential solutions. 

Thank you for your ongoing support and efforts in making Freeplane an outstanding tool :)

**Comment by dpolivaev** [comment]
Hello, I am not aware of any issues related to Java 8. It should work. Please add logs and terminal output and tell me which distribution package you use and where you got it.

**Comment by NivedithaVeerapuraSiddappa** [comment]
Hello,
As documented on the official Freeplane page, Java versions 11 to 17 are required:
“Freeplane-Setup-xxx.exe: Windows installer which requires Java 11 to 17 to be installed independently.”
(Source: https://docs.freeplane.org/getting-started/Distributions.html)


Additionally, when we installed Freeplane on user clients with Java 8, the application fails to run and throws an error indicating that Java 11 or a higher version is required for it to function properly.

Currently, we have Freeplane version 1.12.4 deployed on user clients, sourced directly from the official site.

**Comment by dpolivaev** [comment]
I do not know which update you mean. 
I fixed the documentation to say "8 to 22".
Please check if value of FREEPLANE_JAVA_HOME is set correctly and upload screenshots.
