### ISSUE TITLE
View mind map not updated after a script moved a node to it from another mind map

### ISSUE THREAD

**Issue by HaaiHenkie** [freeplane/freeplane#2094]
[ViewNotUpdated.zip](https://github.com/user-attachments/files/17604567/ViewNotUpdated.zip)
**Describe the bug**
As part of an add-on I have developed a script that moves nodes to an archive mind map. Since 1.12.x (tested with 1.12.3 and 1.12.6) there is a problem: the moved nodes are not visible in the target mind map after the script finishes. With 'File -> Reload mind map version' you can make them visible again. In Freeplane version 1.11.14 and earlier the mind map view was updated properly,

**To Reproduce**

The problem can be reproduced with ViewNotUpdated.groovy in the attached zip file:
[ViewNotUpdated.zip](https://github.com/user-attachments/files/17604567/ViewNotUpdated.zip)

1. In the script: create a target file
2. In the script: create a source file with a child node
3. In the script: move the child node from the source file to the target file
4. In the view of the source file the child node is removed, but in the view of the target file the child node is not added
5. If you reload the last save version of the target file you will see that de child node is there

**Expected behavior**
I am expecting that the copied child is visible in the target file immediately after the execution of the script. It was like this in Freeplane 1.11.14 and earlier.

**Mind map files**
The necessary mind maps are automatically created by the zipped script:
[ViewNotUpdated.zip](https://github.com/user-attachments/files/17604567/ViewNotUpdated.zip)

**Screenshots**
The problem is sufficiently demonstrated by the attached zipped script.

**Desktop (please complete the following information):**
 - OS:Windows
 - Version11
 - Java Version: 8 and 17

**Additional context**
I can implement a workaround by adding the following lines at the end of the script:

~~~groovy
mindMapViewNotUpdated.close(true, false)
c.mapLoader(fileViewNotUpdated).withView().mindMap
~~~

**Comment by dpolivaev** [comment]
Preview 1.12.7_04
