### ISSUE TITLE
Right-Click Context Menu not shown on Map Background under Windows

### ISSUE THREAD

**Issue by abc16361** [freeplane/freeplane#2098]
**Describe the bug**
Right-click context menu on background (NOT on nodes) fails to show up on the recent versions of 1.12.7-pre 04 and 05.  

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version 1.12.7-pre 04 and 05
 - Java Version: zulu21.36.17-ca-jdk21.0.4-win_x64.msi

**Comment by dpolivaev** [comment]
Preview 1.12.7_06
