### ISSUE TITLE
Freeplane crashes on startup under Fedora 41 with OpenJDK 21

### ISSUE THREAD

**Issue by TNing** [freeplane/freeplane#2101]
**Describe the bug**
On startup using ./freeplane.sh it crashes with the following log output:

WARNING: package sun.swing.shell not in java.desktop
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.freeplane.launcher.Launcher (file:/opt/freeplane-1.12.6/freeplanelauncher.jar)
WARNING: Please consider reporting this to the maintainers of org.freeplane.launcher.Launcher
WARNING: System::setSecurityManager will be removed in a future release
Knopflerfish OSGi framework launcher, version <unknown>
Copyright 2003-2020 Knopflerfish. All Rights Reserved.
See http://www.knopflerfish.org for more information.

Created Framework: org.knopflerfish.framework, version=8.0.11.
Background mode.
Nov. 07, 2024 2:43:10 PM org.freeplane.core.util.LogUtils info
INFORMATION: Loaded properties from bundle://1:1/freeplane.properties
Nov. 07, 2024 2:43:10 PM org.freeplane.core.util.LogUtils info
INFORMATION: Loaded properties from bundle://1:2/org/freeplane/main/application/
Installed: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.bugreport (id#2)
Installed: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.codeexplorer (id#3)
Installed: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.formula (id#4)
Installed: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.jsyntaxpane (id#5)
Installed: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.latex (id#6)
Installed: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.markdown (id#7)
Installed: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.openmaps (id#8)
Installed: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.script (id#9)
Installed: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.svg (id#10)
Started: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.bugreport (id#2)
Started: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.codeexplorer (id#3)
Started: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.formula (id#4)
Started: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.jsyntaxpane (id#5)
Started: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.latex (id#6)
Started: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.markdown (id#7)
Started: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.openmaps (id#8)
Started: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.script (id#9)
Started: reference:file:/opt/freeplane-1.12.6/plugins/org.freeplane.plugin.svg (id#10)
Nov. 07, 2024 2:43:11 PM org.freeplane.core.util.LogUtils info
INFORMATION: language resources for de found
Nov. 07, 2024 2:43:11 PM org.freeplane.core.util.LogUtils info
INFORMATION: freeplane_version = 1.12.6; freeplane_xml_version = freeplane 1.12.1
git revision = 6c38f557492aa51dd5c79fa4793a7a222e8d1d03 dpolivaev 2024-09-16T12:00:35Z
java_version = 21.0.5; os_name = Linux; os_version = 6.11.6-300.fc41.x86_64
Nov. 07, 2024 2:43:11 PM org.freeplane.core.util.LogUtils info
INFORMATION: added parsing support for standard date format dd.MM.yy
Nov. 07, 2024 2:43:11 PM org.freeplane.core.util.LogUtils info
INFORMATION: added parsing support for standard date time format dd.MM.yy, HH:mm
Installing shutdown hook.
Framework launched
Nov. 07, 2024 2:43:11 PM org.freeplane.core.util.LogUtils warn
WARNUNG: Exception in org.freeplane.core.ui.components.OneTouchCollapseResizer.setExpanded(enabled): java.lang.RuntimeException: Method not implemented
Nov. 07, 2024 2:43:11 PM org.freeplane.core.util.LogUtils severe
SCHWERWIEGEND: Exception in thread "pool-1-thread-1"
java.lang.RuntimeException: Method not implemented
	at org.freeplane.main.headlessmode.HeadlessMapViewController.getMapViewComponent(HeadlessMapViewController.java:185)
	at org.freeplane.plugin.codeexplorer.map.ShowDependingNodesAction.<init>(ShowDependingNodesAction.java:57)
	at org.freeplane.plugin.codeexplorer.map.CodeMapController.<init>(CodeMapController.java:66)
	at org.freeplane.plugin.codeexplorer.CodeModeControllerFactory.createModeController(CodeModeControllerFactory.java:72)
	at org.freeplane.plugin.codeexplorer.Activator$1.installExtension(Activator.java:49)
	at org.freeplane.main.osgi.ActivatorImpl$OsgiExtentionInstaller.installExtensions(ActivatorImpl.java:271)
	at org.freeplane.main.osgi.ActivatorImpl.installControllerExtensions(ActivatorImpl.java:307)
	at org.freeplane.main.osgi.ActivatorImpl.access$100(ActivatorImpl.java:66)
	at org.freeplane.main.osgi.ActivatorImpl$2.run(ActivatorImpl.java:230)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

^CShutdown hook invoked, stopping OSGi Framework.

**With OpenJDK 17 (openjdk 17.0.13 2024-10-15, OpenJDK Runtime Environment (Red_Hat-17.0.13.0.11-1) (build 17.0.13+11)) it works flawlessly.**

**To Reproduce**
1. Install Fedora 41 (or any Linux using OpenJDK 21 I guess)
2. Download freeplane-1.12.6 from https://sourceforge.net/projects/freeplane/files/freeplane%20stable/
3. Copy freeplane-1.12.6.zip to /opt
4. cd /opt; unzip freeplane-1.12.6.zip (as root user)
5. cd /opt/; ln -s freeplane-1.12.6 freeplane (as root user)
6. cd /opt/freeplane; ./freeplan.sh (as normal user)

**Expected behavior**
Freeplane starts up and works flawlessly.

**Mind map files**
none

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Fedora Linux 41 (uname -a : Linux hex 6.11.6-300.fc41.x86_64 1 SMP PREEMPT_DYNAMIC Fri Nov  1 16:16:00 UTC 2024 x86_64 GNU/Linux)
 - Version: Freeplane 1.12.6
 - Java Version: OpenJDK 21 (openjdk 21.0.5 2024-10-15, OpenJDK Runtime Environment (Red_Hat-21.0.5.0.11-1) (build 21.0.5+11))

**Additional context**
none

**Comment by dpolivaev** [comment]
Lines 
java.lang.RuntimeException: Method not implemented
at org.freeplane.main.headlessmode.HeadlessMapViewController.getMapViewComponent(HeadlessMapViewController.java:185)

indicate that you try to use Java version not including UI (headless)

**Comment by TNing** [comment]
Argh, you are absolutly right, mea culpa. They only install the newest headless version if you upgrade your OS, no matter what you have installed before.

Thanks for the fast support

**Comment by chriscz** [comment]
Yeah, interestingly libreoffice runs with the headless version. After doing 

```
sudo dnf install java-21-openjdk
```

Freeplane worked.

When I looked at `update-alternatives` it was not obvious that the java version I had installed was headless, but the packages don't lie. `java-21-openjdk-headless` installed by default.

Thanks for helping.
