### ISSUE TITLE
HTML paragraph alignment is not considered

### ISSUE THREAD

**Issue by tukanos** [freeplane/freeplane#2109]
**Describe the bug**
Setting paragraph formatting in the *Edit node details* dialog is ignored in the node displayed. 

**To Reproduce**
1. Create forth level node
2. Select Edit -> Edit node details in dialog
3. Format the node
4. See no change in the view 

**Note:** If you double click it to edit you can see moving it according to the formatting.

**Expected behavior**
See the node details formatted as show in the dialog

**Screenshots**
![node_details_formatting](https://github.com/user-attachments/assets/e9a46d05-4558-4a5b-89ae-cb145fc1b1f8)

**Desktop (please complete the following information):**
-    Freeplane version: 1.12.7 (latest preview)
-    OS: Debian
-    Version: Testing - Trixie
-    Java version: OpenJDK Runtime Environment Zulu11.68+17-CA (build 11.0.21+9-LTS)

**Comment by dpolivaev** [comment]
Preview 1.12.9_01

Fixed but only if node text alignment is "on the left"
