### ISSUE TITLE
Connector dialog window gets closed automatically without any user action

### ISSUE THREAD

**Issue by tukanos** [freeplane/freeplane#2112]
**Describe the bug**
If I have a connector going between two nodes and I have mouse auto-raise feature turned on then if I move the mouse out of the dialog window it gets closed automatically without any user interaction.

**To Reproduce**
1. Have two nodes 
2. Create a connection (connector) between the two
3. Have a auto-raise feature turned on
5. Open the connector dialog and move it outside the dialog window while still being on Freeplane main window
6. The window will automatically close without any clicking

**Expected behavior**
The connector dialog window should stay open until user has pressed OK button or X on window decoration.

**Mind map files**
Applies to any

**Screenshots**
Not applicable

**Desktop (please complete the following information):**

 -   Freeplane version: 1.12.7 (latest preview)
 -   OS: Debian
 -   Version: Testing - Trixie
 -   Java version: OpenJDK Runtime Environment Zulu11.68+17-CA (build 11.0.21+9-LTS)

**Additional context**
Found it by accident as I have moved the mouse outside the window to check the information above.

**Comment by dpolivaev** [comment]
The dialog emulates pop-up menu, and therefore it closes if you click somewhere else. I think that auto-raise feature probably behaves like mouse click when you leave the dialog window.
