### ISSUE TITLE
Since v1.11.11: No feedback for a variety of script errors

### ISSUE THREAD

**Issue by i-plasm** [freeplane/freeplane#2114]
**Describe the bug**
I've noticed when creating and using scripts that I'm not getting feedback in the status bar for errors inside `try-catch` blocks like I used to in the old freeplane versions. I found out this behaviour started since Freeplane v1.11.11.

With exceptions like `IOException`, Freeplane displays an error popup, which is good feedback despite the status bar not incrementing the error counter. However with exceptions like `Exception`, `RuntimeException` there's no feedback whatsoever. (checked vs. unckecked issue?)

Previous versions offered convenient feedback to the user that the script is not working as it is supposed to via the error counter in the status bar. A couple of commits since Febrary 24, 2024 changed the way freeplane handles exceptions (for context, see discussion https://github.com/freeplane/freeplane/issues/1686#issuecomment-1962385924). I often don't get warned of important errors in scripts and I notice too late, so it would be very helpful  and safer if the old behaviour could be restored. Thanks for considering it!

**To Reproduce**

## Example # 1

1. *Deny* permission to execute other applications` at `Preferences…->Plugins->Scripting->Permit to execute other applications`
1. Save this groovy script in the `scripts` folder, restart Freeplane, and then run the script on any map.
    ~~~ groovy
        import java.awt.Desktop
        import java.net.URI
        
        try {
	        browseViaDesktop(new URI("https://www.google.com/"))
        } catch (Exception e) {
          e.printStackTrace()
        }
        
            public static void browseViaDesktop(URI uri) throws IOException {
              Desktop desktop = Desktop.getDesktop()
              if (Desktop.isDesktopSupported() && desktop.isSupported(Desktop.Action.BROWSE)) {
                desktop.browse(uri)
              }
            }
    ~~~
1. RESULT>>> Status bar error counter is not shown/incremented
1. NOTE: If I indicate `IOException` instead of `Exception` in the `catch` then Freeplane will display an error popup. However, sometimes script require the use of `Exception`.

## Example # 2

1. Save this groovy script in the `scripts` folder, restart Freeplane, and then run the script on any map.
    ~~~ groovy
    String str
    try {
      str.length()
    } catch (Exception e) {
      e.printStackTrace()
    }
    ~~~
1. RESULT>>> Status bar error counter is not shown/incremented

**Expected behavior**
Status bar error counter should be shown and incremented

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: all versions since Freeplane v1.11.11
 - Java Version: 17

**Comment by dpolivaev** [comment]
In your both scripts, there is a catch block that catches the exception. Currently, Freeplane no longer considers the caught exceptions to be errors because there were too many false positive bug reports triggered by some libraries.

To help you I have just added new method showErrorLogButton() to LogUtils so that you can call it from your scripts when needed, see https://github.com/freeplane/freeplane/commit/6f0fa8666ab2b514cf40c02cf12a048bac40fe51

Does it help?
Currently the change is only in the source code, and we can further improve the solution.

**Comment by i-plasm** [comment]
Hi Dimitry, I think having a way to show the error button is a step in the right direction. But from what I interpret from your comment, its counter would not be incremented on subsequent errors, so there would still be a feeling of false security (again I'm not sure if I understood well! ).

It occurs to me that if the problematic libraries are limited to just a few, that perhaps a good compromise would be to specifically silence out the errors from those libraries, and leave the rest of the error logging behavior as it was until freeplane v1.11.10. But if this is not possible or is complicated, I will just revise all my scripts and insert a JOptionPane or UITools popup inside the catch blocks as an alert. The valuable logging to the local file would be lost, though. In any case, thanks for considering my request!

**Comment by dpolivaev** [comment]
Raising alert and sending to me the error report seems to make no sense if you have your catch block around the exception. It does not affect content of your log file. Therefore you can use the new method if you want to have behavior as before for your scripts.

If your case is different, please explain.

**Comment by i-plasm** [comment]
I can understand now that displaying the button will be enough, everything else still would work as in older freeplane versions. I only need feedback for myself, not sending bug reports, so it seems it would be a solution. Thanks.

**Comment by dpolivaev** [comment]
Preview 1.12.9_01 with new API is available
