### ISSUE TITLE
FP 1.12.7_08 & FP 1.12.8_01: not possible to insert text in new nodes

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#2115]
**Describe the bug**
When creating a new node with previous releases I could immediately write the test in the node (this is the expected behavior), here in both these new releases (and I tried on 2 different PCs): I must 1st  create the node (as empty) and 2nd write the text.

**To Reproduce**
1. use the attached map with one of those releases
2. Create a new node with enter and type immediately the text
3.  you will discover that everything remains frozen

**Screenshots**
Here 2 screenshots of how the nodes remain forzen
![Screenshot 2024-11-18 200728](https://github.com/user-attachments/assets/189ea45f-f5f6-4074-a3b3-ffc9659c622f)
![Screenshot 2024-11-18 200852](https://github.com/user-attachments/assets/cb59e93d-1590-4f11-b3fb-1926cc48ab50)
log file
[log.zip](https://github.com/user-attachments/files/17805364/log.zip)
the map
[Try.zip](https://github.com/user-attachments/files/17805363/Try.zip)
**Expected behavior**
I wish to immediately write the test in the node

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] W11
 - Java Version embedded in FP

At the moment I switched down to FP 1.12.7_07 that is working fine.

**Comment by dpolivaev** [comment]
Preview 1.12.8_02

**Comment by Illegit** [comment]
Working nicely. Thanks
