### ISSUE TITLE
Right-clicking or pressing  'CTRL + F' on Markdown note edit-mode exits it

### ISSUE THREAD

**Issue by i-plasm** [freeplane/freeplane#2116]
**Describe the bug**
Right-clicking or pressing `CTRL + F` on Markdown note edit-mode exits it

**To Reproduce**
1. Activate `View->Notes->Display note panel`
1. On any node, choose "markdown" content type for the node's note
1. Edit note by double-clicking note panel
1. In the editor, right-click in order to display context menu
   - Alternatively, type `Ctrl + F` for displaying the markdown editor search bar
1. ERROR >>> Editing mode exits unexpectedly and the menu/bar ends up erroneously shown in the non-editable view 

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version: Freeplane 1.12.6

**Comment by dpolivaev** [comment]
Preview 1.12.9_01
