### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [freeplane/freeplane#2129]
Dear @freeplane team, @dpolivaev,

Can you remove old tabs:
- https://sourceforge.net/p/freeplane/blog/
- https://sourceforge.net/p/freeplane/wiki/
- https://sourceforge.net/p/freeplane/discussion/
- https://sourceforge.net/p/freeplane/_list/tickets
- External links: Code (GitHub) / Developer List / Home page (wiki) / Old forum
-> After you can add a new one external link for GitHub to have a good tab

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/freeplane/

To disable/delete tabs, go here: https://sourceforge.net/projects/freeplane/
To add a new tab, go here: https://sourceforge.net/projects/freeplane/
To change informations, go here: https://sourceforge.net/p/freeplane/admin/overview
To export, go here: https://sourceforge.net/p/freeplane/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/freeplane/admin/overview
- A new tab, go here: https://sourceforge.net/projects/freeplane/

Thanks in advance.

**Comment by dpolivaev** [comment]
Thank you for the hints. I added the "Moved" box, deleted the blog and hid the source forge wiki. I want to keep all information available in case someone might still need it.

Do you think it is enough?

**Comment by Neustradamus** [comment]
@dpolivaev: Thanks for the first step!
Like I have sent you, there are other parts, can you remove old parts?
- https://sourceforge.net/p/freeplane/discussion/
- https://sourceforge.net/p/freeplane/_list/tickets
- External links: Code (GitHub) / Developer List / Home page (wiki) / Old forum
-> After you can add a new one external link for GitHub to have a good tab

Thanks in advance.

**Comment by dpolivaev** [comment]
I intentionally want to keep old discussion forums as readonly so that information remains available. But I have additionally hidden the old sourceforge tickets.

**Comment by Neustradamus** [comment]
@dpolivaev: Thanks!

You can create an export ^^

Maybe you can add the links into the description:
-> https://freeplane.org/
-> https://docs.freeplane.org/
-> https://github.com/freeplane/freeplane

**Comment by dpolivaev** [comment]
I do not see how the export can make old discussions available online, and sometimes people still find interesting pieces of information there. Therefore I am not deleting them.

If you have an idea how I could modify the description please send me the text, if I like it I can use it.

**Comment by Neustradamus** [comment]
@dpolivaev: On SF here: "Application for Mind Mapping, Knowledge Management, Project Management. Develop, organize and communicate your ideas and knowledge in the most effective way."

You can add:
-> https://freeplane.org/
-> https://docs.freeplane.org/
-> https://github.com/freeplane/freeplane

**Comment by dpolivaev** [comment]
Done

**Comment by Neustradamus** [comment]
@dpolivaev: Thanks :)

**Comment by walmar** [comment]
> I have additionally hidden the old sourceforge tickets.

@dpolivaev, I would like to read the valuable [Tickets](https://web.archive.org/web/20240310165506/https://sourceforge.net/p/freeplane/_list/tickets) on SourceForge without having to create an account.

**Comment by dpolivaev** [comment]
@walmar 
In this ticket another user requested that I hide the tickets. You suggest that you can access them. 
I have no own opinion. If you reach an agreement with the rest of the community and specifically with the person who wrote this ticket, I'll make the old tickets visible again.

**Comment by Neustradamus** [comment]
Like I have specified before, all Sourceforge tickets can be exported and imported after:
- https://sourceforge.net/p/forge/documentation/Project%20Data%20Export/

------------------------------

migrates tickets to GH from SF
https://github.com/cmungall/gosf2github

https://github.com/highperformancecoder/minsky/issues/36#issuecomment-328296734

------------------------------

Move sourceforge tickets to github
https://github.com/Ajnasz/sf2gh

------------------------------

Google search:
- https://www.google.com/search?q=sourceforge+ticket+exporter+importer+GitHub

**Comment by walmar** [comment]
@dpolivaev, to me it looks like the initiator wants to agree with himself, when asking you again to migrate data, while you – without any opinion of your own – have simply decided to hide the data instead, that the community has freely contributed to the project in public.

Perhaps you could come to an agreement with the issue opener that you will not migrate the data and leave it publicly readable on SourceForge as before.

**Comment by dpolivaev** [comment]
For me both seeking an agreement and doing the migration seems to be too difficult and stressful. If you could do any of it, I would appreciate it. Regards.

**Comment by walmar** [comment]
From my side: I have expressed my opinion that the information should remain available to the public.

I don't need friction either. So, lesson learned: I'll be more reserved, as I usually do, when time passes and changes are made that I don't entirely agree with.

I understand that it is not straightforward to transfer hunderds of unlabeled entries from users – who do not need to have a GitHub account – that have remained untouched for years to another platform.
Unlike the issue opener, I would not ask you to migrate without examining the situation and explaining exactly how this can be achieved.

Anyway, thank you for sharing your views and for your continued support on GitHub.

**Comment by dpolivaev** [comment]
The only hope is that issue opener @Neustradamus  recognizes that his idea created more harm than good and it would allow me to open the readonly access to the old tickets and discussions.
