### ISSUE TITLE
Filtering / Freeplane jumps out of pinned node when selecting nodes by using a predefined filter

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#2130]
### Scenario
After using the `Jump in` command on a node, Freeplane is jumping out of that node, as soon as nodes are being selected through a predefined filter. 

### Steps
Please see video.
![Video](https://github.com/user-attachments/assets/cf65b555-dee5-48de-b751-d5038f0518ff)

### Version
Freeplane 1.12.6

Freeplane is ❤ :)

**Comment by dpolivaev** [comment]
Preview 1.12.9_01
