### ISSUE TITLE
Freeplane 1.12.8 inoperable (won't open) on mac OS Ventura 13.7.1

### ISSUE THREAD

**Issue by Pollywoggle** [freeplane/freeplane#2137]
hello, I'm Mindmapping on an iMac (mid 2017 model). Daily Freeplane user.  
I updated to Freeplane 1.12.8 earlier today (after a long span of not updating Freeplane). Unfortunately I overwrote the prior version 1.12.1 when installed.

remedied by locating and installing Freeplane version 1.12.3

**Expected behavior**
Freeplane application would open when prompted. 

**Mind map files**
(operational with prior version)

**Screenshots**
<img width="401" alt="Screenshot 2024-12-07 at 3 59 58 PM" src="https://github.com/user-attachments/assets/58d1f813-2f1d-45b0-b42b-ea9b04b2861b">
<img width="276" alt="Screenshot 2024-12-07 at 4 00 24 PM" src="https://github.com/user-attachments/assets/6a259d10-aea8-40e0-90ef-b198814dac73">

**Desktop (please complete the following information):**
 - OS: Mac OS, Ventura 13.7.1 (highest apple OS issued for this iMac model)
 - Version:  Freeplane 1.12.8
 - Java Versions: 
JavaLaunching:  Version:	1.0
JavaNativeFoundation:  Version:	81
JavaRuntimeSupport:  Version:	79
JavaScriptAppleEvents:  Version:	1.0
JavaScriptCore: Version:	18615
JavaScriptOSA:  Version:	1.1
JavaVM:  Version:	15.0.3

**Additional context**
remedied by locating and installing Freeplane version 1.12.3. Was a bit tricky to find, but worked :)

**Comment by Pollywoggle** [comment]
Edit:  oh. oops, I apparently downloaded "Apple" instead of Intel. Intel v1.12.8 works on my iMac.

**Comment by dpolivaev** [comment]
Yes, I made apple silicon version the new default download for macs, now intel mac users need to be extra careful.
Unfortunately, Java does not support packaging universal binaries.

**Comment by Pollywoggle** [comment]
Thank you Dimitry for your helpfulness & work!

**Comment by elsabricot** [comment]
Hi, 
Got some kind of a similar issue : 
Downloaded [Freeplane-1.12.4u1-JDK21-intel.dmg] for my macbook pro 2,3 GHz Intel Core i5 double cœur. It seems like it might open it (the logo is not crossed or blurry) BUT apple tells me it can't open the app because he can't check it for malwares... Anyone with a similar issue ? Some help ?

Thanks :)

**Comment by Pollywoggle** [comment]
> Hi, Got some kind of a similar issue : Downloaded [Freeplane-1.12.4u1-JDK21-intel.dmg] for my macbook pro 2,3 GHz Intel Core i5 double cœur. It seems like it might open it (the logo is not crossed or blurry) BUT apple tells me it can't open the app because he can't check it for malwares... Anyone with a similar issue ? Some help ?
> 
> Thanks :)

Hi @elsabricot I had this happen as well, I believe it is a standard apple response for when there's independent software being installed. I can say that my updated freeplane app is working well after a month. Try right-clicking on the app in your applications folder, and it should give you a choice to 'open anyway'.

**Comment by dpolivaev** [comment]
Freeplane-1.12.4u1-JDK21-intel.dmg is a very old version. Try the latest one, I think the problem is solved now.

**Comment by elsabricot** [comment]
Hi, thanks, it works well now !
