### ISSUE TITLE
Glossary in Weblate (online translation tool): How to remove a word?

### ISSUE THREAD

**Issue by ldmpub** [freeplane/freeplane#214]
**Context**
I made a type mismatch ("overWiew" entered instead of "overView").

**Problem**
I didn't find any way to remove (or to correct) the source string.
See: https://hosted.weblate.org/translate/freeplane/glossary/fr/?checksum=34ba8357c4cb8b27&sort_by=source

Thanks for the help,

**Comment by tignioj** [comment]
Edit menu->find->find and replace.
or simply type shortcut `Ctrl+Shift +F`

**Comment by ldmpub** [comment]
Glossary term has been corrected in Weblate, see https://hosted.weblate.org/translate/freeplane/glossary/fr/?checksum=c8be5e7d0c7b29dd
