### ISSUE TITLE
FP Beeps in opening

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#2141]
Hi, lately my FP is beeping every time I open it, here there is my log file; my you help in correcting it? Just suggestion.

[log.0 2024-12-08.zip](https://github.com/user-attachments/files/18052275/log.0.2024-12-08.zip)

1) SEVERE: PM org.freeplane.core.util.LogUtils severe --> no idea what to do
2) GRAVE: can not load icon '/images/formula.png' --> I cancelled this folder and the icon, but the error is still present

Anything else?
Thank you

**Comment by dpolivaev** [comment]
I think it is caused by either your configuration files or some of your add-ons. I need the complete user configuration directory to check it, but maybe you just do full text search there and find which place references it.

**Comment by Illegit** [comment]
Sorry I do not know if is that groovy: 

I have cancelled the previous files but I still get the error message as severe an involving the following addons: 
Found in menuItemInfo.groovy: import org.freeplane.core.util.LogUtils
Found in releaseAddOn.groovy: import org.freeplane.core.util.LogUtils
Found in MapDriveInator.groovy: import org.freeplane.core.util.LogUtils
Found in createAnObfuscatedMap.groovy: import org.freeplane.core.util.LogUtils
Found in packAndGoGo.groovy: import org.freeplane.core.util.LogUtils
All of these have been update to last release
Please note that I'm using FP with the zulu java: Java version: 21.0.5
Any tips? Thank you.

**Comment by HaaiHenkie** [comment]
Hi Illegit,

I saw your comment in the mail, where you were searching for ` org.freeplane.core.util.LogUtils`. I do not see that comment here, so maybe you deleted it. Anyhow, ` org.freeplane.core.util.LogUtils` indicates the Freeplane class providing the logging. So it is not part of the error itself.

The actual error concerns `/images/formula.png`, so you have to find out if this icon is mentioned somewhere. Just before the error there is logging that the `default.properties` for the formula plugin is loaded. I have found these properties in the source code and they contain the following property:

~~~ properties
formula.EvaluateAllAction.icon = /images/formula.svg?useAccentColor\=true
~~~

So far I could not find any corresponding Freeplane setting, but I think you could search in `auto.properties` in your Freeplane user directory, if some property is referring to `/images/formula.png`

**Comment by Illegit** [comment]
Thanks, HaaiHenkie, I found it in auto.properties, I canceled that row and FP is not warning any error.
