### ISSUE TITLE
Move to another branch and back like freemind

### ISSUE THREAD

**Issue by keyzci** [freeplane/freeplane#2142]
Thank you for the Freeplane update.

I have been using Freemind and FreePlane every day for over 16 years and FreePlane is a very great app.
Could you please add the following new feature as a switchable option by ON/OFF?

<As Is>
For example, currently, when I press the ”up" button of my keyboard on branch 2-1-1, the cursor will move to "branch 1".
Then press the "down" button of my keyboard on branch1, the cursor will move to "branch2".
Please see the <State of the branch> below.

<ToBe (After change)>
when I press the ”up" button of my keyboard on branch 2-1-1, the cursor will move to "branch 1".
Then press the "down" button of my keyboard on branch1, the cursor will move to "branch2-1-1" (it will return to branch2-1-1, the original location, rather than branch2).

In Freemind, the cursor will move like <ToBe After change>.
I believe it is useful for some Freeplane users.

<State of the branch>
branch1

branch2
  branch2-1 
     branch2-1-1
     branch2-1-2
  branch2-2
  branch2-3

**Comment by dpolivaev** [comment]
There is a dedicated action to go back to the previously selected node, Navigate->Go backward (Alt+←). Would it satisfy your need to quickly navigate back?

**Comment by keyzci** [comment]
Hello dpolivaev

Thank you for your reply.
At least for me, "Go backward (Alt+←)" does not satisfy me.

The reason is that when my cursor is on "branch2-1-6" and  only from branch2-1-3 to branch2-1-6 is displayed on the PC screen(branch2-1-1 is not displayed),
I need to press the "up" button multiple times to display "branch 2-1-1" on the PC screen.

After that, I realize that I have moved to branch1, so I click the "down" button, but I realize that I have moved to branch2, not branch2-1-1.

Then, I have to press "Go backward (Alt+←)" multiple times.

The target "branch 2-1-1" is not displayed on PC screen, it is difficult to know how many time I need to press "up" to show "branch 2-1-1".

The usage may differ depending on the person, but if "branch2-1-1" to "branch2-1-6" are the tasks in order from top to bottom, this case(need to press "Go backward (Alt+←)" multiple times) will happen many times.

Also, I think it's common to only open the branches I need now (e.g. branch2) and close the branches I don't need now  (e.g. branch1).

So, I think it is inconvenient that after moving from branch2-1-1 to branch1, I can not go back to the original branch2-1-1 by "down" like Freemind behavior.

branch1
branch2
  branch2-1 
    branch2-1-1
    branch2-1-2
    branch2-1-3
    branch2-1-4
    branch2-1-5
    branch2-1-6
  branch2-2 
  branch2-3

I think some people prefer the current way, so if possible, 
could you please add the new feature as a switchable option by ON/OFF?

**Comment by dpolivaev** [comment]
As you can see, github does not preserve indentation. Could you please upload zipped example mind maps? I can not follow you otherwise. And also there are too many ways what you might have in mind writing `The target "branch 2-1-1" is not displayed on PC screen`. Could you please add screen shots containing enough visual information?

**Comment by dpolivaev** [comment]
Probably you mean that node "branch2-1-1" is outside the visible part of the mind map?

**Comment by dpolivaev** [comment]
<img width="407" alt="branches" src="https://github.com/user-attachments/assets/55e4fc49-0009-4b81-aef5-ab39939124b6" />
Is this what you mean?

**Comment by dpolivaev** [comment]
What you think about the idea that when you are at node "branch2-1-1" and press "up", you should not go to branch1 at all and remain at this node? This idea was recently suggested by another user, and we are discussing it in https://github.com/freeplane/freeplane/discussions/2169

**Comment by dpolivaev** [comment]
What do you mean by "common" in your statement "Also, I think it's common to only open the branches I need now (e.g. branch2) and close the branches I don't need now (e.g. branch1).". Is it common? Where have you observed it?

**Comment by dpolivaev** [comment]
Preview 1.12.9_01, I mimic Freemind now

**Comment by keyzci** [comment]
Hello dpolivaev

Thank you for your reply.
I was traveling for a while so my reply is late.

The branch screenshot you attached is correct.
I read ”#2169”.
I think the behavior of ”#2169” is good for me.

I installed 1.12.9_01.
Moving the cursor from the current branch to a different branch is very very very useful than ever.

Thank you for immediately implementing this.
