### ISSUE TITLE
Freeplane issues when switching between multiple monitors.

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#2149]
When switching between the primary and secondary monitor, Freeplane does not adapt properly and the user has to restart the FP.
This issue occurs both when using a secondary monitor and when connecting the laptop to a video projector.
Look at the images below. I have provided the necessary explanations within the images.

**### _step 1:_**

![step 1](https://github.com/user-attachments/assets/a1e19fa7-c248-4c07-b00c-c43cd44b00aa)

**### _step 2:_**

<img width="1163" alt="srep 2" src="https://github.com/user-attachments/assets/68bb6ed8-b632-47fd-a35f-2c337f16cbda" />

**### _step 3:_**

![step 3](https://github.com/user-attachments/assets/b23a94c9-64d2-4396-b74b-fa91f6892bf6)

**Comment by JavaMaxim** [comment]
Hey, and what happens if you try to drag the window from one monitor to another (if you select Extend in monitors configuration)?

**Comment by aaa1386** [comment]
> Hey, and what happens if you try to drag the window from one monitor to another (if you select Extend in monitors configuration)?

There is bug.

**Comment by aaa1386** [comment]
The image below is a solution. The size and scale are good, but the image quality is bad, meaning it does not display clearly.

![image](https://github.com/user-attachments/assets/3c49398f-364a-4937-96ed-ef19c5fe5ab2)

**Comment by aaa1386** [comment]
My question to the developer is, is it possible to make changes in the FP so that when applying these settings shown in the image, there is no change in the transparency of the icons and texts?

If this is possible, the problem will be solved.
This problem occurs for everyone who has two monitors with different resolutions and scales. Unless the difference in resolution and scale is so small that the change in the dimensions of the icons and texts is tolerable.

**Comment by aaa1386** [comment]
Before setting.

![image](https://github.com/user-attachments/assets/b6578abc-3390-4a4f-bb48-258626d57fa1)


Aftersetting.

![image](https://github.com/user-attachments/assets/89eba856-0357-4844-a0c2-20533f9c4b8c)

**Comment by aaa1386** [comment]
If you open the image fully, you will notice the difference in transparency.

**Comment by euu2021** [comment]
> [...] and the user has to restart the FP.

I got a new external monitor, and I'm also getting this problem. When my laptop comes back from suspension, the external monitor takes more time than the laptop screen to wake up, so the bug happens.

But, it's not necessary to restart FP. You just need to move the FP window (eg, minimizing and mximizing again).

**Comment by aaa1386** [comment]
> > [...] and the user has to restart the FP.
> 
I always keep the main monitor active and the laptop monitor off. When I hibernate and disconnect the cable connecting to the external monitor, then if I turn on the laptop, everything goes wrong.
I also have problems with this function.
The problem does not resolve with the minimize and maximize options.
