### ISSUE TITLE
Cannot start Freeplane as it doesn´t support Java version 23.

### ISSUE THREAD

**Issue by rbarte** [freeplane/freeplane#2150]
**Describe the bug**
Cannot start Freeplane on Fedora 41 as Freeplane doesn´t support Java 23.
Java 23 is available and installed by default on some operating systems like Fedora Linux 41.
Please support current Java releases.

**To Reproduce**
```
./freeplane.sh 
ERROR:   Found /usr/lib/jvm/java-23-openjdk-23.0.1.0.11-1.rolling.fc41.x86_64//bin/java in $JAVA_HOME.
ERROR:   It has version 23.0.1
ERROR:   Currently, freeplane requires java version 8 or from 11 to 22
ERROR:   
ERROR:   Select a supported java version
ERROR:   by setting FREEPLANE_JAVA_HOME to a valid java location
ERROR:   OR use an unsupported java version
ERROR:   by setting FREEPLANE_USE_UNSUPPORTED_JAVA_VERSION to 1
```

```

java --version:
java --version
openjdk 23.0.1 2024-10-15
OpenJDK Runtime Environment (Red_Hat-23.0.1.0.11-1) (build 23.0.1+11)
OpenJDK 64-Bit Server VM (Red_Hat-23.0.1.0.11-1) (build 23.0.1+11, mixed mode, sharing)
```

**Comment by mkalinski** [comment]
[It looks like there's no plan to support Java releases past 21 LTS.](https://github.com/freeplane/freeplane/discussions/2124)

Note that in Fedora 41 you can install package `java-21-openjdk` in parallel to `java-latest-openjdk` (which is Java 23 currently).

**Comment by dpolivaev** [comment]
Preview 1.12.9_01

**Comment by rbarte** [comment]
Thank you - Freeplane preview 1.12.9_01 works fine with Java 23!

![image](https://github.com/user-attachments/assets/0bdd6c71-dff5-464f-baf8-db0da39ade9f)
