### ISSUE TITLE
Colorful emojis don't work on certain zoom levels

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#2155]
Following this comment: https://github.com/freeplane/freeplane/discussions/2113#discussioncomment-11284556

What happens is that the emojis only get correct (colorful) when the zoom level is big:

![javaw_4jhuSmDpnj](https://github.com/user-attachments/assets/a76cde90-6a34-43bf-af2b-6aa3b2efe27e)

Notice that, on the Map Overview it is always correct.

I'm using jbr_jcef-21.0.5-windows-x64-b631.30.tar.gz, from https://github.com/JetBrains/JetBrainsRuntime/releases, which is the latest provided by JetBrains.

**Comment by euu2021** [comment]
It works fine when I build FP using this Gradle JVM:
![image](https://github.com/user-attachments/assets/72adcef3-93ad-4c4f-aeba-c02abcb30e4b)

**Comment by dpolivaev** [comment]
I can't see the problem on my computer.

**Comment by dpolivaev** [comment]
I checked it using the released windows setup version 1.12.8 on my windows 10 laptop.

**Comment by euu2021** [comment]
Now, I noticed that it's a matter of the resolution of the monitor. When my FP window is on my FullHD monitor, it has the behavior shown in the GIF of my first post. But, if I move the FP window to my 2560x1600 monitor, the emojis render perfectly on any zoom level.
