### ISSUE TITLE
&radic; gives A

### ISSUE THREAD

**Issue by spandugithub** [freeplane/freeplane#2156]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Version [e.g. 22] 22
 - Java Version

**Additional context**

**Comment by dpolivaev** [comment]
I do not understand what you mean, please provide screenshots and example mind map.

**Comment by spandugithub** [comment]
![2024-12-19](https://github.com/user-attachments/assets/765cc436-6b25-407d-832a-3e764ca2f4ec)

I want to write Square root for which HTML entity is &radic;

Layout view shows A circumflex  but not square root

**Comment by spandugithub** [comment]
&&radic;

**Comment by spandugithub** [comment]
sorry it is & r a d i c (wrote like this it is giving square root symbol. But in freeplane it is giving A

**Comment by dpolivaev** [comment]
I think  it is not supported by the library, see https://chatgpt.com/share/6764393b-c080-8000-b8ba-b12b386fce41
