### ISSUE TITLE
Add on dView not working

### ISSUE THREAD

**Issue by pmraps** [freeplane/freeplane#2159]
**Describe the bug**
Add on dView is not working with the error in the image below.

**To Reproduce**
1. Select a node
2. Click on 'Tools'
3. Scroll down to 'Scroll down to dView' and Select a panel
4. See error below

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs:
[Test dView.zip](https://github.com/user-attachments/files/18217351/Test.dView.zip)

**Screenshots**
Screenshot added
![dView_Error](https://github.com/user-attachments/assets/f24fee51-5a73-451a-800a-e5fe0adfe055)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 10
 - Version [e.g. 22]: 1.12.8
 - Java Version: 21.0.5

**Additional context**

**Comment by HaaiHenkie** [comment]
Hi!

This is not a Freeplane bug, but a bug in the add-on dView. The developer Jodi D. Krol is not active anymore. Maybe another add-on developer can revive dView.

**Comment by pmraps** [comment]
OK, thank you.
