### ISSUE TITLE
Search in selected subtree

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#2165]
Suggestion: Adding the `Search in Subtree` Option to the Toolbar

Currently, Freeplane has a very useful `Search in Subtree` option, available as a checkbox in the `Edit -> Find -> Find` menu within the search panel. When activated, it limits the search to the selected branch.

While this feature is highly beneficial, it has two notable limitations:

No Toolbar Icon: There is no dedicated icon for `Search in Subtree` in the toolbar, which could make it quicker and easier to access. Many users prefer not to have the search panel (activated via `Edit -> Find -> Find`) displayed on the map and would benefit from a direct toolbar icon.
Limited Combination of Features: The six search options currently available in the toolbar (highlighted by a green line in the image below) are not present in the search panel under `Edit -> Find -> Find`. As a result, it’s not possible to use these six options in conjunction with the `Search in Subtree` checkbox.
To address these issues, I suggest adding a `Search in Subtree` icon to the toolbar. Here’s how it could work, explained through an example:

Toolbar Icon:

A new icon labeled `Search in Subtree` is added to the toolbar. When inactive, the icon appears dimmed. When active, the icon becomes bold (similar to the cloud icon for active/inactive states).
Example Workflow:

The user selects Node 1, which has several child nodes and branches.
The user activates the `Search in Subtree` icon, making it bold.
The user types "book" in the search box and sees results limited to Node 1 and its branches.
Behavior of the Icon:

The `Search in Subtree` feature remains active even when nodes are folded, unfolded, or different nodes are selected.
The icon is automatically disabled only when:
The user edits a node.
The user copies or cuts and pastes a node into another branch.
The icon can also be manually disabled by the user.

Adding this feature would improve usability by allowing users to search more efficiently without relying on the search panel, while also enabling the combination of existing toolbar search options with `Search in Subtree`.

![image](https://github.com/user-attachments/assets/245abd77-2616-41a4-984c-5b243b1c144f)

**Comment by euu2021** [comment]
You can customize your toolbar. See: https://github.com/freeplane/freeplane/issues/747

**Comment by aaa1386** [comment]
> You can customize your toolbar. See: #747

This is my file. Can you make the necessary changes?
[mindmapmodemenu.zip](https://github.com/user-attachments/files/18223376/mindmapmodemenu.zip)

**Comment by euu2021** [comment]
> This is my file. Can you make the necessary changes? [mindmapmodemenu.zip](https://github.com/user-attachments/files/18223376/mindmapmodemenu.zip)

I don't know how it works. I don't know how to include an item that is not in the menus.

**Comment by aaa1386** [comment]
> > This is my file. Can you make the necessary changes? [mindmapmodemenu.zip](https://github.com/user-attachments/files/18223376/mindmapmodemenu.zip)
> 
> I don't know how it works. I don't know how to include an item that is not in the menus.

I think that searching for a word from the `Edit -> Find -> Find` path, which has the `Search in Subtree` option, is completely different from searching for a word through the toolbar, although they are similar. Therefore, the `Search in Subtree` option should be added to the toolbar and the specific function that I explained in the idea should be considered for it. This function is also different from the function of the `Search in Subtree` option in the `Edit -> Find -> Find` path, although it is similar.

**Comment by dpolivaev** [comment]
Preview 1.12.9_01

**Comment by aaa1386** [comment]
very good.
