### ISSUE TITLE
Idea: Change the behavior of the up and down arrow keys without losing any functionality with many benefits.

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#2168]
<gray>Watch the video below. Nodes with green icons will move in the same column when using the up and down arrow keys, no matter how many times they are used, and this behavior is recommended.</gray>

https://github.com/user-attachments/assets/2d38fdd2-a5b8-4d54-9520-0cea7ec578b2

<gray>In nodes with red cross icons, when we move with the down arrow key, we are moved to another column at the end. If we use the up arrow key, we do not return to the initial node that had the red icon. This behavior may confuse the user. Pay attention to the three starting points of navigation with the cross icon. Is it easy for you to imagine how this works or confusing?</gray>

<gray>Imagine that you want to navigate between brothers and sisters in a large map where a node has many children. What happens if you hold down the down arrow key to quickly reach the end of the column? If you do not pay attention to the lowest node, you may get lost and be transported to another part of the map. There is no way back because the up arrow key does not return you to the original path. This problem has happened to me many times and I have to be careful not to go past the wrong bottom node.</gray>

<gray>Now, create a large map and quickly move by pressing the down button. In this case, you don't really know where you are on the map and every time you press the down button, you get more lost. Now, suppose you want to return to your starting point with the up button. This is practically impossible and makes you even more confused. In addition to vertical movement, the up and down arrow keys also move left and right, which makes no sense and confuses the user. It would be better if the arrow keys only moved vertically and did not move to other columns.</gray>

<b>Suggestion for solving the problem:</b> 
In Freeplane, there are two options called `Navigate → Select Up` and `Navigate → Select Down` that perform the current function of scrolling up and down. But the up and down arrow keys on the keyboard work independently of these two options. That is, even if no shortcut is defined for these two options, the arrow keys will still have their current function of scrolling up and down.

<gray>It is recommended that the arrow keys be defined so that they only scroll through siblings and not exit them, similar to the function you saw in the video for the three nodes with the green icon.</gray>

<gray>If some users do not want to lose the current functionality of Freeplane, there is no problem. They can define their own shortcuts for these two options (`Navigate → Select Up` and `Navigate → Select Down` ). They can even set the up and down arrow keys for them. Therefore, by implementing this idea, no functionality of Freeplane will be reduced.</gray>

<b>Benefits of the new idea:</b>

<b>You can move to the end or beginning of the sibling column at full speed.</b>

<gray>More focus:</gray> 
The user is more focused when navigating a branch because they no longer have to worry about being unexpectedly taken to other parts of the map.

<b>Maintain ease and speed in navigation:</b> 
With this change, the user can quickly reach the beginning or end of a branch without worrying about making a mistake while navigating between columns. This feature is especially useful in large and complex maps.

<b>Simple and clear:</b> 
By limiting the movement of the directional buttons to the same column, navigation will be clearer and simpler for the user.

<b>Ability to return to the starting point:</b> 
The user will always be able to return to their starting point using the directional buttons and avoid getting lost in the map.

<b>More flexibility for users:</b> 
Users who want to move between columns can set their own shortcuts for the two options `Navigate → Select Up` and `Navigate → Select Down`  to maintain the current functionality of the FP. As a result, nothing is removed from the current functionality of FreePlane.

<b>Reduced Confusion:</b> 
This change can help prevent user confusion and provide a better user experience, especially when the map is large and complex.

<b>Conclusion:</b> 
Implementing this change in FreePlane will make navigating between nodes easier and error-free. These changes also give the user more control over how the map is navigated, without requiring major changes to the current functionality of the software. This feature will improve the user experience, increase navigation speed and accuracy, and ultimately increase the efficiency of mind maps.

**Comment by dpolivaev** [comment]
There is a dedicated action to go back to the previously selected node, Navigate->Go backward (Alt+←)

**Comment by aaa1386** [comment]
> There is a dedicated action to go back to the previously selected node, Navigate->Go backward (Alt+←)

Yes, that's right - but the functionality that was proposed is really very simple and interesting.
Look at the image below
Columns 1, 2 and 3 are known.

![image](https://github.com/user-attachments/assets/86d6ceb0-0241-4ab7-a7de-29a841f3f1e4)


 Suppose the user navigates in column 2 with the up and down arrow keys. Whenever he decides to move to column 1 or 3, he moves with the right and left arrow keys and navigates again with the up and down arrow keys. That is, there is always a control mode that does not unconsciously navigate to unwanted nodes and does not get confused

Can't the up and down arrow keys or the two options that exist for navigating and selecting the up and down nodes ( `Navigate → Select Up` and `Navigate → Select Down` ) be changed to suit the idea, and the other one remains for the current state of the FP?

**Comment by aaa1386** [comment]
In my opinion, it is even better to use the `Shift + Up` and `Shift + Down` button combination to select nodes only among siblings. Whenever the user decides to select from other branches, by holding the Control button and clicking on another branch, he is moved to it, and there he can again select other nodes using the `Shift + Up` and `Shift + Down` buttons.

The current functionality of FP in using the `Shift + Up` and `Shift + Down` keys to select multiple nodes often causes errors for the user. You can try it, you should always be careful not to make any mistakes.

**Comment by aaa1386** [comment]
Current functionality: When you navigate with the down arrow key, if you reach the end of the siblings, for example node 888, you will be moved to the highest node of the uncle of these siblings, which is below their father.
The up arrow key is the opposite of this functionality.

Question: How often is such a confusing functionality used? How useful is it?
I have never used this function, either in navigation by `up` and `down` keys  or in selecting a number of nodes with `Shift + Up` and `Shift + Down` , but I was always careful not to let it lead me into error.
Others, I don't know if it really has a specific use for it or not?

**Comment by aaa1386** [comment]
Look at the video below: Consider nodes 8, 7, and 10


https://github.com/user-attachments/assets/eb63aa7b-7850-469c-9b2a-60ae4d0685a6




We navigate to node 8 with the down arrow key
We press the key again
If node 7 is unfolded, node 10 is selected
If node 7 is folded, node 7 is selected
It seems a bit confusing.
