### ISSUE TITLE
Add nodes inside selection rectangle to selection if shift is pressed

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#2171]
the new rubber band selection has one flaw, which is that you can't select more than one set of nodes.
The correct behavior is that whenever the user selects multiple nodes using the control button and mouse drag, if they press the control button again and select other nodes by dragging the mouse, the previously selected nodes should not be de-selected.
With this proposed behavior, any number of different sets of nodes can be selected, even if they are far apart. This is an interesting suggestion.

_Originally posted by @ajaberi1360 in https://github.com/freeplane/freeplane/discussions/2169#discussioncomment-11671821_

**Comment by euu2021** [comment]
Maybe, using Ctrl+Shift to add new group of node, as mentioned at: https://github.com/freeplane/freeplane/issues/1218#issuecomment-2428967958

And simply Shift, if the user is using the right button of the mouse.

**Comment by aaa1386** [comment]
Look at the image. Can you select all the nodes I have marked with the green line in the image at the same time with the current FP functionality?

![image](https://github.com/user-attachments/assets/7efe8e74-6d4f-4c83-92fa-5e81941907db)

**Comment by dpolivaev** [comment]
Preview 1.12.9_01
