### ISSUE TITLE
Enhanced Performance in Direct Selection Mode with Mouse Interaction

### ISSUE THREAD

**Issue by aaa1386** [freeplane/freeplane#2179]
<b>Issue:</b>
In the current implementation of direct selection mode, nodes are automatically selected as the mouse moves over them. This behavior is undesirable, as it leads to unintended selections and a suboptimal user experience.

<b>Proposed Solution:</b>
The selection mechanism should be refined so that nodes are only selected when the mouse stops over a node, indicating the user’s intention to select it. Simply moving the mouse across nodes should not trigger any selection.

<b>Demonstration:</b>
Refer to the attached video, which illustrates CPU processing metrics and highlights the current resource usage of this feature.

https://github.com/user-attachments/assets/bbdf070d-4ff1-4e2a-b897-8881da3da92f

<b>Benefits:</b>

<b>Improved User Focus:</b> Users can freely move the mouse without triggering unintended selections, allowing for a more deliberate and focused interaction.
<b>Reduced CPU Load:</b> By avoiding constant node selection during mouse movement, CPU usage is minimized, improving overall system efficiency and performance.

**Comment by euu2021** [comment]
I like the current behavior. Having to stop the mouse would slow me down.

**Comment by macmarrum** [comment]
@ajaberi1360 I know this isn't what you're asking for, but I think it's pretty close. So until your feature request is implemented (if ever), you might want to try:
`Preferences…->Behaviour->Selection method->Selection method` = **Delayed**
`Preferences…->Behaviour->Selection method->Time for delayed selection` = **240**

**Comment by dpolivaev** [comment]
Yes, delayed selection can help you.

**Comment by aaa1386** [comment]
> I like the current behavior. Having to stop the mouse would slow me down.

You are absolutely right -

**Comment by aaa1386** [comment]
> I like the current behavior. Having to stop the mouse would slow me down.

There is no difference in speed in nodes that are close to each other, but in nodes that are far apart, the speed of work is faster with the current state of FP. I had not paid attention to this point

**Comment by aaa1386** [comment]
> @ajaberi1360 I know this isn't what you're asking for, but I think it's pretty close. So until your feature request is implemented (if ever), you might want to try: `Preferences…->Behaviour->Selection method->Selection method` = **Delayed** `Preferences…->Behaviour->Selection method->Time for delayed selection` = **240**

Thank you for always trying to help me.
