### ISSUE TITLE
Windows- Freeplane will run from .bat file but not directly

### ISSUE THREAD

**Issue by incansvl** [freeplane/freeplane#220]
OS: Windows 10 Pro 64 bit
JDK: openjdk 15.0.2 2021-01-19
Freeplane: 1.9.4

##Background##
I installed Freeplane 1.9.4 on a Windows machine that had the latest OpenJDK (1.16.1) installed. Freeplane objects to this withj the error-

![image](https://user-images.githubusercontent.com/28898330/122981267-7618fd80-d391-11eb-90cf-e0436aecf2d1.png)

Even after uninstalling OpenJDK 1.16 and replacing it with 1.15.2 and similarly uninstalling + reinstalling Freeplane the symtoms are the same.

##Symptoms##
Running Freeplane from the Windows start menu, or by double-clicking `freeplane.exe` causes the error-

> This application requires a Java Runtime Environment 1.8.0 - 15 
> The system could not find the environment option that was entered.

Running the `freeplane.bat` script either by double-clicking, or from the cmd shell starts Freeplane as expected.

I can work around the problem by running the batch script, but it would be nicer for the program to run as-installed, as I assume I may run into the same problem after an upgrade in future.

**Comment by dpolivaev** [comment]
Running Freeplane under Java 16 is blocked by intention because the latest Groovy version has troubles with it and some scripts or formulas could stop working correctly. You can install or just extract some older Java version and use an environment variable FREEPLANE_JAVA_HOME so that Freeplane launcher can find it.

**Comment by incansvl** [comment]
I understand Freeplane does not currently support Java 16. What I don't understand is why after downgrading my machine to Java 15 Freeplane (only the .exe) still thinks the version of Java is incompatible.

The .bat script runs correctly, so somerhow the two seem to be picking up different views of the Java version on the machine?

`Java -version` reports:

> openjdk version "15.0.2" 2021-01-19
> OpenJDK Runtime Environment (build 15.0.2+7-27)
> OpenJDK 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)

**Comment by dpolivaev** [comment]
Freeplane uses launch4j as a launcher. I found out it could consider JAVA_HOME (but it is still to be configured), but it looks like I can not let it search in a path for your java.exe.

Currently, it considers only FREEPLANE_JAVA_HOME, and you can point it to any Java15 you have at any place on your computer.

**Comment by dieterstueken** [comment]
finally got it running with Java 11 using FREEPLANE_JAVA_HOME.

I saw you put in JAVA_HOME, too: [exe launcher honors JAVA_HOME](https://github.com/freeplane/freeplane/commit/8b2206a6bc5b1629f23a1db338611625c0d0a071)

but I suspect you forgot a trailing % on freeplaneGui.i4j.xml

**Comment by kimim** [comment]
PR #247 fix this issue.
