### ISSUE TITLE
Automatically center map on found node when searching (already available feature or new feature request?)

### ISSUE THREAD

**Issue by ldmpub** [freeplane/freeplane#222]
Hi,

**Issue**
When I'm searching nodes in a map, it's hard for me to identify which node map contains the result.

**My "workaround"**
The only way I can change this behavior is by modifying the appearance of the selected node (because step by step search uses "selected node style" to highlight current result).

Is there a way to "automatically center the current found node"? (I haven't seen this search option yet 😅)
Can you suggest any other convenient option I can activate? or any best practice when searching in a "huge" map?

**New Freeplane Feature?**
If above answers were "sorry, currently not", what do you thing about adding this new feature for node search? => **_Automatically center map on the found node when searching in a map._**

**Comment by dpolivaev** [comment]
Filter->Highlight all matching nodes should actually do it, also available on the filter toolbar

**Comment by xarich** [comment]
@dpolivaev thanks for this tip 👍.

I have activate it and it's better to identify "result nodes" but I miss the "automatically center map on current result node".

**What do you think: does this feature makes sens for other users?** Should I fill a new feature request or does this GitHub issue is enough (with its "short history")? or should I ... forget my idea 😥?

**Comment by dpolivaev** [comment]
Use View->View settings->Center selected node automatically

**Comment by ldmpub** [comment]
Thanks 👍, it's fine but it's not exactly doing the job because:
1. while performing a search, center node does not always work (is it a bug?)
2. this behaviour is enabled for "all contexts" not only while searching ...
3. ... a toolbar shortcut to enable / disable this "center selected node" option will do the the trick but I haven't found any nor been able to customize / add this option to a tool bar.

Eager to get your answers on this particular "use case".

**Comment by ldmpub** [comment]
To let you know: workaround used yet => **define a keyboard shortcut to Enable / Disable "Center selected node"** (the harder part will be to remember the created shortcut among all shortcuts  have already setted up in Freeplane and elsewhere 😊).

**Comment by dpolivaev** [comment]
> while performing a search, center node does not always work (is it a bug?)

Can you please describe the case where it does not work? It might be a bug

**Comment by ldmpub** [comment]
Hi,

Please find attached a video capture of a search with "center node" option activated
=> 2 results founds
=> 1 working OK (auto center) and 1 not.

Note: password for video is _FreePlaneBUG_

If bug is confirmed, should we and if so, who will ?, open a new issue?

Best regards,

[EDIT] attachment added (note: no password)
[FreePlane.zip](https://github.com/freeplane/freeplane/files/6877541/FreePlane.zip)

**Comment by dpolivaev** [comment]
Sorry, I see no attachment

**Comment by ldmpub** [comment]
Regarding "auto center selected node", I really miss

**- a way to activate / unactivate quickly the option** (yet, read above, I have done it by creating one more personnal keyboard shortcut 😊)
**- a status displayed somewhere in Freeplane** to know iF option is unabled or not (for instance text in the existing "status bar").

According to me, adding a "sensitive icon" with 2 states in a Freeplane toolbar will solve both 2 issues.

**Comment by ldmpub** [comment]
@dpolivaev sorry => attchment added above (in original comment).

**Comment by dpolivaev** [comment]
Bug confirmed,could you please upload some map which I could use to reproduce it?

**Comment by ldmpub** [comment]
Ok I will send one tonight.

**Comment by ldmpub** [comment]
I performed some more tests, it's not so easy to reproduced the bug (it may depend on the map size and/or nodes content).

@dpolivaev => I sent you an email to suggest (for privacy reasons) to the transfer the "buggy map" to your personal email address rather than storing it here  in a "public" GitHub issue ...

**Comment by dpolivaev** [comment]
I think I fixed it

**Comment by ldmpub** [comment]
@dpolivaev: Test map sent to your personal email. It will allow you to confirm you fixed this "search and center" issue 😉.

**Comment by ldmpub** [comment]
For history (I removed an incorrectly authored GitHub comment)
« _@dpolivaev thanks for this tip 👍._

_What do you think: does this feature ("automatically center map on current result / found node") makes sens for other users? (if so should I fill a new feature request or does this GitHub issue is enough with its "short history")? or should I ... forget my idea 😥?_
 »

=> answer is: feature already available in Freeplane 😅

**Comment by dpolivaev** [comment]
Fixed, version 1.9.7 released

**Comment by ldmpub** [comment]
Hi,

Update done to Freeplane version 1.9.7 => I confirm center map when searching bug is now fixed ✅.

Many thanks to you @dpolivaev 👏 ... quick answer and efficient dev (as usual 🙏). Thanks again!
