### ISSUE TITLE
literally unusable due to a visual glitch 

### ISSUE THREAD

**Issue by Kyr4l** [freeplane/freeplane#230]
installed today, never used freeplane before, this is what happens after one minute of usage 
![image](https://user-images.githubusercontent.com/24955106/132979808-9092de35-5e64-4611-acab-f7479bc623a6.png)

**Comment by dpolivaev** [comment]
Please upload log files and any map which allows to reproduce the issue.
You can find log files in a subdirectory of freeplane user configuration directory which can be opened using menu item 

Tools->Open user directory

**Comment by Kyr4l** [comment]
there
[freeplanebugreport.zip](https://github.com/freeplane/freeplane/files/7149321/freeplanebugreport.zip)
as i said i never used freeplane before, this is the first time i use it, i even reinstalled it but this bug still happens and it's just unusable

**Comment by ldmpub** [comment]
@Kyr4l don't worry too much because Freeplane is a stable software and the dev team is reactive 😊.

By the way, can you confirm under which OS this glitch occurs?

Thanks,

**Comment by dpolivaev** [comment]
I am not so optimistic because I don't know which steps and environment cause this bug to happen.
From the log I see that it is a fresh freeplane installation running on Windows under Java 8 update 301.
There are no internal errors tracked in the log.
So unless you can tell me what I should try I don't know how I could investigate it.

**Comment by dpolivaev** [comment]
If you have changed any user preferences you could upload your auto.properties so that I can test it,
and I definitely need a sequence of steps triggering the issue.

**Comment by dpolivaev** [comment]
I see also that some entries in the map pop-up menu are doubled.
I do not have any explanation for it.

I would also appreciate if you could try the latest preview version available at https://sourceforge.net/projects/freeplane/files/freeplane%20preview/ because actually it is the version running on my machine

**Comment by dpolivaev** [comment]
It might be related to your graphic card or graphic card driver.
Which graphic card do you use?

You might try adding all or any of the options described in https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/java2d-props002.html to your freeplane.l4j.ini in the directory with freeplane.exe one per line

````
-Dsun.java2d.noddraw=true
-Dsun.java2d.d3d=false
-Dsun.java2d.ddblit=false
````

**Comment by Kyr4l** [comment]
> 
> 
> @Kyr4l don't worry too much because Freeplane is a stable software and the dev team is reactive 😊.
> 
> By the way, can you confirm under which OS this glitch occurs?
> 
> Thanks,

Windows 10 21H1 Build 19043.928

**Comment by Kyr4l** [comment]
> 
> 
> If you have changed any user preferences you could upload your auto.properties so that I can test it,
> and I definitely need a sequence of steps triggering the issue.

the only thing ichanged is the default theme, i switched to Darcula, but even with 100% default settings the bug still occurs

**Comment by Kyr4l** [comment]
> 
> 
> It might be related to your graphic card or graphic card driver.
> Which graphic card do you use?
> 
> You might try adding all or any of the options described in https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/java2d-props002.html to your freeplane.l4j.ini in the directory with freeplane.exe one per line
> 
> ```
> -Dsun.java2d.noddraw=true
> -Dsun.java2d.d3d=false
> -Dsun.java2d.ddblit=false
> ```

i have a GTX 1660 Super, 
Game Ready Driver 471.68

**Comment by Kyr4l** [comment]
![image](https://user-images.githubusercontent.com/24955106/132988418-3fa70255-52cc-4ac4-a212-6029e028b6d0.png)
![image](https://user-images.githubusercontent.com/24955106/132988426-8bbd9a86-6077-4fee-8cb3-7fe970ad1a07.png)
![image](https://user-images.githubusercontent.com/24955106/132988437-ad37ad00-30ea-4357-896a-5c8495747a22.png)

same issue with the latest version 1.9.8

**Comment by Kyr4l** [comment]
note that i recently reinstalled my driver from scratch using DDU, i'm not facing any issues with my GPU, this is the only program i'm having trouble with

**Comment by EdoFro** [comment]
I had once a similar error when playing with a script that opened a swing dialog with different LookAndFeel than Freeplanee.
I remember the error was AWT related.
hope this information helps

**Comment by EdoFro** [comment]
I described here how I got the error:

https://sourceforge.net/p/freeplane/discussion/758437/thread/142cf1a292/?limit=25#fc8e

**Comment by Kyr4l** [comment]
I uninstalled JRE 8 from Oracle (java.com) and installed OpenJDK JRE 11 LTS (Eclipse Temurin JRE with Hotspot 11.0.12+7 x64)
seems like the problem is gone for now

**Comment by dpolivaev** [comment]
I am glad you could fix it.
It does not look like a freeplane specific issue.

You can select Java version used to run Freeplane by pointing environment variable FREEPLANE_JAVA_HOME to its root directory.

**Comment by Kyr4l** [comment]
nevermind, nothing changed, it's still happening
![image](https://user-images.githubusercontent.com/24955106/133167092-49e179b7-4e5b-4021-a141-021df4f1d7a9.png)
