### ISSUE TITLE
still unusable (mentionned in #230)

### ISSUE THREAD

**Issue by Kyr4l** [freeplane/freeplane#231]
same problem as described in #230 
the problem still occurs
![image](https://user-images.githubusercontent.com/24955106/133167247-730dda3d-45d7-40f5-a298-a79d5900e902.png)

**Comment by Kyr4l** [comment]
![image](https://user-images.githubusercontent.com/24955106/133167408-14d890a3-5ddb-49db-9a57-39b47bb52315.png)
this area is duplicating itself when i move my cursor across the nodes

**Comment by Kyr4l** [comment]
update : seems like executing freeplane from the batch file doesn't cause this issue, so the .exe file might be the problem

**Comment by dpolivaev** [comment]
Both exe und batch just launch java.
Maybe they launch different versions or use different options.
Check the differences and let me know.

To check all parameters you can use https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer
