### ISSUE TITLE
What is mean about "(?ims)"?

### ISSUE THREAD

**Issue by daidai21** [freeplane/freeplane#233]
https://github.com/freeplane/freeplane/blob/7933f479d48d147cdf222ed7a19200f540dd60d2/freeplane/src/main/java/org/freeplane/core/util/HtmlUtils.java#L123

**Comment by dpolivaev** [comment]
ignore case, multiline, dot all

https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html
