### ISSUE TITLE
Nodes unselected after moving them

### ISSUE THREAD

**Issue by bekoeppel** [freeplane/freeplane#234]
Unfortunately, I think https://github.com/freeplane/freeplane/issues/223 caused a regression. After moving a node, it is now unselected.

1.9.7:
![Screencast_turbot muasch ch_2021-09-24_22-15-47](https://user-images.githubusercontent.com/1185824/134734963-9dc4c700-9c1d-4827-9c69-39f3daa1f77a.gif)

1.9.8:
![Screencast_turbot muasch ch_2021-09-24_22-16-26](https://user-images.githubusercontent.com/1185824/134734978-8760c4b9-e497-4514-8c63-f14d810d6fb6.gif)

Notice how in 1.9.8 the nodes that I just dragged around got unselected.

**Comment by dpolivaev** [comment]
I think it is fixed now
