### ISSUE TITLE
[macOS] Unreadable Tabs on Perferences and Color pick plates

### ISSUE THREAD

**Issue by shenlebantongying** [freeplane/freeplane#236]
It is not critical to functionality, but the glitches does feel uncomfortable.

![image](https://user-images.githubusercontent.com/20123683/136528314-81c35ffe-bfe3-4e81-801a-435737f45d5e.png)
![image](https://user-images.githubusercontent.com/20123683/136528444-b457ca56-1eba-446c-9d51-699f9ccf11b0.png)

**Comment by dpolivaev** [comment]
It is a look and feel library issue, it is not freeplane specific and can not be fixed here

**Comment by shenlebantongying** [comment]
Thanks for the info.
