### ISSUE TITLE
Node Notes lost after abandoning an inserted child.

### ISSUE THREAD

**Issue by leehach** [freeplane/freeplane#240]
Today I lost Notes added to a Node after the following sequence of events:

1. Edit a Node Note. (This can be a new node or preexisting node. The important thing is to start making edits to the Note without Saving the document or changing the focus to any other node.)
2. Hit Insert to insert a child node.
3. Hit Esc to abandon the child node.
4. The child node disappears. Focus reverts to the parent node. However, any edits made to the Note are lost.

It appears that changing the focus to any other Node "commits" changes to the Note. Thus, the edits are preserved if any other node is clicked before a child node is inserted. The edits are also preserved if after inserting the child node, text is added and committed to the child node. It seems to only be lost if a child node is "proposed" but abandoned.

**Comment by dpolivaev** [comment]
The fix is available in preview 1.10.1_05
