### ISSUE TITLE
Translations reviewer

### ISSUE THREAD

**Issue by pmraps** [freeplane/freeplane#249]
@dpolivaev Hello,
In order to continue working on Freeplane translations, I need to be a reviewer on Weblate. Can you please change my status?

**Comment by dpolivaev** [comment]
Hello, can you please explain what difference the status makes and why you need it?

**Comment by pmraps** [comment]
Hello,
as you probably know, I've been translating Freeplane and some plugins for some time, alone, and without complaints from anybody.
Recently someone quite rute decided to change bits of my work, without even the courtesy of contacting me.
So, the difference is, if I am a reviewer, I have the option to accept or not the suggestions those rude people make, in order to maintain the existing consistency. That is what I need it for. If there is no reviewer, at some point you end up with a complete mess.
Thank you

**Comment by dpolivaev** [comment]
As I can see looking at the history of the Portuguese translation file https://github.com/freeplane/freeplane/commits/1.9.x/freeplane/src/editor/resources/translations/Resources_pt_PT.properties recently only you and one other person https://github.com/mansil changed it.

I believe that both of you were striving for the best possible translation. I have no expertise in Portuguese myself and I can not decide which translations are better. I believe in the power of teamwork, collaboration, and goodwill. I would appreciate it if you could either get in touch with Manuela and find a solution together or allow me to reach out to her and moderate the discussion, whatever you like more.

Do you mind contacting Manuela?
Would you like me to write to her or would you like to do it yourself?
Maybe even tagging her GitHub user name at this issue would be sufficient, but if she would not respond I could also try other ways.

What do you think?

**Comment by pmraps** [comment]
I will not contact her. She has the habit of doing this, she did it already on the Apache OpenOffice project, where both me and Pedro Lino, also a translator with whom I work on AOO, tried to reach out and neither of us got an answer. But, if you want to try, be my guest.

**Comment by dpolivaev** [comment]
It looks like I can not activate reviews only for one language and activating reviews for all languages does not seem to be a good solution. The only option I see is blocking Manuela so that she is not able to make any submissions to Freeplane translations.
However, before doing so I am going to reach out to her.

Could you please create a new issue containing no personal remarks about her and just describing why you found her changes inappropriate? Given this text, I could try to establish a contact and block her if I get no response because not responding is a crime.

**Comment by pmraps** [comment]
About the reviews, on Weblate, and also on Transifex, I review most of the projects I'm involved with, but I only translate to Portuguese from Portugal. If you can't activate it per language, maybe something is wrong with the project configuration.

And creating a new issue is way too much trouble. My remarks are correct. I've been part of open source projects for ten years  now, and never ever overwritten anybody's work without at least trying to contact the previous translators. That is RUDE. Plain and simple. Just so you know, I'll cite a few, AOO, LibreOffice, Gnome (until v 3.22 if I remember right), GNU Translation Project, etc.

And, this is important, in some of them I even helped using that stupid orthographic agreement that was supposed to be ratified by all 9 countries and never was, making it absolutely void.

Since the lady wants the translation, fine by me. I'll suspend my collaboration for the time being. Keep my Github profile close and contact me when needed. For now, if you want, delete this issue, or hide it. Thank you for your time.
