### ISSUE TITLE
Incompatible JRE version error

### ISSUE THREAD

**Issue by Dominiquini** [freeplane/freeplane#252]
When I try to open and use Freeplane on Windows, this message appears:

![javaw_NJakm2KD6U](https://user-images.githubusercontent.com/1180808/156891197-8594717e-33ab-4a13-a144-8a5bbb1a3ede.png)

* OS: Windows 10 x64 21H2
* Java: 17.0.2

Thanks

**Comment by xogafdev** [comment]
I got the same problem. Due to restrictions and license topics we had to switch to official java version 17

Any info when this version will be supported?

**Comment by dpolivaev** [comment]
Java 17 should be supported in Freeplane 1.10.x, the first preview is already available
