### ISSUE TITLE
Wrong encoded UTF-8 characters in saved PDF file 

### ISSUE THREAD

**Issue by junaruga** [freeplane/freeplane#253]
Hello, thank you for maintaining this app! I see UTF-8 characters in saved PDF file is not correctly encoded.

## My environment

Mac: 10.13.6
Freeplane: 1.9.13, the latest stable version.

I downloaded the archive at https://www.freeplane.org/wiki/index.php/Home page.

I am not sure it this Java is used or not. Just in case I share Java version.

```
$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

## Reproducing steps

1. Create a map with a UTF-8 node "テスト" (Japanese).

![Test_freeplain](https://user-images.githubusercontent.com/121989/156902400-66e72e43-f981-4fb6-9b8f-aba44b672c9c.png)

Save as "テスト.mm".

```
$ cat テスト.mm
<map version="freeplane 1.9.13">
<!--To view this file, download free mind mapping software Freeplane from https://www.freeplane.org -->
<node TEXT="テスト" FOLDED="false" ID="ID_696401721" CREATED="1610381621824" MODIFIED="1646519968069" STYLE="oval">
...
```

From Menu - File - Print map - Click "PDF", save a PDF file as "Test.pdf"

The "テスト" is not correctly printed.

![Test_pdf](https://user-images.githubusercontent.com/121989/156902401-80a37da3-d8b9-4019-91c7-98af705efeb5.png)

I am not sure this issue is related to the following UTF-8 issues.

* https://github.com/freeplane/freeplane/issues/98
* https://github.com/freeplane/freeplane/issues/219

**Comment by dpolivaev** [comment]
I tried it on my mac and it worked
