### ISSUE TITLE
Bad display in formula edit freeplane 1.9.13

### ISSUE THREAD

**Issue by jologithub** [freeplane/freeplane#259]
While editing a formula the editing windows is smaller than equation. 

here is a image screen : 
![formula_size 2022-03-11 104743](https://user-images.githubusercontent.com/33137196/157872520-8f048ccc-557f-44d8-97a8-7494a4004ba0.png)

My system infos ; 
screen resolution : 1366 X 768
HP 250 G6 Notebook PC  14'
Windows 10 Famille 21H1

freeplane 1.9.13
version ZIP stable

java 8 update  241

and simple freeplane 1..9.13  test
[freeplane_test.zip](https://github.com/freeplane/freeplane/files/8232104/freeplane_test.zip)

Thamks JL

**Comment by macmarrum** [comment]
Hi JL
The Edit Formula window is resizable.
When I need it to be bigger or smaller, I drag one of its borders.
The window size is remembered for the next time it is used.
Are you able to resize the window?

**Comment by jologithub** [comment]
Thanks for the rapid answer.

I find that  possibility  later !

The resize function is OK.

JL
