### ISSUE TITLE
FP 193 13: addon Mardown Helper v6 problems

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#262]
Hi Edo, I updated your addon Markdown Helper in v6 but it creates errors in managing the list of tasks. Instead v5 is working well.
SFPC

**Comment by EdoFro** [comment]
Hi SFPC,
please submit the issue in its github repository:

https://github.com/EdoFro/Freeplane_MarkdownHelper/issues

Thanks,

edo

**Comment by dpolivaev** [comment]
It is not a Freeplane issue.
