### ISSUE TITLE
unrecognized #at notation in links and hyperlinks to other mindMaps

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#269]
Further to [link to an alias in another mindmap? #268](https://github.com/freeplane/freeplane/discussions/268#discussioncomment-2398306)

When a link or a hyperlink to another mindMap uses the #at notation, the link is unrecognized.

Expected
The #at notation works similar to the #ID notation

Example maps
[mindMap-links.zip](https://github.com/freeplane/freeplane/files/8312005/mindMap-links.zip)

**Comment by dpolivaev** [comment]
Fixed in previews 1.9.15_01 and 1.10.1_03, now you can use `#at(...)` - notation in internal links.
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

**Comment by macmarrum** [comment]
Works well. Thanks.
