### ISSUE TITLE
FP 10.1 not find Java 17

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#278]
I had java 8 and FP 1.9.14
I installed FP 10.1, ran it error
I Installed java 17.02
reinstalled FP 10.1, ran it: error

![Immagine 2022-03-26 163306](https://user-images.githubusercontent.com/62674157/160247220-ce3e2746-124c-439f-af7d-e610dcb3bdf8.png)

What next to run FP?
PS: I use
Windows 11
Browser Edge

Thanks
SFPC

**Comment by abc16361** [comment]
After installation, create JAVA_HOME --> C:\Program Files\Java\jdk-17.0.2\bin in the Environment Variables, and reboot Windows. It works here. Good luck!

abc

**Comment by Illegit** [comment]
Hi Abc , I found the system variables and created the following:
1) in user vaiables in path I added: C:\Program Files\Java\jdk-17.0.2\bin
![Immagine 2022-03-27 185117](https://user-images.githubusercontent.com/62674157/160292541-fd235b4d-c879-4b82-9de6-7ba6ec635a63.png)

2) in system vaiables in path I added: C:\Program Files\Java\jdk-17.0.2\bin
![Immagine 2022-03-27 185244](https://user-images.githubusercontent.com/62674157/160292546-4d26af7f-0d16-4f1b-889c-01a3d8316a34.png)

3) in system variables I created classpath with C:\Program Files\Java\jdk-17.0.2\lib
![Immagine 2022-03-27 185803](https://user-images.githubusercontent.com/62674157/160292560-178bf8d9-ad00-438b-a5db-92fe316e1cec.png)

Rebooted but I got always the same message.
At now situation means I'm not able to move forward to FP10.x.

I attached the changes I made.


ABC I thank you for your support. What else can I do?

SFPC

**Comment by Illegit** [comment]
Just to complete I found this files java in 
![Immagine 2022-03-27 191925](https://user-images.githubusercontent.com/62674157/160293005-11711f2b-889f-48f8-866d-a8b17a203b70.png)
and they are the same as they are here (a java 8
![Immagine 2022-03-27 192119](https://user-images.githubusercontent.com/62674157/160293032-dd3d437d-aa48-4e62-a31e-b3e5d0bdeb9a.png)

Does it make any sense?
SFPC
)

**Comment by Illegit** [comment]
Hi Abc I see a closed status?. is it a mistake? for me this is still open...
SFPC

**Comment by dpolivaev** [comment]
Consider https://github.com/freeplane/freeplane/discussions/275#discussioncomment-2447228
