### ISSUE TITLE
IllegalAccessError on Save

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#286]
Freeplane 1.10.1
Windows 10
openjdk 17
Reproducible: to be determined

1. Create a new mind map
2. Ctrl+S to save it

[Bug-IllegalAccessError_on_Save.txt](https://github.com/freeplane/freeplane/files/8381482/Bug-IllegalAccessError_on_Save.txt)

**Comment by abc16361** [comment]
Most likely it is the setting of security permission in openJDK.  I had a similar situation when using openJDK and solved it by creating a java.policy file [link here](https://github.com/freeplane/freeplane/discussions/275#discussioncomment-2445638).

abc

**Comment by macmarrum** [comment]
The issue was caused by missing arguments to java.exe when launching Freeplane.
I missed to update my launch script from the new freeplane.bat, which has the following new lines
```
--add-exports=java.desktop/sun.awt.shell=ALL-UNNAMED ^
--add-exports=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED ^
```
Closing as `invalid`
