### ISSUE TITLE
Unable to Display Icon, Freeplane 1.9.14

### ISSUE THREAD

**Issue by extremeware4217** [freeplane/freeplane#289]
This is confusing.  It seems that icons are inserted to nodes but no display
I am using Windows 10

**Comment by theelectricsoul** [comment]
Hello

I am not part of the developer team. But I can assure you, that they need you to provide ...

* an example "mind map" 
* more details 
* screenshots or videos in clean english

... to understand the problem quickly. 


A developers time is precious :)

**Comment by dpolivaev** [comment]
Check View->View settings->Show icons
