### ISSUE TITLE
FP 1.10.3: key alt gr doesn't work

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#290]
**Describe the bug**
The ctrl alt command is working with the combination "ctrl" + "alt" but not with the key "alt gr" (typically on the right of the keyboard)
In previous releases, both of the combinations were similar now I can utilize only the ctrl + alt. I ask if it is possible to re-create the same usability of keys as per FP 1.10 as it was previously with FP 1.9.x
**To Reproduce**
1. create a command using the shortcut alt gr
2. Click  that shortcut
3. See the error

**Expected behavior**
to have the same behavior by clicking ctr + alt (on the left of the keyboard) and altgr (on the right of the keyboard

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: w11
 - Browser [e.g. chrome, safari] edge
 - Version [e.g. 22] FP 1.10.3

Thanks
SFPC

**Comment by Illegit** [comment]
same in FP 10.1 04.

**Comment by dpolivaev** [comment]
https://github.com/freeplane/freeplane/issues/384
