### ISSUE TITLE
Default paste mode "Paste as plain-text" does not work

### ISSUE THREAD

**Issue by bartensud** [freeplane/freeplane#292]
**Describe the bug**
Although in preferences the default paste mode is set to "Paste as plain-text", pasting is done with formatting.

**To Reproduce**
1. Set default paste mode "Paste as plain-text" in Preferences -> Behaviour -> Rich-Text Editor.
2. Restart Freeplane (just to ensure that the change is really applied)
3. When I copy some formatted text (e.g. from web browser) and paste it on a mind map, the text is inserted as new node(s) but the formatting is preserved instead of having plain text now.
Note: It doesn't matter if I use keyboard shortcut CTRL+V or via menu Edit-> Paste.

FYI: As a workaround I can still use CTRL+SHIFT+V (Paste as...) and select then plain-text where also then plain text is pasted in the end.

**Expected behavior**
On pasting formatted text, it should be inserted as plain-text.

**Screenshots**
![Freeplane_CopyNPasteIssue_FormattedAlthoughDefaultModeIsPlainText](https://user-images.githubusercontent.com/156340/161533396-f6537be2-b5be-47be-93c8-921d613c8bad.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Freeplane Version 1.9.14, 1.9.13 (and also seen in older versions)

**Comment by EdoFro** [comment]
I think it's another preference (the one for pasting nodes)

![image](https://user-images.githubusercontent.com/35700575/161639521-47bff3f3-16bb-40fd-ba70-e2664e03ebd3.png)

**Comment by bartensud** [comment]
Thanks for the hint! 
I could apply my intended workflow now. For others which may run into same issue I document it here: 

- **Paste node by default as plain-text** (by setting Preferences -> Behaviour -> Confirmations -> "Use rich text for pasted nodes" to "No").

- To be still able to **paste node while keep the formatting** you can press CTRL+SHIFT+V (or from menu: Edit -> Paste as...) and select "HTML as node hierarchy".
