### ISSUE TITLE
FP 10.1.4: problem with script

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#293]
**Describe the bug**
this script is creating an error only in this FP release

**To Reproduce**
Just run the script

**Expected behavior**
the script has to move a node to the details of the parent node:
if (!node.isRoot()) {
    def parent = node.parent
    def oldDetail = node.to.value
    parent.detailsText = oldDetail
    node.delete()
}

**Screenshots**

![Immagine 2022-04-04 202848](https://user-images.githubusercontent.com/62674157/161608349-0cabbf08-21b1-45ca-ae8e-1b9b69f55888.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] W11
 - Browser [e.g. chrome, safari] Edge
 - Version [e.g. 22] FP 1.10.1 04

**Comment by Illegit** [comment]
I need to explain: if I change "value" with "text" it is working, but why it was working before in  FP 1.9.14 ?
Thanks for the eventual answer.
SFPC

**Comment by EdoFro** [comment]
Hi SFPC,
`node.to.value` makes no sense to me.

`.to` is the groovy way from `.getTo()` and `.value` is it from `.getValue()`

and if you look in NodeRO page in Freeplane's api, both are the same, so you are telling to do twice the same thing on `node`

![image](https://user-images.githubusercontent.com/35700575/161636360-6d7948e0-bfb3-4630-90eb-81b4ecc2ebfe.png)

![image](https://user-images.githubusercontent.com/35700575/161637140-8bdb18b2-b778-413b-9c71-a7e8fcd96239.png)


if you need node's text then use `node.text` that gives you a string (text or html)

if you want to pass a convertible, than use `node.value` OR `node.to`

Hope it helps,

edo

**Comment by EdoFro** [comment]
and **Convertible** class has no `.getValue()` method

I don't know why it worked before, but so far as I understand, it wasn't meant to work before neither.

**Comment by Illegit** [comment]
Thankyou EdoFro,
clear.
SFPC
