### ISSUE TITLE
FP 1.10.1 04: addon Jumper doesn't work any longer

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#294]
**Describe the bug**
The addon Jumper filter is opening but it is empty. It is a pity because I found it very useful.

**To Reproduce**
Just run it in FP 1.10.1 04

**Expected behavior**
list the solutions

**Screenshots**
If applicable, add screenshots to help explain your problem.:
![Immagine 2022-04-04 202848](https://user-images.githubusercontent.com/62674157/161609972-97fb20fb-c96f-4699-9a97-187e98ce0ada.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] w11
 - Browser [e.g. chrome, safari] edge
 - Version [e.g. 22] FP 1.10.1 04

**Comment by dpolivaev** [comment]
Please check if replacing jumper.jar in .../1.10.x/addons/jumper/lib with the attached file helps (you need to extract it first
[jumper.jar.zip](https://github.com/freeplane/freeplane/files/8451996/jumper.jar.zip)
)

**Comment by Illegit** [comment]
Thank you Dimitry, with that file changed it is working perfectly!
illegit
