### ISSUE TITLE
1.9.14 - Cannot unhide/hide node details

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#297]
Hello

Thank you for freeplane :) ♥🥂

Please see [video](https://user-images.githubusercontent.com/10260832/161979333-73f44a23-9759-4254-9281-1a16078b6a42.mp4) and attached map :)

[New Mindmap.zip](https://github.com/freeplane/freeplane/files/8427033/New.Mindmap.zip)

**Comment by macmarrum** [comment]
Hello @theelectricsoul 

Freeplane prevents `Hide details` from working when there is at least one node selected which has no details.

You can work around it using a script, e.g.

```groovy
node.hideDetails = !node.hideDetails
```

If this is your first time with scrips in Freeplane, you might want to have a look at https://www.freeplane.org/wiki/index.php/Scripting
In any case, shout if you need any further support.

**Comment by theelectricsoul** [comment]
@macmarrum 
> Freeplane prevents `Hide details` from working when there is at least one node selected which has no details.

Scroll to the position in the video where the first two nodes are **not** selected. You can see that there are two nodes without any details part of the selection. They do not prohibit hiding/unhding the details from the other nodes.

![grafik](https://user-images.githubusercontent.com/10260832/161997548-ab209ddc-a975-4938-9252-152913b64351.png)


Sooo...    somebody changed the behaviour you describe :)

**Comment by theelectricsoul** [comment]
@macmarrum 
BTW. I've been playing with the scripts :)  Thank you. :)

**Comment by macmarrum** [comment]
You are right 😊 
I stand corrected: Freeplane prevents `Hide details` from working when **the first node** that's been selected has no details.
