### ISSUE TITLE
Calling freeplane.bat yields exception "Security Manager is deprecated"

### ISSUE THREAD

**Issue by lusitania** [freeplane/freeplane#300]
**Describe the bug**
When I call `freeplane.bat` bootstrap terminates with the exception `Exception in thread "main" java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release`.

**To Reproduce**
1. Open console and go to the folder where you've installed freeplane.
2. Call `freeplane.bat`
3. See error
```
C:\Program Files\Freeplane>freeplane.bat

C:\Program Files\Freeplane>java -Xmx512m -Dorg.freeplane.userfpdir="%APPDATA%\\Freeplane" -jar freeplanelauncher.jar
*org.knopflerfish.framework.readonly=true
*org.knopflerfish.gosg.jars=reference:file:C:\Program Files\Freeplane\core/
*org.freeplane.user.dir=C:\Program Files\Freeplane
*org.freeplane.basedirectory=C:\Program Files\Freeplane
*org.freeplane.globalresourcedir=C:\Program Files\Freeplane\resources
*java.security.policy=C:\Program Files\Freeplane\freeplane.policy
*org.osgi.framework.storage=C:\Program Files\Freeplane\fwdir
Exception in thread "main" java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:416)
        at org.freeplane.launcher.Launcher.launchWithoutUICheck(Launcher.java:291)
        at org.freeplane.launcher.Launcher.main(Launcher.java:88)
```

**Expected behavior**
Application starts.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19044.1620]
 - Browser N/A
 - Versions
   - Freeplane 1.9.14
   - Java
     ```
     C:\Program Files\Freeplane>java -version
     openjdk version "18" 2022-03-22
     OpenJDK Runtime Environment (build 18+36-2087)
     OpenJDK 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)
     ```

**Additional context**

**Comment by macmarrum** [comment]
Freeplane 1.9.x runs on Java 8 through 15.
If you need to run Freeplane on a higher Java version, please consider using a preview of Freeplane 1.10.x: https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

Please see also https://github.com/freeplane/freeplane/discussions/275#discussioncomment-2447254

**Comment by dpolivaev** [comment]
If you want to try running Freeplane with Java 18 you should use Freeplane 1.10.x and add option `-Djava.security.manager=allow` to the freeplane.bat. Unfortunately this option can not be added by default because it is not compatible with Java versions below Java 17.

**Comment by lusitania** [comment]
That's a detail worth mentioning next to the download link in https://www.freeplane.org/wiki/index.php/Home. I'm fine with either option. In fact, I don't run any Java apps and had to install it just for Freeplane. Downgrade is easiest. Thanks
