### ISSUE TITLE
FP 1.10.1 0: script blocked

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#301]
**Describe the bug**
I get this kind of error when running the attached script
![Immagine 2022-04-09 180715](https://user-images.githubusercontent.com/62674157/162582036-abae0149-6005-4f99-b4aa-df2ddf218a93.png)
What am I missing in the system? How to reactivate it?

**To Reproduce**
this script is in groovy (just rename the subfix .txt in .groovy)

[LinkToPdfPageFull.txt](https://github.com/freeplane/freeplane/files/8457314/LinkToPdfPageFull.txt)

**Expected behavior**
.

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] w11
 - Java Version 17.0.2

**Comment by dpolivaev** [comment]
It looks like the script tries to access protected field, and that it is not allowed any longer.

**Comment by Illegit** [comment]
Or may be I do not have the java.awt? Is it possible after moving to java 17?

**Comment by Illegit** [comment]
Do you think it is a problem with antivirus? It happens on 2 laptops with w11 and w10 and different antiviruses...

**Comment by Illegit** [comment]
this is not for sure my field of knowledge....!

**Comment by dpolivaev** [comment]
No,  it has definitely no relation to antivirus. It might be caused by either java 17 or by groovy 4.
You find some information in the log and actually looking in log is highly recommended before you submit an issue.

**Comment by Illegit** [comment]
[log.txt](https://github.com/freeplane/freeplane/files/8457419/log.txt)

**Comment by macmarrum** [comment]
@Illegit https://www.youtube.com/watch?v=H0OetoieSDQ explains the topic of access modifiers in Java, if you want to learn a bit more about the context of the issue.

The Java API docs [GridBagLayout.html#defaultConstraints](https://docs.oracle.com/en/java/javase/17/docs/api/java.desktop/java/awt/GridBagLayout.html#defaultConstraints) describe the access modifier for `defaultConstraints` → `protected`

All in all, it looks like the script needs to be fixed to make it work on Java 17 / Groovy 4.

**Comment by Illegit** [comment]
Macmarrum, thank you for the explanations. Now it is clearer.
Now how to move to a public version of those methods? Probably I have to ask the original author (lilive).
Thanks
illegit

**Comment by macmarrum** [comment]
@Illegit 👍 

`GridBagLayout` comes with Java (there's little chance that `protected` will change to `public`).

I believe it's the correct approach to contact the author of the script. They could try to adapt it to the new environment, e.g. by changing how the class is used in their script.

**Comment by dpolivaev** [comment]
There is nothing I could do. You can check https://www.infoq.com/news/2021/06/internals-encapsulated-jdk17/ for background info.
