### ISSUE TITLE
FP 1.10.1 04: cursor wrong position in formula dialog

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#303]
**Describe the bug**
the problem is that the real position of the cursor  is not always correct, you can see at the end of the formula the cursor is very far from the last character (the parenthesis) imagine that this happens even with the previous character if you move to the left with the arrows you do not read where you really are, and normally you wright the instruction in the wrong position

**To Reproduce**
![Immagine 2021-06-04 234727](https://user-images.githubusercontent.com/62674157/162584275-910a7b43-1e11-4ac8-a8e9-e3b05ee64dc2.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] w11
 - Java Version 17.0.2

**Comment by Illegit** [comment]
<img width="654" alt="Annotazione 2022-04-09 190922" src="https://user-images.githubusercontent.com/62674157/162584440-544a9f71-4f45-4aba-b371-d659a6c2d462.png">
sorry wrong image

**Comment by Illegit** [comment]
<img width="635" alt="Annotazione 2022-04-09 195424" src="https://user-images.githubusercontent.com/62674157/162586112-02b87aa2-b8b6-4177-bd8b-630ec4ca48fd.png">

and in this, you can see the beginning after pressing enter.

**Comment by macmarrum** [comment]
The formula editor works well for me.
Maybe you could try to change the font – I use a mono-spaced font (like Cousine, Consolas or Courier New)

![2022-04-09_20,08,43](https://user-images.githubusercontent.com/7197131/162586535-7062d47e-aa9b-4b7c-8787-cdffe706a677.png)

**Comment by Illegit** [comment]
I changed to courier new but same problem
<img width="949" alt="Annotazione 2022-04-09 204259" src="https://user-images.githubusercontent.com/62674157/162587645-35f82cce-83e6-4c25-9a8d-14e3e03f5f14.png">
<img width="950" alt="Annotazione 2022-04-09 204209" src="https://user-images.githubusercontent.com/62674157/162587646-93bede37-9dd5-416b-92ef-538656c68909.png">

**Comment by Illegit** [comment]
last are in w10 java 17.0.2.

**Comment by dpolivaev** [comment]
Please add your formulas given in the screen shots as text to the report

**Comment by dpolivaev** [comment]
Generally, uploading mind maps where bugs can be observed should be a substantial part of any bug report

**Comment by Illegit** [comment]
Here below the formula:

=try{
w=format(round(((format(node['Day'].to.date,'yyyy-MM-dd')-node['LastDay'].to.date)/7-round((format(node['Day'].to.date,'yyyy-MM-dd')-node['LastDay'].to.date)/7000)*1000)),'0')
wr=w/52;
w=format(Math.round(52*(wr-Math.floor(wr))),'00')
if(w==0){w=52}
"" + format(node['Day'].to.date,'yyyy') +" "+ w}
catch(Exception exp)
{node['Day'].text}



and the map:
[mTA for bug.zip](https://github.com/freeplane/freeplane/files/8457876/mTA.for.bug.zip)

**Comment by dpolivaev** [comment]
I could not see any issues with the cursor position but discovered garbage on the line number ruler to the left of the edited groovy formula. I investigated the garbage, submitted an issue https://github.com/Sciss/SyntaxPane/issues/36 and created a work-around for Freeplane.

**Comment by Illegit** [comment]
It could be that both the problems are correlated?

Here what happens on my pc, there is this pointer wrong location on the editor
![Annotazione 2022-04-10 195217](https://user-images.githubusercontent.com/62674157/162633144-3d607ecc-1526-4922-af1d-d256f8c84b37.png)
illegit

**Comment by Illegit** [comment]
you see times the cursor is on the left, sometimes it is on the right, depending on when I open the pc...

**Comment by dpolivaev** [comment]
I do not understand why you mention the mouse. The only relevant cursor is the blinking keyboard cursor.
I also do not understand what you mean saying 
 > you see times the cursor is on the left, sometimes it is on the right, depending on when I open the pc...

If English is not your native language you could try using https://www.deepl.com/translator

**Comment by Illegit** [comment]
Now after restarting again the pc with the font Courier New it seems that there isn't this issue (of the cursor) any longer... if it re-appears I try to take a video. It remains the mixing on the left bar as you see in the attached images.

**Comment by dpolivaev** [comment]
The left bar is fixed in the latest preview 1.10.1_05
