### ISSUE TITLE
updating Freeplane doen't copy Templates folder

### ISSUE THREAD

**Issue by EdoFro** [freeplane/freeplane#320]
**Describe the bug**
When updating Freeplane from version 1.9.15 to v1.10.1, it creates a new user directory and it copies add-ons, icons, properties, etc from directory '1.9.x' into the new one '1.10.x', but it doesn't do this with the **templates** folder.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
The first FP v1.10.x that I installed was the one with Java embeded. Then I uninstalled it (without uninstalling the user directory) and installed it again  from the ...bin.zip file.

**Comment by dpolivaev** [comment]
Fixed in preview 1.10.1_07
