### ISSUE TITLE
When replacing "F2" with "I" to edit node text, the "i" character is inserted

### ISSUE THREAD

**Issue by NicolasWebDev** [freeplane/freeplane#321]
**Describe the bug**
When replacing "F2" with "I" to edit node text, the "i" character is inserted

**To Reproduce**
1. In Settings -> Behaviour, set "On key type" to "Do nothing"
2. Replace the F2 shortcut with "I" (the "Edit node core in-line" action)
3. With a node selected, press "I"
4. Freeplane enters edit mode inside the node, but inserts an "i" at the end of the node text

**Expected behavior**
I would expect to only enter edit mode, not to have an "i" character inserted, knowing that the "I" is only a shortcut. Once in edit mode, as expected all the characters should be inserted.

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version 1.9.14-1
 - Java Version java-11-openjdk

**Comment by dpolivaev** [comment]
Fixed in preview 1.10.1_07

**Comment by NicolasWebDev** [comment]
Thanks for the really quick fix @dpolivaev !!!
