### ISSUE TITLE
adding attributes to multiple nodes seems inconsistent

### ISSUE THREAD

**Issue by ofossum** [freeplane/freeplane#334]
# Describe the bug

When having multiple nodes selected, adding attributes to them all at once is different depending on which dialogue / function one chooses:

* _only the first_ selected node gets an attribute assigned…
  * …when using the right side-menu: `Attributes > new attribute`
  * …when using `Edit > Node properties > Edit attribute in-line`
* _all nodes_ get the attribute assigned when using `Edit > Node properties > Add attribute in dialogue`

# To Reproduce

1. Open a mindmap with multiple nodes
2. select multiple nodes
3. try adding an attribute to every node by using the dialogue in the side-menu on the right hand side

Effect: only the first selected node gets the attribute.

# Expected behavior

I'd expect _all the nodes_ get the attribute assigned - at least, when using the side-menu on the right (since one add a `New attribute`) and `Edit > Node properties > Add attribute in dialogue` .

# Desktop (please complete the following information):

 - OS: Linux (Arch)
 - Version: 1.9.14
 - Java Version: 11

**Comment by dpolivaev** [comment]
The side panel on the right shows all attributes of a single node. It is introduced for the case when attributes are not shown in the map so that can still be accessed,
