### ISSUE TITLE
Big Folding Symbols On 'No filtering'

### ISSUE THREAD

**Issue by abc16361** [freeplane/freeplane#338]
**Big Folding Symbols On 'No filtering'**

Big folding symbols show up when filtering condition is removed. This behaviour has existed on fp-1.10.1-01, and it could be so on previous many versions. Since the colour of the symbol is light before the version of 1.10.1-02, it does not get much attention. Recently a dark colour and thicker border of the symbol are adopted, so many big symbols displaying at the same time looks like a bug. 

![FoldingSymbol](https://user-images.githubusercontent.com/101362122/166101422-ab19a897-f3cc-41be-b18a-adc6f16a78d0.png)

Win 10
Java: jdk-17_windows-x64_bin_17.0.3.exe

**Comment by dpolivaev** [comment]
Preview 1.10.2
