### ISSUE TITLE
Can't Export Maps with images to PDF. 

### ISSUE THREAD

**Issue by TWiseGuy19** [freeplane/freeplane#351]
I cannot export mind maps with pictures in them to PDFs.  To see what I am experiencing, insert at least 5 images into the nodes, go to File>Export>PDF. I tried multiple times and it prevented me from exporting them.

**Comment by dpolivaev** [comment]
I can not see any problems.
Please attach an example ming map, all included images and the PDF file which is generated when you export the map as PDF.

**Comment by PaulWilliamWoods** [comment]
I had a problem which might be the same. I couldn't export to PDF on MacOS Freeplane at all - it created a zero-bytes file and sat using up huge quantities of processor energy. In Windows, however, the exact same map, the exact same export to PDF, almost instant production of a perfect map. My map happened to have images in, but I haven't tested whether this is the cause of the problem.

I tried to get around this problem by printing to PDF in the MacOS. That produced a file - but the branches which happened to sit at the break between pages were a little obscured - some lines couldn't be read - so it wasn't a good solution.

**Comment by euu2021** [comment]
Maybe, [this is related](https://sourceforge.net/p/freeplane/discussion/758437/thread/241cf375fa)?

**Comment by PaulWilliamWoods** [comment]
It's interesting you should say that - because I got the 'not enough memory' error when trying to export to jpeg instead. But I'm running it (in MacOS) on a new 16Gb-rammed M2 MacBook Air. I did notice ('enormous RAM usage' thread) that it was filling up all available RAM when I moved the map around the screen.

**Comment by PaulWilliamWoods** [comment]
I just checked - I get the 'out of memory' error on Windows when trying to export the same map to jpeg. My machine is a 16Gb i7-1065G7 with 1Tb SSD, so if it's running out of memory to export my 296Kb map, I'd better give up now! :)

**Comment by dpolivaev** [comment]
Let me google it for you

https://www.google.de/search?q=freeplane+pdf+export+does+not+work

https://github.com/freeplane/freeplane/issues/144
