### ISSUE TITLE
Freeplane doesn't work with Java 17

### ISSUE THREAD

**Issue by entodoays** [freeplane/freeplane#366]
**Describe the bug**
On Linux Freeplane doesn't launch when using Java version java-17-openjdk

**To Reproduce**
1. Install the above-mentioned java version
2. run Freeplane as usual
3. Nothing happens

**Expected behavior**
Freeplane runs as usual.

**Desktop (please complete the following information):**
 - OS: Fedora Workstation 36
 - Java Version java-17-openjdk

**Additional context**
When running from terminal I get the following errors: 
[Freeplane java 17 debug.txt](https://github.com/freeplane/freeplane/files/8676217/Freeplane.java.17.debug.txt)

**Comment by dpolivaev** [comment]
Line java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-17.0.3.0.7-1.fc36.x86_64/lib/libawt_xawt.so
means the java installation seems to be not complete

**Comment by fnatter** [comment]
I think that [entodoays](https://github.com/entodoays) has installed a headless jdk.

**Comment by entodoays** [comment]
I am using Fedora 36 and it came with openjdk 17. I installed the `java-latest-openjdk.x86_64` package which I don't think is the headless version as far as I know.
When I removed the package it removed the following:
> java-latest-openjdk-1:18.0.1.0.10-1.rolling.fc36.x86_64                       
> java-latest-openjdk-headless-1:18.0.1.0.10-1.rolling.fc36.x86_64

I installed the `java-11-openjdk.x86_64` package and Freeplane works fine with that.

**Comment by josephs07** [comment]
I had the same issue. It can be fixed by `sudo dnf install java-17-openjdk-devel` which installs the OpenJDK development package which includes the missing file.
