### ISSUE TITLE
FP 1.10.2: ZZZZZ* directories displayed in file browser dialog

### ISSUE THREAD

**Issue by Tom582** [freeplane/freeplane#370]
**Describe the bug**
When using the "Save map as ..." file browser dialog, sometimes directories named "ZZZZZ[0-9]+" (regular expression) are displayed that do not exist in Windows explorer.

**To Reproduce**
1. Start-up FP
2. Select a template
3. Klick on "File > Save map as ..." and browse through different directories
4. Check for ZZZZ* directories

**Expected behavior**
The file browser dialog should display only objects that are also displayed by the Windows explorer.

**Screenshots**
![SaveMapAsDesktopFolder](https://user-images.githubusercontent.com/45515358/168423561-3885c518-ff7b-4545-b74e-588cb4da3ab3.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 20H2
 - Java Version: 8 Update 181

**Comment by dpolivaev** [comment]
I do not think it is a freeplane related issue.
All I could find is this link:
https://social.technet.microsoft.com/Forums/Lync/en-US/096b353f-5f97-43a8-8cdd-32814f2fbcbb/weird-files-in-public-profile-beginning-with-zzzzz-or-?forum=win10itprogeneral
