### ISSUE TITLE
FP 1.10.2: Alt Key Codes are not recognized

### ISSUE THREAD

**Issue by Tom582** [freeplane/freeplane#371]
**Describe the bug**
I often use Alt key codes to enter special characters in my mindmaps. In FP 1.9.14 everything went fine, but in FP 1.10.2 many key codes only result in a "?".

**To Reproduce**
1. Make sure to have the number lock enabled on your keyboard, start-up FP and select a template
2. Edit the Root node or any other node
3. Hold down the Alt key, enter 16 on the key pad and release the Alt key.
4. Rather than the character "►" only a "?" is displayed.

**Expected behavior**
The character "►" should be displayed.

**Mind map files**
[New Mindmap.zip](https://github.com/freeplane/freeplane/files/8692835/New.Mindmap.zip)

**Screenshots**
![AltKeyCodes](https://user-images.githubusercontent.com/45515358/168423951-94034121-751b-44c9-b56d-1c5939f26e95.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 20H2
 - Java Version. 8 Update 181

**Comment by dpolivaev** [comment]
Fixed in preview 1.10.3_01 (to be uploaded later today)
