### ISSUE TITLE
[not closed!] Is there any way to prevent the location information of the clone node from being shared?

### ISSUE THREAD

**Issue by moonlitsp** [freeplane/freeplane#372]
(I'm not an English speaker. Translator has been turned on. Please understand.)
I'm an writer who came all the way here because I only wanted a mind map with a clone function on the node, and I'm ignorant of technology.

I studied the overall function hard, but when I moved the clone node, the other clones moved together, so I couldn't do normal node placement.

Could you give me an option to move the clone node separately? I'm going to use this program like an index card app with a reference function. I thought of a function like the reference node of the margin note 3, but I'm sad that I can't use it like that.

Over the past few years, I've installed or tried almost every mind map app or index card app or documentation app that's actually searched on the Internet. There were very few apps that had some functionality, but they didn't allow Korean. Could you please give me an option to move the clone separately? Please...

**Comment by dpolivaev** [comment]
If you clone the whole subtree, you can't move its nodes independently.
It works only for single node clones

**Comment by moonlitsp** [comment]
I'm talking about a single clone. I'm not talking about placement, I'm talking about other clones changing positions as they drag and move. Not including the subtree, but a single clone.
Whether it's a single clone node or a node including a subtree, it moves together when you hold the circle and move it. I mean, I want to move it independently.
