### ISSUE TITLE
Latest version (1.10.2) does not work on my 32bit machine.

### ISSUE THREAD

**Issue by PandaGlo1** [freeplane/freeplane#389]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Screenshots**

**Desktop (please complete the following information):**
 - Java Version

**Additional context**

**Comment by dpolivaev** [comment]
I don't know why

**Comment by PandaGlo1** [comment]
Thanks.  Sorry to have almost bothered you.
