### ISSUE TITLE
useAccentColor issue with an icon and other icons need to be removed

### ISSUE THREAD

**Issue by rexelbartolome** [freeplane/freeplane#391]
filter.svg isn't responding to the `useAccentColor` tag for the lower left part, but it works in the right click menu
![image](https://user-images.githubusercontent.com/88552647/169691895-248d5ef8-4b82-44cf-b205-e6cce54c3411.png)

also please remove the lines containing these svg's in freeplane.properties since their icons were intentionally not updated as Predrag and I planned on removing them

```
AttributesView.svg
SetAcceleratorOnNextClickAction.svg
acceleratorPresets.svg
```

**Comment by dpolivaev** [comment]
> AttributesView.svg
SetAcceleratorOnNextClickAction.svg
acceleratorPresets.svg

How should I replace them?

**Comment by dpolivaev** [comment]
```
menu_displayAttributes.icon=/images/AttributesView.svg?useAccentColor\=true
SetAcceleratorOnNextClickAction.icon=/images/SetAcceleratorOnNextClickAction.svg?useAccentColor\=true
acceleratorPresets.icon=/images/acceleratorPresets.svg?useAccentColor\=true
```
or should they just be removed without any replacement?

**Comment by rexelbartolome** [comment]
> ```
> menu_displayAttributes.icon=/images/AttributesView.svg?useAccentColor\=true
> SetAcceleratorOnNextClickAction.icon=/images/SetAcceleratorOnNextClickAction.svg?useAccentColor\=true
> acceleratorPresets.icon=/images/acceleratorPresets.svg?useAccentColor\=true
> ```
> 
> or should they just be removed without any replacement?

yes just removed without replacement :)

**Comment by dpolivaev** [comment]
Preview 1.10.3_05
