### ISSUE TITLE
Homepage/Info page update screenshots

### ISSUE THREAD

**Issue by rexelbartolome** [freeplane/freeplane#392]
They're now complete (aside from the User Testimonials and Other Features which I think are optional anyway) this is what they look like:

![image](https://user-images.githubusercontent.com/88552647/169693233-13446a6d-9737-4f23-ba4e-4c34392ce5cb.png)

And they can be downloaded here

[freeplane-features.zip](https://github.com/freeplane/freeplane/files/8749317/freeplane-features.zip)

**Comment by dpolivaev** [comment]
Where could we place them?

**Comment by dpolivaev** [comment]
I would like to remove word "UPDATE:" because actually things become old very fast.

**Comment by dpolivaev** [comment]
I have uploaded some of them to Source Forge (there is a limit of 6 screenshots there).
If you think we could add them to wiki, or to the project readme let us talk. I would like to give you the access to do it.

**Comment by rexelbartolome** [comment]
> I have uploaded some of them to Source Forge (there is a limit of 6 screenshots there). If you think we could add them to wiki, or to the project readme let us talk. I would like to give you the access to do it.

Yeah I was also thinking about editing the readme myself. I'll message you on discord about it :)

**Comment by EdoFro** [comment]
> > I have uploaded some of them to Source Forge (there is a limit of 6 screenshots there). If you think we could add them to wiki, or to the project readme let us talk. I would like to give you the access to do it.
> 
> Yeah I was also thinking about editing the readme myself. I'll message you on discord about it :)

Nice work! Congratulations!
