### ISSUE TITLE
Some icons looking jagged when Windows has scaling

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#393]
On Windows 11 there is an option  `Display settings>Scale and Layout>Custom scaling`,  where my laptop auto set itself to 125%, saying that it is recommended. 

When I set the scale to 100%, everything looks sharp in FP, but when I set to 125%, those two elements looks jagged:

- The splash screen
![image](https://user-images.githubusercontent.com/77707706/169694104-0cd85675-5e7b-4fe3-b770-288783469f75.png)

- The inactive version of the icons. The active icons look normal.- 
![image](https://user-images.githubusercontent.com/77707706/169694186-ef4aca31-17c9-4b89-adbd-8775a9da343b.png)

I'm using the latest AMD drivers
Thanks,

**Comment by dpolivaev** [comment]
Could you please check it with all look-and-feels and write here which look-and-feels have this problem and which do not?

**Comment by euu2021** [comment]
yes, all of them have this problem

**Comment by dpolivaev** [comment]
Can you please try to add a line 
```
-Dsun.java2d.uiScale=1.0
```
in files freeplane.l4j.ini and freeplaneConsole.l4j.ini in your freeplane installation directory and run freeplane.exe?
Please let me know if it helps and if you see any negative consequences

**Comment by euu2021** [comment]
It solves the problem, and I don't see negative consequences 👌

**Comment by dpolivaev** [comment]
The fix does not work on MacOs. It is a limitation of the Java library which is not easy to overcome.
