### ISSUE TITLE
Regression on 1.10.3_pre4: touchpad scrolling is dead on the map view

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#395]
The scrolling in the preferences window and on format panel is fine.

I will attach my auto.properties
[auto.zip](https://github.com/freeplane/freeplane/files/8749564/auto.zip)

**Comment by dpolivaev** [comment]
I can not see it here.
Which OS?
Please attach your log file.

**Comment by dpolivaev** [comment]
I got it

**Comment by dpolivaev** [comment]
Preview 1.10.3_05
