### ISSUE TITLE
wrong: logs

### ISSUE THREAD

**Issue by Narchya** [freeplane/freeplane#396]
![image](https://user-images.githubusercontent.com/106069201/169787744-a7b21332-0e62-47e5-9b8d-66b96c402705.png)
hi, i do not know what's the problem it should be classified, it just report the wrong to me and i am confused about its impact and how should i solve it.
Thx

**Comment by dpolivaev** [comment]
Could you please zip the log files from this directory and attach them to your bug report?

**Comment by dpolivaev** [comment]
Please reopen the issue if you want to send the  logs
