### ISSUE TITLE
Doing a multiple word search in the icon table result in unintentional add of icons

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#399]
I'm used to adding icons from the command search, where I can make a multiple word search to find icons more quickly. For example, to search for the "artist pallet" icon, I can simply type "ar pa". 

Now, I'm moving to use the icon table, but I noticed that inputting Space adds whatever icon is selected. So, the multiple word search exists, but it's not usable.

Thanks,

**Comment by euu2021** [comment]
Tested. Thanks!

(should I close the issue in this situation?)

**Comment by dpolivaev** [comment]
Preview 1.10.3_06
