### ISSUE TITLE
Recently used icons in the icon table

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#400]
The lateral icon panel has a top section with recently used icons. That would be pretty useful to have on the icon table, too, as it is not easy to find those little devils in this crowd:

![image](https://user-images.githubusercontent.com/77707706/170120002-207becc7-5667-43d2-a8ab-0dd935f9b962.png)

Thanks,

**Comment by dpolivaev** [comment]
Why do you need them here if you already have them on the icon toolbar?

**Comment by euu2021** [comment]
I mostly use undocked windows, so I don't have access to the icon toolbar.

**Comment by euu2021** [comment]
Tested. Thanks!

**Comment by dpolivaev** [comment]
Preview 1.10.3_06
