### ISSUE TITLE
Avoid floating nodes overlapping

### ISSUE THREAD

**Issue by Neeqstock** [freeplane/freeplane#403]
**Problem description**
Whenever there are neighboring floating nodes within the map, the nodes overlap with each other resulting in unreadability and confusion. Also, which nodes are shown in the foreground seems arbitrary.

**Solution I'd like**
I use floating nodes a lot, particularly to mark things on maps that I use as background images (see attached example). I wish there was a solution to momentarily display only certain nodes, so that they don't overlap, or to decide which group of nodes should be visible in the foreground.

**Alternatives I've considered**
A simple solution would be, **when a node is selected**, to put in the foreground the child nodes and relatives only of the floating node to which they belong, **including the cloud surrounding them** (see attached image).

**Additional context**
I included a screenshot of the issue and a possible solution (faked with Paint ;)).

**ISSUE:**

![Issue](https://user-images.githubusercontent.com/15343295/170371779-f6f32c73-eb02-4d19-aecc-31d856d940a4.png)

**POSSIBLE SOLUTION:**

![Solution](https://user-images.githubusercontent.com/15343295/170371789-3e474d91-575c-4007-93ce-b27886626173.png)

**Comment by euu2021** [comment]
Idea for workaround: I don't know exactly how you use the map, but if you want to hide momentarily one cloud, you can use filters or hide nodes. So, in your example above, I would select the node "Liberare i Pedoni", and use `Filter->Filter selected nodes`, which would hide the other cloud.

On a side note, some time ago, we had [a discussion about marking things on maps](https://sourceforge.net/p/freeplane/discussion/758437/thread/16ff50db79/?limit=25#fcc1/516d). This may be an interesting read for you.

**Comment by Neeqstock** [comment]
@eu2021 the workaround you suggested based on filters works like charm, thanks!
I mapped `Filter selected nodes` and `No filter` to two reachable keyboard shortcuts (i. e. ALT+Q and ALT+W) and activated `Show descendants` on the filter menu. Things became really manageable, I don't know if I prefer this or the original solution I proposed. Let's say I'd like to see both :') but for now this saved my work.

The _discussion about marking things on maps_ was very interesting for me to read, indeed.
Sometimes I mark places in multiple images per maps by setting a node `N` which has these children: 

- a node with an image on its extension
- floating nodes marking places on the image

Since floating nodes are children of the node `N` as well, their position becomes relative to `N`, and they appear/disappear depending on `N` being folded or not. Very comfortable.
The only drawback is that clouds and connectors get rendered _behind_ the image, so they're not visible.

I really love what Freeplane allows you to do, btw. <3

**Comment by euu2021** [comment]
> The only drawback is that clouds and connectors get rendered behind the image, so they're not visible.

About the connectors, you can solve by unchecking `Preferences…->Defaults->Connectors->Paint connectors behind nodes`. But, this has the shortcoming of having connectors crossing above the text nodes, which can become messy.

About the Clouds, I don't see a solution. I tried multiple ways of inserting images with the [Insert Inline Image Addon](https://www.freeplane.org/wiki/index.php/Add-ons_(install)#:~:text=Images%20and%20icons-,Insert%20Inline%20Image,-by%20Volker%20B%C3%B6rchers), but the clouds always get behind the image.

**Comment by dpolivaev** [comment]
If you need a semiautomatic layout you can also try a new option that allows overlapping nodes that are not floating nodes. You probably need the preview version for it.

View->View settings->Allow compact layout
