### ISSUE TITLE
Conditional styles using "For any descendant" are way slower than using an equivalent script filter

### ISSUE THREAD

**Issue by EdoFro** [freeplane/freeplane#406]
**Describe the bug**
I have a big mindmap, not giant, but big, and I added a Conditional Style rule using the option "For any descendant" and the mindmap got very slow every time I tried to select another node.

"big" map means:
![image](https://user-images.githubusercontent.com/35700575/170535357-ac2012b8-580d-49ec-be45-65d22f6e28c9.png)

I have other mindmaps that are maybe bigger where I use the "_same_" conditional style and I don't have that problem.

I compared both and in one I used the option "For any descendant" and in the other I created a script filter that looked the descendants of the node to look for the condition. In teory both conditional rules do the same, but one is way faster than the other.

**To Reproduce**
(_I added a sample mindmap you can test_)
In a big map add these conditional rules. (are not the same that I use, but are equivalent)

This test rule logic is: the node gets the conditional style, if any of its descendants has a formula in its text or its details.

|Rule|Looks on|Type|Condition
|--|--|--|--|
|1|'Own'|Script filter|` (node.findAll() - node)?.any{it.text.startsWith('=') \|\| (it.details && htmlUtils.htmlToPlain(it.details.html).startsWith('='))} `|
|2|'For any descendant'|Script filter|` node.text.startsWith('=') \|\| (node.details && htmlUtils.htmlToPlain(node.details.html).startsWith('='))} `|

**Expected behavior**
I would expect that the inbuilded "For any descendant" option works faster or, at least, as fast as the script way. Maybe there is some space for improvement or optimization.

**Mind map files**
I created a mindmap as example. it has two conditional style rules. Both are initially inactivated.
![image](https://user-images.githubusercontent.com/35700575/170541585-5c62ffac-9d8e-41bd-bcdb-74a0fc92658b.png)

Activate one at a time and look the diference in speeds.
[test Conditional styles speed.zip](https://github.com/freeplane/freeplane/files/8780874/test.Conditional.styles.speed.zip)

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version FP 1.10.2
 - Java Version Java 17

**Additional context**
-

**Comment by dpolivaev** [comment]
Checking the case was helpful and I could improve performance a bit.
However running a script always has an overhead. Therefore executing one script is always faster than running a script multiple times with different nodes.
