### ISSUE TITLE
Regression: Diagonal trajectory when zooming with two fingers in the touchpad

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#412]
It started in 1.10.3-pre06.

It's similar to what I described in the first point of [this post](https://sourceforge.net/p/freeplane/discussion/758437/thread/494dfaa629/?page=1&limit=25#4bff).

Windows 11
Java version: 15.0.7

**Comment by dpolivaev** [comment]
Preview 1.10.3_07
