### ISSUE TITLE
Regression: in the icon table, Enter doesn't close the window

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#413]
The previous behavior was: Enter inserts the icon and closes the window. This was more convenient than the current "Ctrl+Enter".

I think that `inserting one icon and closing the window` is a more frequent operation than `inserting and not closing the window`. So, I think that `inserting one icon and closing the window` should have precedence in getting the more convenient key. 

1.10.3-pre06

**Comment by dpolivaev** [comment]
Now icons can not be inserted using SPACE. They can be inserted either using ENTER or using a shortcut that is specific to this table. For consistency using control+enter or the shortcut closes the dialog but enter does not.
