### ISSUE TITLE
Regression: broken ticked checkboxes

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#414]
Now, they are showing up broken:

![image](https://user-images.githubusercontent.com/77707706/170876937-d6535f30-5f0d-4a5e-8c50-b23e00a53b1a.png)

Note: I set `Preferences…->Appearance->Look and feel->Monitor size (inches)` to 23 (but, my actual monitor is 15), because I like a smaller UI. When I set it to 15, the icons show up in the usual old way.

1.10.3-pre06
Windows 11
Java version: 15.0.7

**Comment by dpolivaev** [comment]
Preview 1.10.3_07
