### ISSUE TITLE
Attributes not visible in the dark* templates

### ISSUE THREAD

**Issue by HaaiHenkie** [freeplane/freeplane#419]
**Describe the bug**
When you are using one of the Dark templates the attributes of a node are not visible because fore- and background colours are the same.

**To Reproduce**
1. Open or create a map with nodes that have attributes
2. Apply one of the following templates (Format > Manage Styles > Replace map styles by...
   - dark_gruvbox_template.mm
   - dark_nord_template.mm
   - dark_purple_neon_template.mm
   - dark_solarized_template.mm
4. Hide attributes (View > Node attributes > Show selected attributes, or: Hide all attributes) and hover over node with attributes
   - Error: Text and cell borders are invisible
6. Show attributes (View > Node attributes > Show all attributes) and look at a node's attributes
   - Error: Text and cell borders are invisible
   - OK: Cell borders of selected node and text in selected cell are visible
1. Select a node with attributes and edit the attributes inline (Alt + F9)
   - Error: Text is invisible in unselected cell and while editing text in a cel
   - OK: Text in selected cell and selected characters while editing are visible. Cell borders are visible 
1. Select a node with attributes and edit the attributes in Tool panel
   - Error: as soon as you edit text in a cell the text becomes invisible
   - OK: Attributes text and cell borders are visible. Selected characters while editing are visible

**Expected behavior**
Attributes in Dark templates are visible at all times like for example in Darcula-1.7.mm

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Screenshots**
Hide attributes and hover:
Darcula-1.7.mm (correct):
![image](https://user-images.githubusercontent.com/8525411/171057286-9be24a15-1f44-420a-a1a8-ef8081e8b623.png)
dark_gruvbox_template.mm (error):
![image](https://user-images.githubusercontent.com/8525411/171057395-8cd704c7-cba8-443f-b675-d2bcf6f6804b.png)

Show attributes
Darcula-1.7.mm (correct):
![image](https://user-images.githubusercontent.com/8525411/171057554-9447e3fe-21ad-4fa7-9c27-4c1aadb0e454.png)
dark_nord_template.mm (error):
![image](https://user-images.githubusercontent.com/8525411/171057645-b5f3b328-69fa-4acc-9c1b-56eaf5c9e36d.png)

Edit attributes inline
Darcula-1.7.mm (correct):
![image](https://user-images.githubusercontent.com/8525411/171057784-06fd4f61-7a53-4a7a-8284-abd5110e64c7.png)
dark_purple_neon_template.mm (error):
![image](https://user-images.githubusercontent.com/8525411/171057852-dfa4f841-f30f-480b-81ab-6f955625fb4f.png)

Edit attributes in Tool panel
Darcula-1.7.mm (correct):
![image](https://user-images.githubusercontent.com/8525411/171058115-c006e47d-9b6e-4510-96c6-6df2b1386e46.png)
dark_solarized_template.mm (error):
![image](https://user-images.githubusercontent.com/8525411/171058391-d9c93d49-4b6b-456d-941a-7b28c1857e0d.png)

**Desktop (please complete the following information):**
 - OS: Window 11
 - Version 1.10.2
 - Java Version 15 (runtime included in Freeplane download)

**Additional context**
Part of this bug is a reoccurrence of [2 closed bugs](https://sourceforge.net/p/freeplane/bugs/search/?q=dark+AND+reported_by%3Ahaaihenkie)

**Comment by dpolivaev** [comment]
Preview 1.10.3_08

**Comment by HaaiHenkie** [comment]
Checked in preview 1.10.3_09 and everything fixed. Thanks!
