### ISSUE TITLE
MacOS verification prroblem.

### ISSUE THREAD

**Issue by mprakash13** [freeplane/freeplane#420]
On Mac (MacOS version 12.3.1), Freeplane versison 1.10.2 gives the following error on startup:

“Freeplane” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

**Comment by HaaiHenkie** [comment]
You need to disable notarization for Freeplane, see https://sourceforge.net/p/freeplane/discussion/758437/thread/e4374ed1c2/

**Comment by mprakash13** [comment]
Thanks, that worked.
   Mayank

**Comment by shopirye** [comment]
Hey - I'm also running into this issue, but following the steps above won't work for me and I still get the same error message.

**Comment by dpolivaev** [comment]
Good news: I was able to fix the issue completely. You can download the verified version from https://sourceforge.net/projects/freeplane/files/freeplane%20stable/

**Comment by shopirye** [comment]
Thank you so much @dpolivaev !!!

**Comment by ndeffayet** [comment]
I still get the following error message with Freeplane-1.10.6-apple.dmg:

“Freeplane” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.
