### ISSUE TITLE
Main window zoom depends on monitor scale factor app opened first time

### ISSUE THREAD

**Issue by flyasky** [freeplane/freeplane#421]
**Describe the bug**
Window zoom depends on monitor scale factor app opened first time.

**To Reproduce**
1. Setup second monitor (first laptop with scale 125%(recommended), second HP with scale 100%(recommended))
2. Start Freeplane, let's suppose it opens on laptop display.
3. Move window to HP display and close the app
4. Open app again. Main window will be opened on HP display with all elements zoomed up.
5. Moving app between screens does not reduce zoom.
6. To fix I need to move app back to laptop display and close it there.

**Expected behavior**
Same elements scale.

**Mind map files**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/213282/171664177-2582bd29-df1c-441a-a913-988d26759911.png)
![image](https://user-images.githubusercontent.com/213282/171664248-efb583e7-0891-4c29-b22c-5395902a3a47.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.10.2
 - Java Version 11.0.15

**Additional context**
N/A

**Comment by flyasky** [comment]
![image](https://user-images.githubusercontent.com/213282/171664917-c27c9ebb-ba5b-4514-aa39-4b3172dfd097.png)

**Comment by dpolivaev** [comment]
Sorry, I don't know how to fix it
