### ISSUE TITLE
Latex texts become garbled characters when exported to PDF

### ISSUE THREAD

**Issue by 123sleaf-123** [freeplane/freeplane#423]
**Describe the bug**
All the texts using latex are displayed well on the workspace, but become garbled characters when exported to PDF file. They are not printed in what they are looked like on the workspace.

**To Reproduce**
1. Double click any peer to edit
2. Type '\latex ...'
3. Press _Enter_ to save
4. Export the .mm file as a PDF file
5. See error

**Expected behavior**
It is displayed what it looked like on the workspace.

**Mind map files**
[Probability  Statistics.zip](https://github.com/freeplane/freeplane/files/8837708/Probability.Statistics.zip)

**Screenshots**
The PDF looked like:
![1654346173947](https://user-images.githubusercontent.com/80097831/171999270-a7a76acb-b1ad-4451-953b-b355861690e5.png)
The right format looked like:
![1654346348819](https://user-images.githubusercontent.com/80097831/171999308-348150af-879a-43c1-b99d-d76af60b7bf9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.10.2
 - Java Version 15.0.7

**Comment by fnatter** [comment]
hello 123sleaf-123,

please try the "convert texts to shapes" preferences option which you can find by using command search:
- Ctrl+F1
- type export
- double-click on the first result
You can also try the "embed fonts" option (2nd hit in command search).

Best Regards,
Felix

**Comment by dpolivaev** [comment]
I am sorry I don't think I can fix it. Try the work arounds suggested by Felix.
