### ISSUE TITLE
Bugs on Import branch

### ISSUE THREAD

**Issue by abc16361** [freeplane/freeplane#425]
Three Import functions (**Branch, Linked branch and Linked branch without root...**) do not work on **unsaved** new map created from the templates like **standard-1.6.mm, dark_nord_template.mm, etc,** in the installation folder.  Applying these three medthods on the unsaved new map pops up error alerts. But on unsaved new maps created from user's templates, all three methods work smoothly. One strange thing is, importing a map (**dp_test.mm**) modified on December 2021, possibly saved on fp-1.9.12, goes well, but fails again if this map is saved again (named as **dp_test2.mm**) before importing on the current version of 1.10.03-pre07.  

Testing on windows 10, java-17 and fp-1.10.03-pre07 
Files: 
[import.zip](https://github.com/freeplane/freeplane/files/8839253/import.zip)
- dp_test.mm   	: saved on December 2021 on fp-1.9.12
- dp_test2.mm 	: copy of dp_test.mm saved on fp-1.10.03-pre07
- standard-1.6-saved.mm	: created from standard-1.6.mm, can be used as a user's template to create new map, and all three import methods work well on it.
- log
![Import1](https://user-images.githubusercontent.com/101362122/172033281-8b844d9f-2f27-4e27-bf98-fc85e5de7031.png)
![Import2](https://user-images.githubusercontent.com/101362122/172033288-95b784c2-3181-4723-8357-1c43c73cae7d.png)

**Comment by dpolivaev** [comment]
Preview 1.10.3_08
