### ISSUE TITLE
Improve selected node colors in some included templates

### ISSUE THREAD

**Issue by burnuser** [freeplane/freeplane#432]
**Is your feature request related to a problem? Please describe.**
Get a bad to read background color (like #4E85F8) for selected node in every new map
(https://github.com/freeplane/freeplane/discussions/430)

**Describe the solution you'd like**
Add an Option in Preferences - Defaults: use selected color for selected node **instead** of map style.

**Describe alternatives you've considered**
A) The Standard Templates should never use color combinations like black Text on relatively dark blue background like #4E85F8!
It is hard to read for normal people and an in legal terms an accessibility nightmare!
The original color #ccffff is much better!
B) More easy way to (1 click) change of selected node color style in used template.

**Additional context**
Found a workaround with putting my own manually styled template in template directory and declared it as standard. But for newbies (I'm working also as Trainer and recommend Freeplane every time) is this not as easy as it should be.

**Comment by dpolivaev** [comment]
> The Standard Templates should never use color combinations like black Text on relatively dark blue background like #4E85F8

You are right, let me know which standard templates do it and I shall fix it

**Comment by dpolivaev** [comment]
The whole idea of using styles for selected nodes is to avoid bad color combinations.
Therefore the templates should be fixed but this feature request should IMHO be rejected.

**Comment by burnuser** [comment]
I don't need such a feature, if color combinations are OK.
And in earlier versions of freeplane the problem does not appear to me, as **background color for selected node** was always #ccffff

Now it is hardcoded #4E85F8 for:
BigMap
BuzanMap
essey
standard-1.6
standard-1.6-noEdgeColor

In Darcula-1.7 is the combination of #ccffff with light text also a (reverse) problem.

**Comment by dpolivaev** [comment]
Yes, could you please give me suggestions how to change it?

**Comment by burnuser** [comment]
For the maps with black Text, I would recommend the traditional #ccffff
For Darcula I would recommend a dark color like #660000 (which also fits good with a vampire theme :-)

**Comment by dpolivaev** [comment]
Colors changed in preview 1.10.3_10
