### ISSUE TITLE
Current version of XML Schema

### ISSUE THREAD

**Issue by vlcinsky** [freeplane/freeplane#440]
**Describe the bug**
I was searching for XML schema to validate structure of freeplane file.

The only schema I have found is at https://github.com/igor-go/mm_xslt_exports/blob/master/freeplane_1.3.x.xsd

Trying to validate simple file created in the FreePlane v1.7.10 fails.

**To Reproduce**
1. Create new freeplane document - only having root element. Save it as empty.mm file
2. download the xml schema
3. using some tool, e.g. xmlstarlet, validate empty.mm file: `xmlstarlet val --err --xsd schema/freeplane_1.3.x.xsd empty.mm
Output of the validation reports couple of errors, so the xml schema is apparently outdated and invalid:

```
$ xmlstarlet val --err --xsd schema/freeplane_1.3.x.xsd empty.mm 
empty.mm:3.131: Element 'node', attribute 'STYLE': [facet 'pattern'] The value 'oval' is not accepted by the pattern 'hide_edge'.
empty.mm:3.131: Element 'node', attribute 'LOCALIZED_TEXT': The attribute 'LOCALIZED_TEXT' is not allowed.
empty.mm:3.131: Element 'node', attribute 'FOLDED': The attribute 'FOLDED' is not allowed.
empty.mm:6.185: Element 'properties', attribute 'edgeColorConfiguration': The attribute 'edgeColorConfiguration' is not allowed.
empty.mm:6.185: Element 'properties', attribute 'fit_to_viewport': The attribute 'fit_to_viewport' is not allowed.
empty.mm:6.185: Element 'properties': The attribute 'show_icon_for_attributes' is required but missing.
empty.mm:6.185: Element 'properties': The attribute 'show_note_icons' is required but missing.
empty.mm:9.103: Element 'stylenode', attribute 'UNIFORM_SHAPE': The attribute 'UNIFORM_SHAPE' is not allowed.
empty.mm:9.103: Element 'stylenode', attribute 'VGAP_QUANTITY': The attribute 'VGAP_QUANTITY' is not allowed.
empty.mm:11.78: Element 'stylenode': This element is not expected.
empty.mm:66.70: Element 'hook', attribute 'RULE': The attribute 'RULE' is not allowed.
empty.mm - invalid
```

**Expected behavior**
There shall exist XML schema, which describes XML structure of the latest freeplane files.

Created mm files shall validate against it.

**Mind map files**
[empty-map.zip](https://github.com/freeplane/freeplane/files/8861377/empty-map.zip)

**Desktop (please complete the following information):**
 - OS: Debian 11

**Additional context**
Apparently the schema I used is outdated. Anyway, I did not find anything more recent.

Having valid XML schema shall allow generating libraries for parsing and creating mm files. E.g. using [Python library xsdata](https://xsdata.readthedocs.io/en/latest/) one can generate python package allowing to parse and create xml files.

**Comment by dpolivaev** [comment]
The schema does not exist. I am sorry.
