### ISSUE TITLE
Java 1.8  not supported/recognised under Linux

### ISSUE THREAD

**Issue by HaaiHenkie** [freeplane/freeplane#442]
**Describe the bug**
Running Freeplane on Linux under OpenJDK version "1.8.0_312" gives the error ¨Currently, freeplane requires java version 8 or from 11 to 17¨

**To Reproduce**
1. Install freeplane_1.10.2~upstream-1_all.deb on Linux Mint with OpenJDK version "1.8.0_312" installed
2. Run freeplane from a terminal
3. The following error is visible

        $ freeplane
        ERROR:   Found /usr/bin/java in $PATH.
        ERROR:   It has version 1.8.0_312
        ERROR:   Currently, freeplane requires java version 8 or from 11 to 17
        ERROR:   
        ERROR:   Select a supported java version
        ERROR:   by setting FREEPLANE_JAVA_HOME to a valid java location
        ERROR:   OR use an unsupported java version
        ERROR:   by setting FREEPLANE_USE_UNSUPPORTED_JAVA_VERSION to 1

**Expected behavior**
Freeplane starts up (java 8 and 1.8 are the same java version)

**Mind map files**
NA

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3
 - Version 1.10.2
 - Java Version: OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)

**Additional context**
I read that Freeplane still supports Java 8 under Linux and was just verifying that. If it were up to me you can drop Java 8 support, so that supported Java versions for Linux and Windows are the same.

**Comment by dpolivaev** [comment]
Fixed in preview 1.10.3_10

**Comment by HaaiHenkie** [comment]
Confirmed that it is fixed in preview 1.10.3_10
