### ISSUE TITLE
Images are not exported to doc or odt format

### ISSUE THREAD

**Issue by juasiepo** [freeplane/freeplane#453]
**Describe the bug**
Images are not exported to doc or odt format

**To Reproduce**
1. Export a map containing an image to .odt or .doc format

**Expected behavior**
Images are embedded in the exported .odt or .doc file

**Desktop (please complete the following information):**
 - OS: Windows/Linux
 - Version: 1.10.2
 - Java Version: OpenJDK 11

**Additional context**

**Comment by dpolivaev** [comment]
It is not implemented
