### ISSUE TITLE
Preferences freezes Freeplane with second screen attached

### ISSUE THREAD

**Issue by bakelnaar** [freeplane/freeplane#456]
**Describe the bug**
When trying to open the preferences panel, freeplane seems to freeze and the preferences panel does not appear. That only happens when a secondairy screen is active. When only one screen is actively used, the preferences menu opens without problems.

**To Reproduce**
1. Having a secondairy screen connected (both 4K screens, one up straight, the other one sideways on a 90 degree angle)
2. Click on Tools -> Preferences in the menu bar (Ctrl + Comma also suffices)
3. Freeplane freezes 

**Expected behavior**
The preferences menu opening

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19043
 - Version 1.10.2
 - Java Version: 15.0.7

**Comment by dpolivaev** [comment]
I can not reproduce the problem. Could you please attach the log files?

**Comment by bakelnaar** [comment]
Sorry for the late reply, I was not in the ability to respond any sooner. I've tried to reproduce it now with the same setup (the idea was to record it with a screen capture tool), but now it doesn't crash anymore. 

As far as I know, nothing could be found in the log files back then, so sorry for the wild goose chase. Probably was it some interference with some other software I was running back then.
