### ISSUE TITLE
Option to revert buttonbar to previously theme

### ISSUE THREAD

**Issue by antoniopaolini** [freeplane/freeplane#457]
Hello, 
I'm not happy with the new toolbar theme (1.10) and then I looking for a option in the preferences to change the icons but I can't find it.
No way to have the old colored button bar?

Bye

**Comment by dpolivaev** [comment]
No way because the time does not go back.
If you like you can contribute your concerns to the discussions.

**Comment by dpolivaev** [comment]
By the way, there is a lot of work going and you can check the latest previews if you want to see the current state and share your feedback.

**Comment by antoniopaolini** [comment]
> No way because the time does not go back.

Not very user-oriented in my opinion :-/ but I can understand your point, it is open source, if someone doesn't like it there are forks.

I'm a relatively new user (was a freemind user); I will contribute to the discussion in the future.

Anyway, thank for your fast reply. :-)
And sorry for my bad english.
