### ISSUE TITLE
Freeplane can't start after closing toolbar

### ISSUE THREAD

**Issue by abc16361** [freeplane/freeplane#460]
**Describe the bug**

On version fp-1.10.3-pre15, the toolbar is open on default. If toolbar is toggled **off** before Freeplane closes, Freeplane can't restart. Removing auto.properties from user directory or changing "false" on toolbarVisible setting to "true", Freeplane starts again.

**Screenshots**
![toolbar](https://user-images.githubusercontent.com/101362122/174461689-483d3090-7175-4d94-9282-5f3ca2f59893.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version: fp-1.10.3-pre15
 - Java: jdk-17_windows-x64_bin_17.0.3.msi

**Additional context**
[auto.zip](https://github.com/freeplane/freeplane/files/8934576/auto.zip)
[logs.zip](https://github.com/freeplane/freeplane/files/8934577/logs.zip)

**Comment by dpolivaev** [comment]
Preview 1.10.3_16 
many thanks for reporting
