### ISSUE TITLE
sf.net wiki erased

### ISSUE THREAD

**Issue by coconutpalm** [freeplane/freeplane#47]
The wiki on sf.net appears to have been cracked and totally erased; every page I have bookmarked there gives me a 404.  Fortunately, the wayback machine at archive.org has a copy as-of 3 December, so the content isn't entirely gone.  

(https://web.archive.org/web/20151201183119/http://www.freeplane.org/wiki/index.php/Main_Page)

I suggest this be taken as an opportunity to move the content to GitHub Pages or to GitHub's own wiki.

**Comment by htgoebel** [comment]
Am 04.01.2016 um 15:29 schrieb Dave Orme:
> The wiki on sf.net appears to have been cracked and totally erased;

Seams as Sourceforce is on it's way down.

> I suggest this be taken as an opportunity to move the content to GitHub Pages or to GitHub's own wiki.

If so, I'd recommend *not* to use the Github wiki. IMHO it is not quite
usable. AFAIK it only supports a flat documents-structure and all pages
will be listed flat in the "pages" sidebar

-- 
Regards
Hartmut Goebel

| Hartmut Goebel          | h.goebel@crazy-compilers.com               |
| www.crazy-compilers.com | compilers which you thought are impossible |

**Comment by aadrian** [comment]
> If so, I'd recommend *not* to use the Github wiki. IMHO it is not quite usable. AFAIK it only supports a flat documents-structure and all pages will be listed flat in the "pages" sidebar

GitHub also supports static websites, so the actual content from SF can be converted to a combination of WebSite and WIKI pages.

**Comment by dpolivaev** [comment]
We are working on restoring the old wiki. It just takes us some time.
