### ISSUE TITLE
Fehlende Funktion unter 1.10.3?

### ISSUE THREAD

**Issue by Treysse** [freeplane/freeplane#471]
Bei den bisherigen Versionen konnten die Notizen in einer Tabelle pro Knoten angezeigt und sortiert werden. Diese Funktion finde ich unter 1.10.3 (Linux) nicht mehr.
Wurde diese Funktion weggelassen? Sie war sehr hilfreich.

**Comment by macmarrum** [comment]
I am not sure which functionality you are referring to. Could you please attach a screenshot?

---
Ich bin mir nicht sicher, welche Funktion du meinst. Könntest du bitte einen Screenshot anhängen?

**Comment by dpolivaev** [comment]
Edit->Find->Find and replace… (Ctrl+Shift+F)
I don't think anything changed

**Comment by Treysse** [comment]
Dimitry. Many Thanks. It works perfectly
