### ISSUE TITLE
Use Markdown in Notes panel

### ISSUE THREAD

**Issue by mrjazz** [freeplane/freeplane#475]
**Is your feature request related to a problem? Please describe.**

HTML editor is quite heavy and buggy. Sometimes when I paste content I have to switch in HTML representation and fix markup manually. 

**Describe the solution you'd like**

Makdown is simple and lightweight format, it also could be implemented as Editor & Preview and it seems to me much easier and user-friendly.

**Describe alternatives you've considered**

Alternatively it could be just plain text without any highlighting. It's easier to implement and allows work with markup like Markdown, LaTeX, AsciDoc, etc

**Comment by bepolymathe** [comment]
It’s already implemented

**Comment by macmarrum** [comment]
https://docs.freeplane.org/#/user-documentation/css-for-html-or-markdown

**Comment by mrjazz** [comment]
Thanks @macmarrum ! Can I setup Markdown by default somehow?

**Comment by macmarrum** [comment]
Yes. You can set it on the `Default` style → https://docs.freeplane.org/#/user-documentation/styles?id=style-editing

Change **Content Types->For notes** to `Markdown` and accept (`OK`)

**Comment by mrjazz** [comment]
@macmarrum thanks! Lem me ask last one question, didn't find it in the doc. After apply Markdown for notes in Editor turned off Word Wrap, how to set it back?

**Comment by macmarrum** [comment]
I believe the code editor which is used for editing Markdown, Groovy script/formula and LaTeX is missing the functionality of word wrap.

Please feel free to create a feature request.

**Comment by macmarrum** [comment]
As a workaround, you could use an external editor to edit Note.

Here's a script that works for me. Replace `'gvim', '--nofork',` with your editor of choice.
You can define a hot key to run the script/launch the editor.

```Groovy
def tempFile = File.createTempFile(node.id + '~', '.tmp')
String text = node.note ?: ''
tempFile.setText(text, 'UTF-8')
def editorProcess = ['gvim', '--nofork', tempFile].execute()
editorProcess.waitFor()
node.note = tempFile.getText('UTF-8') ?: null
tempFile.delete()
```

In case you opt for it, let me know if you need further guidance.

**Comment by dpolivaev** [comment]
Preferences…->Plugins->Markdown->Edit Markdown in-line
However, it does not work for the note panel. I think I could apply this option for the note panel too.,

**Comment by dpolivaev** [comment]
Word wrap works for markdown, groovy and latex editors now
Preview 1.10.5_04
