### ISSUE TITLE
how to setup Freeplane for development with Intellij / gradle?

### ISSUE THREAD

**Issue by gotohr** [freeplane/freeplane#48]
I've checked out 1.5.x branch.
What should I do next?

**Comment by dpolivaev** [comment]
To build Freeplane with gradle just execute `gradle build`.

For developing with eclipse you can execute `gradle clean build cleanEclipse eclipse`.
which generates eclipse project files and osdgi manifest files which can be used specially running freeplane as OSGi application under eclipse.

We do not know how to develop freeplane with IntelliJ. Please tell us if you find out how to do it.

**Comment by dpolivaev** [comment]
For eclipse there are also launch configuration files provided.

**Comment by aadrian** [comment]
If the project is a "clean" multi-module Gradle project (without dynamic hacks), than IntelliJ can import it and keep the settings in sync. Just use "Import Project" and in the wizard allow to scan recursively.

**Comment by dpolivaev** [comment]
If you find out how to develop and debug Freeplane using IntelliJ please share it with us. We tried and failed.

**Comment by aadrian** [comment]
> We tried and failed.

What exactly was not working for you? 

To try it, I just imported a fresh project and IntelliJ (Ultimate) seems to recognize so far 13 Gradle modules as IntelliJ modules.
![freeplane_intellij_1](https://cloud.githubusercontent.com/assets/140953/12364137/427dbf60-bbcd-11e5-9da4-2f7a77e2556a.png)

Of course, the IntelliJ specific files are not in ```.gitignore``` yet:
![freeplane_git_1](https://cloud.githubusercontent.com/assets/140953/12364223/b7d46a98-bbcd-11e5-9694-afb1e17e1902.png)

**Comment by dpolivaev** [comment]
Running a debug session with Freeplane as OSGi - Application 
(Freeplane is deployed with knopflerfish, http://www.knopflerfish.org/)

**Comment by dpolivaev** [comment]
It should not matter which OSGi framework you take

**Comment by dpolivaev** [comment]
Developing without debug possibility is not really comfortable, therefore we had to use only eclipse until now.

**Comment by aadrian** [comment]
> Running a debug session with Freeplane as OSGi 

Just curious, what's the advantage of OSGi for a tool like FreePlane?

Shouldn't the entire application just work by just starting ```FreeplaneMain``` ?
![freeplane_intellij_2](https://cloud.githubusercontent.com/assets/140953/12365170/6c65dae6-bbd3-11e5-8059-ea6c4088b874.png)

**Comment by dpolivaev** [comment]
Main advantage is the modularisation in design, development and deployment. Historically Freeplane osgi plugins come from FreeMind plug-ins with the difference that FreeMind used its own specific implementation and Freeplane used standard OSGi framework.

**Comment by BlairArchibald** [comment]
The main issue we had getting Intellij to work was setting up the relevant paths for OSGi. It is possible, but automating the process was non-trivial.

Perhaps it's been improved in recent Intellij versions?

**Comment by aadrian** [comment]
IMHO the OSGi is useless for a tool like Freeplane, and the disadvantages are not worth the effort, effort that could be used for features the users really need.

**Comment by shnaps** [comment]
Any news about Intellij Idea and Freeplane?

**Comment by dpolivaev** [comment]
From now freeplane development is possible using IntelliJ and Netbeans in addition to Eclipse.
Check https://www.freeplane.org/wiki/index.php/IDE_setup for the details.
