### ISSUE TITLE
Role of the freeplane_ant module?

### ISSUE THREAD

**Issue by aadrian** [freeplane/freeplane#49]
What is the role of the ```freeplane_ant``` module since the build system seems to be Gradle now?

thank you.

**Comment by dpolivaev** [comment]
We still call from gradle our ant tasks responsible for properly sorting property files with translations. The sorting is needed to make merging easier.

**Comment by aadrian** [comment]
> We still call from gradle our ant tasks responsible for properly sorting property files with translations. > The sorting is needed to make merging easier.

Wouldn't the ```sort old_file.txt new_file.txt``` command do the trick?

IntelliJ can't sort lines in a file, but it can highlight those that are not correct for all languages:
![freeplane_intellij_3](https://cloud.githubusercontent.com/assets/140953/12367709/a6a680d2-bbe4-11e5-8a7d-87b15202fef6.png)

**Comment by dpolivaev** [comment]
Freeplane_ant is not relevant for IntelliJ, just ignore it

**Comment by dpolivaev** [comment]
Also freeplane_mac
