### ISSUE TITLE
Children of a Submap root don't get positioned like the children of the main Root

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#491]
I started testing the new Jump in feature (#482) and I noticed this behavior. Is it a bug or intended?

So, starting with this map:
![image](https://user-images.githubusercontent.com/77707706/178088189-a934f8ad-3108-4652-afbb-f745d4bbc322.png)

Jump into this node:
![image](https://user-images.githubusercontent.com/77707706/178088209-137d6a4f-91ed-432c-8af0-9d45cc5a6df3.png)

Move node "to the left" to the left of the submap root. I would expect that it would get positioned to the left, like happens when the operation is done on the ROOT node. But, the "to the left" node gets positioned like this:
![image](https://user-images.githubusercontent.com/77707706/178088237-174b4975-c68b-4f20-b6f4-25e2b4ebf917.png)

**Comment by euu2021** [comment]
I forgot to attach the example mind map:
[example jump 1.zip](https://github.com/freeplane/freeplane/files/9075789/example.jump.1.zip)

**Comment by dpolivaev** [comment]
I am sorry I do not understand what exact steps you do, what you expect and what you observe.
On my computer moving the node "to the left" to the left after jumping in leads to implicit jump out as a result and it is a correct behavior.

See attached screen shot
![Selection_116](https://user-images.githubusercontent.com/1558052/178099259-a1865923-d84c-443b-a205-dac971f20d15.png)

**Comment by dpolivaev** [comment]
Because originally node "to the left" was a child node of node "jump in here" after moving it to the left that means in the direction of the root node it becomes a sibling node of node "jump in here". Therefore it would not be visible unless the jump out happens.

**Comment by dpolivaev** [comment]
If you observe anything different please let me know.

**Comment by euu2021** [comment]
I see. I thought you intended to implement the "left side expansion" that was suggested on #455. I will explain it better on the main thread.

**Comment by euu2021** [comment]
Ok, now I see that my description was misleading. When I talk about moving to the left, I mean drag and drop to the left side of the node "jump in here":

https://user-images.githubusercontent.com/77707706/178106348-73a4f826-2d24-43f7-8ede-ffade6f274ba.mp4

**Comment by dpolivaev** [comment]
Oh, now I see what you mean.

**Comment by dpolivaev** [comment]
Preview 1.10.4_07
