### ISSUE TITLE
Freeplane 1.10.3 - Cannot move nodes independently; other nodes are dragged along

### ISSUE THREAD

**Issue by j1k2** [freeplane/freeplane#500]
Freeplane is great for mindmapping but it seems to have a fatal flaw: the nodes cannot be moved independently. Therefore, you cannot arrange your map so that it displays logically or compactly. Somehow, nodes act as if they were somehow attached to other nodes so that when you move one, many move. It's not consistent though; sometimes, it's possible to move a single node but I haven't found the pattern yet. Sometimes, just deleting a node causes many other nodes to move in an undesirable manner.

To Reproduce
1. Create a map of moderate complexity (several dozen nodes) with a few layers.
2. Try moving some of the first-tier (children of the root) node.
3. Observer how other nodes (and their descendants) also move.
4. If not observed, try moving other nodes.

Expected behavior
The expected and desired behavior is that nodes can be moved independently of other nodes. (Of course, when a node is moves, its descendants should move with it, but its siblings should not.)

**Desktop (please complete the following information):**
 - Ubuntu Linux 22.04 LTS
 - Freeplane 1.10.3 (but reports of this undesired behavior go back at least ten years)
 - Java Version 1.8.0_71

**Comment by macmarrum** [comment]
Please have a look at the functionality of free nodes: https://docs.freeplane.org/#/attic/new-wiki-initiative/understanding-nodes?id=free-nodes

**Comment by j1k2** [comment]
Thank you!

I don't think I ever would have found that solution myself !

But I wonder why nodes don't normally have the "Position Node
Independently" attribute set to "on" by default?

**Comment by dpolivaev** [comment]
Because the automatic layout is a key feature. If you don't need it you are probably better helped by another application.
