### ISSUE TITLE
FP 1.10.4 05: with addon Map Drive Inator

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#506]
**Describe the bug**
![image](https://user-images.githubusercontent.com/62674157/180468016-2090886f-3ab0-441a-a52d-d9eb9758a5f2.png)
Using the addon I got this message and the addon wasn't doing anything... Strange because the write permit has been already flagged.
See the attachment:
![image](https://user-images.githubusercontent.com/62674157/180468685-bb1813a8-66e2-43c6-9408-c9f090265e54.png)

What is wrong? How to correct it?
Thank you

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] WINDOWS
 - Version [e.g. 22] 11
 - Java Version:  JAVA OF FP 1.10.4 05

**Comment by EdoFro** [comment]
Hi,
just an additional information for this case:

the "**Map_Drive_Inator**" is **NOT really an addon**. It is a bunch of scripts and a library that the user copies manually into the library folder. When I made this development, I didn't know how to pack add-ons yet.

So, the problem could have been happened with any script or Library and I think it's not an Add-on related problem (jmho)

I will  install that FP version, test it myself and report here.

With FP 1.10.3 and OpenJDK 15 I have had no problem until now. And I use these scripts constantly.

bye,

edo

**Comment by EdoFro** [comment]
I tested it in my notebook and I don't have the problem.
I installed  Freeplane 1.10.4 pre05 portable (**FreeplanePortable-1.10.4-pre05.paf.exe**)  (it uses OpenJDK64 15)  to do the test.

Can you restart Freeplane and see if the error continues?

**Comment by Illegit** [comment]
Hi EdoFro, I confirm it, it happens only with a specific map:
[FreePlane Instructions.txt](https://github.com/freeplane/freeplane/files/9170600/FreePlane.Instructions.txt)
Note: to read it in FP change .txt in .mm 
In this map I0ve highlighted in dark orange the writings of the interested nodes that are generating the problem.
How can I inhibit them for the use of MDI? If it is possible otherwise I know that that type of links related with FP cannot be updated...
Luckily it is a very specific problem not affecting the fundamental behaviour of your scripts. They are nice.

**Comment by dpolivaev** [comment]
Freeplane treats some directories differently, have a look at https://github.com/freeplane/freeplane/blob/f3017355c37d0f8ffd6b96af2c06f6c717603052/freeplane_plugin_script/src/main/java/org/freeplane/plugin/script/ScriptingPolicy.java

**Comment by EdoFro** [comment]
@Illegit,
I think @dpolivaev nailed it: Your map has links to files in the Freeplane's application directory and scripts are restricted in there through that [ScriptingPolicy.java](https://github.com/freeplane/freeplane/blob/f3017355c37d0f8ffd6b96af2c06f6c717603052/freeplane_plugin_script/src/main/java/org/freeplane/plugin/script/ScriptingPolicy.java) code

**Comment by Illegit** [comment]
OK. Thanks
