### ISSUE TITLE
Suggestion: Improve Tablet Support a Bit?

### ISSUE THREAD

**Issue by dsnvwlmnt** [freeplane/freeplane#51]
It wouldn't take much. All i wish i had was:

click to edit node core
click to edit node details

**Comment by dpolivaev** [comment]
Interesting. What Tablet do you use?

**Comment by ldmpub** [comment]
Hi,

Personally I'm still seeking a way to open my Freeplane maps under an Android device (Smartphone Samsung S3 or Tablet).

Yet I'm using DroidPlane : https://play.google.com/store/apps/details?id=ch.benediktkoeppel.code.droidplane 
I also made some test with "m3 - Mobile Mind Mapper" see https://sourceforge.net/p/freeplane/discussion/758437/thread/13ffc88e

The basic feature I need:
- open map
- minimal rendering for content: nodes texts and icons
- navigate map (move + zoom + fold / unfold)
- search in nodes texts
- option: edit node text content.

Regards,

**Comment by dpolivaev** [comment]
A mobile app is out of the scope of this project
