### ISSUE TITLE
Tab inserts 4 spaces when editing node text inline and I think it should insert a new childnode instead

### ISSUE THREAD

**Issue by EdoFro** [freeplane/freeplane#511]
**Describe the bug**
-
I think this is a BUG, but it may be a feature request. I don't know. But anyway:

When using "TAB" as shortcut for "New child node", when editing a node text inline if pressed again it inserts 4 spaces and stays in the node.
This makes that every time I want to create a childnode from the node I am currently editing I have to extra press the Return key before pressing "TAB" key.

I can understand this behavior when editing a node text using the dialog, but when pressing TAB there, it doesn't insert any sapces, or do anything at all.

**To Reproduce**
-
1. Assign "TAB" as shortcut for "New child node"
2. select a node
3. press Tab
4. type some text (without  pressing "Enter")
5. press TAB
6. type some text

It continues in the same node and when pressing TAB it inserts 4 spaces

**Expected behavior**
-
- When editing a node core text inline, the TAB key should not be captured and should execute any command it is assigned to.
  - If it inserts 4 spaces or not is not relevant, because when editing a node it automatically trims the content when losing focus (so it still works for users using other shortcuts for inserting childnodes)
- When editing the node core in dialog, the TAB key should insert 4 spaces and be captured. not executing the binded menu command .

**Mind map files**
-

**Screenshots**
-

**Desktop (please complete the following information):**
-

**Additional context**
-

**Comment by isaacniebeling** [comment]
This gets me _every_ time I'm working in Freeplane. Is there any way to change that ourselves (without any dev time? like, is there already a preference or a way to set a hotkey?)

**Comment by dpolivaev** [comment]
Finally fixed

**Comment by EdoFro** [comment]
Thanks!
