### ISSUE TITLE
Default paper size and margins

### ISSUE THREAD

**Issue by vascotenner** [freeplane/freeplane#52]
The standard paper size is some strange non-standard format. When I change it to a4, the margins are huge (2inch!). Can freeplane respect the papersize set in the envirmentent (for example `LC_PAPER="en_GB.UTF_8"` for a4 paper)? And set the margins to something more sensible (2.5cm for example).

**Comment by dpolivaev** [comment]
Please reopen this issue if needed

**Comment by vascotenner** [comment]
Please reopen.

**Comment by dpolivaev** [comment]
Current implementation has the intention of getting the values from the printer unless user executes page setup. It looks like a sensible standard behavior. Isn't it?
