### ISSUE TITLE
Selected node color is not alterable.

### ISSUE THREAD

**Issue by sheepdoggie** [freeplane/freeplane#528]
**Describe the bug**
The color of the selected node cannot be changed.

**Expected behavior**
Changing the preferences "Standard selected node color (fallback)" should allow the user to change the color of the selected node. In this map it does not.

**Mind map files**
[DIE ELVERSKÖNIGIN DER ELBENKÖNIGIN 1 - DAS MAGISCHE SCHILD - 12.mm.zip](https://github.com/freeplane/freeplane/files/9252352/DIE.ELVERSKONIGIN.DER.ELBENKONIGIN.1.-.DAS.MAGISCHE.SCHILD.-.12.mm.zip)

**Desktop (please complete the following information):**
 - OS: 5.15.0-43-generic #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - Version 1.10.3
 - Java Version: 11.0.14

**Additional context**

**Comment by dpolivaev** [comment]
If a map defines a style for selected nodes, the option from the preferences is ignored.
