### ISSUE TITLE
Copy --> paste image from clipboard to Note (panel) doesnt work

### ISSUE THREAD

**Issue by blurymind** [freeplane/freeplane#53]
I noticed that if you highlight and copy an image from a web page and paste it to the note panel - it some times works - probably because it copies the html code.

If you however right click on the actual image and copy it to clipboard, pasting it to the note will not work at all. 

Please implement the ability to copy images from clipboard (not just their html code) and paste them into node notes. Pasting an image from clipboard into the note panel should also create a local copy of that image in the folder. Freeplane can already do the import - but it is not doing it in a very practical way and is limited only to actual nodes - not their notes.

Also add ability to resize images that are embedded into nodes, or node notes.

**Comment by fnatter** [comment]
hi blurymind,
clipboard handling in java is really painful. Many things don't work (e.g. html paste from
firefox to FP on linux). Maybe a workaround is to paste to libreoffice writer first and then to Freeplane?
Best Regards,
Felix

**Comment by dpolivaev** [comment]
Please reopen this issue if needed
