### ISSUE TITLE
Display chaos and cannot be used normally on windows 11

### ISSUE THREAD

**Issue by iqoug** [freeplane/freeplane#536]
**Describe the bug**
Display chaos and cannot be used normally on windows 11 when use chinese input method
**To Reproduce**
1. open freeplane
2. Type chinese in some node
3. Display chaos and cannot be used normally

**Expected behavior**
Display  normally

**Mind map files**
**Log files**
[logs.zip](https://github.com/freeplane/freeplane/files/9259585/logs.zip)

**Desktop (please complete the following information):**
 - OS: windows
 - Version windows11 21H2
 - Java default

**Screenshots**

![QQ截图20220804192421](https://user-images.githubusercontent.com/26008116/182836380-14f5f361-9149-4169-9fc0-e65d70738a48.png)
![QQ截图20220804192539](https://user-images.githubusercontent.com/26008116/182836394-933c0ae1-c680-43bc-9053-ba1fd75d1313.png)

[](url)

**Comment by iqoug** [comment]
freeplane version 1.10.3

**Comment by dpolivaev** [comment]
It does not look like a Freeplane-specific issue. Rather something with Java, Chinese Input, and your graphic driver.
I am closing this issue because I do not know how I could investigate it.
Probably you need to find some Chinese developer to dive into the problem.
