### ISSUE TITLE
Node Details Dialog font too small

### ISSUE THREAD

**Issue by SevKos** [freeplane/freeplane#542]
I'm always frustrated when I try to edit node details in dialog (ctrl+F3). The font is too small to read. On my screen (40 inch), I am unable to read those tiny letters (setting font size to 24 makes it comfortable to read but I end up with massive node details font and small node core text). 

An ability to use CTRL+mouse wheel to zoom in and out inside the node details dialog might be an acceptable solution.

An option to set zoom level for node details dialog in preferences could work too.

Thanks for consideration.

![Screenshot 2022-08-07 01 17 29](https://user-images.githubusercontent.com/82227362/183269857-672edd05-5985-4188-a658-e0990cc09590.png)
![Screenshot 2022-08-07 01 17 27](https://user-images.githubusercontent.com/82227362/183269859-ad1451d7-3773-4216-99f8-26dedf1fb2aa.png)

**Comment by dpolivaev** [comment]
Check the value of Preferences…->Appearance->Look and feel->Monitor size (inches) and try values 30, 35 and 40 restarting Freeplane after each change
Try different look and feels and write if they have any influence
Preferences…->Appearance->Look and feel->Look and Feel
Attach your auto.properties and some example mind map containing node details.

**Comment by SevKos** [comment]
Thanks for suggestions. It took some tinkering with settings but I finally managed to get decent proportions balance for appearance. Strangely, I had to set my Monitor Size to 15 and lower Menu Item Font Size to 6, and Toolbar Icon Height to 10pt. Glad there is option to set Format Panel Size to 'Big', so no compromises had to be made.

I appreciate quick response.

**Comment by dpolivaev** [comment]
Actually, setting the font size to 6 does not feel right.
I think you could try different look-and-feels and share here your auto.properties and some minimal map containing node details

**Comment by SevKos** [comment]
I set the font size to 6 because only setting monitor size to 15 inches made text within node details window big enough for me (could have set monitor size to 20, and it would have been acceptable too). The strange thing is that setting monitor size to my true size, makes text too small to read.

Thanks for looking into it.

Here's how my current setup looks:

![Screenshot 2022-08-12 17 31 33](https://user-images.githubusercontent.com/82227362/184405737-763e70cf-131a-478d-a3f3-887a98121879.png)

Here are contents of auto.properties with current settings I'm happy with:

#Freeplane 1.10.3
#Sun Aug 07 23:48:28 BST 2022
filter_toolbar_visible=false
markdown_editor_font_size=20
leftToolbarVisible.fullscreen=false
split_pane_last_position=-1
last_update_verson=
antialiasAll=true
outline_hgap=10 pt
standarddrawrectangleforselection=true
statusVisible.fullscreen=false
filter_toolbar_visible.fullscreen=false
hugeFontsFixed=true
EditStylesAction.dialog=<EditStylesAction.dialog x\="192" y\="108" width\="1536" height\="864"/>
OptionPanel_Window_Properties=<option_panel_window_configuration_storage x\="146" y\="106" width\="1318" height\="864" panel\="OptionPanel.Appearance"/>
presentation.combineAll=false
last_bug_report_info=at 2021-11-24 22\:13\:50 CMT,  hash 1d7ce9b4ab0ba1625d123367a88bf36b
menubarVisible=true
last_java_compiler_version=15.0.7
editNodeDialog.height=841
monitor_size_inches=15.0
appwindow_x=-8
appwindow_y=-8
leftToolbarVisible.size=393
recently_used_icons=
plugins.script.ScriptEditorPanel/window_positions=<manage_style_editor_window_configuration_storage x\="192" y\="108" width\="1536" height\="864" left_ratio\="100" top_ratio\="240"/>
outline_vgap=3 pt
presentation.zoom=false
editNodeDialog.width=1566
fullscreen_enabled=true
styleEditorPanelSize=BIG
lookandfeel=com.formdev.flatlaf.FlatDarculaLaf
menuItemFontSize=6
org.freeplane.plugin.bugreport.1d7ce9b4ab0ba1625d123367a88bf36b=1
groovy_editor_font_size=24
connector_color=\#000000ff
dialog_statusVisible=true
dialog_styleScrollPaneVisible=true
styleScrollPaneVisible.size=669
use_split_pane=false
menubarVisible.fullscreen=false
leftToolbarVisible=false
skip_template_selection=false
appwindow_height=1096
openedNow_1.3.04=
styleScrollPaneVisible=true
toolbar_icon_height=10 pt
split_pane_position=0
lastLocations=ID_556576270;;ID_1090958577;;ID_526295664;;ID_1090958577;;ID_729753755;;ID_1090958577;;ID_1090958577;;ID_1090958577;;ID_804557611;;ID_1090958577;;ID_1622032017;;ID_1090958577;;ID_1090958577;;ID_1887018588;;ID_1448665925;;ID_1090958577;;ID_1090958577;;ID_721248134;;ID_1067150918;;ID_1090958577;;ID_1870639924;;ID_1146052082;;ID_1922160426;;ID_1173357699;;ID_1870602202;;ID_1090958577;;ID_1090958577
toolbarVisible=false
standardselectednodecolor=\#4e85f8ff
appwindow_state=6
resources_use_default_font_for_notes_too=false
user_defined_screen_resolution=147
dialog_toolbarVisible=true
statusVisible=true
center_selected_node=false
lastOpened_1.0.20=
file_chooser_window_configuration=<file_chooser_window_configuration x\="182" y\="182" width\="516" height\="365"/>
standardselectednoderectanglecolor=\#4e85f8ff
latex_editor_font_size=30
antialiasEdges=true
script_compilation_disabled_extensions=
appwindow_width=1936
save_last_visited_node=false
revision_color=\#ffff00ff
last_update_check_time=1659830494633
standardcloudcolor=\#f0f0f0ff

**Comment by dpolivaev** [comment]
Could you please check Preview 1.10.4_07 ?
I fixed one bug which might help in your case, but I still do not understand completely what happens in your case.

**Comment by SevKos** [comment]
I tried to check out the preview version but it wouldn't run (requires Java Runtime Environment 11 - 17). I installed JDK 17 but the message still pops up.

**Comment by dpolivaev** [comment]
You can either use installer containing Java or follow https://docs.freeplane.org/#/getting-started/Command-line_options_and_configuration?id=select-java-installation-used-to-run-freeplane
