### ISSUE TITLE
Brainstorming mode 

### ISSUE THREAD

**Issue by aymangithub** [freeplane/freeplane#555]
It would be very good to add brainstorming mode as in the Mindjet . Where the user can write what is in his mind randomly and without a structure and then organize it and complete his work on it

**Comment by HaaiHenkie** [comment]
Hi @aymangithub 

I think this is already the standard mode in Freeplane:

- Create new mind map
- Press Tab, enter first idea and press Enter twice
- Enter next idea and press Enter twice
- Repeat previous step until you have finished brainstorming

You now have an unstructured list and can start structuring it.

**Comment by aymangithub** [comment]
Ok, thanks a lot

**Comment by dpolivaev** [comment]
You can also add a node visually not connected to the rest using double-click and holding  control button.
Later you can attach it to any node using drag-and-drop
