### ISSUE TITLE
Closing the node background color picker window resets the nodes color

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#557]
Closing the node background color picker window, with the X button, is equal to `reset`. I guess it is supposed to be `cancel`, right?

**Comment by dpolivaev** [comment]
I can not see it.

**Comment by euu2021** [comment]
[bug reset.zip](https://github.com/freeplane/freeplane/files/9328757/bug.reset.zip)

Closing the window should leave the color as it is (red):

![javaw_oGjA2zar8z](https://user-images.githubusercontent.com/77707706/184409887-31c2a0e3-1f99-4170-a8c1-ccbd5d8fa77d.gif)

**Comment by dpolivaev** [comment]
Preview 1.10.4_07
