### ISSUE TITLE
Alt+Shift+Tab on for summary nodes on Windows. Not working

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#558]
`Insert->New node->New summary node (selected nodes)` is, now, the hotkey `Alt+Shift+Tab`. But, on Windows (I'm on Windows 11), it doesn't work, because the "alt tab window switcher" pops up.

FP 1.10.4_pre5

**Comment by dpolivaev** [comment]
I changed the shortcuts in Preview 1.10.4_07
