### ISSUE TITLE
Jump in/out: Nodes misaligned when changing sides, after jump in

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#561]
In this situation:

![javaw_eCZh5xoaMS](https://user-images.githubusercontent.com/77707706/184517583-94ec8fd5-3558-41ee-85ea-f56c6d0352f4.gif)

Hovering makes them go back into place.

[bug left 1.zip](https://github.com/freeplane/freeplane/files/9332454/bug.left.1.zip)

Freeplane-Setup-with-Java-1.10.4-pre07

**Comment by dpolivaev** [comment]
Seems to be fixed but I fixed another bug testing it
