### ISSUE TITLE
Jump in/out: error when jumping into two selected nodes

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#563]
Steps:

1. Select two nodes
2. Use Jump in

The status line shows an error (but, the jump in proceeds successfully to one of the nodes). Here is the log and map:

[bug left 2.zip](https://github.com/freeplane/freeplane/files/9336741/bug.left.2.zip)

**Comment by dpolivaev** [comment]
I can not reproduce it here. Are you sure the problem is not caused by your scripts?

**Comment by euu2021** [comment]
I noticed that the error only happens if I Jump In using a hotkey (I set Tab as the hotkey).

I will create a vanilla version of Freeplane here, so I can isolate the scripts in the tests.

**Comment by dpolivaev** [comment]
Assigning TAB as a hotkey does not change anything here.

**Comment by dpolivaev** [comment]
By the way, I am moving the jump in and out actions into menu navigate and they are getting hot keys "shift + escape" and "control + escape"

**Comment by euu2021** [comment]
I tested with vanilla settings: problem doesn't happen

I copied only my auto.properties to this vanilla profile (so, without scripts and add-ons): problem happens

Here are is auto.properties: 
[auto (2).zip](https://github.com/freeplane/freeplane/files/9337265/auto.2.zip)

**Comment by dpolivaev** [comment]
I do not see the problem using your map and your auto.properties.
Would you like to record a video?

**Comment by euu2021** [comment]
I simply open the map (the same for new maps of standard template), select both nodes and press Tab:
![javaw_SpKdGWZGRL](https://user-images.githubusercontent.com/77707706/184664009-059e024d-9c9a-458c-973b-a21b639d0fad.gif)


What else would be helpful showing?

Notice that I didn't use a fresh install of FP. I simply use [this](https://www.youtube.com/watch?v=OZR-5Q5fAJ4) technique to have a fresh profile. Before replacing the auto.properties: no problem. After: problem.

**Comment by dpolivaev** [comment]
No appearance of the bug here.
I used your configuration just as you have shown and tried to do the same steps.
You can try to upload the log file from your new configuration location.
Up to now, I have no idea what we do differently.
I have even tried it on Windows 10 (I have no Windows 11 PC)

**Comment by euu2021** [comment]
> You can try to upload the log file from your new configuration location.

This is the log:
[log.zip](https://github.com/freeplane/freeplane/files/9338946/log.zip)

**Comment by dpolivaev** [comment]
Please try version 1.10.4_09. I changed the logging so that there is a chance of a better understanding of what happens from the new log files.

**Comment by euu2021** [comment]
I installed 1.10.4_09, and the problem stopped happening 😯
