### ISSUE TITLE
Export to HTML <span style="font-family:..."> should escape the quotes

### ISSUE THREAD

**Issue by cousteaulecommandant** [freeplane/freeplane#564]
**Describe the bug**
When exporting to HTML (not the old "Html document", but the new "HTML" that has javascript for folding elements), `<span>` tags with a `style=` attribute don't handle quotes properly (they should be escaped as `&quot`, but instead they are left as `"`).

  * Expected:
    ```html
    <span style="font-family: &quot;Dialog&quot; ;">...</span>
    ```
  * Actually obtained:
    ```html
    <span style="font-family: "Dialog" ;">...</span>
    ```

**To Reproduce**
1. Create a new map using template `standard-1.6-noEdgeColor.mm`.
2. Add a node containing the text "TEST" (for example).
3. Right-click node > "Apply style" > "Topic".
4. File > Export map... > Files of type: "HTML" (not "Html document"; that's the old format).
5. Inspect the source code of the generated HTML file (specifically, of the "TEST" node).

**Expected behavior**
```html
<span style="color: #18898b; font-family: &quot;Liberation Sans&quot;, sans-serif; font-weight: bold; ">TEST</span>
```
(or without any quotes at all -- this particular font name doesn't need them anyway; they're just systematically added)

**Current behavior**
```html
<span style="color: #18898b; font-family: "Liberation Sans", sans-serif; font-weight: bold; ">TEST</span>
```

**Mind map files**
[HTML_quotes_bug.zip](https://github.com/freeplane/freeplane/files/9337349/HTML_quotes_bug.zip)

**Desktop:**
 - OS: cross-platform (tested it on Windows 10 and Ubuntu 18.04)
 - Version: 1.10.2, 1.10.4-pre08
 - Java Version:
    - Windows: "About Java" = Version 8 Update 131 (Oracle)
    - Ubuntu: `java --version` = openjdk 11.0.16 2022-07-19

**Comment:**
Most browsers seem fine with this formatting anyway, but I guess that's just because they're built to handle such errors.

**Comment by dpolivaev** [comment]
Preview 1.10.4_12
