### ISSUE TITLE
Export to HTML doesn't specify the character encoding

### ISSUE THREAD

**Issue by cousteaulecommandant** [freeplane/freeplane#569]
**Describe the bug**
When exporting to HTML (not the old "Html document", but the new "HTML" that has javascript for folding elements), the generated UTF-8 HTML document doesn't provide any information about its encoding.
This can cause strange and inconsistent behavior if the document contains non-ASCII characters.  Specifically, I noticed that both Chrome and Edge (in Windows) assume UTF-8 if the document is stored in C: BUT for some reason it assumes Latin-1 or Windows-1252 if it's stored in a shared network drive.  (This was particularly problematic since the file looked OK for me but when I shared it on a network drive with a coworker it looked strange for them.)

The old "Html document" format doesn't have this issue, since it:
 - explicitly specifies the encoding through a `<meta>` tag, and
 - uses `&xxx;` for non-ASCII characters anyway.

**To Reproduce**
1. Create a new map containing non-ASCII characters.
2. File > Export map... > Files of type: "HTML" (not "Html document"; that's the old format which works fine).
3. Inspect the source code of the generated HTML file -- observe the presence of non-ASCII characters and the lack of encoding metadata.
4. Open the generated file with certain browsers (Google Chrome or MS Edge in my case), with the file in a local drive -- the characters display correctly.
5. Copy the file to a network drive (in Windows) and open it from the network drive -- the characters display wrong.

**Expected behavior**
The generated document is either encoding-agnostic (pure ASCII with `&xxx;` entities for non-ASCII characters) or explicitly states its encoding.

**Current behavior**
The generated document
 - is encoded in UTF-8,
 - has non-ASCII characters encoded directly in UTF-8,
 - does not contain any `<meta>` tag stating its encoding,
 - does not contain a Unicode BOM,
 - is saved explicitly as HTML 4.01.

**Possible solutions**
 - Encode non-ASCII characters as XML entities (`&xxx;`).
 - [Explicitly state the encoding](https://www.w3.org/International/questions/qa-html-encoding-declarations) using a `<meta http-equiv="Content-Type" content="text/html; charset=utf-8">` tag.
 - Add a UTF-8 BOM ([may be discouraged](https://www.w3.org/International/questions/qa-byte-order-mark.en.html), or [maybe not](https://www.w3.org/International/questions/qa-html-encoding-declarations#bom)).
 - [Some sources](https://www.geeksforgeeks.org/how-to-set-character-encoding-for-document-in-html5/) claim that HTML 5 defaults to UTF-8 if not specified (so upgrading the generated documents to HTML 5 could be an option), but [that seems to be a lie](https://www.w3.org/International/articles/spec-summaries/encoding#html5-summary).

**Mind map files**
[Test_unicode_html.zip](https://github.com/freeplane/freeplane/files/9366672/Test_unicode_html.zip)

**Desktop:**
 - OS: cross-platform (tested it on Windows 10 and Ubuntu 18.04)
 - Version: 1.10.2, 1.10.4-pre08
 - Java Version:
    - Windows: "About Java" = Version 8 Update 131 (Oracle)
    - Ubuntu: `java --version` = openjdk 11.0.16 2022-07-19

(I haven't been able to reproduce the incorrect rendering issue in Linux, which is related to the browser anyway, but I can confirm that the _generation_ behaves identically in Linux and Windows.)

**Comment by dpolivaev** [comment]
Preview 1.10.4_11
