### ISSUE TITLE
Paste image at current node

### ISSUE THREAD

**Issue by heliocarbex** [freeplane/freeplane#57]
Hello,

When you select a node and paste a image, Freeplane creates a "new child" and it puts the image there. I think that would be better if the image could be pasted at the current node and not inside the "new child".

**Comment by heliocarbex** [comment]
I saw that you have published the new version at Source Forge. Do you prefer discuss the evolution of this project there or here at Github?

Congratulations for your efforts!

**Comment by fnatter** [comment]
hello heliocarbex,

our primary bug reporting system is here:
https://sourceforge.net/p/freeplane/bugs/
--> Can you close this issue and open a bug there, so that your voice is heard?

Cheers and Best Regards,
Felix
