### ISSUE TITLE
When updating Freeplane major version, existing maps stay following templates from old user directory

### ISSUE THREAD

**Issue by EdoFro** [freeplane/freeplane#571]
**Describe the bug**
When updating Freeplane major version (from v1.9.x to v1.10.y) the user directory is copied and Freeplane now interacts only with the new one (that's ok).
But the existing maps that follow a template stay linked to the old folder, although a new active template folder was created.

**Screenshots**
![image](https://user-images.githubusercontent.com/35700575/185456167-0413edd1-478b-452b-97fd-9f7155aefa4d.png)

**To Reproduce**
1. Open Freeplane v1.9
2. create a new map that follows a user template
3. save it
4. Open Freeplane v1.10
5. Open the map
6. Go to `Format->Manage Styles->Manage followed and associated mind maps`
7. See error

**Expected behavior**
When a mindmap is opened and its followed mindmap is in a previous Freeplane user directory and the current user directory has a version of the same map (very likely because it should have been automatically copied), then Freeplane should ask the user if he wants to update the followed mindmap to the new one and update it.

**Comment by EdoFro** [comment]
new info:
Now I changed the followed mindmap and it now uses relative path, not absolute.
![image](https://user-images.githubusercontent.com/35700575/185459944-5c95fd31-0f24-497b-873d-5b70e29facac.png)

Maybe my map was from a previous version, but now with new maps there shouldn't be any problem, or?

If so, please close the issue. thanks

**Comment by dpolivaev** [comment]
I think it is fixed for the latest maps.
