### ISSUE TITLE
Dropping a node to the left side of the root: node goes to the right

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#581]
Expected: node goes to the left. 
What actually happens:
![javaw_lnmv1r4bkG](https://user-images.githubusercontent.com/77707706/185815569-caa755f0-444b-4066-8bb8-c38e588f1c4c.gif)

1.10.4-pre10

**Comment by dpolivaev** [comment]
preview 1.10.4_11

**Comment by euu2021** [comment]
I noticed that the bug also happens when the moved node is the level 1 child of the Root. Also, if level 1 child of a subroot. Still happening on 1.10.4_11:
![javaw_kVG7UjvWjk](https://user-images.githubusercontent.com/77707706/186288846-6868408e-17f2-4ca4-9395-867a4269cac4.gif)
