### ISSUE TITLE
jump-in: LEFT and RIGHT ignored for non-root children when groupping them into a summary node

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#583]
I can see that preview 1.10.4_11 disallows to create a new summary node that groups a LEFT and a RIGHT node, but only if the nodes are children of `map.root`. Otherwise the action is performed. 
E.g. `A left-2` and `A right-1` (in [test-side-2.zip](https://github.com/freeplane/freeplane/files/9389657/test-side-2.zip)) can still be grouped into a summary node.

It looks to me that to make it work, `side` needs to be considered, making sure it's LEFT or RIGHT for all the nodes in the summary-node group to be created (not only the first and last nodes). If `side == DEFAULT`, `isLeft(rootNode)` should be called for the common parent (not for map.root).

**Comment by dpolivaev** [comment]
I do not understand why it should be restricted.
The summary node is always added on the side of the last summarized node.
But I have fixed another issue ensuring that the first group node and the summary node are always created on the same side.

**Comment by dpolivaev** [comment]
(@macmarrum  Feel free and welcome to comment on this and other closed issues. I have closed them just to easier see other issues)

**Comment by macmarrum** [comment]
It's inconsistent behavior of Freeplane to try and shield User from creating a Summary Node consisting of LEFT and RIGHT nodes when they are children of `view.root` but allowing the action when the same nodes aren't children of `view.root` (e.g. after jumping out).

But I can see that Summary Nodes have more issues in general, this one being the least important/impactful, so I am fine with the current implementation, especially after the recent fix – tested on git version

```git
3c8c56d8 Dimitry Polivaev <dpolivaev@gmx.de> on 26/08/2022 at 17:52
```
