### ISSUE TITLE
jump-in: moving a summary-groupped node to the other side fails to remove it from group

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#584]
I can see in preview 1.10.4_11 that given two children of `map.root` are part of a summary-node group, when one of them is moved to the other side, the node is taken out of the summary-node group. But the same action on a jump-in view doesn't take the node out of the group. It should.

In [test-side-2.zip](https://github.com/freeplane/freeplane/files/9389657/test-side-2.zip)
1. Jump in `debates`
2. Move `debate-B` right
3. Insert a new summary node for `debate-A` and `debate-B`
4. Move `debate-B` left
5. Jump out

**Comment by EdoFro** [comment]
I'm not so convinced that this is a bug, because a node may move to the other side just by activating the jumped-in view on its parent.

Look at the example here:
https://github.com/freeplane/freeplane/discussions/560#discussioncomment-3460653

For me is very important that a mindmap information doesn't change if the only thing I do is jumping in and out.

> if you jump in and change some nodes sides, then you jump out and add a summary node to them, if you jump in again the summary node doesn't show correctly, but it doesn't change what you defined when in jumped-out mode.

![jump-in-out-summary](https://user-images.githubusercontent.com/35700575/186276467-50d8172f-eb30-4f70-849b-51940d93c22a.gif)

**Comment by macmarrum** [comment]
> I'm not so convinced that this is a bug, because a node may move to the other side just by activating the jumped-in view on its parent.

@EdoFro My initial thought, as stated in the issue description, was to keep the behavior consistent for map.root and jump-in.root, i.e. if it's disallowed there, it should be disallowed here too. Later I reconsidered the topic and proposed a different approach – see 

* https://github.com/freeplane/freeplane/issues/580

In line with the proposal, Freeplane could allow different-side nodes in a summary node for jump-in.root, but keep insisting on same-side nodes in case of map.root.

**Comment by dpolivaev** [comment]
I do not see any inconsistent behavior.
The vertical order of the nodes is not changed when you move node "debate-B" to the left.
Therefore it does not go out of the summary scope.
Only if you move it down after the jump-out, it does.

**Comment by macmarrum** [comment]
What I had in mind was in fact the functionality in v1.10.3, but in 1.10.4pre11 is gone.
Since it's gone, there is no inconsistency any more.
