### ISSUE TITLE
How can I port/develop an app for Google Android, Web and Microsoft Appsource and Marketplace App Stores

### ISSUE THREAD

**Issue by MsD201x** [freeplane/freeplane#592]
### Discussed in https://github.com/freeplane/freeplane/discussions/591

<div type='discussions-op-text'>

<sup>Originally posted by **MsD201x** August 25, 2022</sup>
**My Problem**:  Frustrated in my learning Freeplane. Why? On desktop, I am ok. But, if on the web at Google, Microsoft apps marketplace, Freeplane isn't there. Freeplane is not an optional app for me and my Freeplane learning development.
**My Solution**:  I want to develop an app for Google android, web and Microsoft appsource and marketplace app stores.</div>

**Comment by MsD201x** [comment]
Ayoa, iMindMap, iThoughts, MindGenius, MindManager, MindMaple, MindMapper, MindMaster, MindMeister, MindNode, XMind
These are the current free but limited mindmap tools available but are not Freeplane.

**Comment by ldmpub** [comment]
You're welcomed 👌 if you want to develop a mobile (phone) application version of freeplane.
The task is hard and has been discussed in one of our Freeplane community online conference, read the minute there:  https://github.com/freeplane/freeplane/discussions/339#discussioncomment-2842778
