### ISSUE TITLE
summary node: FirstGroupNode or SummaryNode gets orphaned, causing misbehavior

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#595]
FirstGroupNode or SummaryNode gets orphaned in 2 scenarios. Please see [test-side-summaryNode-1.10.4-git2022-08-26.zip](https://github.com/freeplane/freeplane/files/9438247/test-side-summaryNode-1.10.4-git2022-08-26.zip)

**Comment by dpolivaev** [comment]
It is a difficult case requiring significant changes because of side changes by jumping in.
I am going to work on it.

**Comment by dpolivaev** [comment]
Actually here we have got two related but different problems.
The first problem is that sometimes the FirstGroup helper node is missing. I can fix it.
The second problem is that if node change sides after jump-in and jump-out, summary nodes can start to overlap.

It could be prohibited in case described in Scenario 1  of your map, but I do not know how I could avoid it in the case I attach below.

Because Freeplane layout can not handle overlapping summary nodes and can not maintain consistency after a nodes change sides (after jumping in or out, copying or moving), some misbehaviour seems to be unavoidable.

Please let me know how what you think.

<img width="145" alt="jumpin" src="https://user-images.githubusercontent.com/1558052/188176940-80278042-05e0-4251-96ed-ba7787f6b3e9.png">
<img width="226" alt="jumpout" src="https://user-images.githubusercontent.com/1558052/188176969-e04897d0-cdc1-4af8-9cd6-d0a3028b2c18.png">
<img width="369" alt="analysis" src="https://user-images.githubusercontent.com/1558052/188176989-31c345d7-de96-4bcf-bb83-073dbb39191c.png">

[summary-node-on-sides.mm.zip](https://github.com/freeplane/freeplane/files/9478922/summary-node-on-sides.mm.zip)

**Comment by macmarrum** [comment]
The functionality of summary nodes in v1.10.3 and earlier already had this kind of issue. It was possible to move nodes so that their summary nodes overlapped. So it wouldn't be that bad if it was still possible.
[test-side-summaryNode-1.10.3.zip](https://github.com/freeplane/freeplane/files/9479211/test-side-summaryNode-1.10.3.zip)


![2022-09-02_17,26,09](https://user-images.githubusercontent.com/7197131/188182808-8b745597-09c7-4065-81c3-644710604df6.png)

That being said, I think that the validation logic could be extended so that a summary node is allowed only if nodes' positions are one after another, not only visually, but also considering child's position.
Alternatively, when creating a summary node on non-contiguous nodes, a warning could be displayed, but allowing the operation:
"_There are other nodes positioned between selected nodes, but displayed on the other side. The resulting summary node might end up different than you expect. Please consider moving all nodes to the same side before creating a summary node._"

**Comment by dpolivaev** [comment]
I could add this check and output a warning during the creation of the summary nodes. 
Would you like it?

It would still remain possible to create such overlapping nodes by moving nodes after the summary nodes are created.

**Comment by dpolivaev** [comment]
And should the creation of the summary nodes after the warning be possible?

**Comment by macmarrum** [comment]
> I could add this check and output a warning during the creation of the summary nodes. Would you like it?

:+1: I think it can help people to avoid unexpected behavior.

> It would still remain possible to create such overlapping nodes by moving nodes after the summary nodes are created.

That's fine, in my opinion, because when moving, it's visually clear that something funny is going on. User can `Ctrl+Z` to undo the action.

> And should the creation of the summary nodes after the warning be possible?

Yes. User can `Ctrl+Z` to undo the action, move the nodes to the same side and retry.

**Comment by dpolivaev** [comment]
Preview 1.10.4_12
The fix does not affect old maps if they got this problem

**Comment by macmarrum** [comment]
Thanks :+1: 

There is still an issue with multi-level summary nodes, i.e. FirstGroupNode is not deleted.

A multi-level summary node can be created by moving nodes around.

[test-side-summaryNode-1.10.4pre12.mm.zip](https://github.com/freeplane/freeplane/files/9533574/test-side-summaryNode-1.10.4pre12.mm.zip)

![test-side-summaryNode-1 10 4pre12 ~2022-09-09_10,08,18](https://user-images.githubusercontent.com/7197131/189303651-b0f49776-6d74-4e1d-a00a-7da0145cfa50.png)

**Comment by dpolivaev** [comment]
Could you please describe how exactly you created the first map with two FirstGroupNode - nodes one after another?

I have attached your mind map containing fixed analysis script

[test-side-summaryNode-09.09.mm.zip](https://github.com/freeplane/freeplane/files/9536865/test-side-summaryNode-09.09.mm.zip)

**Comment by macmarrum** [comment]
[test-side-summaryNode-09.09.mm.zip](https://github.com/freeplane/freeplane/files/9537728/test-side-summaryNode-09.09.mm.zip)

![test-side-summaryNode-09 09~2022-09-09_19,49,44](https://user-images.githubusercontent.com/7197131/189413531-592bb582-45cd-4d7d-aea7-ac26573157dd.png)

**Comment by dpolivaev** [comment]
I have spent many weekends trying to find a solution to it and I do not see any good solution.
I can either give up and stop making Freeplane completely or give up and ignore this problem.
Which way would you prefer?

**Comment by dpolivaev** [comment]
This situation can happen in too many cases e.g. if nodes are copied,  if they change sides, and I do not understand how it can be repaired.

**Comment by macmarrum** [comment]
Cool :sunglasses: 
I think it's great you've had a go at it :+1:
An orphan FirstGroupNode won't happen often, an probably won't cause too much trouble anyway.
If it does, it can be cleaned up with a script.

**Comment by dpolivaev** [comment]
Preview 1.10.5_04

**Comment by macmarrum** [comment]
In 1.10.5_04, SummaryNode gets orphaned when moving nodes around.

![2022-09-26_20,53,46](https://user-images.githubusercontent.com/7197131/192357524-8d8e0d43-e7c6-41b0-9307-ceb01caed7e5.png)

[test-side-summaryNode-v1.10.5pre04.mm.zip](https://github.com/freeplane/freeplane/files/9648909/test-side-summaryNode-v1.10.5pre04.mm.zip)

**Comment by dpolivaev** [comment]
Preview 1.10.5_05
