### ISSUE TITLE
Since 1.10.4pre10, script title in menu is descriptive, tooltip is double-descriptive

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#596]
Since 1.10.4pre10, a script title in menu is descriptive, its tooltip is double-descriptive.
The descriptive title causes the script menu entries to be less readable.
And the additional information is superfluous; it's clear that a script menu entry is for executing the script.
It might make sense to clearly state the scope of the script (on one selected node; on all selected nodes; on selected nodes, recursively). This information could be indicated by an icon, so that the menu item is kept as short as possible.

#### v1.10.4pre10
![Script_title_v1 10 4pre10](https://user-images.githubusercontent.com/7197131/187061859-3dfa8761-8de8-4f90-bc3a-c16c82f79fad.png)

#### v1.10.3
![Script_title_v1 10 3](https://user-images.githubusercontent.com/7197131/187061885-4d7f31c8-d9b4-440a-8429-e29551e70b93.png)

**Comment by dpolivaev** [comment]
Preview 1.10.4_12
