### ISSUE TITLE
FP 1.10.4 11: missing filters

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#600]
**Describe the bug**
Filter composer is loading my filters without problem on one pc, but on another pc I'm not able to read it, the filters are empty:

After overwriting the empty auto filter, still the filter composer shows the filter, but they are not present in the menu.

Every time I apply and approve with (ok) (and all of the other combinations of buttons in the filter composer) the filters visible in the filter composer it doesn't load them in FP (see the images)

I even copied the same autofilter file working in the other pc: no result the filters were still empty (even after reloading FP)
I reinstalled FP, but no result, always the same message "no named filters"
Any suggestion? I do not think it is a bug... but.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] w11
 - Version [e.g. 22]11
 - Java Version 15

**Additional context**
[log.zip](https://github.com/freeplane/freeplane/files/9439727/log.zip)
[auto.zip](https://github.co
<img width="1174" alt="Annotation 2022-08-28 153258" src="https://user-images.githubusercontent.com/62674157/187076579-501e069a-6abb-4158-b02d-afd5c415716f.png">
<img width="251" alt="Annotation 2022-08-28 153208" src="https://user-images.githubusercontent.com/62674157/187076580-5815f12f-5e94-4195-a171-c56dd9054874.png">
m/freeplane/freeplane/files/9439731/auto.zip)

**Comment by dpolivaev** [comment]
Hello,

unfortunately, the file with the filters is not attached correctly.
Could you please submit it again?

**Comment by Illegit** [comment]
[auto (2).zip](https://github.com/freeplane/freeplane/files/9538372/auto.2.zip)
is it ok?

**Comment by dpolivaev** [comment]
Yes, now I see the content, thanks

**Comment by dpolivaev** [comment]
It does not look like a bug.
The menu shows only filters assigned a name using the set name button in the filter composer.
The attached file contains no filter names.

<img width="371" alt="setName" src="https://user-images.githubusercontent.com/1558052/189486498-d44ed820-32f7-46ea-b3c5-930aadb42317.png">
