### ISSUE TITLE
节点大小怎么调节

### ISSUE THREAD

**Issue by s114210** [freeplane/freeplane#609]
节点的大小是否有限制，导图节点的内容无法完全显示，我找不到调节按钮，你能帮助我么？非常感谢！

**Comment by euu2021** [comment]
Please, try to increase this number:

请尝试增加这个数字：


![image](https://user-images.githubusercontent.com/77707706/187804920-684eb13c-d810-43fe-b3ea-63cc9ecd74f5.png)
