### ISSUE TITLE
Search Should Highlight the Searched Text Inside the Node, Not Just Highlight the Node

### ISSUE THREAD

**Issue by dsnvwlmnt** [freeplane/freeplane#61]
When searching, if your node text is a decent length, searching is an absolute nightmare. I realize most people probably don't make long node texts, but some use cases do. Some of my mindmaps have large node text, and searching becomes impossible. Search highlights the node title, but to find the text i'm looking for, i have to copy/paste the node text into Notepad and search there. :P

**Comment by fnatter** [comment]
Hello,

you can search within a node 
In the Rich Text Editor:
Alt+Enter Ctrl+F

Cheers and Best Regards,
Felix

**Comment by dpolivaev** [comment]
Please reopen this issue if needed
