### ISSUE TITLE
Allow (or force) word wrap in Note panel for Markdown and LaTeX content types

### ISSUE THREAD

**Issue by leehach** [freeplane/freeplane#614]
Freeplane added the ability to set Notes to Markdown or LaTeX. Long lines hang off the right side of the panel, especially if the user chooses to display the Note panel on the right or left side of the Freeplane window. (I do so, and think it is more useful given that most laptops/monitors have a wide aspect ratio. There is more real estate for an extra panel on the sides than on the top or bottom.)

Most text editors (e.g. Notepad++) allow the use to toggle word wrap on and off. The Standard and Text Content types automatically have text editing, which is common for WYSIWYG editors. It would be very useful to have word wrap enabled for code-based content as well, such as Markdown and LaTeX.

Personally, I think it should be the default.

**Comment by dpolivaev** [comment]
Preview 1.10.5_04
