### ISSUE TITLE
jump-in: drop-as-sibling +COPY creates a child instead of a sibling

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#616]
### Discussed in https://github.com/freeplane/freeplane/discussions/613

<div type='discussions-op-text'>

<sup>Originally posted by **wordmuse** August 31, 2022</sup><i>
In previous versions of FP, if I dragged [+COPY] a node from outside a hierarchy, I could drag it to a sibling position or a child position. FP would visually show me which I was doing.

But recent versions have made it so I can only drag [+COPY] such a node to a child position - even though the visual cue that I am dragging to a sibling position remains.  

Can this be looked into and corrected?  Or if it's a setting that I somehow inadvertently changed, let me know that.

If necessary, I can provide a video of what I'm experiencing.

Thanks.
~ Bal</i></div>

Since 1.10.4-pre06 (_allow left and right side nodes after jumping in_)

#### Technical investigation
* `org.freeplane.view.swing.ui.mindmapmode.MNodeDropListener`#**drop**
  * `org.freeplane.features.map.MapController`#**suggestNewChildSide**
    * `org.freeplane.features.map.mindmapmode.clipboard.MMapClipboardController`#**paste**

`suggestNewChildSide` looses `AS_SIBLING` in favor of `target.getSide()` and the subsequent call to `paste(t, targetNode, MapController.suggestNewChildSide(targetNode, side));` no longer receives `AS_SIBLING` (but instead `LEFT`, `RIGHT` or `DEFAULT`). 
And without `AS_SIBLING`, `paste` creates a new child, instead of a sibling.

**Comment by dpolivaev** [comment]
Preview 1.10.4_12
