### ISSUE TITLE
Better Cloud (Cloud Over Selected Nodes in Different Branches Only)

### ISSUE THREAD

**Issue by autoca** [freeplane/freeplane#617]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to create a cloud and find out how limited this feature is.

**Describe the solution you'd like**
It should be possible to make a cloud span only over indiviually selected nodes, i.e. over partial branches. On the old sourceforge domain I found a similar feature request already: https://sourceforge.net/p/freeplane/featurerequests/1060/
The point is, I want one cloud to span over nodes of different branches and not necessarily all the way to the last node.

**Describe alternatives you've considered**
Creating one floating transparent node with a cloud and then adapting the size and position of that node-cloud accordingly as I want it. For me, the important part is the visual grouping aspect. I don't need to connect the data of the cloud to the data of the nodes in the background.

I could also be happy with just visually drawing a vector based cloud around some nodes, but Freeplane does not have any drawing tools, afaik.

**Additional context**
None.

**Comment by macmarrum** [comment]
I understand your need and see the validity of the request.

In the meantime, maybe summary nodes could be of some help to you – please see [cloud-possiblities.zip](https://github.com/freeplane/freeplane/files/9477014/cloud-possiblities.zip).

> Creating one floating transparent node with a cloud and then adapting the size and position of that node-cloud accordingly as I want it.

Oh, that's a clever trick. I used it in [cloud-possiblities.zip](https://github.com/freeplane/freeplane/files/9477014/cloud-possiblities.zip) and it looks quite interesting.

**Comment by autoca** [comment]
Regarding the could-possibilities map:

(1) Ooohhhh, you are actually using a floating node with one extra child node and a cloud around them. This way, the size of the cloud can easily be adjusted by just moving the child node. I like a lot. I think that is an acceptable work-around. (I had only used it without child, so changing the size to my wishes was a pita. But with a child node, that is really clever. Should have thought of it. Thanks!)

Hint: This works easily with the two rectangular clouds. 
_With the arc or star cloud shapes, though, one probably would want to add more than one child node - and make them free floating as well - to use them as "corner points" for the overall cloud area._

(2) The visual trick with A1-F1, hiding the edge coming from A1 and adding a connector to another node that looks like an edge, is cute, but confusing and deceptive. Could easily lead to problems down the line, I think.

(3) Summary nodes, I don't think that gives me what I want, but thanks for the hint.

Still, the cloud for a floating node with child mentioned above solved my issue for now. Thank you.

Regards, autoca

**Comment by euu2021** [comment]
> Ooohhhh, you are actually using a floating node with one extra child node and a cloud around them.

I would just add that using free positioned nodes as child of B1, instead of free floating nodes, may be a better option, because the cloud will follow the parent node. See comparison (on the left, following my suggestion):

![javaw_Md616b12ds](https://user-images.githubusercontent.com/77707706/188248269-f90ead82-f87e-4470-99fe-1015336b9d01.gif)

**Comment by autoca** [comment]
Good point. That sure is a valuable additional thought. I would, again, not have thought of that. Like it a lot, as before. Thank you!

I assume that both will have its applications. Sometimes I would want to be able to flexibly move the cloud around and sometimes I would rather want it to follow a certain node.

What cannot be done by either approaches is that the size of the cloud area would follow the size of the visible part of the sub-branch. E.g. if a sub-branch is inside a cloud and part of that sub-branch gets hidden, then the cloud will be "too big" with both of these approaches. So, they remain a work-around until the end-node(s) of a standard cloud can be specified as well.

**Comment by euu2021** [comment]
>What cannot be done by either approaches is that the size of the cloud area would follow the size of the visible part of the sub-branch. E.g. if a sub-branch is inside a cloud and part of that sub-branch gets hidden, then the cloud will be "too big" with both of these approaches. So, they remain a work-around until the end-node(s) of a standard cloud can be specified as well.

I see that this is another situation that would benefit from the technique of using relative distances in a script, as I mentioned in the end if that [post](https://github.com/freeplane/freeplane/issues/578#issuecomment-1221440286). So, we would be able to make the cloud nodes get automatically aligned with the last visible node.
