### ISSUE TITLE
conditional style based on the results of another conditional style does not work

### ISSUE THREAD

**Issue by autoca** [freeplane/freeplane#632]
**Describe the bug**
(1) I am first basing a conditional style on the parent's style. If the parent has style "S1" then the child node should have style "S2". This works. So far so good.

(2) Now, I am also basing another conditional style on the parent style: If the parent has style "S2" then the child should have style "S3".
-> Here seems to be a bug. If I manually assign "S2" to the parent in the second scenario, the child has "S3", this works ok. But if the parent gets "S2" assigned automatically because of the conditional style in scenario (1), then the conditional style in scenario (2) does not take effect.

**Mind map files**
[conditional style based on the results of another conditional style.zip](https://github.com/freeplane/freeplane/files/9484825/conditional.style.based.on.the.results.of.another.conditional.style.zip)

**Expected behavior**
I expect a conditional style to be applied not matter HOW the condition comes to be true.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 8.1
 - Java Version: 15.0.7

**Comment by macmarrum** [comment]
It's so by design.

But there is a way to apply a Style to a node based on another node's Style. It can be done with a script. And the script can be made to run automatically whenever a node is changed.

I can help you with creating such a script and setting it up for an automatic execution.

**Comment by autoca** [comment]
Thanks!
I did not find an explanation for that by-design behavior in the documentation nor is is clear or even intuitive that it would (not) work that way. Anyway, I hope anyone noticing that behavior will find this thread.

As for my particular situation, I could solve it for me by adjusting the conditions to follow a different logic. But it is just furstrating if one expects it to work a particular way, investing time and thought into creating conditions and stuff and then must find out that he/she can change it all around again. Anyway, thx for the info and the help offered.
