### ISSUE TITLE
Filtered nodes can be overlapping with still visible root node (bug)

### ISSUE THREAD

**Issue by autoca** [freeplane/freeplane#635]
Root is never hidden. It's how Freeplane works.

Regarding (2), this sounds like a bug. Would you be able to create a report, including a sample mindmap and steps to reproduce the issue?

_Originally posted by @macmarrum in https://github.com/freeplane/freeplane/discussions/634#discussioncomment-3549260_

**Comment by autoca** [comment]
[filtering and root node.zip](https://github.com/freeplane/freeplane/files/9485005/filtering.and.root.node.zip)

(1) open the attached map:
![grafik](https://user-images.githubusercontent.com/37442404/188321923-ce90abe2-63d8-4654-94b6-02450cbf8914.png)

(2) do Filter -> Filter selected nodes:
![grafik](https://user-images.githubusercontent.com/37442404/188321945-6541510b-28a8-4f4c-906b-0cd4c2613b82.png)

(3) result is already bad -> imagine a bigger root node and more level 3 nodes even with children, then it is even worse

**Comment by dpolivaev** [comment]
Node 1 is a floating node. It's distance to the parent node is ignored when it is hidden, but think I can change it.

**Comment by autoca** [comment]
If you could also change the issue that a new floating node always appears half on top of the root, that would be great.
It should either appear in the middle of the current view if added with the main menu or with a hot key.
Or, if added with the context menu of an existing node, then it should be added where the next child node of that node would be.
But the fact that it is added half on top of the root even when I am viewing a completely different part of the map is just ... well I don't want to be negative again, but it is hard not to be. :smiley: Besides, it is hard to pick it up with the mouse when it is half way on top of the root. MTIA :+1:

**Comment by euu2021** [comment]
>If you could also change the issue that a new floating node always appears half on top of the root, that would be great.

I agree with your suggestion, but I just want to make sure that you know that floating nodes can be created by pressing `Ctrl + Double Click on the background`. The advantage of doing like this is that the new node is created exactly on the spot clicked.

**Comment by autoca** [comment]
> that floating nodes can be created by pressing `Ctrl + Double Click on the background`. ... the new node is created exactly on the spot clicked.

That's exactly what I was looking for all the time. I wish that info was easier to find in the help. THANK YOU!!!

**Comment by dpolivaev** [comment]
I  can not write help. I can write only code.
If you can suggest an improvement to help or know someone who could contribute please let me know.

**Comment by autoca** [comment]
I could not find a PM option, so I just reply here:
Yes ..... I do know someone who could contribute with writing help ... it's me 🥲
I just got my diploma in writing technical doc and in my thesis I focused on writing online help.
However, I also just startet a new job and thus do not have much time atm. But I can probably help a little bit.

**Comment by euu2021** [comment]
>I just got my diploma in writing technical doc and in my thesis I focused on writing online help.

Interesting! The documentation is a big challenge for FP. You could make it a study case for your PhD!

**Comment by dpolivaev** [comment]
Hello @autoca ,

> I do know someone who could contribute with writing help ... it's me

I am glad to hear it.

> I just got my diploma in writing technical doc and in my thesis I focused on writing online help.

Currently, Freeplane has a documentation mind map delivered with the app and a new online documentation site https://docs.freeplane.org/ mostly written by the community and written using markdown at https://github.com/freeplane/docs. 

I would be highly interested to learn your ideas and welcome any contributions. I am looking forward to learning from you.

> I could not find a PM option

It is just not available on GitHub. You can write me an email e.g. to dimitry (at) freeplane (dot) org

> However, I also just started a new job and thus do not have much time atm. But I can probably help a little bit.

Particularly, when you discover an important not documented feature like using control+double click to insert a floating node, it were great if you could document it. Because both finding a good place and writing a clear documentation statement require proficiency and competence in docu writing.

To play around with the online documentation you can use a free online IDE https://gitpod.io/#https://github.com/freeplane/docs running in your browser (Chrome preferred) and giving you an instant preview of all changes. To submit your changes you need to fork the repo and run it with your own repo address where you can push the changes and create a pull request. Both steps are pretty easy even if people who never did it before might feel slightly out of confidence.

As I have already mentioned, the project is driven by passion and a desire to give my life a bit more sense.

Cheers, Dimitry

**Comment by dpolivaev** [comment]
Preview 1.10.5_01

**Comment by autoca** [comment]
> Interesting! The documentation is a big challenge for FP. You could make it a study case for your PhD!

Thanks for the idea, but I am done with my thesis and am happy that I am finished. Even though is is no PhD, it was enough work. xD

**Comment by dpolivaev** [comment]
I appreciate that you want to contribute, although it is not of much use if you can not find the time.

**Comment by autoca** [comment]
> Currently, Freeplane has a documentation mind map delivered with the app and a new online documentation site https://docs.freeplane.org/ mostly written by the community and written using markdown at https://github.com/freeplane/docs.

Yes, I had that impression as well. Thanks for the confirmation and some extra details.

> I would be highly interested to learn your ideas and welcome any contributions. I am looking forward to learning from you.

Thank you forr your nice words. Let's see how much time and energy I will have in the future.
 
> > I could not find a PM option
> 
> It is just not available on GitHub. You can write me an email e.g. to dimitry (at) freeplane (dot) org

Ok, thanks for clearing that up.
 
> Particularly, when you discover an important not documented feature like using control+double click to insert a floating node, it were great if you could document it. Because both finding a good place and writing a clear documentation statement require proficiency and competence in docu writing.
> 
> To play around with the online documentation you can use a free online IDE https://gitpod.io/#https://github.com/freeplane/docs running in your browser (Chrome preferred) and giving you an instant preview of all changes. To submit your changes you need to fork the repo and run it with your own repo address where you can push the changes and create a pull request. Both steps are pretty easy even if people who never did it before might feel slightly out of confidence.

Ok, thanks for the heads up. I will try to look into it eventually.

**Comment by autoca** [comment]
> I appreciate that you want to contribute, although it is not of much use if you can not find the time.

That might be true. And as a matter of fact, I am not planning to invest a lot of time. That would defeat the purpose of using a free software. Before I would invest a lot of time, I would be better off just buying that expansive commercial mindmap software.

**Comment by dpolivaev** [comment]
If the purpose is saving personal resources, maybe yes. If the purpose is having a larger positive impact, probably not.

**Comment by autoca** [comment]
Sure, but at the moment I don't even have enough personal resources. And even if that ever changes, I guess, I would rather try to have a larger positive impact on society in other ways. But as I said, now that I know about the help thing, I might contribute a little bit once in a while.
