### ISSUE TITLE
allow oval handle size (for moving nodes in space) to be changed

### ISSUE THREAD

**Issue by autoca** [freeplane/freeplane#636]
see this discussion:
https://github.com/freeplane/freeplane/discussions/630

especially on larger maps and when zoomed out, this is extremely cumbersome to find and click the oval handle of a node with the currently fixed size settings (because under these conditions they become extremly narrow).

**Comment by dpolivaev** [comment]
Preview 1.10.5_03

**Comment by autoca** [comment]
Thank you!
