### ISSUE TITLE
note content loading error after ui change

### ISSUE THREAD

**Issue by guoranjun2** [freeplane/freeplane#639]
**Describe the bug**
note 

**To Reproduce**
1. change ui by script of setting
2. check note in notepanel and note dialog

---

two way have same effect:

1. change ui by script: 

![screenshot-20220905121816](https://user-images.githubusercontent.com/50692082/188359893-861c0f4a-340c-409c-a344-e7a211cf27a0.gif)

2. change ui by setting: 

![screenshot-20220905122913](https://user-images.githubusercontent.com/50692082/188361002-a1fa54ba-62e7-4810-9d66-c8d015649d7f.gif)

**Expected behavior**

note content loading normal.

**Mind map files**
[testui.zip](https://github.com/freeplane/freeplane/files/9486679/testui.zip)

**Desktop (please complete the following information):**
 - OS: win10
 - Java Version: java17

**Comment by guoranjun2** [comment]
here is the script for quicker test:

```groovy
import com.formdev.flatlaf.FlatLaf
import com.formdev.flatlaf.IntelliJTheme
import org.freeplane.core.resources.ResourceController

def name = "SolarizedLight.theme.json"
def stream = ResourceController.getResourceController().getResourceStream("/laf/"+name)
IntelliJTheme.setup(stream)
FlatLaf.updateUI()
```

**Comment by guoranjun2** [comment]
here is the script for quicker test:

```groovy
import com.formdev.flatlaf.FlatLaf
import com.formdev.flatlaf.IntelliJTheme
import org.freeplane.core.resources.ResourceController

def name = "SolarizedLight.theme.json"
def stream = ResourceController.getResourceController().getResourceStream("/laf/"+name)
IntelliJTheme.setup(stream)
FlatLaf.updateUI()
```

**Comment by dpolivaev** [comment]
Preview 1.10.5_04
