### ISSUE TITLE
enable "Permit File/Read Operations (NOT recommended)"

### ISSUE THREAD

**Issue by LaWizard** [freeplane/freeplane#642]
There are two(2) enable "Permit File/Read Operations (NOT recommended)" checkboxes available. 

Click Menu options Tools > Preferences > Plugins > Scripting

See that - There are two(2) enable "Permit File/Read Operations (NOT recommended)" checkboxes available. 

**Screenshots**
![Bug-Preferences-Plugins-Scripting](https://user-images.githubusercontent.com/6464740/188949938-b3400982-c8c4-4a16-9274-88f0283d5656.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro
 - Version 10.0.19044 Build 19044
 - Java Version - interesting questions can not confirm the presence of Java - it should exist I would think - but I can not confirm or deny it being installed at this time.

**Comment by macmarrum** [comment]
In the screenshot that you attached I can see two separate checkboxes
- Permit file/**read** operations (NOT recommended)
- Permit file/**write** operations (NOT recommended)

One is for reading, the other for writing.

**Comment by LaWizard** [comment]
Author,

WOW - Sorry I swear I stared at that forEVER before reporting it.

My apologies, SMH - Tired eyes too late in the day.

John
________________________________
