### ISSUE TITLE
Have a way to "Edit node core in-line" but with the cursor at the beginning instead of at the end

### ISSUE THREAD

**Issue by NicolasWebDev** [freeplane/freeplane#643]
**Is your feature request related to a problem? Please describe.**
I'm used to editing in vim for as many things as I can, so I got pretty used to using the "i" key to "insert" text before the cursor, and the "a" key to "append" text after the cursor. Similarly, many times I want for example to just capitalize the first word of a node, or modify its first part. Right now I have to click my shortcut to edit, then press home to go to the beginning of the node.

**Describe the solution you'd like**
It would be really nice to have an option to edit, but positioning the cursor at the beginning of the text rather than at the end.

**Describe alternatives you've considered**
As said earlier, use the shortcut to edit in-line, then press "home" on my keyboard. But I need it so often that it gets annoying.

**Comment by euu2021** [comment]
When I press Home (without opening the edit in-line first), the cursor goes straight to the beginning:

![javaw_iOWAEQ2qnE](https://user-images.githubusercontent.com/77707706/189006696-93d4c6f6-c324-4f48-801e-671255cd1091.gif)

**Comment by NicolasWebDev** [comment]
Thanks @eu2021 for the really prompt answer. And impressive answer indeed, I actually would never have thought about trying that. Actually, on my laptop I have to press an Fn key combination to get "Home", which is really terrible design.

I didn't think it was feasible because I did not find any menu entry to do it. Do you know if it is somewhere there, and I haven't found it? Because I would appreciate the possibility to remap the key.

![Screenshot from 2022-09-07 19-51-15](https://user-images.githubusercontent.com/2276631/189010277-ec9ee343-e2cc-4576-b6da-3dba353d2901.png)

![Screenshot from 2022-09-07 20-02-17](https://user-images.githubusercontent.com/2276631/189010785-8e7b54ca-bf86-4305-8518-4e9e7be70d12.png)

**Comment by euu2021** [comment]
I think it's not possible. While your request is not fulfilled, I can recommend a workaround. Using Autohotkey solves most of those remapping problems. This script turns F2 into Home, only in Freeplane:

```
#NoEnv 
SendMode Input 
SetWorkingDir %A_ScriptDir% 
SetTitleMatchMode 2

#IfWinActive, ahk_exe javaw.exe
F2::
Send, {Home}

return

```

You can change F2 for whatever key is more convenient to you.

**Comment by NicolasWebDev** [comment]
Thanks @euu2021 , I will use a workaround then.
