### ISSUE TITLE
Look and feel nimbus gives absurdly large buttons

### ISSUE THREAD

**Issue by grotesque** [freeplane/freeplane#647]
Tools->preferences->Appearance->Look and feel->Nimbus 

Restart

blown up scaling, OK button takes up the entire screen etc.

Have to uninstall and reinstall to resolve

OS: windows 11
version Freeplane-Setup-with-Java-1.10.3.exe

**Comment by dpolivaev** [comment]
Can you please check if this problem still occurs under the latest preview version?
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

**Comment by grotesque** [comment]
This doesn't occurs in Freeplane-Setup-with-Java-1.10.4-pre12.exe
