### ISSUE TITLE
Pasting the following text in freeplane creates a weird node

### ISSUE THREAD

**Issue by grotesque** [freeplane/freeplane#648]
text exclude quotations "How to remove EAR WAX at home using HYDROGEN PEROXIDE (H202) solution | Doctor O'Donovan explains - YouTube: https://www.youtube.com/watch?v=pprkgX0fwNs"

When pasted (ctrl+v) into freeplane makes a node with pink border. Why?
![weird](https://user-images.githubusercontent.com/305091/189484017-5eb508d4-f96d-4ab8-b42d-6fad7b945037.png)

check screenshot

OS: windows 11
ver: Freeplane-Setup-with-Java-1.10.3.exe

**Comment by dpolivaev** [comment]
You activated option `Filter->Highlight all matching nodes` and entered text `pla` which is contained in word "explains"

**Comment by grotesque** [comment]
Ah yes. I'm new. sorry.
