### ISSUE TITLE
Freeplane won't start up saying: "This application requires a Java Runtime Environment 11 - 17"

### ISSUE THREAD

**Issue by PontiacCZ** [freeplane/freeplane#649]
**Describe the bug**
I have just installed 64bit Freeplane 1.10.3 using **Freeplane-Setup-1.10.3.exe**. When I launch the application I get a window saying:

_This application requires a Java Runtime Environment 11 - 17_

![image](https://user-images.githubusercontent.com/9153595/189484600-e8c48c99-d86e-45e0-a212-c20fa8bfa759.png)

After I click the OK button a Java webpage opens offering download 64bit Java Version 8 Update 341.

![image](https://user-images.githubusercontent.com/9153595/189484748-24c2583b-944c-473f-ac6f-5b386771b05b.png)

BUT I already have Java 8 update 341 thanks to automatic updates:

![image](https://user-images.githubusercontent.com/9153595/189484882-5b8a0ed5-ea1a-4ccf-86a6-1e50e042131f.png)

![image](https://user-images.githubusercontent.com/9153595/189484989-278fb7c1-adc3-4c74-a4b2-2349fccdc66f.png)

And what's more, before uninstalling previous Freeplane version 1.9.12 (which had come from _Freeplane-Setup-1.9.12.exe_) I was using it. It ran smoothly and opened my recent mindmap just fine.

**Desktop:**
 - OS: Windows 10 Pro
 - Version 21H2
 - Java Version 8 update 341

**Comment by lukailicgithub** [comment]
I have the exact same issue.

Can someone help us here?

Merci!

**Comment by euu2021** [comment]
One easy solution is using the version that comes with Java: Freeplane-Setup-with-Java-1.10.4.exe (edit for clarification: or any newer version that comes with Java, including the preview versions)

![image](https://user-images.githubusercontent.com/77707706/189505713-b5752400-e881-41cc-ab53-dae9a62300d8.png)

For more solutions, see:
#275 
#365 
#462

**Comment by euu2021** [comment]
Clarification: in my example above, I used the version 1.10.4 simply because it was the latest stable version by the time that I was writing. The important thing here is that you use the version that already comes with Java. The same effect can be achieved by using the latest preview version, for example.

See more in [this comment](https://github.com/freeplane/freeplane/discussions/652#discussioncomment-3618720)

**Comment by PontiacCZ** [comment]
I have just installed fresh new version 1.10.4, but the issue stays the same.

I know about Freeplane with bundled Java. This report is about the installer without Java.

**Comment by dpolivaev** [comment]
If you want to use an external Java version you need to set the environment variable FREEPLANE_JAVA_HOME as described in https://docs.freeplane.org/getting-started/Command-line_options_and_configuration.html#select-java-installation-used-to-run-freeplane.

The patch changing the download URL is not available in 1.10.4, it is scheduled for 1.10.5

**Comment by autoca** [comment]
Also, have a look at https://github.com/freeplane/freeplane/discussions/659
You may need a version that is NOT from Oracle.

**Comment by regis586** [comment]
Hi,
I've the same issue (Java error) with Freeplane-Setup-with-Java-1.10.5.exe..
I'm back on 1.10.04..

**Comment by dpolivaev** [comment]
@regis586 it means you are likely to have downloaded the Setup without Java

**Comment by regis586** [comment]
Hum..
Before install "with Java", I've tried "the without"..

Same issue..

And each time, to use 1.10.4 again, I've had to reinstall "jre-8u351-windows-x64" again..

**Comment by regis586** [comment]
It work's fine now, with Freeplane-Setup-with-Java-1.10.6.. :-)

**Comment by PontiacCZ** [comment]
It indeed does, I've just installed it as well. But this issue is about the installer **without** bundled Java. So I first tried to update with `Freeplane-Setup-1.10.6u1.exe` - still the same "This application requires a Java Runtime Environment 11 - 17" error.

**Comment by autoca** [comment]
Which external Java version did you download and, especially, from WHERE did you download it?
