### ISSUE TITLE
HiDPI rendering is bad.

### ISSUE THREAD

**Issue by aadrian** [freeplane/freeplane#65]
Freeplane renders badly on HiDPI screens (at least on Windows and Linux).

Icons, tab names and many popup window contents do not seem to be scaled correctly (or at all) on HiDPI screens.

Thank you.

**Comment by aadrian** [comment]
Sorry but in 1.6.x is even worse :( .
 - If nothing is set, it's smaller than older versions
 - If in "Appearance/Monitor Size"  is correctly given (since it seems to get a wrong value on any monitor I've tried), the scaling is waaay to big, and makes is also unusable.

I know there are to many possible tweaks and tricks regarding HiDPI for Java, but a "simple" app like this: https://github.com/krpors/gimlet just seems to scale correctly on various HiDPI screens.

**Comment by dpolivaev** [comment]
The example application you mention uses another GUI framework and is not relevant for Freeplane.
Generally, the bigger the monitor size you put in the configuration, the smaller the visible fonts.

**Comment by aadrian** [comment]
> The example application you mention uses another GUI framework and is not relevant for Freeplane.

It was just an example (using JavaFX) that illustrates that Java seems to get it right now out-out-of-the-box without any tweaks required from the user's side - I suppose it reads the system settings (this was not working in the past with older JDKs).

> Generally, the bigger the monitor size you put in the configuration, the smaller the visible fonts.

I'm not reporting issues with the diagrams themselves (since they can be easily zoomed in and out). The issue is still with the GUI controls that don't seem to be right.

**Comment by dpolivaev** [comment]
It was still not working using Java Swing with JDK 8

**Comment by dpolivaev** [comment]
If you can point me to a working solution please do, overwise accept the reality

**Comment by mlogic** [comment]
I'm running Freeplane on Linux using a HiDPI monitor (4K with 15" display). Changing the "Appearance/Monitor Size" from the default 45 to 25 worked for me, but the default theme's (of Look and Feel) font was ugly in a larger size. I found that the GTK+ theme works great with the default 45 "Appearance/Monitor Size" on my monitor. Thanks for the great job! One thing that could be improved is that the GTK+ theme's checkboxs are a still a bit too small and seem not to change with the Monitor Size setting.

**Comment by dpolivaev** [comment]
Recommended is setting the monitor size option to its real size (15'') and selecting the"scale UI fonts" option. However, on some systems other settings work better in a particular case.

**Comment by dpolivaev** [comment]
Also, consider a separate option for menu font size

**Comment by GordianDziwis** [comment]
Solution for 4k and 16 inch screen for Freeplane 1.7:
1. Start freeplane with 

    ```
    env GDK_SCALE=2 freeplane
    ```
1. In `Appereance` Uncheck Scale UI Fonts
