### ISSUE TITLE
style assigned to new nodes: grayed out menu items

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#654]
Executing `Format->Manage Styles->Edit styles` causes menu items to gray out in `Format->Style assigned to new nodes`

![2022-09-11_15,05,39](https://user-images.githubusercontent.com/7197131/189529457-0bfae7d9-6b35-4ee5-8f1a-46cec45194ec.png)

**Comment by dpolivaev** [comment]
Preview 1.10.5_02
