### ISSUE TITLE
Error: Could note create the virtual Machine Error: a fatal exception has occured. Program, will exit

### ISSUE THREAD

**Issue by AngelikaZuefle** [freeplane/freeplane#661]
we got this error
Error: Could note create the virtual Machine Error: a fatal exception has occured. Program, will exit*Describe the bug**
We use the OpenJDK Version1.8.0_345 64 Bit and the Freeplane Mindmap Version 1.10.4   If we start the "C:\Program Files\Freeplane\freeplanelauncher.jar"  directly Mindmaps starts....  it seams for me that freeplane Mindmaps not work with the new version of openJDK version 1.8.0_345-B01

**Comment by macmarrum** [comment]
Freeplane requires Java version between 11 and 17. Java 8 (aka 1.8.0) is not compatible.

Please see also 
- https://github.com/freeplane/freeplane/discussions/659#discussioncomment-3629166
- https://docs.freeplane.org/getting-started/Distributions.html
