### ISSUE TITLE
Add-ons - link broke - https://www.freeplane.org/addons/

### ISSUE THREAD

**Issue by engdarkalchemist** [freeplane/freeplane#664]
**Describe the bug**
Clicking in the 'Visit add-on page', in Tools > Add-ons, redirect to page and gets error. The link should redirect to https://docs.freeplane.org/getting-started/Add-ons_(install).html

**To Reproduce**
1. Go to 'Tools'
2. Click on 'Add-ons'
3. Click on 'Visit add-on page'
4. See error on page https://www.freeplane.org/addons/
An error has been encountered in accessing this page.

1. Server: www.freeplane.org
2. URL path: /addons/
3. Error notes: NONE
4. Error type: 404
5. Request method: GET
6. Request query string: NONE
7. Time: 2022-09-14 14:31:44 UTC (1663165904)

Reporting this problem: The problem you have encountered is with a project web site hosted by SourceForge.net. This issue should be reported to the SourceForge.net-hosted project (not to SourceForge.net).

If this is a severe or recurring/persistent problem, please do one of the following, and provide the error text (numbered 1 through 7, above):

Contact the project via their [designated support resources](https://sourceforge.net/support/prweb-lookup.php?host=www.freeplane.org&support=1).
Contact the project administrators of this project via email (see the upper right-hand corner of the [Project Summary page](https://sourceforge.net/support/prweb-lookup.php?host=www.freeplane.org) for their usernames) at user-name@users.sourceforge.net
If you are a maintainer of this web content, please refer to the [Site Documentation regarding web services](https://sourceforge.net/p/forge/documentation/Project%20Web%20Services/) for further assistance.

NOTE: As of 2008-10-23 directory index display has been disabled by default. This option may be re-enabled by the project by placing a file with the name ".htaccess" with this line:

Options +Indexes

**Expected behavior**
The link should be pointed to https://docs.freeplane.org/getting-started/Add-ons_(install).html instead.

**Comment by dpolivaev** [comment]
It should be fixed now
