### ISSUE TITLE
Embedded SVG image text color is not shown correctly

### ISSUE THREAD

**Issue by apaza610** [freeplane/freeplane#670]
**Describe the bug**
When importing an SVG image the text color is always black.

**To Reproduce**
1. Create an SVG with text in Inkscape.
2. In Freeplane go to 'Inset/AddImage/AddImage' in a node.
3. See error

**Expected behavior**
Colored text should display correct colors.

**Screenshots**
![problemaFreeplaneSVGcolor](https://user-images.githubusercontent.com/10149862/190914711-f5191d19-4225-4120-9696-4cabcad2aebf.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [10]
 - Java Version 17

**Comment by dpolivaev** [comment]
I think it is a limitation of the library used for rendering svg images.
