### ISSUE TITLE
FP 1.10.5 03: not able to load user defined filters

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#686]
**Describe the bug**
Cannot load user defined filters, the list is always empty. What is wrong? How can I mend it?

**To Reproduce**
![image](https://user-images.githubusercontent.com/62674157/192141787-ea2ac955-87c9-4918-84d7-511e44208938.png)

I have no idea how to detail this issue to you.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22] 11
 - Java Version 10.5 (FP loaded)

**Additional context**
[log.0.txt](https://github.com/freeplane/freeplane/files/9640677/log.0.txt)

**Comment by Illegit** [comment]
Hi, just happened now:
if I load filters from the map user folder proposed by the filter composer it doesn't work, instead, if I download filter from the fp user folder it works (and I succeeded to load them in FP). Strange. NOw it is solved but with this sort of recommendation.
Regards

**Comment by dpolivaev** [comment]
I am sorry I do not understand the bug description.
"It does not work" and "It works" do not contain any specific details.
Please upload all relevant filter definition files and attach all relevant screenshots.

**Comment by Illegit** [comment]
the problem is that filters list is empty, why? when I load the filters nothing happened, as I've written I'm very specific.
I discovered later that when I open a filters list file e.g.: xxx.mmfilter if the file is in the FP folder (called "user directory") it has been loaded and user filters list becomes full, but if  the filters file is in "current map directory" (when filter composer by defualt opens) the user filters list remains empty (even if the filters are written in the filter composer)... cannot ubderstand the reason why it happens...

**Comment by dpolivaev** [comment]
> Please upload all relevant filter definition files

Why do you not do what I am asking for?

**Comment by dpolivaev** [comment]
Also, if the filters are loaded you can find them in the filter drop-down boxes. Only filters that have explicitly assigned names are shown as menu items.

**Comment by Illegit** [comment]
I have not understood what you are asking for. But maybe the following:
[filter1.zip](https://github.com/freeplane/freeplane/files/9641703/filter1.zip)
[filter2.zip](https://github.com/freeplane/freeplane/files/9641705/filter2.zip)

Filter2 wasn't possible to load & keep (only load in filter composer).

**Comment by dpolivaev** [comment]
Filter conditions in Filter2 have no user given names.
I think you have not assigned them.

**Comment by Illegit** [comment]
Hi I couldn't answer. That's ok. Still cannot Connect to My account till
end  next week. Now with names it is working.
Thanks

Il gio 29 set 2022, 18:37 Dimitry Polivaev ***@***.***> ha
scritto:
