### ISSUE TITLE
Enregistrement échoué

### ISSUE THREAD

**Issue by webew** [freeplane/freeplane#691]
**Describe the bug**
Impossible to save a map

**To Reproduce**
1. Go to 'File'
2. Click on 'Save'
3. L'enregistrement de la carte a échoué

**Expected behavior**
Save a map

.

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Screenshots**
![Capture freeplane](https://user-images.githubusercontent.com/27566348/192360006-fcbbf2ba-aea1-42bb-a4f3-280de0a59858.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version10.0.19043
 - Java Version : 8 mise à jour 341

**Additional context**
![Capture freeplane version](https://user-images.githubusercontent.com/27566348/192360810-03ba158b-3077-4cd3-b573-c9b25dc7d786.JPG)

**Comment by dpolivaev** [comment]
It looks like you try to save a map in a folder where you do not have write permissions.
It does not look like a freeplane bug.
