### ISSUE TITLE
A configuration to set Java path

### ISSUE THREAD

**Issue by mahengrui1** [freeplane/freeplane#695]
for Windows it looks like an environment variable is to show the path of Java required if Java is not registered. But I prefer portable version and don't like set environment variable. Maybe a file to edit will be better

**Comment by dpolivaev** [comment]
Windows launcher uses launch4j, I think we do not have a choice there.

**Comment by macmarrum** [comment]
An alternative is to use `freeplane.bat` with a path to `java.exe` in place of `java`

**Comment by mahengrui1** [comment]
> An alternative is to use `freeplane.bat` with a path to `java.exe` in place of `java`

@macmarrum thank you. Where is `freeplane.bat`?

 now I find that to launch freeplane in terminal, just in jdk:

` .\java -jar "……\FreeplanePortable\App\Freeplane\freeplanelauncher.jar"`
