### ISSUE TITLE
Notes: One hyperlink turns all following text into the same hyperlink.

### ISSUE THREAD

**Issue by DendrocoposMajor** [freeplane/freeplane#696]
**Describe the bug**
In a note:
All text following a link to a URL is also turned into the same hyperlink. Even if you manually delete a superfluous link the next text turns blue and is converted to the same link as the first intentionally created one. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a node, any node
2. If not visible "Show" the notes panel.
3. Enter some text and turn it into a hyperlink either by using CTRL+ H (on windows) + return when done or the menu.
4. Enter some more text. 
6. See error! Surprisingly this is now also a hyperlink to to same URL. This also affects pasted text.

**Expected behaviour**
Only text explicitly marked as a hyperlink should be well hyperlinks.

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Screenshots**
**Example HTML**
<html>
  <head>
  </head>
  <body>
    <p>
      This is meant to be a <a href="https://slashdot.org">link to Slashdot</a>.<a href="https://slashdot.org">
</a>    </p>
    <p>
      <a href="https://slashdot.org">
</a>    </p>
    <p>
      <a href="https://slashdot.org">The following text is not supposed to link to anything at all. </a>
    </p>
    <p>
      <a href="https://slashdot.org">So this is an error.</a>
    </p>
  </body>
</html>

**Freeplane Version**
1.10.5 2022-09-25
**Desktop (please complete the following information):**
 - OS: Window 10
 - Version 21H2 (OS Build 19044.1889)
 - Java Version 15.01

**Additional context**
[Hyperlink in notes error.zip](https://github.com/freeplane/freeplane/files/9675159/Hyperlink.in.notes.error.zip)

**Comment by dpolivaev** [comment]
Yes, unfortunately, it is not perfect.
You can remove the hyperlink before adding text or add a new line for the new text and remove it using a backspace.
