### ISSUE TITLE
Freeplane crashes when script would need to delete an image cache w/o having permission

### ISSUE THREAD

**Issue by autoca** [freeplane/freeplane#698]
### Discussed in https://github.com/freeplane/freeplane/discussions/693 and especially https://github.com/macmarrum/freeplane-scripting/issues/1
Culminating in:

> Yep. The reason for my script to fail is that Freeplane needs a delete permission to remove image cache when an image-node is moved.
> 
> The error can be isolated to the following instruction
> 
> ```
> node.moveTo(node.parent.parent)
> ```
> 
> Please feel free to create a Freeplane bug
> 

**Describe the bug**
Please, see the above linked threads.

**Suggestion**
Allow write/delete and also other permissions on a "per script" basis.
I don't want to generally allow it for any script. I just forget about it and it opens a security risk for the future. But on a "per script" basis I could allow it for specific scripts without allowing it in general.

**Comment by dpolivaev** [comment]
Please attach an exception trace from the log

**Comment by autoca** [comment]
If you mean the log that macmarrum mentioned here: https://github.com/macmarrum/freeplane-scripting/issues/1#issuecomment-1261356773
then my opinion is still the same. There is a lot of data in that log and I don't understand whether it might contain information that I would not want to make public. After all, this is still a public space.

**Comment by dpolivaev** [comment]
You can send it to dimitry (at) freeplane (dot) org

**Comment by dpolivaev** [comment]
Actually, all I need is the exception trace. If it does not contain it I don't need it either.

**Comment by autoca** [comment]
Ok, thank you, Dimitry, for providing this way to transfer the information.
I have sent you an email now.

**Comment by dpolivaev** [comment]
I have not got it.

**Comment by autoca** [comment]
Hmm, not sure what the reason is. I have not gotten any reply from any mail server or anything. On my end all looks ok, so far. 
I can send it again, but does that make sense?

It has 2 zip attachments, but small in size.

**Comment by dpolivaev** [comment]
You can create an issue at https://gitlab.com/freeplane/freeplane/confidential-issues/-/issues/new and mark it as confidential

**Comment by dpolivaev** [comment]
You can use your github account to register / log in there

**Comment by autoca** [comment]
Something is weird today. I use my normal git login data but it does not work there.
I'll check again later.

**Comment by dpolivaev** [comment]
Oh, dear. You need to sign up at https://gitlab.com/users/sign_up but you can use a GitHub link instead of entering a new e-mail and password.

**Comment by autoca** [comment]
Ok, that was a misunderstanding.
Even on the sign_up page I almost did not understand but then I saw at the bottom of the page:
![grafik](https://user-images.githubusercontent.com/37442404/193449726-122425d0-34ef-4ffe-9d6b-516b50a4f0fd.png)

Since you added a commit on this issue, do you still need the data?

**Comment by dpolivaev** [comment]
I think I don't. Thanks.

**Comment by dpolivaev** [comment]
Preview 1.10.5_05

**Comment by autoca** [comment]
Thanks Dimitry,
it generally works now.

One small issue is still there:
The swapping with the parent node (that has an image attached) works but after the swapping the nodes the image is not diplayed anymore. When I save, close, and reopen the map then the image is displayed again.

I know that FP again says something about permissions but it still seems like a bug when it works after a reload of the map.
Just for the record. At least, FP does not chrash anymore.

Thx and regards, a.
