### ISSUE TITLE
HELP - Instructions for installing Freeplane alpha version on KDE Neon

### ISSUE THREAD

**Issue by budislav** [freeplane/freeplane#70]
Hello, 
I would like to ask for someone to make some instructions for installing the latest development version of **Freeplane 1.6.1 pre alpha** on **KDE Neon 5.9.3**. I didn't find on internet any kind of tutorial.. 

I have clean install of KDE Neon so I don't know if I need to download something beside this file **freeplane_src-1.6.1-alpha-pre13.tar.gz.**
From discover I can install only 1.3.15 version but this is too old..

I would be very grateful and believe many others if you put that instructions like README.txt in installation file, or wiki, github..

**Comment by ldmpub** [comment]
Hi,

Instructions to install Freeplane alpha under Linux is there is the Wiki:
https://www.freeplane.org/wiki/index.php/Linux

Last preview can be downloaded here:
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

Best regards,

2017-03-18 18:59 GMT+01:00 Budislav <notifications@github.com>:

**Comment by budislav** [comment]
Thank you for answer, but I have a problem with installing.
1. Download the Freeplane zipfile, and extract its contents to the folder of your choosing (e.g. ~/local/freeplane-xxxx , where xxxx is a version-number).
Do it means tar.gz? I downloaded zip that was for Windows? So I downloaded tar.gz and exported in Downloads folder.
I don't know where is local? I have it in Download folder.
2. Create a freeplane symlink to ~/local/freeplane-xxxx:
`ln -nsf ~/local/freeplane-xxxx ~/local/freeplane`
I typed 
`ln -nsf ~/Downloads/freeplane-1.6.1-alpha-pre13 ~/Downloads/freeplane`
so it makes me one folder with chain icons on it.

3. (optional) If you have a ~/bin folder which is in your shell path, you can create a symlink to the freeplane start-script:
`ln -s ~/local/freeplane/freeplane.sh ~/bin/freeplane`
This is optional so i didn't make that

- You should now be able to run freeplane from the commandline by simply typing freeplane.
Not working, won't start:

> The program 'freeplane' is currently not installed. You can install it by typing:
sudo apt install freeplane

So it is not installed.

Can you explain me how to install it please?
Thanks!

**Comment by vboerchers** [comment]
It's Java, so the zip is for all platforms. The tar.gz contains "src" in its name that is "source" - not what you are looking for. Please follow the instructions Nam gave you.

Closing that here. Please use the [Open Discussion forum](https://sourceforge.net/p/freeplane/discussion/758437/) for further questions.

**Comment by budislav** [comment]
Ok, I found it. You need to execute freeplane.sh from that folder because it won't start if you type just freeplane from konsole. You should change that.
