### ISSUE TITLE
The setting "Place new branches" (being set to "First") should affect more than just TAB

### ISSUE THREAD

**Issue by autoca** [freeplane/freeplane#703]
Hi Dimitry,

Thank you for your work. Here is another FR:

**Is your feature request related to a problem? Please describe.**
When I change the setting "Place new branches" to "First", then new nodes that I create by pressing TAB are positioned on top of their siblings. This is good.
However, I find it unexpected that nodes that I create by pressing ENTER, are still placed below the current node. 
Even worse, nodes (or branches) that I copy/paste are inserted still at the bottom of their new siblings.

**Describe the solution you'd like**
1) At least for copy/paste, the pasted node/branch should be inserted at the top if "Place new branches" is set to "First".
2) I personally think, that also the behaviour for creating new nodes upon ENTER should be reversed, but I understand if others may have a different feeling about this second point.

**Describe alternatives you've considered**
Not requesting this feature and being frustrated.

**Additional context**
Can't think of any.

MTIA and regards, a.

**Comment by dpolivaev** [comment]
Issue template modified
https://github.com/freeplane/freeplane/commit/b392a456c172d85f4e6bf775e66023760e054e30

**Comment by dpolivaev** [comment]
Preview 1.10.5_05

**Comment by autoca** [comment]
Thank you,
I think it was changed in _06 but still, pasting a node is now inserted at the top with the described setting. Thank you!
I also think that it is **good** that you did **not** change the insertion position upon Enter. Thank you for that too.

**However, one bug in connection with the new behaviour:**
When copying and pasting multiple nodes, then the pasted nodes, although inserted at the top, they are inserted in reverse order (compared to the source nodes). I would expect them to be inserted at the top (this is good) but in the same order as the source nodes. If you agree and could still fix that, it would be awesome, please. Thank you lots in advance.

Regards, a.

**Comment by dpolivaev** [comment]
I created preview 1.10.5_09 with a fix. I would appreciate it if you could check it timely because I would like to release 1.10.5 stable soon and focus on Freeplane 1.11.

**Comment by autoca** [comment]
Thank you for this quick fix , Dimitry!
I confirm that it now works as expected (based on my quick testing).
Seems to be fixed. Thx again.
