### ISSUE TITLE
节点设置为LaTeX格式后无法直接编辑，选中“节点编号”后格式显示错误。(en: After the node is set to LaTeX format, it cannot be edited directly, and the format will display an error after selecting "Node No.")

### ISSUE THREAD

**Issue by Shwen-Y** [freeplane/freeplane#709]
*bug1*描述
(en: bug1 description)
节点设置为LaTeX格式后无法直接编辑，选中“节点编号”后格式显示错误。
(en: After the node is set to LaTeX format, it cannot be edited directly, and the format will display an error after selecting "Node No.")

* 复现
(**To Reproduce**)
1. 将节点格式设置为 LaTeX
(en: set the node format as LaTeX)
![图片](https://user-images.githubusercontent.com/24468393/193400249-4c1c2c79-3a66-4944-8a0d-be76c067cb90.png)

2.  双击节点
(en: double click on the node)

3.  弹出对话框而不是进入编辑模式
(en: pop up a dialog box rather than entering editing mode)
![图片](https://user-images.githubusercontent.com/24468393/193400391-b3d7fa7b-a7ca-4f0f-8f2d-0bd8f82c1cfb.png)

* bug2 描述
(en: bug2 description)

* 复现
1. 将节点模式设置为LaTeX格式后，选中节点编号
(en: after setting the node to LaTeX format, select the node number)
![图片](https://user-images.githubusercontent.com/24468393/193400639-185ed7fe-1ece-4c76-861e-819b1643ec28.png)

2.  节点格式出现错误
(en: and the node display error)
![图片](https://user-images.githubusercontent.com/24468393/193400676-9bfdade9-b299-4aac-9422-9e72cde17938.png)

* 希望的行为
（en :**Expected behavior**)
1. 在节点为LaTeX格式下，双击后仍能像标准模式下进入编辑模式。
(en：when the node is set to LaTeX format and  after double clicking on the node, it can enter in editing mode as the standard format does )

2. 在节点为LaTeX格式下，选中节点编号后仍能正常显示
(en: when the node is set to LaTeX format and select node number , the node can still display correctly.)

**Screenshots**

**Desktop (please complete the following information):**
 - Java Version

**Additional context**

**Comment by dpolivaev** [comment]
latex is not compatible with node numbering.
For editing latex, there is a special text editor with syntax coloring.
In the latest preview, the editor also supports word wrap.
