### ISSUE TITLE
docear stoped updating, will you consider to integrate the docear functions

### ISSUE THREAD

**Issue by TheKiteRunning** [freeplane/freeplane#72]
freeplane and docear are both my favorite mindmap software, and I feel so sorry to see docear has stopped to update for years. Considering the close relationship between freeplane and docear, would you like to consider to integrate the docear functions.

Thank you

**Comment by dpolivaev** [comment]
Unfortunately Docear forked freeplane instead of simply delivering additional plug-ins.
Therefore Docear functions can not be integrated back.

Regards



On 10.04.2017 15:51 wrote TheKiteRunning:
