### ISSUE TITLE
XML Export fail

### ISSUE THREAD

**Issue by ghost** [freeplane/freeplane#722]
**Describe the bug**
Open the tutorial map. Click export> xml. You get "Error exporting" message.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.10.4
 - Java Version : Embed

**Comment by dpolivaev** [comment]
I think it is because you do not have write access to the directory where you want to save the exported file. By default it is the same directory as for the original mind map file.

**Comment by ghost** [comment]
Though other export worked just fine. Thank you regardless
