### ISSUE TITLE
No apostrophe first character of node in Linux version

### ISSUE THREAD

**Issue by PaulWilliamWoods** [freeplane/freeplane#723]
Make any node with the first character an apostrophe, and any text after it: 'sample text
When you press enter to commit the node, the apostrophe disappears: sample text
I've seen this on the Linux version, doesn't appear in MacOs version.

**Comment by EdoFro** [comment]
adding an apostrophe as first character is a way to define that the text after that should be treaten as a string

do this exercise for better understanding:

-   add a new node and type `3/5/2022` in it
-   When you leave the node (press Enter) it is recognized as a date and it changes to `03/05/22` or `03-05-22` or `03.05.22`, depending on your local configuration

-   but if you type `'3/5/2022`, then it is treated as a string and it shows `3/5/2022`

if you want that the apostrophe to be shown. just type two apostrophes as first characters. One will disappear, but the other will be visible.

This behaviour is not exclusive from Freeplane. There are other softwares that work the same way as well.

hope it helps,
edo

**Comment by EdoFro** [comment]
another example:

`= 3 + 5`  versus `'= 3 + 5`

the first one will show `8` and the second one `= 3 + 5`

**Comment by PaulWilliamWoods** [comment]
Thank you. I don't recall ever doing it with anything other than letters
after the apostrophe, so it seems odd that it would correct that. I was
always writing down something someone said. For example, 'I smashed my
glass in the fireplace,' he said. Then after Enter, the first apostrophe
would disappear.

Having been a programmer in the past, I can see how the apostrophe trick
could be very useful - but there must be some way to make it realise when
it's not a statement for evaluation.

Anyway, like I said, I don't have this problem in the MacOS version of
Freeplane.

**Comment by EdoFro** [comment]
you can set the **core text format** to "Text" for that node
or set it to the default style or a custom style you want to behave that way and assign that style to those nodes
