### ISSUE TITLE
A floating node influences size of summary node's curly bracket

### ISSUE THREAD

**Issue by autoca** [freeplane/freeplane#742]
**Describe the bug**
If a floating node is "before" a summary node in the hierarchy, it influences the size of the summary node's curly bracket.

**Expected behavior**
The floating node should not influence the size of the curly bracket. It should not influence it at all.

**Mind map files**
[summary and floating node bug.zip](https://github.com/freeplane/freeplane/files/9777747/summary.and.floating.node.bug.zip)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/37442404/195626234-af0262be-ea7b-40e6-9db8-c8aa2ffc5ac2.png)

**Comment by dpolivaev** [comment]
In your example, you can move the floating node down by Edit->Move and sort->Move node (Sibling down) (Control+↓).
The behavior is intentional. If you want me to reconsider it please start a discussion.

**Comment by autoca** [comment]
ok, I see, thank you for the support
