### ISSUE TITLE
Hold Shift to Keep Node on Same Horizontal Pos While Dragging

### ISSUE THREAD

**Issue by autoca** [freeplane/freeplane#748]
When I drag a node with the oval drag handle, right now it seems to be an abolutely free positioning mode.

**Is your feature request related to a problem? Please describe.**
This is generally nice, but sometimes I want to move the node ONLY horizontally.
It would be nice, if there was a constraint that stops the node from moving up or down while I drag it, maybe by holding Shift.

P.S.:
Maybe a vertical positioning constraint could be nice too or other positioning "helpers" that allow me to snap the node in place relative to other nodes or things. The grid is nice but it is not relative to anything.

Maybe the grid could be made relative to the current selection by calling a command? <-- That could be a solution for everything above.

MTIA and regards, a.

**Comment by dpolivaev** [comment]
Preview 1.11.1_05
Two-dimensional movement is possible only when shift is pressed, overwise only one direction.
