### ISSUE TITLE
Node Numbering: Cannot Save the "NUMBERED='false'" Settings

### ISSUE THREAD

**Issue by madlogos** [freeplane/freeplane#76]
Hi:

I created a mindmap like below.
![p1](https://user-images.githubusercontent.com/7327311/29298975-2c8f80a6-819e-11e7-916a-5b74bf0661d8.png)

By Ctrl+F11, I set some of the node levels `numbered`.
![cfg1](https://user-images.githubusercontent.com/7327311/29298973-2c8502d4-819e-11e7-941b-03acfd07ea4b.png)

But when I restart the freeplane app, the settings are lost.
![cfg2](https://user-images.githubusercontent.com/7327311/29298974-2c8d453e-819e-11e7-9f9e-6625513ca923.png)
All the node levels are now numbered.
![p2](https://user-images.githubusercontent.com/7327311/29298976-2cb36ade-819e-11e7-8ffd-053512746813.png)
I opened the .mm file with a text editor and noticed that only the first node has the tag `NUMBERED='true'`. If I manually insert `NUMBERED='false'` inside the node configuration entry, the mindmap keeps the style all the time. But whenever I edit and save the file, all the `NUMBERED='false'` entries are lost. 

I think this could be a problem. Please help look into it. Thx.

I am using the most up-to-date version 1.6.4.

**Comment by dpolivaev** [comment]
Fixed, https://github.com/freeplane/freeplane/commit/acb6a4573925785fb79a470f8f16f344f9784227
