### ISSUE TITLE
Bring back full screen mode of 1.8.11

### ISSUE THREAD

**Issue by nobinajohan** [freeplane/freeplane#768]
In version 1.8.1, when you chose full screen mode (Cmd L on mac) it was really full screen mode. That is no borders at all.
In version 1.10.4 you get a border and top bar left on the screen, when you choose full screen.
Is it possible to bring back the old functionality. Maybe as a setting, so you can choose at least?
It was so nice and calm having a totally blank screen around your mindmap.

**Comment by euu2021** [comment]
You can disable the top bars by right-clicking the background and disabling the bars, like the Menubar and Toolbar. This setting is independent of the setting outside full screen.

**Comment by nobinajohan** [comment]
I'm not talking about the bars, but about the gray frame:

<img width="2560" alt="Screen Shot 2022-10-24 at 19 17 43" src="https://user-images.githubusercontent.com/75474252/197590920-f84818be-58d8-402b-b517-bf2207505fb3.png">

This is how it looked in 1.8.1. No gray frames for full screen:

<img width="2560" alt="Screen Shot 2022-10-24 at 19 40 14" src="https://user-images.githubusercontent.com/75474252/197591011-87feee2f-b307-4f5a-9b43-8339c7fa8766.png">

**Comment by euu2021** [comment]
Now, I understand what you mean by "top bar".  On Windows, it doesn't appear when full screen is activated.

**Comment by dpolivaev** [comment]
Fixed in preview 1.10.5_07

**Comment by nobinajohan** [comment]
Thanks for the fast input and fix.
But unfortunately, it's not quite what I meant.
This is how it looks in the fix: the frame is gone, but the top bar is still there.
In 1.8.11 it was white all around.
Also in 1.8.11 it was not a mac full screen.
I.e., you didn't get the annoying (which is Apple's fault) side animation, but just switched window instantly.
In 1.10.5_07 it does this annoying side animation.
In 1.8.11 it didn't.
Please try 1.8.11 to see what I mean.

**Comment by dpolivaev** [comment]
Now it is implemented correctly. If you don't like apple, don't use apple or convince them to change their UI which I personally do not like at all.

**Comment by dpolivaev** [comment]
I do not understand what you mean by "gray frames". I am not going to look back at the 1.8.x version. Please provide all necessary screenshots and add explanations needed to understand what you mean.

**Comment by nobinajohan** [comment]
> Now it is implemented correctly. If you don't like apple, don't use apple or convince them to change their UI which I personally do not like at all.

I understand.
The question is how it was solved in 1.8.11 since there was no animation when switching to and from Freeplane in fullscreen.

**Comment by nobinajohan** [comment]
> Now it is implemented correctly. If you don't like apple, don't use apple or convince them to change their UI which I personally do not like at all.

It actually works as I wanted to be when it comes to animaton, after I press cmd-L once. But then I have to press it 3 more times to get it back. But that is quite ok. It seems like cmd-L circulate through 4 different states.

**Comment by nobinajohan** [comment]
> I do not understand what you mean by "gray frames". I am not going to look back at the 1.8.x version. Please provide all necessary screenshots and add explanations needed to understand what you mean.

I wrote: "This is how it looks in the fix: the frame is gone, but the top bar is still there".
So after pressing cmd-L once, I get this:
<img width="2560" alt="Screen Shot 2022-10-31 at 20 09 41" src="https://user-images.githubusercontent.com/75474252/199090326-7887bc42-73a5-4637-b334-88330542ff28.png">

It's really nice that the frame is gone. But the top bar (with the red, yellow, and green buttons) is still there. Is it possible to hide that as well, so it is totally white surrounding the mind map content?

**Comment by dpolivaev** [comment]
I don't have the bar with the buttons on my screen when full-screen mode is active. I use the mind map popup menu to activate/deactivate it. I do not know why you mention cmd-L.

**Comment by nobinajohan** [comment]
Just to check: I'm running "Freeplane 1.10.5-pre07". Is that the correct version?

Ok, forgot the cmd L.
But if you look at the screenshot below, you see that I have activated full screen mode via the popup menu.
But you can still see the title of the mind map at the top.
How come I get that, and not you?
I'm running MacOS 12.6.1.

<img width="2560" alt="Screen Shot 2022-11-01 at 06 14 46" src="https://user-images.githubusercontent.com/75474252/199164056-5f2c56ae-9235-4d4b-9cc2-4939e337963d.png">
