### ISSUE TITLE
Annoying LaTeX ligatures

### ISSUE THREAD

**Issue by nigredo-tori** [freeplane/freeplane#77]
![ligature](https://user-images.githubusercontent.com/5962285/30246354-c0d8be20-9621-11e7-9aae-bbfa5144822d.png)

I've found that some cyrillic character sequences get replaced when using LaTeX format. Most notably, "тс" gets replaced with "ц". This can probably be worked around, but that gets old fast, since the sequence is extremely common in Russian.

I've found a similar [issue](https://help.geogebra.org/topic/latex-text%D1%82%D1%81-in-russian) in GeoGebra. The way the bug was fixed there is not explained, but following this second point of reference and the timeline led me to this record in JLaTeXMath changelog:
> Remove ligatures info for cyrillic

It seems the issue is resolved in JLaTeXMath 1.0.5/1.0.6, but from what I can gather Freeplane uses 1.0.3. So just updating the library should fix this.

**Comment by dpolivaev** [comment]
Hi Felix, do you think we could update JLaTeXMath to the latest version? Could you check it with 1.6.x ?
Cheers, Dimitry

**Comment by fnatter** [comment]
@nigredo-tori: Thanks for reporting.
Current 1.6.x now uses jlatexmath-1.0.6. This will be part of freeplane-1.6.7.
Cheers and Best Regards,
Felix

**Comment by dpolivaev** [comment]
Current version refuses to paint a node and throws an exception from JLatexMath when the attached map is opened at the first time. After you reload the map the node is painted without problems.
[latex-bug.zip](https://github.com/freeplane/freeplane/files/1300928/latex-bug.zip)

~~~~
WARNING: Problem with command text at position 4:10
fonts/language_cyrillic.xml
org.scilab.forge.jlatexmath.ParseException: Problem with command text at position 4:10
fonts/language_cyrillic.xml
	at org.scilab.forge.jlatexmath.PredefMacroInfo.invokeID(PredefMacroInfo.java:593)
	at org.scilab.forge.jlatexmath.PredefMacroInfo.invoke(PredefMacroInfo.java:70)
	at org.scilab.forge.jlatexmath.TeXParser.processCommands(TeXParser.java:1398)
	at org.scilab.forge.jlatexmath.TeXParser.processEscape(TeXParser.java:1238)
	at org.scilab.forge.jlatexmath.TeXParser.parse(TeXParser.java:712)
	at org.scilab.forge.jlatexmath.TeXFormula.<init>(TeXFormula.java:284)
	at org.scilab.forge.jlatexmath.TeXFormula.<init>(TeXFormula.java:268)
	at org.freeplane.plugin.latex.TeXText.createTeXIcon(TeXText.java:39)
	at org.freeplane.plugin.latex.LatexRenderer.getIcon(LatexRenderer.java:90)
~~~~

**Comment by fnatter** [comment]
hi,
thanks for noticing. I think we shall file a bug against jlatexmath upstream.
I will do it this evening.

Cheers and Best Regards,
Felix

**Comment by dpolivaev** [comment]
It was because of missing dependency in gradle
https://github.com/freeplane/freeplane/commit/820920afa2c1556250ef8fbcb6990d7ab5703c57

**Comment by dpolivaev** [comment]
@nigredo-tori you can try preview version1.6.7_02 with the fix. https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

**Comment by nigredo-tori** [comment]
@dpolivaev, seems to work for me. Thank you.
