### ISSUE TITLE
ink handwriting function

### ISSUE THREAD

**Issue by mainDevgithub** [freeplane/freeplane#777]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of why you need it. Ex. When I want [...] I can not get it done because of [...]

Want to add ink handwriting function, so as to draw in the node and quickly add special symbols.

**Additional context**

**Comment by euu2021** [comment]
related request: #593 

[This](https://www.youtube.com/watch?v=EOJCSvEint8), video shows how it works on Mindjet Mindmanager (I don't remember how this feature changed in recent versions, though).
