### ISSUE TITLE
Problem opening files

### ISSUE THREAD

**Issue by reagle** [freeplane/freeplane#78]
As noted in https://github.com/caskroom/homebrew-cask/pull/38886#issuecomment-332594165

> Since upgrading to this version [1.6.7], I can no longer open mindmaps via QuickSilver launcher or `open` from the command line. It still launches FreePlane, but it starts with a new mindmap, not the one I specified.
> NOTE: this only happens if there is no FreePlane running. If the app is already running, these invocations *will* result in the specified file opening.

**Comment by reagle** [comment]
Clicking on a file.mm in explorer has the same problem too.

**Comment by dpolivaev** [comment]
Do you use Mac OS?
Which Version had you used before you upgraded?

**Comment by dpolivaev** [comment]
Check version 1.6.8_01 from https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

**Comment by reagle** [comment]
Yes, that seems to work. Thanks!
