### ISSUE TITLE
Unresponsive text box when hovering minimized node close to the bottom of the screen

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#783]
There is a text box that shows up when hovering over minimized nodes. Usually, it's responsive, i.e., it disappears if the mouse is not hovering over the minimized node. 

The bug: when this text box is touching the bottom of the screen, it stops being responsive, and I need to click in order to make it disappear:

![javaw_trNGHtsn2f](https://user-images.githubusercontent.com/77707706/198385121-0f22cb71-1a9f-4efa-b577-e90349c354ee.gif)

To me, it's relevant because I only use minimized nodes, and I'm hovering over them all the time to see the contents, so I need the text box to be responsive.

**Comment by euu2021** [comment]
Additional information: I like to keep this text box narrow (there is a setting for this), much more than in the example that I posted above, so it's not uncommon that my text boxes get tall and end up touching the bottom of the screen.

**Comment by dpolivaev** [comment]
I do not know why the tooltip disappears so quickly on your machine. On my machine, it stays until you move the mouse across some other node.

**Comment by euu2021** [comment]
I tried with a default auto.properties and the behavior is the same:

![javaw_wcJyjrlSdM](https://user-images.githubusercontent.com/77707706/198883299-a153e1c1-e06f-47be-b815-469ee41aafc6.gif)

Java version: 15.0.7
Windows 11
Freeplane-Setup-with-Java-1.10.5-pre08

**Comment by euu2021** [comment]
I noticed that this problem disappeared, now.
