### ISSUE TITLE
Why didn't to suppot to export svg file in 'Freeplane'?

### ISSUE THREAD

**Issue by c0001** [freeplane/freeplane#79]
# Hello for freeplane developer :
 > I am the one want to let the freeplane file to be the svg file.

Why or how can I export the freeplane file to the svg file.

Hope for your help!

**Comment by ldmpub** [comment]
Hi,

You can use the Freeplane's Menu: **File > Export Map > and then choose SVG image file** among the large list of available export formats which are available.

Regards,

**Comment by c0001** [comment]
I used chinese platform of the latest version of freeplane,and I have found the large list of export menu ,but just xml,wiki,html and just two picture format which are png and jpeg format.

**Comment by c0001** [comment]
And I found repeat, the export map doesn't have any svg type ,the whole type list was below:
* html
* latex
* xml
* doc about
* adoc
* png
* jpeg
* markdown
* opml
* mediawiki
* wiki about
* java about
* tji

> There's no svg type can be found.
Hope your help if you said was true that there's the svg type export support in export map.

**Comment by ldmpub** [comment]
Sorry but the list I see is not the same when running "my" Freeplane stable version 1.6.7, see for instance screen copy here #80.
I have yet no explanation. Maybe a developer has one?

**Comment by belonesox** [comment]
Confirm. I just tried binary distro of freeplane 
freeplane-1.5.21
freeplane-1.6.3
freeplane-1.6.7

SVG export is absent in all versions >=1.6 (OK in 1.5.21, absent in 1.6.3, 1.6.7)

**Comment by dpolivaev** [comment]
hello folks,

we have removed SVG and PDF exports because the library we used can not properly handle colors of the new scalable freeplane icons

Regards,
Dimitry

**Comment by c0001** [comment]
@dpolivaev 
Thanks for relying, but we (most of us in our teams) has the very high demands of svg exproting, and there's some else method to take it in with manually doing ?

Hope for your helps with the highest gratitude in -v- !

**Comment by fnatter** [comment]
hello,

PDF/SVG export is working again, see:
https://sourceforge.net/p/freeplane/discussion/758437/thread/3bf4dca5/

Cheers and Best Regards,
Felix

**Comment by dpolivaev** [comment]
Version 1.6.10_02 , https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
