### ISSUE TITLE
Menu and Icons disorder on MacOS

### ISSUE THREAD

**Issue by yusun001** [freeplane/freeplane#815]
### Discussed in https://github.com/freeplane/freeplane/discussions/814

<div type='discussions-op-text'>

<sup>Originally posted by **yusun001** November  8, 2022</sup>
The FreePlane 1.10.3 worked well until I uninstalled it, then reinstalled Freeplane-1.10.5-intel.dmg on MacOS 12.6.1
After the reinstallation, the Menu and Icons become extremely large (See screenshot below). 
Help Please! Thank you very much!

![Screen Shot 2022-11-08 at 5 43 17 PM](https://user-images.githubusercontent.com/36675329/200693162-0c3a2317-c36c-43ce-ba4d-4c09d68395ab.png)
</div>

**Comment by dpolivaev** [comment]
Please attach your auto.properties for problem investigation

**Comment by yusun001** [comment]
Problem solved. 
Delete ~/.freeplane folder first before reinstallation.
Thanks!
