### ISSUE TITLE
FP 1.11.1 01: maps too slow performing

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#822]
**Describe the bug**
I tried to run a map that normally I use in FP 1.10.05, but it is too slow in FP 1.11.1 01.
It is a small size map, in this pc I reserve 1g of memory  for FP on 8g available.

**To Reproduce**
Here in the attachment my obfuscated one

**Expected behavior**
I like to keep the same answer time I'm used in FP 1.10.5. 11.
and I like to use the new features of FP 1.11.1.

**Mind map files**
See the attachment

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11
 - Java Version: FP Java included 1.11.1 01

**Additional context**
[obfuscated~obf 2022 45.zip](https://github.com/freeplane/freeplane/files/9997019/obfuscated.obf.2022.45.zip)

**Comment by dpolivaev** [comment]
Can you please give me an example of at least one action which is slower on the new version?

**Comment by Illegit** [comment]
Just opening a branch was very slow, and more moving the nodes or adding some new nodes.
At now because I need to work with those maps I reverted to FP 1.10.5 11

**Comment by Illegit** [comment]
and got again the same speed

**Comment by Illegit** [comment]
to be clear: the correct speed as before. The movement of dragging nodes are fluid, the opening and closing of branches are quite immediate again

**Comment by dpolivaev** [comment]
Your mind map is helpful, I am going to optimize the performance in the next preview.

**Comment by Illegit** [comment]
Ok, glad to help. I'm eager to utilize your new solutions.

**Comment by dpolivaev** [comment]
Preview 1.11.1_02
