### ISSUE TITLE
Combination of top to bottom and left to right layouts causes cloud margin loss on children

### ISSUE THREAD

**Issue by abc16361** [freeplane/freeplane#823]
**Describe the bug**
A node with top to bottom layout causes top and bottom margin loss on its child cloud with left to right layout. And vice versa, a node with left to right layout, margin loss on both left and right sides of a child cloud with top to bottom layout.

**Screenshots**
![MarginLossOnCmbLayouts](https://user-images.githubusercontent.com/101362122/201523824-dc4c7830-eb35-4872-826b-745af0d69d92.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version : freeplane_bin-1.11.1-alpha-pre01.zip
 - Java Version : jdk-17_windows-x64_bin_17.0.3.msi

**Comment by abc16361** [comment]
It seems the error is more related with left to right layout, is it?
![left2right](https://user-images.githubusercontent.com/101362122/201526578-696f89ec-c356-4a41-aa44-cb941ebf900b.png)

**Comment by dpolivaev** [comment]
Please attach the mind map.
Otherwise, I have to spend time trying to reproduce your example with a pretty high likelihood of getting it wrong.

**Comment by abc16361** [comment]
Sorry, here is the map.
[LayoutTest_1.11.xx.mm.zip](https://github.com/freeplane/freeplane/files/9998330/LayoutTest_1.11.xx.mm.zip)

**Comment by dpolivaev** [comment]
Preview 1.11.1_02
