### ISSUE TITLE
Incompatibility with Freemind maps

### ISSUE THREAD

**Issue by sorenwacker** [freeplane/freeplane#829]
The info text from freemind is stored as HTML, but Freeplane just shows the raw text source. 

![image](https://user-images.githubusercontent.com/3391614/202248872-e92dc591-48e0-48a3-8a6c-85eb20b22015.png)

There also does not seem to be an option to edit this text. If there is one, it is not intuitive to find.

**Comment by dpolivaev** [comment]
It looks like a note which does not start with `<html>`. Where do you have it from? AFAIK it is not a typical note content in freemind.

And because it is a note you can edit it in the note panel. Just like in Freemind. Showing it as a tooltip is not thought for editing.
