### ISSUE TITLE
Placeholder not replaced in "New version available" message

### ISSUE THREAD

**Issue by ldmpub** [freeplane/freeplane#833]
# Describe the bug
**Placeholder not replaced in "New version available" message**
(bug seen in FP version 1.10.4 but exists since several FP versions).

* Current message displayed in FP status bar (on the bottom left corner): `New version ''{0}'' available` ❌
* Message should be: `New version ''1.10.4'' available` ✅

Hope this is clear, because I'm sorry and I missed to perform and screenshot before performing FP update 😥.

# To Reproduce 
Launch an "outdated Freeplane" with option "Check version at startup" enabled.

# Screenshots
Strings for the key `new_version_available` in Weblate for english and french [are looking fine](https://hosted.weblate.org/translate/freeplane/translation/fr/?checksum=fd87a8a95baa74ac):
![image](https://user-images.githubusercontent.com/1452146/202852618-7beb84a1-4aed-458b-8f33-6793171ae241.png)

# Desktop
 - OS: Win10
 - FP version: 1.10.4
 - Java Version:

**Comment by penn5** [comment]
I switched to English and it works.

**Comment by ldmpub** [comment]
Now solved! _(without any change performed in french translation 😋)_

![image](https://github.com/freeplane/freeplane/assets/1452146/cb7e6b91-571f-40b8-a469-d5eecb2f9ca2)

See also discussion:
* https://github.com/freeplane/freeplane/discussions/1062
