### ISSUE TITLE
When creating a new node with a script, the 'conditional formating script filter' rules are not applied to the new node.

### ISSUE THREAD

**Issue by dpolivaev** [freeplane/freeplane#843]
First side effect:
When creating a new node with a script, the 'conditional formating script filter' rules are not applied to the new node.

The new node will not **show** its correct styles:
- it may not show a conditional style that its assigned to it
- it may show a conditional style that it's not assignet to it (but was assigned to other node in the script)

This happens with script filter conditioned styles.

when unfolding/folding its parent node the format is not refreshed and  stays wrong.

when selecting the node, its format gets refreshed and shows right.

_Originally posted by @EdoFro in https://github.com/freeplane/freeplane/issues/831#issuecomment-1323900056_

**Comment by dpolivaev** [comment]
@EdoFro 
Fixed in preview 1.10.6_02, please test it.

**Comment by EdoFro** [comment]
@dpolivaev 

Tested. works perfect.
Issue has been solved and Freeplane maintains its speed.

Thanks!

**Comment by EdoFro** [comment]
bug: when moving a node, it disappears

I created new bug report https://github.com/freeplane/freeplane/issues/844

**Comment by EdoFro** [comment]
tested again with 1.10.6_03.
Works perfect.

This Issue can be closed

**Comment by EdoFro** [comment]
hi @dpolivaev,
you can close this issue as solved
