### ISSUE TITLE
FP v1.10.6_02: when moving a node it disappears

### ISSUE THREAD

**Issue by EdoFro** [freeplane/freeplane#844]
**Describe the bug**
When moving a node it disappears.
when moving it with the mouse (drag'n drop) or with the keyboard (ctrl + arrows) it disapears from the map.

But when the user folds and unfolds its parent node, then is visible again. (Sometimes)

**To Reproduce**
1. just move a node
2. See error

For example, this map had multiple nodes and I moved them inside the map and they disappear:

![image](https://user-images.githubusercontent.com/35700575/203877594-56f11cb2-8be7-406b-827d-9b86c99b5ec1.png)

I executed this script:
```groovy
root.findAll()
```

and it returned this:

`Result: [(Node) New Mindmap, (Node) ccc, (Node) hola, (Node) qq, (Node) ee, (Node) rr, (Node) xxx, (Node) bbb, (Node) aaa, (Node) ddd, (Node) ww]`

You can see that the nodes are still there, but they are no visible anymore.

**Comment by dpolivaev** [comment]
Preview 1.10.6_03

**Comment by EdoFro** [comment]
Tested. 👍🏼 

thanks!
