### ISSUE TITLE
Possibility to rename (grouped) map view tabs

### ISSUE THREAD

**Issue by EdoFro** [freeplane/freeplane#865]
**Is your feature request related to a problem? Please describe.**
When grouping multiple views in one tab, the name (text) in the new tab is just the concatenation of all different views (¿maps?) included in it. Sometimes they get very long to be on a tab and a shorter description would be more useful.

look for example at this image:

![image](https://user-images.githubusercontent.com/35700575/206038239-73090cd4-0b18-461b-8b07-def503b1bf0e.png)

### I would like the ability to right click on any view tab (or at least on any grouped view tab) and rename the tab (edit its text)

Thanks in advance,

edo

**Comment by EdoFro** [comment]
I tried to look if it could be easily done and have found that the appending routine is part of the external docking windows library:

https://github.com/ebourg/infonode/blob/672cc6b8323525bc5c1caad0c4c39e8ea3219828/src/net/infonode/docking/title/SimpleDockingWindowTitleProvider.java#L56

**Comment by euu2021** [comment]
Is it bad news? Being able to change the name of the tab would be very useful.

**Comment by EdoFro** [comment]
I tried to make an add-on to solve this issue. I couldn't.

I'm going to post here everything I learned about the docking windows in Freeplane.
Maybe it may help sombody who wants to gets this feature too. Or maybe in the future I learn some more and can do this myself.

BR
edo

**Comment by EdoFro** [comment]
# About docking windows in Freeplane

Freeplane uses the java library `net.infonode.docking` to manage the mindMaps windows.

- About Infonode
   - net.infonode is a relative old project
   - Its homepage is no longer available
   - I didn't found much information about it or example codes online
   - Infonode's unofficial repository in Github
      - [https://github.com/ebourg/infonode](https://github.com/ebourg/infonode)
   - Infonode's javadoc in sourceforge
      - [net/infonode/docking](https://hipo.sourceforge.net/javadoc/net/infonode/docking/package-summary.html)
      - [overview-summary](https://hipo.sourceforge.net/javadoc/overview-summary.html)

**Comment by EdoFro** [comment]
# Testing how to use Infonode with groovy scripts

Groovy scripts have no direct access to the infonode library. This can be solved by two different ways:

1. adding its folder in preferences
   - `Preferences…->Plugins->Scripting->Script classpath`
1. Saving a copy of the .jar file in `<userDirectory>/lib/`

I decided to do the second one.

- the library file is `idw-gpl-1.6.1.jar`
- You can find this file in:
   - the Freeplane's installation folder
   - in my case (windows):
      - `C:\Program Files\Freeplane\core\org.freeplane.core\lib`
- You can also download the file from Freeplane's repository:
   - [github: freeplane/lib](https://github.com/freeplane/freeplane/tree/1.11.x/freeplane/lib)

After saving it I had to restart Freeplane

# Test 1: Changing the text to a window tab

## method windowTab.setText

- The method to change the title text in a window tab is:
   - windowTab.setText(java.lang.String text)<br>inherited from class TitledTab
- associated javadocs:
   - [Class WindowTab](https://hipo.sourceforge.net/javadoc/net/infonode/docking/WindowTab.html)
   - [Class TitledTab](https://hipo.sourceforge.net/javadoc/net/infonode/tabbedpanel/titledtab/TitledTab.html)
   - [method setText](https://hipo.sourceforge.net/javadoc/net/infonode/tabbedpanel/titledtab/TitledTab.html#setText(java.lang.String))

<details><summary><h2>Testcode 1: changing the tab text under the mouse</h2></summary>

The folowing script changes the tab text under the mouse arrow.

- It changes its text to "TEST_A"
- You have to execute the script using a keyboard shortcut after placing the mouse arrow on the window tab you want to change.
- video:

https://github.com/freeplane/freeplane/assets/35700575/5ae1c499-1dc6-4f29-b60f-31863dc69f0f

 

Code: **'change tab text - tab under mouse'**

```groovy
import java.awt.Component
import java.awt.Point
import java.awt.Window

import javax.swing.JComponent
import javax.swing.SwingUtilities

import net.infonode.docking.WindowTab

//get component under mouse
JComponent component = (JComponent) getComponentUnderMouse()

//get windowTab
def windowTab

//Option A: I tried to get the windowTab using getAncestorOfClass, but I couldn't. I don't know how it works.
//windowTab = SwingUtilities.getAncestorOfClass(WindowTab.class, component)
//println windowTab

//Option B: It climbs through the components tree until it get to the windowTab.
// I should use toString(), because as classes they wouldn't match.
windowTab = component
while(windowTab && (windowTab.class.toString() != WindowTab.toString())){
    windowTab = windowTab.parent
}

//set new text to tab label
windowTab.setText('TEST_A')

//---------------- methods ---------------------------------

def getComponentUnderMouse(){
    for (Window window : Window.getWindows()) {
        Point mousePositionA = window.getMousePosition(true)
        if(!mousePositionA)continue
        def compo = window.getLayeredPane()
        Point mousePosition
        try {
            mousePosition = SwingUtilities.convertPoint(window,mousePositionA,compo)
        } catch (e){
            logger.warn('menuAction',e)
            logger.warn('window:  ' + window.toString())
            logger.warn('mousePosition:  ' + mousePositionA.toString())
            logger.warn('LayeredPane:  ' + compo.toString())
            throw e
        }
        if (mousePosition != null) {
            Component componentUnderMouse = SwingUtilities.getDeepestComponentAt(compo, (int) mousePosition.x,
                (int)  mousePosition.y);
            return componentUnderMouse
        }
    }
}
```

</details>
<details><summary><h2>Testcode 2: changing the tab text of the selected first level window</h2></summary>

The folowing script changes the tab text of the selected window (or window group)

- It changes its text to "TEST_B"
- video:

https://github.com/freeplane/freeplane/assets/35700575/c57d58dd-395d-47e4-9011-7b077dbcf173



Code: **'change tab text - selected first level window'**

```groovy
import javax.swing.SwingUtilities
import net.infonode.docking.title.DockingWindowTitleProvider;
import net.infonode.docking.DockingWindow;

def rootWindow = SwingUtilities.getRootPane(ui.frame).contentPane.components[0].components.find{it.class.name == 'net.infonode.docking.RootWindow'}

def tabWindow =  rootWindow
do{
    tabWindow = tabWindow.getLastFocusedChildWindow()
} while (tabWindow && !tabWindow.insideTab())
if(!tabWindow) {
    def msg = 'no window selected'
    c.statusInfo = msg
    return msg
}

def tabWindowTab = tabWindow.getTab()

if(tabWindowTab.showing ) {
    tabWindowTab.setText('TEST_B')
} else {
    def msg = "selected view "${tabWindow.title}" is not inside a group of tabs"
    c.statusInfo = msg
    return msg
}
```

</details>

**Comment by EdoFro** [comment]
# Text stays?... no  :(

There are different events that makes that the Tab text gets refreshed and returns to its original value.

For example:

- selecting a child window
- draging window tabs
- when saved map is changed (title gets a * at its end)

In the following video you can see that the renamed "TEST_B" tab gets its original value when one of its childwindows is selected


https://github.com/freeplane/freeplane/assets/35700575/77e29435-e129-4fc1-9233-0fc55e401198



# How does this title updating works?

These different events call the **DockingWindow.getTitle()** method from the infonode library.

- This method then calls the **SimpleDockingTitleProvider.getTitle()** method that has the logic that builds the title from the window's name or, if it has child windows, concatenating its child windows titles.
- Here is the code taken from its github repository:
   - [SimpleDockingWindowTitleProvider.java#L50-L70](https://github.com/ebourg/infonode/blob/672cc6b8323525bc5c1caad0c4c39e8ea3219828/src/net/infonode/docking/title/SimpleDockingWindowTitleProvider.java#L50-L70)


Code: **'SimpleDockingWindowTitleProvider.getTitle(DockingWindow window)'**

```java
  public String getTitle(DockingWindow window) {
    StringBuffer title = new StringBuffer(40);
    getTitle(window, title);
    return title.toString();
  }

  private void getTitle(DockingWindow window, StringBuffer title) {
    if (window == null)
      return;
    else if (window instanceof View) {
      if (title.length() > 0)
        title.append(", ");

      title.append(((View) window).getViewProperties().getTitle());
    }
    else {
      for (int i = 0; i < window.getChildWindowCount(); i++) {
        getTitle(window.getChildWindow(i), title);
      }
    }
  }
```



# but there is a way ...

**DockingWindow.getTitle()** only calls this concatanating method if the window has not its own TitleProvider!!

- You can see here in its code that it looks if the window has its own title provider, and if not, uses SimpleDockingTitleProvider
   - [DockingWindow.java#L966-L969](https://github.com/ebourg/infonode/blob/672cc6b8323525bc5c1caad0c4c39e8ea3219828/src/net/infonode/docking/DockingWindow.java#L966-L969)

Code: **'DockingWindow.getTitle()'**

```java
  public String getTitle() {
    DockingWindowTitleProvider titleProvider = getWindowProperties().getTitleProvider();
    return (titleProvider == null ? SimpleDockingWindowTitleProvider.INSTANCE : titleProvider).getTitle(this);
  }
```

# The solution is to asign a title provider to the window with the logic we want

**Comment by EdoFro** [comment]
But I haven't been able to do that

**Comment by EdoFro** [comment]
# looking at other use cases

I searched for some code examples in Github:

- [github code search: "getWindowProperties().setTitleProvider"](https://github.com/search?q=getWindowProperties%28%29.setTitleProvider&type=code)

and found an example that I thought it was easy to implement as a test:

Code: **'setTitleProvider example'**

```java
editingTab.getWindowProperties().setTitleProvider(new DockingWindowTitleProvider() {
        @Override
        public String getTitle(final DockingWindow arg0) {
                return "Edit";
        }
});
```

- source:
   - [ReterasModelStudio .... MainPanel.java#L1652-L1657](https://github.com/Retera/ReterasModelStudio/blob/2b7c9f0c223874381074f4e04f82442f03a8ec53/matrixeater/src/com/matrixeater/src/MainPanel.java#L1652-L1657)

# javadoc info about the used classes

- [Interface DockingWindowTitleProvider](https://hipo.sourceforge.net/javadoc/net/infonode/docking/title/DockingWindowTitleProvider.html)
- [Class DockingWindow](https://hipo.sourceforge.net/javadoc/net/infonode/docking/DockingWindow.html)
- method
   - [getWindowProperties](https://hipo.sourceforge.net/javadoc/net/infonode/docking/DockingWindow.html#getWindowProperties())
- [Class DockingWindowProperties](https://hipo.sourceforge.net/javadoc/net/infonode/docking/properties/DockingWindowProperties.html)
- methods
   - [getTitleProvider](https://hipo.sourceforge.net/javadoc/net/infonode/docking/properties/DockingWindowProperties.html#getTitleProvider())
   - [setTitleProvider](https://hipo.sourceforge.net/javadoc/net/infonode/docking/properties/DockingWindowProperties.html#setTitleProvider(net.infonode.docking.title.DockingWindowTitleProvider))

**Comment by EdoFro** [comment]
# Test 2: Asigning a custom title provider to the window

I tried to add to one my script the example code

it ended this way:

Code: **'change tab text and titleProvider - selected first level window'**

```groovy
import javax.swing.SwingUtilities
import net.infonode.docking.title.DockingWindowTitleProvider;
import net.infonode.docking.DockingWindow;

def rootWindow = SwingUtilities.getRootPane(ui.frame).contentPane.components[0].components.find{it.class.name == 'net.infonode.docking.RootWindow'}

def tabWindow =  rootWindow
do{
    tabWindow = tabWindow.getLastFocusedChildWindow()
} while (tabWindow && !tabWindow.insideTab())
if(!tabWindow) {
    def msg = 'no window selected'
    c.statusInfo = msg
    return msg
}

def tabWindowTab = tabWindow.getTab()

if(tabWindowTab.showing ) {
    tabWindowTab.setText('TEST_C')
} else {
    def msg = "selected view "${tabWindow.title}" is not inside a group of tabs"
    c.statusInfo = msg
    return msg
}

println tabWindow.class

tabWindow.getWindowProperties().setTitleProvider(new DockingWindowTitleProvider() {
        @Override
        public String getTitle(final DockingWindow arg0) {
                return "TEST_D";
        }
});
```

but it throwed this exception:

Code: **'error'**

```console
Exception thrown

groovy.lang.MissingMethodException: No signature of method: net.infonode.docking.properties.DockingWindowProperties.setTitleProvider() is applicable for argument types: (ConsoleScript5$1) values: [ConsoleScript5$1@70821ba6]
Possible solutions: setTitleProvider(net.infonode.docking.title.DockingWindowTitleProvider), getTitleProvider()

    at ConsoleScript5.run(ConsoleScript5:31)

    at jdk.internal.reflect.GeneratedMethodAccessor291.invoke(Unknown Source)

    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

And I don't know how to deal with that. I think it's a problem between java and groovy.

If somebody has any clue, please tell me.

**Comment by EdoFro** [comment]
here is another example. The resulting class of the object doesn't match the needed DockingWindowTitleProvider class.

```groovy
import net.infonode.docking.properties.DockingWindowProperties
import net.infonode.docking.title.DockingWindowTitleProvider
import net.infonode.docking.DockingWindow



def myProps = new DockingWindowProperties()

myProps.setTitleProvider(new DockingWindowTitleProvider() {
                           @Override
                           public String getTitle(final DockingWindow arg0) {
                                    return "Edit";
                           }
                  })

def msg =  myProps.getTitleProvider().class.toString()
c.statusInfo = msg
return msg
```

it returns `'class ConsoleScript0$1'`

**Comment by dpolivaev** [comment]
@EdoFro Why are you trying to implement it as an add-on? Could you consider developing it directly in the Freeplane code base and sending a pull request?  If I can help you let me know.

**Comment by EdoFro** [comment]
Hi Dimitry,
> Why are you trying to implement it as an add-on? 

I have three reasons (maybe not good ones) to always think any feature as an add-on:
- I haven't been able to install the developing enviroment properly. I always get lost and don't know what to do.
- I feel that errors in addons are not so important. They can fail and that doesn't affect Freeplane itself. So I feel free to play and learn by doing (and failing).
- Everything that is added to Freeplane requires maintenance afterwards. I don't know if I will be able to do that (technically and timely), so it will end  meaning more work for other developers (you).

> Could you consider developing it directly in the Freeplane code base and sending a pull request?

I think in this case, it may be a good project to learn how to implement changes in Freeplane itself.

I will try again to set my developing enviroment properly.

> If I can help you let me know.

Thank You very much, I will certainly need help and supervision.


Next time I have some free time I will try. 
I let you know.

Thanks,
edo

**Comment by dpolivaev** [comment]
Hi Edo, for me helping you to set up your development environment and taking care of improving, integrating, and maintaining your pull requests can be better and more fun than coding everything on my one.

**Comment by euu2021** [comment]
> # About docking windows in Freeplane
> Freeplane uses the java library `net.infonode.docking` to manage the mindMaps windows.
> 
> * About Infonode
>   
>   * net.infonode is a relative old project
>   * Its homepage is no longer available
>   * I didn't found much information about it or example codes online
>   * Infonode's unofficial repository in Github
>     
>     * https://github.com/ebourg/infonode
>   * Infonode's javadoc in sourceforge
>     
>     * [net/infonode/docking](https://hipo.sourceforge.net/javadoc/net/infonode/docking/package-summary.html)
>     * [overview-summary](https://hipo.sourceforge.net/javadoc/overview-summary.html)

The Infonode codebase is a pleasure to explore, because there are many comments explaining how things work. Even I can understand the general idea 😄

I wish I could learn more about Java, but my time will be so short in the next couple of months 😫

**Comment by EdoFro** [comment]
> Hi Edo, for me helping you to set up your development environment and taking care of improving, integrating, and maintaining your pull requests can be better and more fun than coding everything on my one.

@dpolivaev 

Hi Dimitry,
I'm now trying (and failing) again in setting up the development environment.
I'm going to create a Discussion Topic to explain my problems and collect the whole information. Maybe it can be useful to update/improve the current documentation. #1321

BR

edo

**Comment by EdoFro** [comment]
Hi @dpolivaev,
I made some changes to Freeplane's source code trying to implement this idea.

The branch with the changes is here:
https://github.com/EdoFro/freeplane/tree/test_edo

And [these are the changes](https://github.com/freeplane/freeplane/commit/28288fa31b99085004a131edfd8058fba81b4099)

1. added a CustomTitleProvider class
2. some changes to MapViewDockingWindows.java:
    - added a PopupMenu to the window tabs, that changes the tab's name and adds the customTittleProvider to the window.

Pendings:
1. When changing the windows layout inside the tab (from splitWindow to tabWindow or back) changes the window --> looks like it resets the title. I don't know how to handle this.
2. The modified names from the tabs get lost when closing Freeplane. They are not saved anywhere. Maybe for the next time.
3. the displayed text is hardcoded. It must be refactored to use textUtils. (I wanted You to see this changes before me worrying about that)

In my opinion this is an improvement. It is something I will use.

Can You please look at it and tell me your opinion and next steps?

(Today we have a family meeting here at home, so I won't be able to look a this)

Regards,

edo

**Comment by dpolivaev** [comment]
Hi Edo, please create a pull request (there is a GitHub button for it). It helps me in analyzing and commenting on your submission.

**Comment by dpolivaev** [comment]
I always need pull requests for reviewing and commenting on submissions. I could create a pull request from your branch (there is a button for it on GitHub). Unfortunately now I appear as the author of the Pull Requests and therefore you are not getting my comments. But you can still look at them at https://github.com/freeplane/freeplane/pull/1353#pullrequestreview-1585958198

**Comment by EdoFro** [comment]
I think this can be closed now
