### ISSUE TITLE
Dragging inside a node does not move.

### ISSUE THREAD

**Issue by abc16361** [freeplane/freeplane#872]
**Describe the bug**

Dragging inside a node, not via the node handle,  can move it and attach to another node, but this action does not work on the new version fp-1.11.1-04. 

**Mind map and log files**

[1.11.1.04.map-log.zip](https://github.com/freeplane/freeplane/files/10187490/1.11.1.04.map-log.zip) ( log shows errors )

**Screenshots**
![dragging](https://user-images.githubusercontent.com/101362122/206509941-ee33a722-bdfd-4d08-b363-f6124158ca1d.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - Version:  fp-1.11.1-04
 - Java Version: jdk-17_windows-x64_bin_17.0.3.msi

**Comment by dpolivaev** [comment]
Fixed in preview 1.11.1_05
