### ISSUE TITLE
No visual indication of focused panel

### ISSUE THREAD

**Issue by steveatmaat** [freeplane/freeplane#877]
**Describe the bug**
In a previous version, when the user hit Ctrl-Shift-, to put the focus on the note editor, the note editor panel became surrounded by a blue rectangle. When the focus went back to the main panel, the tab had a blue underline. In versions 1.10.5 and 1.10.6 these indicators are gone.

**To Reproduce**
1. Click on Ctrl-Shift-, to focus the note editor panel.

**Expected behavior**
A blue rectangle should surround the panel to show that it is focused.

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version 22H2
 - Java Version 15.0.7

**Additional context**

**Comment by dpolivaev** [comment]
Please try to use different look-and-feels which you can change at Preferences…->Appearance->Look and feel->Look and Feel. If all of them do not work as you expect please upload screenshots with the old and the new freeplane versions so that iI can grasp the difference.

**Comment by steveatmaat** [comment]
Thanks. I see that the Flat IntelliJ look-and-feel is what I wanted. My mistake. Not a bug.

**Comment by ldmpub** [comment]
Maybe this issue can be marked as "Closed"? adding final comment 
> solve by changing the look-and-feel to `Flat IntelliJ`

**Comment by steveatmaat** [comment]
This was user error, not a bug. The visual UI element I had seen previously is in a couple of the look-and-feels.
