### ISSUE TITLE
Small UI font size with Java 11

### ISSUE THREAD

**Issue by githubinator** [freeplane/freeplane#887]
Hi, 

I installed freeplane 1.10.6 ([Freeplane-Setup-1.10.6.exe](https://sourceforge.net/projects/freeplane/files/freeplane%20stable/Freeplane-Setup-1.10.6.exe/download)) on Windows 10.
I use Java OpenJDK 11.0.2.

The menu font is very tiny. I tried to change the size under "Werkzeuge" -> "Einstellungen" -> "Aussehen" -> "Menü-Schriftgröße". It does not have any effect (I restarted freeplane after changes).

Help is very welcome, because the font is not easy to read for me.

Thanks

**Comment by euu2021** [comment]
Please, take a look at #801 

And try the solutions at #740, #505 and #345

**Comment by githubinator** [comment]
Thank you.
I tried the tip of @walmar in https://github.com/freeplane/freeplane/issues/505
It works for me so far. But it is just a workaround, the issue itself should be fixed (there is no need for changing a font size which does not have any effect).

**Comment by dpolivaev** [comment]
Please upload your auto.properties containing the configuration where you see the small font size for analysis.

**Comment by githubinator** [comment]
Where do I find auto.properties?

**Comment by dpolivaev** [comment]
In the directory opened by Tools->Open user directory

**Comment by githubinator** [comment]
This is it, which I was using last. The only change since Dec 13 was the font size.

**Comment by githubinator** [comment]
I can't see that I uploaded anything...

**Comment by dpolivaev** [comment]
Zip it, otherwise the upload is not accepted by GitHub

**Comment by dpolivaev** [comment]
And give me some time, I usually work on Freeplane only during the weekend

**Comment by githubinator** [comment]
[auto.properties.zip](https://github.com/freeplane/freeplane/files/10237476/auto.properties.zip)
Now it should work.

**Comment by dpolivaev** [comment]
I checked it. The problem occurs under Windows OS using Java 11 but not with Java 15.
I restored previous manual settings for Java versions below Java 15.

**Comment by dpolivaev** [comment]
Try version 1.10.6u1 available in https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

**Comment by githubinator** [comment]
Perfect, thank you!
