### ISSUE TITLE
Render the formulas only but not the whole branch

### ISSUE THREAD

**Issue by Edenharder** [freeplane/freeplane#89]
Is it possible to use [jlatexmath](https://github.com/opencollab/jlatexmath) only to render the formulas in the branch but not the whole branch? Because the text rendered by `jlatexmath` is in the different style with the normal text.

**Comment by fnatter** [comment]
Hello Edenharder,

I'm not sure I understand you. If you want to render _all_ nodes using jlatexmath, do:
- Format->Manage Styles->Edit styles
- select Default style
-> Properties panel/Tools panel->Core text->Format=LaTeX
- File->ok

If you want to render only formulas using jlatexmath, but have the same font as normal nodes,
use \textsf{...} in the formulas.

Cheers and Best Regards,
Felix

**Comment by Edenharder** [comment]
Thanks! 
> If you want to render only formulas using jlatexmath, but have the same font as normal nodes
This is indeed what I want, and `use \textsf{...} in the formulas` is exactly one solution. But what if the font of the normal node is not SansSerif?

Happy Christmas!

**Comment by fnatter** [comment]
Hello Edenharder,

you need to pick a Freeplane font that can be matched with a jlatexmath font.
To my knownledge that is just "latex roman/serif" and "latex sans-serif". So either:
- use the default jlatexmath font and [use the computer modern font in Freeplane](https://tex.stackexchange.com/questions/8308/make-ms-word-document-look-like-it-has-been-typeset-in-latex)
- use \textsf{...} in jlatexmath nodes and use the default (or another sans-serif) font in Freeplane

Cheers and Best Regards,
Felix

**Comment by Edenharder** [comment]
But I'm curious why it's not possible to just render the  some texts in a branch, but not the whole branch. For example, we can define the syntax to imply which texts to be rendered with jlatexmath,
```
text not rendered {\latex text rendered and maybe $formulas$}.
```
It will be more flexible.

I know there is no solution currently, so it's just a suggestion for the developers.

All the best.

**Comment by fnatter** [comment]
hi Edenharder.

now I understand what you mean by branch (in Freeplane/mindmapping, we refer to branch as a
node and all its subnodes).

The reason we're not doing "inline latex" is that jlatexmath allows to render LaTeX content
as a Swing unit (Icon IIRC), so it is much more work to merge JLabels (plain text) and JLaTeXMath
icons together. I think it would be doable with some effort, but we have no one working on it.

Cheers and Merry Christmas,
Felix
