### ISSUE TITLE
the layout "top to bottom, both sides" is misaligned

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#898]
Notice that, when the "both sides" version is selected, edges come from the side; but, when the "right side" version is selected, the edges come from the bottom:

![image](https://user-images.githubusercontent.com/77707706/208531269-5669b2ac-bea9-4eba-bc2a-57bbcd9288c1.png)

Shouldn't the behavior be the same on both cases?

**Comment by dpolivaev** [comment]
fixed
