### ISSUE TITLE
REGEX-based conditions in conditional formatting disappear

### ISSUE THREAD

**Issue by RomainTT** [freeplane/freeplane#91]
1. I open a .mm file.
2. I create a new conditional formatting, with a regular expression as condition.
3. After validating, the conditional formatting is correctly applied on my map.
4. I save and close the file.
5. I re-open the file. The conditional formatting has been corrupted ! My condition is not a REGEX anymore but is set on "always". My REGEX just disappeared. But when I read the .mm file in a text editor, the REGEX is still there in the ```<conditional_styles>``` tag. It is like Freeplane does not recognize this condition anymore.

**Comment by dpolivaev** [comment]
I can not reproduce the behavior. Which regular expression have you entered and for which filter? Attach a filter editor screen shot.

**Comment by RomainTT** [comment]
I'm on Freeplane 1.2.23 (Sorry my configuration is French.)
edit: I will try with recent versions of Freeplane. I didn't notice I had an old version.

So, here is the screenshot when I write the conditional formatting with the regular expression. When I click on "validate" it works perfectly.

![capture du 2018-01-11 11 59 46](https://user-images.githubusercontent.com/12847715/34822496-73f49d5c-f6c7-11e7-8193-e381f014d132.png)

Then I save the file, close it, and re-open it. And here is what I find when I open the conditional formatting again : the regular expression disappeared, and my format is set on "always".

![capture du 2018-01-11 12 00 52](https://user-images.githubusercontent.com/12847715/34822505-7ce2786c-f6c7-11e7-9abe-e84316ecfd97.png)

**Comment by RomainTT** [comment]
I updated Freeplane to version **1.6.12** and the problem disappeared. Sorry for for the issue.
