### ISSUE TITLE
Minor bug: Node details have wrong background color that don't seem changeable

### ISSUE THREAD

**Issue by chaostang** [freeplane/freeplane#913]
**Describe the bug**
The node details have black background in the light-theme template ```light_nord_template.mm```. What's more, the triangle that should enable me to fold the node details is white, which is completely invisible in the light-theme background. I suspect this template is mixed up with the dark version.

Also, it would be nice to be able to change the background of the node details. However, I did not find where to change it -- neither the format panel nor ```edit node details in dialog``` has such an option, and the ```Help``` menu has not been very helpful regarding this.

**Screenshots**
<img width="323" alt="image" src="https://user-images.githubusercontent.com/32127688/209935171-3a69e210-d6e1-4eed-816a-13027348844f.png">
<img width="764" alt="image" src="https://user-images.githubusercontent.com/32127688/209936346-78dba4f9-2ec9-4b22-8370-b8454aa02c7d.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6
 - Version 1.10.6
 - Java Version 15.0.8

**Comment by macmarrum** [comment]
The look of node details is controlled by a style called `Details`. Please see https://docs.freeplane.org/user-documentation/styles.html#style-editing

The fold/unfold triangle is the color of Details text; white text = white triangle.

You can create your own version of `light_nord_template.mm` (with a different `Details` background and text colors) and then save it to `User templates` -- see also https://docs.freeplane.org/user-documentation/templates.html#create-a-new-map-from-a-template

**Comment by chaostang** [comment]
Ah yes, I see. I had been looking in the wrong places. Thanks!
