### ISSUE TITLE
Add toolbar icons for text alignment

### ISSUE THREAD

**Issue by sifran-github** [freeplane/freeplane#918]
New toolbar icon for text alignment.

The icon on the menu will show the alignment of the selected node.
When pressed, will show options to select from.

Location: close to the font size option.

Note that no text is needed, keep it just a small icon. text can be written just inside a tooltip.

something like this:
![image](https://user-images.githubusercontent.com/5730355/210336835-ecce9990-c69e-4dd3-808a-9e85303257b2.png)

**Comment by macmarrum** [comment]
The related actions are already available in Freeplane. The main toolbar can be customized. Putting these two together and you can "easily" add the buttons yourself.

1. Copy the file `Freeplane-install-dir/resources/xml/mindmapmodemenu.xml` (on Windows it's usually `C:\Program Files\Freeplane\resources\xml\mindmapmodemenu.xml`) and paste it in `<user-dir>/resources/xml/`. You can use `Tools->Open user directory` to get to `<user-dir>`. You might need to create the `resources` and `xml` directories.
2. Add your entries to the copied `mindmapmodemenu.xml`, picking the place where you want them. You might need to play with the parameters a bit
```xml
<Entry name="TextAlignAction.LEFT" />
<Entry name="TextAlignAction.CENTER" />
<Entry name="TextAlignAction.RIGHT" />
```

Here's an example that works in my Freeplane installation: 
[mindmapmodemenu-TextAlign.zip](https://github.com/freeplane/freeplane/files/10336592/mindmapmodemenu-TextAlign.zip)

**Comment by sifran-github** [comment]
Nice... thanks @macmarrum  i didn't know that you can edit the toolbars.

The entries you wrote added these buttons:
![image](https://user-images.githubusercontent.com/5730355/210365043-b18822f3-c6b4-46a1-ad57-d4714c04fa11.png)

It is also nice that you can "reset" the state by clicking on an icon if its active.

I still think that some version should be included as default, either 3 icons, or 1 icon with a dropdown menu.

**Comment by sifran-github** [comment]
I think this feature was implemented and therefore this issue can be closed.
