### ISSUE TITLE
"Goto next node(fold)" not working on filtered map

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#923]
**Describe the bug**
`Goto (next|previous) node(fold)` is not working on filtered maps.

**To Reproduce**
[Video](https://user-images.githubusercontent.com/10260832/210759799-20e2a3dd-bed8-4d8c-8efa-2440ebbf6fb2.mp4)

**Map file**
[Mindmap.zip](https://github.com/freeplane/freeplane/files/10351297/Mindmap.zip)

**Version**
1.11.1 alpha

**Comment by dpolivaev** [comment]
Unfortunately, your filter settings are not visible on the video because it hides an essential part of the filter toolbar.
For me, it looks like the node can not be unfolded because the filter hides the child nodes of node 1.

**Comment by theelectricsoul** [comment]
Hello 
I just tested again. I can unfold the branch below node "1" using the mouse and space key. So I suppose there is no filter active when I can do that :)

**Comment by theelectricsoul** [comment]
![image](https://user-images.githubusercontent.com/10260832/211169534-cae573fc-bbfc-4f8a-81b7-e2cf4fbba79d.png)
