### ISSUE TITLE
Note editor: Font size is fixed after changing the fontssize

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#935]
Hello

If you change the fontsize within the note editor, then the font size will no longer inherit the font size below the cursor. 

See [video](https://user-images.githubusercontent.com/10260832/211546623-69bdb834-0a9a-419f-b846-a7962a8d5d29.mp4)

[New Mindmap.zip](https://github.com/freeplane/freeplane/files/10382548/New.Mindmap.zip)

**Version**
1.11.1 alpha

**Comment by dpolivaev** [comment]
Preview 1.11.1_07
