### ISSUE TITLE
Conditional Styles for Map: Cannot Delete Default "Always" Rule

### ISSUE THREAD

**Issue by 7enderhead** [freeplane/freeplane#937]
**Describe the bug**
- When creating a new conditional style for a map, there exists a default "Always" rule, which cannot be deleted or manipulated.
- A newly created rule will therefore match all nodes.

**Expected behavior**
- "Always" rule can be deleted.

![image](https://user-images.githubusercontent.com/339726/212336563-2a8f193b-7781-40b3-8375-b28998353ef1.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Mint 20.3
 - Java Version
```
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)
```

![image](https://user-images.githubusercontent.com/339726/212336127-411cdf48-4de1-49ef-b65b-dfe939d6762b.png)

**Comment by dpolivaev** [comment]
How does it bother you? Why is it bad?

**Comment by 7enderhead** [comment]
Sorry, my misunderstanding the GUI concept here. I thought all filter rules in this list are being applied to a rule, but it turns out you have to double-click one and this one is active then. (The questions remains how to ever remove unwanted old filter rules.)

**Comment by dpolivaev** [comment]
I think the most rules in the list are just shown for reference until you close the program and they are not saved with the map
