### ISSUE TITLE
Regression: Impossible to drop as child

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#940]
In Freeplane-Setup-with-Java-1.11.1-alpha-pre06, it's impossible to drop a node as child:

![javaw_VRtzdex9KF](https://user-images.githubusercontent.com/77707706/212492819-c330cf13-6674-4c2d-a727-3b9e8e95f116.gif)

[bug drop.zip](https://github.com/freeplane/freeplane/files/10418689/bug.drop.zip)

**Comment by dpolivaev** [comment]
Preview 1.11.1_07
