### ISSUE TITLE
Layouts  icons disappearing when resizing the sidebar

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#941]
Notice how the selected layout icon disappears:
![XfyNBOmYb4](https://user-images.githubusercontent.com/77707706/212496923-307f0f38-7c1d-4488-9f15-3107d685fd62.gif)

Freeplane-Setup-with-Java-1.11.1-alpha-pre06

**Comment by dpolivaev** [comment]
Preview 1.11.1_07
