### ISSUE TITLE
Juxtaposition when using horizontal layouts with zero base distance

### ISSUE THREAD

**Issue by euu2021** [freeplane/freeplane#942]
Zero base distance works fine when using vertical layouts:

![image](https://user-images.githubusercontent.com/77707706/212498100-b8850505-0189-4612-92b0-039356d0372c.png)

But it results in juxtaposition when using horizontal layouts:

![image](https://user-images.githubusercontent.com/77707706/212498118-105a97ae-c27a-45c6-badc-9457fcb0b132.png)

Freeplane-Setup-with-Java-1.11.1-alpha-pre06

[bug position.zip](https://github.com/freeplane/freeplane/files/10418878/bug.position.zip)

**Comment by dpolivaev** [comment]
Yes, I know. Unfortunately I can not easily fix it because it arises from the fact that default gaps are different in case of vertical and horizontal layout, but all values are just added to them. So although the problem does not look hard it has no solution at all.

Can you accept it?

**Comment by euu2021** [comment]
I see, thanks

**Comment by euu2021** [comment]
I noticed that, no matter how "tall" the nodes are, the juxtaposition only happens when the base distance is below (around) 6 points:
![image](https://user-images.githubusercontent.com/77707706/212563188-79037af1-5d87-4275-9cab-6e27305a709f.png)

So, in my noob mind, I would think that 6 points of the horizontal layouts is equivalent to 0 points of vertical layouts; so the software could make that conversion (adding 6 points) when changing the layout from horizontal to vertical, and vice versa. 

I don't know if what I'm saying makes any sense, though.
