### ISSUE TITLE
FP 1.11.1 pre 06

### ISSUE THREAD

**Issue by Illegit** [freeplane/freeplane#944]
**Describe the bug**
with the new layout I experienced some troubles:
1) space to fold/unfold doesn't work anymore
2) not possible to drag with mouse nodes in some position with reference to other nodes; eg: as children

**Mind map files**
If possible, upload a zipped mind map file where the problem occurs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]Windows
 - Version [e.g. 22] 11
 - Java Version FP java embedded

**Additional context**

**Comment by dpolivaev** [comment]
With this bug report I experienced some troubles:

1. it contains more than one bug description in just one issue
2. it contains no example mind map
3. I can not confirm that space to fold/unfold does not work

I have fixed issues with drag and drop in preview 1.11.1_07 (I am uploading it later today).

Please submit new bug report and attach an example mind map if you still see any bugs.

**Comment by Illegit** [comment]
OK
