### ISSUE TITLE
Filter by date fails

### ISSUE THREAD

**Issue by macmarrum** [freeplane/freeplane#945]
Expected: node 2023-01-01 is highlighted
Actual: no node is highlighted
![2023-01-15_19,27,24](https://user-images.githubusercontent.com/7197131/212560042-f7996734-a628-4ccf-a579-cd4bcbd36164.png)

Expected: node 2022-12-31 is highlighted
Actual: no node is highlighted
![2023-01-15_19,27,07](https://user-images.githubusercontent.com/7197131/212560043-8f711598-ff07-4e06-b4fb-09890fdf38c0.png)

Expected: node 2023-01-01 is highlighted
Actual: no node is highlighted
![2023-01-15_19,26,49](https://user-images.githubusercontent.com/7197131/212560044-603bb5bd-f8c7-43b7-a9f7-d3e239343a09.png)

Just to show that regular text matching works OK
![2023-01-15_19,26,33](https://user-images.githubusercontent.com/7197131/212560045-56819961-a806-4225-9f00-316bef3ef326.png)

[test-filtering-by-date.zip](https://github.com/freeplane/freeplane/files/10420904/test-filtering-by-date.zip)

**Comment by macmarrum** [comment]
Freeplane v1.10.6

**Comment by bepolymathe** [comment]
Thanks @macmarrum for open it 👍🏼

**Comment by dpolivaev** [comment]
Preview 1.11.1_07
