### ISSUE TITLE
Please stop writing and loading unsigned DLL files to/from the Temp folder

### ISSUE THREAD

**Issue by christophvw** [freeplane/freeplane#953]
Please install the Flatlaf DLLs to %ProgramFiles% instead of loading them from a Temp folder.

Possible solution can be found here:
https://github.com/JFormDesigner/FlatLaf/issues/624

**Comment by dpolivaev** [comment]
Thanks for pointing out the problem. 
Unfortunately, I could not understand how to solve it from the discussion link.
Please give me more hints.

**Comment by christophvw** [comment]
Bundle the DLLs with your application, install them to the application folder in %ProgramFiles% and set flatlaf.nativeLibraryPath like [remcopoelstra] described.

[DevCharly] wrote that he plans to change how the DLLs are loaded in a future version:
"... Will also change FlatLaf to automatically load them if they are in the same folder as the JAR (or in ../bin/ ?). This will make the build scripts shorter and it is no longer necessary to set FlatSystemProperties.NATIVE_LIBRARY_PATH. ..."

But he did not say when this will be done.

**Comment by dpolivaev** [comment]
Preview 1.11.1_11
