### ISSUE TITLE
Java issue

### ISSUE THREAD

**Issue by abc16361** [freeplane/freeplane#969]
**Describe the bug**
Just downloaded fp-1.11.1-09, and tested freeplane_bin-1.11.1-alpha-pre09.zip and FreeplanePortable-1.11.1-alpha-pre09.paf.exe. Both of them say " This application requires a Java Runtime Environment 11 - 17 " and fail to activate. Previous 1.11.1.xx run smoothly, so it seems the setting in fp-1.11.1-alpha-pre09 is somewhat different.

**Desktop (please complete the following information):**
 - OS: wins 10
 - Version fp-1.11.1-alpha-pre09
 - Java Version: jdk-17_windows-x64_bin_17.0.3.msi

**Comment by dpolivaev** [comment]
There was an issue with the build process, please try the latest preview versions 1.11.1_09u1
