### ISSUE TITLE
Layout patterns on layout box do not change accordingly

### ISSUE THREAD

**Issue by abc16361** [freeplane/freeplane#971]
**Describe the bug**

After setting different layouts on different node branches, layout patterns on the layout box do not change accordingly if node branches are clicked one by one. It always shows the last set layout. Further, open the box, the layout pattern always stay on the last set pattern. When freeplane is activated and a map is open, it is expected that the layout pattern set on the node selected is shown, but the Node layout just displays the first one. 

**Mind map files**
[fp1-11-1-09u1layout.zip](https://github.com/freeplane/freeplane/files/10537414/fp1-11-1-09u1layout.zip)

**Screenshots**
![LAYOUT_ed](https://user-images.githubusercontent.com/101362122/215527055-0d24ace1-50de-4260-a8f9-9b47b3fb3c72.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version : freeplane_bin-1.11.1-alpha-pre09u1.zip & FreeplanePortable-1.11.1-alpha-pre09u1.paf.exe
 - Java Version: jdk-17_windows-x64_bin_17.0.3.msi

**Comment by dpolivaev** [comment]
preview 1.11.1_10
