### ISSUE TITLE
Freeplane should fold/unfold only visible nodes and their ancestors

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#980]
## Current behaviour
Those functions apply to all nodes on the map, even on nodes that are filtered/not visible. 
![image](https://user-images.githubusercontent.com/10260832/216630059-0f35696e-c17c-45b3-bb73-f72c35126df7.png)

![Video Demonstration](https://user-images.githubusercontent.com/10260832/216643647-ae12ad03-4c08-4737-8733-ff3d58db299a.mp4)

## The problem
* On big maps the user will feel a little delay, when working with those functions.🔴
* If the user removes all filters, he/she will be presented with a messed up map :)🔴

## Improvement proposal
The mentioned functions should ignore invisible nodes.

**Comment by dpolivaev** [comment]
Nice video

**Comment by dpolivaev** [comment]
When level folding or all node folding as on your screenshot is applied, I can limit folding/unfolding to nodes that are either not hidden by the current filter or are ancestors of nodes matching the current filter.

Would it solve your case?

**Comment by dpolivaev** [comment]
Preview 1.11.1_12

**Comment by dpolivaev** [comment]
Fixed in Preview 1.11.1_13, please test it and submit feedback

**Comment by theelectricsoul** [comment]
The correction seems good :) Thank you

But I found other very minor issues.  The behavior, when using those 4 commands, seems inconsistent. I think I should open an extra issue. I will if you need it.

## My expectation as a user
Level 1 cannot be folded when filtering is off. This is the current behaviour. I know it, I like it. 

Also I would expect not to be able to fold nodes that look like Level 1 nodes. For example, if level 1,2,3 is hidden, then level 4 will look like level 1. You will know what I mean below.

## Minor issues based on expectation
**Scenario** ![image](https://user-images.githubusercontent.com/10260832/216848008-8f594280-737a-451b-894e-e27068452074.png)
1. When filtering, I can fold the first node after the root node, which will collapse the whole branch including hidden nodes.! [Video🎬](https://user-images.githubusercontent.com/10260832/216848400-a4c1ddbe-f05a-45e1-a6ff-0f77097ffba1.mp4). This feels inconsistent.
1. When filtering, I can unfold the first node after the root, which will show 2 nodes. [Video🎬](https://user-images.githubusercontent.com/10260832/216848056-767f0521-faa5-4098-9cb0-906b3cec679b.mp4). This feels buggy :)

## Suggestion
1. Do not allow to fold nodes on the visible level 1.
2. Also apply 1. when the command ![image](https://user-images.githubusercontent.com/10260832/216848999-bd79785b-e44b-4305-a710-2b9513f22c0f.png) is in use.

**Comment by dpolivaev** [comment]
I like how you describe your reasons, watching your videos adds clarity.
I do not like the formal use of the structure "as a ... I want ... so that ..." particularly if you write as a user. 
I know you are the user. I just do not like formalities.

**Comment by dpolivaev** [comment]
Your arguments are rather of the kind "I think behavior X is not consistent with my expectations.  I expect X because of ... but observe Y"

**Comment by dpolivaev** [comment]
Preview 1.11.1-14, https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
