### ISSUE TITLE
"Check for udates" command doesn't "see" current stable version

### ISSUE THREAD

**Issue by EdoFro** [freeplane/freeplane#987]
**Describe the bug**
When executing the "**Check for udates**" command, the dialog shows an outdated "Latest version" for Freeplane:

![image](https://user-images.githubusercontent.com/35700575/216980557-40a51ec6-9d56-43c5-8145-b9e71b7c05b7.png)

**To Reproduce**
1. Go to 'Help->Check for updates'
2. Wait for the dialog to open
3. See error

**Expected behavior**
- 'Latest version' should show the last stable version for Freeplane.
- 'View changelog' should download/show its 'history' file
- 'Go to download' should open download page or directly download that Freeplane version

I think the last two points are working today, I just added them, because they are part of the "expected behavior"

**Desktop (please complete the following information):**
 - OS: Win 10
 - Java Version: Java 15

**Comment by dpolivaev** [comment]
Thanks, it was a configuration isssue. Fixed.
