### ISSUE TITLE
Root node's shape is not being inherited correctly

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#992]
# Problem
Root is formatted as a bubble, but the children look like forks :)
See ![Video](https://user-images.githubusercontent.com/10260832/217382064-012a57d9-72ab-4867-ace6-a10fc6416fae.mp4)

![image](https://user-images.githubusercontent.com/10260832/217382434-ab767080-7337-4344-940f-a650e1f73d8f.png)
[New Mindmap.zip](https://github.com/freeplane/freeplane/files/10679935/New.Mindmap.zip)

# Version
1.11.1-pre13

**Comment by dpolivaev** [comment]
Preview 1.11.1-14, https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
