### ISSUE TITLE
Command "Jump in" is forcing a root shape

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#993]
# Problem
Using the command "jump in" will use a oval root shape, ignoring the maps root shape and the selected nodes shape.

As a user I do not want surprise changes to my nodes, especially with a command that is able to focus on subbranches but at the same time changes my design and potentially messes with a clean map.

![See Video](https://user-images.githubusercontent.com/10260832/217384763-15cc79e5-f6c8-4597-8204-d0b07fd06cab.mp4)

![image](https://user-images.githubusercontent.com/10260832/217523352-21b29746-c1ab-4cf7-828d-a21123f2e680.png)

# Workaround
Hard format the affected node with the needed shape.

# Ideas
1. Use the shape of the maps root node.
1. Use the shape of the node that was selected when the command 'Jump in' was invoked.
1. Make it optional how Freeplane behaves with a setting. Create a setting like _'Jump in' inherits shape of selected node_

I prefer 3 :)....  advanced settings ;)

[New Mindmap.zip](https://github.com/freeplane/freeplane/files/10680068/New.Mindmap.zip)
1.11.1-pre13

**Comment by dpolivaev** [comment]
Preview 1.11.1-14, https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
