### ISSUE TITLE
Command "Jump in" is messing with all children node's shape

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#994]
# Problem
See [Video](https://user-images.githubusercontent.com/10260832/217390765-2c217aa7-1d39-4b24-8ac6-944da140f1d0.mp4)

[DashBoard.zip](https://github.com/freeplane/freeplane/files/10680287/DashBoard.zip)

# Workaround
Hard formatting the nodes shape

# Version
1.11.1-pre13

**Comment by dpolivaev** [comment]
Preview 1.11.1-14, https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
