### ISSUE TITLE
Cmd-Shift-B  does not remove the bubble when used on a Bubble

### ISSUE THREAD

**Issue by pedrorolo** [freeplane/freeplane#996]
**Describe the bug**
When selecting a bubble node and pressing Cmd-Shift-B the Bubble node does not cease to be a bubble

**To Reproduce**
1. Open a map
2. Select a node
3. Press Cmd-Shift-B or Ctrl-Shift-B to turn the node into a bubble
4. Press Cmd-Shift-B or Ctrl-Shift-B to removed the bubble of the node

**Expected behavior**
on 4. it would be expected that the node would cease being a bubble, though that does not happen

**Mind map files**
This happens in every mind map

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 13.1 (22C65)
 - Java Version 15.0.8
 - Freeplane 1.10.6

**Comment by theelectricsoul** [comment]
What is the name of the command behind your hotkeys ?

**Comment by dpolivaev** [comment]
Preview 1.11.1-14, https://sourceforge.net/projects/freeplane/files/freeplane%20preview/
