### ISSUE TITLE
Fast workflow: Remove selected nodes from filter/view with one -click

### ISSUE THREAD

**Issue by theelectricsoul** [freeplane/freeplane#998]
# Scenario
I am in a meeting. Brainstorming with colleagues.  I need a clean map without edges crossing each other. In the following screenshot, I want to remove the red marked node with one single click.

![image](https://user-images.githubusercontent.com/10260832/217797561-f65cc3e1-62a6-4add-870c-9866a439eb08.png)

![image](https://user-images.githubusercontent.com/10260832/217793771-77775037-f3e9-4de6-969f-f347967472e6.png)

# Problem
There is no fast one-Click solution for removing this node

# Possible Workarounds
There are three.

1. Unfolding all nodes, etc. etc. see [Video](https://user-images.githubusercontent.com/10260832/217801930-bb0022a2-4fb8-47ad-923d-5ae893ce063f.mp4)
2. Moving the unwanted node around, and maybe later on moving it back.
3. Using the 'hidden node' command, and later on with the need to undo the hiding.

The workarounds are ok when working alone, but not in meetings 🔴

# Request
Allow to remove selected nodes from filter/view with one click.

# Ideas
1. Simulate workaround no. 1.
2. Calling Harry potter ..lol

**Comment by euu2021** [comment]
related discussion is #995

**Comment by dpolivaev** [comment]
Yeah, have you tried View->Hidden node?

**Comment by theelectricsoul** [comment]
Actually....  this low priority. I'll close the request. The maps are usually easy to navigate and filter. There are more important things :)

But yes, I've tried hidden nodes. Sure it does the trick, but it is not a one click solution. And I rather leave a node standing, then fiddling around with it :)

I'll check the scripts provided in the related discussion posted above 

thanks everybody :)
